### ISSUE TITLE
Remove deprecated DeviceProfile.Objects field

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#1007]
Per our discussion with @trcox about device profiles, the [`DeviceProfile.Objects`](https://github.com/edgexfoundry/edgex-go/blob/master/pkg/models/deviceprofile.go#L35) field should be removed as it was deprecated a long time ago.

We should also consider re-naming the [DeviceObject](https://github.com/edgexfoundry/edgex-go/blob/master/pkg/models/deviceobject.go) struct to `DeviceResource`.

**Comment by jduranf** [comment]
If it's fine, I will work on it

**Comment by cloudxxx8** [comment]
If we really remove Object, we might still add a field to put any extendable properties for Device Profile and Device, such as an attribute map

**Comment by tonyespy** [comment]
@cloudxxx8 The `DeviceProfile` field already contains an array of `DeviceObject` structs. The `DeviceObject` struct in turn includes a field called `Attributes` (which is a map).

This issue is solely about getting rid of the `Objects` field, as it's unused per our discussion with @trcox.

If we need to add any new fields to the `DeviceProfile` or `DeviceObject` structs, then please open new issues with detailed use cases.
