### ISSUE TITLE
core-config-seed in Go

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#103]
Review and bring in Samsung initial config-seed in Go project.  Update and apply new config key standards.  Add profile bootstrap property to load only the necessary configuration.

**Comment by Jaewook-Jung** [comment]
Hi, it's Jaewook Jung from Samsung. I updated [core-config-seed-go](https://github.com/mgjeong/core-config-seed-go) repo to apply code file structure and how to build similar to the current edgex-go repo. Please check it.

**Comment by tsconn23** [comment]
The core-config-seed-go repo has been brought over from holding to main. I'm going to close this issue as complete. Issues related to refactoring can be opened and assigned on the new [target repo](https://github.com/edgexfoundry/core-config-seed-go).
