### ISSUE TITLE
Create Registry Abstraction interface and Consul implementation

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#1039]
This creates the abstract interface and the Consul implementation of that interface, but doesn't include modifying services to use the new abstraction.

**Comment by iain-anderson** [comment]
I've put a registry abstraction into the C SDK. Requesting an implementation is done using a URL-like syntax `<implementation-name>://<location>` where `<location>` is usually going to be `<host>:<port>` (but in theory other registry implementations could have their own location scheme).
So consul could be specified by `consul://localhost:8500`
I'm open to changing the above but we should have consistency at least at this level.

**Comment by lenny-intel** [comment]
@iain-anderson I have created a preview PR for the Go Registry Abstraction implementation ([#1084](https://github.com/edgexfoundry/edgex-go/pull/1084)). There I stuck with the existing config.RegistryInfo struct in internal\pkg\config\types.go to configure which implementation, i.e. consul and connection info. Please take a look. Thanks!

**Comment by iain-anderson** [comment]
Looks okay, there's a couple of things we're missing in the C version (config updates, getting endpoints from the registry) that will go on my todo list.
The only thing I'm not keen on is having to go to a configuration file to get the registry connection info etc. If this was done with flags we could avoid having the config file entirely for registry-enabled deployments? That's where I was going with the URL-ish stuff above, so that useRegistry (BoolVar) is replaced by registry (StringVar) with an empty string indicating no registry.

**Comment by lenny-intel** [comment]
All the edgex-micro services use the configuration approach, but the abstraction shouldn't care where the information is coming from as long as it is normalized before receiving it, i.e. it isn't responsible for parsing the URL-ish stuff above and should receive the data in a RegistryInfo struct. @tsconn23 do you agree?

**Comment by iain-anderson** [comment]
Agree that the abstraction should get a RegistryInfo, I just think that if the microservices were able to populate RegistryInfo from flags they could configure entirely from the registry.

**Comment by lenny-intel** [comment]
@tsconn23, I am currently using the config.RegistryInfo and config.ServiceInfo structs from edgex-go internal\pkg\config\types.go as parameters to NewRegistryClient. When I move the code to go-mod-registry these will not be accessible. Thinking that I will have to define new types in go-mod-registry and edgex-go services will have to populate them from their structs or maybe flatten to just be list of function parameters. Thoughts?

**Comment by lenny-intel** [comment]
@iain-anderson, I get where you are going with this. I think that is slightly outside the scope of the Abstract Registry and would have to be agreed to by @tsconn23 and the Core WG to make that happen in the services.

**Comment by iain-anderson** [comment]
ok thanks

**Comment by lenny-intel** [comment]
#1125 completed this task
