### ISSUE TITLE
Export client need refactor configuration reading logic

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#105]
Now it used const hardcode, should read from config file. apply this ticket to fix.

**Comment by drasko** [comment]
Please mark issue relation to service layer (core, support, export, ...) via labels, not an issue title. Use first capital letter in the tiitle.

Closing this one - you do not need an issue for trivial fixes.

**Comment by yanghua** [comment]
@drasko , I do not have permission to mark a issue with label. And there is no issue naming rule document, I remember I have given some suggestion in mailing list recently, but no one gave a reply. In Apache project community, there is a generic conventions: one PR one issue. The issue can create a discuss about a problem. And if the committer think the issue do not need fix or it's not a problem, it would be closed, and the creator would save time in unnecessary issue.
@jpwhitemn I think the issue and PR conventions should be set up as soon as possible.

**Comment by drasko** [comment]
@yanghua you probably got the point there... Let's reopen commits then.

**Comment by yanghua** [comment]
I think the label is a very good practice. But I can not use. I don't know whether it need a setting about this function or not. Or we should consider let newbie know the rule as fast as possible.

**Comment by yanghua** [comment]
@drasko thanks for your suggestion, I have changed these issues' title.

**Comment by yanghua** [comment]
closing this issue, thanks!
