### ISSUE TITLE
Update Device MQTT setup docs to use Go version

### ISSUE THREAD

**Issue by mhall119** [edgexfoundry/edgex-go#1055]
The docs on https://docs.edgexfoundry.org/Ch-ExamplesMQTTDeviceService.html still refer to the old Java version of device-mqtt, they need to be updated to use the new Go version

**Comment by cloudxxx8** [comment]
@weichou1229 will take care of it

**Comment by weichou1229** [comment]
@mhall119 It is duplicated with https://docs.edgexfoundry.org/Ch-ExamplesAddingMQTTDevice.html
