### ISSUE TITLE
Remove old logs

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#1056]
Currently there is no way to remove the oldest logs using a scheduled task. With the events there is the endpoint `/removeold/age/{age:[0-9]+}`, what do you think about implementing the same endpoint for the logs system? If it's fine, I can do that.

**Comment by tsconn23** [comment]
@jduranf Take a look at the discussion here
https://github.com/edgexfoundry/edgex-go/issues/909

I'm personally OK with your suggestion but take the point about persistence to file vs database into account.  In fact, if you want to extend this issue to accomplish the handling described at the end of the above thread for all endpoints in support-logging, that could be helpful.

**Comment by jduranf** [comment]
This modification will not imply any modification in the persistence system, only `internal/support/logging/server.go` will be modified.
