### ISSUE TITLE
Abstraction Layer for Messaging

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1057]
Currently the messaging functionality connecting core-data with export-distro is tightly coupled to ZeroMQ. We need to put this behind an interface and implement with the appropriate type. The initial thought was to do this in a manner commensurate with how we've integrated database providers (interface in the respective service, type in an internal package). However during the Application Services face-to-face in Boston, an additional requirement has become apparent. That is, this same capability needs to be usable by the soon to be created App Services SDK. A discussion was had w/r/t implementing this in an externally usable package or module which would then be consumed by the SDK and edgex-go. Initial thoughts are that this could be hosted within the edgex-go repo at the following location:

/pkg/modules/messaging

The package would contain a go.mod designating it as a module which can be consumed by any number of 3rd party apps/services.

**Comment by lenny-intel** [comment]
Reworked the issues for this effort onto the appropriate repos. The following issues will address this issue:

- edgexfoundry/go-mod-messaging#5
- #1148
- edgexfoundry/app-functions-sdk-go#27
