### ISSUE TITLE
Export distro refactor configuration reading logic

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#106]
Now it used const hardcode, should read from config file. Can I apply this ticket to fix?

**Comment by jpwhitemn** [comment]
This is getting address globally (see https://wiki.edgexfoundry.org/display/FA/Architecture+Issues+and+Decisions#ArchitectureIssuesandDecisions-ServiceIdentifiers).  You can look at core services for the initial implementation.

**Comment by yanghua** [comment]
thanks all of you, closing this issue
