### ISSUE TITLE
Add CPU telemetry retrieved from each service to the metrics handler

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/edgex-go#1078]
* Add metrics (telemetry) retrieved from each service to the metricsHandler in https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/data/router.go

Subtask of #832. Related to #690. Will require #1077 to be complete.

**Comment by brandonforster** [comment]
Complete.

**Comment by tsconn23** [comment]
Which PR is this a part of?
