### ISSUE TITLE
Pass CorrelationID through EventPublisher

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1089]
We need to extend handling of the correlation-id value through the EventPublisher that allows core-data to send events to export-distro. Soon, core-data will also be sent events to other endpoints via pub/sub such as the app-functions-sdk. The event being published needs to retain the correlation-id so that it can be utilized on the subscription side in order to add the value to an HTTP request. For example, in both export-distro and app-functions-sdk, the event can be forwarded onto the next level of processing via HTTP. We need to track this egress from edge-x and log it along with the duration of time taken to obtain a response.

**Comment by rsdmike** [comment]
Hey @tsconn23 just want to clarify, this sounds like it is focused on the existing export distro. Is this intended to include the "Envelope" idea that we discussed at the Boston F2F? Or did you want to create a separate issue for that?
