### ISSUE TITLE
Need a reference implementation for an SMA executor (docker-compose).

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1091]
- We need a reference implementation for an SMA executor. This will be a Docker Compose Executor that, like any other executor maintained by the EdgeX project, will reside in a separate Go repository. 
- As the executor does not need any EdgeX models, libraries, etc. it can stand alone, be managed independently, and be built separately. 
- The only packages that it should need is some type of logging and the Go Lang os/exec package.
- This ties in with: [PR-926](https://github.com/edgexfoundry/edgex-go/pull/926)

**Comment by akramtexas** [comment]
The current (_temporary_) home for this new work is: [docker-compose](https://github.com/akramtexas/docker-compose)

**Comment by anonymouse64** [comment]
> * As the executor does not need any EdgeX models, libraries, etc. it can stand alone, be managed independently, and be built separately.

I disagree, I don't think it should be built separately because the SMA in the default docker distribution is useless without this executable. As such, it should at least be built alongside the SMA in this repo. For simplicity's sake since it's built in edgex-go, the code should probably also live inside edgex-go.

**Comment by akramtexas** [comment]
> > * As the executor does not need any EdgeX models, libraries, etc. it can stand alone, be managed independently, and be built separately.
> 
> I disagree, I don't think it should be built separately because the SMA in the default docker distribution is useless without this executable. As such, it should at least be built alongside the SMA in this repo. For simplicity's sake since it's built in edgex-go, the code should probably also live inside edgex-go.

In turn, I respectfully disagree, and here's my reasoning: We are going to have a hard timing scaling up the `edgex-repo` if we keep adding all kinds of executors right there in the `edgex-go` code-base. By keeping the two separate (physically), we have a much better shot at scalability (of code, at the artifact level, as well as at the runtime footprint level).

**Comment by anonymouse64** [comment]
> We are going to have a hard timing scaling up the `edgex-repo` if we keep adding all kinds of executors right there in the `edgex-go` code-base

I am not saying we should include every possible executor inside edgex-go, but rather the official support distribution mechanisms should be here so that users have a "turnkey" deployment mechanism where they just run docker-compose and the SMA just works out of the box with docker.

For reference, we already will be adding support for the snap executor to edgex-go, so I don't see why we shouldn't add the docker-compose version.

**Comment by jpwhitemn** [comment]
Ian - actually, based on prior discussions of this, I'd like to move all executors external to edgex-go.  These executors could be for different architectures, could be written in different languages, etc.  All executors move external.  This was discussed and agreed upon during January WG meetings.

**Comment by anonymouse64** [comment]
Hi Jim, my apologies for not being able to attend any of the WG meetings in January, but I'd like to revisit this in the WG meeting tomorrow as it has implications for both the docker distribution and the snap distribution that either introduce complex developer work in edgex-go simultaneously with complciated devops work or alternatively produces very bad user deployment situations. 

Furthermore what is the strategy that was decided on to deliver user's a *_usable_* SMA docker container with docker-compose for Edinburgh if this new repo is introduced and isn't included in edgex-go? We already had issues with Delhi and I think we should work to make it easier to deliver a working SMA docker container for Edinburgh not harder.

**Comment by jpwhitemn** [comment]
Yep - on the agenda for tomorrow's discussion Ian.  No apologies necessary as we are all running at 100mph.  In the end, I can be persuaded to move it, but we need to discuss non-go implementations and issue of scale if everyone was allowed to put their implementation in there (similar to issue we have discussed with regard to supporting all database implementations for something like core data).

**Comment by akramtexas** [comment]
- The reference implementation for an SMA executor has since then been moved into the `edgex-go` repository. As such, this issue be closed.
