### ISSUE TITLE
Error in export client documentation for HTTP / REST endpoint setup

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#1092]
As reported by in Slack:  https://edgexfoundry.slack.com/archives/CE4KJ5VV2/p1549639982295400 by Marcelo.

7.9.3.2.2. Setup
Register for JSON formatted data to be sent to a REST address

POST to http://localhost:48071/api/v1/registration
{"origin":1471806386919,"name":"MQTTXMLClient","addressable":{"origin":1471806386919,"name":"EdgeXTestMQTTXMLBroker","protocol":"TCP","address":"m10.cloudmqtt.com","port":15421,"publisher":"EdgeXExportPublisher", "user":"hukfgtoh","password":"uP6hJLYW6Ji4","topic":"EdgeXXMLDataTopic"},"format":"XML","enable":true,"destination":"REST_ENDPOINT"}

**Comment by mhall119** [comment]
It looks like this was fixed in commit e296aeaa46bf14535a693604dccaaf8868c84b03
