### ISSUE TITLE
Can't install snap in Multipass on Mac OS X

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1100]
I am pretty sure this issue is due to the low RAM/ low CPU provided to multipass images by default, but I am unable to install the snap in an Ubuntu Server 16 (classic) image launched with `multipass launch`. What probably happens is that due to low RAM cassandra takes too long to startup and as such the services dependent on cassandra then get failed by systemd and the installation is aborted. 

Mac OS X version:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
```

Representative journal for the multipass instance: [journal.log](https://github.com/edgexfoundry/edgex-go/files/2852205/journal.log)

**Comment by tonyespy** [comment]
I'm closing this as the edgexfoundry snap as of Geneva (or earlier) no longer uses Casandra, and running the snap in a multipass image on MacOS is not a common use case.
