### ISSUE TITLE
Change Device Addressable for More Broad Protocol Support

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1101]
Resulting from the Device Service Working Group call 11-Feb-19

- The [Device](https://github.com/edgexfoundry/edgex-go/blob/master/pkg/models/device.go) struct should contain a map of the properties necessary for connecting to a device. This will be a more flexible structure to connect via any number of protocols rather than overloading a type ([Addressable](https://github.com/edgexfoundry/edgex-go/blob/master/pkg/models/addressable.go)) that is specific to HTTP
- Since the Addressable type will remain for other purposes, the above supporting property should be called `ProtocolProperties` of type `map[string]string`
- The `ProtocolProperties` will be stored as part of the Device document in the database. No sharing is required as in the case of the existing Addressable, thus no requirements for uniqueness.
- Remember to modify the DB storage logic to remove the Addressable mgmt for Devices.

**Comment by tsconn23** [comment]
@SteveOss @tonyespy for visibility

**Comment by SteveOss** [comment]
@tsconn23 Need to remember that a device can support multiple protocol types (e.g. modbus-ip/modbus-rtu) so in terms of modelling a device I think we have (using Thrift as a definition):

struct ProtocolProperty
{
  1: string name;
  2: string value;
}
typedef list <ProtocolProperty> ProtocolProperties;

struct Protocol
{
  1: string type;
  2: ProtocolProperties properties;
}
typedef sequence <Protocol> Protocols;

struct Device
{
  1: Protocols protocols;
}

**Comment by tsconn23** [comment]
This issue is going to get moved to the new https://github.com/edgexfoundry/go-mod-core-contracts repo

**Comment by tsconn23** [comment]
Closing this issue. Moved to core-contracts repo.

**Comment by tsconn23** [comment]
Re-opening issue to track work done within the edgex-go repo itself to support this.
