### ISSUE TITLE
try to use edgex in arm-linux 32bits

### ISSUE THREAD

**Issue by conthing** [edgexfoundry/edgex-go#1114]
What were you trying to achieve?
    A: run edgex in my arm-linux device. first step: just run consul, mongodb, support-logging
What are the expected results?
    A: support-logging can be discovered in the web UI of consul.
What are the received results?
    A: support-logging init with error "error reading from Consul"
![image](https://user-images.githubusercontent.com/46510972/52937176-60e2cd00-3399-11e9-960d-49ff5d018a89.png)
And consul web UI:
![image](https://user-images.githubusercontent.com/46510972/52930005-b0b59a00-3381-11e9-8748-19fe1e98643c.png)

What are the steps to reproduce the issue?
     A:
        go get github.com/edgexfoundry/edgex-go
        make prepare
        make -f arm.mk build
        make sure mongodb is serving
        run consul with command line:  /root/consul/consul agent -data-dir /root/consul/consuldata -server -client=0.0.0.0 -bind=127.0.0.1 -bootstrap -ui -syslog &
       cd cmd/support-logging
       ./support-logging -c 
        ****** arm.mk is a modified makefile target for arm-linux host. The only different between arm.mk and Makefile is:
----------------------------------------------------------------------------
                GO=GOARCH=arm CGO_ENABLED=0 go
                GOCGO=CC=arm-linux-gnueabihf-gcc CGO_LDFLAGS="-g -O2 -L/usr/local/gcc-linaro-arm-linux-gnueabihf-4.8-2013.10_linux/lib/zeromq-4.2.2/release/lib -L/usr/local/gcc-linaro-arm-linux-gnueabihf-4.8-2013.10_linux/arm-linux-gnueabihf/lib -Wl,-rpath-link /usr/local/gcc-linaro-arm-linux-gnueabihf-4.8-2013.10_linux/lib/zeromq-4.2.2/release/lib -Wl,-rpath-link /usr/local/gcc-linaro-arm-linux-gnueabihf-4.8-2013.10_linux/arm-linux-gnueabihf/lib" GOARCH=arm CGO_ENABLED=1 go
----------------------------------------------------------------------------
In what environment did you encounter the issue?
    A: 
        hardware: arm cortex-A7; OS: Ubuntu server 14.04
        And debug support-logging in windows got the same result.
![image](https://user-images.githubusercontent.com/46510972/52937478-288fbe80-339a-11e9-9f10-b3e19688db59.png)

**Comment by anonymouse64** [comment]
How are you running MongoDB on armhf 32-bit?

**Comment by tsconn23** [comment]
The error being shown is most likely a red herring. Mongo isn't officially supported on ARM32, thus ARM32 isn't something ExgeFoundry explicitly supports either right now. Hopefully we'll be able to have full 32 bit support using Redis for the Edinburgh release.
