### ISSUE TITLE
Sending core command API /device/{id}/command/{commandid} with nonexistent device id should return 404.

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1115]
OS version: ubuntu 16.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

Method : GET 
http://35.194.157.122:48082/api/v1/device/a6f928f3-5737-40c5-99e6-0db366c9434d/command/8654ceff-1e66-4b58-b7d7-7c449ad174fc

device id is nonexistent : a6f928f3-5737-40c5-99e6-0db366c9434d

Response 
HTTP/1.1 500
status: 500
Date: Tue, 19 Feb 2019 08:26:50 GMT
Content-Length: 0

Same API with PUT method also returned 500.

**Comment by tsconn23** [comment]
Identified root cause, found in another repo. Created issue.
https://github.com/edgexfoundry/go-mod-core-contracts/issues/8

**Comment by tsconn23** [comment]
@cherrycl PR has been merged. Please verify and close if working as expected.

**Comment by cherrycl** [comment]
@tsconn23  I pulled latest images and verified the issue. The API still returned 500 with nonexistent device id.

**Comment by tsconn23** [comment]
@cherrycl I think you tried too early. The images are built at noon Austin time (CST) and the PR was merged at 4pm Austin time. I think you need to wait until the next publishing cycle.

**Comment by cherrycl** [comment]
> @cherrycl I think you tried too early. The images are built at noon Austin time (CST) and the PR was merged at 4pm Austin time. I think you need to wait until after the next publishing cycle.

Thanks. I will verify it later.

**Comment by cherrycl** [comment]
Verified on latest images, and the issue was fixed.

**Comment by kishcs** [comment]
how to get deviceid for core-command while sending data from rule engine?
