### ISSUE TITLE
Core command is no debug log for debugging

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1116]
OS version: ubuntu 16.04
EdgeX version: 1.0.0
Environment details: Docker container
 
Core command service is no any debug log.

**Comment by tsconn23** [comment]
There aren't any logging statements of level DEBUG in the core-command service, so you won't get any additional output by setting the level that low. If I manually insert one and change the LogLevel setting in the config file, it does get logged.

From local
```
level=INFO ts=2019-02-19T22:18:17.830525Z app=edgex-core-command source=middleware.go:43 correlation-id=cfd7c966-bff0-4527-83fe-76da73922e26 path=/api/v1/device/5c6c6cc4deafc2106784ecc8 msg="Begin request"
level=DEBUG ts=2019-02-19T22:18:26.478498Z app=edgex-core-command source=restDevice.go:110 msg="This should be logged from core-command"
level=ERROR ts=2019-02-19T22:18:29.730208Z app=edgex-core-command source=restDevice.go:111 msg="Item not found"
level=INFO ts=2019-02-19T22:18:31.789758Z app=edgex-core-command source=middleware.go:34 correlation-id=cfd7c966-bff0-4527-83fe-76da73922e26 duration=13.959233483s msg="Response complete"
```
If we had any statements in core-command logged at the DEBUG level, then I would expect the same behavior.

Please close if there is no issue.

**Comment by cherrycl** [comment]
According the above comment, close issue.
