### ISSUE TITLE
Initial EdgeX system management capability

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#112]
Provide initial EdgeX system management features which include a system management API in each micro service and a system management agent to allow translation and EdgeX orchestration of system management operations (like stop, start, restart).  Per https://wiki.edgexfoundry.org/download/attachments/329501/EdgeX%20Foundry%20Micro%20Service%20System%20Management-v5.docx?version=1&modificationDate=1515605688000&api=v2

**Comment by yanghua** [comment]
@jpwhitemn if you are busy, I can help to implement it~

**Comment by akramtexas** [comment]
Making a note of this TODO, thanks! @tsconn23 @jpwhitemn

**Comment by drasko** [comment]
@akramtexas what's the status of this one? If initial implementation is finished (I do not know what's the acceptance criteria), maybe we can close this one and add more specific issues - like "Implement service stop", etc...

**Comment by akramtexas** [comment]
@drasko Your following up is much appreciated. Excellent point: Given that the initial implementation is finished, I have closed out this issue and created a more-specific issue, which is [Issue Number 581](https://github.com/edgexfoundry/edgex-go/issues/581)
