### ISSUE TITLE
How can I get  3rd party / vendor packages?

### ISSUE THREAD

**Issue by PKUZHOU** [edgexfoundry/edgex-go#1135]
Hi
I am new to this project, when I follow the build procedure in ReadMe, I find that `make prepare` command has no longer effects now, so how can I pull the 3rd party / vendor packages such as `github.com/gorilla` ?
Thank you!

**Comment by tsconn23** [comment]
- Install the latest version of Go 1.11.x
- Clone a repo
- Do `make build`
