### ISSUE TITLE
SMA Documentation Link

### ISSUE THREAD

**Issue by rsdmike** [edgexfoundry/edgex-go#1140]
Upon googling "edgex system management agent" i get:

![image](https://user-images.githubusercontent.com/22204562/53597155-ab650600-3b5e-11e9-8dbc-c7e9319e27f9.png)

Which leads me to https://docs.edgexfoundry.org/Ch_SysMgmtAgent.html which is sort of a dead end even though I can see the nav on the left. I think a redirect to https://docs.edgexfoundry.org/Ch-SystemManagement.html or a link in the body, or removing it would be good idea to avoid confusion.

**Comment by mhall119** [comment]
This is being resolved by adding content to this page in issue #1183
