### ISSUE TITLE
go.sum should be committed

### ISSUE THREAD

**Issue by vaind** [edgexfoundry/edgex-go#1141]
currently, the file is in .gitignore but it should be committed
https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

**Comment by tsconn23** [comment]
We won't be doing this at least until the Fuji development cycle as discussed in the DevOps channel a couple weeks ago, as well as on last week's DevOps call.

**Comment by anonymouse64** [comment]
@tsconn23 I wasn't in that devops call, what is the rationale behind not committing the go.sum file?
