### ISSUE TITLE
ProvisionWatcher Can Be Created With Empty OperatingState

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1145]
When creating a new ProvisionWatcher via `http://localhost:48081/api/v1/provisionwatcher` it is possible to do so with an empty OperatingState value. OperatingState should be specified as either `enabled` or `disabled`. If an attempt to create a ProvisionWatcher is made without one of these valid values, a `400 Bad Request` should be thrown.

**Comment by brandonforster** [comment]
I have a fix pending https://github.com/edgexfoundry/blackbox-testing/issues/174

**Comment by brandonforster** [comment]
Should we close this issue and reopen it in https://github.com/edgexfoundry/go-mod-core-contracts? If we want the contract to manage the functionality and not the EdgeX routing logic, that would probably make the most sense.
