### ISSUE TITLE
Rules Engine microservice for raspberry pi

### ISSUE THREAD

**Issue by RoshDevi** [edgexfoundry/edgex-go#1146]
We need image of version of rules engine microservice support for raspberry pi.
Thanks

**Comment by tsconn23** [comment]
The [support-rulesengine 0.7.0](https://github.com/edgexfoundry/support-rulesengine/releases/tag/0.7.0) will run on a Raspberry Pi. If you prefer a docker image for the service, that's found [here](https://hub.docker.com/r/edgexfoundry/docker-support-rulesengine/tags). 

If, however, you are looking for something with a smaller footprint, we do not yet have a replacement for the Drools internals of this service.
