### ISSUE TITLE
When scheduling in progress, PUT method is not working

### ISSUE THREAD

**Issue by RoshDevi** [edgexfoundry/edgex-go#1147]
Hi
We have scheduled modbus event which is performing read operation for every 5sec
At the same time, PUT operation on some of the registers are being performed. But we can observe that modbus communication is not initiated.
Without scheduling operation, we are able to PUT on the modbus registers.

**Comment by tsconn23** [comment]
You would be better served asking about this on [Slack](https://edgexfoundry.slack.com) in the #device-services channel. Also, if you are working from the `master` branch, I can pretty much guarantee this isn't a stable area right now.
