### ISSUE TITLE
Update Export Services docs to include new application functions

### ISSUE THREAD

**Issue by mhall119** [edgexfoundry/edgex-go#1161]
Overviews:
https://docs.edgexfoundry.org/Ch-Intro.html#export-services-layer
https://docs.edgexfoundry.org/Ch-ExportServices.html

Quickstart:
https://docs.edgexfoundry.org/Ch-QuickStart.html#connecting-an-application

API Walkthrough:
https://docs.edgexfoundry.org/Ch-WalkthroughExporting.html

API Reference:
https://docs.edgexfoundry.org/Ch-APIExportServicesClientRegistration.html

**Comment by lenny-intel** [comment]
@mhall119 , the application functions are separate from the export distro so there shouldn't be any updates export distro docs.

**Comment by mhall119** [comment]
@lenny-intel do you think the export-services layer of the architecture documentation needs to be changed? Or would it be enough to just add new documentation about the application functions architecture at the same level a the export-services docs?

**Comment by lenny-intel** [comment]
@mhall119 core-data and export-distro architecture documentation needs to be updated for the new message bus abstraction, but not for app functions. Yes there needs to be new documentation about the application functions architecture at the same level a the export-services docs. @tsconn23 , you agree?

**Comment by tsconn23** [comment]
> Yes there needs to be new documentation about the application functions architecture at the same level a the export-services docs

Agreed
