### ISSUE TITLE
Need documentation for writing new application functions with the Go SDK

### ISSUE THREAD

**Issue by mhall119** [edgexfoundry/edgex-go#1164]
We need a guide to writing a new custom application function for exporting via a new API or format

**Comment by lenny-intel** [comment]
@mhall119 , should this issue be on the app-functions-sdk-go repo?

**Comment by mhall119** [comment]
@lenny-intel no, all of our documentation for docs.edgexfoundry.org is in the edgex-go repo, so the PR to fix this issue would go in here.
