### ISSUE TITLE
Got "500 Internal Server Error" when posting /api/v1/valuedescriptor with duplicate name

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1167]
OS version: ubuntu 16.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. start up EdgeX
2. Post /api/v1/valuedescriptor with the following body which is existed on DB.

> Method: POST
URL: http://localhost:48080/api/v1/valuedescriptor
Body:
  {
  "name":"co2",
  "min":"12",
  "max":"15",
  "type":"F",
  "uomLabel":"degreecel",
  "defaultValue":"0",
  "formatting":"%s",
  "labels":["NHCO2","hvac"]
  }

Actual results: Got return code "500" and  response body "duplicate name for value descriptor: co2".
Expected results: Return code 409 with response body "duplicate name for value descriptor: co2"

**Comment by brandonforster** [comment]
fixed by #1178
