### ISSUE TITLE
Extract getMetrics() and getConfig()-related functionality into a module.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1169]
- The idea behind extracting getMetrics() and getConfig()-related functionality into a module is that, currently, the implementation of getting metrics for a service is duplicated between `edgex-go` and `device-sdk-go`. 
- As recommended by @anonymouse64, it would make our code-base more efficient if we extract these common tasks into another module, which lives independently of `device-sdk-go` and `edgex-go`.

**Comment by jpwhitemn** [comment]
@akramtexas - still a Fuji release item?  Label Geneva?

**Comment by akramtexas** [comment]
@jpwhitemn thanks for catching that 👍

**Comment by shashank-priyadarshi** [comment]
@michaelestrin can please I take this up?

**Comment by cloudxxx8** [comment]
@shashank-priyadarshi thanks for offering, but I just checked the code, and we have completed this issue in the main branch
the logic of config and metrics have both been moved to go-mod-bootstrap
https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/bootstrap/container/configuration.go
https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/bootstrap/container/metrics.go

closing this issue as resolved
