### ISSUE TITLE
Stub Core-Data/AddEvent for CBOR Request

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1170]
We need to provide a stub return value for the Device Service team to make a call from their work in the SDK to Core and obtain some kind of response. Once they are able to do that and obtain the 501 response, we will proceed to implement the actual CBOR handling in the core services.

When receiving a new event, core-data now needs to first look at the incoming `Content-Type` header and make a decision. For this initial issue if the value is `application/cbor` then [this endpoint](https://github.com/edgexfoundry/edgex-go/blob/89c9520f0c9afb3e29b3f0b5e9dcbbb771fd210c/internal/core/data/router.go#L205) should return an [HTTP 501](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501) status code. All other content type values should proceed as handled currently.

Header values can be [obtained](https://golang.org/pkg/net/http/#Header.Get) via the incoming HTTP request. Example: `r.Header.Get(clients.ContentType)`

Constants should be defined in the go-mod-core-contracts module per [this issue](https://github.com/edgexfoundry/go-mod-core-contracts/issues/32) for use. Do not use literal strings for things like the `Content-type` header name or expected value.

**Comment by lenny-intel** [comment]
@tsconn23, I thought that there would already be content type constants in a standard go package like there is for HTTP status codes, but I am not finding any. Should these constants be put somewhere in go-mod-contracts?

**Comment by tsconn23** [comment]
@lenny-intel You might have added your question while I was editing the above issue. Yes, see last paragraph.

**Comment by brandonforster** [comment]
closed via #1176
