### ISSUE TITLE
Add device-virtual guide

### ISSUE THREAD

**Issue by mhall119** [edgexfoundry/edgex-go#1182]
Add a user guide for device-virtual that is similar to the device-mqtt and device-modbus guides.

Also update API documentation for device-virtual if necessary

**Comment by cloudxxx8** [comment]
@FelixTing will take care of it

**Comment by tsconn23** [comment]
Closed based on @mhall119 moving this to "Done" in the above workflow. I don't see a related PR.

**Comment by cloudxxx8** [comment]
@tsconn23 please see this one https://github.com/edgexfoundry/edgex-go/pull/1476
