### ISSUE TITLE
Interlock: Persist Media Type on PropertyValue

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1196]
Tracking the need to persist the MediaType on new ValueProperty location. A PR must be merged to address the issue below first.

https://github.com/edgexfoundry/go-mod-core-contracts/issues/48

Mongo PropertyValue data model located [here](https://github.com/edgexfoundry/edgex-go/blob/7d525f1a1549dede24648221ea74da91be6105b8/internal/pkg/db/mongo/models/deviceprofile.go#L29). Include in mapping to/from contract.

**Comment by tsconn23** [comment]
https://github.com/edgexfoundry/go-mod-core-contracts/pull/52 has been merged so we can start on this. Update the go.mod to pull in the changes.

**Comment by brandonforster** [comment]
closed via #1201
