### ISSUE TITLE
Design the Manifest mechanism of services for the SMA.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1197]
- The SMA will need to be provided a configuration (aka `manifest`) that specifies the list of the services it manages. The manifest will enumerate the services which the SMA is managing, along with details such as are needed to manage any given service. This mechanism is warranted by the need to onboard additional (device) services.
- Essentially, the SMA needs to be made aware of (in the _discoverability_ sense) of services that come online _after_ the EdgeX (core) services have been launched: This, in turn, means some sort of  `manifest` mechanism that provides yet a third way to the SMA to be made aware of (in the _discoverability_ sense) of services, in addition to the existing `Registry` and `configuration.toml`-based workflows.
- Thus, from the perspective of the SMA—and in particular the discoverability aspects—we have in place a check to determine whether the SMA is aware of a given service (via its associated ServiceKey) via a lookup to identify if the ServiceKey is one for which the SMA has a ready-made "client" (referring here to a client that is responsible for mediating between a given service and the SMA). In particular, the SMA simply uses one of the ready-made list of clients that was created at bootstrap, thus using the config that's driven by statically-defined keys (one each for the core services)
- But if a service is unknown to the SMA, the Registry is queried to determine whether it (i.e. the service) is available. And given that the service is unknown to the SMA, the Registry is asked for a ServiceEndpoint associated with that service.
- And this is where the manifest mechanism comes in: The SMA will, at this juncture, lean on the provided configuration (aka manifest) to proceed with servicing the request. (_Dynamic_ generation of the needed config information comes to mind as a possibility, though this may not be feasible for the first pass of a possible implementation.)
- The alternate flow is that, for a service that is known to the SMA, there is no need to ask the Registry for a ServiceEndpoint associated with that service: The SMA simply uses one of the ready-made list of clients that was created at bootstrap, thus using the config that's driven by statically-defined keys (one each for the core services).

**Comment by akramtexas** [comment]
- This really is an overall exercise in `Service Discovery`, and within that is situated the design of a manifest mechanism of services for the SMA. 
- To this end, the following potential use cases have been captured following design discussions:
[SMA File-based Service Discovery.pdf](https://github.com/edgexfoundry/edgex-go/files/3086668/SMA.File-based.Service.Discovery.pdf)
[SMA Registry-based Service Discovery.pdf](https://github.com/edgexfoundry/edgex-go/files/3086669/SMA.Registry-based.Service.Discovery.pdf)
[SMA Manifest-based Service Discovery.pdf](https://github.com/edgexfoundry/edgex-go/files/3086670/SMA.Manifest-based.Service.Discovery.pdf)

**Comment by brandonforster** [comment]
@akramtexas Is this an ongoing concern? Should it be a Geneva work item?

**Comment by michaelestrin** [comment]
I think this is an obsolete issue.  Closing.

**Comment by akramtexas** [comment]
> I think this is an obsolete issue. Closing.

- @michaelestrin That is correct, thanks for closing this issue.
- @brandonforster Thanks for spotting this.
