### ISSUE TITLE
Export services (client and distro) do not have an attribution file

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#120]
License and Attribution files are necessary to satisfying licensing agreements.  The Attribution.txt is missing from export-distro and export-client.  DevOps is working on way to automate the inclusion of these files in deployment artifacts like Docker images.

**Comment by yanghua** [comment]
hi @janko-isidorovic if you are busy and have more import things to do, I can try to finish this work.

**Comment by yanghua** [comment]
@janko-isidorovic if you are busy, I can take this one~

cc @jpwhitemn @drasko and @tsconn23

**Comment by janko-isidorovic** [comment]
Thanks for your help @yanghua , please do so.

**Comment by yanghua** [comment]
@tsconn23 this issue can be closed~
