### ISSUE TITLE
Update to latest go-mod-registry and fix imports

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#1206]
Once PR https://github.com/edgexfoundry/go-mod-registry/pull/6 has been merged,
`go-mod-registry` will have been refactored to conform with using `/pkg` and `/internal` appropriately. This will require some imports and namespace changes.

First update go.mod to pull in latest go-mode-registry
Then update any failing imports and namespaces.

**Comment by brandonforster** [comment]
closed via #1211
