### ISSUE TITLE
Core-Command: Correlation-ID not propagated when issuing command

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1219]
The core-command service invokes commands on a remote addressable using a native http client.

https://github.com/edgexfoundry/edgex-go/blob/65d9a2a4033eb83af861f200106da1aaea6cff03/internal/core/command/device.go#L26

The correlation-id HTTP header is not being passed when these calls are made. The `issueCommand` function needs to have a Context passed into it from which a correlation-id can be obtained and set on the request. Callers to `issueCommand` need to be updated to provide the Context.

**Comment by AnthonyMBonafide** [comment]
@tsconn23 , I am thinking about creating a unit test to cover this newly added functionality. Is this OK or is that getting too granular?

**Comment by brandonforster** [comment]
@AnthonyMBonafide We need more tests, not less.

You're doing the best work.

**Comment by tsconn23** [comment]
@AnthonyMBonafide Go for it

**Comment by AnthonyMBonafide** [comment]
Opened PR #1240
