### ISSUE TITLE
Snap builds broken due to missing device-mqtt-go config file

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1225]
See for example build  https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-master-stage-snap/298/console

```
10:38:17 install: cannot stat './cmd/res/configuration-driver.toml': No such file or directory
```

This is due to https://github.com/edgexfoundry/device-mqtt-go/pull/37 where the file was deleted and it seems (?) the configuration-driver.toml file isn't needed anymore.

**Comment by drensber** [comment]
I'm running into the same issue. Is there a workaround?

**Comment by tonyespy** [comment]
The file was deleted as it's now possible for a device services developer to add driver-specific keys to the base configuration.toml file, the separate file is no longer needed.

**Comment by anonymouse64** [comment]
Actually we need to re-open this and remove the snippet from the install hook that attempts to copy this file into $SNAP_DATA too, as the snap is no longer installable since the file doesn't exit :frowning_face:
