### ISSUE TITLE
Make shell scripts conform to shellcheck

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1227]
There are a number of shell scripts in the repo that have issues as reported by [shellcheck](https://github.com/koalaman/shellcheck).

We should:

1. Fix these issues
2. Integrate the shellcheck program into CI pipelines (probably under `make test` to prevent new issues from being introduced to the project.

**Comment by anonymouse64** [comment]
Note that if we are still considering SonarQube there is a plugin for this: https://github.com/emerald-squad/sonar-shellcheck-plugin

**Comment by tonyespy** [comment]
A lot of these errors were cleaned up recently as part of https://github.com/edgexfoundry/edgex-go/pull/2534, however there are still some remaining warnings. They don't however warrant fixing for Geneva, so I'm removing the release milestone.

**Comment by jpwhitemn** [comment]
Jim Wang has done some shellcheck work with security scripts - but probably needs to be formalized and reviewed globally.
