### ISSUE TITLE
Correlation ID Logging Statements Should be at TRACE Level

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1243]
For now, the community has decided, in the interest of reducing the log content, that correlation ID logging should be done at the TRACE level. This is not at all ideal for a high availability cloud environment, but that is not EdgeX's primary deployment target at the moment. It is understood that with the default log level of INFO, these log statements will not be captured and so may not be available in the case of troubleshooting an error that has already occurred. One would have to modify the LogLevel setting in the configuration and then hope to capture a similar occurrence to see the service interaction accompanying the error.

This should be as simple as changing the calls to LoggingClient in the `OnResponseBegin` and `OnResponseComplete` functions [here](https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/correlation/middleware.go).

**Comment by brandonforster** [comment]
closed via #1250
