### ISSUE TITLE
Allow specifying sub-second schedule frequencies

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1246]
AFAICT, there's no way to create a schedule that has a frequency larger than 1 Hz (i.e. the minimum duration time for scheduled events that are scheduled is 1 second).

This seems to just be a limitation of our implementation of handling ISO 8601 duration spec parsing where we only allow integer time values. The code _could_ be adapted to also allow specifying something like 

```PT0.1S```

which would have a duration of 0.1 seconds and correspond to a frequency of 10 Hz. 

The only part that would need to be changed for this to work would be this function:
https://github.com/edgexfoundry/edgex-go/blob/78ba8bd0017a61459c0f8cd4eb25efb4f917d6ab/internal/support/scheduler/schedulecontext.go#L109-L124

where instead of assuming that the scheduler components are all int64's, we would support parsing decimal fractions too.

**Comment by anonymouse64** [comment]
I see that the device-sdk now supports AutoEvents with simple golang time duration parsing as provided by `time.ParseDuration` and that supports sub-second time durations. 
Perhaps support-scheduler should also switch to supporting simple durations like device-sdk-go rather than using ISO-8601?

**Comment by xmlviking** [comment]
@anonymouse64 I agree I believe the scheduler move towards the ubiquitous time standard used throughout edgex-go and now the device-sdk-go.  ISO-8601 is the original standard we used in the Java version.  It was simply left behind.

**Comment by xmlviking** [comment]
@anonymouse64  - I have moved the frequency validation to using the go lang time parseDuration.  I have a question regarding the Start and Stop DateTime formats.  We are currently using ISO 8601.  Go lang in general supports the RFC versions including straight RFC33339 non Nano.   We have a few options if we desire to change our DateTime format to something more precise.   

**ISO8601** (RFC33339)  "What were doing currently" but parsing it manually not using the Go fmt option with RFC33339. 
Example:
     **RFC3339**     = "2006-01-02T15:04:05Z07:00"

Hashicorp et. al. use the RFC33339Nano 
Example: 
 **RFC3339Nano** = "2006-01-02T15:04:05.999999999Z07:00"

My only issue with this is regarding reproduction of the value after persistence in a data store. 
[Slack Issue RFC3339Nano](https://stackoverflow.com/questions/55251584/can-a-golang-rfc3339nano-timestamp-be-reliably-converted-to-and-from-a-unix-time) 

And finally the [RFC33339](https://www.ietf.org/rfc/rfc3339.txt) 

Eric

Alternatively we could leave the format as it is.

**Comment by anonymouse64** [comment]
RFC3339Nano seems like the way to go to me, I don't see any downsides with it

**Comment by anonymouse64** [comment]
As mentioned in the associated PR,

It seems that we serialize intervals with the ISO-8601 string exactly, which means that we could still implement this change in a backwards compatible manner by doing the following:

- add a new `FrequencyFormat` string to the `Interval` spec (adding new strings doesn't break backwards compatibility for semver)
- if the `FrequencyFormat` key is defined for a given `Interval`, then use that value to deserialize the `Frequency` string into a `time.Duration`
- if the `FrequencyFormat` key is missing or not defined, then assume the format is ISO-8601 and deserialize appropriately

None of these changes would break an existing installation, though note I am assuming that mongo/redis can handle a new key added to a struct when serializing it.

**Comment by xmlviking** [comment]
@anonymouse64 

I will start looking into this.  If it appears to not be overly fragile I will go ahead and implement the deserialization format check etc...

**Comment by xmlviking** [comment]
@anonymouse64 - sorry got a bit side tracked with some other stuff I will get this done and have a PR for you monday :)

**Comment by michaelestrin** [comment]
Closed for lack of activity.
