### ISSUE TITLE
Create Blackbox Tests for the SMA.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1251]
- We want to have a set of ready-to-run Blackbox Tests to catch regression bugs for the SMA.

**Comment by tsconn23** [comment]
@akramtexas Would you mind moving this issue to the blackbox-testing repo so we can track it there? Thx.

**Comment by akramtexas** [comment]
@tsconn23 Done. 
- Yep, the blackbox-testing is _indeed_ the right spot for this issue 👍 
- Closing this issue and created [Issue-204](https://github.com/edgexfoundry/blackbox-testing/issues/204) in lieu, thanks.
