### ISSUE TITLE
Pare down logging for the docker-compose reference implementation.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1266]
- We need to enable the Docker-in-Docker solution to deploy and function properly in a containerized environment. 
- For this, we need to pare down logging for the docker-compose reference implementation of the **system management executor** (aka `sys-mgmt-executor`) because, while the facilities for logging are available to **edgex-go** services in general, `sys-mgmt-executor` is a _standalone, bare-bones executable_ for which it does not make sense to pull in the machinery for initializing full-blown logging as we do for other services proper; instead, we are paring down to lean (built-in golang) logging.
- Specifically, when an attempt is made to use full-blown logging, the following (as an example) ensues, with main.go:74 referring to the first instance of (un-initialized) instance of LoggingClient:
```
bash-4.4# ./sys-mgmt-executor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x85b13b]

goroutine 1 [running]:
main.main()
        /go/src/github.com/edgexfoundry/edgex-go/cmd/sys-mgmt-executor/main.go:74 +0x7b
bash-4.4# ./sys-mgmt-executor edgex-core-data stop
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x85b13b]
```

**Comment by anonymouse64** [comment]
The other way you could solve this is by initializing `LoggingClient`, no?

**Comment by akramtexas** [comment]
> The other way you could solve this is by initializing `LoggingClient`, no?

@anonymouse64 Yep, thanks, that is indeed the approach I'm currently implementing.
