### ISSUE TITLE
When a DeviceProfile is Deleted, Delete Devices and Commands

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1273]
The idea is that when a DeviceProfile is deleted, there should not be any lingering devices and their associated commands. In practice, we will probably want to ensure that a DeviceProfile cannot be deleted until all Devices have been deleted through a separate call or process. The effect of cascading a DeviceProfile delete is too significant. 

Still we want this as a requirement.

**Comment by michaelestrin** [comment]
Closed.  Believe this to be addressed by https://github.com/edgexfoundry/edgex-go/pull/1496.
