### ISSUE TITLE
Remove "prepare" target from Makefile

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1275]
The "prepare" target in the Makefile is no longer used. We should remove it. Confirm with the DevOps team prior to removal that their JJB scripts no longer call this.

**Comment by mhall119** [comment]
This has already been removed from the documentation instructions as well

**Comment by jamesrgregg** [comment]
@tsconn23 there should be no issue with removal of the "prepare" target from Makefile

**Comment by anonymouse64** [comment]
Removing the target will break the snap build, but I can submit a PR to remove the call to `make prepare` from the snap build
