### ISSUE TITLE
mqtt export needs QoS , autoreconnect and retained flag to be configurable

### ISSUE THREAD

**Issue by freedreamer82** [edgexfoundry/edgex-go#1276]
Hi,

In my opinion the mqtt export service needs the QoS, autoreconnect and retain flag (but also others , see https://github.com/eclipse/paho.mqtt.golang/blob/78406c8b51ca579deb2517931e8812869064b78b/options.go ) to be configurable when a client is registered.
I can make a pull request but before I would like to discuss with someone what should be the right way to implement it.

type mqttSender struct {
	client MQTT.Client
	topic  string
        autoreconnect bool
        qos    int
        retained  bool
}

token := sender.client.Publish(sender.topic, sender.qos, sender.retained, data)

I was thinking something like that : modding the mqtt part is pretty simple but remains the issue how to pass the parameter.
I wanted to put the new info in the raml file for export service but i'm not sure if it is the right place

https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/export-client.raml

maybe should be better to pass a generic key-value for options in order to be agnostic from the service
when registering a client I have been thinking something like this :
 PUT to http://localhost:48071/api/v1/registration
{{"name":"MQTTClient","compression":"NONE", options: { "autoreconnect" : "true" , "qos" : "1"  , }  .....

what do u think ?

Marco

**Comment by tsconn23** [comment]
Export-services will be deprecated after Edinburgh in favor of application services. Not going to make this a priority.

**Comment by freedreamer82** [comment]
yes thanks , I already made a PR in application services according to this.
I close it.

Marco
