### ISSUE TITLE
Update snap build documentation

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1282]
```
Fetched 43.1 MB in 6s (4167 kB/s)                                                                                                                    
Failed to fetch stage packages: Error downloading packages for part 'cassandra': The package 'openjdk-8-jdk' was not found..
```

**Comment by anonymouse64** [comment]
Hi! If you are building the snap on an linux distribution other than Ubuntu 16.04, you will need to build it with lxd using `snapcraft cleanbuild` (see the readme: https://github.com/edgexfoundry/edgex-go/tree/master/snap#building-with-lxd-containers). I haven't tried this on 19.04 yet, but the following should be sufficient:

```bash
$ snap install snapcraft --classic
$ snap install lxd
$ sudo lxd init 
...
$ git clone github.com/edgexfoundry/edgex-go
$ cd edgex-go
$ snapcraft cleanbuild 
```

Note that you don't need to clone edgex-go in your $GOPATH, though it will work if you've got it there as well.


I do see however that the link we have in the readme is out of date and is 404 right now so we should update the readme at the very least.

**Comment by anonymouse64** [comment]
It seems the new link is https://docs.snapcraft.io/build-on-lxd/4157 and actually the recommendation is to use:
```bash
$ export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
$ snapcraft
```

**Comment by bnevis-i** [comment]
Revised (envvar procedure) having different effect.  Need to fight Internet proxy and will update.

**Comment by anonymouse64** [comment]
We will update the documentation on how to build the snap as per the new snapcraft 3.X handling from this issue: https://github.com/edgexfoundry/edgex-go/issues/888
