### ISSUE TITLE
Interlock -- Consume Latest Core-Contracts for Unmarshal Bug Fix

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1292]
See original issue here
https://github.com/edgexfoundry/go-mod-core-contracts/issues/80

There's a bug in the unmarshaling of event readings whereby the value is being dropped. Once the relevant PR is merged for the above bug fix, it should be consumed ASAP in edgex-go.

**Comment by brandonforster** [comment]
closed via #1293
