### ISSUE TITLE
Add support for services to notify systemd socket when ready

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1301]
After a service has finished it's initialization, it would be nice if the service could mark itself as ready to systemd using the standard notify socket - this would facilitate more efficient service initialization because then we would only start services after their dependencies are actually initialized. For example, we wouldn't start a device service until after core-data, core-metadata, etc. are fully initialized.

Note that this only would apply to deployment scenarios where systemd is the orchestrator, such as the snap or manually writing systemd units.

Also note that this can be done entirely in the std library by writing `"READY=1"` to the unix datagram socket identified by `$NOTIFY_SOCKET`, and that if `$NOTIFY_SOCKET` isn't defined or is empty then we wouldn't do this at all and would run as we currently do.

See https://github.com/hashicorp/consul/blob/master/agent/systemd/notify.go for an example of how this could be done and http://manpages.ubuntu.com/manpages/bionic/man5/systemd.service.5.html for an explanation of how systemd notify units work

**Comment by anonymouse64** [comment]
Additionally, it would be nice if the ports that services listen on could be inherited from systemd when the services are managed by a systemd unit. That would involve code in edgex-go that checks if the service is running as a systemd service, and if so, receive file descriptors from systemd socket using [`sd_listen_fds`](https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html#) (there can be multiple socket file descriptors that systemd opens for the service).

Finally, it would also be useful if services had the option of listening on unix sockets in addition to or in replacement of TCP sockets. This would implement additional security for the services and prevent needing to setup firewall rules for devices, as no packets would ever hit the NIC when services on the same device need to talk to each other and would otherwise work exactly the same as normal TCP sockets. Unix sockets can also be inherited from systemd with `sd_listen_fds`.

**Comment by anonymouse64** [comment]
A good reference for how to do this from Go with the coreos/systemd library is here: https://vincent.bernat.ch/en/blog/2018-systemd-golang-socket-activation

See also the examples at https://github.com/coreos/go-systemd/tree/master/examples/activation

**Comment by cloudxxx8** [comment]
@farshidtz do you have any comment for this issue?  should we still keep it opening?

**Comment by jumpingliu** [comment]
close this issue due to no further investigation
