### ISSUE TITLE
Parsing start/end time error when post /api/v1/interval

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1308]
OS version: ubuntu 18.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. start up EdgeX
2. Post /api/v1/interval with the following body.

Method: POST
URL: http://localhost:48085/api/v1/interval
{
            "name": "noon",
            "start": "20180101T000000",
            "frequency": "P1D",
            "origin": 0
}
Actual results: Got return code 400 with message "error parsing Start strconv.ParseInt: parsing "20180101T000000": invalid syntax".
Expected results: According to the [interval.go](https://github.com/edgexfoundry/go-mod-core-contracts/blob/65beb1e99b0216ab0484907a7783b268ade78540/models/interval.go#L48), "**20180101T000000**" should be correct format.

Please correct me if I misunderstood. 
This issue caused all scheduler testcases failure.

**Comment by xmlviking** [comment]
I will review this and see what I can see :) . I will get back to you on this.

**Comment by tsconn23** [comment]
@xmlviking Any updates?

**Comment by cloudxxx8** [comment]
@xmlviking may I have the status of this issue?  thanks.

**Comment by tsconn23** [comment]
@cloudxxx8 We merged a PR for this issue yesterday https://github.com/edgexfoundry/go-mod-core-contracts/pull/102 and the dependency was consumed in edgex-go https://github.com/edgexfoundry/edgex-go/pull/1343

I'm unclear if that's all the work that's required here. @jdharms Please verify / confirm whether additional action is necessary to resolve these test failures.

**Comment by jdharms** [comment]
@cloudxxx8 @tsconn23 The PR @tsconn23 linked along with https://github.com/edgexfoundry/developer-scripts/pull/110 fixes all support-scheduler blackbox tests as far as I am aware.  I believe the PR in developer-scripts isn't needed for the automated blackbox tests (they should be working currently).

**Comment by tsconn23** [comment]
@cloudxxx8 @cherrycl Please verify. If it works, close the issue please.

**Comment by cherrycl** [comment]
This issue was fixed.
