### ISSUE TITLE
Replacing the fmt.Println code with log framework api for the whole project.

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#131]
If agree this ticket, I could fix it.

**Comment by drasko** [comment]
OK for me, but let @jpwhitemn or @tsconn23 confirm.

**Comment by yanghua** [comment]
@jpwhitemn and @tsconn23 , what's your opinion?

**Comment by tsconn23** [comment]
Can you provide a specific example of the usage you want to replace and the specific proposed change? We may want to handle this as more of a style guideline with issues sent to the specific teams responsible for their portion of EdgeX.

**Comment by yanghua** [comment]
@tsconn23 there are many examples, such as [print error](https://github.com/edgexfoundry/edgex-go/blob/master/core/clients/metadataclients/metadata-clients.go#L169), [print debug](https://github.com/edgexfoundry/edgex-go/blob/master/core/clients/metadataclients/metadata-clients.go#L270), [print error](https://github.com/edgexfoundry/edgex-go/blob/master/core/data/init.go#L80), [print info](https://github.com/edgexfoundry/edgex-go/blob/master/cmd/support-logging/main.go#L54) and so on. I agree with you, the log level should be decided by the specific teams(maintainer). However, currently we could do some common refactor. For example we could replace this mode : 

```go
if err != nil {
  fmt.Println(err.Error())
}
```
with : 

```go
if err != nil {
  logger.Error(err.Error())
}
```

The reason about replacing the print code is that we should unified log output format and code style.

**Comment by tsconn23** [comment]
@drasko Just to clarify, are you agreeing with me or with yanghua's approach to introduce the logger everywhere including packages where it may not be referenced yet?

**Comment by yanghua** [comment]
@tsconn23 consider a scenario, if a module which used `fmt.println` to print a error message to std out.  But the log framework configuration tends to log the message into a file. In this case, the system's log is incomplete and would stop developer making diagnosis about issues.

I think import a logger package is not the core problem. Maybe it do not need a logger (for example just print to std out now), but it would need logger, especially in complex production and distributed environment.

**Comment by drasko** [comment]
@tsconn23 - I would go tith @yanghua's proposition for now - looks simpler to me (pure change)

**Comment by drasko** [comment]
@yanghua @tsconn23 yep, this "stdout logger" does not mean anything - in production logs would be sent directly from logger to `syslog`, some file or - most probably - a remote machine. This is why I insisted from the start on removing pritfs and using logging.

**Comment by tsconn23** [comment]
@drasko @yanghua And so the error gets logged from the metadataclient, thrown to the caller and then relogged again there? That's what will happen in the scenario I described above.

**Comment by yanghua** [comment]
@tsconn23 for your scenario, if logs multiple times, that's the exists code's issue, if replaces with logger would log multiple times, the print to console would also print multiple times, because the logger just replaced the action of print. I think it could be split into two issue: 

1) replace the exists log mode (from println to logger), this action would not change the original's semantic and behavior around the code context, and it assumes the exists semantic is reasonable;
2) after replacing done, we could make a review and evaluate those reasonableness in the context and call chain;

so, I think your scruple about that scenario belongs 2).

**Comment by drasko** [comment]
@tsconn23 @yanghua this is what I though also - just to replace fmt prints as a first step. Then address architectural issues as a second step (separate issue)

**Comment by drasko** [comment]
@yanghua any updates on this?

**Comment by yanghua** [comment]
I no more want to say. Does it mean you guys agree with this issue and I can start the work in this case?

**Comment by yanghua** [comment]
in process of this issue.

**Comment by yanghua** [comment]
except `support-logging` and `support-logging-client`, all others `fmt.Println` has been replaced. cc @drasko please review it.

**Comment by drasko** [comment]
Reviews done, please push PR

**Comment by jpwhitemn** [comment]
All - thank you for your comments here and I thank each of your for your continued participation in the project.  On this issue, however, I believe we need to work through the core working group to discuss before trying to implement.  The comment section here allows us to get some initial ideas and conversation going, but clearly there are alternate options and opinions that really should be brought up before a larger audience and then implemented consistently across all services.  These are the types of issue that are really appropriate for working group weekly meetings.  I've asked Trevor @tsconn23 to prepare this a part of an upcoming Core WG discussion so we can reach a majority consensus.

**Comment by yanghua** [comment]
@jpwhitemn OK, sounds good. actually, I think it's a generic specification, just like replacing `System.out.println` to log4j/slf4j framework.
