### ISSUE TITLE
Query transmission by limit does not work

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1312]
OS version: ubuntu 18.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. Start up EdgeX
2. Import transmission data with 10 records.
3. Get /api/v1/transmission/end/{{endDate}}/{{limit}}.

Method: Get 
Import 
URL: http://localhost:48060/api/v1/transmission/end/{{current timestamp}}/2.

Actual results: More than 2 records had queried.
Expected results: Only 2 records had queried.

All of transmission APIs with limit have the same problem.

**Comment by akramtexas** [comment]
@cherrycl I will be in touch shortly ✅

**Comment by akramtexas** [comment]
@cherrycl I am unable to recreate this issue (Investigating a bit further...)

**Comment by cherrycl** [comment]
@akramtexas I created another issue #1316.  If the resendcount of transmission is > 1, the data can't be queried. I am not sure if this is why you are unable to recreate this issue.
You can also run the transmission testcases of blackbox testing to recreate this issue.

**Comment by akramtexas** [comment]
I am unable to recreate the reported scenario.

**Comment by cherrycl** [comment]
@akramtexas May I know how many records you received, if you importing 10 records and set the limit to "2". Please also make sure the resendcount is "1" or "0" on all of imported records.

**Comment by tsconn23** [comment]
@cherrycl As I mentioned on #1316 `limit` in this case is `resendLimit`. So the above endpoint is actually returning results where the resendLimit < 2 and not limiting the result count to 2. Here's the query driving this endpoint.

`https://github.com/edgexfoundry/edgex-go/blob/eec8e1f3ce6d9a9c8c1e1098fbe9df49c355ee97/internal/support/notifications/rest_transmission.go#L198`

I find the dual-purpose usage of `limit` to be confusing. In the `transmission` endpoint it apparently  means something different than everywhere else.

**Comment by akramtexas** [comment]
@tsconn23 Thanks for that observation and clarification 👍 
@cherrycl I trust that this answers your question ✅

**Comment by cloudxxx8** [comment]
please see my comment on https://github.com/edgexfoundry/edgex-go/issues/1316 for the `{limit}` explanation

**Comment by tsconn23** [comment]
Closing. Replacing with https://github.com/edgexfoundry/edgex-go/issues/1338
