### ISSUE TITLE
Subscription PUT request not update as expected, still using the old value instead

### ISSUE THREAD

**Issue by lindseysimple** [edgexfoundry/edgex-go#1313]
- Reproduce step:
Send a request body to the subscription PUT request `http://localhost:48060/api/v1/subscription`, got 200 OK, but the value was not updated as expected.

- Expected result:
The subscription record should be updated successfully with the new value sending in the request body.

- Actual result:
Got 200 OK response, but the value remains the same, not modified as expected as in the request body.

Tracing the code in https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/notifications/rest_subscription.go
```
case http.MethodPut:
		var s models.Subscription
		dec := json.NewDecoder(r.Body)
		err := dec.Decode(&s)
...
		if err = dbClient.UpdateSubscription(s2); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			LoggingClient.Error(err.Error())
			return
		}
```
Looks like this line should use `dbClient.UpdateSubscription(s)` instead to avoid updating the DB using the old value.

**Comment by akramtexas** [comment]
@lindseysimple I will be in touch shortly ✅

**Comment by akramtexas** [comment]
- On sending a request body to the subscription PUT request http://localhost:48060/api/v1/subscription, I get an HTTP 404 status (Investigating further...)

**Comment by akramtexas** [comment]
@lindseysimple I ran into the scenarios (in trying to recreate this issues) where the collections test data (in Postman) is not setting data up in a way that would help recreate the reported scenario. So I had to tweak the test data, after which I _**was**_ able to recreate issue.
```
- I have implemented a fix, and will be submitting PR for review shortly...

**Comment by lindseysimple** [comment]
@akramtexas Thanks for the update! Look forward for the fix.
