### ISSUE TITLE
Created field of transmission has updated "0" after status changing to "ESCALATED"

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1315]
OS version: ubuntu 18.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. Startup EdgeX
2. Create a subscription.
3. Create a critical notification by following API.
Post /api/v1/notification.

> Method: POST
> URL: http://localhost:48060/api/v1/notification
> {
>     "slug": "notice-0012",
>     "sender": "System Management",
>     "category": "HW_HEALTH",
>     "severity": "CRITICAL",
>     "content": " [ WARNING ] Room's temperature is 103 °F , it's over upper limit 100 °F.",
>     "labels": [
>         "room",
>         "temperature"
>     ]
> }

Actual results: 2 transmisstion records are created with failed status, and the created field displayed correctly. For a while, the status of both records are updated to ESCALATED, then created field is updated to 0
Expected results: The created field should not be changed.

**Comment by tsconn23** [comment]
Unable to duplicate using `master` branch running natively. Unsure where the docker container referenced above is sourced from.

1.) Created subscription both individually using the `"name": "Create a subscription"` test and also via the importer collection
2.) Ran the POST with body specified above.
3.) One record created, shown below.

`{ "_id" : ObjectId("5cd5e80ddeafc27f91d6e39d"), "created" : NumberLong("1557522445096"), "modified" : NumberLong("1557522445097"), "origin" : NumberLong(0), "uuid" : "6d40816c-e11f-4f66-a07e-fc6ab7b46c0e", "slug" : "notice-0012", "sender" : "System Management", "category" : "HW_HEALTH", "severity" : "CRITICAL", "content" : " [ WARNING ] Room's temperature is 103 °F , it's over upper limit 100 °F.", "description" : "", "status" : "PROCESSED", "labels" : [ "room", "temperature" ], "contenttype" : "" }`

**Comment by cherrycl** [comment]
@tsconn23 The created field displayed "0" is not in notification data, but **transmission** data. After posting critical notification, transmission records will auto-created. 
DB screenshot is attached for your reference.
![image](https://user-images.githubusercontent.com/41656797/57609513-9e728300-75a1-11e9-8296-d8956ee0f19b.png)

**Comment by tsconn23** [comment]
@cherrycl OK, thanks for the clarification. See associated PR.
