### ISSUE TITLE
Post notification API should return id when 202 Accept

### ISSUE THREAD

**Issue by lindseysimple** [edgexfoundry/edgex-go#1329]
###  Description
Currently the post notification/subscription API will return the `slug` value after successfully created a new notification/subscription.

### Expected
The **`id`** value should be returned instead of the **`slug`** as the user already has the slug value, also to be in consistent with other POST API in the EdgeX services.

**Comment by cloudxxx8** [comment]
slug is something user has already known, so we had better return id for creation to be consistent with other services

**Comment by cloudxxx8** [comment]
RAML should also be modified if we accept this change
https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/support-notifications.raml#L864-L869
