### ISSUE TITLE
Get Transmission by slug REST API enhancement suggestion

### ISSUE THREAD

**Issue by lindseysimple** [edgexfoundry/edgex-go#1335]
#### Suggest to add  new `/transmission/slug/{slug}/start/{start}/end/{end}/{limit}` API
The `/transmission/slug/{slug}/{limit}` GET API can only fetch the MaxLimit number of transmissions by specific Notification slug, which is unable to fetch large scale transmission data for a given slug.

Suggest to add a new `/transmission/slug/{slug}/start/{start}/end/{end}/{limit}` API so that user can query transmission data for a given slug by time range, to support large scale transmission data query for the specific Notification slug

**Comment by tsconn23** [comment]
@lindseysimple No promises on this for Edinburgh. Also, be advised that we are discovering `{limit}` has a different meaning under the transmission endpoint than everywhere else in the system. @cherrycl has more details.

**Comment by cloudxxx8** [comment]
@tsconn23 if you accept this API extension, could you please assign this issue to me?  We are making this request because we thought the GUI for Transmission needs this API to present the correct information for large scale.

**Comment by tsconn23** [comment]
@cloudxxx8 Assigned to you. Obviously, needs to be done quickly for inclusion in Edinburgh. I am assuming you'll also oversee any additions in the blackbox tests.

**Comment by weichou1229** [comment]
@tsconn23 PR is ready.
