### ISSUE TITLE
Supplement Unit Testing for the SMA.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1344]
- Increase code coverage by supplementing unit testing for `system management`.

**Comment by anonymouse64** [comment]
It would also be good to have unit tests for the functionality in the sys-mgmt-executor, however that would likely require some refactoring to handle mocking running the `docker` command

**Comment by akramtexas** [comment]
> It would also be good to have unit tests for the functionality in the sys-mgmt-executor, however that would likely require some refactoring to handle mocking running the `docker` command

Good feedback @anonymouse64, thanks. I was giving thought to exactly that and, given that it will require some refactoring, as you rightly point out, decided to defer the refactoring-related work to the Fuji release 👍
