### ISSUE TITLE
Implement Redis Override in Config-Seed

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1347]
For the Edinburgh release, we need a way to seed Consul with Redis connectivity configuration via docker-compose. The proposal is to add a cmd line flag such as 

```
--database=redis
-d=redis
```

The default value would be `mongo` for now. If this flag is set then right before config-seed puts the configuration into Consul, the Port and Type properties of the primary database configuration should be set to

```
Port=6379
Type=redisdb
```

Adding this flag will allow us to override the default Docker entrypoint for the config-seed from a docker-compose file using a `command` parameter. ([see here](https://docs.docker.com/compose/compose-file/#command))

Example usage from our security docker-compose file is [here](https://github.com/edgexfoundry/developer-scripts/blob/605ce7474e3372a562427fb7bb28f74a6e79d262/compose-files/security/docker-compose-delhi-0.7.0.yml#L106)

**Comment by anonymouse64** [comment]
Why isn't it enough to simply have different config-seed read different config files for redis vs mongo? That's how I've been handling it in the snap is just by automatically changing the config files to use redis and then running config seed with the config files again.

**Comment by tsconn23** [comment]
We could but we would need to publish a separate Docker image then, and I'm trying to come up with a solution that doesn't put more work into the DevOps pipeline at the last minute.

**Comment by anonymouse64** [comment]
As recommended in the PR, I think a cleaner solution to this short-term would be to have a different set of configuration files specific to redis in the container and then in docker-compose for redis override the arguments to config-seed to specify the folder for redis configuration files instead of the mongo configuration files

**Comment by tsconn23** [comment]
1.) That would require duplicating all of the configuration.toml files in all services with the only difference in them being the Database/Type and Port. These would then be copied into the config-seed image to support the use case, but wouldn't ever be used directly by the individual services -- which is confusing. In the proposed PR the variation is encapsulated and managed completely within the config-seed.
2.) Since "profile" is already used as a command line flag and maps to subdirectories within the `./res` folder, we can't put these in a new directory so we'd need to name them accordingly -- something like `configuration_redis.toml`
3.) We would still need command line flag support for config-seed.

Since #3 is needed regardless, the solution can be refactored after Edinburgh without breaking backward compatibility.

**Comment by anonymouse64** [comment]
Why do you need additional command line flag support for config-seed? You already have this with the `--confdir` and `--profile` options. I imagine you would just do something like:

config-seed dockerfile:
```dockerfile
ENTRYPOINT bin/config-seed
CMD --cmd /config -confdir /config/config-seed/res --props /config/config-seed/res/properties

```

mongo compose (i.e. default):
```yaml
  config-seed:
    image: edgexfoundry/docker-core-config-seed-go:0.7.1
    container_name: edgex-config-seed
```

redis compose:
```yaml
  config-seed:
    image: edgexfoundry/docker-core-config-seed-go:0.7.1
    container_name: edgex-config-seed
    command: ["--cmd" "/config-redis" "-confdir" "/config-redis/config-seed/res" "--props /config-redis/config-seed/res/properties"]
```

(note that this isn't exactly the same as the current `/edgex/cmd/...` directory structure, but you should get the idea from above)

This way the only thing you need to change for Edinburgh is to create additional configuration.toml files in the docker container - you don't even have to commit them to edgex-go, you could easily generate them using the mongo ones in edgex-go during the docker image build process.

Regarding 2, AFAICT none of the services ever use the configuration files from config-seed currently when using docker, they all use consul? How would it be different to have additional files in the config-seed image?

**Comment by tsconn23** [comment]
> Regarding 2, AFAICT none of the services ever use the configuration files from config-seed currently when using docker, they all use consul? How would it be different to have additional files in the config-seed image?

If you look [here](https://github.com/edgexfoundry/edgex-go/blob/196b10d88770176563ec93fb5345d4e7c417f58c/cmd/config-seed/Dockerfile#L57), you can see that ALL of the service config files are copied into the config-seed image. The issue isn't the config-seed's configuration. The approach above would require a duplicate config file for all services, as I was saying above, which would only be used for this operation. This is because config-seed uses each individual service config to populate Consul. As said above, I'm not going to create a directory for Redis because sub-directories inside of `./res` already map to the `profile` flag. Thus I would have to create a `configuration-redis.toml` for each service with only two values being different which seems inefficient to me. And in order to tell config-seed to read that file, I would need to hand it some kind of new parameter anyway.

I think we're going to have to agree to disagree here.

**Comment by tsconn23** [comment]
Also remember that the solution has to work in a situation where the services are deployed natively (no Docker) and using Consul.

**Comment by anonymouse64** [comment]
> in order to tell config-seed to read the correct file I would need to hand it some kind of new parameter anyway.

I don't think this is true, I think the combination of the `-profile` and `-confdir` options in edgex-go right now are sufficient to solve this. If you still don't understand how to use this from my above examples perhaps as you say I should just submit an PR to explain how those options can be used. I had hoped the Dockerfile and docker-compose snippets above would be sufficient to see how this would work.

To your other point, yes the other service config files in the config-seed container would be duplicated, but I just checked and it's only ~9 KB for all the configuration.toml files in the docker folders:
```bash
$ for f in $(find $(pwd)/cmd -name configuration.toml | grep docker/configuration.toml); do ls -l $f | awk '{print $5}'; done | paste -s -d+ - | bc
9317
```

Personally I think having 1 container be 9 KB larger is better than adding a flag like this.
