### ISSUE TITLE
 References to glide in Ch-GettingStartedSDK-Go.html need to be replaced with those for go modules

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1358]
# 📚 Docs or Wiki Bug Report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://docs.edgexfoundry.org/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by mhall119** [comment]
This should have already been done in the `master` branch, can you tell me where you're still seeing it?

**Comment by mhall119** [comment]
Ah, just realized this issue is older than the fix, so nevermind.
