### ISSUE TITLE
MIME types should not be case-sensitive

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/edgex-go#1379]
ie, the value of the Content-Type header.
For example, in the current code a Content-Type of "Application/CBOR" is not recognized as indicating CBOR encoding.
Easiest fix is probably to do ToLower() on the incoming value.

**Comment by iain-anderson** [comment]
[https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7](url) applies?

**Comment by tsconn23** [comment]
Are you asking for this change in Edinburgh or Fuji?

**Comment by iain-anderson** [comment]
Fuji. As far as I am aware it's not actually blocking anything at the moment.
