### ISSUE TITLE
Email notification should allow sending to non authenticated smtp servers 

### ISSUE THREAD

**Issue by adam-intel** [edgexfoundry/edgex-go#1382]
If the smtp.Password is empty don't assume the authentication type is smtp.PlainAuth() just use nil instead.  

https://github.com/edgexfoundry/edgex-go/blob/823421a4da071faa6d3c579db468f86a03773fe5/internal/support/notifications/sending_service.go#L93-L95

**Comment by rudderfree** [comment]
I would like to take this up, if someone is not working on it already.

**Comment by jpwhitemn** [comment]
@rudderfree - feel free to assume this issue for Fuji release.  Ask @akramtexas to review on your PR when submitted.

**Comment by rudderfree** [comment]
Thanks Jim.

do we have any test mail servers for such feature testings by any chance, or possibly test mail accounts?

**Comment by jpwhitemn** [comment]
I'm afraid we do not @rudderfree.  That's why you see Gmail and Yahoo email addresses typically as a default.

    On Wednesday, June 12, 2019, 5:49:28 AM CDT, rudderfree <notifications@github.com> wrote:  
 
 
Thanks Jim.

do we have any test mail servers for such feature testings by any chance, or possibly test mail accounts?

**Comment by rudderfree** [comment]
I have tested the changes below for the empty case using a local sendmail server on my linux machine, after pulling the code out to a separate binary. It passes the test. I still need to test it from edgex-go build, but putting it out here for comments.

@akramtexas does it look any good, would appreciate your comments, Thanks.

```go
func smtpSend(message string, addressees []string) models.TransmissionRecord {
        var err error
        smtp := Configuration.Smtp
        tr := getTransmissionRecord("SMTP server received", models.Sent)
        buf := bytes.NewBufferString("Subject: " + smtp.Subject + "\r\n")
        // required CRLF at ends of lines and CRLF between header and body for SMTP RFC 822 style email
        buf.WriteString("\r\n")
        buf.WriteString(message)

        if (smtp.Password != "") {
                err = mail.SendMail(smtp.Host+":"+strconv.Itoa(smtp.Port),
                        mail.PlainAuth("", smtp.Sender, smtp.Password, smtp.Host),
                        smtp.Sender, addressees, []byte(buf.String()))
        } else {
                err = mail.SendMail(smtp.Host+":"+strconv.Itoa(smtp.Port),
                        nil,
                        smtp.Sender, addressees, []byte(buf.String()))
        }

```
[sending_service.patch.txt](https://github.com/edgexfoundry/edgex-go/files/3285315/sending_service.patch.txt)

**Comment by akramtexas** [comment]
@rudderfree Thanks for reaching out. Yep, I'll take a look today 👍

**Comment by akramtexas** [comment]
> I have tested the changes below for the empty case using a local sendmail server on my linux machine, after pulling the code out to a separate binary. It passes the test. I still need to test it from edgex-go build, but putting it out here for comments.
> 
> @akramtexas does it look any good, would appreciate your comments, Thanks.
> 
> ```go
> func smtpSend(message string, addressees []string) models.TransmissionRecord {
>         var err error
>         smtp := Configuration.Smtp
>         tr := getTransmissionRecord("SMTP server received", models.Sent)
>         buf := bytes.NewBufferString("Subject: " + smtp.Subject + "\r\n")
>         // required CRLF at ends of lines and CRLF between header and body for SMTP RFC 822 style email
>         buf.WriteString("\r\n")
>         buf.WriteString(message)
> 
>         if (smtp.Password != "") {
>                 err = mail.SendMail(smtp.Host+":"+strconv.Itoa(smtp.Port),
>                         mail.PlainAuth("", smtp.Sender, smtp.Password, smtp.Host),
>                         smtp.Sender, addressees, []byte(buf.String()))
>         } else {
>                 err = mail.SendMail(smtp.Host+":"+strconv.Itoa(smtp.Port),
>                         nil,
>                         smtp.Sender, addressees, []byte(buf.String()))
>         }
> ```
> 
> [sending_service.patch.txt](https://github.com/edgexfoundry/edgex-go/files/3285315/sending_service.patch.txt)

@rudderfree LGTM 👍 And I don't see any issues. When ready, please go ahead and submit a PR, thanks.

**Comment by rudderfree** [comment]
@akramtexas Thanks for the review :), working on testing it within Edgex-go and PR submission.

**Comment by akramtexas** [comment]
> @akramtexas Thanks for the review :), working on testing it within Edgex-go and PR submission.

Yep, I'll look forward to reviewing your PR :) 👍

**Comment by rudderfree** [comment]
@akramtexas submitted the PR

**Comment by akramtexas** [comment]
> @akramtexas submitted the PR

@rudderfree 👍
