### ISSUE TITLE
Cannot Delete DeviceProfile, DeviceService and Addressables when using Redis DB

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-go#1392]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Redis implementation of metadata.go DBClient.
The issue probable exists in other DBClients implementations as notifications, schedulers and etc. 

### Is this a regression?

 No

### Description and Minimal Reproduction 
When using Redis DB Device related objects as DevicePRofile, DeviceService, Addressables cannot be cleared:

1. DeviceService [cannot be deleted](https://github.com/edgexfoundry/edgex-go/blob/8bfb242945e30f6b8a24071db0a838d0bcc60c0b/internal/core/metadata/rest_deviceservice.go#L370), because [No Devices are assigned](https://github.com/edgexfoundry/edgex-go/blob/8bfb242945e30f6b8a24071db0a838d0bcc60c0b/internal/pkg/db/redis/metadata.go#L292) to it.
2. DeviceProfiles [cannot be deleted](https://github.com/edgexfoundry/edgex-go/blob/8bfb242945e30f6b8a24071db0a838d0bcc60c0b/internal/core/metadata/rest_deviceprofile.go#L356), because the DeviceProfile have[ No Provisioning watchers](https://github.com/edgexfoundry/edgex-go/blob/8bfb242945e30f6b8a24071db0a838d0bcc60c0b/internal/pkg/db/redis/metadata.go#L1008)

and as a site effect -> Addressables cannot be deleted, becasue the DeviceService are not deleted (1) and the addressables are still[ in use](https://github.com/edgexfoundry/edgex-go/blob/8bfb242945e30f6b8a24071db0a838d0bcc60c0b/internal/core/metadata/rest_addressable.go#L141)

The root cause of these cleaning issues is that: when searching for multiple objects from the DB by some criteria, and no object was found, this is not a condition for raising an ErrNotFound, instead an empty list should be returned.
The issue discussed here: explaind: https://github.com/edgexfoundry/edgex-go/issues/1203
https://github.com/edgexfoundry/edgex-go/issues/1203#issuecomment-496827782
https://github.com/edgexfoundry/edgex-go/issues/1203#issuecomment-488569660

Wants to point that there is a slight difference between the mongo and redis database implementations. For example GetDevicesByServiceId. 
MONGO:

> func (mc MongoClient) GetDevicesByServiceId(id string) ([]contract.Device, error) {
	ds, err := mc.getDeviceServiceById(id)
	if err != nil {
		return []contract.Device{}, err
	}
	return mc.getDevices(bson.M{"service.$id": ds.Id})
}

REDIS 
>func (c *Client) GetDevicesByServiceId(id string) ([]contract.Device, error) {
	return c.getDevicesByValue(db.Device + ":service:" + id)
}

Before **GetDevicesByServiceId** is called, it is always validated that such deviceservice already exists (we already have read the Device Service object from the database). So, is it redundant to get Device Service objects itself in mongo implementation ?! or it is needed to be added in the Redis implementation ? Where is the best place to validate that the object exists: inside this function or one above ? Currently in Mongo the object is read two times. 
Based on this **test/db_metadata.go** could needs to be **adjusted**. 
@tsconn23 @andresrinivasan 

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:** Edinburg v0.0.1

**Anything else relevant?**

**Comment by tsconn23** [comment]
> The root cause of these cleaning issues is that: when searching for multiple objects from the DB by some criteria, and no object was found, this is not a condition for raising an ErrNotFound, instead an empty list should be returned.

I agree with this. For example, perhaps a device service was created in error and hasn't had any devices associated with it yet. The fact that there aren't any devices should not prevent the deletion of the device service. Same applies to you DeviceProfile --> ProvisionWatcher case.

**Comment by difince** [comment]
@tsconn23  what do you think about section: _Anything else relevant?_
