### ISSUE TITLE
Update Dockerfiles to Use golang:1.12-alpine

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1401]
All services with Dockerfile support in the `edgex-go` repo need to be upgraded from `golang:1.11-alpine` to `golang:1.12-alpine`

**Comment by AnthonyMBonafide** [comment]
@iain-anderson , What work is needed in order to upgrade the snap packages to use go 1.12?

**Comment by iain-anderson** [comment]
@AnthonyMBonafide  Think @anonymouse64 may be able to help :-)

**Comment by anonymouse64** [comment]
The snippet where we download go inside the snap build here: 

https://github.com/edgexfoundry/edgex-go/blob/46ef4c6d7e5c69bdb661db443cdf1cd27be6138b/snap/snapcraft.yaml#L375-L389

All you need to do to update this is just pull the new download links from https://golang.org/dl/ and the associated sha's and put them in the right variables
