### ISSUE TITLE
Nanosecond Timestamp Support for Events/Readings

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1404]
During the Device Service working group call 3-Jun-19 it was decided that all timestamp fields for events and readings should support fidelity down to the nanosecond level. Events and Readings have three timestamp fields

- Origin _(timestamp reflecting when the event was sourced from the device)_
- Created _(timestamp reflecting when the event was first persisted to the database)_
- Modified _(timestamp reflecting when the event was last modified in the database)_

Of these, core services is responsible for managing the last two. All timestamps within the core services are currently set according to the following function.

https://github.com/edgexfoundry/edgex-go/blob/63c99229ab73133cb40a9f2e3e8640625d2de825/internal/pkg/db/db.go#L75

To accomplish the above, non-Origin timestamps related to readings ([example](https://github.com/edgexfoundry/edgex-go/blob/63c99229ab73133cb40a9f2e3e8640625d2de825/internal/pkg/db/mongo/data.go#L65)) and events ([example](https://github.com/edgexfoundry/edgex-go/blob/63c99229ab73133cb40a9f2e3e8640625d2de825/internal/pkg/db/mongo/data.go#L86)) will need to be managed differently.

**Comment by AnthonyMBonafide** [comment]
Closing this issue as per our discussion in the Core working group call on June 13, 2019
