### ISSUE TITLE
Containers should consistently use support-logging

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1415]
The containerized version of the individual edgex-go services are most likely to be used together via the docker-compose manifests found in [edgexfoundry/developer-scripts](https://github.com/edgexfoundry/developer-scripts/tree/master/compose-files).  As such, the individual services should be configured to handle their logging in a consistent way.

Update services (except for config-seed which has a dependency on support-logging) currently logging locally to log via the support-logging service.

Services currently logging locally:

- config-seed
- core-command
- core-metadata
- export-distro
- support-notifications
- support-scheduler
- sys-mgmt-agent

Services currently logging to support-logging:

- core-data
- export-client

**Comment by tsconn23** [comment]
@jpwhitemn Should we also create a PR against the `edinburgh` branch for this?

**Comment by anonymouse64** [comment]
What about the snap? Right now the services in the snap default to logging to both a file and stdout (and stdout for the services is routed to systemd/snapd)

**Comment by jpwhitemn** [comment]
Trevor - good question.  What do others think - is this a bug worthy of fix on the branch or is it just for Fuji.  Per Ian J, Snap does both.  Should this be consistent across all deployments too?  

Other inputs and opinions sought.  If we can come to consensus via email, let's act.  If not, let's cover in Core WG next week.

    On Friday, June 7, 2019, 10:47:22 AM CDT, Trevor Conn <notifications@github.com> wrote:  
 
 
@jpwhitemn Should we also create a PR against the edinburgh branch for this?

**Comment by jpwhitemn** [comment]
@tsconn23 - no other responses on this.  Recommend we give this to either @AnthonyMBonafide or @brandonforster and fix for Edinburgh and Fuji.  I would say default to file go remain partially consistent with snaps per @anonymouse64 (stdout is not an option currently).

**Comment by tsconn23** [comment]
Reopening for @brandonforster when it comes time to submit the `edinburgh` PR
