### ISSUE TITLE
Add database versioning support

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#1424]
# 🚀 Feature Request

### Relevant Packages
This feature request is for core services.

### Description
Leverage a Go based database migration tool so that we can better manage changes to databases while also better facilitating backwards compatibility. See [migrate](https://github.com/golang-migrate/migrate) for possible library and features we could use.

#### Problems:

1. Database initialization - The initialization of database(s) are done via scripts, like `init_mongo.js`, which are copied across multiple repos (`docker-edgex-mongo` and `developer-scripts`). This makes standing up an EdgeX system complicated since the user has to first configure Mongo, then execute the `init_mongo.js` script(located in either of the two repos), then start the necessary services.

2. Database maintainability - Making updates in the code sometimes can lead to making changes in the database schemas. This results in multiple PRs across repos which then have to come together for the final product. This coordination adds some complexity to the maintainability of the project/system and can be error prone.

3. Backwards compatibility - With the current implementation, there is no way to provide backwards compatibility for situations which require moving around of data or re-structuring the database schema. For example, if we decide that --for some crazy reason-- we would like to merge data from two different collections into one. As of now we would make the necessary code changes, update the `init_mongo` script, and roll out the updates together. However, this would not be ideal for users that are already using the system and just want to update to the latest version as it would require them to lose data as they switch to the new schema by re-executing the initialization script.

4. Fault tolerance - We do not have a good way of ensuring the state of the database within EdgeX. Since the code and the database schema information are disjointed we don't have a reliable way of ensuring that the database and the code have been updated, shipped, and installed correctly. In some cases we may not see any errors until we actually try to access the problematic data.

#### Suggested Solution:

Use a Go based database migration tool, possibly [migrate](https://github.com/golang-migrate/migrate), and handle the database setup and versioning within the respective services.

The thought is that each service has its own scripts, specific to its data and underlying database, which will make the necessary changes to the database to bring the database to a state which the application can interact with. This should work with any previous database state which is valid.

For example, given the structure of the `edgex-go` as of this writing. The database files for `coredata` would reside in a folder with the different versions, lets assume `cmd/coredata/res`, and would look something like:
```
- 1_initalize_mongo.js
- 2_add_index_to_reading_device.js
- 3_rename_reading_collection.js
...
```

During startup after connecting to the database, the service would then execute migrations to ensure the database is in the correct state and startup as it does today. If there are migrations to be made then leverage the database migration tool to perform the migrations. If an error is encountered we simply fail and do not start the service.

With this setup, we can simply just create new migration scripts and add them to the correct location and the startup process will handle applying the migrations.

This would solve the problems:
1. Database initialization - Having all the database information in one place reduces the complexity of standing up an environment.

2. Database maintainability - Reduces the complexity when making code changes which also require database schema updates since the code and database scripts are co-located

3. Backwards compatibility - We would be able to better facilitate backwards compatibility since we would be able to package database scripts with the version of the service and would give us more control of how to manage the persisted data between different versions.

4. Fault tolerance - We would now be able to programatically fail during startup, which ensures the system is in the correct state and we can add tests for these situations.

In theory this setup could allow us to eliminate `docker-edgex-mongo` repo, and the mongo setup scripts from `developer-scripts` and reduce the complexity of the system.

#### Unknowns:

1. How does this affect CI jobs?
2. How does the database locking work ensure applications that leverage the same database are not causing interfering with one another?
3. Will this cause issues when services are scaled out?
4. Are there any other good tools to achieve this?

### Describe alternatives you've considered
No other solutions have been explored

**Comment by AnthonyMBonafide** [comment]
I think this may also give us an opportunity to better manage secrets once we incorporate the functionality from `go-mod-secrets`  since we are handling the database migrations in the service applications we can possibly eliminate the need for storing database credentials in multiple places

**Comment by AnthonyMBonafide** [comment]
Another tool to look into is [Liquibase](https://www.liquibase.org). Thank you @akramtexas for the suggestion.

**Comment by tsconn23** [comment]
I think there are two issues here that are combined:
- The current methodology for scripting the initial state of the Mongo DB needs improvement (I agree)
- Data migration pursuant to an upgrade of some kind (I'm not convinced on this point)

Some thoughts as I was reading this.

1.) I think the hooks for any migration capabilities should be in the database provider layer (internal/pkg/db) and not via some scripts in the ./res folder. Methodologies will differ across vendors and if someone wants to integrate, then THEY need to solve this problem for their storage model. 
2.) Migrations should be done once, the first time a newly versioned service starts and that's it. Once it's done, it's done -- no checking of "valid states" every time a service starts up.
3.) What if the customer ends up having to rollback but their data's already been migrated forward?
4.) There's a difference between transient and long-lived data in the system. Transient data is readings/events and that data must be drained prior to an upgrade. There will be no upgrade path for these. For everything else, there could be a migration scenario -- but we have no customer requirements (or even SLAs) around that yet. That makes this a solution without a problem.

Let's concretize this with an example. @difince is working on reworking the device profile to device relationship. This also fundamentally changes the way we handle commands. When Fuji releases, any command records in the database can stay because they'll never be retrieved (we don't pay any attention to them now) and since the structure of a command is changing, they won't match any of the new queries that will be going in.

Here's something a bit more invasive -- Removing Addressable from Device and replacing it with `Protocols      map[string]ProtocolProperties`. For something like that, I'd seriously consider making the customer re-provision their environment. If we take on migration in these cases, we're taking on a certain liability. I'm open to discussion but, as a third party solution provider to a customer's OT environment, I would be hugely careful here.

All of that said, it may be useful to adopt a document versioning practice similar to what is shown [here](https://www.mongodb.com/blog/post/building-with-patterns-the-document-versioning-pattern).

**Comment by michaelestrin** [comment]
Trevor's response caught my attention.  Some additional thoughts...

1. Concur that persisted documents should be versioned and I see that as an implementation detail behind the existing DBClient contract.

1. Concur that migrations are implementation-specific and I therefore envision them implemented behind the existing DBClient contract.  

1. Having integrated migration support in prior product efforts, I've anecdotally found always rolling forward is easiest.  Explicit rollback introduces significant complexity.  Migrations that move or delete data are best done in stages to ensure a conceptual rollback (via roll forward) can be accomplished without data loss.  Easily done when you're managing a SaaS product with continuous delivery/deployment -- not necessarily so in EdgeX's case where we have no control over the deployment environment.

1. The external API and DBClient both use the same model contracts.  These will likely need to be decoupled if we support multiple API versions for backward compatibility.   

1. This discussion begs the question of EdgeX's upgrade story/strategy going forward.  Must minor (dot) releases be persistence-compatible?  Do we version the overall persistence instance (the actual stored data) and flag it is out of sync with the executing version of EdgeX? When persistence schema changes, do we require EdgeX be re-provisioned (and, if so, what does that look like from a DevOps perspective)?

**Comment by AnthonyMBonafide** [comment]
To @tsconn23 's comments:
> 1.) I think the hooks for any migration capabilities should be in the database provider layer (internal/pkg/db) and not via some scripts in the ./res folder. Methodologies will differ across vendors and if someone wants to integrate, then THEY need to solve this problem for their storage model.

My thought is that the service would determine which database vendor is being used, then pass the scripts to the proper DBClient implementation to execute the queries. I see having the database queries in a script as being easier to maintain and read. I agree every vendor will need to be treated differently and the ones we do not support are out of scope for us, but as of now we support Mongo and Redis and we should be providing support for those. With this model of using scripts one can simply add support for another data-store in the code, drop in the script to provision the data-store, start up the service, and verify that it has successfully started. If the user is concerned about giving EdgeX permissions to alter the data-store then simply do not use the functionality. 

> 2.) Migrations should be done once, the first time a newly versioned service starts and that's it. Once it's done, it's done -- no checking of "valid states" every time a service starts up.

Agreed migrations should be done once, however you would have to check the current version of the database and see which migrations are available and which need to be applied. I think this has to happen in order to ensure all migrations have been applied.

> 3.) What if the customer ends up having to rollback but their data's already been migrated forward?

Most of the tools, including the one referenced in my original post, provide functionality for rolling back. The idea is that you provide 2 scripts for each migration. One for introducing the necessary changes, the other to undo the changes from the other script. You can then leverage the tool to execute the script which puts your data back to the state it was before the migration. 

As @michaelestrin stated that you have to be clever as how you introduce the rollback scripts. Doing deletions in stages has worked for me in the past as well

> 4.) There's a difference between transient and long-lived data in the system. Transient data is readings/events and that data must be drained prior to an upgrade. There will be no upgrade path for these. For everything else, there could be a migration scenario -- but we have no customer requirements (or even SLAs) around that yet. That makes this a solution without a problem.

I see this proposal as only being applied to data which needs to be migrated. If you do not need to touch certain data, simply don't. In this case there should be no changes to the data layout for readings, events, and other transient data.

> Here's something a bit more invasive -- Removing Addressable from Device and replacing it with `Protocols map[string]ProtocolProperties`. For something like that, I'd seriously consider making the customer re-provision their environment. If we take on migration in these cases, we're taking on a certain liability. I'm open to discussion but, as a third party solution provider to a customer's OT environment, I would be hugely careful here.

I agree, in situations like this I think we would simply require them to re-provision and communicate that in the release of the software. Adding database versioning won't solve all migration problems. It has the potential to make migrations easier given the migrations are compatible. In the past I have added migrations scripts as the application needed and when there was a breaking migration I would increase the major version and consolidate all the queries into one script and start over.

> All of that said, it may be useful to adopt a document versioning practice similar to what is shown [here](https://www.mongodb.com/blog/post/building-with-patterns-the-document-versioning-pattern).

:+1: 

My suggestions and comments are based on previous experiences using [Flyway](https://flywaydb.org/) to manage database migrations. The applications that I have leveraged this tool with has supported different database vendors(driven by configuration), and sometimes requiring more than one database at a time(Oracle,Cassandra). I think this can be done with the tools provided by the Go community and our current code structure regarding the DBClient and the database configuration functionality.

**Comment by AnthonyMBonafide** [comment]
To @michaelestrin 's comments:

> * The external API and DBClient both use the same model contracts.  These will likely need to be decoupled if we support multiple API versions for backward compatibility.

I agree and think we should be doing this. I think the API which the user uses should not be tied to how the backend uses the data. I think we should try to not change the API as much but be free to change how we perceive the data within the system.

> * This discussion begs the question of EdgeX's upgrade story/strategy going forward.  Must minor (dot) releases be persistence-compatible?  Do we version the overall persistence instance (the actual stored data) and flag it is out of sync with the executing version of EdgeX? When persistence schema changes, do we require EdgeX be re-provisioned (and, if so, what does that look like from a DevOps perspective)?

Great questions! I think we do need these answered.

**Comment by AnthonyMBonafide** [comment]
@tonyespy, as per the conversation in the core working group call regarding migrating the Mongo initialisation scripts to Go. I would like to get your thoughts on this feature request.

**Comment by jpwhitemn** [comment]
@AnthonyMBonafide @michaelestrin - still a Fuji release item?  Label Geneva?

**Comment by michaelestrin** [comment]
Closed.  Not on the current road map.
