### ISSUE TITLE
Error while importing export-client.raml in Postman

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#143]
When trying to import file export-client.raml in Postman, I get the error "Error while importing RAML: mapping values are not allowed here"

I think the error is in line 129 in export-client.raml:
`description: Export Client registration property type. Valid types are: "algorithms", "compressions", "formats", and "destinations".`

The second `:` should be removed, so this line will be:
`description: Export Client registration property type. Valid types are "algorithms", "compressions", "formats", and "destinations".`

After this modification, I can import with Postman without problems.

I'm not a RAML expert, so, does it make any sense? Is this an export-client.raml error or a Postman error?

**Comment by dylan-hantula** [comment]
I ran into the same issue and was able to resolve it by removing the second `:` in line 129.
