### ISSUE TITLE
Refactor the same semantic configuration item with the unified key.

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#144]
Just like @jduranf said in the PR #130 , the existed naming for the same semantic configuration key are confused in many sub modules. We should refactor them with unified key naming.
If it is worthy to be done, I want claim it.

**Comment by yanghua** [comment]
closing this issue, thank you.

**Comment by tsconn23** [comment]
Closing this. There's no need to do this in the existing codebase due to upcoming general rework of configuration during coming weeks.
