### ISSUE TITLE
Notifications - fishy error test

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1441]
/github.com/edgexfoundry/go-mod-core-contracts/models/notifications_test.go

Line 39:
if err == nil {
		handleFailedTransmission(t)
	}

Line 55:
if err == nil {
		handleFailedTransmission(t)
	}

**Comment by tsconn23** [comment]
@mkbhanda This needs to be created in the `go-mod-core-contracts` repository. If you create a new issue, please provide a little more detail with regard to the resolution you'd like to see. I would not categorize a suspect unit test as a bug.

**Comment by mkbhanda** [comment]
Oops! Sorry for filing to wrong repository.
