### ISSUE TITLE
Override Configuration Using Environment Variables

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1450]
# 🚀 Feature Request

### Relevant Package

This feature request is for all core services.

### Description

Enable ability to override service configuration using environment variables.  This is the generally accepted mechanism to inject variation when instantiating a container.

My specific use case -- a Helm Chart to support the management of multiple instances of EdgeX in a Kubernetes cluster -- precludes use of the containerized `configuration.toml` files and registry-based configuration.  Each instance of EdgeX must have its own uniquely named Kubernetes service to facilitate inter-instance communication.   Any EdgeX service that communicates with another would need to be updated with that unique instance/service name.

### Describe the solution you'd like

- In internal/pkg/config, implement a reflection-based traversal of an empty interface typed `ConfigurationStruct`.  
- Environment variable keys would be formatted using underscore separators.  For example, `MessageQueue_Host` would refer to core-data's `ConfigurationStruct.MessageQueue.Host` field.
- Environment variables would supersede both file- and registry-based configuration values.

### Describe alternatives you've considered

- Considered and discarded conversion of service-specific `ConfigurationStruct` (required for marshaling toml and registry data) into generic key/value configuration contract/implementation to be used by service to retrieve configuration.

**Comment by iain-anderson** [comment]
Could the configuration structure be retained by replacing
`Clients      map[string]config.ClientInfo`
with
`Clients      ClientStruct`
and
```
type ClientStruct struct {
  MetadataClient  config.ClientInfo
  LoggingClient   config.ClientInfo
// etc
}
```
(and similar for databases)

**Comment by michaelestrin** [comment]
@iain-anderson Indeed.  Verified.  Updated issue description to reflect.

**Comment by michaelestrin** [comment]
Based on Core WG feedback, I modified the proposed solution as follows:

- Support environment variable overrides for config-seed to the `configuration.toml` content it uploads into registry.  An environment variable can be service-specific or generic.  

    A service-specific environment variable override would include the targeted service's name and would only affect configuration for that service; i.e. `core-metadata_Clients_logging_Host=<someAddr>`.  

    A generic environment variable override would not include a service name and would affect configuration across all services config-seed handles; i.e. `Registry_Host=<someAddr>`.

- Support environment variable override of a core service's RegistryInfo fields (i.e. host, port, and type) to allow a containerized service instance to be pointed at an alternate registry location.

See #1461 for additional details.
