### ISSUE TITLE
Support automatic migration of Devices between Device Services

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/edgex-go#1451]
# 🚀 Feature Request

[**NB WIP**: There may well be insuperable problems with this]

### Relevant Package
core-metadata, device services

### Description
In a scenario where a device can move between the connectivity domains of different device services (eg a radio-connected device physically moving in and out of range of various base stations), we wish to be able to automatically update the Device object in EdgeX accordingly.

### Describe the solution you'd like
* ProvisionWatchers to allow wildcarded DeviceService field, eg "device-bluetooth-basement-*"
* core-metadata to match said wildcard when queried for PWs for a particular Device Service
* DS implementation would have to generate a consistent name for a Device whichever DS discovers it
* DS SDK to detect that a discovered device already exists, and update the Device's Device Service field to point to itself
* DS SDK to react appropriately to the callback from core-metadata indicating that a Device now belongs to it / to another DS

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by michaelestrin** [comment]
Discussed in last week's Device Services WG call and decided not to do this for Geneva.  Changing label to unscoped.

**Comment by cloudxxx8** [comment]
@iain-anderson do we still need this issue?

**Comment by jumpingliu** [comment]
same as https://github.com/edgexfoundry/edgex-go/issues/4694
