### ISSUE TITLE
Expose edgexproxy command in the snap

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1472]
We currently run edgexproxy as a one-shot service in the snap, however it can also be used as a user-driven app to configure OAuth tokens and such when provided with specific arguments and a different configuration.toml file. There is currently no way to override the arguments passed to edgexproxy in order to use it like this, so we should add a specific new app (not a daemon) to the snap to allow using edgexproxy in this way.

**Comment by anonymouse64** [comment]
Assigning this to @knitzsche

**Comment by tonyespy** [comment]
I removed the fuji label as PR #2102 landed for Fuji just prior to the release however it didn't include a "Fixes" line.

**Comment by anonymouse64** [comment]
Fixed for geneva/master with https://github.com/edgexfoundry/edgex-go/pull/2136
