### ISSUE TITLE
By default downgrade user privileges in Docker containers

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1479]
The Linux kernel user namespace support provides additional security by enabling a process, and therefore a container, to have a unique range of user and group IDs which are outside the traditional user and group range utilized by the host system. Potentially the most important security improvement is that, by default, container processes running as the root user will have expected administrative privilege (with some restrictions) inside the container but will effectively be mapped to an unprivileged uid on the host.
For details about how to use this feature, as well as limitations, see Isolate Containers (https://docs.docker.com/engine/security/userns-remap/)  

2 ways to downgrade the user:

1) Launching the container with a user-id (does not even have to exist) with no special privileges, typically a number greater than 500.

Docker run command with a –u <id> ..<standard arguments>        // id > 500, unprivileged, non-existent user-id, low order IDs are reserved

2) Editting the Dockerfile to set the user to a not privileged user once all package/software related installs are complete. See line (d) below.

a)   FROM ubuntu:latest 
b)   RUN apt-get update --fix-missing && \ 
c)      apt-get install <something1>
d)   USER 9000 
f)   EXPOSE 6379 
9)   CMD  <something2>
 

This will require changes to docker files and a full run of the test suite to ensure everything works as before.  To test with less effort, perhaps install using a docker compose file with the user set to underprivileged as in (1). After confirming everything works, modify the docker files.

**Comment by bnevis-i** [comment]
Closing in favor of https://github.com/edgexfoundry/edgex-go/issues/1955
