### ISSUE TITLE
Verify SW packages for trusted origin before launching

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1484]
# 🚀 Feature Request

### Relevant Package

 This feature request is for...

Verify SW package origins for trust worthiness before launching

### Describe the solution you'd like
Before installing SW packages, first verify whether they are signed by a trusted authority
For containers possibly use the Docker engine to verify their signature. For other SW has the package and check whether the signature encoded hash is the expected value. 

EdgeX could use PKI, guarding its private key, sign all release artifacts. Nightly builds and pre-release candidates could be signed by a lesser key-pair such as Dev-EdgeX.

Who are valid signatories? These might be EdgeX specific and Application Vendor specific. Application vendors might be providing application processing software as containers or other packages and use their own public-private key pairs.

### Describe alternatives you've considered
No

**Comment by tingyuz** [comment]
need more details about the topic. can we discuss it next week?

**Comment by mkbhanda** [comment]
Docker Engine enterprise, Snaps, Open Horizon etc have logic to check for signatures. We shall address this issue through documentation. @Tingyu and self will add a best-practices chapter in our security documentation.
