### ISSUE TITLE
Implement the design: SMA to get Metrics via Executor.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1486]
- This issue tracks the _implementation_ of the `design` that was created previously per [Issue#1414](https://github.com/edgexfoundry/edgex-go/issues/1414)
- The goal here is to refactor metrics collection - moving metrics collection to the executor so that it can remain platform and even service implementation agnostic.
- Effectively, this is a direct follow-up to: [Issue #1414](https://github.com/edgexfoundry/edgex-go/issues/1414)

**Comment by michaelestrin** [comment]
@anonymouse64 

I agree with your assessment (made on several abandoned PRs related to the system executor) that we should have a standard contract for metrics and, further, that we should also return the raw metrics for optional consumption.

The Fuji road map specifies:

> Refactor metrics collection - moving metrics collection to the executor so that it can remain platform and even service implementation agnostic.

I believe this implies the executor will become the source of metric collection and the existing service-based metric collection implementation and endpoints will be removed.  I discussed this with @akramtexas this morning and I'll be working to obtain clarity from @jpwhitemn on this point when he returns from his vacation next week.

**Comment by anonymouse64** [comment]
@michaelestrin the discussion I had with Jim and Akram was that we would keep the service-based metric collection as an option for non-docker based implementations such as the snap or native process deployments, etc. So you can pick which implementation to use from the configuration.

**Comment by michaelestrin** [comment]
@anonymouse64 

That makes sense to me.  Services in non-containerized environments would be the likeliest source for metrics.  You could obtain them by querying a separate OS-specific process (i.e. top) but I'm not sure why one would take on the added complexity.

Which raises a separate but related question -- why not continue to use the service-based metric collection implementation for Docker-based deployments (i.e. what is the value of having the executor handle metrics collection for Docker-based deployments)?  

I appreciate everyone's patience.  I'm not trying to be difficult or to change the existing agreements or design.  I'm just trying to understand why we're doing what we're doing the way we're doing it.

**Comment by anonymouse64** [comment]
TBH, I don't recall the reasoning for creating a new docker-specific implementation... I think we should have 2 choices for collecting metrics:
- ask the service through the service endpoints, like what we do today
- call out to an arbitrary binary that responds in JSON or some other structured format

The second option allows folks running inside different distribution mechanisms or where they have more accurate or useful metrics to implement their own and use it instead.

**Comment by michaelestrin** [comment]
@anonymouse64 That's helpful.  Thank you.  Perhaps the Docker-specific implementation is intended as an example implementation of an arbitrary binary.  I'll proceed under that assumption.

**Comment by akramtexas** [comment]
- Good discussion here, @michaelestrin and @anonymouse64, and I appreciate it: Our goal, as an open-source community, is to help steer System Management (in its evolution) in the right direction forward, in the best way possible. 
- Yes, one of the goals of the [roadmap for the Fuji Release](https://wiki.edgexfoundry.org/display/FA/Fuji+Release) is to "_Refactor metrics collection - moving metrics collection to the executor so that it can remain platform and even service implementation agnostic._"
- I thank you, @anonymouse64, for succinctly capturing here per the discussion (from a little while ago) that we would keep the _service-based metric collection_ as an option for non-Docker based implementations such as the snap or native process deployments, etc., whereby you can pick which implementation to use from the configuration.

**Comment by akramtexas** [comment]
> @anonymouse64 That's helpful. Thank you. Perhaps the Docker-specific implementation is intended as an example implementation of an arbitrary binary. I'll proceed under that assumption.

@michaelestrin, you are correct in this assumption: The `Docker-specific implementation` _is_ indeed intended as a `reference implementation` of an arbitrary binary 👍

**Comment by akramtexas** [comment]
Michael graciously joined hands with me to tackle this issue. I've transitioned the completion of the associated work to him. As such, the (original) PR associated with this issue ([PR-1672](https://github.com/edgexfoundry/edgex-go/pull/1672)) has been closed. As for [the original feature branch](https://github.com/akramtexas/edgex-go/commit/1d1598df0835e9178ddaea73ca0c5cc9f2e69dff) on which I had done the relevant work, it reflects the valuable feedback I got from Michael, as well as the invaluable pair-programming sessions we did, and for which I'm most grateful 👍

**Comment by michaelestrin** [comment]
I propose a standard contract for metrics that specifies four values -- cpuUsedPercent, memoryUsedPercent, rawType, and rawResult.  All four will be required, will be provided by all metric gathering implementations, and may require a specific implementation to normalize/transform its gathered data.  Sample result from the example Docker executor follows:

    {
      "operation": "metrics",
      "service": "edgex-core-data",
      "success": true,
      "cpuUsedPercent": 1.73,
      "memoryUsedPercent": 0.11,
      "rawType": "DockerExecutor",
      "rawResult": {
        "cpu_perc": "1.73%",
        "mem_usage": "8.582MiB / 7.786GiB",
        "mem_perc": "0.11%",
        "net_io": "246MB / 418MB",
        "block_io": "14.9MB / 0B",
        "pids": "19"
      }
    }

This provides a basic set of universal metrics that do not require a metrics consumer to have knowledge of the underlying metrics gathering implementation.  The raw data (and a corresponding type indicator) is provided should a consumer wish to go beyond the contract to obtain implementation-specific metrics data.

Thoughts @anonymouse64?

**Comment by anonymouse64** [comment]
LGTM @michaelestrin

**Comment by michaelestrin** [comment]
First pass work merged.  PR with refactored agent and unit tests to follow.

**Comment by tsconn23** [comment]
> First pass work merged. PR with refactored agent and unit tests to follow.

@michaelestrin Now that the associated PR has been merged should we close this issue and track remaining work in additional issues?

**Comment by michaelestrin** [comment]
Agreed.
