### ISSUE TITLE
Add Go.Sum to Repo

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1487]
It was decided during the Core WG meeting 20-Jun-19 that we would add the `go.sum` file to the edgex-go repo. This should also be copied into the service Dockerfiles. This will help to ensure stability in builds w/r/t versioned dependencies, both locally and via CI pipeline.

**Comment by anonymouse64** [comment]
There should be equivalent issues opened in all the rest of the go based edgex repos too I think now

**Comment by tsconn23** [comment]
Discussion item for Core WG 3-Oct-2019

**Comment by tsconn23** [comment]
Core WG notes -- 17-Oct-2019 / punting on this for now. Need someone to possibly reach out to hashicorp and see why we get collisions on their `hashicore/go-rootcerts`. This seems to be the main collision.

**Comment by michaelestrin** [comment]
Closing as Core WG decided not to add go.sum to the repository.
