### ISSUE TITLE
Remove the unexpected print log in start shell script

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#149]
in start shell script, such as `edgex-launch.sh` exists many [print log](https://github.com/edgexfoundry/edgex-go/blob/master/bin/edgex-launch.sh#L27), these log used to tell the user which microservice is launching.

Ideally, it should print like this (in sequence) : 

```
### Starting edgex-support-logging
{
  here is support logging launch log detail
}
### Starting edgex-core-command
{
  here is core command launch log detail
}
....
```
Actually, the result is like this (unordered): 
```
### Starting edgex-support-logging
### Starting edgex-core-command
### Starting ...
{
  here is support logging launch log detail
}
{
  here is core command launch log detail
}
### Starting ...
{
  ...
}
...
```

I would like to remove these print code and place them into the front of `cmd/xxx/main.go`

what's your opinion? @jpwhitemn @drasko @tsconn23

**Comment by yanghua** [comment]
@drasko what do you think about this?

**Comment by drasko** [comment]
@yanghua in Mainflux every service has a line like thus upon the start: https://github.com/mainflux/mainflux/blob/master/cmd/manager/main.go#L96

Your proposition looks OK to me, but have in mind that `edgex-launch.sh` is not an actual production script - it is there just for the convenience of development.

In production some other and more robust way of starting services must be used, and if dockerized then orchestrator must be used.

**Comment by yanghua** [comment]
I have no more to say. Does it mean you guys agree this issue and I could start my work?

**Comment by yanghua** [comment]
@drasko thanks, closing this issue
