### ISSUE TITLE
Device Profile Update -- Check for Existing Devices

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1494]
Decided during Core WG 27-Jun-19

When a request is received by core-metadata to update a DeviceProfile, the service should first check to see if there are any devices associated with that profile. If so, then the service should return a `409 Conflict` HTTP status to the caller.

To be consistent with the DELETE of a DeviceProfile, we should probably add a similar check for the association with one or more Provision Watchers. See associated issue #1495.

Handler is here
https://github.com/edgexfoundry/edgex-go/blob/9421ecd6e689ba6c8274a1d2f5deb84c71282b73/internal/core/metadata/router.go#L94

**Comment by AnthonyMBonafide** [comment]
Resolved via PR #1498
