### ISSUE TITLE
PUT or POST interval action not work

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#1497]
I don't know how to create POST or PUT interval action and didn't found any clue in the source code.
The http request body is nil and params only use for ContentLengthKey
```
	req, err := http.NewRequest(httpMethod, executingUrl, nil)
	req.Header.Set(ContentTypeKey, ContentTypeJsonValue)

	params := strings.TrimSpace(intervalAction.Parameters)

	if len(params) > 0 {
			req.Header.Set(ContentLengthKey, string(len(params)))
	}
```
https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/scheduler/schedule.go#L465

### Affected Services
support-scheduler

### Is this a regression?
I not sure.  I didn't found any description to setup a POST or PUT action.
https://docs.edgexfoundry.org/Ch-APISupportingServicesScheduling.html

## 🌍  Your Environment
**Deployment Environment:**
macos
**EdgeX Version:**
edgex-go master branch

**Comment by xmlviking** [comment]
Ok I can see the documentation on this is wrong.  I will update that data areas for the actual calls into the scheduler service. 

To use the Scheduler you will using the RAML API.
https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/support-scheduler.raml

There you can see the API reference which the scheduler uses.  What was linked was the internal scheduler service implementation. That is abstracted from the RAML API interface.  So interacting with it directly would not work.  You would need to do HTTP POST using a something like Postman to send in a new Interval or Interval Action.  

There are some examples in the RAML of how to do that. :) .  I will make some time to update the .RST file for the data fields and update those samples! ;)

**Comment by weichou1229** [comment]
Thanks for your reply, but I can create a scheduled job with the following API:
```
curl -X POST -H "Content-Type: application/json" -d '{
    "name": "every20s",
    "frequency": "PT20S"
}' "http://localhost:48085/api/v1/interval"

curl -X POST -H "Content-Type: application/json" -d '{
    "name": "get-switch-action",
    "interval": "every20s",
    "target": "edgex-device-modbus",
    "protocol": "http",
    "httpMethod": "GET",
    "address": "localhost",
    "port": 49991,
    "path":"/api/v1/device/name/Modbus TCP test device/Switch"
}' "http://localhost:48085/api/v1/intervalaction"
```
But the question is how to create the job with httpMethod POST or PUT.

**Comment by xmlviking** [comment]
We have some black box tests which do this.  From the tests I can verify via Postman you should be able to create an Interval via the following: 

POST:

http://localhost:48085/api/interval

BODY:   “RAW” - JSON(application/json)

{
    "name": "afternoon",
    "start": "20180101T000000",
    "frequency": "P1D"
}

When I execute that on my local instance native.  “Using the Make Run” command I get the following back 

RESPONSE:
286a51cc-7ce6-4c6e-9887-e672cf012c7d

This is the ID of the Interval I created via the REST API call using POST.   


You can see the new interval using the Interval or the more specific interval by name pathing.

GET - Interval by Name

http://localhost:48085/api/v1/interval/name/afternoon

{
    "name": "afternoon",
    "start": "20180101T000000",
    "frequency": "P1D"
}

RESPONSE:
{
    "Timestamps": {
        "created": 1562867216233,
        "modified": 1562867216233
    },
    "id": "286a51cc-7ce6-4c6e-9887-e672cf012c7d",
    "name": "afternoon",
    "start": "20180101T000000",
    "frequency": "P1D"
}

Or you can reference the Interval By ID as a parameter.
Using the ID previously listed from the POST operation I could pass that 

GET - Interval by ID

http://localhost:48085/api/v1/interval/286a51cc-7ce6-4c6e-9887-e672cf012c7d

RESPONSE: 

{
    "Timestamps": {
        "created": 1562867216233,
        "modified": 1562867216233
    },
    "id": "286a51cc-7ce6-4c6e-9887-e672cf012c7d",
    "name": "afternoon",
    "start": "20180101T000000",
    "frequency": "P1D"
}

For brevities sake here is the afore mentioned GET all intervals REST call.

GET - All Intevals

http://localhost:48085/api/v1/interval

RESPONSE:
[
    {
        "Timestamps": {
            "created": 1562867091979,
            "modified": 1562867091979
        },
        "id": "75f23eb9-e9ea-4552-86ac-424e95a49267",
        "name": "midnight",
        "start": "20180101T000000",
        "frequency": "P1D"
    },
    {
        "Timestamps": {
            "created": 1562867216233,
            "modified": 1562867216233
        },
        "id": "286a51cc-7ce6-4c6e-9887-e672cf012c7d",
        "name": "afternoon",
        "start": "20180101T000000",
        "frequency": "P1D"
    }
]

Additionally I will list the PUT (or update) REST API call.


PUT - update and existing Interval

http://localhost:48085/api/v1/interval

NOTE: I updated the name of the interval.  If the interval was in use by any other interval actions you would be prevented from doing this update until you removed the existing interval actions referenced. 

BODY
{
    "id": "286a51cc-7ce6-4c6e-9887-e672cf012c7d",
    "name": "tenAM",
    "start": "20180101T000000",
    "frequency": "P1D"
}

RESPONSE:
True

And for clarity lets execute the GET all Intervals once more:

GET - all intervals
http://localhost:48085/api/v1/interval

RESPONSE:

[
    {
        "Timestamps": {
            "created": 1562867091979,
            "modified": 1562867091979
        },
        "id": "75f23eb9-e9ea-4552-86ac-424e95a49267",
        "name": "midnight",
        "start": "20180101T000000",
        "frequency": "P1D"
    },
    {
        "Timestamps": {
            "created": 1562867216233,
            "modified": 1562868121947
        },
        "id": "286a51cc-7ce6-4c6e-9887-e672cf012c7d",
        "name": "tenAM",
        "start": "20180101T000000",
        "frequency": "P1D"
    }
]

You can see the Interval name has been changed from afternoon to the updated version “tenAM”.  :)


For IntervalAction’s the same pattern holds true.  The only exception is that the assigned “Interval” must exist.  So you may get an error POST’ing a new IntervalAction, which contains and reference to an Interval, which does not exist.   Interval creation first or reference one that already exists.  

Interval - The timing periodicity or point in time for which you want stuff to happen. 
IntervalAction - What you want to happen when that Interval point is reached. 


GET - all IntervalActions
http://localhost:48085/api/v1/intervalaction

RESPONSE:
[
    {
        "id": "65693f32-1d29-4af7-aebe-7dda63b4b231",
        "created": 1562867091982,
        "modified": 1562867091982,
        "name": "scrub-pushed-events",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/scrub"
    },
    {
        "id": "98926755-7c4b-42b4-ba12-65eb365a77f7",
        "created": 1562867202143,
        "modified": 1562867202143,
        "name": "scrub-aged-events",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/removeold/age/604800000"
    }
]

You can follow the aforementioned pattern for all of the GET (all, or by name, or ID), POST (body), PUT (with ID param) and body.   

I hope this helps.

**Comment by weichou1229** [comment]
@xmlviking 
How to create an IntervalAction with httpMethod POST or PUT?
Where is the POST body I can set?
Is Parameters ? https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/interval_action.go#L124
```
curl -X POST -H "Content-Type: application/json" -d '{
    "name": "post-action",
    "interval": "every20s",
    "target": "edgex-device-modbus",
    "protocol": "http",
    "httpMethod": "POST",
    "address": "localhost",
    "port": 49991,
    "path":"/api/v1/device/name/Modbus TCP test device/Switch"
}' "http://localhost:48085/api/v1/intervalaction"
```

**Comment by xmlviking** [comment]
Ok. 

For IntervalAction’s the same pattern holds true.  The only exception is that the assigned “Interval” must exist.  So you may get an error POST’ing a new IntervalAction, which contains and reference to an Interval, which does not exist.   Interval creation first or reference one that already exists.  

Interval - The timing periodicity or point in time for which you want stuff to happen. 
IntervalAction - What you want to happen when that Interval point is reached. 


GET - all IntervalActions
http://localhost:48085/api/v1/intervalaction

RESPONSE:
[
    {
        "id": "65693f32-1d29-4af7-aebe-7dda63b4b231",
        "created": 1562867091982,
        "modified": 1562867091982,
        "name": "scrub-pushed-events",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/scrub"
    },
    {
        "id": "98926755-7c4b-42b4-ba12-65eb365a77f7",
        "created": 1562867202143,
        "modified": 1562867202143,
        "name": "scrub-aged-events",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/removeold/age/604800000"
    }
]

We can now POST a new IntervalAction using the following similar pattern

POST - (using Body content-type raw JSON(application/json)

http://localhost:48085/api/v1/intervalaction


BODY
{
        "name": "scrub-alt-test",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/scrub"
    }
RESPONSE
8b452368-5a2d-485f-91a8-e087b9f78314

This is the ID of the new IntervalAction we just created.  With the name “scrub-alt-test”.  This Interval Action is associated with the Interval previously created “midnight”.

Let’s verify using the GET verb to ensuref the IntervalAction has been created    

GET 
http://localhost:48085/api/v1/intervalaction

RESPONSE
[
    {
        "id": "65693f32-1d29-4af7-aebe-7dda63b4b231",
        "created": 1562867091982,
        "modified": 1562867091982,
        "name": "scrub-pushed-events",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/scrub"
    },
    {
        "id": "98926755-7c4b-42b4-ba12-65eb365a77f7",
        "created": 1562867202143,
        "modified": 1562867202143,
        "name": "scrub-aged-events",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/removeold/age/604800000"
    },
    {
        "id": "8b452368-5a2d-485f-91a8-e087b9f78314",
        "created": 1562945736420,
        "modified": 1562945736420,
        "name": "scrub-alt-test",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/scrub"
    }
]

Now we will update the Interval Action we just created:   Let’s change the name to something different.
I will change it to “scrub-my-test”. 

PUT- (using Body content-type raw JSON(application/json)
http://localhost:48085/api/v1/intervalaction

BODY
    {
        "id": "8b452368-5a2d-485f-91a8-e087b9f78314",
        "name": "scrub-my-test",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/scrub"
    }
RESPONSE 
True

Let’s validate we changed the IntervalAction name.   

GET
http://localhost:48085/api/v1/intervalaction

RESPONSE
[
    {
        "id": "65693f32-1d29-4af7-aebe-7dda63b4b231",
        "created": 1562867091982,
        "modified": 1562867091982,
        "name": "scrub-pushed-events",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/scrub"
    },
    {
        "id": "98926755-7c4b-42b4-ba12-65eb365a77f7",
        "created": 1562867202143,
        "modified": 1562867202143,
        "name": "scrub-aged-events",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/removeold/age/604800000"
    },
    {
        "id": "8b452368-5a2d-485f-91a8-e087b9f78314",
        "created": 1562945736420,
        "modified": 1562946138558,
        "name": "scrub-my-test",
        "interval": "midnight",
        "target": "core-data",
        "protocol": "http",
        "httpMethod": "DELETE",
        "address": "localhost",
        "port": 48080,
        "path": "/api/v1/event/scrub"
    }
]


I hope this helps.  Again on the GET verbs with the REST API you can (By Name BASE API URI + /name/myIntervalActionName, by ID . BASE API URI + \ID, or ALL BASE API URI).

**Comment by weichou1229** [comment]
@xmlviking 
Could you provide **httpMethod POST** example ?

{
    "name": "post-action",
    "interval": "every20s",
    "target": "edgex-device-modbus",
    "protocol": "http",
    **"httpMethod": "POST",**
    "address": "localhost",
    "port": 49991,
    "path":"/api/v1/device/name/Modbus TCP test device/Switch"
}' "http://localhost:48085/api/v1/intervalaction"

**Comment by xmlviking** [comment]
There is one there? 

> We can now POST a new IntervalAction using the following similar pattern

POST - (using Body content-type raw JSON(application/json)

http://localhost:48085/api/v1/intervalaction

BODY
{
"name": "scrub-alt-test",
"interval": "midnight",
"target": "core-data",
"protocol": "http",
"httpMethod": "DELETE",
"address": "localhost",
"port": 48080,
"path": "/api/v1/event/scrub"
}
RESPONSE
8b452368-5a2d-485f-91a8-e087b9f78314 
>

**Comment by weichou1229** [comment]
No, it's DELETE.
I need POST.
{
"name": "post-action",
"interval": "every20s",
"target": "edgex-device-modbus",
"protocol": "http",
"httpMethod": "POST", <===== I need the example for POST
"address": "localhost",
"port": 49991,
"path":"/api/v1/device/name/Modbus TCP test device/Switch"
}

**Comment by xmlviking** [comment]
@weichou1229 
Oh ok you use the combination of what you had listed and the parameters property:
{
"name": "post-action",
"interval": "every20s",
"target": "edgex-device-modbus",
"protocol": "http",
"httpMethod": "POST", <===== I need the example for POST
"parameters": "{ }"
"address": "localhost",
"port": 49991,
"path":"/api/v1/device/name/Modbus TCP test device/Switch"
}
The scheduler parses the parameters and produces a content-length header as well based on your supplied body.   I'm not sure what you want to POST but the "parameters" property is what your looking for.

**Comment by weichou1229** [comment]
I tried, but it not work.

**Comment by xmlviking** [comment]
Could you show me what you tried to POST?  I will try to trouble shoot what your seeing.

**Comment by weichou1229** [comment]
@xmlviking 
For example, I want to run off the light every midnight. so I need to set up a scheduler to do this job.

Steps:
1. Deploy EdgeX with device-virtual
2. Execute the following command to create interval action.
```
curl -X POST -H "Content-Type: application/json" -d '{
    "name": "every20s",
    "frequency": "PT20S"
}' "http://localhost:48085/api/v1/interval"

curl -X POST -H "Content-Type: application/json" -d '{
    "name": "put-action",
    "interval": "every20s",
    "target": "edgex-device-modbus",
    "protocol": "http",
    "httpMethod": "PUT",
    "address": "localhost",
    "port": 49990,
    "path":"/api/v1/device/name/Random-Boolean-Device/RandomValue_Bool",
    "parameters": "{\"RandomValue_Bool\": \"true\",\"EnableRandomization_Bool\": \"true\"}"
}' "http://localhost:48085/api/v1/intervalaction"
```


The log shows **no request body provided**
```
level=INFO ts=2019-07-12T16:50:24.014055Z app=edgex-support-scheduler source=router.go:339 msg="posting new intervalAction: {\"name\":\"put-action\",\"interval\":\"every20s\",\"parameters\":\"{\\\"RandomValue_Bool\\\": \\\"true\\\",\\\"EnableRandomization_Bool\\\": \\\"true\\\"}\",\"target\":\"edgex-device-modbus\",\"protocol\":\"http\",\"httpMethod\":\"PUT\",\"address\":\"localhost\",\"port\":49990,\"path\":\"/api/v1/device/name/Random-Boolean-Device/RandomValue_Bool\"}"
level=WARN ts=2019-07-12T16:50:24.018159Z app=edgex-support-scheduler source=schedule.go:234 msg="scheduler could not find interval id with intervalAction name : put-action"
level=DEBUG ts=2019-07-12T16:50:24.022321Z app=edgex-support-scheduler source=schedule.go:270 msg="adding the intervalAction with id  : 65fe36f5-f339-4877-aa23-3a4fa9e0bc07 to interval : every20s into the queue"
level=INFO ts=2019-07-12T16:50:24.022607Z app=edgex-support-scheduler source=schedule.go:298 msg="added the intervalAction with id: 65fe36f5-f339-4877-aa23-3a4fa9e0bc07 to interal: every20s into the queue"
level=DEBUG ts=2019-07-12T16:50:27.231821Z app=edgex-support-scheduler source=schedule.go:421 msg="executing interval, detail : {{\"Timestamps\":{},\"id\":\"74b8d484-b763-4bcc-afda-72433abcaafc\",\"name\":\"every20s\",\"frequency\":\"PT20S\"}} , at : 2019-07-13 00:50:27.452926 +0800 CST m=+42.227788163"
level=DEBUG ts=2019-07-12T16:50:27.233311Z app=edgex-support-scheduler source=schedule.go:448 msg="1 interval action need to be executed."
level=DEBUG ts=2019-07-12T16:50:27.233709Z app=edgex-support-scheduler source=schedule.go:452 msg="the event with id : 65fe36f5-f339-4877-aa23-3a4fa9e0bc07 belongs to interval : 74b8d484-b763-4bcc-afda-72433abcaafc will be executing!"
level=DEBUG ts=2019-07-12T16:50:27.234046Z app=edgex-support-scheduler source=schedule.go:456 msg="the event with id : 65fe36f5-f339-4877-aa23-3a4fa9e0bc07 will request url : http://localhost:49990/api/v1/device/name/Random-Boolean-Device/RandomValue_Bool"
level=DEBUG ts=2019-07-12T16:50:27.238034Z app=edgex-support-scheduler source=schedule.go:485 msg="execution returns status code : 400"
level=DEBUG ts=2019-07-12T16:50:27.23839Z app=edgex-support-scheduler source=schedule.go:486 msg="execution returns response content : no request body provided; PUT /api/v1/device/name/Random-Boolean-Device/RandomValue_Bool\n"
level=DEBUG ts=2019-07-12T16:50:27.238677Z app=edgex-support-scheduler source=schedule.go:495 msg="requeue interval, detail : {\"Timestamps\":{},\"id\":\"74b8d484-b763-4bcc-afda-72433abcaafc\",\"name\":\"every20s\",\"frequency\":\"PT20S\"}"
level=DEBUG ts=2019-07-12T16:50:47.227659Z app=edgex-support-scheduler source=schedule.go:421 msg="executing interval, detail : {{\"Timestamps\":{},\"id\":\"74b8d484-b763-4bcc-afda-72433abcaafc\",\"name\":\"every20s\",\"frequency\":\"PT20S\"}} , at : 2019-07-13 00:50:47.452926 +0800 CST m=+62.227788163"
level=DEBUG ts=2019-07-12T16:50:47.228937Z app=edgex-support-scheduler source=schedule.go:448 msg="1 interval action need to be executed."
level=DEBUG ts=2019-07-12T16:50:47.229207Z app=edgex-support-scheduler source=schedule.go:452 msg="the event with id : 65fe36f5-f339-4877-aa23-3a4fa9e0bc07 belongs to interval : 74b8d484-b763-4bcc-afda-72433abcaafc will be executing!"
level=DEBUG ts=2019-07-12T16:50:47.229443Z app=edgex-support-scheduler source=schedule.go:456 msg="the event with id : 65fe36f5-f339-4877-aa23-3a4fa9e0bc07 will request url : http://localhost:49990/api/v1/device/name/Random-Boolean-Device/RandomValue_Bool"
level=DEBUG ts=2019-07-12T16:50:47.230629Z app=edgex-support-scheduler source=schedule.go:485 msg="execution returns status code : 400"
level=DEBUG ts=2019-07-12T16:50:47.230934Z app=edgex-support-scheduler source=schedule.go:486 msg="execution returns response content : no request body provided; PUT /api/v1/device/name/Random-Boolean-Device/RandomValue_Bool\n"

```

**Comment by xmlviking** [comment]
Ok this is a bug.  I am looking through the code and I don't think we have ever used POST or PUT IntervalActions verb types.   I can see were missing any kind of body buffer io operations. The fix will not be to bad as were currently passing the parameters property optionally.     I will see to it that both the HTTPMethod types POST and PUT are working correctly.
