### ISSUE TITLE
core-data cannot send zero mq message to export-distro successfully

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#1502]
# 🐞 Bug Report

### Affected Services
The issue is located in:  core-data and export-distro

### Is this a regression?
Yes, the previous version in which this bug was not present was delhi (0.7.1)

### Description and Minimal Reproduction
By default, core-data should push each event to export-distro via 0MQ, but the export-distro doesn't receive any.
core-data did push:

> level=INFO ts=2019-07-04T02:45:40.771164652Z app=edgex-core-data source=event.go:257 msg="Event Published on message queue. Topic: events, Correlation-id: a9bf6cef-5127-46e9-b4cc-795423d79a56 "
> level=INFO ts=2019-07-04T02:45:40.789396646Z app=edgex-core-data source=event.go:239 msg="Putting event on message queue"
> level=INFO ts=2019-07-04T02:45:40.789677613Z app=edgex-core-data source=event.go:257 msg="Event Published on message queue. Topic: events, Correlation-id: 3667e68c-86c6-46fe-b494-0ccdba072719 "

## 🔥 Exception or Error
The log of export-distro doesn't show it receives data, and it sometimes pump the following error:

> level=INFO ts=2019-07-03T13:48:06.832822052Z app=edgex-export-distro source=messaging.go:41 msg="Connecting to incoming message bus at: tcp://edgex-core-data:5563"
> level=INFO ts=2019-07-03T13:48:06.83360274Z app=edgex-export-distro source=messaging.go:50 msg="Connected to inbound event messages for topic: events"
> level=INFO ts=2019-07-03T13:48:06.833719582Z app=edgex-export-distro source=main.go:53 msg="Service dependencies resolved..."
> level=INFO ts=2019-07-03T13:48:06.833762392Z app=edgex-export-distro source=main.go:54 msg="Starting edgex-export-distro 1.0.0 "
> level=INFO ts=2019-07-03T13:48:06.833814419Z app=edgex-export-distro source=main.go:57 msg="This is the Export Distro Microservice"
> level=INFO ts=2019-07-03T13:48:06.833864992Z app=edgex-export-distro source=main.go:66 msg="Service started in: 1.21739086s"
> level=INFO ts=2019-07-03T13:48:06.833911588Z app=edgex-export-distro source=main.go:67 msg="Listening on port: 48070"
> level=INFO ts=2019-07-03T13:48:06.83637125Z app=edgex-export-distro source=registrations.go:306 msg="Starting Export Distro :48070"
> level=INFO ts=2019-07-03T13:48:06.838738526Z app=edgex-export-distro source=init.go:247 msg="Writeable configuration has been updated from the Registry"
> level=INFO ts=2019-07-03T13:48:06.846716769Z app=edgex-export-distro source=registrations.go:340 msg="Starting registration loop"
**level=ERROR ts=2019-07-03T13:53:46.982689813Z app=edgex-export-distro source=registrations.go:346 msg="exit msg: found more than 2 incoming messages (1 is no topic, 2 is topic and message), but found: 3"**

## 🌍  Your Environment
**Deployment Environment:**
x86 or arm64

**EdgeX Version:**
1.0.0 edinburgh

**Anything else relevant?**
In 0.7.1 delhi, the log of export-distro normally shows

> INFO: 2019/07/02 15:11:51 Service dependencies resolved...
> INFO: 2019/07/02 15:11:51 Starting edgex-export-distro 0.7.1 
> INFO: 2019/07/02 15:11:51 This is the Export Distro Microservice
> INFO: 2019/07/02 15:11:51 Starting Export Distro :48070
> INFO: 2019/07/02 15:11:51 Connecting to incoming 0MQ at: tcp://edgex-core-data:5563
> INFO: 2019/07/02 15:11:51 Connected to inbound 0MQ
> INFO: 2019/07/02 15:11:51 Starting registration loop
> INFO: 2019/07/02 15:11:53 Event received: {"id":"5d1b74390e36080001ba3f09","pushed":0,"device":"GroveDevice","created":1562080313401,"modified":0,"origin":1562080313000,"schedule":null,"event":null,"readings":[{"id":"5d1b74390e36080001ba3f0a","pushed":0,"created":1562080313401,"origin":0,"modified":0,"device":"GroveDevice","name":"LightIntensity","value":"6.79905272e+00"}]}
> INFO: 2019/07/02 15:11:53 Event received: {"id":"5d1b74390e36080001ba3f0b","pushed":0,"device":"GroveDevice","created":1562080313406,"modified":0,"origin":1562080313000,"schedule":null,"event":null,"readings":[{"id":"5d1b74390e36080001ba3f0c","pushed":0,"created":1562080313406,"origin":0,"modified":0,"device":"GroveDevice","name":"SoundIntensity","value":"1.34259999e+00"}]}
> INFO: 2019/07/02 15:11:53 Event received: {"id":"5d1b74390e36080001ba3f0d","pushed":0,"device":"GroveDevice","created":1562080313410,"modified":0,"origin":1562080313000,"schedule":null,"event":null,"readings":[{"id":"5d1b74390e36080001ba3f0e","pushed":0,"created":1562080313410,"origin":0,"modified":0,"device":"GroveDevice","name":"RotaryAngle","value":"3.00045898e+02"},{"id":"5d1b74390e36080001ba3f0f","pushed":0,"created":1562080313410,"origin":0,"modified":0,"device":"GroveDevice","name":"RotaryVoltage","value":"5.01270008e+00"}]}
> INFO: 2019/07/02 15:11:55 Event received: {"id":"5d1b743b0e36080001ba3f10","pushed":0,"device":"GroveDevice","created":1562080315398,"modified":0,"origin":1562080315000,"schedule":null,"event":null,"readings":[{"id":"5d1b743b0e36080001ba3f11","pushed":0,"created":1562080315398,"origin":0,"modified":0,"device":"GroveDevice","name":"LightIntensity","value":"6.76178741e+00"}]}
> INFO: 2019/07/02 15:11:55 Event received: {"id":"5d1b743b0e36080001ba3f15","pushed":0,"device":"GroveDevice","created":1562080315406,"modified":0,"origin":1562080315000,"schedule":null,"event":null,"readings":[{"id":"5d1b743b0e36080001ba3f16","pushed":0,"created":1562080315406,"origin":0,"modified":0,"device":"GroveDevice","name":"SoundIntensity","value":"1.37689996e+00"}]}
> INFO: 2019/07/02 15:11:55 Event received: {"id":"5d1b743b0e36080001ba3f12","pushed":0,"device":"GroveDevice","created":1562080315404,"modified":0,"origin":1562080315000,"schedule":null,"event":null,"readings":[{"id":"5d1b743b0e36080001ba3f13","pushed":0,"created":1562080315404,"origin":0,"modified":0,"device":"GroveDevice","name":"RotaryAngle","value":"3.00045898e+02"},{"id":"5d1b743b0e36080001ba3f14","pushed":0,"created":1562080315404,"origin":0,"modified":0,"device":"GroveDevice","name":"RotaryVoltage","value":"5.01270008e+00"}]}
> INFO: 2019/07/02 15:11:57 Event received: {"id":"5d1b743d0e36080001ba3f17","pushed":0,"device":"GroveDevice","created":1562080317402,"modified":0,"origin":1562080317000,"schedule":null,"event":null,"readings":[{"id":"5d1b743d0e36080001ba3f18","pushed":0,"created":1562080317402,"origin":0,"modified":0,"device":"GroveDevice","name":"LightIntensity","value":"6.79905272e+00"}]}

**Comment by tsconn23** [comment]
@cloudxxx8 I'm unable to duplicate this using the `edinburgh` branch. My steps to try and repro are as follows

- Clean Mongo
- Start all edgex services via `make run`
- Start sample export-client
- Start device-random

The expectation is that I should see the events from `device-random` published to my sample client.

Logs from edgex services showing client registration (some irrelevant entries omitted)
```
level=INFO ts=2019-07-05T16:33:45.407685Z app=edgex-export-distro source=registrations.go:306 msg="Starting Export Distro :48070"
level=INFO ts=2019-07-05T16:33:45.407753Z app=edgex-export-distro source=main.go:67 msg="Listening on port: 48070"
level=INFO ts=2019-07-05T16:33:45.418354Z app=edgex-export-distro source=registrations.go:340 msg="Starting registration loop"
level=INFO ts=2019-07-05T16:33:49.756113Z app=edgex-export-distro source=registrations.go:356 msg="Registration changes"
level=INFO ts=2019-07-05T16:33:49.757107Z app=edgex-export-distro source=registrations.go:236 msg="registration loop started: dell-ecp-client"
```
Logs from edgex services showing event is published from core-data to export distro
```
level=INFO ts=2019-07-05T16:34:15.153372Z app=edgex-core-data source=event.go:239 msg="Putting event on message queue"
level=INFO ts=2019-07-05T16:34:15.154085Z app=edgex-core-data source=event.go:239 msg="Putting event on message queue"
level=INFO ts=2019-07-05T16:34:15.154453Z app=edgex-core-data source=event.go:257 msg="Event Published on message queue. Topic: events, Correlation-id: 55f429d3-ba79-448d-93c1-58eaa7392fc9 "
level=INFO ts=2019-07-05T16:34:15.154891Z app=edgex-core-data source=event.go:239 msg="Putting event on message queue"
level=INFO ts=2019-07-05T16:34:15.15521Z app=edgex-core-data source=event.go:257 msg="Event Published on message queue. Topic: events, Correlation-id: 2f26dd8b-ac4b-488d-9a39-db2f4010f3a5 "
level=INFO ts=2019-07-05T16:34:15.456469Z app=edgex-core-data source=event.go:257 msg="Event Published on message queue. Topic: events, Correlation-id: 067b30b6-8263-49eb-b40d-c490033ea571 "
level=INFO ts=2019-07-05T16:34:15.492318Z app=edgex-export-distro source=httpsender.go:67 correlation-id=067b30b6-8263-49eb-b40d-c490033ea571 duration=34.687046ms msg="Response: 200 OK"
level=INFO ts=2019-07-05T16:34:15.496764Z app=edgex-export-distro source=httpsender.go:73 msg="Sent data: 7B226964223A2236353232323334322D386436612D346664382D393833612D323835376263336237396538222C22646576696365223A2252616E646F6D2D496E74656765722D47656E657261746F723031222C226F726967696E223A313536323334343435353134323238383030302C2272656164696E6773223A5B7B226964223A2237393662643038322D613135642D346164302D616463312D343230666537386434616534222C226F726967696E223A313536323334343435353134323133303030302C22646576696365223A2252616E646F6D2D496E74656765722D47656E657261746F723031222C226E616D65223A2252616E646F6D56616C75655F496E743332222C2276616C7565223A222D323234353633333034227D5D7D"
```
Logs from sample client confirming receipt of the event
```
level=INFO ts=2019-07-05T16:33:49.749278Z source=main.go:32 msg="bootstrap OK"
level=INFO ts=2019-07-05T16:33:49.753623Z source=logging.go:26 duration=4.268584ms function=registration/Register msg="received client id ddd8d484-3570-4553-a2b4-e14f31de55be"
level=INFO ts=2019-07-05T16:33:49.753891Z source=main.go:73 transport=http address=:48050 msg=listening
level=INFO ts=2019-07-05T16:34:15.492066Z source=logging.go:27 duration=32.428605ms function=receiver/AddEvent msg="event id 65222342-8d6a-4fd8-983a-2857bc3b79e8 hash QmZrWxnTLETzJScFvFvQRtBVG1nE5bduxCt3J3YyT3NpJM"
```
We had to thoroughly test this flow for the CBOR work, Rules Engine changes and App-Functions SDK integration so a lot of different folks have run this scenario. I'm pretty confident it's working. If you find more information, post it here.

**Comment by tsconn23** [comment]
@cloudxxx8 Just sent you an email that I believe is related to this. If you like you can try the fix I link to from that email in your local environment and see if it solves the problem. We'll have to take an action on Monday.

**Comment by cloudxxx8** [comment]
@tsconn23 sorry, I just confirmed this issue is invalid, because the receive log won't print anymore in this release.  I opened this issue because of this line https://github.com/edgexfoundry/edgex-go/blob/edinburgh/internal/export/distro/zeromq.go#L70 , but just found out this function is no longer used.  We have confirmed the export-distro works fine with MQTT without any INFO log print out
