### ISSUE TITLE
Add support for username-password authentication and invalid (self-signed) certs

### ISSUE THREAD

**Issue by rudderfree** [edgexfoundry/edgex-go#1504]
Adding the relevant comment chain from PR of issue #1469  
AnthonyMBonafide 14 days ago • Member

I think we need to make the Username portion of the mail.PlainAuth function parameters configurable so that users can specify the credentials for their SMTP server. I think it is valid for someone to require a username and password in order to send mail. This would mean updating the SmtpInfo to include a Username field and then leveraging it here.

Just a side note. In the issue related to this pull request you asked about SMTP servers to use for testing. I have and still use a postfix docker container which you can find here. Under the usage section you can find commands to start the server. The nice thing is that using that container will result in an email actually being sent. I used this to verify your changes. I hope this helps

**Comment by rudderfree** [comment]
https://github.com/edgexfoundry/edgex-go/pull/1469#issuecomment-507827960
https://github.com/edgexfoundry/edgex-go/pull/1469#issuecomment-508720894

**Comment by rudderfree** [comment]
@AnthonyMBonafide Looks like we might have to do our own version of smtp.SendMail() to accomplish this, because there seems to be no way of passing InsecureSkipVerify or leveraging any other parameters that are being passed to pass the same information to smtp.SendMail()

**Comment by AnthonyMBonafide** [comment]
I think you are correct and we will have to connect and/or send the mail via another mechanism. I poked around for a bit while verifying PR #1469 and was not able to find anything that would allow for this with the way we are doing things now. This will require some investigation to see how we can accomplish this and what is the best way to seamlessly incorporate it into our existing implementation.

**Comment by rudderfree** [comment]
I have done a version of SendMail function, the function declaration looks like this.

`func sendMail(addr string, a mail.Auth, from string, to []string, msg []byte, skipVerify bool) error {`

I am in the process of pushing the branch, so that rest of the code can be seen.
I am using it as such in notifications.smtpSend
```
       err := sendMail(smtp.Host+":"+strconv.Itoa(smtp.Port),
                mail.PlainAuth("", smtp.Sender, smtp.Password, smtp.Host),
                smtp.Sender, addressees, []byte(buf.String()), false)
```
Notice the last parameter, that can be passed as the configuration parameter for skipping the verification, it is false to keep the existing functionality intact. also smtp.Sender is actually fulfilling the function of username

**Comment by rudderfree** [comment]
@AnthonyMBonafide I have added the commit at the link below containing the code for the new sendMail function, please take a look, Thx!
https://github.com/rudderfree/edgex-go/commit/91e1d6550d5c0e6b5063180c99bebb9aa922aaa8

**Comment by rudderfree** [comment]
Not exactly a fan of this solution, but I don't see any other way to manipulate tls.Config using any other method or code from outside of smtp.SendMail. The only other way I see is to raise this with go lang maintainers and see if they can expose in someway the ability to set-reset the InsecureSkipVerify flag. The smtp package seems to have been frozen.

**Comment by AnthonyMBonafide** [comment]
We may also want to update the mail sender to allow for specifying a `username` separate from the `sender`. Right now we are using the `sender` as the username to authenticate with the SMTP server, and as the name associated with the sender portion of the email. I think it would be useful to have these be different values. Just a thought

**Comment by rudderfree** [comment]
> We may also want to update the mail sender to allow for specifying a `username` separate from the `sender`. Right now we are using the `sender` as the username to authenticate with the SMTP server, and as the name associated with the sender portion of the email. I think it would be useful to have these be different values. Just a thought

@AnthonyMBonafide Yes, I agree, I had given it some thought. 

So, I have added the Username field to SmtpInfo and configuration.toml, tested it, and it works. I think there will be some work required in the sender function (notifications.smtpSend) for setting the flag true (as in when), and I am not sure but does this field also gets stored in the db(?)

The  commit is here at https://github.com/rudderfree/edgex-go/commit/613679d58a7a2c84833e8b9fd943299953de3e7c, if it looks good, let me know I will create the PR.

**Comment by rudderfree** [comment]
Merged, closing.
