### ISSUE TITLE
modbus example in docs is not working...

### ISSUE THREAD

**Issue by horoyoii** [edgexfoundry/edgex-go#1506]
I just followed the example of modbus but following errors has occurred. 

When I sent following 'GET' method using postman,
`http://localhost:48082/api/v1/device/19728d2c-f422-40e6-bcd2-c0067c1cf9e0/command/e2745b58-d4a1-4cf1-ac9a-93cabe3e98f8`

the response body is like this.
`Handler - execReadCmd: error for Device: DENT's Motor cmd: Configuration, unable to create TCP connection info, protocol config 'Address' not exist /api/v1/device/19728d2c-f422-40e6-bcd2-c0067c1cf9e0/Configuration`

and I checked the logs of device-modbus container, it said 
`http://localhost:48082/api/v1/device/19728d2c-f422-40e6-bcd2-c0067c1cf9e0/command/e2745b58-d4a1-4cf1-ac9a-93cabe3e98f8`

* I'm not fully understanding of edgeX foundry and just following the examples in docs... 
so could you tell me what i'm missing.

* I'm a college student in Korea who lacks experience but is interested in this project.

**Comment by mhall119** [comment]
What version of EdgeX are you using? 1.0 "Edinburgh" was just released last week, but the docs might still be for the previous "Delhi" release.

**Comment by tsconn23** [comment]
@horoyoii Please take this to the #help channel in edgexfoundry.slack.com
