### ISSUE TITLE
Edinburgh: Update Messaging Module Reference due to Race Condition

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1509]
Myself, @xmlviking and @brandonforster have all confirmed the possibility of an error due to a race condition in the go-mod-messaging module. As is the case with race conditions, it doesn't happen all the time but we have each experienced it using the following steps. All services below are running natively.

1.) Clean your database
2.) Build the Edinburgh branch of edgex-go
3.) Build device-random (at the current time `master` is fine)
4.) Bring up edgex-go services via `make run`
5.) Bring up device-random

In each case where you go through this scenario, you have a good chance of encountering the following error:

```
level=ERROR ts=2019-07-05T23:31:37.314722Z app=edgex-core-data source=event.go:255 msg="Unable to send message for event: {\"id\":\"e7dfcec9-0db7-45c3-bc20-1473d81046a5\",\"device\":\"Random-Integer-Generator01\",\"origin\":1562369497307028000,\"readings\":[{\"id\":\"a845adba-b390-42c3-ae6b-d00cf96e9bb7\",\"origin\":1562369497306850000,\"device\":\"Random-Integer-Generator01\",\"name\":\"RandomValue_Int16\",\"value\":\"6252\"}]} error: address already in use [tcp://*:5563]"
```

The "address already in use" is happening due to two goroutines going into the same block of logic to bind the message client to the ZeroMQ port. When this happens, it hoses the connection to ZeroMQ. It will look like core-data is processing subsequent messages just fine but in truth, they're getting dropped. 

A fix for this has already been made to the go-mod-messaging module via https://github.com/edgexfoundry/go-mod-messaging/pull/26

To fix this issue in Edinburgh, the above update must be consumed via the edgex-go `go.mod` in the Edinburgh branch.

**Comment by anonymouse64** [comment]
Does this mean that we will have a 1.0.1 edinburgh release?

**Comment by tsconn23** [comment]
That will be discussed on Wednesday's TSC call
