### ISSUE TITLE
Ensure Services running in EdgeX are those expected and authorized

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1518]
# 🚀 Ensure Services running in EdgeX are those expected and authorized
EdgeX is a collection of containerized micro services. How does one ensure that the containers running on your edge node are to be trusted and just those expected.

Container engines offer a secure mode, which can be used to check that each container to be launched is signed by a trusted entity. This minimally requires that containers be signed before being published/released. This becomes meta data associated with the container.

The container engine would need to be launched in trusted/secure mode.
Docker Engine trust information:  https://docs.docker.com/engine/security/trust/content_trust/.
Ubuntu snaps would have a similar solution.

But EdgeX allows custom code to be deployed such as Device Services and Application pipeline components. The vendor developing a vertical solution or a system integrator would be creating these. The signee would not be  EdgeX. Does container engine trust extend to a whitelist of signatories? 

### Relevant Package
All EdgeX micro service artifacts.

### Description
EdgeX is a collection of containerized micro services. How does one ensure that the containers running on  edge nodes are just those expected and can be trusted.

Seeking input from the community and DevOps folks on what they expect with respect to expected and authorized services to establish the scope of this feature. Then to deliver on it possibly iteratively (first just EdgeX micro services and processes, then custom services).

### Describe the solution you'd like
Container engines offer a secure mode, which can be used to check that each container to be launched is signed by a trusted entity. This minimally requires that containers be signed before being published/released. This becomes meta data associated with the container.

The container engine would need to be launched in trusted/secure mode.
Docker Engine trust information:  https://docs.docker.com/engine/security/trust/content_trust/.
Ubuntu snaps would have a similar solution.

But EdgeX allows custom code to be deployed such as Device Services and Application pipeline components. The vendor developing a vertical solution or a system integrator would be creating these. Also AppStores that provide micro services, Machine Learning models would fall into this scope. The signee in these cases certainly would not be  EdgeX. Do container engines that provide trust extend to a whitelist of signatories? 

### Describe alternatives you've considered
Leave things as they are, assuming that during deployment, that is at start time only known and trusted software will be launched on the  edge node and in future when Over-the-Air update is supported, the management agent/endpoint/orchestrator will push only known good software onto the node using a combination of a secure transmission channel and possibly mutual client-server authentication using certificates.

**Comment by mkbhanda** [comment]
Another resource: https://researcher.watson.ibm.com/researcher/view_group.php?id=9510

**Comment by anonymouse64** [comment]
All snaps are cryptographically signed by Canonical GPG keys when they are uploaded to the Snap Store and using snaps requires trust of the Canonical keys, so this is pretty much a no-op for snaps. 
Independent vendors when developing their device services or app function services as snaps will also end up being signed by Canonical GPG keys when they are uploaded to the Snap Store so using snaps provides this functionality out of the box.

**Comment by tingyuz** [comment]
looking for more clarification on the topic. Can we discuss this item in the next meeting?

**Comment by mkbhanda** [comment]
Addressing this as a deployment best practice. New documentation issue opened: https://github.com/edgexfoundry/edgex-docs/issues/60
