### ISSUE TITLE
Remove 'docs' from edgex-go

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1528]
Per the 10-Jul-19 TSC call, it sounds like we have confirmation that the content in the new [edgex-docs](https://github.com/edgexfoundry/edgex-docs) repo have been approved and are considered complete. In the 11-Jul-19 DevOps call, @ernestojeda confirmed that the docs-verify job has been removed from edgex-go builds. That means we can delete the entire `docs` directory from this project.

@mhall119 for visibility. Please +1 if you agree this can be worked.

**Comment by mhall119** [comment]
+1 from me. Should this be removed from the `edinburgh` branch as well, or just the `master` branch?
