### ISSUE TITLE
Update Snap to use Consul 1.5

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/edgex-go#1531]
# 🚀 Feature Request

### Relevant Package
This feature request is targeting the Snap build sequence.

### Description
The Snap build should be updated to use Consul version 1.5. As part of the work from upgrading from 1.3.1, the Snap build path for Consul will have to change from using vendoring to using Go modules.

**Comment by anonymouse64** [comment]
Closing since switching consul version was rolled back in #1560
