### ISSUE TITLE
Migrate Security-API-Gateway to EdgeX-Go

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#1532]
This issue is created to track the progress of moving security-API-Gateway project ( currently as a standalone project) into EdgeX-Go project.

**Comment by tsconn23** [comment]
Recommend the scope of this migration target the tip of master as of 11-Jul-2019. https://github.com/edgexfoundry/security-api-gateway

Outstanding issues from the above repo that the Security WG has agreed to take on should then be migrated to this one and tagged with the "security" label. The `edgex-go` issues will then form the subsequent backlog for enhancements to this service.

**Comment by tingyuz** [comment]
security-api-gateway has been renamed to security-proxy-setup and merged into EdgeX-Go, hence close the issue.
