### ISSUE TITLE
Support Kafka Client in Export Services

### ISSUE THREAD

**Issue by xiaosuiba** [edgexfoundry/edgex-go#1533]
# 🚀 Feature Request

### Relevant Package

 This feature request is for export-client and export-distro

### Description
Currently, the export service only support two types of destinations: push to a REST endpoint, or publish to a designated MQTT broker's topic. In some scenarios, we would like to export event to a kafka cluster. For example, we could run a Flink container on the edge and subscribe events of devices. 

### Describe the solution you'd like
 Please add a new destination type in export servers to support Kafka.

**Comment by tsconn23** [comment]
Export services will be deprecated after the Fuji release. You should look to the [application functions sdk](https://github.com/edgexfoundry/app-functions-sdk-go) instead for this kind of integration.

**Comment by xiaosuiba** [comment]
OK, I'll take a look at that, thanks.

**Comment by xiaosuiba** [comment]
> Export services will be deprecated after the Fuji release. You should look to the [application functions sdk](https://github.com/edgexfoundry/app-functions-sdk-go) instead for this kind of integration.

OK, I'll take a look at that, thanks.
