### ISSUE TITLE
use configuration.toml file to decide if remote logging is needed

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#1540]
Similar to other microservices that have entry in the configuration.toml to decide if remote logging is needed, security-proxy-setup need to add such entry so that remote logging can be enabled.

**Comment by tsconn23** [comment]
This will be resolved when the new PR is created from the new feature branch.

**Comment by tingyuz** [comment]
This has been addressed with the latest merge of security-proxy-setup to edgex-go.
