### ISSUE TITLE
Drop Get from the function names in the security-proxy-setup project

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#1542]
There are a couple of functions with Get-* prefix that return values such as  GetProxyServerName(). It is suggested to drop Get from the function names.

**Comment by anonymouse64** [comment]
Note that whether these interfaces should be used at all should be a topic of discussion for this week's WG meeting

**Comment by tsconn23** [comment]
This will be resolved when the new PR is created from the new feature branch. All of these methods and their associated interfaces have been dropped.

**Comment by tingyuz** [comment]
This has been addressed & security-proxy-setup has been merged in the edgex-go, hence close the issue.
