### ISSUE TITLE
Edinburgh -- Address Docker-Compose Bootstrap Issues

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1544]
There are timing issues in the Edinburgh docker-compose bootstrapping process that have been identified and root caused. These issues occur when no volumes are present and must be created for the first time via `docker-compose up`. To replicate use the Edinburgh "no security" [compose file](https://github.com/edgexfoundry/developer-scripts/blob/master/compose-files/docker-compose-edinburgh-no-secty-1.0.0.yml)

1.) `docker volume prune`
2.) `docker-compose -f docker-compose-edinburgh-no-secty-1.0.0.yml up`

You will observe two symptoms caused by three different issues. I will detail the symptoms here.

1.) Support-logging is the first service to come up. However there is additional latency for this to occur as the volume is being created. Other services start coming up and try to log their startup info remotely via support-logging. Since the actual API router in support-logging doesn't come up until the config is read and connectivity to the database is established, these other services will all throw "connection refused" errors when attempting to log for a period of time. This eventually corrects itself.
2.) The flow whereby the RulesEngine registers as an export-client, which should then trigger a notification to export-distro so that it will publish events is disrupted by the additional volume creation latency. This results in no events ever reaching the Rules Engine.

It should be noted that you can go through the scenario above and experience these errors and then shut the whole thing down via `docker-compose down`. If you then bring the services back up without pruning your docker volumes, the whole thing works just fine. I suspect most of us were using this latter approach without thinking to prune the underlying volumes as would be done on a brand new deployment.

I will also point out that the code that will be associated with this issue for the dot release is targeting these symptoms. There are more fundamental issues with regard to service bootstrapping in a containerized environment that will need to be addressed for a long term fix. I do not yet have a view on what these long term patterns should be, but the operability of this process is pretty essential for Edinburgh.

**Comment by anonymouse64** [comment]
> disrupted by the additional volume creation latency

How is it disrupted? Is it just that events are delivered more slowly?

> This results in no events ever reaching the Rules Engine.

I don't follow how this happens, what specifically is blocking delivery of events to the Rules Engine?

**Comment by anonymouse64** [comment]
Also, as a general comment, what files are stored in the volume? I don't see any sockets being stored there, only log files and database files for Redis/Mongo/Consul so I don't see how delivery of ZMQ messages could be affected by the existence of slow I/O on the volume.
Also do these issues still only affect macOS users or have the issues been reproduced on Linux (or Windows for that matter)?

**Comment by jpwhitemn** [comment]
Ian - this has been an evolving set of issues that have been communicated in several meetings recently.  These are critical issues (and now fixes the teams have developed) to get in place for a 1.0.1 release - many around race problems.  Rather than consuming the teams' time trying to provide all the details here, please feel free to connect with me directly and I will personally update you (612.916.6693).  Ping me on Slack if you prefer to set up a conference call.

**Comment by anonymouse64** [comment]
@jpwhitemn that's unnecessary, this issue was just quite vague, but Trevor's followup PR description was sufficient for me
