### ISSUE TITLE
Core data stops publishing events to ZMQ afterstress testing 12+ hrs

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#1547]
# 🐞 Bug Report

### Affected Services

The issue is located in: core-data

### Is this a regression?

Yes, the previous version (Delhi) did seem to have this issue, i.e. never reported ....

### Description and Minimal Reproduction
After running for many hours as described below, core-data quits publishing events to ZMQ. Core data is still receiving the events from the device services.
This issue has only been observed once.

Do the following to recreate this issue:
- Build docker images locally from edgex-go:master for core-data & export-distro
- Modify https://github.com/edgexfoundry/developer-scripts/blob/master/compose-files/docker-compose-edinburgh-no-secty-1.0.0.yml to use images just built
- Run EdgeX using modified docker-compose-edinburgh-no-secty-1.0.0.yml
- From Consul set the core-data & export-distro logging levels to TRACE so you can see the data is flowing.
- Using a DB tool like Robo 3T, connect to the EdgeX Mongo instance and set the autoEvents frequency to 500ms for all defined devices in the MetaData
- Restart device-virtual using `docker restart edgex-device-virtual`
- Run device-random natively with AutoEvents frequency set to 500ms for all devices in the local configuration.toml
- Issue should occur if run 12+hrs. 

## 🔥 Exception or Error
No error or crash occurs. Core data just stops publishing to ZMQ.
While the issue was occurring, dropping the Event and Reading collections from the Mongo DB got it working again.

## 🌍  Your Environment
**Deployment Environment:**
Linux Ubuntu 
**EdgeX Version:**
Edinburgh 1.0.0

**Anything else relevant?**
Not at this time

**Comment by tsconn23** [comment]
If someone is able to reproduce, a panic trace or some kind of error would be helpful.

**Comment by lenny-intel** [comment]
I have run going on using the latest with the fix for the Publish race condition after pruning volumes. 19 hrs and still running! :-) Maybe the volume prune was needed??

**Comment by lenny-intel** [comment]
This ran for 21+ hrs without issue. I will run it again later after testing other bootstrap issue fix.

**Comment by jpwhitemn** [comment]
I am on hour 8+ with no issues and will continue to let it run through tomorrow.  Will let you know at tomorrow's core WG meeting of results.

    On Wednesday, July 17, 2019, 12:34:00 PM CDT, Lenny Goodell <notifications@github.com> wrote:  
 
 
This ran for 21+ hrs without issue. I will run it again later after testing other bootstrap issue fix.

**Comment by tsconn23** [comment]
@lenny-intel @jpwhitemn Are we leaving this open or closing? I don't believe we have any duplications of this condition over the last few days.

**Comment by lenny-intel** [comment]
@tsconn23 , @jpwhitemn , I am good with closing it for now and re-open if it pops up again.
