### ISSUE TITLE
Create common marshaling functionality for all REST handlers

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#1567]
# 🚀 Feature Request

### Relevant Package
core-metadata(possibly all core services)

### Description
Create a common pattern for marshaling and unmarshalling  which can be leveraged by all REST handlers to abstract the process of unmarshaling a request body(depending on `Content-Type`) and marshaling to the response body. This will help reduce the amount of both duplicate code and duplicate APIs which perform the same functionality, but only differ in the request content-type and response body. For example,

https://github.com/edgexfoundry/edgex-go/blob/73854f625f543dcd78e33e0be13d55dc32395032/internal/core/metadata/rest_deviceprofile.go#L384

and

https://github.com/edgexfoundry/edgex-go/blob/73854f625f543dcd78e33e0be13d55dc32395032/internal/core/metadata/rest_deviceprofile.go#L409

Both retrieve a device profile by name using the same database functions, but differ only in the request body format, response header `Content-Type`, and the format which the `DeviceProfile` is marshaled.

I think we can abstract the marshaling and unmarshaling processes such that our REST handlers will not care which format the request body is in nor the format of response body and content type. As I see it this will allow us to also remove some of the redundant APIs, like the couple mentioned above, by allowing the client to specify not only the `Content-Type` for the request body, but also the `Accept` header to specify the format and content type they would like in return.

### Describe the solution you'd like
As I am envisioning this, the solution would look something like:

```
func someRestHandlerForCreatingDevice(w http.ResponseWriter, r *http.Request){
    b := ... // Code to get bytes from request
    ct := .. // Code to get content type from request
    someEntitiy, err := device.Unmarshal(b,ct)
   if err != nil{
        // Return Bad Request as we cannot unmarshal
    }

    // Do our normal processing with someEntity as it is a struct we can work with programmaticly 
    ...

    at :=  ... // Code to get Accept type from request
    resp := ... // valid response object. Today we just return "true" :( 
    respType , respBody := device.Marshal(resp,at)

    w.Header().Set("Content-Type", respType)
    w.WriteHeader(http.StatusOK)
    w.Write(respBody)
}
```

With this pattern we can receive `JSON`, `YAML` and possibly `CBOR` all in the same REST handler. Also, we would be able to respond in any of those supported formats. So we can do things like take in `CBOR` and respond in `JSON` if that is what the client wants. If we follow this flow we have to think about how the `Accept` header can be presented. As per the [HTTP spec](https://tools.ietf.org/html/rfc7231#section-5.3.2), the header can contain 0 or more media types. This means we would have to handle the cases were there are more than one content type provided. It seems reasonable to do the following for the situations:

1. No `Accept` header- use a default which applies system wide. Probably `JSON`
2. One supported media-type provided in the `Accept` header - Use the provided media-type in the `Accept` header
3. One unsupported media-type provided in the `Accept` header - Return a [406 (Not Acceptable)](https://tools.ietf.org/html/rfc7231#section-6.5.6)
4. Multiple unsupported media-types in the `Accept` header - Return a [406 (Not Acceptable)](https://tools.ietf.org/html/rfc7231#section-6.5.6)
5. Multiple supported media-types in the `Accept` header without weights- pick the first supported media-type listed in the `Accept` header as it has been listed by the client.
6.  Multiple supported media-types in the `Accept` header with weights - pick the supported media-type with the highest weight

### Describe alternatives you've considered
None, this is a new feature request to improve the current implementation. The alternative is to continue with the current pattern.

**Comment by tsconn23** [comment]
The `Unamrshal()` portion of the enhancement sounds similar to the [RequestReader](https://github.com/edgexfoundry/edgex-go/blob/4d276e7052b68daf3c5a40e8311f5b0a5557fba6/internal/core/data/io.go#L88) you implemented for core-data/AddEvents.

w/r/t handling the Accept header, we could probably put that into GorillaMUX [middleware](https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/correlation/middleware.go).

**Comment by AnthonyMBonafide** [comment]
This issue may overlap with #1573

**Comment by michaelestrin** [comment]
Closed.  Expect to be addressed by [Geneva v2 API](https://github.com/tsconn23/edgex-geneva-api) changes.
