### ISSUE TITLE
Eliminate Literals from API Endpoint Responses

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1573]
We currently have API endpoints that return string literals instead of a formal response object. Here are some examples:

- GET <any service>/api/v1/ping returns `pong`
- POST core-data/api/v1/event returns `id of new event`
- POST core-data/api/v1/valuedescriptor returns `id of new value descriptor`
- PUT core-metadata/api/v1/device returns `true`
- DELETE core-metadata/api/v1/device/id/{id} returns `true`
- Errors when they occur write out a literal string to the caller.

Instead, API responses should be well formatted types that can be unmarshaled by the caller. In cases where we need to indicate success for an operation that returns no content, rather than a literal "true" we should be using an HTTP status code to indicate that success.

I'm creating this issue to track the desire for a complete audit of the services in edgex-go w/r/t their responses. I would like to see these changes included for the Geneva release.

**Comment by michaelestrin** [comment]
Closed.  Expect this to be addressed by the [Geneva v2 API](https://github.com/tsconn23/edgex-geneva-api) changes.
