### ISSUE TITLE
Explore Use of QueryStrings For Specifying Limit / MaxResultCount

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1574]
Sourced from a discussion in this thread https://github.com/edgexfoundry/edgex-go/issues/1326

Explore the possibility of utilizing a "limit" querystring parameter rather than a routing segment in order to specify the maximum number of results returned by a GET request.

For example, the following core-data endpoint will return events for a given device, capped at the number provided in the `{limit}` segment

`/event/device/{deviceId}/{limit}`

We should explore implementing an alternative mechanism like so

`/event/device/{deviceId}?limit=100`

The old endpoint MUST be maintained for backward compatibility. If this can be done in a backward-compatible manner for 1.x releases, then we can assign this issue and others like it to the Fuji release cycle. This issue will track the one specific use case above. If we decide to adopt the pattern, subsequent issues will be used to track specific API route changes.

**Comment by AnthonyMBonafide** [comment]
Do you think it would be beneficial to support more of a page response? For example, query parameters like `page size` and `page offset`. My thought here is that if we have 1 million devices, and the `MaxResultCount` is something lower, like `1,000`. We will never be able to get all the devices as we will always be limited to the `MaxResultCount`(1,000) regardless of the `limit` query parameter.

Another thought, should we consider supporting `chucked`/streaming responses? As these responses get bigger we will be consuming a lot of memory while building the response for the user. If we return `1,000` devices, we could be using a lot of memory where as if we stream we could get the same result as if were only stream say `100` devices.

**Comment by tsconn23** [comment]
For answers to those questions, I would rely on input from our UI teams or else from a partner company bringing a real business requirement. I don't want to build that stuff to support a hypothetical case.

**Comment by anonymouse64** [comment]
> Do you think it would be beneficial to support more of a page response?

Yes, this is how I've seen it implemented in other APIs and how I'd recommend it. As I mentioned on the original issue, I think there should be both server side limits, and client side limits. The `limit` paramater here in the naive implementation would be a client side limit, but it would be much more useful it if paging was implemented.

**Comment by tsconn23** [comment]
> Do you think it would be beneficial to support more of a page response? For example, query parameters like `page size` and `page offset`. My thought here is that if we have 1 million devices, and the `MaxResultCount` is something lower, like `1,000`. We will never be able to get all the devices as we will always be limited to the `MaxResultCount`(1,000) regardless of the `limit` query parameter.
> 
@AnthonyMBonafide I'm putting this into the OpenAPI spec I'm building for the Core Services for the Geneva release. All endpoints returning a list of results will have this capability.

**Comment by tsconn23** [comment]
Closing. This will be facilitated by the pagination that all multi-result GET endpoints must support in the [API 2.0 definition](https://github.com/tsconn23/edgex-geneva-api)
