### ISSUE TITLE
Update APIs to have consistent and deterministic HTTP responses

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#1581]
# 🚀 Feature Request

### Relevant Package
Core-services

### Description
Address some of the API level inconsistencies within the Core-services. These changes should be integrated within a release where backwards-compatibility is less of an issue.

The core-services' APIs have  inconsistencies regarding HTTP Response codes. Some operations return a `500(Internal Server Error)` if no matching entitiy can be found(restGetProfileByModel, restGetProfileByLabel, etc), while others will return a `404(Not Found)` under the same circumstances(restGetProfileByName, restGetProfileById, etc).

 I also think we should consider using a wider range of HTTP status codes to allow clients to integrate a little easier. This is especially true if a user is using a higher level HTTP client library. I think with how we are communicating a successful creation by returning a `true` string, `200(OK)` status, and `application/json` `Content-Type` would break a few HTTP client libraries as the `true` string is not valid `JSON`. Instead using the `204 No Content` response code would be just as effective.

Here are just some thoughts regarding possible 2xx codes we can use:

1. 201(Created) - For any creation API or `POST` operation. We can also respond with the ID in the body of the response

1. 202(Accepted) - For any operation that is not completed when responding to the user. This goes for any additional background processing. This lets the client know that some additional processing must happen. Therefore, if a they receive a `404` trying to obtain some dependant entity, they should not be surprised.

1. 204(No content) - For operations which do not yield a response. like Deletes and maybe some updates.A `true` string in a `200(OK)` response body is redundant and we probably do not need to send that to the client.

### Describe the solution you'd like

1. Consistent responses by the Core-services' APIs for similar circumstances(i.e. Entity not found)

1. More deterministic HTTP response codes and response bodies.

NOTE

I created issue #1567, and @tsconn23 created #1573  which addresses the other issue of invalid response bodies, so that can be addressed in those issues as that might be a much broader issue.

### Describe alternatives you've considered
N/A, as this is an improvement and the alternative to this is to continue with the current structure and flow as it is implemented.

**Comment by anonymouse64** [comment]
> Other APIs return multiple entities but do not perform this check
To me, this sounds like a bug

**Comment by AnthonyMBonafide** [comment]
Should I convert this to a bug?

**Comment by anonymouse64** [comment]
IMHO, the best thing to do would be to split out the parts that are specifically bugs into a different issue (and file that as a bug), and fix those separately from implementing this feature - since those are bugs we could release those fixes sooner than Geneva. Then just trim this issue down to only the enhancement/new feature request part

**Comment by AnthonyMBonafide** [comment]
Will do. I will create a bug and move the `MaxResultCount` portion, and leave the other stuff in this feature issue.

**Comment by michaelestrin** [comment]
Closed.  Expect to be addressed by [Geneva v2 API](https://github.com/tsconn23/edgex-geneva-api) changes.
