### ISSUE TITLE
APIs exceed MaxResultCount

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#1582]
# 🐞 Bug Report

### Affected Services
Core-services and consumers of core-services

The issue is located in: Core-services. I noticed this in core-metadata, but this could exist in others as well. More investigation is required to identify all of the issues

### Is this a regression?

No, the services which I noticed the issue always contained the flawed logic.

### Description and Minimal Reproduction

Some core-services' operations conform to the configuration setting `MaxResultCount` and will return an error if the response is bigger than the `MaxResultCount`. Other APIs return multiple entities but do not perform this check and can exceed the MaxResultCount. For example, `restGetAllDeviceProfiles` performs the check to ensure the limit is not exceeded, but `restGetProfileByModel`, and `restGetProfileByLabel` do not.

## 🔥 Exception or Error
N/A as the offending functionality is flawed due to the lack of error.

## 🌍  Your Environment
Fedora 30 (Linux)

However this issue is not dependant on environment, but rather logic within the code.

**EdgeX Version:**

edinburgh

**Anything else relevant?**

This issue was created from #1581 which is an issue regarding some API cleanup work within core-services

**Comment by akramtexas** [comment]
Fixing this bug will require having the APIs (across core-services) to conform to a single, unified set of configuration settings and to perform a consistent set of checks to ensure that the limit is not exceeded.
