### ISSUE TITLE
make run_docker fails after developer-scripts PR #131

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/edgex-go#1585]
https://github.com/edgexfoundry/developer-scripts/pull/131

The docker-compose files are referenced in `bin/edgex-docker-launch.sh` and reorganizing them has broken `make run_docker` for the moment.  Downloading a compose file and specifying the `$COMPOSE_FILE_PATH` env variable still works.

```
[master] brave:edgex-go jdharms$ make run_docker
bin/edgex-docker-launch.sh
Downloading Docker Compose file...
Starting EdgeX...
ERROR: In file '/tmp/compose-files/docker-compose-edinburgh-1.0.0.yml', the service name 404 must be a quoted string, i.e. '404'.
make: *** [run_docker] Error 1```

**Comment by tsconn23** [comment]
https://github.com/edgexfoundry/edgex-go/pull/1586
