### ISSUE TITLE
Wrong host configuration in System Management Agent docker image

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#1594]
# 🐞 Bug Report

### Affected Services
The issue is located in:  System Management Agent

### Is this a regression?
No

### Description and Minimal Reproduction
https://github.com/edgexfoundry/edgex-go/blob/8b5a3a86adb03d8d3708adf15906ed0d5873a114/cmd/sys-mgmt-agent/res/docker/configuration.toml#L18
It should not be `localhost`, but `edgex-sys-mgmt-agent` according to the docker-compose file in 
https://github.com/edgexfoundry/developer-scripts/blob/deac70c76d9a837a6e9b3f0168aa66f17acf8ed8/releases/edinburgh/compose-files/docker-compose-edinburgh-1.0.1.yml#L234

## 🔥 Exception or Error
health check will always fail on Consul if running in docker enviromnet

## 🌍  Your Environment
**Deployment Environment:**
Docker

**EdgeX Version:**
v1.0.1

**Comment by akramtexas** [comment]
I will address this shortly, keeping in mind that the bug fix will need to go in one more branch (for edinburgh `dot release`) other than master.

**Comment by anonymouse64** [comment]
Should this also be included in the 1.0.1 release, given that we haven't actually tagged 1.0.1 in git yet?

**Comment by akramtexas** [comment]
> Should this also be included in the 1.0.1 release, given that we haven't actually tagged 1.0.1 in git yet?

I will follow up with @tsconn23

**Comment by tsconn23** [comment]
Tag was applied this morning
https://github.com/edgexfoundry/edgex-go/releases/tag/v1.0.1

**Comment by akramtexas** [comment]
Bug fix has been applied to both the `edinburgh` and `master` branches (and also to [PR-1609](https://github.com/edgexfoundry/edgex-go/pull/1609)). Closing this issue, as such.
