### ISSUE TITLE
Create Profile with put-method only Command->the Get method is still created

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-go#1595]
# 🐞 Bug Report

### Affected Services: metadata, command 
 

 The issue is located in: go-mod-core-contracts

### Is this a regression? 

  No, the problem exists in Edinburgh release as well.

### Description and Minimal Reproduction
When creating a profile with a core command that has only one of the methods defined - for example only put method is defined ->  A Get command is still created. 

The problem is within the unmarshaling of the core commands.
Here it is how the Commands struct looks like: 

> type Command struct {
	Timestamps  `yaml:",inline"`
	Id          string `json:"id" yaml:"id,omitempty"`   
	Name        string `json:"name" yaml:"name,omitempty"`
	Get         Get    `json:"get" yaml:"get,omitempty"`  
	Put         Put    `json:"put" yaml:"put,omitempty"`  
	isValidated bool   
}

Get and Put are structs -> even if they are missing in the json (in the body of create Device Profile), the result after unmarshaling is empty struct. (default value of structs)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by brandonforster** [comment]
This is apparently the expected behavior of the Go JSON marshaller.

https://stackoverflow.com/questions/18088294/how-to-not-marshal-an-empty-struct-into-json-with-go

I'll go ahead and implement the pointer solution described.

**Comment by tsconn23** [comment]
@brandonforster Question -- Does that mean calling `String()` on the Command model returns an empty string?

https://github.com/edgexfoundry/go-mod-core-contracts/blob/7f83d8b2411e0538aebb1617e055e464ef7479f6/models/command.go#L107

If so, maybe then the solution is to check the value of `String()` before creating the GET command in the database.

**Comment by brandonforster** [comment]
> @brandonforster Question -- Does that mean calling `String()` on the Command's Get property returns an empty string?

Yes. In `master` and `Edinburgh`, `Command{}.Get.string()` returns `{}`. The crux of this bug is that in `master` and `Edinburgh` `Command{}.string{}` returns `{"get":{},"put":{}}`

 With my current solution `Command{}.string()` returns `{}`, as expected.



> https://github.com/edgexfoundry/go-mod-core-contracts/blob/7f83d8b2411e0538aebb1617e055e464ef7479f6/models/get.go#L47
> 
> If so, maybe then the solution is to check the value of `String()` before creating the GET command in the database.

I think it's a good idea to make sure we're not putting empty structs in the DB, but upon further reflection there definitely is a bug here.

**Comment by brandonforster** [comment]
@tsconn23 @difince I created edgexfoundry/go-mod-core-contracts/issues/139 to track this issue in `core-contracts`. Do we want to keep this issue open to expand its scope, or create a new issue to track any DB input validation we might want to do?

**Comment by tsconn23** [comment]
@difince Any follow-up required on this or are we OK to close?

**Comment by brandonforster** [comment]
Do we want to do an Edinburgh fix too for the next dot release, or is this just going to be as-is for that and it's just going in Fuji?

**Comment by difince** [comment]
Yes, I am OK to close this issue
