### ISSUE TITLE
Adjust baseUri in all RAML files

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1614]
This issue follows from PR https://github.com/edgexfoundry/edgex-go/pull/1599

With the introduction of the `/api/version` endpoint to all of the edgex-go core/support/export services, it is necessary to adjust the RAML files. We created the version endpoint off the base `/api` route because its purpose is to report the version of the compiled service. An `/api/v1/version` endpoint shouldn't respond that its version is something like `v2.x.x` and we don't want to duplicate this endpoint for every major version.

The adjustments that need to be made to all RAML files in edgex-go are as follows
- `baseUri` needs to be changed some that `v1` is not included. Taking core-data as an example, the value should be `http://localhost:48080/api`
- All of the routes in the RAML file should then start with `/v1`. So a current entry of `/event` would become `/v1/event`
- Finally, add an entry for the `/version` endpoint to each RAML file. The original issue defining the response of this endpoint is https://github.com/edgexfoundry/edgex-go/issues/1596

**Comment by nkstanchev** [comment]
I'd like to take this one
