### ISSUE TITLE
security-secrets-setup docker image should not generate certs on image build time

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-go#1635]
The current security-secrets-setup docker image produces the certificates of root ca and signed vault and kong certs.  This creates the vulnerability of the same certificates for all docker images use these services.   We need to fix the docker images to not all have the same certificate setup.

Current CWE issues in `security-secrets-setup`:  
1. CWE-318: Cleartext Storage of Sensitive Information in Executable 
2. CWE-313: Cleartext Storage in a File or on Disk

**Comment by jim-wang-intel** [comment]
This can be done in two phases: 1) through the script like @anonymouse64 Ian suggested in snap as the short-term solution and until then 2) integrating the full features of generation from Pki-Init services (which can be done piece meal, small chunk at a time for better review and tests)

**Comment by tingyuz** [comment]
#1794 and #1830 addressed this issue, closed.
