### ISSUE TITLE
Register azure iothub as client in export services

### ISSUE THREAD

**Issue by payalgaikwad42** [edgexfoundry/edgex-go#1636]
Hi, 
I am new to edgex. I have my project which i want to deploy on edgex. I am using azure iothub as a cloud. 
I have both java and go sdks for export services. 
I am trying to register my iothub as a client but I am confused about how to do that. 
Where should i store my configurations in order to register service?
I have postman request as shown in the following screenshot and now i want to do it programmatically but stuck at where to store the configurations.
![image](https://user-images.githubusercontent.com/42204123/62675646-75596700-b9c5-11e9-9c10-66b04e488799.png)
What does raml file do in this case? Can i store my request body in raml file ? 
Can someone please tell which sdk is better and easy to use and configure?

**Comment by michaelestrin** [comment]
Issues are not the place to ask for help.  Please refer to the _**[Getting Help](https://wiki.edgexfoundry.org/display/FA/Getting+Help)**_ page on the EdgeX Foundry wiki.

I have been able to successfully connect EdgeX to Azure IoT Hub.  See [sample code](https://github.com/michaelestrin/cloudmqtt) and [step-by-step directions](https://github.com/michaelestrin/cloudmqtt/blob/master/docs/azure/README.md).
