### ISSUE TITLE
arm64: zmq.h: No such file or directory

### ISSUE THREAD

**Issue by singoo** [edgexfoundry/edgex-go#1637]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
Keyword: crosscompile, arm64, zmq.h

### Is this a regression?
no

I don't know. Sorry about that.
 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

make build
CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=arm GOARM=7 CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=1.1.0" -o cmd/config-seed/config-seed ./cmd/config-seed
CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=arm GOARM=7 CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=1.1.0" -o cmd/export-client/export-client ./cmd/export-client
CGO_ENABLED=1 GO111MODULE=on GOOS=linux GOARCH=arm GOARM=7 CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=1.1.0" -o cmd/export-distro/export-distro ./cmd/export-distro 
# github.com/pebbe/zmq4
../Program_Golang/pkg/mod/github.com/pebbe/zmq4@v1.0.0/auth.go:19:17: fatal error: zmq.h: No such file or directory
compilation terminated.
Makefile:54: recipe for target 'cmd/export-distro/export-distro' failed
make: *** [cmd/export-distro/export-distro] Error 2

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Linux ubuntu 4.15.0-55-generic X86_64

**EdgeX Version:**
Edinburgh

**Anything else relevant?**
I want the cross compiler to be used under the arm64 platform.
But there was an error for zmq.
Normal compilation is no problem.

GO ENV:
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zs/Program_Golang"
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GORACE=""
GOROOT="/home/zs/go"
GOTMPDIR=""
GOTOOLDIR="/home/zs/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/zs/edgex-go-arm/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build938658851=/tmp/go-build -gno-record-gcc-switches"

Makefile:
#
# Copyright (c) 2018 Cavium
#
# SPDX-License-Identifier: Apache-2.0
#

.PHONY: build clean test docker run

#$(info "go path => " $(GOPATH))

INCLUDE=$(shell pkg-config --cflags libzmq)
LIBS=$(shell pkg-config --libs libzmq)
GO=CGO_ENABLED=0 GO111MODULE=on
GOCGO=CGO_ENABLED=1 GO111MODULE=on

#PLATFORM=go
PLATFORM=GOOS=linux GOARCH=arm GOARM=7 CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ go

DOCKERS=docker_config_seed docker_export_client docker_export_distro docker_core_data docker_core_metadata docker_core_command docker_support_logging docker_support_notifications docker_sys_mgmt_agent docker_support_scheduler docker_security_secrets_setup
.PHONY: $(DOCKERS)

MICROSERVICES=cmd/config-seed/config-seed cmd/export-client/export-client cmd/export-distro/export-distro cmd/core-metadata/core-metadata cmd/core-data/core-data cmd/core-command/core-command cmd/support-logging/support-logging cmd/support-notifications/support-notifications cmd/sys-mgmt-executor/sys-mgmt-executor cmd/sys-mgmt-agent/sys-mgmt-agent cmd/support-scheduler/support-scheduler cmd/security-secrets-setup/security-secrets-setup

.PHONY: $(MICROSERVICES)

VERSION=$(shell cat ./VERSION)
DOCKER_TAG=$(VERSION)-dev

GOFLAGS=-ldflags "-X github.com/edgexfoundry/edgex-go.Version=$(VERSION)"

GIT_SHA=$(shell git rev-parse HEAD)

ARCH=$(shell uname -m)

build: $(MICROSERVICES)

cmd/config-seed/config-seed:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/config-seed

cmd/core-metadata/core-metadata:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/core-metadata

cmd/core-data/core-data:
	$(GOCGO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/core-data

cmd/core-command/core-command:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/core-command

cmd/export-client/export-client:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/export-client

cmd/export-distro/export-distro:
	$(GOCGO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/export-distro 

cmd/support-logging/support-logging:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/support-logging

cmd/support-notifications/support-notifications:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/support-notifications

cmd/sys-mgmt-executor/sys-mgmt-executor:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/sys-mgmt-executor

cmd/sys-mgmt-agent/sys-mgmt-agent:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/sys-mgmt-agent

cmd/support-scheduler/support-scheduler:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o $@ ./cmd/support-scheduler

cmd/security-secrets-setup/security-secrets-setup:
	$(GO) $(PLATFORM) build $(GOFLAGS) -o ./cmd/security-secrets-setup/security-secrets-setup ./cmd/security-secrets-setup

clean:
	rm -f $(MICROSERVICES)

test:
	GO111MODULE=on go test -coverprofile=coverage.out ./...
	GO111MODULE=on go vet ./...
	gofmt -l .
	[ "`gofmt -l .`" = "" ]

run:
	cd bin && ./edgex-launch.sh

run_docker:
	bin/edgex-docker-launch.sh $(EDGEX_DB)

docker: $(DOCKERS)

docker_config_seed:
	docker build \
		-f cmd/config-seed/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-core-config-seed-go:$(GIT_SHA) \
		-t edgexfoundry/docker-core-config-seed-go:$(DOCKER_TAG) \
		.

docker_core_metadata:
	docker build \
		-f cmd/core-metadata/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-core-metadata-go:$(GIT_SHA) \
		-t edgexfoundry/docker-core-metadata-go:$(DOCKER_TAG) \
		.

docker_core_data:
	docker build \
		-f cmd/core-data/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-core-data-go:$(GIT_SHA) \
		-t edgexfoundry/docker-core-data-go:$(DOCKER_TAG) \
		.

docker_core_command:
	docker build \
		-f cmd/core-command/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-core-command-go:$(GIT_SHA) \
		-t edgexfoundry/docker-core-command-go:$(DOCKER_TAG) \
		.

docker_export_client:
	docker build \
		-f cmd/export-client/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-export-client-go:$(GIT_SHA) \
		-t edgexfoundry/docker-export-client-go:$(DOCKER_TAG) \
		.

docker_export_distro:
	docker build \
		-f cmd/export-distro/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-export-distro-go:$(GIT_SHA) \
		-t edgexfoundry/docker-export-distro-go:$(DOCKER_TAG) \
		.

docker_support_logging:
	docker build \
		-f cmd/support-logging/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-support-logging-go:$(GIT_SHA) \
		-t edgexfoundry/docker-support-logging-go:$(DOCKER_TAG) \
		.

docker_support_notifications:
	docker build \
		-f cmd/support-notifications/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-support-notifications-go:$(GIT_SHA) \
		-t edgexfoundry/docker-support-notifications-go:$(DOCKER_TAG) \
		.

docker_support_scheduler:
	docker build \
		-f cmd/support-scheduler/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-support-scheduler-go:$(GIT_SHA) \
		-t edgexfoundry/docker-support-scheduler-go:$(DOCKER_TAG) \
		.

docker_sys_mgmt_agent:
	docker build \
		-f cmd/sys-mgmt-agent/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/sys-mgmt-agent-go:$(GIT_SHA) \
		-t edgexfoundry/sys-mgmt-agent-go:$(DOCKER_TAG) \
		.

docker_security_secrets_setup:
	docker build \
		-f cmd/security-secrets-setup/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-edgex-vault:$(GIT_SHA) \
		-t edgexfoundry/docker-edgex-vault:$(DOCKER_TAG) \
		.

raml_verify:
	docker run --rm --privileged \
		-v $(PWD):/raml-verification -w /raml-verification \
		nexus3.edgexfoundry.org:10003/edgex-docs-builder:$(ARCH) \
		/scripts/raml-verify.sh

**Comment by anonymouse64** [comment]
> `GOARCH=arm GOARM=7 CC=arm-linux-gnueabihf-gcc`

This indicates you are compiling for armhf, not arm64. Did you install the arm64 package of zmq? You will need to install the armhf zmq package if you are compiling for armhf.

**Comment by singoo** [comment]
> > `GOARCH=arm GOARM=7 CC=arm-linux-gnueabihf-gcc`
> 
> This indicates you are compiling for armhf, not arm64. Did you install the arm64 package of zmq? You will need to install the armhf zmq package if you are compiling for armhf.

Thank you very much.
