### ISSUE TITLE
Make Retry behavior configurable

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/edgex-go#1642]
# 🚀 Feature Request

### Relevant Package

 This feature request is for...
All supported services

### Description
 The Retry loops used when obtaining configuration at startup have hardcoded properties. Specifically they will wait 1s between attempts to contact the registry, and will wait for a total of 30000ms. This should be configurable.

### Describe the solution you'd like
 
Allow use of environment variables:
`edgex_registry_retry_count` for the number of attempts to make
`edgex_registry_retry_wait` for the time to wait in between attempts (in seconds? microseconds?)
With default values corresponding to the existing behavior.

**Comment by michaelestrin** [comment]
@scsosna99 #1739 has been merged.  It contains a basic abstraction around the retry timer interval and timeout.  It also moved the configuration file read and environment variable overrides outside of the retry loop.  You might take another pass at implementing this functionality using the new common bootstrap package and its initial core-data implementation.  Reach out if you'd like assistance.

**Comment by scsosna99** [comment]
starting to look at again
