### ISSUE TITLE
Move SecurityProxySetupServiceKey to go-mode-core-contracts Merge API-Gateway

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1653]
Reported by @anonymouse64 in the context of https://github.com/edgexfoundry/edgex-go/pull/1627

Would be nice to move from internal/constants.go the below to
SecurityProxySetupServiceKey = "edgex-security-proxy-setup"

to github.com/edgexfoundry/go-mod-core-contracts/clients where the other service keys are defined.

**Comment by tingyuz** [comment]
This needs to be changed along with registry support.

**Comment by tingyuz** [comment]
Close the issue as it has been fixed within #2175.
