### ISSUE TITLE
Provide a function that dynamically discovers services  using the Registry Service

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1654]
Suggestion by @anonymouse64 in the context of https://github.com/edgexfoundry/edgex-go/pull/1627

In internal/pkg/config/types.go  
func ListDefaultServices() map[string]string {

"this function seems more like it should be implemented in go-mod-core-contracts, and possibly there it could use go-mod-registry to implement dynamic discovery if there are more clients, because for example how do we add rulesengine to the list of services that the SMA handles and also now security-proxy-setup? Not something to be fixed in this PR, but deserves an issue I think"

**Comment by tsconn23** [comment]
Closing as the elimination of `ListDefaultServices()` is being addressed by two different efforts

- https://github.com/edgexfoundry/edgex-go/pull/1769
- https://github.com/edgexfoundry/edgex-go/issues/1662
