### ISSUE TITLE
Attribution.txt file missing some entries

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1655]
Reported by @anonymouse64 in the context of https://github.com/edgexfoundry/edgex-go/pull/1627

Missing github.com/dgrijalva/jwt-go v3.2.0+incompatible in attributions file, possibly in more than one and possibly other libraries too.
cmd/<xyz>/Attribution.txt

This certainly is a tedious error prone task. Perhaps we should create a tool for this to scan all imports and create.

**Comment by tsconn23** [comment]
@mkbhanda I'm pretty sure this was resolved in totality via PR #1627. If you see evidence otherwise, please provide specifics. Otherwise I think we can close this out.

**Comment by anonymouse64** [comment]
@tsconn23 github.com/dgrijalva/jwt-go is missing from attribution.txt files, also all of the docker related libraries I think can be removed, etc.
