### ISSUE TITLE
Create a tool to auto generate Attributions.txt files - and eliminate a tedious error prone task

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1656]
The Attrubutions.txt file should include all imported packages and libraries. The automated build tests not code coverage tests catch omissions. Would be nice to ensure that these files are kept up to date by auto-generating them whenever any imports change in go.mod files.

**Comment by tsconn23** [comment]
Recommend we close this one. I agree it would be nice to have a tool like this but that could be an open source project all on its own. I don't know that it's necessarily a core component of the EdgeX platform.

**Comment by michaelestrin** [comment]
Closed.
