### ISSUE TITLE
Add usage help Merge API-Gateway

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1657]
Reported by @anonymouse64 in the context of https://github.com/edgexfoundry/edgex-go/pull/1627
in internal/pkg/usage/usage.go
help option mentioned but not implemented.

**Comment by tsconn23** [comment]
Capturing specifics from the PR #1627 

In security-proxy-setup/main.go w/r/t the following block
```
func main() {

	if len(os.Args) < 2 {
		usage.HelpCallbackSecurityProxy()
	}
```
The comment was as follows
```
a potential improvement we could add later would be to have this code path happen later and also have a --help option that does the same thing as this.
```

**Comment by tingyuz** [comment]
This has been fixed and merged into edgex-go, hence closed.
