### ISSUE TITLE
Rename a security flag in Merge SPI-Gateway

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1658]
Reported ny @anonymouse64 in the context of https://github.com/edgexfoundry/edgex-go/pull/1627/files

Flag name unclear and little typo in comment

instead of "InsecureSkipVerify: true",
replace with skipHostVerify 
alternately follow curl's -k option, namely
 -k, --insecure      Allow insecure server connections when using SSL

Touches files: 
internal/pkg/usage/usage.go 
internal/export/distro/xmpp.go
internal/export/distro/iotcore.go
internal/export/distro/xmpp_test.go
internal/export/distro/mqtt.go

	--insecureskipverify=true/false   Indicates if skipping the server side SSL cert verifcation, similar to -k of curl

s/verifcation/verification

**Comment by anonymouse64** [comment]
Isn't this a duplicate of #1651 ?

**Comment by mkbhanda** [comment]
Indeed duplicate of #1651, which also contains more comments.
