### ISSUE TITLE
Look at Driving "Default Services List" via Configuration

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1662]
From https://github.com/edgexfoundry/edgex-go/pull/1627#discussion_r311156531

Both the SMA and the security-proxy-setup service enumerate a set of "default services", services which are expected to be up and running in any EdgeX installation. Currently that list of services is defined and exposed [here](https://github.com/edgexfoundry/edgex-go/blob/3c8972b0ec460de0184d9656babf814c76f3b501/internal/pkg/config/types.go#L22).

In the case of the security-proxy-setup service, however, there are two additional services called out.
```
services["edgex-support-rulesengine"] = "Rulesengine"
services["edgex-device-virtual"] = "Virtualdevice"
```
In particular the virtual device service may not be running in a Production installation of EdgeX. It has been proposed that we review this mechanism to determine if it can be driven via configuration.

**Comment by xmlviking** [comment]
@anonymouse64 Are we saying here we don't want to include any kind of externalization for the default service list for the SMA service?

**Comment by anonymouse64** [comment]
@xmlviking I don't follow your question, what do you mean by externalization?

The point I'm saying is that in the security-proxy-setup microservice specifically we shouldn't be hard-coding specific services there, it should be configurable someway, and that there's probably an integration point with go-mod-registry to enable that configuration of what services get tokens generated for them. It's fine if security-proxy-setup has to query consul to get services.

**Comment by michaelestrin** [comment]
This is still an issue with system management agent.  Because of backwards-compatibility concerns and the rapidly approaching Fuji code freeze, we're not going to remove the [static list of servicies](https://github.com/edgexfoundry/edgex-go/blob/3c8972b0ec460de0184d9656babf814c76f3b501/internal/pkg/config/types.go#L22) before the fuji release.

See #1780 discussion to understand the underlying issue with removal.  

Reopening and marking this for Geneva.

**Comment by tingyuz** [comment]
need to clarify from Michael.

**Comment by michaelestrin** [comment]
Reverted #2401 (with #2427).  Reopened and reclassified as post-Geneva issue.

**Comment by cloudxxx8** [comment]
decided in Core WG meeting on 26-April-2023, closing this issue because SMA is removed in v3.0 and we would keep the list in the security service configuration.
