### ISSUE TITLE
Implementation of credential creation for Microservices in security-secretstore-setup

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#1676]
Some micro services in EdgeX needs credentials to access mongodb. Security-secretstore-setup is responsible of creating such credentials and store them into Vault so that other micro services are able to retrieve them and use them to access mongodb.

**Comment by bnevis-i** [comment]
For separation of concerns, I recommend to remove this from security-secretstore-setup and put this into some kind of security-seed utility, either combine with #1675 or its own utility for setting up mongodb credentials.

For now this probably needs to use the root token, but we should generate a Vault token specifically for this seeding.
