### ISSUE TITLE
export services are missing /res folder in Docker container and fail on startup

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#168]
When export client and export distro try to start in their Docker containers, both services are missing the /res folder.  The Dockerfile needs to be modified to contain the /res folder from cmd.

Jim@JimsXPS MINGW64 ~/GitRepos/edgexforks/developer-scripts/compose-files (master)
$ docker-compose -f docker-compose-california-0.5.2.yml logs -f --tail=100 export-client
Attaching to edgex-export-client
edgex-export-client | {"level":"error","ts":1524607138.386605,"caller":"export-client/main.go:39","msg":"could not load configuration file (./res): open ./res/configuration.toml: no such file or directory","version":"0.5.2","stacktrace":"main.main\n\t/go/src/github.com/edgexfoundry/edgex-go/cmd/export-client/main.go:39\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:195"}
edgex-export-client exited with code 0

Jim@JimsXPS MINGW64 ~/GitRepos/edgexforks/developer-scripts/compose-files (master)
$ docker-compose -f docker-compose-california-0.5.2.yml logs -f --tail=100 export-distro
Attaching to edgex-export-distro
edgex-export-distro | {"level":"info","ts":1524607203.4346569,"caller":"export-distro/main.go:32","msg":"Starting edgex export client","version":"0.5.2"}
edgex-export-distro | {"level":"error","ts":1524607203.434721,"caller":"export-distro/main.go:43","msg":"could not load configuration file (./res): open ./res/configuration.toml: no such file or directory","version":"0.5.2","stacktrace":"main.main\n\t/go/src/github.com/edgexfoundry/edgex-go/cmd/export-distro/main.go:43\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:195"}
edgex-export-distro exited with code 0

Jim@JimsXPS MINGW64 ~/GitRepos/edgexforks/developer-scripts/compose-files (master)
$

Assigned to Fede and Janko but adding @drasko  and @tsconn23 for awareness.

**Comment by feclare** [comment]
I think it is being fixed in #159
