### ISSUE TITLE
Go Get zeromq package gives repository not found error

### ISSUE THREAD

**Issue by payalgaikwad42** [edgexfoundry/edgex-go#1697]
Hi, 
I am running edgex-go on my ubuntu machine locally where at the start of the set up there is command as follows :
go get github.com/rjeczalik/pkgconfig/cmd/pkg-config
but the repo mentioned in the command does not exists.

![image](https://user-images.githubusercontent.com/42204123/63487740-fd616580-c4c9-11e9-8270-46bcf2ff9194.png)

Also on terminal it is giving me error as:

![image](https://user-images.githubusercontent.com/42204123/63487775-25e95f80-c4ca-11e9-8c63-7558ada496ff.png)

**Comment by brandonforster** [comment]
The command works fine on my machine. Additionally, the repository exists and is available at

https://github.com/rjeczalik/pkgconfig/

The path to the dir you'd like is

https://github.com/rjeczalik/pkgconfig/tree/master/cmd/pkg-config

**Comment by anonymouse64** [comment]
@payalgaikwad42 What is `go version` for your machine?
