### ISSUE TITLE
Update kong to 1.3.0 and re-enable for arm64

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1698]
Now that Kong 1.3 is released, we can re-enable the security services by default for arm64 in the snap at least.

There's probably an equivalent task for docker, not sure if we ever produced a security docker-compose for arm64, I don't think we did.

**Comment by anonymouse64** [comment]
See https://github.com/Kong/kong/blob/1.3.0/CHANGELOG.md#130 for a changelog

**Comment by jpwhitemn** [comment]
@anonymouse64 - still a Fuji release item?  Label Geneva?

**Comment by anonymouse64** [comment]
yes still Fuji

**Comment by michaelestrin** [comment]
See also https://github.com/edgexfoundry/developer-scripts/pull/155

**Comment by michaelestrin** [comment]
And you'll also need to sync these changes to the blackbox-testing's [environment](https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/arm64_env.sh) shell script that sets the arm64 image names in the blackbox-testing-specific docker-compose file.

**Comment by anonymouse64** [comment]
@michaelestrin this task is specific to the snap, so no docker-compose changes needed here

**Comment by bnevis-i** [comment]
Note that the docker scripts have all rolled forward to Kong 1.3.0 for Fuji release on last day of the F2F.

**Comment by anonymouse64** [comment]
Unfortunately while we can upgrade to Kong 1.3 for amd64 for Fuji easily enough, it will take a bit more work in the snap to make it work on arm64, so we will need to enable for Geneva or later.
