### ISSUE TITLE
Timeout isn't respected in any EdgeX Service

### ISSUE THREAD

**Issue by rsdmike** [edgexfoundry/edgex-go#1702]
# 🐞 Bug Report

### Affected Services

 The issue is located in: All Services 

### Is this a regression?

 Not that i'm aware of.

### Description and Minimal Reproduction
Using core-data as an example: 
1) Set 
```toml
[Service]
Timeout = 1
``` 
in configuration.toml
2) Set a sleep (larger than that timeout set in your configuration) in any http handler (i.e. pingHandler) for core-data: 
`time.Sleep(time.Millisecond * time.Duration(5000))`
3) Make the rest request. (i.e. /api/v1/ping) should give you a "Response Timed out" response, but instead you will get pong after however long you put a sleep in the handler for. 

The timeout is ignored 
```
	http.TimeoutHandler(nil, time.Millisecond*time.Duration(data.Configuration.Service.Timeout), "Request timed out")
``` 
in main.go since the handler returned from the timeoutHandler is simply not used, and nil is passed to the TimeoutHandler so it doesn't have any routes to build on. It's basically a no-op. 

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Native, Windows 10
**EdgeX Version:**
Master Branch

**Anything else relevant?**
the timeoutHandler should be moved into `startHttpServer()`. Something like:
```golang
r := data.LoadRestRoutes()
tr := http.TimeoutHandler(r, time.Millisecond*time.Duration(data.Configuration.Service.Timeout), "Request timed out")
errChan <- http.ListenAndServe(":"+strconv.Itoa(port), context.ClearHandler(tr))
```

**Comment by tsconn23** [comment]
@brandonforster Please validate and provide a fix if verified.

**Comment by mkbhanda** [comment]
Are these not 2 separate things? The sleep determines when the request is made, the timeout is how long the client is willing to wait


Sent from VMware Boxer

On August 26, 2019 at 12:17:00 PM PDT, Brandon Forster <notifications@github.com> wrote:

Reproduced on my Mac with the ping scenario described above. Will get to work.
