### ISSUE TITLE
Inconsistent usage of ContentType constants

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/edgex-go#1712]
Currently, in EdgeX several handler functions set their content types with string literals instead of the constants defined in [core contracts.](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go#L70) There should be a complete suite of constants usable for all the returned types of endpoints.

**Comment by jbonafide623** [comment]
Handled in PR #1768. This issue can be closed with merge of PR #1768.
