### ISSUE TITLE
Split edgex-vault Docker container into edgex-vault and edgex-pki-init

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1716]
Please add to https://github.com/edgexfoundry/edgex-go/projects/13

EdgeX is currently in the position that we are distributing a custom version of Vault.
This means that we are inheriting security vulnerabilities in Vault's container, and we have to do extra releases whenever the upstream Vault is released. Now that the PKI-init code is merged into security-secrets-setup we should go back to using a stack version of Vault, and move security-secrets-setup into its own container.

 * Modify docker-compose to modify edgex-vault microservice, deloyed using sha256 hash tag from dockerhub.
 * New vault to bind mount /run/edgex/secrets/vault volume
 * Remove /vault/config mount from the vault service (security-secrets-worker still needs to to create legacy tokens)
 * New vault uses same backend data store as old vault (see existing config file in notes)
 * Set VAULT_LOCAL_CONFIG environment variable on container to bind TLS assets and consul backend. Set the following keys
 * tls_cert_file = /run/edgex/secrets/edgex-vault/server.crt
 * tls_key_file = /run/edgex/secrets/edgex-vault/server.key
 * tls_perfer_server_cipher_suites = true
 * Block block container startup on availability of /run/edgex/secrets/vault/.pki-init.complete
 * Init-block example run command override (for vault)
 * /usr/bin/dumb-init -- /bin/sh -c "while test \! -f /run/edgex/secrets/edgex-vault/.pki-init.complete; do sleep 1; done; exec  /usr/local/bin/docker-entrypoint.sh"

##### https://github.com/edgexfoundry/developer-scripts/issues/150
Issue 150 places additional constraints on how this key material can be shared across containers in a MacOS environment.  Specifically:
1. MacOS doesn't have a /run
2. On MacOS, bind mounts are white-listed and /run is not in the white-list by default.

Proposed solution must accommodate differences between Linux and MacOS deployments.  One  possible solution is to share via /tmp by default, and recommend that Linux users use /run.

**Comment by jim-wang-intel** [comment]
Will re-visit this after Fuji
