### ISSUE TITLE
Modify go-mod-core-security to support per-service Vault tokens

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1717]
Please add to https://github.com/edgexfoundry/edgex-go/projects/13

Changes:
 * SecretConfig needs to have reasonable, overridable defaults
 * Ensure that Vault certificate is verified by default
 * Read an environment variable, VAULT_TOKEN_URL, that contains the URL to that services' Vault token
 * Any file:// URLs should be handled internally, by reading a JSON file at the indicated path and parsing out the 'token' and 'token_accessor' fields
 * Start a goroutine that ensures that the Vault token doesn't go stale, since we have no way of reissuing file:// tokens without rebooting
 * Needs to ensure that the security service is all the way up. (See #1710)

**Comment by tsconn23** [comment]
Should this be an issue in [go-mod-secrets](https://github.com/edgexfoundry/go-mod-secrets) rather than edgex-go?

**Comment by bnevis-i** [comment]
If you tell me we can do a cross-project reference in a GitHub project/kanban, then I will move it.  If not the answer is not clear cut and I will just do what I'm told.

**Comment by tsconn23** [comment]
Yes -- You can link any number of issues from various repos to issues in a single Kanban board. Here's an example
https://github.com/edgexfoundry/edgex-go/projects/12

As I write this, there are issues from `docker-edgex-mongo` in In Progress status and issues from `go-mod-secrets` in Done status.

**Comment by bnevis-i** [comment]
Moved to https://github.com/edgexfoundry/go-mod-secrets/issues/14
