### ISSUE TITLE
Apply Operator Pattern - IntervalAction Update

### ISSUE THREAD

**Issue by nkstanchev** [edgexfoundry/edgex-go#1727]
This issue addresses the transition of the Scheduler Intervalaction endpoint for PUT to the operator pattern and the addition of the accompanying unit tests.

https://github.com/edgexfoundry/edgex-go/projects/11#card-24596170

**Comment by brandonforster** [comment]
@nkstanchev Is this still being worked?

**Comment by michaelestrin** [comment]
Closed.  Post common-bootstrap, this is no longer needed.
