### ISSUE TITLE
Refactor the go constant with the unified mixed caps

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#173]
suggested : `MaxLength`
Not suggested : `MAXLENGTH`, `MAX_LENGTH`
discuss refer to : [Go naming conventions for const
](https://stackoverflow.com/questions/22688906/go-naming-conventions-for-const)

claim it.

**Comment by yanghua** [comment]
@drasko do you agree this?

**Comment by yanghua** [comment]
@jpwhitemn @tsconn23 any idea?

**Comment by drasko** [comment]
Yes.

**Comment by drasko** [comment]
@yanghua here you go ;)

**Comment by yanghua** [comment]
hi @jpwhitemn and @tsconn23 is issue will bring a big change, should it waiting for the refactor you are doing?

**Comment by tsconn23** [comment]
@yanghua Don't start on this yet please.
