### ISSUE TITLE
Error Not Being Checked When Event is Added

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1731]
In core-data's `eventHandler` we are apparently not checking the error being returned from the `addNewEvent` function call

https://github.com/edgexfoundry/edgex-go/blob/bbadd2666cf18a2b4fea26103b0e8785b0966c47/internal/core/data/router.go#L230

This results in a 200 OK being returned in all cases.

Steps to duplicate
1.) In the core-data/res/configuration.toml set [Writable]MetaDataCheck = true
2.) POST to `http://localhost:48080/api/v1/event` with the following event payload
```
{  
   "created":1471806386919,
   "origin":1471806386919,
   "device":"livingroomthermostatdevice3",
   "readings":[  
      {  
         "origin":1471806386919,
         "name":"luminousIntensity1",
         "value":"40"
      }
   ]
}
```
3.) You will receive a 200 with an empty response body. The response body for a 200 should ALWAYS contain an event ID. The error from metadata telling us the device is invalid is being ignored. 

It appears that the previous logic returning appropriate status codes based on the returned error needs to be restored.

Please verify whether or not this is the case in the Edinburgh release. If so, we may need to consider another patch release.

**Comment by jdharms** [comment]
@tsconn23 

I've submitted a PR for this issue targeting master: https://github.com/edgexfoundry/edgex-go/pull/1732

I checked and the bug repros in the Edinburgh release as well.  If I should create a PR targeting that branch, let me know.

**Comment by brandonforster** [comment]
@jdharms Yes, we have to fix Edinburgh bugs.

**Comment by mkbhanda** [comment]
+1 concur with Brandon! Good work Daniel!
