### ISSUE TITLE
Config-Seed: Populate Global Security Configuration in Registry

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1735]
Per discussions documented in the Core Working Group 15-Aug-2019, the mechanism by which security features will be enabled will affect security operations for the whole EdgeX platform. In other words, security is not a service by service setting. To that end, we need to have a global configuration area for security in Consul that services are aware of.

The current proposal is to have the following section written by the config-seed

`/edgex/security`

For this particular issue, the above section will contain one key `SECRET_STORE` the value of which will be either true/false. This value will be set by providing the following environment variable to the config-seed -- `edgex_security_secret_store`. This follows the convention already present in the config-seed of overriding values in Consul according to an environment variable that maps to a path.

Separate issues will follow for integrating each service with this global security configuration, as well as usage of environment variables should Consul not be in use.

**Comment by jdharms** [comment]
Some changes I made while addressing code review broke this feature and they slipped through my testing. I've opened #1813 to address these issues.
