### ISSUE TITLE
Unit Test -- Core-Metadata: Create a unit test for Update Device Service LastReported by ID.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1737]
Create a unit test at the REST layer level (add to `internal/core/metadata/rest_deviceservice_test.go`).

**Comment by jpwhitemn** [comment]
@akramtexas - Akram is this going to get done in Fuji or should it be moved to Geneva label?

**Comment by michaelestrin** [comment]
@akramtexas please clarify the scope of this issue.

**Comment by akramtexas** [comment]
@jpwhitemn @michaelestrin Thanks, gentlemen. Working this for `Geneva` 👍

**Comment by michaelestrin** [comment]
"please clarify the scope of this issue."  What exactly does this issue cover (i.e. what are you implementing, changing, etc)?  @akramtexas

**Comment by akramtexas** [comment]
> "please clarify the scope of this issue." What exactly does this issue cover (i.e. what are you implementing, changing, etc)? @akramtexas

@michaelestrin I'm currently working another task... Actually, and as soon as I get to this issue, I was planning on digging into identifying the scope of this issue, beginning with the info per a [link that I see referenced](https://github.com/edgexfoundry/edgex-go/projects/11#card-23264821).

**Comment by akramtexas** [comment]
@michaelestrin  Having picked up this task today, I've done some digging and identified the scope of this issue:
- Given the extensive bootstrapping-related work done, the re-architecting so as to eliminate global variables which you have led and shepherded, the scope of this issue now stands significantly changed.
- There no longer exists the need to follow the "Operator" design pattern (aka GoF "Command") since dependency injection is now taken care of via the bootstrapping-related code.
- The need remains, though, to have unit testing be made available for the core-metadata function identified in this issue (i.e. `func restUpdateServiceLastReportedById(){...}`).
- To that end, given that such a unit test does not exist, I have scoped out what needs to be done:
- Create a unit test at the REST layer level (in `internal/core/metadata/rest_deviceservice_test.go`).
- Since we already have injection points, there is no need to have an HTTP server running. 
- Given the arguments expected by the relevant function (as follows)...
```
func restUpdateServiceLastReportedById(
  w http.ResponseWriter,
  r *http.Request,
  lc logger.LoggingClient,
  dbClient interfaces.DBClient,
  errorHandler errorconcept.ErrorHandler) 
```
...we can mock `http.ResponseWriter`, `http.Request`, etc.
- As usual, this unit test, too, will cover the happy and unhappy paths (e.g. the device service does not exist, etc.) in the function.
- If it makes sense, I can create a new issue to replace this one (to clarify the intent that this issue is not a refactoring, and rather involves the _creation_ of a unit test).

**Comment by michaelestrin** [comment]
There are existing tests for metadata rest endpoints.  Follow the existing patterns.  No need for a new issue; retitle and/or revise the issue description and continue to use this one for continuity's sake.

**Comment by akramtexas** [comment]
> There are existing tests for metadata rest endpoints. Follow the existing patterns. No need for a new issue; retitle and/or revise the issue description and continue to use this one for continuity's sake.

Sounds good. I'll make it so 👍
