### ISSUE TITLE
Common Bootstrap Package

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1739]
Spike a flexible common package to be used by each core service to replace the existing copy/paste implementations of init.go and incorporate the existing internal/package/startup package.

**Comment by AnthonyMBonafide** [comment]
I am pretty confident that the changes you are looking into will fix some, if not all, of the code duplication reported by [SonarCloud](https://sonarcloud.io/component_measures?id=edgexfoundry_edgex-go&metric=duplicated_lines&view=list) for the [init.go](https://sonarcloud.io/component_measures?id=edgexfoundry_edgex-go&metric=duplicated_lines&selected=edgexfoundry_edgex-go%3Ainternal%2Fcore%2Fcommand%2Finit.go&view=list) and [main.go](https://sonarcloud.io/component_measures?id=edgexfoundry_edgex-go&metric=duplicated_lines&selected=edgexfoundry_edgex-go%3Acmd%2Fcore-data%2Fmain.go&view=list) files. I just want to make sure we have some trace-ability.
