### ISSUE TITLE
 cannot load github.com/edgexfoundry/edgex-go: cannot find module providing package github.com/edgexfoundry/edgex-go make: *** [cmd/export-client/export-client] Error 1

### ISSUE THREAD

**Issue by wassim6975** [edgexfoundry/edgex-go#1743]
I have an issue when I want to make build edgex
 
This is the issue : 

 cannot load github.com/edgexfoundry/edgex-go: cannot find module providing package github.com/edgexfoundry/edgex-go
make: *** [cmd/export-client/export-client] Error 1

Thanks for helping me :)

**Comment by tsconn23** [comment]
Closing. Please take this to the #help channel in the EdgeXFoundry Slack
