### ISSUE TITLE
Integrate the redis database on EdgeX

### ISSUE THREAD

**Issue by wassim6975** [edgexfoundry/edgex-go#1744]
Hello everyone, 
Do you know how can I integrate the redis database on EdgeX?

Thanks for helping me :)

**Comment by brandonforster** [comment]
You should read the docs or check out the #help channel on Slack.

**Comment by andresrinivasan** [comment]
And just to be clear, Redis has already been integrated. See [redis/CONFIGURATION.md](https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/CONFIGURATION.md).

**Comment by wassim6975** [comment]
Thank you, I found it.
