### ISSUE TITLE
Refactor REST handlers to reduce code duplication

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#1745]
# 🚀 Feature Request

### Relevant Package
All core services

### Description
Refactor the REST handlers for each of the core services such that we can have more reusable code and less duplication. 

For more details refer to the [SonarCloud report](https://sonarcloud.io/component_measures?id=edgexfoundry_edgex-go&metric=duplicated_lines&view=list) for code duplication, and look in the Go files containing code for the REST handler functions(i.e. rest_deviceservice.go, rest_device.go, router.go, etc.)

As of the creation of this issue the most duplicated code falls within one of these categories:

1. Type checking for errors
1. Writing the content type in the response
1. Logging errors via the `LoggingClient`
1. Writing common responses like "true"
1. Parsing request for URL/query parameters

Please see #1734 for a possible approach to addressing the first 4 concerns listed above.

### Describe the solution you'd like
SonarCloud reporting less code duplication 

### Describe alternatives you've considered
N/A as this is a technical debt concern. We have done some work exploring a new way to handle errors in a more standardized  fashion(See #1734 ). The efforts explored in the associated proposal touches on some of the code duplication categories mentioned above.

**Comment by jbonafide623** [comment]
@tsconn23 Assign this to me please
