### ISSUE TITLE
Refactor Redis client to reduce code duplication

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#1746]
# 🚀 Feature Request

### Relevant Package
redis

### Description
Reduce the code duplication in the Redis client implementation. Please see the [SonarCloud report](https://sonarcloud.io/component_measures?id=edgexfoundry_edgex-go&metric=duplicated_blocks&selected=edgexfoundry_edgex-go%3Ainternal%2Fpkg%2Fdb%2Fredis%2Fmetadata.go) for more specifics as to the duplicated code.

In short, the code used to obtain `DeviceReport`s is duplicated in order to obtain `DeviceReport`s by different criteria(DeviceName, ScheduleEventName, and Action).

The code in the `GetDeviceReportByDeviceName` function seen here:
https://github.com/edgexfoundry/edgex-go/blob/372781e7cefe8f781ab3fc5dab71c43cae451919/internal/pkg/db/redis/metadata.go#L59-L77

can be refactored so that we can reduce the code in the `GetDeviceReportsByScheduleEventName` and `GetDeviceReportsByAction` functions seen here:

https://github.com/edgexfoundry/edgex-go/blob/372781e7cefe8f781ab3fc5dab71c43cae451919/internal/pkg/db/redis/metadata.go#L88-L106

and

https://github.com/edgexfoundry/edgex-go/blob/372781e7cefe8f781ab3fc5dab71c43cae451919/internal/pkg/db/redis/metadata.go#L108-L126

### Describe the solution you'd like
Common functionality refactored so that we are reusing common code and reducing the amount of duplicate code.

### Describe alternatives you've considered
N/A as this is a tech debt issue which can be resolved with a simple refactor

**Comment by Ivan-Marquez** [comment]
Hello @AnthonyMBonafide ,

I'm currently learning Go and I'm looking forward to contribute to OSS by addressing simple issues such as this one. If it's ok with you I’ll work on this and submit a PR. Thanks @AnthonyMBonafide !

**Comment by AnthonyMBonafide** [comment]
@Ivan-Marquez, that is great. We love any and all contributions, so thank you for thinking of EdgeX. Feel free to reach out for this and any other issue you decide to take on if you need any assistance. In addition to pinging me on this issue you can reach out via the EdgeX Slack workspace. You can get an invite to the Slack workspace [here](https://slack.edgexfoundry.org/). Slack is a great place to get help for all EdgeX related topics

**Comment by AnthonyMBonafide** [comment]
I assigned the issue to you so no one else works on this.

**Comment by Ivan-Marquez** [comment]
Thanks so much @AnthonyMBonafide ! I look forward to contribute and learn more about this project. And I just joined your workspace on Slack. I really appreciate the invite!

**Comment by tsconn23** [comment]
Given the age and lack of progress on this issue, I'm inclined to close. Any thoughts to the contrary @andresrinivasan ?

**Comment by andresrinivasan** [comment]
Makes sense. Someone will get frustrated in the future and help address this. Also (so it's mentioned here for posterity) we are using a two different Redis SDKs. One in the EdgeX repo and one in the go-mod-messaging repo.

**Comment by jpwhitemn** [comment]
OBE??  Pull back to icebox.

**Comment by cloudxxx8** [comment]
the original issue is fixed by #1784, and in V2 we reduce the duplicated code in 
https://github.com/edgexfoundry/edgex-go/blob/0f1fe820ccd95aec4869edd2918246727b77d5b6/internal/pkg/v2/infrastructure/redis/queries.go#L18-L45

Close this issue
