### ISSUE TITLE
Consider removing HttpCaller instead using Requestor for core\command

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#1749]
During the review of https://github.com/edgexfoundry/edgex-go/pull/1748, Ian suggested to remove HttpCaller (https://github.com/edgexfoundry/edgex-go/blob/c810a60f0fd49918467451174b412dd73294d2e5/internal/interface.go) as it may be duplicated with Requestor (in internal/security/proxy).  

As HttpCaller is being used by core\command, it is suggested to refactor core\command to remove HttpCaller and consider using Requestor.

**Comment by anonymouse64** [comment]
This issue isn't necessary, the duplicated Requestor interface will instead be removed from PR #1748 instead
