### ISSUE TITLE
snap builds are broken due to incorrect branch for docker-mongo script

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1755]
We should really have been specifying the `source-branch` for https://github.com/edgexfoundry/docker-edgex-mongo in the snapcraft.yaml, since we didn't it defaulted to master which conveniently continued to work all the way back to Delhi up until some changes for Fuji were landed to master.

Example broken builds:
- https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-master-stage-snap/465/console
- https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-delhi-stage-snap/318/console
- https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-edinburgh-stage-snap-arm/108/console

For delhi, we should just disable the builds since it's not supported anymore, but for Edinburgh the fix is to use the `edinburgh` branch of docker-edgex-mongo. For Fuji/master more investigation is needed

**Comment by knitzsche** [comment]
see PR https://github.com/edgexfoundry/edgex-go/pull/1757

**Comment by anonymouse64** [comment]
hmm @difince and @tsconn23 is the new go implementation of docker-edgex-mongo complete? I'm trying to update the snap to use it and it seems to be missing a few things, if that's the case then for now to unbreak the nightly snap build, I will just switch the part in the snapcraft.yaml for this to use the edinburgh branch I think

**Comment by anonymouse64** [comment]
This is fixed for Edinburgh with #1757, and for master with https://github.com/edgexfoundry/edgex-go/pull/1774. We may need to continue to update usage of the new go binary as changes land to docker-edgex-mongo, but builds should be unblocked for now
