### ISSUE TITLE
Add Support for kubenetes?

### ISSUE THREAD

**Issue by spade69** [edgexfoundry/edgex-go#1760]
# 🚀 Feature Request

### Relevant Package
 This feature request is for K8S multiple host deploy.

### Description
just add support for kubernetes, and make it more mature for prodution.

**Comment by michaelestrin** [comment]
EdgeX is not fully twelve-factor compliant and does not explicitly support high availability.  This is a road map item for a future release.

Meanwhile, you can deploy EdgeX to K8s.  See https://github.com/edgexfoundry-holding/edgex-kubernetes-support
