### ISSUE TITLE
/bin/test-attribution-txt.sh complains about missing licensing for nested packages

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/edgex-go#1766]
Example: We have attribution for package github.com/foo/bar but then also begin using github.com/foo/bar/baz.  currently /bin/test-attribution-test.sh will complain about not having attribution for github.com/foo/bar/baz.

See comment thread in #1756:

https://github.com/edgexfoundry/edgex-go/pull/1756#discussion_r324291308

**Comment by jdharms** [comment]
Assigning to @anonymouse64 as requested

**Comment by anonymouse64** [comment]
In the original PR, the root-level consul package was no longer imported, but the leaf level was now imported, but I think the original issue might still happen generically

**Comment by anonymouse64** [comment]
I won't have time to work on this, if it comes up again perhaps someone else can take a look at it.
