### ISSUE TITLE
SMA Health Check should not be limited to "known" services

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1771]
getHealth() in internal/system/agent/services.go relies on the IsKnownServiceKey() function to determine whether it's possible to query the registry to determine a service's health.  

IsKnownServiceKey() should be eliminated.  The registry should be queried for the health of any specified service.

**Comment by michaelestrin** [comment]
Also dependent on https://github.com/edgexfoundry/edgex-go/issues/1763 merge.

**Comment by anonymouse64** [comment]
Related https://github.com/edgexfoundry/edgex-go/issues/1662
