### ISSUE TITLE
Add README to security-secretstore-setup service

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1776]
Originally from https://github.com/edgexfoundry/security-api-gateway/pull/76

New README.md should like in the following directory
https://github.com/edgexfoundry/edgex-go/tree/master/cmd/security-secretstore-setup

**Comment by tingyuz** [comment]
With recent release the command line parameters for secretstore-setup have been updated. The latest supported command line parameters can be found here under securitySecretStoreSetupUsageStr :
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/usage/usage.go

So init option needs to be removed from this README:
https://github.com/edgexfoundry/edgex-go/blob/master/cmd/security-secretstore-setup/README.md

Other than that everything still holds.
