### ISSUE TITLE
SMA Get Configuration Endpoint Without Registry Flag No Longer Returns Configuration

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1780]
Call to `GET http://localhost:48090/api/v1/config/edgex-core-data` when the system management agent service is not started with the --registry flag should communicate directly with edgex-core-data to retrieve and return edgex-core-data's configuration.

This works in the Edinburgh branch but the related code was removed from the master branch.

This is a backwards-breaking change that must be addressed prior to the Fuji release.

**Comment by michaelestrin** [comment]
My reporting of this issue was apparently flawed.

Upon inspection and testing of master (post #1769 merge), the implementation is working as I would expect when the service is run without the --registry flag.  

It leverages the `[Clients]` chapter in configuration.toml to obtain a service's address and subsequently attempts to connect to that address to retrieve the service's configuration.

If the named service is not found the `[Clients]` chapter in configuration.toml, the implementation will return a response similar to this:

```
{
  "configuration": {
    "foo": "registry is required to obtain configuration."
  }
}
```

Prior to #1769, the implementation would fault.

**Comment by michaelestrin** [comment]
@tsconn23 -- can you confirm this works as you'd expect when the service is started without the --registry flag (and the corresponding configuration.toml has a valid entry for the service name you're passing in the url that you want to obtain configuration for)?

**Comment by tsconn23** [comment]
Currently in `master` (Fuji) the get configuration no longer panics, which is good.

```
GET http://localhost:48090/api/v1/config/edgex-core-data

{"configuration":{"edgex-core-data":"registry is required to obtain configuration."}}
```

However in the Edinburgh release, the same GET request returns the service configuration. So I'm still of the opinion that we have a bug.
```
GET http://localhost:48090/api/v1/config/edgex-core-data
{"Configuration":{"edgex-core-data":{"Clients":{"Logging":{"Host":"localhost","Port":48061,"Protocol":"http"},"Metadata":{"Host":"localhost","Port":48081,"Protocol":"http"}},"Databases":{"Primary":{"Host":"localhost","Name":"coredata","Password":"","Port":27017,"Timeout":5000,"Type":"mongodb","Username":""}},"Logging":{"EnableRemote":false,"File":"./logs/edgex-core-data.log"},"MessageQueue":{"Host":"*","Port":5563,"Protocol":"tcp","Topic":"events","Type":"zero"},"Registry":{"Host":"localhost","Port":8500,"Type":"consul"},"Service":{"BootTimeout":30000,"CheckInterval":"10s","ClientMonitor":15000,"Host":"localhost","MaxResultCount":50000,"Port":48080,"Protocol":"http","StartupMsg":"This is the Core Data Microservice","Timeout":5000},"Writable":{"ChecksumAlgo":"xxHash","DeviceUpdateLastConnected":false,"LogLevel":"INFO","MetaDataCheck":false,"PersistData":true,"ServiceUpdateLastConnected":false,"ValidateCheck":false}}}}
```
I believe you root caused this to the mismatch of the [Client] entry keys in the configuration.toml. But the behavior needs to be preserved between Edinburgh and Fuji, so we need to  come up with a way to make it so IMHO. I personally don't think changing the [Client] entries to have their name agree with the service key would be a problem if that's the recommended fix.

For example, changing `[Clients.CoreData]` to `[Clients.edgex-core-data]`. Although be advised that the current naming is the same in every service.

**Comment by michaelestrin** [comment]
You are right @tsconn23.

Edinburgh maps services in generalClients by serviceKey (CoreData -> edgex-core-data).  https://github.com/edgexfoundry/edgex-go/blob/b4a4fa47c55b1800914bcdfcd3ef6ebcd814ee62/internal/system/agent/init.go#L238

My implementation doesn't do that.  Breaks backwards-compatibility.  

I'll figure out a way to correct this -- hopefully without restoring the static code-based mapping of serviceKey to serviceName.  https://github.com/edgexfoundry/edgex-go/blob/b4a4fa47c55b1800914bcdfcd3ef6ebcd814ee62/internal/system/agent/init.go#L48

**Comment by michaelestrin** [comment]
I restored the prior behavior.  It depends on a static map of serviceKey to ServiceName in the ListDefaultServices() function from internal/pkg/config.  

There is a related issue (https://github.com/edgexfoundry/edgex-go/issues/1662) to make this mapping configuration-driven.
