### ISSUE TITLE
Error running edgex-proxy from 'make docker' images

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/edgex-go#1782]
# 🐞 Bug Report

### Affected Services
The issue is located in: edgex-proxy

### Is this a regression?

I'm not sure, I've tested against current master branch and commit bffbfbb2

### Description and Minimal Reproduction

* Run `make docker` from edgex-go root
* Grab a current docker-compose file, edit all applicable images to use the 1.1.0-dev tag
* Bring up edgex services following instructions [here](https://docs.edgexfoundry.org/Ch-GettingStartedUsers.html#run-edgex-foundry)
* Attempt to bring up edgex-proxy using the following commands:

```
docker-compose up -d vault
docker-compose up -d vault-worker
docker-compose up -d kong-db
docker-compose up -d kong-migrations
docker-compose up -d kong
docker-compose up edgex-proxy && echo note no -d
```

Result: 

```
[(HEAD detached at bffbfbb2)] brave:docker jdharms$ docker-compose up edgex-proxy
kong-db is up-to-date
edgex-files is up-to-date
kong is up-to-date
edgex-core-consul is up-to-date
edgex-vault is up-to-date
Starting edgex-proxy ... done
Attaching to edgex-proxy
edgex-proxy        | level=INFO ts=2019-09-19T16:27:21.1067381Z app=edgex-security-proxy-setup source=service.go:64 msg="the service on http://kong:8001 is up successfully"
edgex-proxy        | level=ERROR ts=2019-09-19T16:27:21.1124642Z app=edgex-security-proxy-setup source=main.go:79 msg="open /vault/config/assets/resp-init.json: no such file or directory"
edgex-proxy exited with code 1
```

I expect this to succeed so I can make requests against the proxy service.

## 🌍  Your Environment
**Deployment Environment:**
Docker using Edinburgh docker-compose file, edited to point to locally built docker images.

**EdgeX Version:**

Current master ( ea1f15c5e52ec41aeee6b49e69e44486ee9ba6fa ) and commit bffbfbb2.  I see the same error with both.

**Comment by jdharms** [comment]
If anyone has any suggestions on where to start looking to resolve this please let me know.

**Comment by tingyuz** [comment]
This is expected if we rebuild vault-worker and use the new-built image. The reason is we merged the vault-worker as a pilot project with a frame only but nothing implemented. As part of the work vault-worker needs to initialize and unseal Vault, in which it will create resp-init.json file and put it on the volume to be consumed. When we implement vault init and unseal this will be gone. 
To test edgex-proxy currently, one needs to change the docker-compose file to use the older version of vault-worker such as 1.0.0.

**Comment by tingyuz** [comment]
This is related to issue #1674.

**Comment by jdharms** [comment]
Thanks for the information.  I'd recommend leaving this issue open until #1674 is resolved even still--so we have something to point to if someone else runs into this issue.

**Comment by anonymouse64** [comment]
note that the service previously known as `vault-worker` living in https://github.com/edgexfoundry/security-secret-store is now known as `security-secretstore-setup` in edgex-go

**Comment by tingyuz** [comment]
This is no longer an issue with the merge of #1916. Close the issue.
