### ISSUE TITLE
Config Seed is always overwriting settings for Edinburgh 1.0.1

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#1783]
# 🐞 Bug Report

### Affected Services

config-seed

### Is this a regression?

Yes, the previous version , I think, didn't overwrite when rerunning the compose file.

### Description and Minimal Reproduction

Start Edinburgh 1.0.1. (docker-compose up)
Change the logging setting for Core Data to `TRACE` from Consul
Stop Edinburgh 1.0.1 (docker-compose down)
Start Edinburgh 1.0.1. (docker-compose up)
Check logging setting for Core Data from Consul. It will be back at `INFO`

## 🔥 Exception or Error

No error

## 🌍  Your Environment
**Deployment Environment:**
Linux
**EdgeX Version:**
Edinburgh 1.0.1

**Anything else relevant?**
Nothing

**Comment by lenny-intel** [comment]
The issue is with how Consul is being run, not with confg-seed. Closing this issue and opened https://github.com/edgexfoundry/developer-scripts/issues/135

**Comment by anonymouse64** [comment]
FWIW the snap does not have this problem because it runs consul in normal mode:

https://github.com/edgexfoundry/edgex-go/blob/16192152b3c66082da2350bd202f4259c7319125/snap/local/runtime-helpers/bin/start-consul.sh#L4-L7
