### ISSUE TITLE
XMPP export connector

### ISSUE THREAD

**Issue by janko-isidorovic** [edgexfoundry/edgex-go#179]
Add support in export client and export distro services to allow for data export using XMPP protocol.

**Comment by yanghua** [comment]
@drasko please assign to me, thanks!

**Comment by yanghua** [comment]
@janko-isidorovic  it seems @drasko has the assignment permission.

**Comment by drasko** [comment]
@yanghua for some reason you do not appear on the list of possible assignees here.

Please proceed with implementation, we know that you reserved this issue.

**Comment by yanghua** [comment]
hi @janko-isidorovic and @drasko I am going to start this task. I am finding the XMPP's golang client. Here is a  [searching result](https://godoc.org/?q=xmpp) , I tend to choose the first package. Any suggestion or other choice? thanks

**Comment by drasko** [comment]
@yanghua this one looks OK: https://github.com/mattn/go-xmpp

BSD-3 license should be compatible with Apache-2.0, so this is OK also.

**Comment by yanghua** [comment]
@drasko thanks, pick it~

**Comment by yanghua** [comment]
status : ongoing

**Comment by yanghua** [comment]
@tsconn23 this one can be closed, the PR #261 has been merged~

**Comment by janko-isidorovic** [comment]
Done via  #261
