### ISSUE TITLE
edgex docker images can not launch in raspbian-buster-lite os, and the docker logs is :standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by liuzhenhee** [edgexfoundry/edgex-go#1797]
# 🐞 Bug Report

### Affected Services
The issue is located in: all docker imagex of edgex components.

### Description and Minimal Reproduction
when i launch the edgex images with docker-compose, all the container status  are exit 1:

root@raspberrypi:/home/pi/share# docker-compose up -d
Starting edgex-files ... done
Starting edgex-support-rulesengine ... done
Starting edgex-mongo               ... done
Starting edgex-core-consul         ... done
Starting edgex-config-seed         ... done
Starting edgex-support-logging     ... done
Starting edgex-core-metadata       ... done
Starting edgex-core-data           ... done
Starting edgex-support-notifications ... done
Starting edgex-export-client         ... done
Starting edgex-core-command          ... done
Starting edgex-support-scheduler     ... done
Starting edgex-export-distro         ... done
Starting edgex-device-mqtt           ... done
Starting edgex-device-modbus         ... done
root@raspberrypi:/home/pi/share# 
root@raspberrypi:/home/pi/share# 
root@raspberrypi:/home/pi/share# docker-compose ps
           Name                          Command               State    Ports
-----------------------------------------------------------------------------
edgex-config-seed             /edgex/cmd/config-seed/con ...   Exit 1        
edgex-core-command            /core-command --registry - ...   Exit 1        
edgex-core-consul             docker-entrypoint.sh agent ...   Exit 1        
edgex-core-data               /core-data --registry --pr ...   Exit 1        
edgex-core-metadata           /core-metadata --registry  ...   Exit 1        
edgex-device-modbus           /device-modbus --profile=d ...   Exit 1        
edgex-device-mqtt             /device-mqtt --profile=doc ...   Exit 1        
edgex-export-client           /export-client --registry  ...   Exit 1        
edgex-export-distro           /export-distro --registry  ...   Exit 1        
edgex-files                   /bin/sh -c /usr/bin/tail - ...   Exit 1        
edgex-mongo                   /bin/sh -c /edgex/mongo/co ...   Exit 1        
edgex-support-logging         /support-logging --registr ...   Exit 1        
edgex-support-notifications   /support-notifications --r ...   Exit 1        
edgex-support-rulesengine     /bin/sh -c java -jar -Djav ...   Exit 1        
edgex-support-scheduler       /support-scheduler --regis ...   Exit 1        

And the logs of docker is:
root@raspberrypi:/home/pi/share# docker logs 5cde2024cf19
standard_init_linux.go:207: exec user process caused "exec format error"
standard_init_linux.go:207: exec user process caused "exec format error"

The logs of above is  export-distro-go-arm64:1.0.1, and the other components are the same result.

## 🌍  Your Environment
My yml file:
root@raspberrypi:/home/pi/share# cat docker-compose.yml 
version: '3'
volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  portainer_data:

services:
  volume:
    image: edgexfoundry/docker-edgex-volume-arm64:1.0.0
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      
  consul:
    image: arm64v8/consul:1.1.0
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume  

  config-seed:
    image: edgexfoundry/docker-core-config-seed-go-arm64:1.0.1
    container_name: edgex-config-seed
    hostname: edgex-core-config-seed
    networks:
      edgex-network:
        aliases:
            - edgex-core-config-seed
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - consul
      
  mongo:
    image: edgexfoundry/docker-edgex-mongo-arm64:1.0.1
    ports:
      - "27017:27017"
    container_name: edgex-mongo
    hostname: edgex-mongo
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  logging:
    image: edgexfoundry/docker-support-logging-go-arm64:1.0.1
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - config-seed
      - mongo
      - volume

  notifications:
    image: edgexfoundry/docker-support-notifications-go-arm64:1.0.1
    ports:
      - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  metadata:
    image: edgexfoundry/docker-core-metadata-go-arm64:1.0.1
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  data:
    image: edgexfoundry/docker-core-data-go-arm64:1.0.1
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  command:
    image: edgexfoundry/docker-core-command-go-arm64:1.0.1
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - metadata

  scheduler:
    image: edgexfoundry/docker-support-scheduler-go-arm64:1.0.1
    ports:
      - "48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - metadata

  export-client:
    image: edgexfoundry/docker-export-client-go-arm64:1.0.1
    ports:
      - "48071:48071"
    container_name: edgex-export-client
    hostname: edgex-export-client
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - data
    environment:
      - EXPORT_CLIENT_MONGO_URL=edgex-mongo
      - EXPORT_CLIENT_DISTRO_HOST=edgex-export-distro
      - EXPORT_CLIENT_CONSUL_HOST=edgex-config-seed

  export-distro:
    image: edgexfoundry/docker-export-distro-go-arm64:1.0.1
    ports:
      - "48070:48070"
      - "5566:5566"
    container_name: edgex-export-distro
    hostname: edgex-export-distro
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-client
    environment:
      - EXPORT_DISTRO_CLIENT_HOST=edgex-export-client
      - EXPORT_DISTRO_DATA_HOST=edgex-core-data
      - EXPORT_DISTRO_CONSUL_HOST=edgex-config-seed
      - EXPORT_DISTRO_MQTTS_CERT_FILE=none
      - EXPORT_DISTRO_MQTTS_KEY_FILE=none

  rulesengine:
    image: edgexfoundry/docker-support-rulesengine-arm64:1.0.0
    ports:
      - "48075:48075"
    container_name: edgex-support-rulesengine
    hostname: edgex-support-rulesengine
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data

  device-mqtt:
    image: edgexfoundry/docker-device-mqtt-go-arm64:1.0.0
    ports:
      - "49982:49982"
    container_name: edgex-device-mqtt
    hostname: edgex-device-mqtt
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - data
      - command

  device-modbus:
    image: edgexfoundry/docker-device-modbus-go-arm64:1.0.0
    ports:
      - "49991:49991"
    container_name: edgex-device-modbus
    hostname: edgex-device-modbus
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - data
      - command

networks:
  edgex-network:
    driver: "bridge"
...

My os is raspbian-buster-lite:2019-07-10-raspbian-buster-lite,img download from https://www.raspberrypi.org/

**Comment by anonymouse64** [comment]
If you are running Raspbian, then I'm fairly certain you are running armhf, which is not supported by the project. You need to use arm64 to run the published EdgeX containers, see https://wiki.edgexfoundry.org/display/FA/Running+on+a+RaspberryPi for how to run arm64 Ubuntu 18.04 LTS Server on the Raspberry Pi 3B+ and use EdgeX.
