### ISSUE TITLE
security-secretstore-setup to spawn security-file-token-provider to issue per-service authentication tokens

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1798]
[security-file-token-provider](https://github.com/edgexfoundry/edgex-docs/blob/master/security/security-file-token-provider.1.rst) needs to be spawned from security-secretstore-setup after the secret store has been unsealed.

This functionality is modeled after [system/agent/executor](https://github.com/edgexfoundry/edgex-go/blob/master/internal/system/agent/executor/executor.go)

This process may be either a short-lived process that creates tokens once at startup, or a long-lived process that provides an authenticated mechanism for services to request tokens at runtime.  In the initial implementation, [security-file-token-provider](https://github.com/edgexfoundry/edgex-docs/blob/master/security/security-file-token-provider.1.rst) is provided using the short-lived process model.

This feature depends on https://github.com/edgexfoundry/edgex-go/pull/1793

Details:

1. Extend the TOML configuration with the following entries
```
[SecretService]
TokenProvider = "security-file-token-provider"
TokenProviderArgs = [ "-confdir", "res/file-token-provider" ]
TokenProviderType = "oneshot"
```

2. Verify the TokenProvider is on the PATH

3. Launch the TokenProvider with supplied TokenProviderArgs (it will be necessary to point at the TokenProvider's configuration.toml)

4. If TokenProviderType="oneshot" (the only supported value at this time) then secretstore-setup should wait for the token provider to finish execution before continuing.  The exit status of the process needs to be properly logged.  The tool will create its own logs.

**Comment by anonymouse64** [comment]
The design here looks good to me and is about what I imagined when suggesting we follow the SMA in this regard
