### ISSUE TITLE
Remove code obsoleted by common bootstrap package

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1811]
Dependent upon completion of #1801, #1802, #1803, #1804, #1805, #1806, #1807, #1808, #1809, and #1810, and https://github.com/edgexfoundry/edgex-go/issues/2236.

**Comment by michaelestrin** [comment]
In conversation with @tsconn23, @tingyuz, and @AnthonyMBonafide yesterday, agreed to put #1805 and #1806 hold until after October Fuji freeze. Follow-on Fuji security release will address those issues.  Because this issue is dependent on the completion of those two issues, this issue will also be delayed.

**Comment by tsconn23** [comment]
@michaelestrin It looks like the only thing pending on this is removal of config-seed, is that correct? Per Core WG 27-Feb-2020 there are some action items in the core/support services before that can happen.

**Comment by michaelestrin** [comment]
Yes.  config-seed removal precedes this.

**Comment by AnthonyMBonafide** [comment]
Since we have completed the work to add config-seed functionality into `go-mod-bootstrap` and updated edgex-go to use a version which has that functionality(`v.0.0.26`) we can now remove the `config-seed` packages and functionality from this repo

**Comment by brandonforster** [comment]
@AnthonyMBonafide is there any work here that wasn't handled by #2445?

**Comment by AnthonyMBonafide** [comment]
@brandonforster , I forgot to add a comment explaining this further. The `config-seed` packages have been removed. However there is some lingering functionality that can be removed. It looks like we can remove the Retry struct:
https://github.com/edgexfoundry/edgex-go/blob/f758cd6862d8e6cc426c71a8990c23b386da041b/internal/pkg/startup/bootstrap.go#L19

Also, we can probably remove the `loader.go`, `environment.go` and `environment_test.go` files completely:
https://github.com/edgexfoundry/edgex-go/tree/f758cd6862d8e6cc426c71a8990c23b386da041b/internal/pkg/config

Please verify these can be safely removed and there is no other lingering functionality.
