### ISSUE TITLE
standardize consul location options/env vars

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1822]
# 🚀 Feature Request

The device services now understand a `--registry` flag as having a value, which is the location of the registry (consul) as a URL such as in the following:

```
$ ./device-mqtt --registry=consul://localhost:8500
```

However the core services still just use `--registry` as a binary option, where if it's true/present then we look at the configuration.toml file to determine the location of consul. I think we should try to standardize these things between the core services/device services/app function services. 

@michaelestrin says that the core services actually understand the location of consul through an environment variable, which I'd be fine with if the device services/app function services also did, the main thing I'm requesting here is that we get all services to be consistent in providing this information.

Additionally, it sounds like this kind of work should be much easier with the ongoing work to make all the core services share a common bootstrap package.

**Comment by michaelestrin** [comment]
If implemented, this should be dependent upon completion of #1801, #1802, #1803, #1804, #1805, #1806, #1807, #1808, #1809, and #1810.  These convert the core services to use the common bootstrap package -- which, once converted, would provide a single place to make this change to affect all core services.

Note also that I've requested discussion around this topic for the next core working group meeting.  As such, I'm attaching a hold label to this issue pending the outcome of that discussion.

**Comment by anonymouse64** [comment]
FWIW, the hold label I think is just for PR's that we don't want to be merged, I don't think we normally use that for issues, but yes understood it should be discussed in the core WG meeting

**Comment by tsconn23** [comment]
Updating thread based on Core WG 26-Sept-19

This will be an agenda item in the Device Services WG call on Monday 30-Sept-19. After review, the recommendation to the DS team will be to rework the `--registry` cmd line flag to provide some level of consistency with the App/Core services. The scope of the desired functionality is reflected in [this comment](https://github.com/edgexfoundry/device-sdk-go/pull/274#issuecomment-492248352) from an earlier PR.

**Comment by michaelestrin** [comment]
Dependency on https://github.com/edgexfoundry/edgex-go/pull/2133; see ADR embedded therein.

**Comment by michaelestrin** [comment]
@anonymouse64 

Is this issue addressed by https://github.com/edgexfoundry/go-mod-registry/issues/37, https://github.com/edgexfoundry/go-mod-bootstrap/issues/18, and https://github.com/edgexfoundry/edgex-go/pull/2317?  

If so, please signify so and close the issue.

If not, please clarify what additional/different behavior is requested.

**Comment by anonymouse64** [comment]
@michaelestrin that PR is not merged, as such I would recommend waiting to close this issue until the feature is completed and merged

**Comment by michaelestrin** [comment]
@anonymouse64 For clarity's sake, does the outstanding PR address this issue?

**Comment by anonymouse64** [comment]
Does the app-functions-sdk-go, the device-sdk-go and device-sdk-c use the same pattern as what's implemented in that PR?

**Comment by lenny-intel** [comment]
> Does the app-functions-sdk-go, the device-sdk-go and device-sdk-c use the same pattern as what's implemented in that PR?

Note yet, but we are moving that direction.

**Comment by tsconn23** [comment]
Closing following on work related to removal of config-seed and standardization of env variables.
