### ISSUE TITLE
Refactor core data clients value descriptor test from integration testing to unit testing

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#183]
code here : [makes a real http request](https://github.com/edgexfoundry/edgex-go/blob/master/core/clients/coredataclients/valuedescriptor_test.go#L36) 

if there is not a http server started before testing, it would return error.

claim it~

**Comment by yanghua** [comment]
cc @drasko

**Comment by jpwhitemn** [comment]
Hi Vino - I would ask that you work with the core development team (in particular @tsconn23 ) before claiming or working on this issue.  Issues like this really require some coordination with the main project leads to make sure they are consistent with the long term strategy and design of these services.

**Comment by yanghua** [comment]
hi @tsconn23 can I start this issue, replace the real http request to a mock server ?

**Comment by tsconn23** [comment]
@yanghua OK

**Comment by yanghua** [comment]
thanks @tsconn23 , closing this...
