### ISSUE TITLE
Cannot detect VCS 

### ISSUE THREAD

**Issue by john0576** [edgexfoundry/edgex-go#184]
hi,
   when i run glide install, error comes out, and log as following, please help solve
[root@localhost edgex-go]# glide install
[INFO]	Loading mirrors from mirrors.yaml file
[INFO]	Lock file (glide.lock) does not exist. Performing update.
[INFO]	Loading mirrors from mirrors.yaml file
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching updates for github.com/BurntSushi/toml
[INFO]	--> Fetching updates for github.com/eclipse/paho.mqtt.golang
[INFO]	--> Fetching updates for github.com/go-zoo/bone
[INFO]	--> Fetching updates for github.com/gorilla/mux
[INFO]	--> Fetching updates for github.com/hashicorp/consul
[INFO]	--> Fetching updates for github.com/influxdata/influxdb
[INFO]	--> Fetching updates for github.com/pebbe/zmq4
[INFO]	--> Fetching updates for github.com/robfig/cron
[INFO]	--> Fetching updates for go.uber.org/zap
[INFO]	--> Fetching updates for gopkg.in/mgo.v2
[INFO]	--> Fetching updates for gopkg.in/yaml.v2
[INFO]	--> Detected semantic version. Setting version for github.com/robfig/cron to v1
[INFO]	--> Detected semantic version. Setting version for github.com/BurntSushi/toml to v0.3.0
[INFO]	--> Detected semantic version. Setting version for github.com/eclipse/paho.mqtt.golang to v1.1.1
[INFO]	--> Detected semantic version. Setting version for github.com/gorilla/mux to v1.6.1
[INFO]	--> Detected semantic version. Setting version for github.com/go-zoo/bone to 1.2
[INFO]	--> Detected semantic version. Setting version for github.com/hashicorp/consul to v1.0.7
[INFO]	--> Detected semantic version. Setting version for github.com/influxdata/influxdb to 1.6
[INFO]	--> Detected semantic version. Setting version for go.uber.org/zap to v1.8.0
[INFO]	--> Detected semantic version. Setting version for gopkg.in/yaml.v2 to v2.2.1
[INFO]	Resolving imports
[INFO]	--> Fetching updates for go.uber.org/atomic
[INFO]	--> Detected semantic version. Setting version for go.uber.org/atomic to v1.3.2
[INFO]	--> Fetching updates for go.uber.org/multierr
[INFO]	--> Detected semantic version. Setting version for go.uber.org/multierr to v1.1.0
[INFO]	--> Fetching updates for github.com/gorilla/context
[INFO]	Found Godeps file in /root/.glide/cache/src/https-github.com-influxdata-influxdb
[INFO]	--> Parsing GPM metadata...
[INFO]	--> Fetching golang.org/x/net/proxy
[WARN]	Unable to checkout golang.org/x/net/proxy
[INFO]	--> Fetching golang.org/x/net/websocket
[WARN]	Unable to checkout golang.org/x/net/websocket
[INFO]	--> Fetching updates for github.com/hashicorp/go-cleanhttp
[INFO]	--> Fetching updates for github.com/hashicorp/go-rootcerts
[INFO]	--> Fetching updates for github.com/hashicorp/serf
[WARN]	Conflict: go.uber.org/zap version is ^1.8.0, but also asked for 35aad584952c3e7020db7b839f6b102de6271f89
[INFO]	go.uber.org/zap reference 35aad584952c3e7020db7b839f6b102de6271f89 (v1.7.1):
[INFO] - author: Prashant Varanasi <github@prashantv.com>
[INFO] - commit date: Mon, 25 Sep 2017 12:53:02 -0700
[INFO] - subject (first line): MapEncoder: Store strings in map when AddByteString is used (#504)
[INFO]	Keeping go.uber.org/zap ^1.8.0
[INFO]	--> Fetching updates for github.com/mitchellh/go-homedir
[INFO]	--> Fetching updates for github.com/armon/go-metrics
[INFO]	--> Fetching updates for github.com/hashicorp/go-immutable-radix
[INFO]	--> Fetching updates for github.com/hashicorp/golang-lru
[INFO]	Downloading dependencies. Please wait...
[INFO]	Setting references for remaining imports
[ERROR]	Failed to set version on golang.org/x/net/websocket to : Cannot detect VCS
[ERROR]	Failed to set version on golang.org/x/net/proxy to : Cannot detect VCS
[ERROR]	Failed to set references: Cannot detect VCS
Cannot detect VCS (Skip to cleanup)
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/go-zoo/bone
[INFO]	--> Exporting github.com/BurntSushi/toml
[INFO]	--> Exporting github.com/gorilla/mux
[INFO]	--> Exporting github.com/eclipse/paho.mqtt.golang
[INFO]	--> Exporting github.com/influxdata/influxdb
[INFO]	--> Exporting github.com/hashicorp/consul
[INFO]	--> Exporting github.com/robfig/cron
[INFO]	--> Exporting github.com/pebbe/zmq4
[INFO]	--> Exporting github.com/gorilla/context
[INFO]	--> Exporting github.com/hashicorp/go-cleanhttp
[INFO]	--> Exporting github.com/mitchellh/go-homedir
[INFO]	--> Exporting github.com/hashicorp/go-rootcerts
[INFO]	--> Exporting github.com/hashicorp/serf
[INFO]	--> Exporting go.uber.org/zap
[INFO]	--> Exporting go.uber.org/multierr
[INFO]	--> Exporting go.uber.org/atomic
[INFO]	--> Exporting github.com/armon/go-metrics
[INFO]	--> Exporting github.com/hashicorp/go-immutable-radix
[INFO]	--> Exporting github.com/hashicorp/golang-lru
[INFO]	--> Exporting gopkg.in/mgo.v2
[INFO]	--> Exporting gopkg.in/yaml.v2
[ERROR]	Cannot detect VCS

**Comment by tsconn23** [comment]
Are you behind a proxy? If so, it could be blocking the fetch. I just deleted my local glide.lock and did a "glide install" from home, no problems. In any case this is a glide issue. Closing.
