### ISSUE TITLE
empty POST's to /api/v1/operation return `null`

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1856]
# 🐞 Bug Report

### Affected Services

 The issue is located in: the system management agent

### Is this a regression?

yes

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction

* empty POST's to /api/v1/operation return `null`:

```
$ curl --verbose -X POST -d "{}" localhost:48090/api/v1/operation; echo
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 48090 (#0)
> POST /api/v1/operation HTTP/1.1
> Host: localhost:48090
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 2 out of 2 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 01 Oct 2019 18:42:28 GMT
< Content-Length: 5
< 
null
* Connection #0 to host localhost left intact
```

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 19.04
**EdgeX Version:**
master branch

**Anything else relevant?**

**Comment by anonymouse64** [comment]
There are a few others I will add to this bug report in a little bit

**Comment by michaelestrin** [comment]
https://github.com/edgexfoundry/edgex-go/issues/1851

**Comment by michaelestrin** [comment]
@anonymouse64 -- in the future, please create a separate issue for each bug report.
