### ISSUE TITLE
Apply error-handling pattern to core-command and core-data REST Handlers

### ISSUE THREAD

**Issue by jbonafide623** [edgexfoundry/edgex-go#1860]
# 🚀 Feature Request

### Relevant Package

- core-data
- core-command

### Description

In core-metadata, a pattern has been put in place in effort to create common way of handling HTTP errors. This approach uses a set of structs referred to as ErrorConcepts. These structs encapsulate all of the properties needed for type-checking, setting the error on the responseWriter, and logging the error. 

We need to apply this same pattern of error-handling to the core-data and core-command services.

### Describe the solution you'd like

The recommended solution is to go through core-data and core-command updating all error-handling to use the same pattern used in core-metadata REST handlers.

This effort may include abstracting out common errors in both core-command and core-data and reusing ErrorConcepts where applicable.

### Describe alternatives you've considered

None

**Comment by brandonforster** [comment]
Core Data is satisfactorily complete. This issue does not accurately reflect the amount of work required to satisfactorily apply error concepts to core-command, and #2012 has been created to supercede this and better track that effort in the Geneva cycle.
