### ISSUE TITLE
Create README for System Management Executor Implementation

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1865]
From https://github.com/edgexfoundry/edgex-go/issues/1851:

>  Additionally, we have no docs for what all is required for an executor to integrate with the agent, so if someone does implement their own custom executor and deploy it, we shouldn't be requiring them to read through all the code

Create a README.md in internal/system/executor geared towards a developer interested in creating their own executor.  Include information on:

- How agent passes service name, action, and optional parameters on the command line.
- Current proxy-like behavior for stop/start/restart operations -- agent passes parameters received to executor as-is.
- Metrics result contract (and its support for embedding executor-specific results).
- Expected format of operation result (based upon the existing Docker executor implementation).

**Comment by akramtexas** [comment]
@michaelestrin that sounds good, I will get started on this shortly 👍
