### ISSUE TITLE
GET to /api/v1/operation returns nothing when it should an error in addition to 405 (it does return 405)

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1867]
# 🐞 Bug Report

### Affected Services

 The issue is located in: the system management agent

### Is this a regression?

yes

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction

* GET to /api/v1/operation returns nothing when it should an error in addition to 405 (it does return 405)

```
$ curl --verbose -X GET  localhost:48090/api/v1/operation; echo
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 48090 (#0)
> GET /api/v1/operation HTTP/1.1
> Host: localhost:48090
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< Date: Tue, 01 Oct 2019 18:43:36 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 19.04
**EdgeX Version:**
master branch

**Anything else relevant?**

Extracted from https://github.com/edgexfoundry/edgex-go/issues/1856

**Comment by akramtexas** [comment]
- I confirmed that a GET to /api/v1/operation returns no error, and that it does return an HTTP 405.
- One possibility to returning an error that I investigated is the following, in `router.go` for `SMA`:
```
func operationHandler(...) {
...
	if r.Method != http.MethodPost {
		// w.WriteHeader(http.StatusMethodNotAllowed)
		w.Write([]byte("a GET call was incorrectly used instead of the proper POST call"))
		return
	}
```
- But it appears that only calls (made to the `/api/v1/operation` endpoint) with a `POST` ever make it to the `operationHandler(...){...}`, which means that we need to intercept the incoming call further upstream:
```
	b.HandleFunc("/operation", func(w http.ResponseWriter, r *http.Request) {
		operationHandler(w, r, bootstrapContainer.LoggingClientFrom(dic.Get), container.OperationsFrom(dic.Get))
	}).Methods(http.MethodPost)
```
- Need to investigated further.

**Comment by michaelestrin** [comment]
Create a new route with an invalidOperationHandler to handle the get error variant.  Error content should be the same as Edinburgh to ensure backwards compatibility.  Reach out if you have questions.

@akramtexas

**Comment by akramtexas** [comment]
> Create a new route with an invalidOperationHandler to handle the get error variant. Error content should be the same as Edinburgh to ensure backwards compatibility. Reach out if you have questions.
> 
> @akramtexas

@michaelestrin Excellent suggestion, thanks, I will follow up with implementation 👍

**Comment by michaelestrin** [comment]
Spoke with @akramtexas.  He tested this use case against Edinburgh branch.  Behavior in master is the same as in Edinburgh branch -- we return a 405 with no error message.  

Not a bug.  Closing without fixing.  @anonymouse64

**Comment by anonymouse64** [comment]
@michaelestrin then this is a bug for master _and_ edinburgh

**Comment by michaelestrin** [comment]
@anonymouse64 How is this a bug exactly?

**Comment by michaelestrin** [comment]
I understand the call for consistency and agree with it.

I don't agree the current inconsistent implementation is a bug or something that needs to be fixed for Fuji.  There's nothing in the RAML for this call that specifies an error message is required for this particular use case.  There's a push, I believe, post-Fuji to standardize request and response content -- I suggest that effort would be the appropriate place to address this concern.

**Comment by michaelestrin** [comment]
Believe the following are related and were discussed at last week's Chicago F2F as in-scope for Geneva:

> Create and separate Request and Response types for API endpoints; these would be defined in go-mod-core-contracts request and response types and clean up metadata (removing any unused elements and simplifying where possible).  This will allow the request and responses bodies of some APIs – especially around things like creating a device profile – to be greatly simplified and smaller.  This will require Geneva be a 2.0 release because of non-backward compatible changes associated.

...and...

> Establish a document template for API information (description, request/response details and organization, response and error codes, etc.)  This will be used to better define the Swagger documents that will be created as well as better support the certification process needs.

I don't believe any issues have been created yet.

**Comment by michaelestrin** [comment]
See also https://wiki.edgexfoundry.org/display/FA/Oct+9+Geneva+F2F+Prewire
