### ISSUE TITLE
Returning 503 Status is Incorrect

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#188]
It's pretty pervasive that services in all bounded contexts return 503 when they encounter some type of runtime exception. They should instead return 500 as 503 is specifically used for temporary conditions where the web server is too busy to respond.

I'm creating this issue right now to track it. Once we get past California, it might make sense to split it according to the bounded contexts (export, support, core, device) and then assign each individually to the respective chairperson.

We'll also need to decide if we make these changes in the Java code.

**Comment by tsconn23** [comment]
@andyf1967 Per the Core WG call yesterday, we pushed this to Delhi. When we make this change, it will affect any tests that are expecting 503 status. FYI.

**Comment by andyf1967** [comment]
@tsconn23 got it!

cc @weichou1229 @cloudxxx8

**Comment by brandonforster** [comment]
@tsconn23 should we close this issue as it has been addressed by sub issues?

**Comment by tsconn23** [comment]
Agreed. Handled by #407 #408 #409 #410
