### ISSUE TITLE
Make the pkisetup-vault.json and pkisetup-kong.json filenames configurable for security-secrets-setup

### ISSUE THREAD

**Issue by eno-intel** [edgexfoundry/edgex-go#1885]
Currently the certificate configuration file names for vault and kong are hardcoded in security-secrets-setup as pkisetup-vault.json and pkisetup-kong.json.
Support making the file names configurable.

Related issues:
#1924

**Comment by tingyuz** [comment]
duplicated with #1924 , close this one.
