### ISSUE TITLE
Check the consul/registry for the configurable settings in security-secrets-setup

### ISSUE THREAD

**Issue by eno-intel** [edgexfoundry/edgex-go#1889]
Support reading the registry for the configured settings like WorkDir, DeployDir, etc. in security-secrets-setup.
Further discussion is needed on the validity of this use case since security-secrets-setup runs in one shot and finishes before the registry service comes up.
Below is the conversation...

```
internal/security/setup/option/optionHelpers.go
	if xdgRuntimeDir, ok := os.LookupEnv(envXdgRuntimeDir); ok {
		return xdgRuntimeDir
		workDir = filepath.Join(xdgRuntimeDir, pkiInitBaseDir)
	} else if setup.Configuration.SecretsSetup.WorkDir != "" {
```
@anonymouse64
anonymouse64 2 days ago  Member
eventually this should also check consul/registry for the settings, but that's not for this PR

  @jim-wang-intel
jim-wang-intel yesterday  Contributor
agree, let's put that into future enhancement for using registry

  @bnevis-i
bnevis-i 20 hours ago  • 
 Contributor
This utility will likely run before the registry is up. It will definitely run before the registry is up if we (at a later date) generate a TLS certificate for the registry using this tool.

  @anonymouse64
anonymouse64 19 hours ago  Member
My understanding was that we will not be generating a TLS certificate for the registry in the short or medium term, so I'd rather see us be consistent with storing configuration in files and also optionally in consul, then deal with the problem of bootstrapping consul later.

Is there another reason why this utility would run before consul other than generating a TLS certificate for the registry some day?

  @bnevis-i
bnevis-i 19 hours ago  Contributor
Service-to-service encryption. If Consul Connect were used to provide that using a Vault back-end as a certificate provider, that would also affect the start order by having Consul depend on Vault rather than Vault depend on Consul, or having two Consul instances. Again, no design implied or proposed -- just possibility thinking here.

  @anonymouse64
anonymouse64 19 hours ago  Member
Hmm, well regardless let's file an issue about this so we don't lose this discussion and can bring the issue to a wider audience than just this PR.

**Comment by bnevis-i** [comment]
Believe we should drop this ticket permanently in order to enable #2453 to move forward.

Since this ticket was filed I have learned that we are using consul for service location.  Using an insecure configuration service to bootstrap security seems like a bad idea.

@mkbhanda  do you agree?

**Comment by mkbhanda** [comment]
Agree 100%, hardly a secure foundation!

**Comment by bnevis-i** [comment]
Closing w/consent of WG chair.
