### ISSUE TITLE
Device Service Callbacks From Metadata

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#189]
Per work on the DS SDK requirements, there needs to be metadata updates (/callback) specified in the RAML (currently incomplete).  More needs to be done with the design and API around what happens when Metadata is given changes and it needs to notify other services like Device Services with.  This is a post California issue.

**Comment by tsconn23** [comment]
Per our Device Service meeting yesterday, I believe we have decided to deprecate this functionality in order to prevent more than one source of truth for device/schedule definitions. @jpwhitemn @tonyespy please correct me if I'm wrong.

**Comment by tsconn23** [comment]
Closing since no feedback to the contrary.
