### ISSUE TITLE
Logging & Config-Seed Docker 

### ISSUE THREAD

**Issue by levystasman** [edgexfoundry/edgex-go#1899]
Newbie to edgex. Trying to get it running following using docker

https://docs.edgexfoundry.org/Ch-WalkthroughRunning.html

but constantly errors out. Any help appreciated

edgex-support-logging
level=ERROR ts=2019-10-13T04:50:08.8215509Z app=edgex-support-logging source=logger.go:105 msg="logTarget cannot be blank, using stdout only"
level=ERROR ts=2019-10-13T04:50:08.8216213Z app=edgex-support-logging source=main.go:72 msg="registry is not available"

edgex-config-seed
level=ERROR ts=2019-10-13T04:49:54.4588928Z app=edgex-config-seed source=main.go:79 msg="registry is not available"
level=ERROR ts=2019-10-13T04:49:55.469439Z app=edgex-config-seed source=logger.go:105 msg="logTarget cannot be blank, using stdout only"
level=ERROR ts=2019-10-13T04:49:55.4695122Z app=edgex-config-seed source=main.go:92 msg="edgex-config-seed: Service bootstrap failed!"

**Comment by tsconn23** [comment]
Please take questions like this to the #help channel on edgexfoundry.slack.com. And be sure to specify which release you're using.
