### ISSUE TITLE
Retry registration to Consul

### ISSUE THREAD

**Issue by rtmaster** [edgexfoundry/edgex-go#19]
Ideally, by performing a 
_docker-compose up_ 
all microservices should come up in the correct manner, without the need to run a shell script delaying the startup because the Go services are "too fast" and come up before Consul.
Since there is no sleep mechanism in docker compose, this should be in the logic of the Go microservices which should retry at specific intervals (5 sec?) to locate Consul and register themselves.

**Comment by drasko** [comment]
@feclare what's the status of this one?

**Comment by drasko** [comment]
@feclare are we closing this one?

**Comment by tsconn23** [comment]
@drasko I would leave this one open as it corresponds to requirements in the [service naming](https://wiki.edgexfoundry.org/display/FA/Architecture+Issues+and+Decisions?preview=%2F7602423%2F12124315%2FServiceNameDesign.odt) document. I'll put a Delhi tag on it.

**Comment by tsconn23** [comment]
Closing. Duplicates of #182, #441, #442
