### ISSUE TITLE
micro services POSIX support

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#190]
Our microservices need to support POSIX signal handling when running in Linux environment.  We'll first have to determine what supporting POSIX means for EdgeX microservices, and then incorporate in service APIs and possibly the proposed system management agent being proposed for Delhi.

**Comment by brandonforster** [comment]
What's the status of this issue?

**Comment by jpwhitemn** [comment]
Closing this issue - can be handled with system management executor
