### ISSUE TITLE
Incorrect return code when running negative reading/valuedescriptor test cases

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1901]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Data

### Is this a regression? Yes

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
API : {{baseURL}}:48080/api/v1/reading
Method : PUT
Request body: 
```
{
    "id": "57e866d4e4b0ca8e6d73a412",
    "created": 1475227070170,
    "modified": 1475227070170,
    "origin": 1471806366619,
    "device": "powerScoutMeter",
    "pushed": 0,
    "name": "co2",
    "value": "12"
}
```
**Expected return code : 404
Actual return code : 500**

The following test cases also failed and returned "500 Internal Server Error" on the BlackBox test.

- reading_error_4xx / 38 http://localhost:48080/api/v1/reading
- reading_error_4xx / 47 http://localhost:48080/api/v1/reading/id/:id
- valuedescriptor_error_4xx / 103 http://localhost:48080/api/v1/valuedescriptor
- valuedescriptor_error_4xx / 72 http://localhost:48080/api/v1/valuedescriptor
- valuedescriptor_error_4xx / 77 http://localhost:48080/api/v1/valuedescriptor/id/:id
- valuedescriptor_error_4xx / 78 http://localhost:48080/api/v1/valuedescriptor/id/:id 409
- valuedescriptor_error_4xx / 83 http://localhost:48080/api/v1/valuedescriptor/name/:name
- valuedescriptor_error_4xx / 84 http://localhost:48080/api/v1/valuedescriptor/name/:name 409

## 🔥 Exception or Error
<pre><code> Got return code : 500 Internal Server Error

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 18.04

**EdgeX Version:** Master

**Anything else relevant?**

**Comment by tsconn23** [comment]
Believe this is related to #1909
