### ISSUE TITLE
Refactor support-logging to use common database handler

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1903]
Refactor support-logging (https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/logging/init.go) to use the common database bootstrap created for #1868 (PR #1902).

**Comment by michaelestrin** [comment]
Per @andresrinivasan, Redis isn't an ideal destination for log files.  This issue should convert to use the common database handler but limit database support to the existing Mongo and file system options.

**Comment by andresrinivasan** [comment]
To quote myself

> For now, my vote is the default should be file. I would argue against sending log lines to a DB without correlation across the services. I would rather see an integration with something like rsyslog that can then be configured to go anywhere, including using Redis as a broker for pushing the logs to a centralized LogStash for correlation across services.

**Comment by michaelestrin** [comment]
Discussed in Feb 13th Core WG meeting.  Hold off on adding Redis or removing Mongo.  To be discussed at Hanoi pre-wire meeting in March.

**Comment by tsconn23** [comment]
Closing due to deprecation of support-logging in Geneva release.
