### ISSUE TITLE
Create transmission failed with error "Sender is empty"

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1911]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Support-Notifications

### Is this a regression? Yes

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
1. Create Notification with the following request body.
API : {{supportNotificationsUrl}}/api/v1/notification
Method : POST
```
{
	"slug": "notice-test-020",
	"sender": "System Management",
	"category": "SECURITY",
	"severity": "NORMAL",
	"content": "Hello, Notification!",
	"labels": [
		"cool",
		"test"
	]
}
```
2. Using the above notification to create Transmission.
API : {{supportNotificationsUrl}}/api/v1/transmission
Method : POST
```
{
    "notification": {
        "slug": "notice-test-020"
    },
    "receiver": "Jack",
    "channel": {
        "type": "REST",
        "url": "http://localhost:5566/test",
        "httpMethod": "POST"
    },
    "status": "SENT",
    "resendCount": 0,
    "records": [
        {
            "status": "SENT",
            "response": "true",
            "sent": 1472439914709
        }
    ]
}
```
Expected result: Create Notification and Transmission both successfully.
Actual result: Create Notification successful, but Transmission failed with error "Sender is empty".

## 🔥 Exception or Error
<pre><code> level=ERROR ts=2019-10-15T01:57:46.626434828Z app=edgex-support-notifications source=rest_transmission.go:43 msg="Error decoding transmission: Sender is empty"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 18.04

**EdgeX Version:** Master

**Anything else relevant?**

**Comment by tsconn23** [comment]
@cherrycl OK, so this is because validation of the Notification model in go-mod-core-contracts was added a month ago.

https://github.com/edgexfoundry/go-mod-core-contracts/commit/5c4e4c24778b1bb78a56f2f23bf46c76a7bdbe0a

As you can see, the Notification model is a property on the Transmission and the "sender" property is required and not populated. Indeed there are MANY required properties that are not populated in the test script. The only field provided is `slug`.

https://github.com/edgexfoundry/blackbox-testing/blob/b8e36661e278f75f628fa6d5afe83eacab3f87df/bin/postman-test/collections/support-notifications-importer.postman_collection.json#L672

The error being thrown as a result of the incomplete request is
```
level=ERROR ts=2019-10-16T01:19:57.464442Z app=edgex-support-notifications source=rest_transmission.go:43 msg="Error decoding transmission: Sender is empty"
```

A reworked request that passes validation looks like this:
```
"name": "Import transmissions",
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"id": "8fbfbf8d-1505-48ae-af9e-dc6b532889b4",
				"exec": [
					"// Prepare test data",
					"var data = [",
					"{",
					"    \"notification\": {",
					"        \"slug\": \"notice-020\",",
					"        \"sender\": \"Room System Management\",",
					"        \"category\": \"HW_HEALTH\",",
					"        \"severity\": \"NORMAL\",",
					"        \"content\": \" [ Notification ] Room's temperature is 82 °F\"",
					"    },",
					"    \"receiver\": \"Jack\",",
					"    \"channel\": {",
					"        \"type\": \"REST\",",
					"        \"url\": \"http://localhost:5566/test\",",
					"        \"httpMethod\": \"POST\",",
					"    },",
					"    \"status\": \"SENT\",",
					"    \"resendCount\": 0,",
					"    \"records\": [",
					"        {",
					"            \"status\": \"SENT\",",
					"            \"response\": \"true\",",
					"            \"sent\": 1472439914709",
					"        }",
					"    ]",
				"},",
```
I have added the `sender`, `category`, `severity` and `content` fields

**Comment by cherrycl** [comment]
After adding the sender and other required fields to the notification block, like below request body., I can create transmission successfully.
```
{
    "notification": {
        "slug": "notice-020",
        "sender": "System Management",
        "category": "HW_HEALTH",
        "severity": "NORMAL",
        "content": " [ Notification ] Room's temperature is 82 °F"
    },
    "receiver": "Jack",
    "channel": {
        "type": "REST",
        "url": "http://localhost:5566/test",
        "httpMethod": "POST",
    },
    "status": "SENT",
    "resendCount": 0,
    "records": [
        {
            "status": "SENT",
            "response": "true",
            "sent": 1472439914709
        }
    ]
}
```
