### ISSUE TITLE
Make docker container images read-only

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1921]
# 🚀 Feature Request

### Relevant Package
Affects the docker-compose for any given release and may initially require workarounds or code changes for containers that do not support running read-only.

### Description
The docker-compose for EdgeX should attempt to run as many services as possible with read-only root file systems.  This feature provides tampering resistance at runtime and promotes immutable infrastructures and stateless service designs. Read-only containers is also a scored item in the CIS docker benchmark.

### Describe the solution you'd like
Every container in the EdgeX docker-compose should mount its root file system as read-only.

**Comment by lenny-intel** [comment]
Along this line, all containers should be running as a non-root user. This may accomplish what you have outlined here.

**Comment by bnevis-i** [comment]
Non-root users are a separate scoring item.  I'll have to go through the benchmark and file issues for all of them.  Some will be harder than others.  Non-root user may have ripple effects.  Read-only file system seems like low-hanging fruit though.

**Comment by bnevis-i** [comment]
Filed [Make docker containers run as non-root users"](#1955)

**Comment by brian-intel** [comment]
The following containers require read/write permission to modify files within the container and do not support the read_only flag:
- device-virtual
- vault
- consul
- rulesengine

**Comment by bnevis-i** [comment]
What were the illegal accesses in all of the above?  I understand vault because of the setcap, but what about the others?

**Comment by bnevis-i** [comment]
Investigated:

- https://github.com/edgexfoundry/device-virtual-go/issues/119
- https://github.com/emqx/kuiper/issues/381
- Vault issue is known via setcap
- Consul issue requires further investigation.

**Comment by cloudxxx8** [comment]
https://github.com/edgexfoundry/developer-scripts/issues/301 opened to track Consul investigation
