### ISSUE TITLE
Refactor SecretStoreClient to combine common~~Request and commonResponse methods

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1923]
# 🚀 Feature Request

### Relevant Package
Affects secretstoreclient package

### Description
The SecretStoreClient has three common methods for formatting requests and processing responses from the secret store: `commonRequest`, `commonJSONRequest`, and `commonResponse`.

The request methods differ in that `commonJSONrequest` takes a JSON object that is serialized before calling `commonRequest`.  Request that do not require a JSON object call `commonRequest` directly.  The `common~~Request` and `commonResponse` objects are intended to be called together, where the output of the former is passed to the latter.  This creates an awkward situation that was raised in code review that the first lines of `commonResponse` handle the errors from `commonRequest`.

### Describe the solution you'd like
The proposal is to combine the request and response methods into a single function that performs the entire request flow, and define a parameter struct so that the caller can supply named arguments to the function.  Otherwise, the argument list to the combined function would be unwieldy.  The named parameter struct is to take care of the special case of whether the invoked API method requires serialization of a JSON object.

The following behavior is proposed:
- If `params.JSONObject (interface{})` is non-nil, the object is sent through the JSON marshaller and passed  to the `http.NewRequest` method.
- Otherwise, `params.BodyReader (io.Reader)` is passed to the `http.NewRequest` method unchanged.

Other named parameters will be defined for the existing positional arguments.

### Describe alternatives you've considered
In code review, it was determined that providing two named arguments, JSONObject and BodyReader with unique types would be cleaner than passing interface{} and using type assertions to dynamically decide what to do with the argument based on its type.

**Comment by anonymouse64** [comment]
Do you need my help on this? (just trying to understand why I was assigned here)

**Comment by bnevis-i** [comment]
> Do you need my help on this? (just trying to understand why I was assigned here)

Just wanted to ensure you got cc'ed on it.  I removed your from the assignees.
