### ISSUE TITLE
Revoke previously issued tokens on security-secretstore-setup startup

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1927]
# 🚀 Feature Request

### Relevant Package
Affects security-secretstore-setup

### Description
When an EdgeX host is booted we have no way of knowing how long the system has been offline.  Consequently, a required initialization step to ensure the system boots successfully is to re-issue authentication tokens for the secret store for all services.  This means that existing installations will have authentication tokens in the database that are left over from existing executions of the EdgeX framework that need to be garbage-collected not only because these abandoned tokens consume space, but because they are a security risk in the even that an access token has been stolen.  Since we regenerate access tokens every boot we don't want stale/cached/stolen access tokens to still be able to access the secret store.  Thus, we have a requirement to revoke previously issued tokens prior to issuing new ones.

### Describe the solution you'd like
The procedure for revoking tokens is as follows (with the difference that the below is done via an API instead of the CLI):

1. Determine the current (root) token ("vault token lookup") and confirm that it is a root token.
2. Determine the list of outstanding token accessors in the the system "vault list /auth/token/accessors"
3. Log information about the stale accessor - get it via "vault token lookup -accessor ~~~"
4. Revoke the token ("vault token revoke -accessor ~~~")
5. Repeat steps 3 and 4 until all tokens except the current root token have been revoked.

At the conclusion of this procedure, the token database will have been returned to its first-use condition.

### Considerations for distributed systems
EdgeX currently does not proscribe a method for running services in a distributed scenario; thus, this section is implementation dependent and discussed from a theoretical perspective.

Since tokens are passed to services via the file system, special consideration need be made for secret clients running non-local boxes.  The per-service token workflow assumes the existence of a distributed file system or some kind of file copying daemon to distribute client tokens to remote hosts.  Similarly, when tokens are revoked and reissued, this mechanism must be in place to distribute new tokens.  This means that clients must be able to detect that their token has been revoked and refresh their cached copy of the token in that case.

A possible modification of this flow in the distributed case is to call /auth/token/tidy to clean up only the expired tokens and leave the non-expired tokens live in the database, with the attendant security risk that if a token is stolen and the system rebooted, the token can be used in perpetuity to continue unauthorized access to the secret store.

**Comment by michaelestrin** [comment]
Added @AnthonyMBonafide per conversation with @bnevis-i at Geneva F2F.  Leaving myself assigned to this issue for the time being.
