### ISSUE TITLE
Standardized router

### ISSUE THREAD

**Issue by falkerson** [edgexfoundry/edgex-go#193]
Currently edgex-go uses couple of routers/dispatchers for building REST API:

* Gorilla Mux - https://github.com/edgexfoundry/edgex-go/blob/master/core/command/rest.go#L23

* Bone - https://github.com/edgexfoundry/edgex-go/blob/master/support/logging/server.go#L20

Need to run some benchmarks (maybe including some others https://github.com/julienschmidt/go-http-routing-benchmark) and select the one that best meets the needs of project

**Comment by drasko** [comment]
https://www.peterbe.com/plog/my-favorite-go-multiplexer

**Comment by jpwhitemn** [comment]
@tsconn23 is refactoring core and supporting services to isolate the router and allow for more easily replacing the router.  Having said that, options should be looked at for selecting our "reference implementation".  This is part of refactor of core services that will be part of Delhi release.

**Comment by tsconn23** [comment]
For the core refactor, there's a factory which allows a router to be swapped. If a customer decides to fork the edgex-go repo, they can use that abstraction to put any router they want in place. I don't see there being a standard router due to pros and cons of other possible features like tracing integration and so on which may/may not be appropriate for the target environment.

**Comment by tsconn23** [comment]
@falkerson Routing factory usage is here
https://github.com/edgexfoundry-holding/core-data-refactor/blob/master/core/data/routers/factory.go

This isn't really a hot topic right now. We may have more time to look at this after the California release.

**Comment by tsconn23** [comment]
Per issue #962 it is time to take up the work to migrate the routers in the legacy export services to Gorilla MUX. We will not be enabling services to swap routers based on configuration and will be standardizing on Gorilla MUX until we decide to rewrite using GoKit or some other framework. I am going to close this issue and create another one that is more targeted.
