### ISSUE TITLE
Relocate proxy TLS certificate in secret store namespace

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1931]
# 🚀 Feature Request

### Relevant Package
Affects security-secretstore-setup and security-proxy-setup.

### Description
The proxy TLS certificate is currently stored at 
```
v1/secret/edgex/pki/tls/edgex-kong
```
Starting in Geneva the above path would be a non-standard secret location.

### Describe the solution you'd like
With implementation of #1677 a more standard location for this secret to live--which would be covered by the default policy for per-service access tokens--would be
```
v1/secret/edgex/edgex-kong/tls
```
or similar.

### Related issues:
#1922 Move proxy certificate upload to vault into separate executable

**Comment by tingyuz** [comment]
close the issue at the PR-2325 to address it was merged.
