### ISSUE TITLE
Rename docker security service containers to match the new executable names

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1933]
# 🚀 Feature Request

### Relevant Package

 This feature request is for... all the security services

### Description
 A clear and concise description of the problem or missing capability...

The executables were re-named for Fuji, but the container names have not been renamed yet. i.e. `vault-worker` from edinburgh is now `security-secretstore-setup`, but we still have the docker file building as `docker-edgex-vault-worker-go`

see:

https://github.com/edgexfoundry/edgex-go/blob/e9a5679ee93190915757fda79bea1215b7647b4d/Makefile#L193-L194

I'd like to see this happen for Fuji

**Comment by bnevis-i** [comment]
@lranjbar can you please weigh-in on the devops impact of the proposed change?

**Comment by lranjbar** [comment]
There isn't any impact on devops for the naming of the docker images themselves. This change will have to happen in the Makefile in edgex-go. However, we should maintain the naming scheme docker-edgex-* for all the docker images we release.
