### ISSUE TITLE
Move Auth Token Loader functionality to go-mod-secrets

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#1934]
# 🚀 Feature Request

### Relevant Package

 This feature request affects all core-services. The changes target `secret.BootstrapHandler` and `authtokenloader` package which is used by all core-services 

### Description
The functionality in the `authtokenloader` package contains functionality for reading and parsing a token file. Since this functionality lives in edgex-go we end up having to:

1. Support a new configuration property for the location of the file. For example:
https://github.com/edgexfoundry/edgex-go/blob/d813f2465a88593405db2addd2744e201a7c7616/internal/pkg/config/types.go#L191-L196

2. Support the logic which determines when to load the token via the token file. For example:
https://github.com/edgexfoundry/edgex-go/blob/d813f2465a88593405db2addd2744e201a7c7616/internal/pkg/bootstrap/handlers/secret/secret.go#L78-L105

### Describe the solution you'd like
Move the `authtokenloader` package to go-mod-secrets and include the `tokenfile` configuration property within the `SecretConfig` struct. This will allow us to act as consumers and simply pass the configurations through to `go-mod-secrets` which will simplify the edgex-go codebase and allow other consumers of  `go-mod-secrets` to leverage the functionality as it would be accessible.

https://github.com/edgexfoundry/edgex-go/tree/c428f14c44d4033f63855cd0a738843e6e0f6c16/internal/security/authtokenloader

### Describe alternatives you've considered
N/A, this is an improvement and the alternative is to go forward with what we have now.

**Comment by AnthonyMBonafide** [comment]
The issue was created as per the discussion in PR #1914

**Comment by bnevis-i** [comment]
Is this for fuji or geneva?

**Comment by bnevis-i** [comment]
Note: removed geneva milestone as part of today's bug scrub as we didn't commit this at TSC level, though it is still geneva planned work.

**Comment by michaelestrin** [comment]
Superceded by edgexfoundry/edgex-go#2235, edgexfoundry/go-mod-bootstrap#12.
