### ISSUE TITLE
Introduce 3rd party component x/crypto/hkdf

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1937]
# 🚀 Feature Request

### Relevant Package
Affects security-secretstore-setup

### Description
Want to introduce [HKDF](https://godoc.org/golang.org/x/crypto/hkdf) as a 3rd party component in order to implement Vault master key protection (#1919).

This component is currently being used indirectly via the [GoKey](https://github.com/cloudflare/gokey) module that security-secretstore-setup is using to derive Mongodb passwords. ([csprng.go](https://github.com/cloudflare/gokey/blob/master/csprng.go))

I request a determination as to whether approval is needed to use the 3rd party dependency directly as it is already introduced indirectly.

**Comment by anonymouse64** [comment]
FWIW, the go/x/crypto package is vetted for security and correctness, and does have CVE's filed for it on occasion, so using this directly instead of the GoKey library feels safer to me than using GoKey (which may be using the hkdf package incorrectly).

**Comment by tingyuz** [comment]
This would be a good candidate of topic to be brought out during PHX F2F meeting as there is no common rules regarding introducing 3rd party package across the project.  I will put it into the list.

**Comment by bnevis-i** [comment]
Have approval from my organization to introduce this in a future commit for hardware storage linkage to vault.
