### ISSUE TITLE
Refactor all the go file name with snake_case style

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#194]
refer to some discuss : 
https://stackoverflow.com/questions/35694137/file-name-convention-for-compound-words?rq=1&utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

https://stackoverflow.com/questions/25161774/what-are-conventions-for-filenames-in-go?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

there are some file used '-' or mixed '-' && '_' especially some clients in [this dir](https://github.com/edgexfoundry/edgex-go/tree/master/export/client/clients).

they should be refactored.

cc @drasko @jpwhitemn @tsconn23

**Comment by jpwhitemn** [comment]
Per issue #195, same comments apply.  Relooking as part of core refactor for Delhi

**Comment by tsconn23** [comment]
Closing this issue as the recommendation is being applied to PRs going forward, and not as a single actionable change across the repo.
