### ISSUE TITLE
Configure password protection for postgres DB with Kong

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1943]
# 🚀 Feature Request

### Relevant Package

 This feature request is for... the security services

### Description
The default docker-compose includes PostgreSQL as the database backend for Kong, but it does not specify a password for it, meaning that the PostgreSQL database is essentially wide open to access. 

### Describe the solution you'd like
Create a kong user account with postgresql that is protected via a password, ideally store this password in Vault and have Kong retrieve the password via Vault with a specific token issued to it.

This password would be ideally generated by security-secrets-setup.

Also provide the password to PostgreSQL when it is started in an appropriate mechanism (which would need another vault token to access the password if that password is stored inside Vault)

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

We could also just specify a password in the config file that is randomly generated upon startup and stored inside Kong's filesystem so that only the Kong container can access it.

**Comment by anonymouse64** [comment]
This is not yet a problem for the snap, but will be shortly as we transition to using Postgres in the snap as per #1222

**Comment by bnevis-i** [comment]
Additionally, PostgreSQL must also be provided the same password during initialization.  This is done via passing `POSTGRES_PASSWORD` environment variable to the entrypoint script, or `POSTGRES_PASSWORD_FILE` and having the password passed via a file system secret.

I would also like to point out that `POSTGRES_USER` creates a superuser account, which is not an issue when kong is the only database on the server, but would be an issue if one wanted multiple databases on the PostgreSQL instance.  There is no current machinery in the Docker Hub postgres image for creating databases with explicit database owners that are not superusers.

**Comment by anonymouse64** [comment]
updated the issue description to address that

**Comment by hutchic** [comment]
Do you envision this using vault dynamic secrets ( https://www.vaultproject.io/docs/secrets/databases/postgresql.html ).

Just idly curious have no strong opinions

**Comment by anonymouse64** [comment]
That seems like a useful feature within Vault, but I don't know if this will use that or not. 
If it's not a lot of work perhaps folks will go that route, but it seems pretty straight forward to manually do this in the scripts that start things up instead (i.e. `security-secrets-setup` et al).

**Comment by bnevis-i** [comment]
@hutchic It would be great if Kong could delegate to Vault to retrieve its password without the project having to write any glue logic.  This would eliminate the need to manage yet another secret besides the Vault access token.

**Comment by hutchic** [comment]
The foundation for that glue already exists in the form of [consul-template](https://github.com/hashicorp/consul-template) or [env-consul](https://github.com/hashicorp/envconsul). Anything Kong does would be to sidecar or run Kong via one of the above tools

We should probably discuss elsewhere and not scope creep this issue but in theory Vault could handle all datastore validation with dynamic secrets authentication provided via something like keycloak / hsm / plain old tokens

**Comment by bnevis-i** [comment]
Fixed by https://github.com/edgexfoundry/developer-scripts/pull/219 and https://github.com/edgexfoundry/developer-scripts/pull/221 for docker scripts.

**Comment by bnevis-i** [comment]
@anonymouse64  Has this issue been fixed in the snap packaging?

**Comment by anonymouse64** [comment]
No, I'll assign to Tony

**Comment by tonyespy** [comment]
I'll make sure this gets addressed in my forthcoming PR to update kong in the snap.

**Comment by tonyespy** [comment]
I could do the same thing in the snap as is done in docker-compose (ie. set an env override), but then we're basically just hard-coding a password at build time, as there's no way to pass an environment variable to the snap at install time. Just wondering why we didn't use the gokey password generator, or builtin vault generator for this?

The other approach I'm considering for this is to use a password generator (eg. apg) at snap install time to generate the password.

@bnevis-i @anonymouse64 Thoughts?

**Comment by bnevis-i** [comment]
The only processes that need the password that you set here is kong and kong-migrations.  The approach of generating a random password at snap install time and configuring postgres, kong, and kong-migrations with it sounds like a good idea.

**Comment by anonymouse64** [comment]
> The other approach I'm considering for this is to use a password generator (eg. apg) at snap install time to generate the password.

This would be my preference

**Comment by tonyespy** [comment]
Branch pushed: https://github.com/tonyespy/edgex-go/tree/snap-postgres-passwd

**Comment by bnevis-i** [comment]
@tonyespy are you planning to turn the above into an official PR?
