### ISSUE TITLE
Pluggable random database password generation

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1946]
# 🚀 Feature Request

### Relevant Package
Affects security-secretstore-setup.

### Description
An issue was raised in the PR #1916 review regarding the use of GoKey to generate mongodb passwords.  The primary concern centers around the lack of formal vetting of the GoKey library and its usage in a security-sensitive setting.  A secondary concern centers around the difficulty of changing the password generation policy or methodology since the implementation is hard-coded into security-secretstore-setup.

The GoKey library features a policy-based password generator, which was the primary feature driving its adoption.  The implementation, however, is based on an HKDF (HMAC key derivation function) that uses a seed as input to predictably derive pseudo-random passwords.  Thus, only one base password need be kept and shared, and it can be used to derive a tree of passwords based on that root secret that to an outsider appear to be random.  This seems overly complicated given the task is to simply generate random database passwords that will be saved in the secret store.

### Describe the solution you'd like
This feature request proposes that the password generator be made pluggable by calling an external utility in the SMA-executor style.  The external utility will generate a database password in an implementation-defined manner.

To achieve this:

1. Extend the TOML configuration with the following entries
```
[SecretService]
PasswordGenerator (string
PasswordGeneratorArgs ([]string)
PasswordGeneratorContextOption string
```

2. Verify the PasswordGenerator is on the PATH

3. Launch the PasswordGenerator with supplied PasswordGeneratorArgs.  Additionally, pass an additional contextual data such as the name of the database as an additional argument (PasswordGeneratorContextOption) that the password generator could use for password derivation.  (For example, the generator could adopt the GoKey approach.)

4. If the exit code of the utility is zero, the standard output of the tool should be consumed directly as the password.

**Comment by hutchic** [comment]
waiting on security ADR's that are related to it to clear before progressing

**Comment by bnevis-i** [comment]
@hutchic Secrets ADR is merged.  Agree to unblock this?
