### ISSUE TITLE
Consider use unified project folder naming style

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#195]
now the project's folders hava two naming style: 

- no '-' link words in [this dir](https://github.com/edgexfoundry/edgex-go/tree/master/core/clients)
- use '-' link words in [this dir](https://github.com/edgexfoundry/edgex-go/tree/master/support)

I suggest use a unified naming style

cc @jpwhitemn @tsconn23 @drasko

**Comment by tsconn23** [comment]
Closing this issue as its recommendation is being incorporated into PRs going forward, not as a single repo-wide change.
