### ISSUE TITLE
Turning off security-secret-store in the snap doesn't also turn off security-api-gateway

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1963]
# 🐞 Bug Report

### Affected Services

 The issue is located in: the snap packaging, specifically the configure hook

### Is this a regression?
Unclear if it ever worked properly, the logic in the configure hook seems to imply no?

### Description and Minimal Reproduction

```
$ snap get edgexfoundry security-api-gateway
on
$ snap get edgexfoundry security-secret-store
on
$ snap set edgexfoundry security-secret-store=off
$ snap get edgexfoundry security-api-gateway
on
$ snap services edgexfoundry.kong-daemon
Service                   Startup  Current  Notes
edgexfoundry.kong-daemon  enabled  active   -
```

When setting security-secret-store to off, we need to set security-api-gateway off as well, as technically there is a linkage between the two, with the gateway accessing it's tokens from the secret-store. 

There is also the inverse problem where if you try to turn on security-api-gateway, this should turn on security-secret-store if that is off, but does not.

## 🌍  Your Environment
**Deployment Environment:** ubuntu 19.04 desktop

**EdgeX Version:** edge channel of the snap, i.e. master

**Comment by bnevis-i** [comment]
@tonyespy  is this being replanned for Hanoi?

**Comment by tonyespy** [comment]
This should've been closed awhile ago as it was fixed in fuji. The steps to repeat actually only work with the edinburgh snap, as the security-api-gateway config option was removed in fuji.

I've verified that disabling security-secret-store disables Kong, and the associated services with the fuji and geneva (built from lastest master) snaps.
