### ISSUE TITLE
Implement ZeroMQ sender for export distro

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#197]
currently, it's not supported [in here](https://github.com/edgexfoundry/edgex-go/blob/master/export/distro/registrations.go#L82)

cc @drasko

**Comment by jpwhitemn** [comment]
To be determined if additional export connectors are something we do before or after export service relook/refactor.  We need a more plug-in or SDK style of architecture to allow export services to scale to vast numbers of connectors over time - without necessarily bloating the code base when you only need a few connectors in a use case.

**Comment by yanghua** [comment]
Does implement it firstly then transplant it to adapt the new architecture(mode) is a consider idea?
We could let the connector hold into holding repository or a feature branch, no matter implement it now or soon, the main business logic is similar (for example the `Send` method). Just a opinion, follow your plan.

**Comment by jpwhitemn** [comment]
Yes - this a duplicate to #102.  Annotating and closing as such.  For what it is worth, we did decide at latest F2F to design new application services for Delhi with implementation scheduled for Edinburgh release.  Whether we add ZeroMQ into current export services (or only do as part of application services) would depend on needs and availability of resources.
