### ISSUE TITLE
update snap README.md with "better" docs links

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1971]
The snap README.md has links like https://docs.snapcraft.io/t/installing-snapd/6735 which were temporary at the time README.md was written, when the real link that should be used going forward is https://snapcraft.io/docs/installing-snapd

Update all such links here to the new form

**Comment by tonyespy** [comment]
Just pushed a branch for this, PR coming soon:

https://github.com/tonyespy/edgex-go/tree/snap-readme-docs-update
