### ISSUE TITLE
security-secretstore-setup should ensure the path exists before creating token file

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/edgex-go#1976]
# 🐞 Bug Report

### Affected Services

 The issue is located in: security-secretstore-setup

### Description and Minimal Reproduction

security-secretstore-setup can run into an issue creating the token file if the token path doesn't exist.  We should ensure this path exists before continuing.

**Comment by michaelestrin** [comment]
Solved by https://github.com/edgexfoundry/developer-scripts/pull/153
