### ISSUE TITLE
Standard project layout

### ISSUE THREAD

**Issue by falkerson** [edgexfoundry/edgex-go#198]
It's a good practice to have some standard project layout for go projects. With current approach all services stored in a root of project directory which could provide mess with time. Propose to take a look https://github.com/golang-standards/project-layout.

**Comment by yanghua** [comment]
+1, looks good to me cc @drasko what's your opinion?

**Comment by drasko** [comment]
My opinion is that premature optimization is the root of all evil.

**Comment by jpwhitemn** [comment]
@tsconn23 - Trevor, please have a look at the above standard project layout.  How does this line up with our core service refactors?  Along with Drasko, I don't want to re-org if it does not offer some compelling assistance/improvements.  We need to understand how pervasive is this "standard" and is it adopted by many go projects and if it seems to fit/meet our needs.  If not, we need to close this issue.  If so, we need to prioritize for work in Delhi.

**Comment by yanghua** [comment]
@drasko seems it is not a optimization (mostly not change the code), it's refactor about the project's structure. Also we should consider whether the 'standard' is a popular convention or not just like jim said.

**Comment by falkerson** [comment]
@drasko @jpwhitemn it's not only about standard in that link. Project should have some well known layout. So it will be easy for every new contributor look through project structure and find interesting part. Example: for me as some new person without onboarding it was little not obviously to understand that directories in root related to services. If we won't such layout we need document somehow that structure

**Comment by tsconn23** [comment]
FYI, I have a need when addressing Issue #182 whereby it would be useful to have the /internal directory with our current /pkg moved inside of that. The packages in /pkg are not intended for external use and so will be moved to /internal/pkg. See the following:
https://github.com/golang-standards/project-layout/tree/master/internal

Will be submitting PR shortly.

**Comment by tsconn23** [comment]
Closing this issue as it isn't a specific actionable item, but has informed several PRs since its creation and will be taken under advisement during Delhi refactoring efforts.
