### ISSUE TITLE
export service connects to the mqtt service auth  fail

### ISSUE THREAD

**Issue by 7040210** [edgexfoundry/edgex-go#1980]
# 🚀 Feature Request

### Description
When the export service connects to the mqtt service, the addressable.publisher is used as the ClientID, which may cause authentication failure on some cloud platforms. It is recommended that the ClientID be configured by the user in the configuration file.

### Describe the solution you'd like
> /api/v1/registration 
```
"addressable": {
		"name": "XXX",
		"protocol": "XXX",
		"method": "XXX",
		"address": "XXX",
		"port": 1883,
		"path": "",
		"publisher": "XXX",
		"user": "XXX",
		"password": "XXX",
		"topic": "XXX",
		"clientid":"Add new configuration "
	}
```

**Comment by michaelestrin** [comment]
Closed.  Export services are deprecated and will be removed from the Geneva release.
