### ISSUE TITLE
Edgex-proxy failed to retrieve CA certificate when insecureSkipVerify set to false

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-go#1984]
# 🐞 Bug Report

### Affected Services

  
 The issue is located in:  
  **edgex-security-proxy-setup** 

One can see the x509 certificate error.  Issue exists when the switch or flag `insecureSkipVefiry` set to **false**.  No issue is observed when that flag is set to true.

### Is this a regression?

 

No, when the flag of  ```insecureSkipVerify``` is false, it appears to have this issue already. 

### Description and Minimal Reproduction
The TLS transport layer requires CA certificate to be present when the communication between proxy and the vault starts in order to retrieve the certificate for Kong.  Because the current mechanism on the requestor is missing the loading of CA certificate into http TLS layer, the `x509: certificate signed by unknown authority` error will surface when the `insecureSkipVerify` flag is off or false. 

To reproduce, 
 1. one can set the insecureSkipVerify=false on the edgex-security-proxy-setup service in the docker-compose file indicating here:
https://github.com/edgexfoundry/developer-scripts/blob/7d7f885b77450c78d4f2c1640c88d406175141f2/releases/nightly-build/compose-files/docker-compose-nexus.yml#L204

Change "true" to "false like
```yaml
command: ["--init=true", "--insecureSkipVerify=false"]
```
2. Save the file
3. Run docker-compose up 
4. In the docker log of the `security-proxy-setup`, one can see the error:

```
level=ERROR ts=2019-10-23T23:33:45.941083418Z app=edgex-security-proxy-setup source=certs.go:96 msg="failed to retrieve certificate on path v1/secret/edgex/pki/tls/edgex-kong with error Get https://edgex-vault:8200/v1/secret/edgex/pki/tls/edgex-kong: x509: certificate signed by unknown authority"
level=ERROR ts=2019-10-23T23:33:45.945461964Z app=edgex-security-proxy-setup source=main.go:86 msg="Get https://edgex-vault:8200/v1/secret/edgex/pki/tls/edgex-kong: x509: certificate signed by unknown authority"
```

## 🔥 Exception or Error
<pre>failed to retrieve certificate on path v1/secret/edgex/pki/tls/edgex-kong with error Get https://edgex-vault:8200/v1/secret/edgex/pki/tls/edgex-kong: x509: certificate signed by unknown authority<code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Linux Docker compose up

**EdgeX Version:**
1.1.0 of nightly docker compose

**Anything else relevant?**
N/A

**Comment by anonymouse64** [comment]
Note that the reproducing instructions are incomplete here, you need to remove the `--insecureSkipVerify` option specified in the command in the docker-compose:

https://github.com/edgexfoundry/developer-scripts/blob/7d7f885b77450c78d4f2c1640c88d406175141f2/releases/nightly-build/compose-files/docker-compose-nexus.yml#L204

@jim-wang-intel can you provide complete instructions on how you reproduced this issue?

**Comment by anonymouse64** [comment]
Well I was able to verify your PR with just removing the --insecureSkipVerify option from that container, but for future reference it's useful to provide a full patch of what a reviewer needs to apply to their tree in order to test something.

**Comment by jim-wang-intel** [comment]
> 
> 
> Note that the reproducing instructions are incomplete here, you need to remove the `--insecureSkipVerify` option specified in the command in the docker-compose:
> 
> https://github.com/edgexfoundry/developer-scripts/blob/7d7f885b77450c78d4f2c1640c88d406175141f2/releases/nightly-build/compose-files/docker-
compose-nexus.yml#L204
> 

or set that flag to false ie `--insecureSkipVerify=false`

> @jim-wang-intel can you provide complete instructions on how you reproduced this issue? (i.e. did you change anything else in the docker-compose.yml file)

updated the above description

**Comment by anonymouse64** [comment]
Thanks

**Comment by jim-wang-intel** [comment]
Close #1984 via #1985
