### ISSUE TITLE
logTarget cannot be blank error occurs when each service starts up

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#1988]
# 🐞 Bug Report

### Affected Services
The issue is located in: the latest images (fuji)

### Is this a regression?

Yes, the previous version in which this bug was not present was: Edinburgh images

### Description and Minimal Reproduction
Use the docker-compose file in developer-script and start EdgeX by
`docker-compose up -d`
See the log in each service, such as
docker logs edgex-core-datadocker logs edgex-core-data

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by michaelestrin** [comment]
Closing.  Duplicate of https://github.com/edgexfoundry/edgex-go/issues/1989.

**Comment by cloudxxx8** [comment]
sorry, I am not sure why I opened this issue twice @@
