### ISSUE TITLE
logTarget cannot be blank error occurs when each service starts up

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#1989]
# 🐞 Bug Report

### Affected Services
The issue is located in: each service in edgex-go repository

### Is this a regression?

Yes, the previous version in which this bug was not present was: Edinburgh (v1.0.1)

### Description and Minimal Reproduction

Use the docker-compose file in developer-script and start EdgeX by
`docker-compose up -d`
Then, see the logs in each service:
```
docker logs edgex-core-data
docker logs edgex-core-metadata
docker logs edgex-support-logging
```

## 🔥 Exception or Error
<pre><code>
You will see the following error logs:
level=ERROR ts=2019-10-24T05:44:35.969925173Z app=edgex-core-metadata source=logger.go:105 msg="logTarget cannot be blank, using stdout only"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 18.04

**EdgeX Version:**
fuji (master branch)

**Anything else relevant?**

**Comment by michaelestrin** [comment]
Known issue.

Bootstrap creates logger with empty logTarget [here](https://github.com/edgexfoundry/edgex-go/blob/f4204656cd259c9ac09dc185824708a797839447/internal/pkg/bootstrap/logging/factory.go#L27).  This happens before configuration is loaded and is done to provide a consistent logging interface.  The error is harmless but should not be logged.  Error occurs [here](https://github.com/edgexfoundry/go-mod-core-contracts/blob/2893c077e808ed15b71fa93d8ae4bcb38d031ecf/clients/logger/logger.go#L105).

Fix is to add a second factory function in go-mod-core-contracts that does not take a logTarget. It should execute all of the same logic (preferably without duplicating it) that the existing NewClient method executes except for the if..then that logs the error when logTarget == "".

Once this change is merged, edgex-go should be modified to use the updated go-mod-core-contracts and the FactoryToStdout function in the bootstrap should be modified to call it.
