### ISSUE TITLE
core-command coupled to core-metadata database

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1990]
Core-command leverages command collection in core-metadata's database to satisfy queries.  See https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/command/interfaces/db.go.

New security implementation (and canonical micro service design principles) assume each service has its own persistence implementation.

Core-command's usage of core-metadata's database should be eliminated and the two services decoupled from one another.

**Comment by michaelestrin** [comment]
Found while troubleshooting security variations of Jenkins blackbox build for https://github.com/edgexfoundry/blackbox-testing/issues/282

**Comment by bnevis-i** [comment]
Reviewed in today's Security WG.  Noted that this issue is currently flagged as Geneva committed item but lacks an assignee.

**Comment by michaelestrin** [comment]
Do the security folks think this needs to be addressed for Geneva?

@jim-wang-intel @bnevis-i @tingyuz @mkbhanda

**Comment by bnevis-i** [comment]
I think there are bigger holes than this that we can address first.  I'm OK with deprioritizing it.

**Comment by tingyuz** [comment]
Had a brief discussion with @bnevis-i @mkbhanda in security group and we feel it is not in the top priority list currently. There are more important issues to be handled. As Bryon mentioned here is the list (not complete) we may be focusing on in the future: 
- Lots of containers running around running as root or with r/w file systems
- RedisDB doesn't have a password, Postgres uses a fixed password seeded in the docker-compose.
- No network segmentation
- No microservice identity, authentication, or authorization of API requests
- No integrity or confidentiality protection of API requests
- The destination of requests is controlled by a service that has the above faults
- Kong proxy is all-or-nothing access
- Project-provided docker compose exposes sensitive ports on the host (edited) 

That being said, it is recommended not to put this into the Geneva scope. We may review it after the design of security enhancement for Hanoi is getting into the place.

**Comment by tsconn23** [comment]
Putting on hold pending Hanoi discussions around possible collapsing of Command/Metadata into one Core service.

**Comment by cloudxxx8** [comment]
fixed in v2
