### ISSUE TITLE
System Management STOP operation fails for two or more services

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2010]
In the current implementation and using the default Docker executor, not all of the requested services are stopped when system management is asked to stop all of the core services in a single request.

May be solved by https://github.com/edgexfoundry/edgex-go/issues/2009

**Comment by akramtexas** [comment]
- Relevant, related issue: [Issue-272](https://github.com/edgexfoundry/blackbox-testing/issues/272)
- Relevant, related PR: [PR277](https://github.com/edgexfoundry/blackbox-testing/pull/277)
- In addition to the reference each above (to blackbox test issue and related PR), this is to note that I have commented-out an individual (`system-management`) blackbox test, and that it will need to be uncommented and pass as part of the issue.

**Comment by michaelestrin** [comment]
Believe this is addressed by #2009

**Comment by michaelestrin** [comment]
@akramtexas please review and verify this issue has been resolved.

**Comment by akramtexas** [comment]
@michaelestrin 
- I have verified that this is no longer an issue.
- To test: Used docker-compose to bring up latest. docker-compose stop system. Run system management agent locally. Send request to operations endpoint for at least three services (example below). 
- Sample request:
```
POST http://localhost:48090/api/v1/operation
Accept: */*
Cache-Control: no-cache
{ "action": "stop", "services": ["edgex-core-data","edgex-core-metadata","edgex-core-command"] }

```- Ensured that the operation is a success, i.e. result is returned (which happens to be within 2-3 seconds).
