### ISSUE TITLE
Alerts & Notification is unable to send emails

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2011]
# 🐞 Bug Report

### Affected Services

 The issue is located in: edgex-support-notifications

### Description and Minimal Reproduction
**post subscription** 
{
	"slug": "group-test-member",
	"receiver": "Group Test",
	"subscribedCategories": [ "HW_HEALTH" ],
	"subscribedLabels": [ "temperature", "humidity" ],
	"channels": [ {"type": "EMAIL", "mailAddresses": ["abc@gmail.com"]} ]
}

**post notification**

{
	"slug": "notice-test-001",
	"sender": "System Management",
	"category": "HW_HEALTH",
	"severity": "NORMAL",
	"content": "Hello, Notification!",
	"labels": [ "cool", "test" ]
}

## 🔥 Exception or Error

It updated the notification status(=PROCESSED), but didn't generate transmission records.

```
level=INFO ts=2019-10-25T07:09:31.9433481Z app=edgex-support-notification source=rest_notification.go:55 msg="Critical severity scheduler is triggered for: notice-test-001"
level=DEBUG ts=2019-10-25T07:09:31.944443Z app=edgex-support-notification source=distribution_coordinator.go:23 msg="DistributionCoordinator start distributing notification: notice-test-001"
level=INFO ts=2019-10-25T07:09:31.9451903Z app=edgex-support-notification source=rest_notification.go:67 msg="Critical severity scheduler has completed for: notice-test-001"
```

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:** 
Edinburgh 1.0.1

**Anything else relevant?**

**Comment by AnthonyMBonafide** [comment]
@jinlinGuan , Do you have any additional logs, or any possible steps for reproduction for this bug? I am not able to replicate this issue nor am I am to see any logical issues in the code. Can you also provide environment information such as ARM vs x86, what email service you are using to deliver the email, configuration properties for `support-notififcations`, and any other relevant information that can help pin-point a root-cause?

**Comment by AnthonyMBonafide** [comment]
I apologize, I was testing this against the `Fuji` release rather than `Edinburgh 1.0.1`. I will attempt to reproduce and fix under the correct version. My apologises.

**Comment by jinlinGuan** [comment]
It works in Fuji. It didn't generate transmission records is because the subscribedLabels in subscription and labels in notification didn't match.

**Comment by michaelestrin** [comment]
@jinlinGuan Is this an active issue/problem with Edinburgh?
