### ISSUE TITLE
Refactor core-command and apply errorConcepts

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/edgex-go#2012]
# 🚀 Feature Request

### Relevant Package

- core-command

### Description

In #1860, work was attempted to apply errorConcepts to core-command. It was realized during the course of that work (see comments on #1972) that core-command, as written, does error checking in too many places and has a large body of code with a very different style and flow to the other microservices. To this end, this issue attempts to capture two work items:

- Refactor core-command to bring its structure and flow in line with the patterns established by core-data and core-metadata
- During that refactor, ensure that errors are processed and handled centrally so that the errorConcepts pattern can be used and error handling can be more readily modified in the future.
- This is a good opportunity to write unit tests.

**Comment by michaelestrin** [comment]
Recommend you don't apply the operator pattern here.  Related issues are being created to remove the global variables from each core service which will obviate the need to use the existing operator pattern.

**Comment by michaelestrin** [comment]
During a conversation, @brandonforster decided to make this work dependent upon the completion of https://github.com/edgexfoundry/edgex-go/issues/2017.
