### ISSUE TITLE
Brightics IoT export connector

### ISSUE THREAD

**Issue by hyogrin** [edgexfoundry/edgex-go#202]
We would like to implement another export-distro which will allow EdgeX to export device data (via export distro) to Brightics IoT which is an B2B targeted enterprise IoT platform. Since Brightics IoT supports MQTT protocols, we will contribute another Brightics IoT-MQTT-export-distro in Go so that our platform users allow to collect device data via EdgeX device services. The target release version would be delhi.

 

* For your information, we have been developing an enterprise IoT platform named "Brightics IoT" for about 3years. (https://www.samsungsds.com/global/en/solutions/off/insa/brighticsIoT.html) The reason why we decide to participate EdgeX poject is that we want to extend platform capabilities via device services of EdgeX.
[1525864011977_Brightics IoT Briefing (EdgeX)_20180509.pdf](https://github.com/edgexfoundry/edgex-go/files/1987555/1525864011977_Brightics.IoT.Briefing.EdgeX._20180509.pdf)

**Comment by hyogrin** [comment]
Please feel free to add any comments we are going to implement the export-distro starting next week.

**Comment by hyogrin** [comment]
We will start the work from next month(Because of the another biz trip). Let's keep in touch on the rocketchat to talk about technical issues and share the architecture / design documents.

**Comment by jduranf** [comment]
@hyogrin still working in this issue or we can close it?

**Comment by hyogrin** [comment]
I have been testing some of test cases right now but it is ok. you can close it.

**Comment by hyogrin** [comment]
@jduranf Still need some time. I have been testing some testcases right now. Would you give me a couple of weeks?

**Comment by jduranf** [comment]
@hyogrin sure, I just want to know if this issue is still alive or not

**Comment by jduranf** [comment]
Done via #565
