### ISSUE TITLE
Core services do not have an attribution file

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#204]
License and Attribution files are necessary to satisfying licensing agreements. The Attribution.txt is missing from core-command, core-data, core-metadata. DevOps is working on way to automate the inclusion of these files in deployment artifacts like Docker images.

**Comment by yanghua** [comment]
@tsconn23 can you assign this issue to me? Or you are fixing it?

**Comment by tsconn23** [comment]
@yanghua That's fine if you'd like to submit a PR for this. It should be pretty simple. Look in the old, separate repos for the Go services. The Attribution.txt files should be there. For example:

https://github.com/edgexfoundry/core-command-go/blob/master/Attribution.txt

We'd need to do a quick audit to be sure they're still current and then put each one in its respective cmd directory. So the one shown above would go into edgex-go/cmd/core-command.

**Comment by yanghua** [comment]
claim it~
