### ISSUE TITLE
Create common Docker base images

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#2047]
# 🚀 Feature Request

### Relevant Package
All core-services

### Description
The Dockerfiles for each of the core-services are similar enough where we can leverage Dockers image layering to reduce the time to build images, and make it easier to make updates. For example, we can have an image which builds off of `golang:1.12-alpine` which does some of the common setup like:

https://github.com/edgexfoundry/edgex-go/blob/4333c146e54e914d1b50db61a2e9368113cae9e2/cmd/core-metadata/Dockerfile#L9-L26

We can then use that image as a base for our Dockerfiles. There is more that can be done in the base image that is common between all the services. There might even be reason to create multiple images which have additional features that are only needed by some services like ZeroMQ. Following this pattern makes the docker images more maintainable. If we were to change our messaging system we would only have to update the layer which installs the necessary binaries for ZeroMQ rather than changing multiple Dockerfiles.

### Describe the solution you'd like

- One or more Docker images created which handle common functionality needed by the core-services.

- Image layering used in the Dockerfiles used to create Docker images for the core-services 

### Describe alternatives you've considered
I thought about incorporating Docker compose so that developers can easily create and run the core-services in docker containers. This might be adding too much work, but would be nice if we can leverage image layering, have simplified Dockerfiles, and a simple Docker compose file for development and possibly CI jobs

**Comment by michaelestrin** [comment]
May be related to changes suggested here https://github.com/edgexfoundry/developer-scripts/pull/155#issuecomment-545462164 (for issue https://github.com/edgexfoundry/developer-scripts/issues/154).
