### ISSUE TITLE
security-secrets-setup says it succeeded when it also says it fails (and it did fail)

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#2048]
# 🐞 Bug Report

### Affected Services

 The issue is located in: security-secrets-setup

### Is this a regression?
maybe?

### Description and Minimal Reproduction

clone fuji branch of edgex-go

```
$ ./cmd/security-secrets-setup/security-secrets-setup -confdir ./cmd/security-secrets-setup/res generate
level=ERROR ts=2019-10-31T15:16:32.496926328Z app=edgex-security-secrets-setup source=logger.go:73 msg="logTarget cannot be blank, using stdout only"
level=ERROR ts=2019-10-31T15:16:32.497171655Z app=edgex-security-secrets-setup source=main.go:124 msg="CertConfigDir from config file does not exist in: ./res"
level=INFO ts=2019-10-31T15:16:32.507093231Z app=edgex-security-secrets-setup source=main.go:128 duration=10.184285ms msg="security-secrets-setup complete"
```

note that the referenced files from cmd/security-secrets-setup/res/configuration.toml in the git tree don't actually exist when run from a different directory, so this is expected to fail, however we shouldn't have the last message in the log above where it says security-secrets-setup is complete because it didn't complete, it failed

## 🌍  Your Environment
**Deployment Environment:** 

**EdgeX Version:** fuji @ dd2af2191e85b0217a30ea176a345c30e0df5ac9

**Comment by michaelestrin** [comment]
> however we shouldn't have the last message in the log above where it says security-secrets-setup is complete because it didn't complete, it failed

I think the intent of the message is to indicate the application (known as security-secrets-setup) execution is complete and not that it completed successfully.  What, if anything, would @anonymouse64 propose for alternate wording?

**Comment by anonymouse64** [comment]
> is to indicate the application (known as security-secrets-setup) execution is complete and not that it completed successfully

But why do we need a message saying that execution is complete? I would just propose that in the error case we don't have this message since it's misleading. It could perhaps be reworded to say something silly like "done executing k thx bai" but I don't see the need for such a message, especially considering that anything needing to monitor the execution status of security-secrets-setup should be using Consul and not searching through log messages. 

Additionally, I would be confused if security-secrets-setup did something else after it failed to load CertConfigDir, so it seems the error message about not loading stuff from CertConfigDir seems sufficient information for me to tell that the execution is done

**Comment by michaelestrin** [comment]
> But why do we need a message saying that execution is complete?

It's there because someone (not me) put it there.  I'm not advocating that it is needed.  Just attempting to understand what you would expect as an alternative.

It sounds to me like the simple fix is to remove the message altogether.  Do you (@anonymouse64) concur?

**Comment by anonymouse64** [comment]
yes removing it is what I would expect, thanks
