### ISSUE TITLE
Drop attribution lines from core service files

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#205]
We will be dropping the attributions lines (example below) from the source files comprising the core services. These aren't maintained and just clutter things up. We have GitHub history for changes.

Example:
 * @microservice: core-clients-go library
 * @original author: Ryan Comer, Dell
 * @version: 0.5.0
 * updated for Kei Ohmura.  Kei made the original contribution in the core-clients-go repo
 * fix - moves `decodeValueDescriptorSlice()` method to the ValueDescriptorClient.
 * added - methods to the ValueDescriptorClient

**Comment by yanghua** [comment]
@tsconn23 Are you doing this work?

**Comment by tsconn23** [comment]
@yanghua If you'd like to submit a PR for it, please do.

**Comment by yanghua** [comment]
@tsconn23 ok, claim it~
