### ISSUE TITLE
Investigate Rules Engine BB Test Failures

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2056]
Investigate/address failures.  From last night's blackbox test run:

> 08:04:22 support-rulesengine
> 08:04:22 
> 08:04:22 ❏ rules
> 08:04:22 ↳ Create a rule
> 08:04:22   POST http://edgex-support-rulesengine:48075/api/v1/rule [errored]
> 08:04:22      getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075
> 08:04:22   2. Status code is 200
> 08:04:22   3. Content-Type is present
> 08:04:22   4. Response body is correct
> 08:04:22 
> 08:04:22 ↳ Create a rule
> 08:04:23   POST http://edgex-support-rulesengine:48075/api/v1/rule [errored]
> 08:04:23      getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075
> 08:04:23   6. Status code is 200
> 08:04:23   7. Response time is less than 5000ms
> 08:04:23   8. Content-Type is present
> 08:04:23   9. Response body is correct
> 08:04:23 
> 08:04:23 ↳ List all rule
> 08:04:23   GET http://edgex-support-rulesengine:48075/api/v1/rule [errored]
> 08:04:23      getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075
> 08:04:23  11⠄ JSONError in test-script
> 08:04:23 
> 08:04:23 ↳ Delete rule by name
> 08:04:23   DELETE http://edgex-support-rulesengine:48075/api/v1/rule/name/motortoofastsignal [errored]
> 08:04:23      getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075
> 08:04:23  13. Status code is 200
> 08:04:23  14. Response time is less than 800ms
> 08:04:23  15. Content-Type is present
> 08:04:23  16. Response body is correct
> 08:04:23 
> 08:04:23 ┌─────────────────────────┬──────────┬──────────┐
> 08:04:23 │                         │ executed │   failed │
> 08:04:23 ├─────────────────────────┼──────────┼──────────┤
> 08:04:23 │              iterations │        1 │        0 │
> 08:04:23 ├─────────────────────────┼──────────┼──────────┤
> 08:04:23 │                requests │        4 │        4 │
> 08:04:23 ├─────────────────────────┼──────────┼──────────┤
> 08:04:23 │            test-scripts │        8 │        1 │
> 08:04:23 ├─────────────────────────┼──────────┼──────────┤
> 08:04:23 │      prerequest-scripts │        5 │        0 │
> 08:04:23 ├─────────────────────────┼──────────┼──────────┤
> 08:04:23 │              assertions │       11 │       11 │
> 08:04:23 ├─────────────────────────┴──────────┴──────────┤
> 08:04:23 │ total run duration: 375ms                     │
> 08:04:23 ├───────────────────────────────────────────────┤
> 08:04:23 │ total data received: 0B (approx)              │
> 08:04:23 └───────────────────────────────────────────────┘
> 08:04:23 
> 08:04:23    #  failure         detail                                                                                               
> 08:04:23                                                                                                                            
> 08:04:23  01.  Error                                                                                                                
> 08:04:23                       getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075                      
> 08:04:23                       at request                                                                                           
> 08:04:23                       inside "rules / Create a rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  02.  AssertionError  Status code is 200                                                                                   
> 08:04:23                       expected { Object (id, _details, ...) } to have property 'code'                                      
> 08:04:23                       at assertion:0 in test-script                                                                        
> 08:04:23                       inside "rules / Create a rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  03.  AssertionError  Content-Type is present                                                                              
> 08:04:23                       expected response to have header with key 'Content-Type'                                             
> 08:04:23                       at assertion:1 in test-script                                                                        
> 08:04:23                       inside "rules / Create a rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  04.  AssertionError  Response body is correct                                                                             
> 08:04:23                       object tested must be an array, a map, an object, a set, a string, or a weakset, but undefined given 
> 08:04:23                       at assertion:2 in test-script                                                                        
> 08:04:23                       inside "rules / Create a rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  05.  Error                                                                                                                
> 08:04:23                       getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075                      
> 08:04:23                       at request                                                                                           
> 08:04:23                       inside "rules / Create a rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  06.  AssertionError  Status code is 200                                                                                   
> 08:04:23                       expected { Object (id, _details, ...) } to have property 'code'                                      
> 08:04:23                       at assertion:0 in test-script                                                                        
> 08:04:23                       inside "rules / Create a rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  07.  AssertionError  Response time is less than 5000ms                                                                    
> 08:04:23                       expected undefined to be a number or a date                                                          
> 08:04:23                       at assertion:1 in test-script                                                                        
> 08:04:23                       inside "rules / Create a rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  08.  AssertionError  Content-Type is present                                                                              
> 08:04:23                       expected response to have header with key 'Content-Type'                                             
> 08:04:23                       at assertion:2 in test-script                                                                        
> 08:04:23                       inside "rules / Create a rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  09.  AssertionError  Response body is correct                                                                             
> 08:04:23                       object tested must be an array, a map, an object, a set, a string, or a weakset, but undefined given 
> 08:04:23                       at assertion:3 in test-script                                                                        
> 08:04:23                       inside "rules / Create a rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  10.  Error                                                                                                                
> 08:04:23                       getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075                      
> 08:04:23                       at request                                                                                           
> 08:04:23                       inside "rules / List all rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  11.  JSONError                                                                                                            
> 08:04:23                       Unexpected token u in JSON at position 0                                                             
> 08:04:23                       at test-script                                                                                       
> 08:04:23                       inside "rules / List all rule"                                                                       
> 08:04:23                                                                                                                            
> 08:04:23  12.  Error                                                                                                                
> 08:04:23                       getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075                      
> 08:04:23                       at request                                                                                           
> 08:04:23                       inside "rules / Delete rule by name"                                                                 
> 08:04:23                                                                                                                            
> 08:04:23  13.  AssertionError  Status code is 200                                                                                   
> 08:04:23                       expected { Object (id, _details, ...) } to have property 'code'                                      
> 08:04:23                       at assertion:0 in test-script                                                                        
> 08:04:23                       inside "rules / Delete rule by name"                                                                 
> 08:04:23                                                                                                                            
> 08:04:23  14.  AssertionError  Response time is less than 800ms                                                                     
> 08:04:23                       expected undefined to be a number or a date                                                          
> 08:04:23                       at assertion:1 in test-script                                                                        
> 08:04:23                       inside "rules / Delete rule by name"                                                                 
> 08:04:23                                                                                                                            
> 08:04:23  15.  AssertionError  Content-Type is present                                                                              
> 08:04:23                       expected response to have header with key 'Content-Type'                                             
> 08:04:23                       at assertion:2 in test-script                                                                        
> 08:04:23                       inside "rules / Delete rule by name"                                                                 
> 08:04:23                                                                                                                            
> 08:04:23  16.  AssertionError  Response body is correct                                                                             
> 08:04:23                       object tested must be an array, a map, an object, a set, a string, or a weakset, but undefined given 
> 08:04:23                       at assertion:3 in test-script                                                                        
> 08:04:23                       inside "rules / Delete rule by name"                                                                 
> 08:04:24 The SECURITY_IS_ON variable is not set. Defaulting to a blank string.
> 08:04:26 newman
> 08:04:26 
> 08:04:26 support-rulesengine
> 08:04:26 
> 08:04:26 ❏ rules_error_5xx
> 08:04:26 ↳ Fail to create a rule
> 08:04:26   POST http://edgex-support-rulesengine:48075/api/v1/rule [errored]
> 08:04:26      getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075
> 08:04:26   2. Status code is 503
> 08:04:26   3. Response time is less than 800ms
> 08:04:26   4. Content-Type is present
> 08:04:26   5. Content-Type is text/plain
> 08:04:26 
> 08:04:26 ┌─────────────────────────┬──────────┬──────────┐
> 08:04:26 │                         │ executed │   failed │
> 08:04:26 ├─────────────────────────┼──────────┼──────────┤
> 08:04:26 │              iterations │        1 │        0 │
> 08:04:26 ├─────────────────────────┼──────────┼──────────┤
> 08:04:26 │                requests │        1 │        1 │
> 08:04:26 ├─────────────────────────┼──────────┼──────────┤
> 08:04:26 │            test-scripts │        3 │        0 │
> 08:04:26 ├─────────────────────────┼──────────┼──────────┤
> 08:04:26 │      prerequest-scripts │        2 │        0 │
> 08:04:26 ├─────────────────────────┼──────────┼──────────┤
> 08:04:26 │              assertions │        4 │        4 │
> 08:04:26 ├─────────────────────────┴──────────┴──────────┤
> 08:04:26 │ total run duration: 203ms                     │
> 08:04:26 ├───────────────────────────────────────────────┤
> 08:04:26 │ total data received: 0B (approx)              │
> 08:04:26 └───────────────────────────────────────────────┘
> 08:04:26 
> 08:04:26   #  failure         detail                                                                                               
> 08:04:26                                                                                                                           
> 08:04:26  1.  Error                                                                                                                
> 08:04:26                      getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075                      
> 08:04:26                      at request                                                                                           
> 08:04:26                      inside "rules_error_5xx / Fail to create a rule"                                                     
> 08:04:26                                                                                                                           
> 08:04:26  2.  AssertionError  Status code is 503                                                                                   
> 08:04:26                      expected { Object (id, _details, ...) } to have property 'code'                                      
> 08:04:26                      at assertion:0 in test-script                                                                        
> 08:04:26                      inside "rules_error_5xx / Fail to create a rule"                                                     
> 08:04:26                                                                                                                           
> 08:04:26  3.  AssertionError  Response time is less than 800ms                                                                     
> 08:04:26                      expected undefined to be a number or a date                                                          
> 08:04:26                      at assertion:1 in test-script                                                                        
> 08:04:26                      inside "rules_error_5xx / Fail to create a rule"                                                     
> 08:04:26                                                                                                                           
> 08:04:26  4.  AssertionError  Content-Type is present                                                                              
> 08:04:26                      expected response to have header with key 'Content-Type'                                             
> 08:04:26                      at assertion:2 in test-script                                                                        
> 08:04:26                      inside "rules_error_5xx / Fail to create a rule"                                                     
> 08:04:26                                                                                                                           
> 08:04:26  5.  AssertionError  Content-Type is text/plain                                                                           
> 08:04:26                      object tested must be an array, a map, an object, a set, a string, or a weakset, but undefined given 
> 08:04:26                      at assertion:3 in test-script                                                                        
> 08:04:26                      inside "rules_error_5xx / Fail to create a rule"                                                     
> 08:04:27 The SECURITY_IS_ON variable is not set. Defaulting to a blank string.
> 08:04:30 newman
> 08:04:30 
> 08:04:30 support-rulesengine
> 08:04:30 
> 08:04:30 ❏ ping
> 08:04:30 ↳ Test service providing an indication that the service is available.
> 08:04:30   GET http://edgex-support-rulesengine:48075/api/v1/ping [errored]
> 08:04:30      getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075
> 08:04:30   2. Status code is 200
> 08:04:30   3. Response time is less than 800ms
> 08:04:30   4. Content-Type is present
> 08:04:30   5. Response body is correct
> 08:04:30 
> 08:04:30 ┌─────────────────────────┬──────────┬──────────┐
> 08:04:30 │                         │ executed │   failed │
> 08:04:30 ├─────────────────────────┼──────────┼──────────┤
> 08:04:30 │              iterations │        1 │        0 │
> 08:04:30 ├─────────────────────────┼──────────┼──────────┤
> 08:04:30 │                requests │        1 │        1 │
> 08:04:30 ├─────────────────────────┼──────────┼──────────┤
> 08:04:30 │            test-scripts │        2 │        0 │
> 08:04:30 ├─────────────────────────┼──────────┼──────────┤
> 08:04:30 │      prerequest-scripts │        1 │        0 │
> 08:04:30 ├─────────────────────────┼──────────┼──────────┤
> 08:04:30 │              assertions │        4 │        4 │
> 08:04:30 ├─────────────────────────┴──────────┴──────────┤
> 08:04:30 │ total run duration: 175ms                     │
> 08:04:30 ├───────────────────────────────────────────────┤
> 08:04:30 │ total data received: 0B (approx)              │
> 08:04:30 └───────────────────────────────────────────────┘
> 08:04:30 
> 08:04:30   #  failure         detail                                                                                               
> 08:04:30                                                                                                                           
> 08:04:30  1.  Error                                                                                                                
> 08:04:30                      getaddrinfo ENOTFOUND edgex-support-rulesengine edgex-support-rulesengine:48075                      
> 08:04:30                      at request                                                                                           
> 08:04:30                      inside "ping / Test service providing an indication that the service is available."                  
> 08:04:30                                                                                                                           
> 08:04:30  2.  AssertionError  Status code is 200                                                                                   
> 08:04:30                      expected { Object (id, _details, ...) } to have property 'code'                                      
> 08:04:30                      at assertion:0 in test-script                                                                        
> 08:04:30                      inside "ping / Test service providing an indication that the service is available."                  
> 08:04:30                                                                                                                           
> 08:04:30  3.  AssertionError  Response time is less than 800ms                                                                     
> 08:04:30                      expected undefined to be a number or a date                                                          
> 08:04:30                      at assertion:1 in test-script                                                                        
> 08:04:30                      inside "ping / Test service providing an indication that the service is available."                  
> 08:04:30                                                                                                                           
> 08:04:30  4.  AssertionError  Content-Type is present                                                                              
> 08:04:30                      expected response to have header with key 'Content-Type'                                             
> 08:04:30                      at assertion:2 in test-script                                                                        
> 08:04:30                      inside "ping / Test service providing an indication that the service is available."                  
> 08:04:30                                                                                                                           
> 08:04:30  5.  AssertionError  Response body is correct                                                                             
> 08:04:30                      object tested must be an array, a map, an object, a set, a string, or a weakset, but undefined given 
> 08:04:30                      at assertion:3 in test-script                                                                        
> 08:04:30                      inside "ping / Test service providing an indication that the service is available."                  
> 08:04:30 Info:Rulesengine Test Completed.

**Comment by cherrycl** [comment]
The rules-engines container didn't start while running the related test cases.
The rules-engines log contains the below error.

> [2019-11-04 12:06:48.672] boot - 6 ERROR [main] --- ZeroMQEventSubscriber: Unable to get a ZMQ subscriber.  Error:  org.zeromq.ZMQException: edgex-app-service-configurable-rules: Name does not resolve : errno 49
> [2019-11-04 12:06:48.715] boot - 6  INFO [main] --- ZeroMQEventSubscriber: Watching for new exported Event messages...
> [2019-11-04 12:06:48.757] boot - 6 ERROR [main] --- ZeroMQEventSubscriber: Unable to receive messages via ZMQ: socket is null
> [2019-11-04 12:06:48.773] boot - 6 ERROR [main] --- ZeroMQEventSubscriber: Shutting off Event message watch due to error!

Full error log [rulesengines.log](https://github.com/edgexfoundry/edgex-go/files/3804040/rulesengines.log)

**Comment by michaelestrin** [comment]
May be related.

- https://github.com/edgexfoundry/blackbox-testing/pull/321
- https://github.com/edgexfoundry/blackbox-testing/pull/320

**Comment by AnthonyMBonafide** [comment]
It looks like the issue with configuration. The errors seem to be stemming from the Docker container not be able to route requests to the container  `edgex-app-service-configurable-rules` which does not exist the container name probably should be `edgex-app-service-configurable`.

https://github.com/edgexfoundry/support-rulesengine/blob/35f17d8e59789244a7d634909f958bd3b73e8e81/docker-files/application.properties#L42

**Comment by michaelestrin** [comment]
> It looks like the issue with configuration.

@lenny-intel introduced these changes inhttps://github.com/edgexfoundry/support-rulesengine/pull/59; can @lenny-intel review/fix?

**Comment by tsconn23** [comment]
^^ It appears that change may depend on the following PR which isn't merged yet
https://github.com/edgexfoundry/developer-scripts/pull/170/files

**Comment by lenny-intel** [comment]
Yes, I will need to add those same changes to the BB tests compose file.
