### ISSUE TITLE
Remove unused request parameter from controller functions

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2074]
Realized in https://github.com/edgexfoundry/edgex-go/pull/2067 that we're not consistently handling request parameter in a closure-wrapped controller function call when the controller function doesn't actually use the parameter.

In the above-mentioned PR, the request was removed from the parameter list.  I believe this is the desired outcome.

In other services, we either pass the request and the controller function lists it either as an implicitly unused parameter (i.e. `r *http.Request`) or an explicitly unused parameter (i.e. `_ *http.Request`).

Refactor the latter (along with the associated tests, if any) to consistently remove the request parameter from the controller function's parameter list if it's not actually used by the controller function.

Depends on completion of the remaining global variable elimination work:

- https://github.com/edgexfoundry/edgex-go/issues/2017
- https://github.com/edgexfoundry/edgex-go/issues/2023
- https://github.com/edgexfoundry/edgex-go/issues/2031
- https://github.com/edgexfoundry/edgex-go/issues/2039
- https://github.com/edgexfoundry/edgex-go/issues/2071

**Comment by brandonforster** [comment]
core command uses the `request` parameter in every controller function currently. Whether that's what we want is an open question, but I don't think there's work to be done w.r.t. this issue on command.

**Comment by brandonforster** [comment]
Spoke too soon. The `ping` handler uses a request. PR to follow.
