### ISSUE TITLE
Delete event func for Redis misses the deletion of pushed and device collection

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2076]
# 🐞 Bug Report

### Affected Services
The issue is located in:  Core-Data

### Is this a regression?

No, it also happens in Delhi and Edinburgh release

### Description and Minimal Reproduction

When creating the event, there are two additional collections added to reference to the event id
```
	conn.Send("ZADD", db.EventsCollection, 0, id)
	conn.Send("ZADD", db.EventsCollection+":created", e.Created, id)
	conn.Send("ZADD", db.EventsCollection+":pushed", e.Pushed, id)
	conn.Send("ZADD", db.EventsCollection+":device:"+e.Device, e.Created, id)
```
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/data.go#L1056-L1059

However, the deleteEvent func only deletes two of them
```
	_ = conn.Send("ZREM", db.EventsCollection, id)
	_ = conn.Send("ZREM", db.EventsCollection+":created", id)
```
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/data.go#L1095-L1096

## 🔥 Exception or Error
The data will keep growing until out of memory

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu

**EdgeX Version:**
delhi, edinburgh, and fuji

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
add @TomFlem and @FelixTing for awareness

**Comment by michaelestrin** [comment]
cc: @AnthonyMBonafide

**Comment by AnthonyMBonafide** [comment]
This bug seems valid. I just want to point out that there is some async processing happening when events are deleted. See:

https://github.com/AnthonyMBonafide/edgex-go/blob/f07acc231909531283c898e4100e3cc5d499f8b9/internal/pkg/db/redis/data.go#L254-L267

I want to point this out so we can verify this functionality still works and is valid after we provide a fix for this.

**Comment by brandonforster** [comment]
@michaelestrin master on Delhi does not currently build. Please open other issues to resolve that or remove the Delhi tag from this bugfix.

**Comment by cloudxxx8** [comment]
@brandonforster 
I just noticed that 
```
	if e.Checksum != "" {
		_ = conn.Send("ZADD", db.EventsCollection+":checksum:"+e.Checksum, 0, e.ID)
	}
```
Thus, we should also delete checksum for binary event

**Comment by brandonforster** [comment]
@cloudxxx8 Where is that line of code from? I can't find it anywhere in `edgex-go`
