### ISSUE TITLE
security-secretstore-setup doesn't use --init at all

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#2077]
security-secretstore-setup currently accepts an `--init` option, but this is not used anywhere. It seems like it is coded just to always run as if --init=true and it's unclear what security-secretstore-setup would do if --init=false.

**Comment by tingyuz** [comment]
I checked the previous release and it seems it just exits if init=false. IMO this option is not needed any more, I will have a PR to remove it.
