### ISSUE TITLE
Develop dependency checking utility for eliminating shared library dependencies

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2078]
# 🚀 Feature Request

### Relevant Package
N/A

### Description
As part of resolving https://github.com/edgexfoundry/edgex-go/issues/1710, we needed to updates several containers to add alpine, curl and jq dependencies.

### Describe the solution you'd like
We should develop a golang executable that can be used by dependency checking scripts that incorporates the functionality of curl and jq to do these checks without requiring use of alpine container and installing curl and jq dependencies.

cc: @anonymouse64

**Comment by anonymouse64** [comment]
Related: https://github.com/edgexfoundry/docker-edgex-consul/issues/3

**Comment by bnevis-i** [comment]
Closed as duplicate.
