### ISSUE TITLE
Add retry logic within go-mod-secret to utilize the dependence check offered by customized consul

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#2080]
With the merge of https://github.com/edgexfoundry/developer-scripts/pull/172, the configuration for go-mod-secret within edgex-go needs to be changed as well to include retry logic so that it can utilize the features of dependence check provided across the microservice.

**Comment by anonymouse64** [comment]
See https://github.com/edgexfoundry/go-mod-secrets/pull/36 for the go-mod-secrets change associated with this and https://github.com/edgexfoundry/docker-edgex-mongo/pull/59 for how this should be done in the various core services here.
