### ISSUE TITLE
The steps to create user token is dated due to recent change on developer-script docker-compose file for FUJI

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#2105]
With latest changes on docker-compose file the steps to create user token in the readme file of edgex-go is dated and needs update.

**Comment by tingyuz** [comment]
Closed as the PR merged.

**Comment by michaelestrin** [comment]
@tingyuz Should these changes also be merged into master?

**Comment by tingyuz** [comment]
No, this is Fuji specific. In master the docker-compose file will be changed again soon so what we have in Fuji may not work on master pretty soon.
