### ISSUE TITLE
Should return boolean indicating the successful

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#211]
when test on **core-command** , PUT api didn't return boolean value as raml file describe .
code snippet:
https://github.com/edgexfoundry/edgex-go/blob/master/core/command/restDevice.go#L56
https://github.com/edgexfoundry/edgex-go/blob/master/core/command/restDevice.go#L69
https://github.com/edgexfoundry/edgex-go/blob/master/core/command/restDevice.go#L81
https://github.com/edgexfoundry/edgex-go/blob/master/core/command/restDevice.go#L93

**Comment by tsconn23** [comment]
Actually, I think it's the RAML that's out of date. The GoLang services return a 200 for a successful PUT which is more appropriate than a hardcoded "return true" as the Java services did.

**Comment by tsconn23** [comment]
@andyf1967

**Comment by tsconn23** [comment]
@andyf1967 @jpwhitemn Guys, my preference here is to leave the Go code as is and change the RAML. I don't see this as a bug. The current behavior is an improvement over the Java services IMHO. I would prefer not to fudge the Go services to make them do what the Java code did for the sake of California only to undo that after June. But, if we leave it and update the RAML, then the Java implementation is out of sync. We need to make a call here.

**Comment by SteveOss** [comment]
@tsconn23 My preference would be to update RAML and fix Java, i.e. implement the correct behaviour. Is this a lot of work for the Java services?

**Comment by tsconn23** [comment]
@SteveOss It could be as easy as just removing the "return true" from the relevant controller methods.

**Comment by tsconn23** [comment]
@weichou1229 On the Core WG call this morning, we decided we would make a limited change in the Java services to address the above specific cases. That means for these specific cases, the RAML will be updated and the Go code left as is. Post-California, we will address this on a more comprehensive basis. Please adjust tests for the above calls accordingly.

Incidentally, I noticed in some of the mods on this PR https://github.com/edgexfoundry/blackbox-testing/pull/24 that you added a content type check to verify "application/json" in the case where methods return "true". If we just go by a 200, these checks won't be required.

**Comment by weichou1229** [comment]
@tsconn23 ok , I saw `status code indicating success` in RAML , then I will remove two assertion , application/json and boolean value
