### ISSUE TITLE
Incorrect event type used when updating a device

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#2119]
# 🐞 Bug Report

### Affected Services
Core-metadata

### Is this a regression?

No, this looks like it has been this way for awhile.  However, the operator which encompasses this bug was created in this [commit](https://github.com/edgexfoundry/edgex-go/commit/818be3dfd721e644cbac9b5acdcbef0f0d1fb2ce)

### Description and Minimal Reproduction
The event type should be `PUT` since the associated operation is an update, but instead it is a `POST`

https://github.com/edgexfoundry/edgex-go/blob/818be3dfd721e644cbac9b5acdcbef0f0d1fb2ce/internal/core/metadata/operators/device/update.go#L143

1. Start core-services
2. Create a device
3. Update the device

See the Slack conversation for more details: https://edgexfoundry.slack.com/archives/CE6902Q6S/p1573569721008100

## 🔥 Exception or Error
An error is logged when the callback is invoked:

https://github.com/edgexfoundry/edgex-go/blob/21750bd69222753f69a7a217e480b07ca6bb6dd6/internal/core/metadata/operators/device/notify.go#L113

## 🌍  Your Environment
**Deployment Environment:**
Linux Fedora

**EdgeX Version:**
Fuji, this is also present in master(Geneva) 

**Anything else relevant?**

**Comment by phanvanhai** [comment]
I describe the process of the problem as follows:
1. Clone edgex-go Fuji, device-sdk-go Fuji. Run the example in sdk: device-simple.
In the picture, on the right side of the screen is the information of device service: device-simple.
2. Run device-simple DeviceService (DS). DS will add a new device: "Device-Simple02" with "description" = "Old".
3. Update:
3.1 Update by name: -> "Duplicate name for Device" error
3.2 Update by ID: "Duplicate name for Device" error
3.3 Update by name and ID:
edgex-go responded "true", when I read the device's information, it was indeed updated: "description" = "New", but in DS, it reported an error regarding adding a new device.
[add new device]
![create new device](https://user-images.githubusercontent.com/26240439/68729713-4cb4bf00-05fd-11ea-9f50-69f25145549a.png)
[update by id]
![update by id](https://user-images.githubusercontent.com/26240439/68729732-53433680-05fd-11ea-8ac7-82a3b8922047.png)
[update by name]
![update by name](https://user-images.githubusercontent.com/26240439/68729740-5a6a4480-05fd-11ea-8452-67d8c251caa3.png)
[update by name + id]
![update by name-id](https://user-images.githubusercontent.com/26240439/68729747-6229e900-05fd-11ea-8cf5-334cd45ebb16.png)
[result]
![updated](https://user-images.githubusercontent.com/26240439/68729754-65bd7000-05fd-11ea-8266-40c2f813360d.png)
[log of edgex-go]
![log edgex](https://user-images.githubusercontent.com/26240439/68729762-6c4be780-05fd-11ea-87f3-afc92376d0df.png)
