### ISSUE TITLE
kong fails to start on aarch64 due to hang in dependency checker due to multiple missing runtime dependencies

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2144]
#🐞 Bug Report

### Affected Services
Kong on aarch64

### Is this a regression?
Unknown

### Description and Minimal Reproduction
Spin up docker-compose stack on aarch64 ubuntu, using kong:1.3.0-ubuntu image using nightly docker-compose. curl command is not found; causing startup dependency checking to fail.

## 🔥 Exception or Error
<pre><code>
kong                 | + cd /consul/scripts
kong                 | + command -v jq
kong                 | + JQ=
kong                 | + [ -z  ]
kong                 | + LD_LIBRARY_PATH=.
kong                 | + export LD_LIBRARY_PATH
kong                 | + JQ=/consul/scripts/jq
kong                 | + export JQ
kong                 | + curl -s -G edgex-core-consul:8500/v1/agent/checks
kong                 | /consul/scripts/consul-svc-healthy.sh: 16: /consul/scripts/consul-svc-healthy.sh: + curl: not found
kong                 | /consul/scripts/jq -r .[] | select(.ServiceName == "kong-migrations") | .Status == "passing"
kong                 | /consul/scripts/consul-svc-healthy.sh: 16: /consul/scripts/consul-svc-healthy.sh: /consul/scripts/jq: not found
kong                 | + [ true =  ]
kong                 | + exit 2
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Linux redacted 5.3.0-1012-raspi2 #14-Ubuntu SMP Mon Nov 11 10:06:55 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

**EdgeX Version:**
Fuji (1.1.0)

**Anything else relevant?**

**Comment by anonymouse64** [comment]
Eh this is really just because the arm64 nightly docker-compose script is not updated with the amd64 one, you can see the error here:

```
kong                 | /consul/scripts/consul-svc-healthy.sh: 16: /consul/scripts/consul-svc-healthy.sh: /consul/scripts/jq: not found
```

which means that the consul-scripts volume was not mounted.

Since we already decided the security services would be experimental in Fuji for arm64, is there a point to fixing this for Fuji?

**Comment by bnevis-i** [comment]
Removed Fuji label.  

Actually, you are right as well.  Here are the details.

```
# pwd
/consul/scripts
# ldd jq
        linux-vdso.so.1 =>  (0x0000ffff80f30000)
        libonig.so.5 => ./libonig.so.5 (0x0000ffff80e21000)
        libc.musl-aarch64.so.1 => not found
        libc.musl-aarch64.so.1 => not found
# which curl
```

The aarch64 kong in the blackbox tests uses `kong:1.3.0-ubuntu`, which doesn't have curl.  Moreover, the `jq` utility comes from docker-edgex-consul and that is apparently based on alpine and doesn't have libc copied over.

**Comment by anonymouse64** [comment]
> doesn't have libc copied over.

... as it shouldn't because sharing libc's is a terrible idea :wink: 

The ideal solution to this whole class of problems is https://github.com/edgexfoundry/docker-edgex-consul/issues/3

**Comment by tingyuz** [comment]
Need more testing to find the root cause/alternative solution.

**Comment by bnevis-i** [comment]
Closing this issue as https://github.com/edgexfoundry/docker-edgex-consul/issues/3 has been merged and a new container released.
