### ISSUE TITLE
Document System Management APIv1 using Swagger

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2155]
For Geneva, the project is moving towards individual working groups being responsible for providing documentation of their service's public APIs using Swagger.  This is a placeholder issue to capture this requirement.  Will amend when additional information is available on how this is to be coordinated/accomplished project-wide.

**Comment by michaelestrin** [comment]
@cloudxxx8 Discussed this with @tsconn23 @jpwhitemn earlier today during the system managment working group meeting.  It's our understanding this is work you're doing across all of the repositories; converting the APIv1 RAML to OpenAPI Swagger documents.  Is this correct?

**Comment by cloudxxx8** [comment]
Yes, @michaelestrin 
@cherrycl will create a PR for this on Monday.  The conversion work has been done.

**Comment by michaelestrin** [comment]
Thank you @cloudxxx8.  I'll update all of the relevant issues.
