### ISSUE TITLE
Manual testing security features of edgex-go on aarch64 while  CI/CD blackbox testing platform is not available

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#2171]
Due to the limited resources & instability of blackbox arm64 testing platform it is needed to have some sorts of testing platform for security features so that these can be verified manually independently.

**Comment by tingyuz** [comment]
set up local aarch64 and verified that Fuji release works on the platform.

**Comment by tingyuz** [comment]
suggest to run the testing at least once a month.

**Comment by tingyuz** [comment]
plan to put more testing details in the future.

**Comment by bnevis-i** [comment]
Moving to in-progress now that aarch64 docker-compose files are checked in to developer-scritpts and blackbox-testing should now theoretically use them.  Need to track:

https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-ubuntu18.04-docker-arm64-4c-2g-master/

https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/

for successful execution and close this issue once successful execution is achieved.

**Comment by bnevis-i** [comment]
Non-security: 1317 pass, 3 fail

| Status | Start Time                   | Stop Time                    | Duration in ms | Parent Suite | Suite                                          | Sub Suite | Test Class    | Test Method | Name                             | Description |
|--------|------------------------------|------------------------------|----------------|--------------|------------------------------------------------|-----------|---------------|-------------|----------------------------------|-------------|
| failed | Tue Jan 07 12:34:39 UTC 2020 | Tue Jan 07 12:34:40 UTC 2020 | 744            |              | device / http://localhost:48082/api/v1/device  |           | CoreCommand   |             | Status code is 200               |             |
| failed | Tue Jan 07 12:32:50 UTC 2020 | Tue Jan 07 12:32:51 UTC 2020 | 948            |              | event / 07 http://localhost:48080/api/v1/event |           | CoreData      |             | Response time is less than 800ms |             |
| failed | Tue Jan 07 12:29:48 UTC 2020 | Tue Jan 07 12:29:48 UTC 2020 | 598            |              | Test whether the virtual device service exists |           | DeviceVirtual |             | Response body is correct         |             |

Security: 1345 pass, 6 fail
| Status | Start Time                   | Stop Time                    | Duration in ms | Parent Suite | Suite                                                                                                 | Sub Suite | Test Class           | Test Method | Name                             | Description |
|--------|------------------------------|------------------------------|----------------|--------------|-------------------------------------------------------------------------------------------------------|-----------|----------------------|-------------|----------------------------------|-------------|
| failed | Tue Jan 07 12:32:13 UTC 2020 | Tue Jan 07 12:32:13 UTC 2020 | 887            |              | transmission / Query transmissions by associating notificationâ€™s slug with limited returned records |           | SupportNotifications |             | Response time is less than 800ms |             |
| failed | Tue Jan 07 12:31:34 UTC 2020 | Tue Jan 07 12:31:35 UTC 2020 | 804            |              | notification / Create a normal notification                                                           |           | SupportNotifications |             | Response time is less than 800ms |             |
| failed | Tue Jan 07 12:22:15 UTC 2020 | Tue Jan 07 12:22:16 UTC 2020 | 804            |              | addressable_error_4xx / 314 http://localhost:48081/api/v1/addressable/id/:id                          |           | CoreMetadata         |             | Response time is less than 800ms |             |
| failed | Tue Jan 07 12:31:04 UTC 2020 | Tue Jan 07 12:31:04 UTC 2020 | 805            |              | subscription / Create a subscription                                                                  |           | SupportNotifications |             | Response time is less than 800ms |             |
| failed | Tue Jan 07 12:15:34 UTC 2020 | Tue Jan 07 12:15:35 UTC 2020 | 550            |              | Test whether the virtual device service exists                                                        |           | DeviceVirtual        |             | Response body is correct         |             |
| failed | Tue Jan 07 12:20:12 UTC 2020 | Tue Jan 07 12:20:12 UTC 2020 | 633            |              | device / http://localhost:48082/api/v1/device                                                         |           | CoreCommand          |             | Status code is 200               |             |

**Comment by bnevis-i** [comment]
Automated CI for aarch64 is now implemented.  Closing this issue.
