### ISSUE TITLE
(Fuji) System Management /metrics resource closes connection when requesting > 2 services

### ISSUE THREAD

**Issue by OdysLam** [edgexfoundry/edgex-go#2184]
# 🐞 Bug Report

### Affected Services
edgex-sys-mgmt

### Is this a regression?

🤷‍♂️

### Description and Minimal Reproduction
Request more than 2 different services from the /metrics resource of the edgex-sys-mgmt service.

## 🔥 Exception or Error

```
#using python requests:

requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

#using curl

curl: (52) Empty reply from server
```

## 🌍  Your Environment
Ubuntu 18

**Deployment Environment:**
Docker

**EdgeX Version:**
Fuji

**Comment by michaelestrin** [comment]
Duplicate #2008.
