### ISSUE TITLE
Make fails because of missing zmq lib

### ISSUE THREAD

**Issue by drasko** [edgexfoundry/edgex-go#22]
```
drasko@Marx:~/go/src/github.com/edgexfoundry/edgex-go$ make
CGO_ENABLED=0 go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=0.5.0" -o cmd/export-client/export-client ./cmd/export-client
CGO_ENABLED=1 go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=0.5.0" -o cmd/export-distro/export-distro ./cmd/export-distro
CGO_ENABLED=0 go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=0.5.0" -o cmd/core-metadata/core-metadata ./cmd/core-metadata
CGO_ENABLED=1 go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=0.5.0" -o cmd/core-data/core-data ./cmd/core-data
# pkg-config --cflags libzmq
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
pkg-config: exit status 1
Makefile:29: recipe for target 'cmd/core-data/core-data' failed
make: *** [cmd/core-data/core-data] Error 2
```

**Comment by drasko** [comment]
`sudo apt-get install libzmq3-dev` resolves the issue

**Comment by SaltySooda** [comment]
It seems that libzmq3-dev doesn‘t support CentOS.what should I do?

**Comment by lenny-intel** [comment]
> It seems that libzmq3-dev doesn‘t support CentOS.what should I do?

@SaltySooda, ZMQ has been Deprecated in EdgeX due to its limitations. It will be removed in the next major release. In the meantime you can build w/o ZMQ in Go services by adding the `no_zmq` build flag. 

```
go build -tags "no_zmq" ....
```

**Comment by SaltySooda** [comment]
thanks,that helps.

**Comment by Vincent990413** [comment]
> thanks,that helps.

sorry! could yo please tell me how can i do that?  I type in `make build` then I encountered that problem...how can I do to fix it? my OS is CentOS7.X, thank you very much!!!

**Comment by cloudxxx8** [comment]
please intall zero mq environment on your machine before running build
https://zeromq.org/download/

**Comment by Vincent990413** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Vincent990413** [comment]
> libzmq3-dev

OMG! thanks so much, Im working on it!!!!! :)

**Comment by Vincent990413** [comment]
> please intall zero mq environment on your machine before running build https://zeromq.org/download/

ah... still same.. 

Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
