### ISSUE TITLE
Convert security-proxy-setup to use go-mod-secrets (dependency tracker fix for master)

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2200]
# 🐞 Bug Report

### Affected Services
security-proxy-setup

### Description and Minimal Reproduction
Convert security-proxy-setup to use go-mod-secrets in the `Load()` method of internal/security/proxy/certs.go

Required to fix #1710 on master branch.

**Comment by tingyuz** [comment]
@bnevis-i I just checked the file internal/security/proxy/certs.go and noticed that the Load() is using fileioperformer and autotokenloader from go-mod-secret already. Is it safe to say this is fixed  and can be closed?

**Comment by bnevis-i** [comment]
Clarification: this request is asking that security-proxy-setup use 

`SecretClient:GetSecrets(subPath string, keys ...string) (map[string]string, error)`

instead of forming the HTTP request to Vault itself.

**Comment by tingyuz** [comment]
To utilize the existing SecretClient:GetSecrets, we need to make the configuration file consistent between security-proxy-setup and core microservices such as metadata etc through using the existing SecretStoreInfo in go-mod-bootstrap. Here is what we have in the go-mod-bootstrap:
```
type SecretStoreInfo struct {
	Host                    string
	Port                    int
	Path                    string
	Protocol                string
	Namespace               string
	RootCaCertPath          string
	ServerName              string
	Authentication          vault.AuthenticationInfo
	AdditionalRetryAttempts int
	RetryWaitPeriod         string
	retryWaitPeriodTime     time.Duration
	// TokenFile provides a location to a token file.
	TokenFile string
}
```
and the configuration file we have for security-proxy-setup is like this below: 
```
[SecretService]
Server = "edgex-vault"
Port = 8200
HealthCheckPath = "v1/sys/health"
CertPath = "v1/secret/edgex/edgex-security-proxy-setup/kong-tls"
TokenPath = "/tmp/edgex/secrets/edgex-security-proxy-setup/secrets-token.json"
CACertPath = "/tmp/edgex/secrets/ca/ca.pem"
SNIS = ["edgex-kong"]
```
So my proposal would be separating the [SecretService] into to categories. The first category will include what we have in go-mod-boostrap such as Host, port, path, protocol etc, and the 2nd category will only include SNIS and HealthCheckPath as these two are specific to proxy. so it will be something like this: 
```
[SecretStore]
Host = 'localhost'
Port = 8200
Path = 'v1/secret/edgex/proxy/blabla'

[Proxy]
HealthCheckPath = 'v1/sys/health'
SNIS = ["edgex-kong"]

```
The problem is that we are going to break the compatibility from FUJI release. 
What's your opinion? @bnevis-i  @jim-wang-intel  @mkbhanda

**Comment by jim-wang-intel** [comment]
@tingyuz Can we still use the old schema but somehow converts it in the wrapper code to preserve the compability?

**Comment by tingyuz** [comment]
@jim-wang-intel  yes it is another option we have - we can build SecretStoreInfo internally and pass it into go-mod-boostrap, however that may leave us inconsistent among the configuration files across the project which may still need to be addressed later. If we are OK to ignore the compatibility from FUJI then we will  be in better shape from now on.

**Comment by bnevis-i** [comment]
Fuji isn't LTS so I don't care about changing the configuration.toml between releases.

Diana did a similar change for edgex-mongo that can probably be used here as well:

https://github.com/edgexfoundry/docker-edgex-mongo/pull/74

**Comment by jim-wang-intel** [comment]
Sure, if the compatibility  is not a concerned at all, I am all for the consistence

**Comment by tingyuz** [comment]
@bnevis-i yes you nailed it - that PR is exactly what we are trying to do here. 
If backward compatibility is not a concern I will go ahead and make the changes.

**Comment by jim-wang-intel** [comment]
Also, I think we should leverage bootstrap if we can to reduce the duplication of codes

**Comment by michaelestrin** [comment]
Backward compatibility of configuration files was a topic in today's Core WG call.  Suggest you delay this change until the community decides whether or not configuration files must be backward-compatible across minor releases.  Geneva is a minor release.  The lack of backward-compatibility was the dominant reason given for reversing #2401.

@tsconn23 @tonyespy @jpwhitemn @lenny-intel

**Comment by bnevis-i** [comment]
I suggest it would be better to ahead with the change and unify the configuration, and write code for backward compatibility that we can throw away if we decide it isn't needed, rather than duplicating code and bugs for the purpose of not changing the config syntax.

**Comment by tingyuz** [comment]
Per the discussion result of security WG meeting on March 11th,  it is decided we will keep the original format of configuration same as Fuji but add internal structure to utilize the go-mod-secrets and go-mod-bootstrap. The format of configuration will be changed to be consistent with the [secretstore] section of other core-services in the next major release ( Hanoi as of now).

**Comment by tingyuz** [comment]
The 1st part of 2 to update on go-mod-bootstrap side is merged and working on 2nd part which is on edgex-go currently.

**Comment by tingyuz** [comment]
Will need PR https://github.com/edgexfoundry/go-mod-bootstrap/pull/60 to into place to avoid the race condition in edgex-go.
