### ISSUE TITLE
The Vault-worker docker entrypoint script uses the non-existing flag --init

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-go#2213]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
security-secretstore-setup

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes, this bug was introduced as --init flag was removed but not removed from entrypoint script.
The related PR: https://github.com/edgexfoundry/edgex-go/pull/2188 

### Description and Minimal Reproduction

When the vault-work docker image from master tries to launch, the docker-entry point script will not  start vault-worker as expected, as the --init flag is removed.

## 🔥 Exception or Error
<pre>

creating /vault/config/assets,
starting vault-worker...,
+ cd /consul/scripts,
+ command -v jq,
+ JQ=,
+ '[' -z  ],
+ LD_LIBRARY_PATH=.,
+ export LD_LIBRARY_PATH,
+ JQ=/consul/scripts/jq,
+ export JQ,
+ curl -s -G edgex-core-consul:8500/v1/agent/checks,
+ /consul/scripts/jq -r '.[] | select(.ServiceName == "security-secrets-setup") | .Status == "passing"',
+ '[' true '=' true ],
,
Usage: /security-secretstore-setup [options],
Server Options:,
	-p, --profile <name>                Indicate configuration profile other than default,
	-r, --registry                      Indicates service should use Registry,
	--insecureSkipVerify=true/false     Indicates if skipping the server side SSL cert verifcation, similar to -k of curl,
	--configfile=<file.toml>            Use a different config file (default: res/configuration.toml),
	--vaultInterval=<seconds>           Indicates how long the program will pause between vault initialization attempts until it succeeds,
Common Options:,
	-h, --help                          Show this message,
,
flag provided but not defined: -init,
<code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
linux ubuntu

**EdgeX Version:**
master as of Dec. 5, 2019

**Anything else relevant?**

**Comment by bnevis-i** [comment]
PR #2214 is merged. Closing.
