### ISSUE TITLE
Remove Export Services for Geneva Release

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2218]
Remove export-client and export-distro code (edgex-go) and related (developer-scripts, blackbox-testing).

**Comment by michaelestrin** [comment]
Reopened; https://github.com/edgexfoundry/edgex-docs/issues/59 must still be completed.

**Comment by michaelkargl** [comment]
Hey, I was just troubleshooting the mysterical disappearence of the export service mentioned in the docs
* https://docs.edgexfoundry.org/1.2/walk-through/Ch-WalkthroughExporting/

Does that mean that edgex currently has no means of exporting data to external services?

**Comment by michaelestrin** [comment]
> Hey, I was just troubleshooting the mysterical disappearence of the export service mentioned in the docs
> 
> * https://docs.edgexfoundry.org/1.2/walk-through/Ch-WalkthroughExporting/
> 
> Does that mean that edgex currently has no means of exporting data to external services?

I'm no longer directly involved with EdgeX.  You may be able to resolve this question by contacting @jpwhitemn.

**Comment by jpwhitemn** [comment]
@michaelkargl - export services have been deprecated with the Geneva release.  We are slowly updating the docs.  The new replacement is application services (with the app functions SDK to help you build new ones or use the app-service-configurable if you can get by with just configuration).  You can find these links to start to learn more
https://docs.edgexfoundry.org/1.2/getting-started/quick-start/#exporting-data
https://docs.edgexfoundry.org/1.2/microservices/application/ApplicationServices/
https://docs.edgexfoundry.org/1.2/microservices/application/AppServiceConfigurable/
https://docs.edgexfoundry.org/1.2/examples/AppServiceExamples/
https://docs.edgexfoundry.org/1.2/getting-started/ApplicationFunctionsSDK/
