### ISSUE TITLE
core-data scrub old event had performance problem

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#222]
when I compare below two method in java and go version , 
go version may cause performance issue ,
due to it will **select all** event data ,   it might replace with condition `bson.M{"created": bson.M{"$lt": expireDate}`

https://github.com/edgexfoundry/core-data/blob/master/src/main/java/org/edgexfoundry/dao/ScrubDao.java#L59
```
    Query scrubQuery = new Query();
    scrubQuery
        .addCriteria(Criteria.where("created").lt(Calendar.getInstance().getTimeInMillis() - age));
    // remove readings
    template.remove(scrubQuery, Reading.class);
    // now remove events
    WriteResult result = template.remove(scrubQuery, Event.class);
```
https://github.com/edgexfoundry/edgex-go/blob/master/core/data/clients/mongo-client.go#L196
```
  currentTime := time.Now().UnixNano() / int64(time.Millisecond)
  query := bson.M{}
  events, err := mc.getEvents(query)
  if err != nil {
    return nil, err
  }

  // Find each event that meets the age criteria
  newEventList := []models.Event{}
  for _, event := range events {
    if (currentTime - event.Created) > age {
      newEventList = append(newEventList, event)
    }
  }

```

**Comment by jduranf** [comment]
Talking about increase the performance, why we have to read all events (or partially) and then remove one by one?
Shouldn't be better to just remove the events directly from database? Maybe change EventsOlderThanAge to ScrubEventsOlderThanAge...
