### ISSUE TITLE
Value descriptor tests timing out on Blackbox tests (Security runs)

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/edgex-go#2220]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-data, value descriptors

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Fuji release

### Description and Minimal Reproduction
We are seeing the blackbox tests time out after running the value descriptor tests. 

## 🔥 Exception or Error

Links to Jenkins build failures:
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/blackbox-testing-security-centos7-blackbox-4c-2g-master/detail/blackbox-testing-security-centos7-blackbox-4c-2g-master/389/pipeline

https://jenkins.edgexfoundry.org/blue/organizations/jenkins/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/detail/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/358/pipeline
<pre><code>
core-data-importer

→ Import valueDescriptor

  GET http://edgex-core-data:48080/api/v1/ping [errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

  POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor [errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

Build timed out (after 60 minutes). Marking the build as failed.

$ ssh-agent -k

unset SSH_AUTH_SOCK;

unset SSH_AGENT_PID;

echo Agent pid 8995 killed;

[ssh-agent] Stopped.

Build was aborted

Unpacking https://repo.jenkins-ci.org/maven-repo1/io/qameta/allure/allure-commandline/2.9.0/allure-commandline-2.9.0.zip to /w/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Allure_Report on prd-centos7-blackbox-4c-2g-29145

[blackbox-testing] $ /w/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Allure_Report/bin/allure generate -c -o /home/jenkins/389/gopath/src/github.com/edgexfoundry/blackbox-testing/allure-report

allure-results does not exists

Report successfully generated to /home/jenkins/389/gopath/src/github.com/edgexfoundry/blackbox-testing/allure-report

Allure report was successfully generated.

Creating artifact for the build.

Artifact was added to the build.

Finished: FAILURE
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** jenkins.edgexfoundry.org

**EdgeX Version:** master / geneva

**Anything else relevant?** The blackbox tests were updated to use the images from the master branch and this issue popped up. The new images are being downloaded from Nexus properly and the blackbox tests are starting up. However, they time out after this error during the core-data value descriptor tests.

**Comment by michaelestrin** [comment]
Security versions are broken.  https://edgexfoundry.slack.com/archives/CE5U62YHM/p1575660256218800

**Comment by michaelestrin** [comment]
From https://jenkins.edgexfoundry.org/blue/rest/organizations/jenkins/pipelines/blackbox-testing-security-centos7-blackbox-4c-2g-master/runs/389/log/?start=0:

**Comment by michaelestrin** [comment]
From https://jenkins.edgexfoundry.org/blue/rest/organizations/jenkins/pipelines/blackbox-testing-security-centos7-blackbox-4c-2g-master/runs/389/log/?start=0:

```
------- vault-worker ------
creating /vault/config/assets
starting vault-worker...
/usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
waiting for security-secrets-setup
/usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
waiting for security-secrets-setup
/usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
waiting for security-secrets-setup
/usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
waiting for security-secrets-setup
/usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
waiting for security-secrets-setup
/usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
waiting for security-secrets-setup
/usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
waiting for security-secrets-setup
waiting for security-secrets-setup
/usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
```

This seems like an issue that was recently fixed (@jim-wang-intel, @tingyuz, @bnevis-i).  I don't believe this is an issue with core services and won't fix unless someone is able to provide some more explicit detail on exactly what is wrong.

**Comment by jim-wang-intel** [comment]
> 
> 
> From https://jenkins.edgexfoundry.org/blue/rest/organizations/jenkins/pipelines/blackbox-testing-security-centos7-blackbox-4c-2g-master/runs/389/log/?start=0:
> 
> ```
> ------- vault-worker ------
> creating /vault/config/assets
> starting vault-worker...
> /usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
> waiting for security-secrets-setup
> /usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
> waiting for security-secrets-setup
> /usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
> waiting for security-secrets-setup
> /usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
> waiting for security-secrets-setup
> /usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
> waiting for security-secrets-setup
> /usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
> waiting for security-secrets-setup
> /usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
> waiting for security-secrets-setup
> waiting for security-secrets-setup
> /usr/local/bin/entrypoint.sh: line 34: /consul/scripts/consul-svc-healthy.sh: not found
> ```
> 
> This seems like an issue that was recently fixed (@jim-wang-intel, @tingyuz, @bnevis-i). I don't believe this is an issue with core services and won't fix unless someone is able to provide some more explicit detail on exactly what is wrong.

The above mentioned issue is because there is no "consul-scripts:/consul/scripts" volume mapping existing yet on the current docker-compose file of the blackbox testing repo.   Either needs to sync'ed compose file with the one in the developer script --OR-- use the one from developer-script.  For the latter, @cloudxxx8 's team is working on #295 towards that, I believe.
