### ISSUE TITLE
Update security/secretstore tests to be OS-agnostic

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2233]
> On MacOS I get the following error running unit tests. I assume this is OS specific since Michael and Lenny are on Windows, Anthony and Jenkins are on Linux.
>```
>--- 
>FAIL: TestTrue (0.00s)
>    tokenprovider_test.go:64: 
>        	Error Trace:	tokenprovider_test.go:64
>        	Error:      	Expected nil, but got: &exec.Error{Name:"/bin/true", Err:(*os.PathError)(0xc00011a8d0)}
>        	Test:       	TestTrue
>FAIL
>coverage: 22.7% of statements
>FAIL	github.com/edgexfoundry/edgex-go/internal/security/secretstore	0.056s
>```

The test you reference assumes the operating system has a `true` command/executable.  There is another in the same file/suite -- TestEcho -- that assumes the operating system has an `echo` command/executable.  These are Linux-centric tests and assume a Linux environment.  I've run across other tests that have similar assumptions about the operating system.

As I'm currently configured, both of the aforementioned tests fail on my personal Windows machine.

I think we should avoid writing OS-specific tests (or tests that make assumptions about what is available within the environment a process is running).  IMO, these two tests should be rewritten; though I also believe doing so is outside the scope of this PR.

@tsconn23 @bnevis-i

_Originally posted by @michaelestrin in https://github.com/edgexfoundry/edgex-go/pull/2223#issuecomment-565724270_

**Comment by bnevis-i** [comment]
You are right.  These were integration tests not unit tests.  I have made them into unit tests and created an integration test that I commented out since there is no way to make the integration test cross-platform.
