### ISSUE TITLE
Remove config-seed service

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2236]
Remove config-seed service.  Consul configuration to be populated via common bootstrap package.

Coordinate with changes made in https://github.com/edgexfoundry/developer-scripts/issues/189.

Dependent upon completion of https://github.com/edgexfoundry/go-mod-bootstrap/issues/14.

**Comment by michaelestrin** [comment]
Believe we resolved that config-seed has to go.  Created this issue before the holiday break.  There are a number of moving parts that need to be coordinated in order to make config-seed go away.  

config-seed populates Consul with rules-engine properties (https://github.com/edgexfoundry/edgex-go/blob/master/cmd/config-seed/res/properties/edgex-support-rulesengine/application.properties and https://github.com/edgexfoundry/edgex-go/blob/master/cmd/config-seed/res/properties/edgex-support-rulesengine%3Bdocker/application.properties).  Existing rules-engine is being replaced.  (@lenny-intel, @rsdmike) What is the timing of the replacement (i.e. when will config-seed no longer be needed to populate the registry with legacy rules-engine properties)? 

config-seed populates Consul with device-virtual properties.  Assuming this is for the archived device-virtual repository/service and not for the current device-virtual-go repository/service.  (@jpwhitemn, @iain-anderson) Can you confirm that this is the case and that the configuration currently being populated by config-seed (https://github.com/edgexfoundry/edgex-go/blob/master/cmd/config-seed/res/properties/device-virtual/application.properties and https://github.com/edgexfoundry/edgex-go/blob/master/cmd/config-seed/res/properties/device-virtual%3Bdocker/application.properties) is not used or needed?

**Comment by michaelestrin** [comment]
Discussed in today's Core WG meeting.  There seemed to be consensus around removing config-seed but not necessarily around what the alternate implementation would be.  @jpwhitemn had hoped to do a related ADR and attempt to drive consensus but unfortunately hasn't had time to complete it.  

As I stated during the call, I will hold off on any activity to remove config-seed until we have consensus on what the expected alternative should be.

**Comment by lenny-intel** [comment]
As discussed in Core WG on 1/16/202, we'll assume Java Rule Engine will be removed in Geneva, so config-seed can be removed. An ADR (author TBD) will be created for this.

**Comment by iain-anderson** [comment]
Also the device-virtual is no longer relevant - has been replaced by device-virtual-go

**Comment by lenny-intel** [comment]
Rules engine will be removed in Geneva so is no longer relevant.

**Comment by michaelestrin** [comment]
> Rules engine will be removed in Geneva so is no longer relevant.

Yes.  It's a question of timing.  If we do have a suitable substitute for the other services that enables us to remove config-seed, and we subsequently remove config-seed before the existing rules engine has been removed, we will effectively break the existing rules engine.

If the community is certain rules engine will be remove, I'd suggest we move forward and remove it before we proceed with this work to remove config-seed (e.g. avoid breaking existing docker-compose files and the like).

**Comment by bnevis-i** [comment]
It appears as if the build for config-seed is broken and has been broken for about a week now.

From here: https://nexus3.edgexfoundry.org/#browse/search/docker=format%3Ddocker%20AND%20attributes.docker.imageName%3Ddocker-core-config-seed-go%20AND%20attributes.docker.imageTag%3Dmaster:7f6379d32f8dd78f5e6145df5681f2ea:cf606f82560ea906f46771320b76579c
the container was last built on Wed Mar 11 2020 09:38:12 GMT-0700 (Pacific Daylight Time)

Below is the output of attempting to build config seed, after adding gcc as a new package to the build container, which did not fully mitigate the issue.  (Limits.h is not in alpine's gcc.)

```
$ make docker_config_seed
docker build \
    --build-arg http_proxy \
    --build-arg https_proxy \
	-f cmd/config-seed/Dockerfile \
	--label "git_sha=01e4977c5a51f2ff55c1e3b26886d77859458597" \
	-t edgexfoundry/docker-core-config-seed-go:01e4977c5a51f2ff55c1e3b26886d77859458597 \
	-t edgexfoundry/docker-core-config-seed-go:master-dev \
	.
Sending build context to Docker daemon  408.4MB
Step 1/38 : FROM golang:1.13-alpine AS build-env
 ---> 57ce7b9daa9b
Step 2/38 : ENV GO111MODULE=on
 ---> Using cache
 ---> 4be112671f27
Step 3/38 : ENV GOPATH=/go
 ---> Using cache
 ---> e6b3936a7a50
Step 4/38 : ENV PATH=$GOPATH/bin:$PATH
 ---> Using cache
 ---> 07c108b5a1f5
Step 5/38 : WORKDIR $GOPATH/src/github.com/edgexfoundry/edgex-go
 ---> Using cache
 ---> 0b4802aedf7e
Step 6/38 : RUN apk update && apk add make git python3 jq gcc python3-dev
 ---> Running in 4ce95fa8bcaa
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
v3.11.3-133-g19a318d1ce [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]
v3.11.3-134-gd973662f3b [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]
OK: 11272 distinct packages available
(1/29) Installing libgcc (9.2.0-r3)
(2/29) Installing libstdc++ (9.2.0-r3)
(3/29) Installing binutils (2.33.1-r0)
(4/29) Installing gmp (6.1.2-r1)
(5/29) Installing isl (0.18-r0)
(6/29) Installing libgomp (9.2.0-r3)
(7/29) Installing libatomic (9.2.0-r3)
(8/29) Installing mpfr4 (4.0.2-r1)
(9/29) Installing mpc1 (1.1.0-r1)
(10/29) Installing gcc (9.2.0-r3)
(11/29) Installing nghttp2-libs (1.40.0-r0)
(12/29) Installing libcurl (7.67.0-r0)
(13/29) Installing expat (2.2.9-r1)
(14/29) Installing pcre2 (10.34-r1)
(15/29) Installing git (2.24.1-r0)
(16/29) Installing oniguruma (6.9.4-r0)
(17/29) Installing jq (1.6-r0)
(18/29) Installing make (4.2.1-r2)
(19/29) Installing libbz2 (1.0.8-r1)
(20/29) Installing libffi (3.2.1-r6)
(21/29) Installing gdbm (1.13-r1)
(22/29) Installing xz-libs (5.2.4-r0)
(23/29) Installing ncurses-terminfo-base (6.1_p20200118-r2)
(24/29) Installing ncurses-libs (6.1_p20200118-r2)
(25/29) Installing readline (8.0.1-r0)
(26/29) Installing sqlite-libs (3.30.1-r1)
(27/29) Installing python3 (3.8.2-r0)
(28/29) Installing pkgconf (1.6.3-r0)
(29/29) Installing python3-dev (3.8.2-r0)
Executing busybox-1.31.1-r8.trigger
OK: 223 MiB in 44 packages
Removing intermediate container 4ce95fa8bcaa
 ---> 5283998dcc31
Step 7/38 : RUN python3 -m pip install remarshal
 ---> Running in 4a24cbd08c3f
Collecting remarshal
  Downloading https://files.pythonhosted.org/packages/db/0e/a0508324594631aa4797434cc5872e7ab381599610f332ac374082e25c64/remarshal-0.12.0-py3-none-any.whl
Collecting cbor2>=5.0.0 (from remarshal)
  Downloading https://files.pythonhosted.org/packages/ee/80/bc617b7fd89855649e48eb8242e09535e1b75371ec8389313fa0f97e2a70/cbor2-5.1.0.tar.gz (72kB)
Collecting pytoml>=0.1.11 (from remarshal)
  Downloading https://files.pythonhosted.org/packages/a5/47/c7f8a0f210ad18576840922e0b504f0b7f5f73aea4a52ab14c5b58517edf/pytoml-0.1.21-py2.py3-none-any.whl
Collecting PyYAML>=5.1 (from remarshal)
  Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
Collecting u-msgpack-python>=2.5.1 (from remarshal)
  Downloading https://files.pythonhosted.org/packages/da/ec/9f984fc2be20b2b78bb4e7d9ee1a13f7868d2c075e812d7a1e0a8ef30142/u_msgpack_python-2.5.2-py2.py3-none-any.whl
Collecting python-dateutil>=2.5.0 (from remarshal)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
Collecting six>=1.5 (from python-dateutil>=2.5.0->remarshal)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Installing collected packages: cbor2, pytoml, PyYAML, u-msgpack-python, six, python-dateutil, remarshal
  Running setup.py install for cbor2: started
    Running setup.py install for cbor2: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uylpkot5/cbor2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uylpkot5/cbor2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-of4whi07/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-uylpkot5/cbor2/
    Complete output (22 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/cbor2
    copying cbor2/decoder.py -> build/lib.linux-x86_64-3.8/cbor2
    copying cbor2/__init__.py -> build/lib.linux-x86_64-3.8/cbor2
    copying cbor2/encoder.py -> build/lib.linux-x86_64-3.8/cbor2
    copying cbor2/types.py -> build/lib.linux-x86_64-3.8/cbor2
    copying cbor2/compat.py -> build/lib.linux-x86_64-3.8/cbor2
    running build_ext
    building '_cbor2' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/source
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.8 -c source/module.c -o build/temp.linux-x86_64-3.8/source/module.o -std=c99 -D_GNU_SOURCE
    In file included from source/module.c:2:
    /usr/include/python3.8/Python.h:11:10: fatal error: limits.h: No such file or directory
       11 | #include <limits.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uylpkot5/cbor2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uylpkot5/cbor2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-of4whi07/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c python3 -m pip install remarshal' returned a non-zero code: 1
Makefile:90: recipe for target 'docker_config_seed' failed
make: *** [docker_config_seed] Error 1
```

**Comment by lenny-intel** [comment]
@bnevis-i,  Looks like a failure to install Python. This will all go away soon as config-seed will be removed and env overrides will take care of the config changes that are being done in the Dockerfile.

**Comment by lenny-intel** [comment]
@tsconn23 , can you post this list of todo's you recorded for when config-seed is remove?

**Comment by bnevis-i** [comment]
I have submitted PR #2444 to disable build of config seed if this is what we want to do in the short term to enable us to make forward progress.

**Comment by lenny-intel** [comment]
@tsconn23 , I think @bnevis-i 's temp solution should suffice. You agree?

**Comment by lenny-intel** [comment]
PR for this ADR edgexfoundry/edgex-docs#115 has consensus and in process of TSC approval, so moving forward with a PR for this which covers all the edgex-go related portions from the ADR.

**Comment by AnthonyMBonafide** [comment]
@lenny-intel, Now that we can move forward with this issue, what issues need to be created to track this work?

As I see it we have the following items to do with associated issues:

1. Update `go-mod-bootstrap` to include the functionality that `config-seed` is now doing: https://github.com/edgexfoundry/go-mod-bootstrap/issues/14

1. Update `edgex-go` to use the changes in `go-mod-bootstrap` and remove the existing packages: this issue

1. Remove docker images from developer scripts:  https://github.com/edgexfoundry/developer-scripts/issues/189

1. Update documentation to not include config-seed: Need to create an issue

Is this correct and/or did I miss anything?

**Comment by lenny-intel** [comment]
> Is this correct and/or did I miss anything?
@AnthonyMBonafide , 3 above needs to include the addition of env overrides, which I plan to discuss in this week's Core WG and have changes WIP for it.  I have PRs for 1 & 2 above.   So the outstanding is an issue for 4 on edgex-docs. Config documentation is a large gap in our current documentation so it is bigger that documenting these changes. I'll ping @tsconn23 to add another topic for Core WG for documentation.

**Comment by michaelestrin** [comment]
Can this issue be closed @lenny-intel @AnthonyMBonafide?

**Comment by lenny-intel** [comment]
Yes, doc issue was created by Trevor
