### ISSUE TITLE
Cannot create access token for API gateway authentication (Fuji)

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2268]
** Duplicated from #2267 **

**Version:** fuji, master

**Environment:**
X86_64 Ubuntu16.04
X86_64 macOS Catalina 10.15.1

**Description:** Cannot create access token for API gateway authentication

**Steps to reproduce:**

_fuji_
1. docker-compose -f [docker-compose-fuji.yml](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/fuji/compose-files/docker-compose-fuji.yml) up -d
2. docker-compose -f docker-compose-fuji.yml run edgex-proxy --init=false --useradd=user --group=admin

_master_
1. docker-compose -f [docker-compose-nexus.yml](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus.yml) up -d
2. docker-compose -f docker-compose-nexus.yml run edgex-proxy --init=false --useradd=user --group=admin

(Also tried to start the security-related services individually like the [deploy-edgex.sh](https://github.com/edgexfoundry/blackbox-testing/blob/master/deploy-edgeX.sh) does, it's still not working.)

**Expected result:** Return the access token

**Received result:**
> Starting kong-db ... done
> Starting edgex-files ... done
> Starting edgex-core-consul ... done
> Starting edgex-vault ... done
> Starting kong-migrations ... done
> Starting kong ... done
> \+ cd /consul/scripts
> \+ command -v jq
> \+ JQ=
> \+ '[' -z ]
> \+ LD_LIBRARY_PATH=.
> \+ export LD_LIBRARY_PATH
> \+ JQ=/consul/scripts/jq
> \+ export JQ
> \+ /consul/scripts/jq -r '.[] | select(.ServiceName == "kong") | .Status == "passing"'
> \+ curl -s -G edgex-core-consul:8500/v1/agent/checks
> \+ '[' true '=' true ]
> \+ cd /consul/scripts
> \+ command -v jq
> \+ JQ=
> \+ '[' -z ]
> \+ LD_LIBRARY_PATH=.
> \+ export LD_LIBRARY_PATH
> \+ JQ=/consul/scripts/jq
> \+ export JQ
> \+ curl -s -G edgex-core-consul:8500/v1/agent/checks
> \+ /consul/scripts/jq -r '.[] | select(.ServiceName == "security-secretstore-setup") | .Status == "passing"'
> \+ '[' true '=' true ]
> level=ERROR ts=2019-12-23T09:11:57.639625Z app=edgex-security-proxy-setup source=logger.go:73 msg="logTarget cannot be blank, using stdout only"

> Creating directory: ./logs
> level=INFO ts=2019-12-23T09:11:57.6417117Z app=edgex-security-proxy-setup source=requestor.go:40 msg="successfully loaded rootCA certificate."

> level=INFO ts=2019-12-23T09:11:57.6504506Z app=edgex-security-proxy-setup source=service.go:64 msg="the service on http://kong:8001 is up successfully"

> level=DEBUG ts=2019-12-23T09:11:57.6904699Z app=edgex-security-proxy-setup source=service.go:151 msg="trying to upload cert to proxy server"

> level=ERROR ts=2019-12-23T09:11:57.6957547Z app=edgex-security-proxy-setup source=service.go:182 msg="failed to add certificate with errorcode 400, error {"message":"schema violation (snis: edgex-kong already associated with existing certificate '49b0a17f-599d-45dd-9496-33b9a0af14d1')","name":"schema violation","fields":{"snis":"edgex-kong already associated with existing certificate '49b0a17f-599d-45dd-9496-33b9a0af14d1'"},"code":2}"

> level=INFO ts=2019-12-23T09:11:57.6970807Z app=edgex-security-proxy-setup source=service.go:98 msg="skipping as the initialization has been done successfully"

cc: @FelixTing

**Comment by bnevis-i** [comment]
Does the resolution for #2267 work for Fuji release as well?

**Comment by tingyuz** [comment]
@bnevis-i it should but needs verification. I will pull the Fuji release and get it done.

**Comment by tingyuz** [comment]
PR-2236 that addresses the issue has been merged, hence close this issue.
