### ISSUE TITLE
Switch default db provider to Redis (Tracking Issue)

### ISSUE THREAD

**Issue by andresrinivasan** [edgexfoundry/edgex-go#2270]
# 🚀 Feature Request

### Relevant Package

Digging into details now

### Description

As agreed at the October 2019 F2F, Redis is to become the default DB provider for EdgeX. It was also agreed that the Redis integration would be updated to support authentication as provided by EdgeX Secrets.

Tracked issues:

- ~~https://github.com/edgexfoundry/developer-scripts/issues/207~~
- ~~https://github.com/edgexfoundry/developer-scripts/issues/194~~
- ~~https://github.com/edgexfoundry/app-functions-sdk-go/issues/253~~
- ~~https://github.com/edgexfoundry/edgex-go/issues/2163~~
- ~~https://github.com/edgexfoundry/edgex-go/issues/1903~~ (no longer part of Geneva)
- https://github.com/edgexfoundry/edgex-go/issues/1746
- https://github.com/edgexfoundry/edgex-go/issues/1490
- https://github.com/edgexfoundry/edgex-go/issues/1442
- ~~https://github.com/edgexfoundry/edgex-go/issues/1388~~ (no longer part of Geneva)
- https://github.com/edgexfoundry/edgex-go/issues/1203
- https://github.com/edgexfoundry/edgex-go/issues/959
- ~~https://github.com/edgexfoundry/edgex-go/issues/631~~
- https://github.com/edgexfoundry/edgex-go/issues/2509

**Comment by michaelestrin** [comment]
@andresrinivasan reach out to @lenny-intel or @rsdmike to create issues related to migrating from Mongo to Redis in the AppFunc space.
