### ISSUE TITLE
Run error of duplicate key in database

### ISSUE THREAD

**Issue by Nitu-coder** [edgexfoundry/edgex-go#2275]
Hello,

I have taken the latest code and build it. When i execute make run command, my services fail with the following error logs

level=ERROR ts=2020-01-13T06:38:03.244007168Z app=edgex-support-scheduler source=init.go:63 msg="**Failed to load schedules and events E11000 duplicate key error collection: scheduler.intervalAction index: slug_1 dup key: { : null** }"**
level=INFO ts=2020-01-13T06:38:03.334310287Z app=edgex-core-data source=message.go:58 msg="Service started in: 720.293355ms"
level=INFO ts=2020-01-13T06:38:03.334690649Z app=edgex-support-scheduler source=database.go:155 msg="**Database disconnected"**

Can you please let me the cause and how can i remove the error. I have freshly installed the mongodb and instance of it is running.

**Comment by jpwhitemn** [comment]
Nitu - are you starting with a clean database volume?  Also, it looks like an issue with setting up a schedule.  Did you create a new schedule via some service?

    On Sunday, January 12, 2020, 11:42:09 PM MST, Nitu <notifications@github.com> wrote:  
 
 
Hello,

I have taken the latest code and build it. When i execute make run command, my services fail with the following error logs

level=ERROR ts=2020-01-13T06:38:03.244007168Z app=edgex-support-scheduler source=init.go:63 msg="Failed to load schedules and events E11000 duplicate key error collection: scheduler.intervalAction index: slug_1 dup key: { : null }"**
level=INFO ts=2020-01-13T06:38:03.334310287Z app=edgex-core-data source=message.go:58 msg="Service started in: 720.293355ms"
level=INFO ts=2020-01-13T06:38:03.334690649Z app=edgex-support-scheduler source=database.go:155 msg="Database disconnected"

Can you please let me the cause and how can i remove the error. I have freshly installed the mongodb and instance of it is running.

**Comment by Nitu-coder** [comment]
> Nitu - are you starting with a clean database volume?  Also, it looks like an issue with setting up a schedule.  Did you create a new schedule via some service? On Sunday, January 12, 2020, 11:42:09 PM MST, Nitu <notifications@github.com> wrote: Hello, I have taken the latest code and build it. When i execute make run command, my services fail with the following error logs level=ERROR ts=2020-01-13T06:38:03.244007168Z app=edgex-support-scheduler source=init.go:63 msg="Failed to load schedules and events E11000 duplicate key error collection: scheduler.intervalAction index: slug_1 dup key: { : null }"** level=INFO ts=2020-01-13T06:38:03.334310287Z app=edgex-core-data source=message.go:58 msg="Service started in: 720.293355ms" level=INFO ts=2020-01-13T06:38:03.334690649Z app=edgex-support-scheduler source=database.go:155 msg="Database disconnected" Can you please let me the cause and how can i remove the error. I have freshly installed the mongodb and instance of it is running. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Nitu-coder** [comment]
Yes its working now after clearing the entire database volume. Thanks

**Comment by Nitu-coder** [comment]
http://localhost:8500/ is gives me unable to connect. Any security thing missing ??

Services have started successfully.

**Comment by michaelestrin** [comment]
GitHub issues are for reporting issues and tracking work.  This issue is requesting support.  Please connect with the community for support via EdgeXFoundry's Slack channels or mailing lists.  See https://wiki.edgexfoundry.org/display/FA/Getting+Help for more information.

**Comment by Nitu-coder** [comment]
ok, thanks alot. Raised the issue in slack channel #help section
