### ISSUE TITLE
Remove UpdateLastConnected logic in coredata

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/edgex-go#2280]
Following through the discussion in [#429](https://github.com/edgexfoundry/device-sdk-go/pull/429), now the `LastConnected` timestamp will only be updated by Device SDK.  
We should remove the related logic in edgex-go

**Comment by tsconn23** [comment]
Reassigned project and label from core services to device services since remaining PR pending approval is against Device SDK Go.

**Comment by cloudxxx8** [comment]
fixed by #429
