### ISSUE TITLE
Update OpenAPI docs for V2 API specification

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2314]
As a follow-on to https://github.com/edgexfoundry/edgex-go/pull/2309, address:

> To remain transport agnostic, pagination primitives must be added to the appropriate request and response DTOs. This doesn't preclude the HTTP implementation from populating those values from optional parameters on the use-case endpoint URL.

>Individual read and delete endpoints do not have corresponding request and response DTOs.

(See specifically https://github.com/edgexfoundry/edgex-go/pull/2309#event-2967934285.)

**Comment by tsconn23** [comment]
Closing as out of date
