### ISSUE TITLE
Integrate latest bootstrap for new Configuration & Registry clients and common command line parsing

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#2316]
# 🚀 Feature Request

### Relevant Package

 This feature request is for integrating the latest `go-mod-bootstrap` containing new Configuration & Registry clients and common command line parsing

### Description
 A clear and concise description of the problem or missing capability...
The Registry Abstraction has been refactored into separate configuration and service registration abstractions which has been integrated into go-mod-bootstrap. As part of this integration a common command line parsing abstract has been created in `go-mod-bootstrap`. 

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
This new version of the `go-mod-bootstrap` needs to be integrated into all the services within `edgex-go`

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
None

**Comment by michaelestrin** [comment]
Dependent upon completion of https://github.com/edgexfoundry/go-mod-bootstrap/issues/18
