### ISSUE TITLE
Address fallout from root token revokation (docker only)

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2318]
# 🐞 Bug Report

### Description and Minimal Reproduction
Blackbox testing is failing due to inability to find Vault token in resp-init.json following root token revokation.

```
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/408/consoleText
```

Affected services list:
- [x] edgex-core-command
- [x] edgex-core-data
- [x] edgex-core-metadata
- [x] edgex-mongo
- [x] edgex-support-logging
- [x] edgex-support-notifications
- [x] edgex-support-scheduler

Specific errors:

```
level=ERROR ts=2020-01-23T12:13:24.881777068Z app=edgex-mongo source=config.go:73 msg="failed to read secret stores data for '/v1/secret/edgex/mongo/rulesengine' path: Unable to obtain secrets from underlying data-store: Received a '400' response from the secret store"

level=ERROR ts=2020-01-23T12:10:06.443261949Z app=edgex-support-logging source=secret.go:58 msg="unable to parse secret store configuration: Unable to find authentication token in /vault/config/assets/resp-init.json"

level=ERROR ts=2020-01-23T12:10:25.137346423Z app=edgex-core-data source=secret.go:58 msg="unable to parse secret store configuration: Unable to find authentication token in /vault/config/assets/resp-init.json"

level=ERROR ts=2020-01-23T12:11:09.323687965Z app=edgex-support-notifications source=secret.go:58 msg="unable to parse secret store configuration: Unable to find authentication token in /vault/config/assets/resp-init.json"

level=ERROR ts=2020-01-23T12:11:29.347249238Z app=edgex-core-metadata source=secret.go:58 msg="unable to parse secret store configuration: Unable to find authentication token in /vault/config/assets/resp-init.json"

level=ERROR ts=2020-01-23T12:11:51.297965091Z app=edgex-core-command source=secret.go:58 msg="unable to parse secret store configuration: Unable to find authentication token in /vault/config/assets/resp-init.json"

level=ERROR ts=2020-01-23T12:12:12.820272862Z app=edgex-support-scheduler source=secret.go:58 msg="unable to parse secret store configuration: Unable to find authentication token in /vault/config/assets/resp-init.json"
```

**Comment by tingyuz** [comment]
Tested and verified that the PRs fixed the error. Here is the log from one of the core services.

level=INFO ts=2020-01-24T20:05:24.1477188Z app=edgex-core-data source=registry.go:149 msg="Writeable configuration has been updated from the Registry"
level=INFO ts=2020-01-24T20:05:24.3869021Z app=edgex-core-data source=database.go:152 msg="Database connected"
level=INFO ts=2020-01-24T20:05:24.4044586Z app=edgex-core-data source=telemetry.go:86 msg="Telemetry starting"
level=INFO ts=2020-01-24T20:05:24.4046429Z app=edgex-core-data source=httpserver.go:89 msg="Web server starting (edgex-core-data:48080)"
level=INFO ts=2020-01-24T20:05:24.4046614Z app=edgex-core-data source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2020-01-24T20:05:24.4046724Z app=edgex-core-data source=message.go:51 msg="Starting edgex-core-data master "
level=INFO ts=2020-01-24T20:05:24.4047784Z app=edgex-core-data source=message.go:55 msg="This is the Core Data Microservice"
level=INFO ts=2020-01-24T20:05:24.4047898Z app=edgex-core-data source=message.go:58 msg="Service started in: 462.9738ms"
