### ISSUE TITLE
Notifications service doesn't distribute the notifications with Normal severity

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2328]
# 🐞 Bug Report

### Affected Services
The issue is located in:  Notifications

### Is this a regression?
 No, it happens in fuji and master

### Description and Minimal Reproduction
Create a Notification with Normal severity, and it won't be sent out.
Only the Critical Notifications will be sent out immediately.
According to the document https://docs.edgexfoundry.org/Ch-AlertsNotifications.html , there should be a mechanism for the Normal Notifications to be processed in batch on schedule.
Core Metadata is creating Notification whenever the Device is updated, and the severity is Normal, which means they won't be sent out.

## 🔥 Exception or Error
N/A

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 18

**EdgeX Version:**
Fuji, master

**Anything else relevant?**
N/A

**Comment by cloudxxx8** [comment]
add @jinlinGuan for awareness

**Comment by akramtexas** [comment]
- @cloudxxx8 Agree that only critical notifications are sent out immediately. Also agree that, according to the document https://docs.edgexfoundry.org/Ch-AlertsNotifications.html, `For normal notifications (severity = "NORMAL"), they wait for the Message Scheduler to process in batch.` The preceding is mentioned (in that document) right after the note that `The Notifications Handler persists the receiving notification first, and passes them to the Distribution Coordinator immediately if the notifications are critical (severity = "CRITICAL")`.
- Evidently, this functionality _needs_ to be implemented (i.e. `For normal notifications (severity = "NORMAL"), they wait for the Message Scheduler to process in batch.`)
- As far as I've been able to determine (details below), the functionality made available via a call to `func dbClient.MarkNotificationProcessed()`) is currently applied only if the notification is CRITICAL, and not if the notification is NORMAL. 
- I used a debugger to step through the `support-notifications` code (specifically starting with the func notificationHandler()) for the scenario when (1) creating a CRITICAL notification, and while (2) creating a NORMAL notification.
- By comparing the flow of execution for the two scenarios above, the call to `func distributeAndMark()` (which, in turn, calls `func dbClient.MarkNotificationProcessed()`) is made if the notification is CRITICAL but not if the notification is NORMAL. 
- The latter (i.e. when the notification is CRITICAL) can be seen via the call stack as follows:
```
github.com/edgexfoundry/edgex-go/internal/support/notifications.distributeAndMark at normal_distribution.go:34
github.com/edgexfoundry/edgex-go/internal/support/notifications.notificationHandler at rest_notification.go:76
github.com/edgexfoundry/edgex-go/internal/support/notifications.loadRestRoutes.func4 at router.go:67
```
- **The scope of implementing the functionality** (i.e. For normal notifications (severity = "NORMAL") to be processed in batch) is as follows:
- The `func notificationHandler()` needs to be updated to contain another `if` block (to handle `models.Normal`) along the lines of the following existing one:
```
if n.Severity == models.NotificationsSeverity(models.Critical) { ... }
```
- Doing so will enable the `func distributeAndMark()` to be called for the scenario when the notification is NORMAL:
```
err := distributeAndMark(n, lc, dbClient, config)
```
- That, in turn, will enable the `func distribute()` to be called, which (currently) happens to be called as a goroutine when the notification is CRITICAL:
```
	go distribute(n, lc, dbClient, config)
```
- That, in turn, calls the `func distribute()`. But we should not process a notification immediately if its severity is NORMAL. Instead, the aforementioned funcs need to be revisited and either updated or other, suitable funcs created (again, this is for scenario where a notification has severity NORMAL) whereby the Message Scheduler processes NORMAL notifications in batch mode.
- @cloud Referring to your final observation (`Core Metadata is creating Notification whenever the Device is updated, and the severity is Normal, which means they won't be sent out.`) in this bug's description, I did find that Core Metadata is indeed creating a notification whenever a Device is updated:
```
	notifier := device.NewNotifier(ch, nc, configuration.Notifications, dbClient, requester, lc, ctx)
	go notifier.Execute()
```

**Comment by tsconn23** [comment]
@akramtexas Referring to the [docs ](https://docs.edgexfoundry.org/Ch-AlertsNotifications.html)you link to above, it also says the following
```
For normal notifications (severity = “NORMAL”), they wait for the Message Scheduler to process in batch.

The Alerts and Notifications is scalable, can be expanded to add more severities and set up corresponding Message Schedulers to process them. For example, the Message Scheduler of normal severity notifications is triggered every two hours, and the minor severity notifications is triggered every 24 hours, at midnight each night.
```
Can you point me to where this is implemented because I can't seem to locate it. Right now the code reads to me like we're never sending any NORMAL or MINOR notifications until a CRITICAL is received, at which time all the pending notifications are flushed. If the scheduling described above is not implemented, it's a gap.

As an aside, I would advocate for just sending notifications of any severity as they're received. I don't know what efficiency is gained by batching them. However, similar to log levels, I could see configuring the service to not send notifications unless they were at or above a given severity.

**Comment by akramtexas** [comment]
@tsconn23 
- This is to confirm the existence of the gap you refer to: The scheduling described in the docs is currently _not_ implemented (I, too, had searched for it, and not found it while doing the investigation yesterday.)
- I agree with your recommendation: Simply sending notifications of _any_ severity as they're received makes the most sense: I, too, don't know what efficiency is gained by batching them.
- Yes, similar to log levels, configuring the service to not send notifications unless they are at or above a given severity sounds like an excellent option to provide to users.
- Please let me know if there's any other information you need prior to discussing the implementation at this week's Core WG.

**Comment by cloudxxx8** [comment]
I agree with sending every notification immediately for now, and see whether there is any further requirement in the future.

**Comment by tsconn23** [comment]
@akramtexas Please go ahead and make the change to send notifications of any severity when they are received rather than batching. In addition, please revise the docs content accordingly.

We can then create a follow-up issue as a proposed enhancement to configure the service to not send notifications unless they were at or above a given severity.

**Comment by akramtexas** [comment]
> @akramtexas Please go ahead and make the change to send notifications of any severity when they are received rather than batching. In addition, please revise the docs content accordingly.
> 
> We can then create a follow-up issue as a proposed enhancement to configure the service to not send notifications unless they were at or above a given severity.

@tsconn23 Sounds good. I will make it so.

**Comment by akramtexas** [comment]
- Since this issue affects the `Fuji` release as well (in addition to the `master` branch), the changeset per https://github.com/edgexfoundry/edgex-go/pull/2347 needs to be applied to the `Fuji` tagged release as well (It seems efficient to wait for approval of this changeset before applying the same changeset to the `Fuji` tagged release).

**Comment by akramtexas** [comment]
> * Since this issue affects the `Fuji` release as well (in addition to the `master` branch), the changeset per #2347 needs to be applied to the `Fuji` tagged release as well (It seems efficient to wait for approval of this changeset before applying the same changeset to the `Fuji` tagged release).

- The `PR` to update the `fuji` tagged release has been closed, [based on a detailed discussion](https://github.com/edgexfoundry/edgex-go/pull/2397#issuecomment-592727101). Closing this issue as such ✅
