### ISSUE TITLE
Refactor correlation middleware so that it does not use Context

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/edgex-go#2334]
# 🚀 Feature Request

### Relevant Package
This feature request is for `edgex-go` and `go-mod-core-contracts` in the `correlation` package.

### Description
Currently, the `correlation` package uses the Context as a simple data store. This requires that consuming services (such as `logging`) make use of the Context simply to retrieve a string. This is implementation detail that should not be exposed.

### Describe the solution you'd like
Refactor the `correlation` package so that it does not use the Context for data storage. This could include outputting a string, passing the correlation ID around, or attaching the correlation as a field on DTOs.

**Comment by michaelestrin** [comment]
Correlation package is APIv1-specific and will disappear with APIv2 implementation/rollout.  I've reviewed and concluded this is not worth the effort.  Closing.
