### ISSUE TITLE
Update Core/Support/SMA Service Dockerfiles for Go 1.13

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#2341]
A Geneva release goal is to update our dependency on Go to utilize v1.13 of the compiler. For this issue, please modify all core/support Dockerfiles to use Go 1.13.

Example of current reference in core-command service:
https://github.com/edgexfoundry/edgex-go/blob/f0ecddb33a38178a7f9f83b66f655389afed08a7/cmd/core-command/Dockerfile#L9

Change the reference from `1.12` to `1.13` for all core, support and SMA-related images.

Please also change the `go 1.12` reference in the `go.mod` to `go 1.13`

**Comment by akramtexas** [comment]
@tsconn23 The (two) Dockerfiles `edgexfoundry/edgex-go/cmd/security-secrets-setup/Dockerfile` and `edgexfoundry/edgex-go/cmd/security-secretstore-setup/Dockerfile` are not explicitly mentioned in the list of Dockerfiles to update. Would like a confirmation please if this is intentional, thanks.

**Comment by akramtexas** [comment]
> @tsconn23 The (two) Dockerfiles `edgexfoundry/edgex-go/cmd/security-secrets-setup/Dockerfile` and `edgexfoundry/edgex-go/cmd/security-secretstore-setup/Dockerfile` are not explicitly mentioned in the list of Dockerfiles to update. Would like a confirmation please if this is intentional, thanks.

- Please never mind the above. In chatting with @tingyuz, I have come to understand that the security components have actually _already_ been verified with Go 1.13 (Plus I couldn't think of any reason why the two Dockerfiles for `core-security` should _not_ be updated along with the rest at this time.)
