### ISSUE TITLE
Fail to query readings from RedisDB by value descriptor name and device name

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#2344]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-data

### Is this a regression?

 No

### Description and Minimal Reproduction
1.  Run core-data to use Redis
2. Add readings:
```
curl -H 'Content-Type: application/json' http://localhost:48080/api/v1/reading -d '{"device":"testDevice","name":"val1","value":"10"}'

curl -H 'Content-Type: application/json' http://localhost:48080/api/v1/reading -d '{"device":"testDevice","name":"val2","value":"20"}'
```

3. Query reading by value descriptor name and device name and the error occur at second http request:
```
curl http://localhost:48080/api/v1/reading/name/val1/device/testDevice/1 
[{"id":"191d2c04-db0c-4df2-a89a-3a2fff1c0698","created":1581064189094,"device":"testDevice","name":"val1","value":"10"}]

curl http://localhost:48080/api/v1/reading/name/val2/device/testDevice/1
ERR wrong number of arguments for 'mget' command
```

## 🔥 Exception or Error
<pre><code>
curl http://localhost:48080/api/v1/reading/name/val2/device/testDevice/1
ERR wrong number of arguments for 'mget' command
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
Master branch

**Comment by weichou1229** [comment]
* Error code snippet:
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/data.go#L392
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/queries.go#L157
```
# redis/data.go
func (c *Client) ReadingsByDeviceAndValueDescriptor(deviceId, valueDescriptor string, limit int) (readings []contract.Reading, err error) {
	conn := c.Pool.Get()
	defer conn.Close()

	if limit == 0 {
		return readings, nil
	}

	objects, err := getObjectsByRangeFilter(conn,
		db.ReadingsCollection+":device:"+deviceId,
		db.ReadingsCollection+":name:"+valueDescriptor,
		0, limit-1)
...

# redis/queries
func getObjectsByRangeFilter(conn redis.Conn, key string, filter string, start, end int) (objects [][]byte, err error) {
	ids, err := redis.Values(conn.Do("ZRANGE", key, start, end))
	if err != nil && err != redis.ErrNil {
		return nil, err
	}
```


*  In the Redis DB, it always return the first record when we **set limit as 1**:
```
ZRANGE reading:device:testDevice 0 0
1) "191d2c04-db0c-4df2-a89a-3a2fff1c0698"
```

Actually, the result should include the second record when we query the **val2**:
```
ZRANGE reading:device:testDevice 0 -1
1) "191d2c04-db0c-4df2-a89a-3a2fff1c0698"
2) "12585547-cc1b-45e6-8363-16b58efd5e56"
```

* I recommend using the ZINTERSTORE to query the intersection of **reading:device:testDevice** and **reading:name:val2** like:
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/notifications.go#L203

**Comment by AnthonyMBonafide** [comment]
@tingyuz , @mkbhanda , @michaelestrin 

I want to bring this up as a security issue. As mentioned in this bug report, `edgex-go` is leaking sensitive information(Redis commands and database errors):
```
ERR wrong number of arguments for 'mget' command
```

How should we proceed with this since this probably is present in more places that this and should be handled more generically than just here?

**Comment by michaelestrin** [comment]
Good call out.  Security issue is orthogonal to addressing this issue.  Will ask this be added to the next Security Working Group meeting; perhaps it will be resolved by community discussion before then.

@AnthonyMBonafide
