### ISSUE TITLE
SMA service operations broken in the snap

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#2368]
# 🐞 Bug Report

The default value of the SMA's ExecutorPath changed in configuration.toml between Edinburgh and Fuji, which caused the sed command used to update this value to the executor required in the snap to fail, leaving the default value unchanged.  This results in a failure when issuing start/stop/restart commands to the SMA when running the Fuji snap.

### Affected Services
SMA (sys-mgmt-agent)

The issue is located in: SMA/./configuration.toml & snapcraft.yaml

### Is this a regression?

Yes, the previous version in which this bug was not present was: Edinburgh

### Description and Minimal Reproduction
Install the fuji snap and run the following command (which will return a failure response as the executor is not found):
 
```
edgexfoundry.curl \
    --fail \
    --header "Content-Type: application/json" \
    --request POST \
    --data '{"action":"stop","services":["edgex-core-data"]}' \
    localhost:48090/api/v1/operation

```

## 🔥 Exception or Error
`[{"operation":"stop","service":"edgex-core-data","executor":"unknown","Success":false,"errorMessage":"fork/exec ../sys-mgmt-executor/sys-mgmt-executor: no such file or directory"}]
`

## 🌍  Your Environment
**Deployment Environment:**
snap

**EdgeX Version:**
Fuji

**Comment by michaelestrin** [comment]
@tonyespy did https://github.com/edgexfoundry/edgex-go/pull/2369 address this issue?

**Comment by tonyespy** [comment]
I should have a PR for master shortly. That said, not sure why #2369 didn't auto-close this when it was merged in fuji? Also I *thought* we were taking the approach of opening a new bug for the development release vs. re-using an issue across releases. Maybe that's being handled slightly differently in each WG? Anyways for now I'll go ahead reference this issue in my PR for master.
