### ISSUE TITLE
Unable to GET Core-Command Device Resources

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2375]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-command

### Is this a regression?

 No

### Description and Minimal Reproduction
1. Running services with nightly-build docker-compose-nexus-no-secty.yml
2. Open browser to **GET http://localhost:48082/api/v1/device**

## 🔥 Exception or Error

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/55377716/74523633-6d701600-4f58-11ea-834f-1cf77aa177e6.png">

## 🌍  Your Environment
**Deployment Environment:**
MacOS
**EdgeX Version:**

**Anything else relevant?**
[edgexfoundry/blackbox-testing/issues/387](https://github.com/edgexfoundry/blackbox-testing/issues/387)

**Comment by brandonforster** [comment]
I've investigated this and I believe this was handled by #2370.
