### ISSUE TITLE
Error in metadata when using redis db instead of mongodb

### ISSUE THREAD

**Issue by Nitu-coder** [edgexfoundry/edgex-go#2376]
Hello,

I m trying to use redis db for metadata,coredata and core command for the storing the data instead of mongodb.

Steps to reproduce:
edited the configuration.toml files to use the database type as redis, port 6379 and host as my machine ip 107.108.87.226.
Build the code clean and then run the code 

The issue is located in:  Metadata , when used redis server for database

I have made the changes to the metadata, coredata, core command configuration toml files to use redis database
logs shows that the database is connected succesfully but then i **get server not reachable error.**

Even the device virtual service is giving the following error
msg="DeviceServicForName failed: Get http://107.108.87.226:48081/api/v1/deviceservice/name/device-virtual: EOF"

![Screenshot from 2020-02-14 17-47-37](https://user-images.githubusercontent.com/43419655/74531515-dbb1da00-4f52-11ea-9dc6-ceb4dfa900cb.png)

Attaching the screenshot for the same. Can you please let me knw what is the issue.
?

## 🌍  Your Environment
**Deployment Environment:: ubuntu 16.04
go version: 1.13

**EdgeX Version:latest code

**Anything else relevant?**

**Comment by Nitu-coder** [comment]
@brandonforster Can you please help me in solving this issue. What cld be the reason?? my redis-server is running at my ip 107.108.87.226 and i have made changes to all the configuration toml files with the same host and type as redisdb

**Comment by brandonforster** [comment]
@Nitu-coder I'll take a look when this comes up on my queue. If you need faster support, you should check out the Slack workspace.

**Comment by brandonforster** [comment]
I'm unable to reproduce. The blackbox tests run and pass for device-service using metadata, after running those tests making this request `curl --location --request GET 'http://localhost:48081/api/v1/deviceservice` provides a list of device services, as expected. Taking one of those names returned by that request and making the request `curl --location --request GET 'http://localhost:48081/api/v1/deviceservice/name/test service for core command'` returns just the one device service, as expected.

@Nitu-coder there might be issues with your firewall, your Redis setup, or something else. I'd encourage you to get on the Slack and we can work your issue there, but the EdgeX code doesn't seem to be the problem.

**Comment by brandonforster** [comment]
Oh, I see the problem. You're trying to make the request at your WAN IP, not your LAN IP. Instead of using that IP address, try doing `localhost:48081`, as I am. Hopefully that takes care of your issue!
