### ISSUE TITLE
Snap build fails when using go compiler version 1.13.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#2378]
# 🐞 Bug Report

### Affected Services
Jenkins `snap` builds for `edgex-go`

### Is this a regression?
No: Issue not present with go compiler version 1.12.

Yes: Issue is present on upgrading to go compiler version 1.13.

### Description and Minimal Reproduction
This issue was discovered during the (`snap`) Jenkins builds, `edgex-go-snap-master-verify`, etc. Details here: [PR-2348 (Update Core/Security/Support/SMA Service Dockerfiles for Go 1.13)](https://github.com/edgexfoundry/edgex-go/pull/2348#issuecomment-587032348).

## 🔥 Exception or Error
<pre><code>
15:53:07 go get gopkg.in/matm/v1/gocov-html: unrecognized import path "gopkg.in" (parse https://gopkg.in/?go-get=1: no go-import meta tags ())
15:53:08 GNUmakefile:235: recipe for target 'tools' failed
15:53:08 make: *** [tools] Error 1
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Jenkins runtime (`edgex-go-snap-master-verify`, etc.)

**Comment by tonyespy** [comment]
This was fixed as part of [PR #2426](https://github.com/edgexfoundry/edgex-go/pull/2426).
