### ISSUE TITLE
All microservices should authenticate themselves when using mongo database

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-go#2380]
# 🐞 Bug Report
All microservices should authenticate themselves when using mongo database no matter if they are started up via docker or via snap. Once issue  https://github.com/edgexfoundry/docker-edgex-mongo/issues/77 is fixed (mongo is started with enabled access control), services started up using configuration.toml files that are directly under **/res** directory will got authentication exception when manipulating the database. 
### Affected Services
All microservices that  use mongo database and are run usually locally or via snap
- core-command
- core-data
- core-metadata
- support-logging
- support-notifications
- support-sheduler

 The issue is located in these files: 
- [core-command](https://github.com/edgexfoundry/edgex-go/blob/e5ebbe2778b17324c446436c8bb6947fa319c3bf/cmd/core-command/res/configuration.toml#L35-L43)
- [core-data](https://github.com/edgexfoundry/edgex-go/blob/e5ebbe2778b17324c446436c8bb6947fa319c3bf/cmd/core-data/res/configuration.toml#L41-L49)
- [ core-metadata](https://github.com/edgexfoundry/edgex-go/blob/e5ebbe2778b17324c446436c8bb6947fa319c3bf/cmd/core-metadata/res/configuration.toml#L40-L48)
- [support-logging](https://github.com/edgexfoundry/edgex-go/blob/e5ebbe2778b17324c446436c8bb6947fa319c3bf/cmd/support-logging/res/configuration.toml#L24-L32)
- [support-notifications](https://github.com/edgexfoundry/edgex-go/blob/e5ebbe2778b17324c446436c8bb6947fa319c3bf/cmd/support-notifications/res/configuration.toml#L31-L39)
- [support-scheduler](https://github.com/edgexfoundry/edgex-go/blob/e5ebbe2778b17324c446436c8bb6947fa319c3bf/cmd/support-scheduler/res/configuration.toml#L31-L39)

### Is this a regression?

 -

### Description and Minimal Reproduction
All /edgex-go/cmd/*/res/configuration.toml files have empty `Password` and `Username` filed under [**Databases**]
Example with edgex-go/cmd/metadata/configuration.tolm file 

> [Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'metadata'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'mongodb'

Username and Password files need to be updated accordingly.  

## 🔥 Exception or Error
Currently there is no exception, but once the mongo get started with enabled access control, all microservice will need to authenticate.  
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by bnevis-i** [comment]
@difince What is left to do here?

**Comment by difince** [comment]
The issue was fixed by PR https://github.com/edgexfoundry/edgex-go/pull/2381
