### ISSUE TITLE
Time issue in the starting services sequence could make edgex-mongo to fail

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-go#2383]
# 🐞 Bug Report
It happens edgex-mongo to read `/tmp/edgex/secrets/edgex-mongo/secrets-token.json`
before this file to be created or the content of this file to be updated with the new `token`  by `vault-worker`.
Because of this, `docker-edgex-mongo` could fails with:
 - open /tmp/edgex/secrets/edgex-mongo/secrets-token.json:` no such file or directory exception` if this file does not exists at all or
 - failed to read secret stores data for '/v1/secret/edgex/mongo/notifications' path: Error found on handling secrets from underlying data-store:` Received a '403' response from the secret store`.
(We got 403 exeception because edgex-mongo reads the content of the file written from the previous vaul-worker run)

**edgex-vault-worker** log  looks like this:
```
level=INFO ts=2020-02-14T12:36:47.113384314Z app=edgex-security-file-token-provider source=provider.go:88 msg="generating policy/token defaults for service edgex-mongo"
level=INFO ts=2020-02-14T12:36:47.114688605Z app=edgex-security-file-token-provider source=provider.go:94 msg="using policy/token defaults for service edgex-mongo"
level=INFO ts=2020-02-14T12:36:47.118347602Z app=edgex-security-file-token-provider source=common.go:97 msg="successfully made request to install policy"
level=INFO ts=2020-02-14T12:36:47.125773421Z app=edgex-security-file-token-provider source=common.go:97 msg="successfully made request to create token"
........
```
Part of **edgex-mongo** log :
```
level=ERROR ts=2020-02-14T12:36:57.047005838Z app=edgex-mongo source=config.go:69 msg="failed to read secret stores data for '/v1/secret/edgex/mongo/logging' path: Error found on handling secrets from underlying data-store: Received a '403' response from the secret store"
........
```

The logs shows that there are 10 seconds delay from token creation and the exception in the edgex-mongo ... but edgex-mongo actually reads the token a few milliseconds before vault worker to do its job, then create a request to vault ..and it takes around 10 seconds to get a replay
### Affected Services

 The issue is located in: 

### Is this a regression?

 The issue was not reproduced in Fuji release 

### Description and Minimal Reproduction
execute a few times: 
```
docker-compose up -d
docker down
```
Approximately one of the three attempts fails, but another retry fix the situation. 
## 🔥 Exception or Error
Possible exceptions in docker-edgex-mongo: 
<pre><code>
 - open /tmp/edgex/secrets/edgex-mongo/secrets-token.json:` no such file or directory exception` if this file does not exists at all or
 - failed to read secret stores data for '/v1/secret/edgex/mongo/notifications' path: Error found on handling secrets from underlying data-store:` Received a '403' response from the secret store`.

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Services started in containerized environment - via docker-compose file.  

**EdgeX Version:** 

**Anything else relevant?**

**Comment by bnevis-i** [comment]
Related issue: #2383 (existing health check doesn't really detect when security-secretstore-setup is done-done)

**Comment by bnevis-i** [comment]
## Testing instructions

Check out related fix branches in edgex-go, docker-edgex-consul, and developer-scripts and build the containers locally.  Make the following change to  the docker-compose file and test for the race condition:

```
diff --git a/releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml b/releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
index 36a4814..6d2663e 100644
--- a/releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
+++ b/releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
@@ -52,12 +52,15 @@ services:
       - consul-data:/consul/data:z
 
   consul:
-    image: nexus3.edgexfoundry.org:10004/docker-edgex-consul:master
+    image: edgexfoundry/docker-edgex-consul:0.0.0
+    #image: nexus3.edgexfoundry.org:10004/docker-edgex-consul:master
     ports:
       - "8400:8400"
       - "8500:8500"
     container_name: edgex-core-consul
     hostname: edgex-core-consul
+    environment:
+      - "SECRETSTORE_SETUP_DONE_FLAG=/tmp/edgex/secrets/edgex-consul/.secretstore-setup-done"
     networks:
       edgex-network:
         aliases:
@@ -66,8 +69,8 @@ services:
       - consul-config:/consul/config:z
       - consul-data:/consul/data:z
       - consul-scripts:/consul/scripts:z
-      - vault-config:/vault/config:ro,z
       - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
+      - /tmp/edgex/secrets/edgex-consul:/tmp/edgex/secrets/edgex-consul:ro,z
       - /tmp/edgex/secrets/edgex-vault:/tmp/edgex/secrets/edgex-vault:ro,z
       - /tmp/edgex/secrets/edgex-kong:/tmp/edgex/secrets/edgex-kong:ro,z
     depends_on:
@@ -134,9 +137,12 @@ services:
       - volume
 
   vault-worker:
-    image: nexus3.edgexfoundry.org:10004/docker-edgex-security-secretstore-setup-go:master
+    image: edgexfoundry/docker-edgex-security-secretstore-setup-go:master-dev
+    #image: nexus3.edgexfoundry.org:10004/docker-edgex-security-secretstore-setup-go:master
     container_name: edgex-vault-worker
     hostname: edgex-vault-worker
+    environment:
+      - "SECRETSTORE_SETUP_DONE_FLAG=/tmp/edgex/secrets/edgex-consul/.secretstore-setup-done"
     networks:
       edgex-network:
         aliases:
```

**Comment by bnevis-i** [comment]
@difince I am having trouble testing this due to the race condition.  However, I have made a set of changes that I believe resolves the issue.  Could you please validate?

**Comment by difince** [comment]
Wednesday I am getting back .. and I will validate it

**Comment by difince** [comment]
It figured out that I will be back Thursday, not Wednesday

**Comment by difince** [comment]
The Issue was validated against the three PRs @bnevis-i have been created.
