### ISSUE TITLE
Race condition when starting containers

### ISSUE THREAD

**Issue by anubhavs9** [edgexfoundry/edgex-go#2404]
# 🐞 Bug Report

### Affected Services
 
 The issue is located in: Vault / other services

### Is this a regression?

 No

### Description and Minimal Reproduction
Using Fuji docker-compose file.
**wget -O docker-compose.yml \
https://raw.githubusercontent.com/edgexfoundry/developer-scripts/master/releases/fuji/compose-files/docker-compose-fuji.yml**

Starting the services-
**docker-compose up -d**

Few containers like core-data/metadata/logging/scheduler exits after retrying. 

On restarting the failed containers, it works properly.
**docker-compose up -d <failed-container-name>**

I suspect there is some race condition, and the secrets are not seeded into the vault, and these services try to retrieve it. 

Tried below commands still same issue-
 **docker-compose down -v**
**docker volume prune**

## 🔥 Exception or Error
<pre><code>
 

Failed support-logging container log-

level=INFO ts=2020-02-25T06:24:23.299549866Z app=edgex-support-logging source=registry.go:144 msg="Writeable configuration has been updated from the Registry"
level=WARN ts=2020-02-25T06:24:23.839073058Z app=edgex-support-logging source=init.go:93 msg="couldn't create database client: server returned error on SASL authentication step: Authentication failed."

Failed core-data container log (similar for other failed services)-

Post http://edgex-support-logging:48061/api/v1/logs: dial tcp 172.20.0.11:48061: connect: connection refused
level=WARN ts=2020-02-25T06:24:35.045741357Z app=edgex-core-data source=database.go:125 msg="couldn't create database client: server returned error on SASL authentication step: Authentication failed."
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 16.04
Docker version 19.03.6
**EdgeX Version:**
v1.1.0 - Fuji

**Anything else relevant?**
Sometimes all the containers starts properly but most of the times few containers exits after retying.

![container-error-auth](https://user-images.githubusercontent.com/61422585/75223340-3b6a7980-57cc-11ea-9b8a-83603794324b.png)
![random-containers-exiting](https://user-images.githubusercontent.com/61422585/75223342-3d343d00-57cc-11ea-9c14-78af3cd37a3d.png)

**Comment by bnevis-i** [comment]
See https://github.com/edgexfoundry/developer-scripts/issues/230 for related issue expected to be fixed in Geneva (in this issue, not only is the above true, but the dependent services are starting even before the secrets token has been written).  In the above cause, services are using the root token, but the DB passwords have not yet been provisioned.

**Comment by bnevis-i** [comment]
@anubhavs9 

Please validate with a docker-compose pull   and a docker-compose up -d  to verify the race has been elimianted.
