### ISSUE TITLE
Add /etc/nsswitch.conf to run EdgeX Foundry on Kubernetes.

### ISSUE THREAD

**Issue by kurokobo** [edgexfoundry/edgex-go#2405]
# 🚀 Feature Request

### Relevant Package

This feature request is for containerized microservices which contain web server using `github.com/edgexfoundry/go-mod-bootstrap/bootstrap/handlers/httpserver`.

### Description

I tried to run EdgeX Foundry on Kubernetes but there was an issue.
My repository is [here](https://github.com/kurokobo/edgex-on-kubernetes), I was using Fuji release on Kubernetes 1.16.3.

If we write a manifest without special consideration, the web servers in the containers stop immediately after its start.
Because of this, all API calls from other microservices and all health checks from consul will fail.

This is the logs from `edgex-support-logging` for example.

```
$ kubectl logs edgex-support-logging-66fc4f6c98-28bk4
...
level=INFO ts=2020-02-25T12:47:50.622662811Z app=edgex-support-logging source=httpserver.go:72 msg="Web server starting (edgex-support-logging:48061)"
level=INFO ts=2020-02-25T12:47:50.624106767Z app=edgex-support-logging source=httpserver.go:80 msg="Web server stopped"
```

This issue will occur any of microservices in the `edgex-go` repository like `edgex-core-command`, `edgex-core-data`, and so on because:

* The web server tries to start an http listener on `<hostname>:<port>` like `edgex-support-logging:48061`.
* This `<hostname>` has to be resolved to an IP address. In this case, the `<hostname>` must be resolved to the IP address of the `Pod`.
* By default, `/etc/hosts` file in the container contains a correct pair of IP address and hostname of the Pod.
* However, there is no `/etc/nsswitch.conf` in the container because the base image of this container is `scratch` or `alpine`.
* The default resolvers of Golang ignore `/etc/hosts` file if `/etc/nsswitch.conf` does not exist.
* Because of this, the `<hostname>` are resolved to one of `ClusterIP` incorrectly by the Kubernetes default name resolution mechanism.
* The `ClusterIP` is not visible to processes in the container. The process can't start a listener on the specified `<hostname>` and then stopped.

The root cause of this behavior is golang/go#35305.

### Describe the solution you'd like

I'd like to place `/etc/nsswitch.conf` which contains `hosts: files dns` in the container images.
To do this, I'd like to add following line to `Dockerfile`
```
RUN echo "hosts: files dns" > /etc/nsswitch.conf
```

### Describe alternatives you've considered

There are some alternative workarounds to avoid this issue. But considering the side effects, I think these are difficult to adopt.

* Specify `GODEBUG` environment variable with the value `netdns=cgo`. This force to use the CGO resolver which refers `/etc/hosts` instead of the pure Go resolver. This is the easiest way so I use this workaround in [my repository](https://github.com/kurokobo/edgex-on-kubernetes).
* Modify the values to `0.0.0.0` for all of `/edgex/core/1.0/*/Service/Host` in your Consul service before we start other microservices.
* Do nothing. According to golang/go#35305, the behavior of pure Go resolver will change in the future release of Go 1.15 to refer `/etc/hosts` regardless `/etc/nsswitch.conf` exists or not.

**Comment by michaelestrin** [comment]
This is a known issue.  EdgeX does not currently explicitly support HA environments.  Environment variable override support was implemented to help address this.  See examples in https://github.com/edgexfoundry-holding/edgex-kubernetes-support; specifically around https://github.com/edgexfoundry-holding/edgex-kubernetes-support/blob/b2e44effe5ce247f70abf9833e922108345ccb28/releases/nightly-build/helm/nightly-build-no-security/templates/edgex-config-seed.yaml#L17.

**Comment by kurokobo** [comment]
@michaelestrin 
Thank you for your comment.

Of course, I know that EdgeX does not currently explicitly support HA environments. I tried this just for my home lab.
So it's OK to close this issue, but I'm writing some additional information for future investigation.

I'm sorry I couldn't convey it well, but I think this issue could not resolved by environment variable overriding.
The same issue has occurred with manifests in `edgex-kubernetes-support`. The web server in the containers does not start correctly.

```sh
$ git clone https://github.com/edgexfoundry-holding/edgex-kubernetes-support.git
$ cd releases/nightly-build/kubernetes/
$ kubectl create -k .
...
$ kubectl exec -it edgex-export-distro-6dd9b869bf-n7rph cat /etc/hosts
...
100.97.250.218  edgex-export-distro-6dd9b869bf-n7rph

$ kubectl logs pod/edgex-export-distro-6dd9b869bf-n7rph <----- ** WRONG HOSTNAME **
...
level=INFO ts=2020-03-01T03:48:00.286387706Z ... msg="Web server starting (edgex-export-distro:48070)"
...
level=INFO ts=2020-03-01T03:48:00.288806083Z ... msg="Web server stopped" <----- ** STOPPED **
```

I think the root cause is not that what the hostname is, but what IP address is resolved from its hostname.
`/etc/hosts` is configured correctly if we add `hostname` in its manifest, but this issue still exists because `/etc/hosts` is not used for name resolution by the issue golang/go#35305.

```sh
$ git diff
...
     spec:
+      hostname: edgex-export-distro <----- ** ADD THIS **
       containers:
...

$ kubectl create -k .
...
$ kubectl exec -it edgex-export-distro-69cb579ff6-kgwbz cat /etc/hosts
...
100.97.250.254  edgex-export-distro <----- ** HOSTNAME FIXED **

$ kubectl logs pod/edgex-export-distro-69cb579ff6-kgwbz
...
level=INFO ts=2020-03-01T04:46:51.617720434Z ... msg="Web server starting (edgex-export-distro:48070)"
...
level=INFO ts=2020-03-01T04:46:51.618942565Z ... msg="Web server stopped" <----- ** BUT STOPPED **
```

So I think I have to add `nsswitch.conf` or add `GODEBUG` to make `/etc/hosts` used correctly.

```sh
$ git diff
...
     spec:
+      hostname: edgex-export-distro
       containers:
         - name: edgex-export-distro
+          env: <----- ** ADD THIS **
+          - name: GODEBUG <----- ** ADD THIS **
+            value: netdns=cgo <----- ** ADD THIS **
           image: nexus3.edgexfoundry.org:10004/docker-export-distro-go:1.1.0

$ kubectl create -k .
...
$ kubectl exec -it edgex-export-distro-66dd8dd84b-98kcv cat /etc/hosts
...
100.97.250.208  edgex-export-distro

$ kubectl logs pod/edgex-export-distro-66dd8dd84b-98kcv
...
level=INFO ts=2020-03-01T05:01:03.360256019Z ...msg="Web server starting (edgex-export-distro:48070)" <----- ** IT WORKS **
```

**Comment by michaelestrin** [comment]
Manifest support is contrived; see https://github.com/edgexfoundry-holding/edgex-kubernetes-support/tree/master/releases/nightly-build/kubernetes.  This is explicitly called out in the repository's /README.md:

> These manifest files work because they name containers using the same names found in the default configuration files built into the Docker images. If you modify the container names in the manifest file, individual services will no longer be able to connect to one another. 

Further, specific host names are assumed (e.g. consul.k8s, command.k8s, data.k8s, etc.).  /releases/nightly-build/kubernetes/README.md includes a step to configure your local naming service:

>Update host machine's hosts file to map HOSTS domain to ADDRESS.

The Helm chart implementation is not contrived.  It specifically names ingress, service, and deployments to include the Helm release name.   The appropriate service names are overridden (via environment variables) in templates/edgex-config-seed.yaml to point at the uniquely named deployment.  **If you want to experiment, I'd recommend using the Helm chart implementation.**

Finally, edgexfoundry-holding/edgex-kubernetes-support is not a community-supported repository.  It currently supports neither the [current Fuji release](https://github.com/edgexfoundry-holding/edgex-kubernetes-support/issues/1) nor the [Geneva release's work-in-progress master branch](https://github.com/edgexfoundry-holding/edgex-kubernetes-support/issues/2).

@kurokobo
