### ISSUE TITLE
Device Provisioning in metadata needs security mechanism to verify if the request is legit when adding/updating devices 

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#2415]
In device provisioning in metadata, anyone can send request to add or update a device without verification. A mechanism is needed to verify such request. 
There are two parts required when developing such mechanism:
1. The request needs to be legit, e,g, coming from a trusted source or can be verified if it is from a trusted source
2. The request needs to include information if the device is trusted.e,g, not every device can be added.  a possible example is: only devices with profile defined in the device database can be accepted and added.

**Comment by hutchic** [comment]
closed as this will be addressed in the future as part of overall api security strategy?
