### ISSUE TITLE
EdgeX microservices are too tightly coupled to configuration

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2420]
### Background

The EdgeX middleware strives to be flexible with regard to deployment scenarios, such as:

- Deployment as standard OS processes
- Deployment into snaps
- Deployment into OCI container infrastructures (such as Docker, Docker Swarm, K3S, microK8S)
- Deployment using only static configuration (Consul-less)
- Deployment with dynamic configuration / registry support (Consul)
- Deployment with security services enabled (Vault + Consul)
- Deployment with MongoDB database backend
- Deployment with a Redis database backend
- Deployment on a variety of processor architectures

In order to make developers' lives easier, certain of these configurations have been pre-selected:

- Security-services enabled on both aarch64 and x86_64
- No-security on both aarch64 and x86_64
- MongoDB and Redis-based versions of the above

Additionally, certain adaptations have been made in the developer infrastructure to make it easy to bring up a functional stack:

- Each microservice includes a static TOML configuration (one for Docker, one for non-Docker) that provides service location and service configuration information such as
  * Address and port numbers of dependent services
  * Database connection and authentication information
  * Other configuration data
- The static configuration is automatically mirrored (one-time) into a Consul configuration registry
- Special processes that seed database schemas for EdgeX services and 3rd party components such as Kong
- When security services are enabled, the following additional bootstrapping services are performed
  * Seeding of a on-device PKI
  * Initialization and seeding of an on-device secret store
  * Seeding of database passwords

The above configuration is spread across the developer-scripts repository as well as in configuration files and code inside of edgex-go and other repositories.

### Problem statement

**Specific problem:**

The security-enabled MongoDB developer-scripts and blackbox tests will not run properly because the Docker configuration TOML files have been changed to reference Redis: the TOML configuration is inside of the containers, while the database that is running is encoded in the docker-compose script where it is easily changed.  (However, on a setting by setting basis, environment variables can be used to override the TOML.  For example: `Databases_Primary_Type=redisdb`.

**General problem:**

Configuration is too tightly-coupled to microservices containers, making it very difficult to test all the supported configurations.  It is also then difficult for downstream consumers of EdgeX to create custom configurations that better match their use cases.

The initialization overhead--particularly to enable security features--is becoming increasingly awkward because there is no "docker-compose install" command.  This leads to a pre-disposition to configure as much as possible statically in upstream EdgeX.  Additionally, in the registry-enabled flows, service location information changes from a state where it is encoded in relatively-immunitable configuration files, to a service that is currently configured without authentication/authorization nor integrity protection.

### Desired solution attributes

On the supposition that most of the EdgeX framework's value lies in the microservices themselves and their APIs, I would like to advocate for the following changes:

- That configuration information be externalized such that downstream consumers--such as blackbox-testing--can inject their own configuration (such as security/non-security, redis/mongo, consul/no-consul) independent of modifying the "source code."

- The Docker environment should behave more like the snap environment in that:
  * There is a separate initialization phase to lay down configuration, preconfigure database schemas and users, and other basic setup.
  * Reduce the amount of coordination required at runtime to ensure just-in-time execution of setup hooks.
  * The runtime services configuration is managed separately from the setup configuration.
  * Ensures that the base services are set up in a default-secure configuration.

**Comment by bnevis-i** [comment]
@andresrinivasan I would like to get your feedback as to whether you think I am going after the right problem here in context of the Redis integration.

**Comment by michaelestrin** [comment]
Kudos for this work @bnevis-i!  

Once refined, this is a topic that should be raised and discussed in a Core WG meeting.  

@tsconn23, @tingyuz  for visibility.

**Comment by andresrinivasan** [comment]
> @andresrinivasan I would like to get your feedback as to whether you think I am going after the right problem here in context of the Redis integration.

Yes, this is the right problem to go after and written very nicely. This immediately bumps into current implementation challenges with the blackbox testing scripts. In other words solving this high level problem will require a rethink of the test scripts.

**Comment by tsconn23** [comment]
@cloudxxx8 For visibility from Test/QA

**Comment by bnevis-i** [comment]
Can't recreate my train of thought on where I was intending this to go.  A lot has changed since this has been written.  Closing.
