### ISSUE TITLE
Update config.Clients usage for new naming scheme

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2424]
Clients in configuration were renamed in https://github.com/edgexfoundry/edgex-go/pull/2401.  References to usage with hardcoded service names (e.g. `configuration.Clients["Logging"]`, etc.) were not updated. 

Suggest implementation replace string literal with centrally defined constant.

**Comment by michaelestrin** [comment]
Placed on hold pending resolution of path forward per March 5, 2020 Core WG call.

**Comment by michaelestrin** [comment]
Closed per conversation with Trevor and decision to revert https://github.com/edgexfoundry/edgex-go/pull/2401 and defer root issue for post-Geneva implementation.

**Comment by lenny-intel** [comment]
Reopening this issue to put in ice box to be addressed when for V2.0.0.

**Comment by jpwhitemn** [comment]
Per the Monthly Architect's meeting of 1/26/21 - it was decided that 
We will use service keys in configuration.toml files 
Service keys are defined in https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go

This issue, while somewhat orthogonal, is also related to https://github.com/edgexfoundry/go-mod-core-contracts/issues/449
Therefore, further changes or address of issues will be done per issue 449.
