### ISSUE TITLE
Update the version number of V1 Swagger files

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2436]
# 🚀 Feature Request

### Relevant Package
This feature request is for API documents

### Description
We should keep v1.1.0 for Fuji release and set the version to v1.2.0 for Geneva in the Swagger files.

### Describe the solution you'd like
Update all the V1 Swagger files to v1.2.0

**Comment by AnthonyMBonafide** [comment]
Closed via PR #2437
