### ISSUE TITLE
Updating device profile cannot callback to device service

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/edgex-go#2442]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Metadata

### Is this a regression?
No

### Description and Minimal Reproduction
the update device profile API cannot trigger the DS callback correctly. First you need to delete all associated devices and provisionwatchers otherwise it'll return below error. After this you can successfully update the device profile on metadata, however the device service callback is not triggered (did not receive the request)

## 🔥 Exception or Error
<pre><code>
device profile invalid state -- id: '' name: 'Simple-Device' description: '1 devices are associated with the device profile'
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
macOS

**EdgeX Version:**
master-branch

**Anything else relevant?**
https://github.com/edgexfoundry/edgex-go/blob/01e4977c5a51f2ff55c1e3b26886d77859458597/internal/core/metadata/rest_deviceprofile.go#L592-L602
I think the reason is because the associated devices need to be deleted first, it doesn't know which device service need to be notified.

**Comment by hahattan** [comment]
We received many requirement to want to be able to update device profile at runtime.
Currently just remove the device and provisionwatcher checking code world work
https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/metadata/operators/device_profile/update.go#L44-L46

@brandonforster is this solution acceptable ?

**Comment by brandonforster** [comment]
@hahattan I'm not sure, I don't have the context to make an informed answer. I'll take a look at this today or tomorrow and take a look at the implications of that change and let you know, but at first glance this doesn't seem unreasonable.

**Comment by brandonforster** [comment]
@hahattan Sorry for the delay. I don't think what you've proposed is the right way to go; this will mean that we allow updating a device profile while it still has devices associated to it.

I think what we should do is investigate why the callback is not being triggered on update.

**Comment by hahattan** [comment]
I think the reason is that it doesn't know which device service it need to notify/callback to:
https://github.com/edgexfoundry/edgex-go/blob/acc4df9fb78c0d0906fa2020a3cf6a0055e98e35/internal/core/metadata/rest_deviceprofile.go#L602
the first parameter would be an empty slice if we delete all the associated devices.
So I was wondering whether we can ignore the checking part, or is there any other way to retrieve DS that had device using the updated device profile .

**Comment by cloudxxx8** [comment]
@brandonforster we opened this issue because we have multiple customers really need to update profile at runtime when the device is running.
Some protocol allow the device resource dynamically change at run time.

**Comment by cloudxxx8** [comment]
I thought it would be the responsibility of the individual Device Service to make sure Devices run smoothly when the profile is updated.  Core Metadata should not block the update.

**Comment by AnthonyMBonafide** [comment]
@cloudxxx8 , @hahattan , @brandonforster 

This seems like a reasonable request, and I think this has come up in the past. I wonder if this is something we should bring up at the next Core WG Call(April 2nd) and discuss. The reason I would like a little discussion around this is that this may affect other parts of the system and may break backwards comparability for reasons that are not immediately clear. The other part I would like to discuss is if this should go into the Geneva or Hanoi release if there are cascading changes that need to take place to support this change. Any thoughts @tsconn23? Is this a good idea and/or has this issue been discussed in the past?

**Comment by cloudxxx8** [comment]
It should not break the backward compatibility, because it still allows the original behavior- "removing all associated device before updating profile".

**Comment by AnthonyMBonafide** [comment]
@cloudxxx8 , agreed. However, the logic was explicitly put in place. Which to me means that at some point someone made a architectural decision to not allow this feature. While I agree that it seems like a good feature to have, and the changes seem to be pretty straight forward. I want to ensure this was not originally done for some reason that is not immediately clear.

**Comment by tsconn23** [comment]
To my knowledge this is an explicit design choice. There is no mechanism in the Device Service to reconcile devices to an updated device profile and I personally am not signing up to support this as an extra requirement three weeks before freeze on the Geneva release.

**Comment by cloudxxx8** [comment]
It seems this restriction doesn't exist in Edinburgh.
https://github.com/edgexfoundry/edgex-go/blob/edinburgh/internal/core/metadata/rest_deviceprofile.go#L114-L123

We would try to get the user to use Edinburgh release to work around this issue for now.

**Comment by hahattan** [comment]
Verified the issue no longer exists in v2.
