### ISSUE TITLE
Make Redis default for secured deployment of EdgeX

### ISSUE THREAD

**Issue by andresrinivasan** [edgexfoundry/edgex-go#2449]
# 🚀 Feature Request

### Relevant Package

 Redis

This is part of #2270 

### Description
 
Add hooks to support secure EdgeX deployment with Redis

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by andresrinivasan** [comment]
Please assign to @andresrinivasan

**Comment by bnevis-i** [comment]
There are no further outstanding PR's/tickets for redis integration. Closing for now; reopen if closing in error.
