### ISSUE TITLE
Security Policy features of GitHub broken by current content of SECURITY.md

### ISSUE THREAD

**Issue by x448** [edgexfoundry/edgex-go#2452]
# 📚 Docs or Wiki Bug Report

### Description

Two GitHub features related to Security Policy are broken by the current content of SECURITY.md:

* __Security -> Policy__ is broken because it displays features rather than security policy

* __New Issue -> View Policy__ is broken because it displays features rather than security policy

## 🔬 Minimal Reproduction

Problem 1: Click on Security tab and then click Policy (see screenshot).

Problem 2: Click on New Issue and then click View Policy button.

### What's the affected URL?

https://github.com/edgexfoundry/edgex-go/security/policy

### Expected vs Actual Behavior

Expected: text about security policy.

Actual: text about software features

## 📷Screenshot 

On the top, the "Security" tab is active.  On the left, the "Policy" section is active.  
However, content shows features instead of security policy.

![image](https://user-images.githubusercontent.com/57072051/77503194-08e38900-6e2b-11ea-8d43-669e0aa6f994.png)

**Comment by bnevis-i** [comment]
This ticket was discussed on the 2020-06-10 security WG.  (https://wiki.edgexfoundry.org/display/FA/Security+Working+Group).

**Comment by hutchic** [comment]
link `SECURITY.md` to https://wiki.edgexfoundry.org/display/FA/Security#Security-ReportingASecurityIssue
