### ISSUE TITLE
REST endpoints do not gracefully handle request timeout configured by bootstrap

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/edgex-go#2462]
# 🐞 Bug Report

### Affected Services
This issue was noticed by working #2421. The underlying problem in that issue is that work behind the scenes is taking longer than the configured timeout in bootstrap, and this timeout is not handled in any way. Currently, this manifests as all the business logic "work" returning their proper values, coming down to the JSON encoder, and the JSON encoding failing because the HTTPResponseWriter timed out.

This does not produce any useful error message and does not provide any meaningful logging in any service.

### Is this a regression?

No, this has never worked well.

### Description and Minimal Reproduction

In any REST endpoint that encodes a result to JSON (most GET endpoints do this) add a call to `time.Sleep(time.Second*30)` at any point before the final lines of `json.Encode(...)` and passing the OK status back.

## 🔥 Exception or Error
The error from the `json.Encode(...)` call on core-command's get all devices endpoint:
`write tcp 127.0.0.1:48082->127.0.0.1:52314: i/o timeout`

The error returned to the user when this error occurs:
`curl: (52) Empty reply from server`

## 🌍  Your Environment
**Deployment Environment:** all environments

**EdgeX Version:** all versions

**Anything else relevant?**

this is very bad

**Comment by JamesKButcher** [comment]
@cloudxxx8 Is this an issue in V2?

**Comment by cloudxxx8** [comment]
It might still be an issue in V2, so we need to spend time making a try.

**Comment by weichou1229** [comment]
This issue was fixed by https://github.com/edgexfoundry/go-mod-bootstrap/pull/267
