### ISSUE TITLE
Design defect in EdgeX secret store paths

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2465]
# 🐞 Bug Report

### Affected Services
All services that use the EdgeX secret store

### Is this a regression?
No.

### Description and Minimal Reproduction
The EdgeX secret store is often accessed via a path of the form

```
/v1/secret/path/to/secret
```

However, this is a design defect
- `/v1` is the API version of the Vault server
- `/secret/` is a configuration value what relates to where the KV secret store was mounted in Vault; /secret is the default, but any number of KV secrets engines can be mounted with arbitrary names
- `path/to/secret` **is the actual location in the secret store for a secret**

This is a design defect that was present in the initial secret store implementation that we have been carrying forward and should be fixed.  We should not be including any `v1/secret` path information when specifying secret locations in configuration files.

**Comment by bnevis-i** [comment]
Pull into Ireland backlog since this is a breaking change but useful cleanup.

**Comment by jim-wang-intel** [comment]
This story is done via both merged `go-mod-bootstrap` PR  https://github.com/edgexfoundry/go-mod-bootstrap/commit/fd895b2ae1c1da34a8bd42f15a688467eb0c2cf1  and `edgex-go` PR https://github.com/edgexfoundry/edgex-go/commit/4dd80814185d38ae6b349cd8e9b4c72539c96da6
