### ISSUE TITLE
Slack link is invalid in README.md

### ISSUE THREAD

**Issue by dthomastx** [edgexfoundry/edgex-go#2468]
# 📚 Docs or Wiki Bug Report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://docs.edgexfoundry.org/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

Is there an active slack workspace?

**Comment by AnthonyMBonafide** [comment]
@dave93cab , can you provide a specific link where the documentation is incorrect?

**Comment by bnevis-i** [comment]
Looks like this invite link is dead <https://join.slack.com/t/edgexfoundry/shared_invite/enQtNDgyODM5ODUyODY0LWVhY2VmOTcyOWY2NjZhOWJjOGI1YzQ2NzYzZmIxYzAzN2IzYzY0NTVmMWZhZjNkMjVmODNiZGZmYTkzZDE3MTA>
