### ISSUE TITLE
edgex-proxy requires valid secret store token to add Kong users

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2477]
# 🐞 Bug Report

### Affected Services
edgex-proxy

### Is this a regression?
Yes

### Description and Minimal Reproduction
```
docker-compose -f docker-compose-nexus-mongo.yml run --rm --entrypoint /edgex/security-proxy-setup edgex-proxy --init=false --useradd=geneva --group=admin
```

The above command will fail if it is issued an hour after docker-compose up is specified.  This is because edgex-proxy requires the secretstore token to initialize Kong.  However, the token is not needed to add a new Kong user. 

The useradd/userdel functionality should be ideally split out into a separate utility.... Maybe even just a shell scripts?

## 🔥 Exception or Error
<pre><code>
level=INFO ts=2020-04-08T14:52:20.567806821Z app=edgex-security-proxy-setup source=secret.go:73 msg="Attempting to create secretclient"
level=WARN ts=2020-04-08T14:52:20.6463629Z app=edgex-security-proxy-setup source=secret.go:82 msg="Retryable failure while creating SecretClient: HTTP response with status code 403, message: failed to lookup token"
level=ERROR ts=2020-04-08T14:52:21.680325849Z app=edgex-security-proxy-setup source=secret.go:87 msg="unable to create SecretClient: HTTP response with status code 403, message: failed to lookup token"
</code></pre>

**EdgeX Version:**
Geneva

**Comment by tonyespy** [comment]
@bnevis-i So after the hour has expired game over or is there someway to trigger a reset so that a kong user can be still be added? Does it require bringing things down, and starting over again from scratch?

**Comment by bnevis-i** [comment]
Workaround is

```
docker stop edgex-vault-worker
docker start edgex-vault-worker
```

The system may survive without having to stop and start the rest of the microservices, but it is somewhat traumatic as it will revoke all the old secret store tokens and issue new ones.

**Comment by tonyespy** [comment]
@bnevis-i I assume rebooting the system, or just all of EdgeX would also accomplish the same end result?

**Comment by bnevis-i** [comment]
@tonyespy rebooting will have the same effect.

**Comment by hutchic** [comment]
pending some security adr's to wrap up before continuing
