### ISSUE TITLE
Update Services to Disable Remote Logging

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#2479]
# 🚀 Feature Request

### Relevant Package

 All core and supporting services

### Description
Update the core and supporting services to avoid using remote logging and only support standard out by default.

### Describe the solution you'd like
Service's configuration to not use remote logging. This can be done by updating the service's configuration `logging` section to something like:
```toml
[Logging]
EnableRemote = false
File = ''
```

We may be able to do this by removing the `Logging` section completely which would allow us to comment the section out with a comment. Just a thought.

### Describe alternatives you've considered
N\A

**Comment by lenny-intel** [comment]
@AnthonyMBonafide , I suggest leaving the Logging section in and adding this comment
```
# Remote and file logging disabled so only stdout logging is used
[Logging]
EnableRemote = false
File = ''
```
