### ISSUE TITLE
SMA continually generates logs errors if support-* services are not running

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#2486]
# 🐞 Bug Report

### Affected Services
The issue is located in: sys-mgmt-agent

### Is this a regression?
Not sure...

### Description and Minimal Reproduction
**docker**: edit one the nightly-built docker-compose and comment out one of the support services (e.g. support-logging; which will actually be commented out in the release docker-compose* files for Geneva). Start up EdgeX with a docker-compose up command, and wait for everything to come up. The following log message will be generated every ~15s:

`edgex-sys-mgmt-agent | unable to get service endpoint for edgex-support-logging: no matching service endpoint found`

**snap**: install the snap from latest/edgex (on a system w/snap support):
 * sudo snap install edgexfoundry
 * snap services edgexfoundry | grep support
Notice that by default, all the support-* services are disabled.
 * sudo snap logs edgexfoundry -f

watch the following log messages get output every ~15s:
```
sys-mgmt-agent[28503]: unable to get service endpoint for edgex-support-notifications: no matching service endpoint found
sys-mgmt-agent[28503]: unable to get service endpoint for edgex-support-scheduler: no matching service endpoint found
sys-mgmt-agent[28503]: unable to get service endpoint for edgex-support-logging: no matching service endpoint found
```
## 🌍  Your Environment
**Deployment Environment:**
docker or snap

**EdgeX Version:**
EdgeX built from latest master branch (i.e. nightly build as of Apr 10 '20)

**Anything else relevant?**
Please see the related issue #1662.

First, I disagree with the initial statement in that issue that states all of the support-* services should be considered always available to any EdgeX instance. AFAIK, neither support-scheduler nor support-notifications are used by any of the internal EdgeX services by default, so it doesn't make sense to require that they're always running. If an EdgeX instance actually requires them, then they should be enabled, otherwise they're just burning compute cycles... 

Also I'm not sure why the registry isn't being used to determine what services are available? Are these checks from the SMA considered health checks? If so, aren't they duplicating the Consul's health checks?

**Comment by tsconn23** [comment]
This isn't a bug. It's working as designed up to the current point. The message you're seeing is coming from the endpoint monitor which is bootstrapped at service start time. The monitor attempts to reconnect with the service it's been instructed to contact at a configurable interval (15 seconds by default). The monitor in the SMA is being instructed to include the support services by the following list of default services.

https://github.com/edgexfoundry/edgex-go/blob/91d8043a7d7fbd27b880d1c7780a34edbe1cbbd2/internal/pkg/config/types.go#L25

It obtains the information for where each service is located from Consul if started with the `-r / --registry` flag otherwise it goes to the local config.

The monitor is implementing a retry in order to restore connectivity if a service were to go down and come back up.

If you want to change the list of what are considered default services, that's fine. But it's more of a requirements gathering exercise than a bug.

**Comment by tonyespy** [comment]
I think it's worth more discussion. What you're saying is that we effectively have two parallel health check mechanisms, one implemented by the Consul, and one by the SMA. It just seems to me that if our support services are considered optional, continually trying to ping them every 15s, when in fact they may have been disabled on purpose, means we're just burning CPU and IO for no reason...

**Comment by michaelestrin** [comment]
Reviewed the code.  

When you deploy with Consul, there are two health checks.  The SMA check works regardless of whether or not you deploy Consul.  I believe it also predates the Consul check.  

Regarding support services, the SMA's architecture and implementation is polling-oriented.  Further, the [issue](https://github.com/edgexfoundry/edgex-go/issues/1662) to remove the default service list in favor of shifting to a completely configuration-driven service list was torpedoed for Geneva.

I'll add this issue to the upcoming System Management Working Group meeting on 4/17/2020 for discussion.  From my perspective, this functionality works as designed and I'm not sure specifically what you would have change.

@tonyespy

**Comment by tonyespy** [comment]
Thanks for taking a look @michaelestrin. It's unfortunate that the config based service list was axed for Geneva. I guess we'll re-raise this once more for Hanoi planning and maybe we can fix it then...

**Comment by tonyespy** [comment]
@jpwhitemn I want to make sure this is on your radar as a potential topic for the next architects' meeting.

**Comment by tsconn23** [comment]
Discussed Core WG 16-Apr-2020 -- Agreement that we should revise this mechanism in Hanoi. We should avoid polling services that are known ahead of time to not be running. Increased emphasis on support services as optional.

**Comment by jpwhitemn** [comment]
This really stems from the fact that the SMA does not have a dynamic list of services it tracks based on what is registered and/or what is running.  It is hard coded into the SMA.  This is the real issue that needs to be fixed.  Thanks @tonyespy and @michaelestrin for raising the awareness.

**Comment by AlexCuse** [comment]
I am wondering if it would be sufficient to filter out any 'default' services that aren't found with a consul lookup **if** the registry is enabled?  This would be enough for my needs anyway, maybe a configurable blacklist could maybe be offered for environments not using the registry?

I may be able to carve out some time to work on this if it seems like a viable solution.

**Comment by jpwhitemn** [comment]
@AlexCuse - sorry for the delay in response.  I think this is an option worth exploring.  How would you differentiate something not being used or running vs something that has fallen over?  Wonder if a configurable "blacklist" is the way to go in general?  Support services could be added to the blacklist if not running.  If we just go off Consul, what do we do when a support service goes down?  Open to suggestions and would welcome any/all design suggestions on how to handle this.

**Comment by AlexCuse** [comment]
No rush @jpwhitemn - I was thinking a combination of an endpoint existing and being available but as I thought about it more I think a blacklist (or whitelist) for support services probably makes the most sense here.

**Comment by AlexCuse** [comment]
Haven't looked at how to get there yet but how about a whitelist for support services to monitor, and if nothing is provided it falls back to the current behavior?

**Comment by cloudxxx8** [comment]
This issue doesn't exist after EdgeX v2
Closing this issue
