### ISSUE TITLE
Edgex support scheduler crashed after removeing a interval from ui and restarting edgex docker

### ISSUE THREAD

**Issue by DaveZLB** [edgexfoundry/edgex-go#2488]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
edgex-support-scheduler

### Is this a regression?

I found this bug in nightly-build version, it  has existed since fuji version

### Description and Minimal Reproduction
The issue is located in support scheduler part, the snapshot is my opertaion,
<img width="1439" alt="operation1" src="https://user-images.githubusercontent.com/29951254/79085412-14abd680-7d6b-11ea-9797-e64bfc339f27.png">

when I use edgex-ui add a interval named i1_3s and  a interval action named action_3s,then first I removed interval i1_3s, next remove interval action action_3s(it failed to delete because of not existing interval id), then i restart edgex docker,  edgex-support-scheduler cannot restart, error log is shown below,

![image](https://user-images.githubusercontent.com/29951254/79086648-66566000-7d6f-11ea-94d8-129a38da0da9.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**EdgeX Version:**

nightly-build

**Anything else relevant?**

I think edgex-support-scheduler code should check such a  situation,  if a interval has been used by interval action , it should not be abled to deleted.

**Comment by lenny-intel** [comment]
@JamesKButcher , @cloudxxx8 , another older bug. This one needs to be validated that it was fixed in Ireland.

**Comment by cloudxxx8** [comment]
verified this issue is fixed in v2
the Interval cannot be deleted if there is any associated IntervalAction existing
