### ISSUE TITLE
Configuration of root CA file is inconsistent across services...

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#2495]
While working on a recent update to the snap packaging (issue #2051), I noticed a few inconsistencies involving the configuration keys, and and sometimes the value of the root CA path across the various configuration files used by core-*, security-*, and support-* services.

One inconsistency is that some services use the top-level configuration key **SecretStore** (core-*, and support-* services), whereas some use **SecretService**.

The next inconsistency is the name of the root CA file path. Some use **CaFilePath** (security-secretstore-setup), some use **CACertPath** (security-proxy-setup), and some use **RootCaCertPath** (core-*, and support-* services).

The final issue is that the values used in the various configuration files differ as well, and thus most of them need to be overridden in the docker-compose files (and the snap). For instance, security-secretstore-setup uses `/tmp/edgex/secrets/ca/ca.pem`, whereas security-proxy-setup uses `res/EdgeXFoundryCA/EdgeXFoundryCA.pem` (the latter is overridden by a service-specific env var override in [docker-compose-nexus-mongo.yml](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml#L250)).  

Also note, in the snap, due to a misconfiguration of security-secrets-setup, the directory `$SNAP_DATA/pki/EdgeXFoundryCA`, isn't properly cleaned up, which means there are two identical root certificates, one named **ca.pem** and one named **EdgeXFoundryCA.pem** that get created (see issue #2547 for details).

At minimum, we should make sure all the default values are correct in the **configuration.toml** files, and if possible at least fix the security-proxy-setup to use **CaFilePath** instead of **CAFilePath** so that the security services are aligned.

This bug is being reported against the master branch.

**Comment by bnevis-i** [comment]
> For instance, security-secretstore-setup uses /tmp/edgex/secrets/ca/ca.pem, whereas security-proxy-setup uses res/EdgeXFoundryCA/EdgeXFoundryCA.pem (the latter is overridden by a service-specific env var override in docker-compose-nexus-mongo.yml). I've always wondered why we have two identical root certificates, one named ca.pem and one named EdgeXFoundryCA.pem that get created?

I've always wondered why we are compiling the configurations files into the containers, instead of injecting the configuration at runtime.  IMO the configuration.toml files don't even belong in the codebase.

**Comment by mkbhanda** [comment]
There is value to having a configuration.toml in the code base as a sample (all the knobs one can set) and default. Through injection or environment variable settings some of the settings may be modified.

**Comment by bnevis-i** [comment]
@mkbhanda I agree that documentation of what each service needs for configuration is important, but  we are also overly dependent on what the actual values for these settings are, such that inconsistencies among the reference values are causing confusion.

**Comment by bnevis-i** [comment]
For future documentation `[SecretStore]`  is the configuration used by go-mod-secrets to find the secretstore.  '[SecretService]' is supposed to be the private configuration used by security-secretstore-setup to do its initialization thing with Vault.  Ideally, SecretService should inherit the same configuration keys as SecretStore so that is less confusing.

**Comment by bnevis-i** [comment]
Related issue: #2200, where it was decided in this release to keep using `[SecretService]` keys in this release for proxy-setup.

**Comment by mkbhanda** [comment]
Would it make sense to use Viper https://blog.gopheracademy.com/advent-2014/configuration-with-fangs/ to bring together all our ways of configuration, use a standard precedence order, facilitate 12 factor apps etc? Viper supports aliases, so different projects could continue to use old names without breaking things.

**Comment by bnevis-i** [comment]
Viper looks very promising.

**Comment by tonyespy** [comment]
So the SecretService vs. SecretStore difference was explained by @bnevis-i, thanks.

Regarding the config keys used for the root CA file path, @tingyuz said we couldn't fix this because it would break compatibility:

> Some use CaFilePath (security-secretstore-setup), some use CACertPath (security-proxy-setup),

I questioned the statement that this would break compatibility because we made some other changes to config keys as part of Geneva. In fact see the following [commit 4ecacc7](https://github.com/edgexfoundry/edgex-go/commit/4ecacc70807748e3e5e4bb17e6e3f987741d9caf) where all of the keys under SecretService were changed from lowercase to CamelCase.

And finally, do we still need to copies of the rootCA certificate with different names per:

> I've always wondered why we have two identical root certificates, one named **ca.pem** and one named **EdgeXFoundryCA.pem** that get created?

**Comment by bnevis-i** [comment]
> I've always wondered why we have two identical root certificates, one named ca.pem and one named EdgeXFoundryCA.pem that get created?

It's technical debt.  I believe the original tool was called PKI-init, which did the named certs.  Then Jim and I wrote pkisetup to ride on top of it and do a bunch of file copies to stash the certs in the appropriate places.   This was our first contribution, and the feedback was to combine the two utilities into one -- security-secrets-setup -- because we were so late for Edinburgh(?) release we did it quick and dirty by smashing the two code bases together -- pkiinit is still in there even though it is a single executable now.

**Comment by tonyespy** [comment]
> > I've always wondered why we have two identical root certificates, one named ca.pem and one named EdgeXFoundryCA.pem that get created?
> 
> It's technical debt. I believe the original tool was called PKI-init, which did the named certs. Then Jim and I wrote pkisetup to ride on top of it and do a bunch of file copies to stash the certs in the appropriate places. This was our first contribution, and the feedback was to combine the two utilities into one -- security-secrets-setup -- because we were so late for Edinburgh(?) release we did it quick and dirty by smashing the two code bases together -- pkiinit is still in there even though it is a single executable now.

Are they both used, or could we remove one of them?

**Comment by bnevis-i** [comment]
@jim-wang-intel Can you make a recommendation to Tony on how to get EdgeXFoundryCA.pem thrown away at the end of security-secrets-setup?

**Comment by jim-wang-intel** [comment]
@bnevis-i  the generated file `EdgeXFoundryCA.pem` should already be deleted at the end of generate command from security-secrets-setup: see this: https://github.com/edgexfoundry/edgex-go/blob/master/internal/security/secrets/command/generate/generate.go#L69-L70 line of code.

Not sure why there is a left-over there...

**Comment by bnevis-i** [comment]
@tonyespy what is left for this one.  Do we need to scrub EdgeXFoundryCA.pem from the configuration.toml scripts?

**Comment by tonyespy** [comment]
@bnevis-i @hutchic I reviewed my original issue and here's an updated status of the issue which actually had four components:

  * use of `SecretStore` [core-*, support-*] vs. `SecretService` [proxy/secretstore-setup] -- this is still an issue, but was punted from Geneva due to the concern that it would be break backwards compatibility with Fuji. This still applies to Hanoi as well as the planned version is 1.3. Also see related issue #2200 where a decision was reached to not update proxy-setup to use go-mod-secrets. I think this could probably be split out into a separate issue and targeted for Ireland, which in theory is supposed to be a 2.0 release.

 * `CaFilePath` (secretstore-setup), `CACertPath` (proxy-setup), and `RootCaCertPath` (everything else) -- this issue still exists, but for the same reasons as above, these can't be aligned until Ireland.

 * actual values of cert paths differ across services (eg. `/tmp/edgex/secrets/ca.pem` vs. `res/EdgeXFoundryCA/EdgeXFoundryCA.pem`) -- this issue still exists, and could be cleaned up as most of these values are overridden using environment variables in docker-compose and the snap.

 * `$SNAP_DATA/pki/EdgeXFoundryCA `directory isn't properly cleaned up -- this was fixed in the Genava release, so is no longer an issue.

**Comment by bnevis-i** [comment]
Proposal is to change the lines marked with an ❌ from the ca.pem path to the EdgeXFoundryCA.pem path.

```
$ grep -ri /EdgeXFoundryCA.pem .
./cmd/security-secrets-setup/res/local-tls.hcl:  tls_client_ca_file ="/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem"
./cmd/support-logging/res/configuration.toml:RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
./cmd/core-command/res/configuration.toml:RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
./cmd/support-notifications/res/configuration.toml:RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
./cmd/core-metadata/res/configuration.toml:RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
./cmd/security-proxy-setup/res/configuration.toml:CACertPath = "res/EdgeXFoundryCA/EdgeXFoundryCA.pem"
./cmd/support-scheduler/res/configuration.toml:RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
./cmd/core-data/res/configuration.toml:RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
./internal/security/proxy/testdata/configuration.toml:CACertPath = "res/EdgeXFoundryCA/EdgeXFoundryCA.pem"

$ grep -ri /ca.pem .
❌./openapi/v2/core-data.yaml:                    RootCaCertPath: "/tmp/edgex/secrets/ca/ca.pem"
✔./snap/local/runtime-helpers/config/security-secret-store/vault-config.hcl.in:  tls_client_ca_file ="$SNAP_DATA/secrets/ca/ca.pem"
✔./snap/snapcraft.yaml:  SecretStore_RootCaCertPath: $SNAP_DATA/secrets/ca/ca.pem
✔./snap/snapcraft.yaml:      SecretService_CaFilePath: $SNAP_DATA/secrets/ca/ca.pem
✔./snap/snapcraft.yaml:      SecretService_CACertPath: $SNAP_DATA/secrets/ca/ca.pem
✔./snap/snapcraft.yaml:      SecretService_CACertPath: $SNAP_DATA/secrets/ca/ca.pem
❌./snap/snapcraft.yaml:                  sed -e "s@\"/tmp/edgex/secrets/ca/ca.pem\"@\"\$SNAP_DATA/secrets/ca/ca.pem\"@" \
❌./cmd/security-secretstore-setup/res/configuration.toml:CaFilePath = "/tmp/edgex/secrets/ca/ca.pem"
❌./cmd/security-secretstore-setup/res-file-token-provider/configuration.toml:CaFilePath = '/tmp/edgex/secrets/ca/ca.pem'
✔./cmd/security-secrets-setup/start_vault.sh:              tls_client_ca_file ="'${VAULT_TLS_PATH}'/ca.pem" 
✔./cmd/security-secrets-setup/README.md:sudo diff -r /etc/edgex/pki/ca/ca.pem /run/edgex/secrets/ca/ca.pem
❌./cmd/security-secretstore-read/res/configuration.toml:  RootCaCertPath = "/tmp/edgex/secrets/ca/ca.pem"
```

**Comment by bnevis-i** [comment]
@hutchic @tonyespy do yo have feedback on the proposal or should we punt the whole thing to Ireland release?

**Comment by hutchic** [comment]
I'm not positive on the scope of work but given the time frame available I think it would be acceptable to allow this to slip to Ireland

**Comment by tonyespy** [comment]
See issue #2873 for yet another example of inconsistent security configuration.

**Comment by bnevis-i** [comment]
@lenny-intel verify if recent cleanup activities addressed this issue.

**Comment by lenny-intel** [comment]
This was address by #3181 and #3189
