### ISSUE TITLE
Correct Redis secret setup per ADR for secret creation and distribution

### ISSUE THREAD

**Issue by andresrinivasan** [edgexfoundry/edgex-go#2503]
# 🚀 Feature Request

### Relevant Package

Update `security-secretstore-read` to use a) go-mod-bootstrap b) conform to [ADR for secret creation and distribution](https://github.com/edgexfoundry/edgex-docs/issues/132)

### Description
 
Currently `security-secretstore-read` config cannot be overridden using common EdgeX mechanisms. Furthermore, the secret is shared in a non-conforming way.

### Describe the solution you'd like

**Objectives**
* Use the Redis Docker image as is to simplify sustaining work
* Have everything live in the edgex-go repo so that this doesn't get orphaned
* Add support for go-mod-bootstrap
* Conform to [ADR for secret creation and distribution](https://github.com/edgexfoundry/edgex-docs/issues/132)

**Solution**
* Rename security-secretstore-read  to security-bootstrap-redis
* Separate security-bootstrap-redis from security-secretstore-setup by creating a new container to host the app. The sole purpose of this container is to inject the Redis secret into Redis after the Vault has been bootstrap.
* Update the secure compose file to start Redis and the security-bootstrap-redis container. After the secret is read from Vault and injected into Redis, security-bootstrap-redis keeps running and keeps the vault token fresh

**Scenarios to test again**
* security-bootstrap-redis starts before Vault is ready and and the secret store token has yet to been provisioned
* security-bootstrap-redis starts before Redis secret has been provisioned in Vault
* security-bootstrap-redis has a stale secret store token from the last run. Use implemented go-mod-bootstrap hook to handle this.
* secret store token has expired (only valid 1hr after issue)
* secret injection container is started multiple times
* Redis crashed and needs to be restarted

**Other impact**
* An update to Snaps will be required

### Describe alternatives you've considered
* Create a config file on the fly and pass it through the secure file store
    * This makes it difficult to use the Redis config file to configure other policies

**Comment by andresrinivasan** [comment]
Please assign to @andresrinivasan for Hanoi or a pre-Hanoi dot release.

**Comment by tonyespy** [comment]
Just a note, one of the impact's of this bug is that configuration values in **cmd/security-secretstore-read**'s `configuration.toml` file cannot be overridden by environment variables.

**Comment by bnevis-i** [comment]
@tonyespy is this a release-blocking issue or were you able to work around it?

**Comment by tonyespy** [comment]
@bnevis-i I was able to work around it by just modifying the **configuration.toml** file which was the technique we used for all snap-specific config changes. Now almost all of these are modifications are handled via the env var overrides.

**Comment by hutchic** [comment]
our goals is this should be compliant with the [ADR for secret creation and distribution](https://github.com/edgexfoundry/edgex-docs/issues/132)

@andresrinivasan is this still on your radar?

**Comment by andresrinivasan** [comment]
Yes. Tracking as part of #2636.

**Comment by andresrinivasan** [comment]
@lenny-intel @bnevis-i @tonyespy @jpwhitemn 

FYI and apologies to @tonyespy who is struck waiting on me to understand the changes needed for the snap (should be much better than it is right now).

I've been working to get this done and I still plan to complete the PR by the freeze but I will be going right up to code freeze date.

**Comment by tonyespy** [comment]
@andresrinivasan thanks for the heads-up! Can you share your WIP branch once you get going on this, so I can keep tabs on this. In the past, we've been OK landing snap specific changes post code-freeze, but I'd like to keep these at a minimum if possible.

**Comment by andresrinivasan** [comment]
@tonyespy See https://github.com/andresrinivasan/edgex-go/tree/issue-2503-correct-redis-secret-setup. I'm just starting to standup my test environment.

**Comment by tonyespy** [comment]
@andresrinivasan thanks for the pointer to your branch. I'm just starting to grok your changes and have pushed my own WIP progress branch for the snap changes here:

https://github.com/tonyespy/edgex-go/tree/andre-redis-bootstrap

I'll touch base once I have a better understanding of your changes.

**Comment by andresrinivasan** [comment]
@lenny-intel @bnevis-i @tonyespy @hutchic 

Please see PR #2850 for review.
