### ISSUE TITLE
Update EdgeX to use one Redis Library Consistently.

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#2509]
# 🚀 Feature Request

### Relevant Package
Core services, and possibly other modules that use Redis and bring in their own Redis dependencies. 

### Description
As part of the work to [add RedisStreams functionality to go-mod-messaging](https://github.com/edgexfoundry/go-mod-messaging/issues/35), a new Redis library was used `go-redis`. This differs from `edgex-go` which uses `redigo`. We should have one library we use to interact with Redis for both consistency and to reduce the size of the system.

### Describe the solution you'd like
Update `edgex-go`, `go-mod-messaging`, and all other Go repos which use redis to use the same Redis library.

### Describe alternatives you've considered
N\A

**Comment by bnevis-i** [comment]
Of the two, go-redis seems to be more actively maintained.

**Comment by bnevis-i** [comment]
@jamesrgregg good candidate for new vetting process

**Comment by lenny-intel** [comment]
@cloudxxx8 , we should make this switch for the V2 Redis Client. I notice that the V2 Redis Client is using the V1 Redis Client.
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/v2/infrastructure/redis/client.go#L33
Not sure why... but this switch to use the go-redis package in the V2 Redis Client would also resolve this.

Thoughts?

**Comment by cloudxxx8** [comment]
I didn't notice we have two different Redis libraries.  I'm fine with switching library, but it would take more time for V2.
redigo has less dependency and uses Go 1.14
https://github.com/gomodule/redigo/blob/master/go.mod

go-redis use Go 1.11
https://github.com/go-redis/redis/blob/master/go.mod

@andresrinivasan this decision needs your recommendation.

**Comment by jpwhitemn** [comment]
discussed in Core WG - decision is that this is tech debt, under the covers that could be done in the next release cycle.  On hold to next release (at earliest).

We should try to be consistent across the project. (database access versus message bus access)
We need a briefing from Redis (Andre?) on any additional benefits/detraction (+/-)
One is supposed to be used for open source efforts and one is recommended for enterprise use (not sure of the which is used for which and why) - again more detailed understanding is needed

@andresrinivasan - can you help with this at an upcoming core WG meeting?

**Comment by andresrinivasan** [comment]
Yes. I guess that's the December 3 meeting. Short answer is redigo is lightweight and we tend to use it for Redis Enterprise as the cluster makes up for the missing client capabilities. Given the roadmap for EdgeX, go-redis makes more sense for things like Redis OSS HA.

**Comment by JamesKButcher** [comment]
Discussed in Core WG and agreed to close.

As Lenny wrote: This would mean a compete refactor on the V2 Redis layer using goredis or complete refactor of Redis Pub/Sub in go-mod-messaging using Redigo. IMO, we are using the right modules in the right places and this can be closed
