### ISSUE TITLE
[core-*, security-*, support-*] Error message logged when remote disabled and no file specified

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#2513]
We recently made a change to all the service configuration.toml files to ensure that all disable remote logging and do not specify Logging.File. This causes each of the services to simply write log messages to stdout. This works great, however every service on startup logs the following error:

level=ERROR ts=2020-04-22T20:35:46.660773509Z app=edgex-security-secretstore-setup source=logger.go:74 msg="logTarget cannot be blank, using stdout only"

As our reference implementation uses this type of configuration across the board, it seems like a good idea to change this log message, at minimum to not be an ERROR message, however the message itself should probably be updated.

This is being reported against the latest nightly build as of code-freeze.

# 🐞 Bug Report

### Affected Services

 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by lenny-intel** [comment]
This was fixed in go-mod-core-contracts PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/369
