### ISSUE TITLE
ARM64 Redis: event socket hang up on Jenkins blackbox-testing

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2521]
There are a few blackbox-testing testcases failed on arm64 with redis DB (rarely happens on amd64 with redis DB).

# 🐞 Bug Report

### Affected Services

 The issue is located in: 
edgex-core-data

### Is this a regression?

 -

### Description and Minimal Reproduction
Using nightly-build redis arm64 [security-enabled](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml) or [no security](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml) compose file

## 🔥 Exception or Error
| tescase | error |
| -------- | ----- |
| <p>Core-data event 07 : <br>GET `/v1/event`</p>13:00:23 ❏ event<br>13:00:23 ↳ 07 http://localhost:48080/api/v1/event<br>13:00:23   GET http://edgex-core-data:48080/api/v1/event [errored]<br>13:00:31     socket hang up<br>13:00:31   2. Status code is 200<br>13:00:31   3. Response time is less than 800ms<br>  | socket hang up | 
| <p>Core-data event 30: <br>DELETE `/v1/event/removeold/age/{age}`</p>13:00:36 ↳ 30 http://localhost:48080/api/v1/event/removeold/age/:age<br>13:00:36   DELETE http://edgex-core-data:48080/api/v1/event/removeold/age/0 [errored]<br>13:00:49      socket hang up<br>13:00:49   5. Status code is 200<br>13:00:49   6. Response time is less than 800ms  | socket hang up |                                               

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
Master

**Anything else relevant?**
Jenkins nightly-build redis arm64 no-secuty 
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-ubuntu18.04-docker-arm64-4c-16g-master/DATABASE=redis,node=ubuntu18.04-docker-arm64-4c-16g/74/consoleFull

Jenkins nightly-build redis arm64 security-enabled
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-16g-master/DATABASE=redis,node=ubuntu18.04-docker-arm64-4c-16g/74/consoleFull

**Comment by cloudxxx8** [comment]
it sometimes happens in x86, too

**Comment by AnthonyMBonafide** [comment]
I wonder if this is related to #2527 somehow

**Comment by cloudxxx8** [comment]
but the blackbox test only generate a little data
this issue didn't exist before

**Comment by AnthonyMBonafide** [comment]
The Blackbox test are not generating data explictly. However I see that device virtual is running and automatially generating Events once it is started:
```
00:54:41 [1A[2K
Creating edgex-sys-mgmt-agent ... [32mdone[0m
```

and by time the GET Events Request is executed:
```
01:00:23 ❏ event
01:00:23 ↳ 07 http://localhost:48080/api/v1/event
01:00:23   GET http://edgex-core-data:48080/api/v1/event [errored]
01:00:31      socket hang up
01:00:31   2. Status code is 200
01:00:31   3. Response time is less than 800ms
```

About 6 mins have lapsed. Device virtual generates Binary data which is very big. On my local machine, running Device Virtual for 1 min with an empty database, a GET Event Request results in a response of 10.67MB. A little after a min of Device Virtual running Postman will crash with the same request. I think this Binary functionality for Device Virtual is newer and did not exist in previous releases, and would explain why we are seeing this now and not for Fuji or earlier.

Doing a little digging, it looks like Device Virtual is creating Binary data and the size of the Binary payload is half of the [maximum size allowed by device-sdk-go which is 16MB](https://github.com/edgexfoundry/device-sdk-go/blob/f380c9750d394b15a68c03899168051b17741a54/pkg/models/commandvalue.go#L105), so each Event it creates is 8MB and its creating an event every [30 seconds](https://github.com/edgexfoundry/device-virtual-go/blob/01be24e26ff5cef53aea6a5bd73bb718927b3a70/cmd/res/configuration.toml#L145). Doing a little "Anthony" math here. When the test is running it looks like core-data can be trying to respond with at least 10 Binary events, assuming 5 mins have elapsed between the start of Device Virtual and the request `GET Event` which means the response size is at least 80MB, not including the other types of events which are being created by Device Virtual. 

I think the best thing to do here is configure Device Virtual to have a higher frequency for creating events for these tests and possibly disabling the Binary functionality to avoid big events.

**Comment by cloudxxx8** [comment]
we commented out the autoevent of binary data in device-virtual, and the blackbox test looks good now.  let's monitor it two more days and we might be able to close this issue.
Thanks for the analysis, @AnthonyMBonafide

**Comment by jinlinGuan** [comment]
No failures on Jenkins blackbox-testing. Closing this issue.
