### ISSUE TITLE
Secure Kong admin port using password

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2537]
Kong admin port is not currently secured against processes running on localhost.  In particular security-proxy-setup is able to perform Kong configuration without requiring an authentication credential.  Ensure that use of kong admin port requires authentication.

Related info: https://docs.konghq.com/2.0.x/secure-admin-api/#introduction

(What we want is the Kong API loopback approach.)

**Comment by hutchic** [comment]
this should be compliant with [ADR for secret creation and distribution](https://github.com/edgexfoundry/edgex-docs/issues/132)

**Comment by hutchic** [comment]
I've ran out of bandwidth / time to fit this into Hanoi but the approach is documented https://docs.konghq.com/2.2.x/secure-admin-api/#kong-api-loopback

**Comment by beaufrusetta** [comment]
First part of this issue has a [PR submitted against it](https://github.com/edgexfoundry/developer-scripts/pull/395). Now I'm off to modify edgex-go to work within the changes I've made.
