### ISSUE TITLE
Remove generation of mongodb passwords from security-services

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2538]
Monbodb is being removed in Hanoi release; remove generation of mongodb passwords from the following components:

- security-secretstore-setup
- security-file-token-provider (remove Vault ACLs for mongodb password)

**Comment by bnevis-i** [comment]
Reverted for Hanoi.  Replan for Ireland release.

**Comment by lenny-intel** [comment]
Reopening as we reverted the PR. Holding off until EdgeX version 2
