### ISSUE TITLE
Notification OpenAPI inconsistent with router implementation

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#2540]
# 📚 Docs or Wiki Bug Report

### Description

The OpenAPI spec does not list get with <id> but the router implementation supports it.
Please correct the OpenAPI spec. Auto generation of stubs would help to keep things consistent.

### What's the affected URL?**
 https://docs.edgexfoundry.org/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by AnthonyMBonafide** [comment]
To which URI or endpoint is the bug related?
