### ISSUE TITLE
[Mongo][Security] support-notification: 502 bad gateway

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2543]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
support-notification

### Is this a regression?

 fails on Jenkins x86 mongo security-enabled blackbox-testing since May 6

### Description and Minimal Reproduction
1. `docker-compose -f docker-compose-nexus-mongo.yml up -d`
Download nightly-build compose file from [edgexfoundry/developer-scripts](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml)
2. get TOKEN
```
OT=$(docker-compose -f docker-compose-nexus-mongo.yml run --rm --entrypoint /edgex/security-proxy-setup edgex-proxy --init=false --useradd=geneva --group=admin | grep '^the access token for')
export TOKEN=$(echo ${OT} | sed 's/.*: \([^.]*\.[^.]*\.[^.]*\).*/\1/')
```
3. `curl -ki -H"Authorization: Bearer $TOKEN" https://localhost:8443/notifications/api/v1/ping`

got 502:
```      
HTTP/2 502 
date: Fri, 08 May 2020 09:44:20 GMT
content-type: text/plain; charset=utf-8
server: kong/2.0.1
content-length: 58
x-kong-upstream-latency: 0
x-kong-proxy-latency: 2
via: kong/2.0.1

An invalid response was received from the upstream server
```
4. However, `curl -ki -H"Authorization: Bearer $TOKEN" http://localhost:48060/api/v1/ping` works fine.
```
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Fri, 08 May 2020 09:44:27 GMT
Content-Length: 4

pong%
```

## 🌍  Your Environment
**Deployment Environment:**
x86
**EdgeX Version:**
master

**Anything else relevant?**
It works fine when getting other services 
`curl -ki -H"Authorization: Bearer $TOKEN" https://localhost:8443/metadata/api/v1/ping`
```
HTTP/2 200 
content-type: text/plain; charset=UTF-8
content-length: 4
date: Fri, 08 May 2020 09:44:15 GMT
x-kong-upstream-latency: 1
x-kong-proxy-latency: 12
via: kong/2.0.1

pong%
```

**Comment by cloudxxx8** [comment]
@tingyuz , @bnevis-i 
could you please help take a look?  It's the only issue on blackbox test right now.

**Comment by bnevis-i** [comment]
Sure.  Will spin up the stack and take a look.

**Comment by hutchic** [comment]
The kong logs

```
kong                      | 2020/05/12 14:59:08 [error] 28#0: *4726 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.224.1, server: kong, request: "GET /notifications/api/v1/pingHTTP/1.1", upstream: "http://127.0.0.1:48060/api/v1/ping", host: "localhost:8443"
kong                      | 2020/05/12 14:59:08 [error] 28#0: *4726 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.224.1, server: kong, request: "GET /notifications/api/v1/pingHTTP/1.1", upstream: "http://127.0.0.1:48060/api/v1/ping", host: "localhost:8443"
kong                      | 2020/05/12 14:59:08 [error] 28#0: *4726 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.224.1, server: kong, request: "GET /notifications/api/v1/pingHTTP/1.1", upstream: "http://127.0.0.1:48060/api/v1/ping", host: "localhost:8443"
kong                      | 2020/05/12 14:59:08 [error] 28#0: *4726 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.224.1, server: kong, request: "GET /notifications/api/v1/pingHTTP/1.1", upstream: "http://127.0.0.1:48060/api/v1/ping", host: "localhost:8443"
kong                      | 2020/05/12 14:59:08 [error] 28#0: *4726 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.224.1, server: kong, request: "GET /notifications/api/v1/pingHTTP/1.1", upstream: "http://127.0.0.1:48060/api/v1/ping", host: "localhost:8443"
kong                      | 2020/05/12 14:59:08 [error] 28#0: *4726 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.224.1, server: kong, request: "GET /notifications/api/v1/pingHTTP/1.1", upstream: "http://127.0.0.1:48060/api/v1/ping", host: "localhost:8443"
kong                      | 192.168.224.1 - - [12/May/2020:14:59:08 +0000] "GET /notifications/api/v1/ping HTTP/1.1" 502 58 "-" "curl/7.47.0"
```

**Comment by bnevis-i** [comment]
Upstream shouldn't be 127.0.0.1.  Should be a docker hostname.

**Comment by bnevis-i** [comment]
```
#  Clients_Notifications_Host: edgex-support-notifications # un-comment if re-enabling logging service for remote logging
```

This seems to be related to the logging disable changes made by @lenny-intel . 

Lenny, how do you suggest we proceed?

**Comment by bnevis-i** [comment]
The services that seem to know about notifications and would be affected by this are:

- proxy-setup
- system management agent
- core-metadata

Core metadata doesn't seem like it will talk to notifications service unless 

```
[Notifications]
PostDeviceChanges = true
```

Would uncommenting
```
#  Clients_Notifications_Host: edgex-support-notifications
```

and adding

```
Notifications_PostDeviceChanges: false
```

be an appropriate fix?

**Comment by bnevis-i** [comment]
Upon further inspection, with the exception of mongo, all of the other Yaml files have:

```
Clients_Notifications_Host: edgex-support-notifications
...
#  Clients_Notifications_Host: edgex-support-notifications
```

(i.e. the commented out remapping isn't doing anything)

**Comment by tonyespy** [comment]
If support-notifications isn't being started, then I'm pretty sure that explains why you can't reach it thru kong...

**Comment by bnevis-i** [comment]
It was supposed to be `# Clients_Logging_Host` that was supposed to be commented out.  @lenny-intel  is working on PR now.

**Comment by bnevis-i** [comment]
Added Clients_Notifications_Host to docker-compose-nexus-mongo.yml.  That was the only dockerfile from which it was missing.
