### ISSUE TITLE
[security-proxy-cmd] Fix usability issues with Kong access token generation

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#2549]
# 🐞 Bug Report

### Affected Services
The issue is located in: security-proxy-setup

There are several usability issues with the security-proxy-setup command used to generate kong access tokens (used to grant access to EdgeX REST endpoints via Kong).

1. There's no command-line option(s) to control where the resulting file is written. A configuration option `KongAuth.OutputPath` exists, but it's set to "accessToken.json" by default, so it's not apparent where the file is written, as the command doesn't write the full pathname of the generated file to stdout.
2. The command outputs a JSON file by default, when what the user actually needs is the auth token returned as a string. One suggestion would be to change the default behavior to output a simple string. Ex.

    `Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXx
    `

3. Another suggestion if the file output function is kept, would be to modify the output to simply write the raw token instead of JSON (see comment below for more details).

4. Finally, based on code inspection, it appears the application never explicitly close the output file.

### Is this a regression?
No

### Description and Minimal Reproduction
The following are steps to reproduce the default behavior of the command.

Docker:
If I follow the instructions from the top-level [Security](https://github.com/edgexfoundry/edgex-go/blob/master/SECURITY.md) page in edgex-go, a token is generated and output to stdout, however there's no output about a file being created even though `AuthToken.OutputPath` is set to "accessToken.json" in security-proxy's **configuration.toml** file.

Snap:
The only way I've been able to get proxy-setup to successfully generate **accessToken.json** is by setting `KongAuth_OutputPath` to /tmp/accessToken.json in the environment of the command (in **snapcraft.yaml**). 

**EdgeX Version:** Geneva

**Comment by bnevis-i** [comment]
Additionally, looking at the code, the file is written but never officially closed.

However, I question the utility of the function as it is written -- particularly the JSON output format.

Ultimately, what is needed to use the token is a

```
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXx
```

HTTP header.  However, the code as it stands now, outputs a JSON file, which would then need to be further processed.

Would it be better to remove KongAuth.OutputPath entirely and just take a parameter such as `-o tokenPath` that just outputs the raw token?
