### ISSUE TITLE
Switch to Go dep

### ISSUE THREAD

**Issue by drasko** [edgexfoundry/edgex-go#255]
Go [dep](https://github.com/golang/dep) is an official Go vendoring tool tad became suitable for production use.

Switch from `glide` should be fairly easy.

**Comment by falkerson** [comment]
@drasko minor note: it's not official yet but 'official experiment' https://github.com/golang/dep#dep.

From https://github.com/golang/dep/wiki/Roadmap:

`Please remember that finishing these issues does not guarantee dep will be accepted. No external code of this size or significance has ever been pulled into the Go toolchain before, so everyone's kind of playing it by ear.`

**Comment by falkerson** [comment]
But Glide is suggesting users to migrate from Glide to dep: https://github.com/Masterminds/glide#golang-dep
