### ISSUE TITLE
ValueDescriptors do not get removed along with DeviceProfile when EnableValueDescriptorManagement=true

### ISSUE THREAD

**Issue by novuscy** [edgexfoundry/edgex-go#2550]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
core-metadata core-data

### Is this a regression?

Not so sure.
### Description and Minimal Reproduction
1. Set EnableValueDescriptorManagement=true in core-metadata config file
2. Add a new DeviceProfile, the associated ValueDescriptors in the profile are added automatically 
3. Remove the profile, but the associated ValueDescriptors are not removed
4. Next time I add the same profile, an 409 error occurred. 

## 🔥 Exception or Error
<pre><code>

409 - duplicate name for value descriptor

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
go 1.14
**EdgeX Version:**
Master

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@JamesKButcher, @cloudxxx8  , found this old bug which should be closed as it is no longer valid for Ireland.

**Comment by JamesKButcher** [comment]
No longer an issue since the device profile restructure. Closing
