### ISSUE TITLE
Post event with binary value returns "reading has no value"

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2553]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
core-data

### Description and Minimal Reproduction
The error happens on x86 and arm64
1. `docker-compose -f docker-compose-nexus-redis-no-secty.yml up -d`
2. 
```
curl -X POST -H "Content-Type: application/json" -d '{                                              
    "device": "irCamera",
    "readings": [
        {
           "device": "irCamera",
           "name": "image",
           "binaryValue": "83010203",
           "mediaType": "image"
        }
    ]
}' http://localhost:48080/api/v1/event
```

## 🔥 Exception or Error
The status code is "500 Internal Server Error".
The response body is "reading has no value".
The log of core-data: `level=ERROR ts=2020-05-12T07:06:06.6926142Z app=edgex-core-data source=handler.go:47 msg="reading has no value"`
## 🌍  Your Environment
**Deployment Environment:**
X86, arm64 
**EdgeX Version:**
master

**Anything else relevant?**

**Comment by tonyespy** [comment]
This test looks wrong to me, as there's no `type` specified, yet `mediaType` is specified which implies that this is a binary reading. I would suggest re-testing with `type` added, and if the error goes away, close this issue as invalid.

**Comment by cloudxxx8** [comment]
It works if I change the test command to 
```
curl -X POST -H "Content-Type: application/json" -d '{                                              
    "device": "irCamera",
    "readings": [
        {
           "device": "irCamera",
           "name": "image",
           "binaryValue": "83010203",
           "mediaType": "image",
           "valueType": "Binary"
        }
    ]
}' http://localhost:48080/api/v1/event
```

Thanks, @tonyespy 
@jinlinGuan please help modify the test script
