### ISSUE TITLE
Delete an In Use Interval Puts System In An Invalid State

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#2554]
# 🐞 Bug Report

### Affected Services
The issue is located in: support-scheduler

### Is this a regression?

No

### Description and Minimal Reproduction
Issuing a delete(`DELETE /interval/name/{name}`) of an `Interval` that is being referenced by an `Interval` action will cause the system to become in an inconsistent state. When issuing the request the first time, you will get the expected response of:
```
interval still in use by intervalAction(s) name:  midnight
```
However, issuing the request again results in a response of:
```
no interval found for id: midnight
```

But the `Interval` is present if you issue a `GET /interval/name/midnight` or list all the `Intervals` with `GET /interval`

### Reproduction Steps
1. Start support-scheduler with clean database
1. Executed a `DELETE /interval/name/midnight` for the midnight interval
1. Executed another `DELETE /interval/name/midnight` for the midnight interval

## 🔥 Exception or Error
There is no exception logged by the service. However the logs show that the interval has been deleted in some fashion:
```
level=INFO ts=2020-05-12T16:03:02.735144787Z app=edgex-support-scheduler source=message.go:58 msg="Service started in: 3.486394ms"
level=INFO ts=2020-05-12T16:03:05.015308365Z app=edgex-support-scheduler source=schedule.go:212 msg="removed the interval with id: e9ea23c1-135c-4587-870b-27e414ff3df2 from the scheduler queue"
```

The `UUID` in that log message is associated with the `Interval` `midnight` on my system which you can see here:
```json
{
    "Timestamps": {
        "created": 1589298776681,
        "modified": 1589298776681
    },
    "id": "e9ea23c1-135c-4587-870b-27e414ff3df2",
    "name": "midnight",
    "start": "20180101T000000",
    "frequency": "24h"
}
```

## 🌍  Your Environment
Linux :penguin: Fedora 32 

**EdgeX Version:**
master - commit 756fbc29ce8ae79

**Anything else relevant?**
This issue seems to be related to us maintaining two places which house the `Interval`s and `IntervalAction`s (in memory via maps and database via Redis) and they are getting out of sync when issuing a delete. At a quick glance, it seems we are deleting the construct from memory before checking if it is use and then not deleting it from the database. This is just a thought as I poked around with the APIs and quickly looked at the code.

Also note that once the service is restarted the issue is not present for the first DELETE request as the system seems to be in the correct state since during startup the `Interval`s and `IntervalAction`s are loaded into memory.

**Comment by AnthonyMBonafide** [comment]
This issue was found during the work done in issue #2520 and PR #2552

**Comment by AnthonyMBonafide** [comment]
This issue is dependent on the completion of #2520 so that we can apply the fix to both deleting by name and ID. As discussed in PR #2552, this issue is present when attempting to add the guard to protect against deleting `Interval`s that are in use when deleting by ID

**Comment by AnthonyMBonafide** [comment]
After having a meeting with @akramtexas, He has cleaned up the code which handles the deleting of `Interval`s in PR #2552 . By doing so he has fixed this issue. I am going to assign this issue to him and this should be resolved when he closes out PR #2552

**Comment by nbfhscl** [comment]
The PR #2517 I opened last month is trying to solve this and several other related problems. Maybe you can take a look at it.

**Comment by AnthonyMBonafide** [comment]
> The PR #2517 I opened last month is trying to solve this and several other related problems. Maybe you can take a look at it.

That PR looks good and solves some other issues. However, as Trevor pointed out the target branch is incorrect, there is no issue related to the PR so we lose some tracking there, and there is a lot of fixes in that PR that are not mentioned in the commit message. If you can update the PR to address those issues then we can take a look at it and look at having it approved and merged into the code base.

**Comment by AnthonyMBonafide** [comment]
The issue here is what I expected in the original comment for this issue under the **Anything else relevant?**. 

The workaround for this bug is to restart support-scheduler. This will cause the service to reload all `Interval`s and `IntervalAction`s into memory. Therefore, everything is back in-sync. Please note that this workaround is not a fix and you can still put the system into an invalid state by again performing the reproduction steps mentioned above.

**Comment by nbfhscl** [comment]
@AnthonyMBonafide  I was working on fuji branch when I found and fixed those bugs not long ago. Did you mean that pull requests on fuji branch is not welcomed and we should only focus on master? 

By the way, I pulled the latest code of master branch but failed to recreate those bugs. So I‘ll give up updating that PR.
