### ISSUE TITLE
No limit on  /v1/reading

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#2560]
# 🐞 Bug Report

### Affected Services
Several of the reading related API calls support a limit argument but /v1/reading does not.
Why not? A long running EdgeX instance which has not processed it's readings will run into an issue of Error: 500 - limit 53470 exceeds configured max. We should provide a limit argument and a complementary method that allows us to purge all readings.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by jpwhitemn** [comment]
Closing this issue as it is being resolved in V2
