### ISSUE TITLE
edgex-proxy --useradd issues JWTs without an exp field

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2568]
```edgex-proxy --useradd``` issues JWT's without an exp field.

Ostensibly the purpose of using Kong with a JWT over a straight OAuth2 token is that the client has possession of JWT signing key.  This means that the client can issue JWT tokens at their discretion with little concern about the theft of the JWT.  This is different from an OAuth2 token, which is re-used over and over again until it either expires (with no recourse) if it expires at all.

The fact of the matter is that this call should return the HMAC secret rather than issuing a signed JWT with no expiration, as the current implementation is no better than a plain token.

**Comment by hutchic** [comment]
Is this resolved by setting the `config.maximum_expiration` on the jwt configuration?

ref: https://docs.konghq.com/hub/kong-inc/jwt/#parameters

**Comment by bnevis-i** [comment]
Short answer is "no."  Long answer follows:

It is not clearly communicated in the EdgeX documentation nor the Kong documentation (https://docs.konghq.com/hub/kong-inc/jwt/#optional-verified-claims) what the risks are of leaving the expiration field off of a signed object.  EdgeX should not be taking the risk on behalf of the user, but rather, if the user wants to create a permanent token, they should do it themselves (perhaps EdgeX can provide a utility to help with that).

We should also consider how we would redesign this for database-less mode.  Allowing RS256 or ES256 signatures with a customer-provided public key would be much safer than the current solution, as it would eliminate he need to have Postgres and the kong-migrations container, as well as associated secrets (superuser password, TLS certificate) as well as the liability of having a database of OAuth secrets somewhere in the system.

The short term solution would be to return the HMAC secret require the user to supply the expiration on the command line (possibly "never"), rather than making the assumption that the user wants an unlimited lifetime certificate, or perhaps making even generation of the JWT optional.

Also due to related issues (#2477) the useradd/token generation utility should be completely separated out.

**Comment by bnevis-i** [comment]
Also it is much better to use a public/private key than an HMAC secret.  HMAC secret is only useful if edgex itself would need to manfacuture its own tokens , which is not the case here.
