### ISSUE TITLE
Some reading/event APIs will malfunction with binary readings

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#2587]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Core Data

### Is this a regression?

 No

### Description and Minimal Reproduction
Once binary readings are generated, the following APIs will malfunction:
- /v1/reading
- /v1/reading/{start}/{end}/{limit}
- /v1/event
- /v1/event/{start}/{end}/{limit}

Steps to reproduce:
1. Startup EdgeX core services and virtual-device service
2. Trigger a GET command of Random-Binary-Device
3. Try the aforementioned APIs

## 🔥 Exception or Error
<pre><code>
level=ERROR ts=2020-06-12T13:50:14.761420961Z app=edgex-core-data source=reading.go:37 msg="reading has no value"
level=ERROR ts=2020-06-12T13:50:14.765121693Z app=edgex-core-data source=handler.go:47 msg="reading has no value"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 18.04.4 LTS

**EdgeX Version:**
Geneva release non-security Redis

**Anything else relevant?**

**Comment by weichou1229** [comment]
Issue fixed by PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/241 
It tags v0.1.59 but edgex-go use v0.1.58 currently.

**Comment by jpwhitemn** [comment]
I was not able to replicate this error with Geneva 1.2.1.  @weichou1229 - if you have additional information which suggests it is still an issue, please provide additional steps to reproduce and reopen the issue.
