### ISSUE TITLE
Error converting int64 to string in support-scheduler

### ISSUE THREAD

**Issue by phanvanhai** [edgexfoundry/edgex-go#2589]
https://github.com/edgexfoundry/edgex-go/blob/373c3ec415297c572841227f0503c779245cc382/internal/support/scheduler/schedule.go#L556

Error:
Scheduling with intervalaction-> method = "PUT" does not work while method = "GET" still works normally.

Fix: 
req.Header.Set(ContentLengthKey, strconv.FormatInt(int64(len(params)), 10))

**Comment by cloudxxx8** [comment]
@weichou1229 could you please check whether this issue still happens in V2?

**Comment by weichou1229** [comment]
This issue is fixed in V2.
https://github.com/edgexfoundry/edgex-go/blob/ca82cc67a24dd3a646f9c54faca12af7640f6229/internal/pkg/utils/restaddress.go#L82

**Comment by lenny-intel** [comment]
@jpwhitemn , we need to note this in the change log `Bug Fixes` section
