### ISSUE TITLE
mismatch between documentation and implementation of delete endpoints /event/device/{deviceId} and reading/device/{deviceId}/{limit}

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-go#2591]
# 🐞 Bug Report
Tested with **Insecure** EdgeX Foundry instance using **Redis** database

There is a mismatch between the documented supported APIs and the implementation when using redis database.

Openapi **core-data.yaml** file says: 
https://github.com/edgexfoundry/edgex-go/blob/5d263c9336f050d061fc6f0f587533ef9146dd01/api/openapi/v1/core-data.yaml#L105-L116
` description: The ID or name of the device associated  to events `

_(Tested with Redis database only)_
This endpoint works only when deviceName is provided. 
If deviceId is provided - there is no error, but nothing happens (no events are deleted)

Same issue appears  when trying to list reading by device 
Openapi **core-data.yaml** : 

https://github.com/edgexfoundry/edgex-go/blob/5d263c9336f050d061fc6f0f587533ef9146dd01/api/openapi/v1/core-data.yaml#L357-L373
The description for `deviceId` parameter is `Device ID or device name`

_(Tested with Redis database only)_
The endpoint list device readings limited by a number only if deviceName is provided. 
If deviceId is provide nothing happens - there is no error, but the returned list is empty

**Comment by difince** [comment]
Here are my insights after a research why such mismatch exists. 

- First of all, It figured out that the issue is not directly related with the underling database that is in use. So, I will rename the  issue removing Redis as a main reason of the issue. (@andresrinivasan )

- If I understand correct, these endpoints are intentionally created to work with both `deviceId` and `deviceName`. Actually the list of endpoints is larger. 

    **Events** related endpoints: 
    DELETE:   ​/v1​/event​/device​/{deviceId}  
    GET:          /v1/event/device/{deviceId}/{limit}
    GET:          /v1/event/count/{deviceId}

    **Readings** related endpoints:
    GET:        /v1/reading/device/{deviceId}/{limit}
    GET:        ​/v1​/reading​/name​/{name}​/device​/{device}​/{limit}

- The functionality that is supposed to validate and retrieve the device, no matter what is the provided parameter - deviceId or deviceName, is part of metadata endpoint **GET: /v1/device/check/{token}** The description of this endpoint is : `Obtain a device by either name or ID, where the ID must be a valid GUID.`

- So core-data or all the above endpoints make a call to core-metadata in order to retrieve the device, no matter what is the input parameter. But the problem comes that they do not care of the returned result. They just take care if the device exists or not. And they continue with logic manipulating the database using the parameter that comes from the user (that could be both deviceId/ deviceName) But what is the device data actually saved in the database under **reading.Device** and **event.Device** - the device ID or device Name ?!

- For both event and reading Create requests there is not restriction/validation what should be provided for filed Device - So, both device Id and Name could be provide ..or any other string?  Am I missing somethings here ?

In my understanding, the database format should be strictly specified. Then we could have endpoints that could handle double-purpose input parameters.  (@lenny-intel, @jpwhitemn )

**Comment by cloudxxx8** [comment]
When receiving event in core-data, there is a chance to validation the `device` field of Event
https://github.com/edgexfoundry/edgex-go/blob/07eb6246d5fb2c01df3c6ba4777e936c65ab9351/cmd/core-data/res/configuration.toml#L3

However, it still calls GET: /v1/device/check/{token}
Thus, id or name could both pass the check.

In Device Service SDK, we always send Event with device name, not id.
@difince I am not sure whether we should change it in V1 API because it might break the backward compatibility.
@jpwhitemn @lenny-intel we could decide whether we should restrict to `name` only in V2 API

**Comment by difince** [comment]
@cloudxxx8 I agree for not changing API v1
Let consider that for API v2 the evens are created using the device name only. 
All other GET requests could use this double purpose parameter - or be responsive on both deviceName And deviceId

**Comment by cloudxxx8** [comment]
@difince in V2 API, we have two checks for name and id respectively
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.x#/default/get_device_check_id__id_
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.x#/default/get_device_check_name__name_

**Comment by difince** [comment]
Thank you @cloudxxx8 
So, the issue is not going to exists in API v2. 

Anyway the issue is present  in API v1 and ...probably is not going to be fixed? Should the issue stay open  just to mark that the issue is known ?

**Comment by cloudxxx8** [comment]
@difince since we will not fix in V1 and will not exist in V2, I suggest we can close this issue with "wontfix" label.  Is it ok with you?

**Comment by difince** [comment]
Yep, it is ok. Thank you @cloudxxx8 
The issue is not going to exists within API v2, But will still remain in API v1 and won't be fixed.
