### ISSUE TITLE
Core services read configuration from hard-coded file

### ISSUE THREAD

**Issue by drasko** [edgexfoundry/edgex-go#26]
Core services currently read config file from hard-coded location: https://github.com/edgexfoundry/edgex-go/blob/master/cmd/core-command/main.go#L37

Go binaries should be portable, and probably end-up in `$GOBIN` (via `go install`). Also, very often `$GOBIN` is added to system path, so that these binaries are accessible system-wide.

Because they should be capable to start from different locations, they should be capable to accept config file location via command-line parameter or ENV variable.

For the sake of simplicity, I would suggest ENV variable here (easy to pass into Docker via `docker-compose `environment` parameter)

**Comment by tonyespy** [comment]
My vote would be for a command-line option, as environment variables can be set via a number of different ways, and thus can be hard to keep track of, whereas there's only one place a command-line argument can be specified, and it's easy to inspect the command-line options passed to a running process (at least it's easy on Linux, not sure about Windows).

**Comment by jpwhitemn** [comment]
Based on our Go project call yesterday, I have Trevor working on this for core-data.  We'll work on a few of these options and provide something for people to look at once we think we have something in place that we are satisfied with - and get everyone's opinion.  As we discussed yesterday, it would be nice to eventually replicate the type of escalating mechanism that Java has (property file, command line, ENV, etc.).  However, we might start simple and then incorporate other options as we go (and as we need) but try to facilitate that type of extension.

**Comment by drasko** [comment]
@tonyespy no need to open command line for passing just one single option: location of the file. this makes code more complicated - you are adding dependencies to parse command line options, send help to command line, etc - this SW will not be run by hand, it will be management service that will be running the services.

Using command line here in my opinion goes against programming principles of simplicity and producing tighter code with less binaries. Parsing command is not only useless but probably adds additional security risks, while all ENV variables can (and probably will be) stacked in Vault: https://www.vaultproject.io/intro/use-cases.html#general-secret-storage - _At a bare minimum, Vault can be used for the storage of any secrets. For example, Vault would be a fantastic way to store sensitive **environment variables**, database credentials, API keys, etc._

**Comment by tsconn23** [comment]
PR https://github.com/edgexfoundry/edgex-go/pull/75 created. Feel free to comment/approve.

**Comment by tsconn23** [comment]
PR has been merged. If there are no follow-up comments/discussion in 24 hours, I'll close the issue as resolved.

**Comment by tsconn23** [comment]
During a call with @jpwhitemn @tonyespy  this afternoon, it was decided we would add command line support as well. For now the order of precedence will be as follows:

1.) cmd line
2.) environment variable
3.) hard-coded location
