### ISSUE TITLE
Registry_Host env variable conflicts with -cp  parameter

### ISSUE THREAD

**Issue by difince** [edgexfoundry/edgex-go#2600]
# 🐞 Bug Report

### Affected Services

 All services that use Registry fails to start when both -cp parameter (config profider)  and Registry_Host env variable are provided.

### Description and Minimal Reproduction
All Dockerfiles files of EdgeX microservices have ENTRYPOINT that looks like this: 
`ENTRYPOINT ["/core-command","-cp=consul.http://edgex-core-consul:8500","--registry","--confdir=/res"]`

`-cp` (or config provider) parameter conflicts/takes precedence over **Registry_Host** environment variable. 
When both are provided log looks like this: 

> app=edgex-core-command source=environment.go:331 msg="Environment override of 'Registry.Host' by environment variable: **Registry_Host=edgex-consul.default.svc"**
> app=edgex-core-command source=config.go:167 msg="Using Configuration provider (consul) from: **http://edgex-core-consul:8500** with base path of edgex/core/1.0/edgex-core-command"
> app=edgex-core-command source=config.go:134 msg="configuration provider is not available" 
> ........
> app=edgex-core-command source=config.go:134 msg="configuration provider is not available"
> app=edgex-core-command source=registry.go:79 msg="Using Registry (consul) from **http://edgex-consul.default.svc:8500"**
> app=edgex-core-command source=bootstrap.go:43 msg="unable to register with Registry in allotted time"

All services fails to start when both -cp parameter  and Registry_Host env variable are provided.

See the entire log in section  **Exception or Error**

## 🔥 Exception or Error
<pre><code>
/tmp/___notification -confdir=/home/difince/git/edgex-go/cmd/support-notifications/res --registry -cp=consul.http://edgex-core-consul:8500 #gosetup
level=INFO ts=2020-06-25T13:01:43.679099033Z app=edgex-support-notifications source=config.go:219 msg="Loaded configuration from /home/difince/git/edgex-go/cmd/support-notifications/res/configuration.toml"
level=INFO ts=2020-06-25T13:01:43.680314159Z app=edgex-support-notifications source=environment.go:331 msg="Environment override of 'Registry.Host' by environment variable: Registry_Host=xaxa"
level=INFO ts=2020-06-25T13:01:43.680750908Z app=edgex-support-notifications source=config.go:167 msg="Using Configuration provider (consul) from: http://edgex-core-consul:8500 with base path of edgex/core/1.0/edgex-support-notifications"
level=ERROR ts=2020-06-25T13:01:43.682764997Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:44.685028773Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:45.687452094Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:46.690451277Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:47.692314066Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:48.694131671Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:49.695230244Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:50.697332985Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:51.699247758Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:52.701021609Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:53.702687396Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:54.704327698Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:55.705105882Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:56.705854836Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:57.707478743Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:58.708285985Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:01:59.709766242Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:00.71159384Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:01.712731978Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:02.713697616Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:03.715402015Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:04.717524654Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:05.719396572Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:06.721667203Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:07.723643246Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:08.725610451Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:09.727670263Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:10.728542184Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:11.730474093Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:12.732392911Z app=edgex-support-notifications source=config.go:134 msg="configuration provider is not available"
level=ERROR ts=2020-06-25T13:02:13.732739566Z app=edgex-support-notifications source=logger.go:74 msg="logTarget cannot be blank, using stdout only"
level=INFO ts=2020-06-25T13:02:13.732869032Z app=edgex-support-notifications source=registry.go:79 msg="Using Registry (consul) from http://xaxa:8500"
level=ERROR ts=2020-06-25T13:02:13.732990442Z app=edgex-support-notifications source=bootstrap.go:43 msg="unable to register with Registry in allotted time"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** 

**EdgeX Version:**

**Anything else relevant?**

**Comment by jpwhitemn** [comment]
@difince to get with @lenny-intel to cover separation fo registry/config
