### ISSUE TITLE
created timestamp always 0

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2602]
# 🐞 Bug Report

### Affected Services
Core Data

### Is this a regression?
Worked in Edinburgh but not Fuji and later

### Description and Minimal Reproduction
The created timestamp on event/reading is 0.  The created timestamp does get set in the database, but it is not set back into the event/reading and when the event/reading is pushed to app services (via 0MQ or message bus), the created timestamp is always zero.

in a nutshell -- Event param to AddEvent the event is not a pointer (https://github.com/edgexfoundry/edgex-go/blob/ad8ce46ea1b4c1cfb589e4a1128cf4f50d0a06e9/internal/pkg/db/mongo/data.go#L51)
the created and modified are being set here in this call just before save to DB but the call to put it on the bus happens after this call returns -- using the same event that was passed in -- which wont have those fields populated

## 🔥 Exception or Error
no exception or error - just no created timestamp

## 🌍  Your Environment
works the same for all environments

**EdgeX Version:**
Fuji or later

**Anything else relevant?**
See #core slack channel exchange around June 25 for exchange between bug finder and Lenny/Rocky

**Comment by lindseysimple** [comment]
@jpwhitemn Verified that the issue does not exist in the latest code in `main`. Since mongo will be removed in Hanoi, can we close this bug? Thanks.

**Comment by jpwhitemn** [comment]
This bug happens with Mongo or Redis.  I don't care about the Mongo implementation so much, but the Redis is very much an issue we need to address.  @rsdmike and @lenny-intel have both been able to replicate this easily and I think they were using the latest from master.  Would ask that they review and if they believe this issue is closed to signal the go ahead to close.

**Comment by lindseysimple** [comment]
@jpwhitemn Sorry I misunderstood the issue was happened on the app service side. I will continue investigate this issue, many thanks.
