### ISSUE TITLE
multiple arch docker images support

### ISSUE THREAD

**Issue by kaisawind** [edgexfoundry/edgex-go#2603]
# 🚀 Feature Request

### Relevant Package

 
all services docker images

### Description
 
It is not a good idea to use different docker images to distinguish different CPU architectures.
```
edgexfoundry/docker-core-data-go:1.2.0
edgexfoundry/docker-core-data-go-arm64:1.2.0
```

### Describe the solution you'd like
 
Why we don't use different image layer to distinguish different CPU architectures.
![深度截图_选择区域_20200630093340](https://user-images.githubusercontent.com/4010613/86072745-e362bd00-bab4-11ea-9680-918a9f0debfa.png)

Docker 19.03+ support `docker buildx` to build images of multiple architectures at once, and it doesn't need to change something many.
At least our official images can support multiple architectures.

### Describe alternatives you've considered
 
If we use  multiple arch images, we don't need to maintain multiple compose files or other k8s files.

**Comment by kaisawind** [comment]
BTW, we can use `docker manifest` to merge different images into one image.
```bash
#!/bin/bash
version=1.1.0
image=csedge/device-serial-go

docker manifest create ${image}:${version}-dev ${image}:${version}-arm64-dev ${image}:${version}-amd64-dev
docker manifest annotate ${image}:${version}-dev ${image}:${version}-arm64-dev --os linux --arch arm64
docker manifest annotate ${image}:${version}-dev ${image}:${version}-amd64-dev --os linux --arch amd64
docker manifest push -p ${image}:${version}-dev
```

**Comment by cloudxxx8** [comment]
@ernestojeda could you please bring this issue to DevOps meeting?  Thanks

**Comment by ernestojeda** [comment]
> @ernestojeda could you please bring this issue to DevOps meeting? Thanks

We discuss this a few weeks ago. We said we will are going to implement first in the app-service-configurable docker images. Once we get an OK from the App WG, we would implement this for other projects. Works is slated to begin in a few weeks. Just need to finalize the new edgex-go pipeline first.

**Comment by jpwhitemn** [comment]
Putting this in Core WG icebox until we get word from App/Analytics WG and DevOps on success.

**Comment by jpwhitemn** [comment]
Per TSC meeting of 7/29/20, with consultation of community members and users, this request is on indefinite hold.  There are two key issues that do not warrant moving in this direction at this time. 
- Losing visibility into DockerHub stats par architecture amd64 vs arm64 vs …
- Potential increased developer complexity working with individual images (ex: I am on Windows but want to pull down and work with an ARM image).

This can be reassessed in future roadmapping discussions.

**Comment by kaisawind** [comment]
I'm glad that we discuss this issue.
I think docker has two major features, isolation and cross-platform.Unfortunately, we cannot make full use of it.

> Losing visibility into DockerHub stats par architecture amd64 vs arm64 vs …

Yes, we will lose it, but i think we should not care it.

> Potential increased developer complexity working with individual images (ex: I am on Windows but want to pull down and work with an ARM image).

For docker
```bash
docker pull --platform xxxx xxxx
```
```bash
Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry

Options:
  -a, --all-tags                Download all tagged images in the repository
      --disable-content-trust   Skip image verification (default true)
      --platform string         Set platform if server is multi-platform capable
  -q, --quiet                   Suppress verbose output
```
For docker-compose(added 2.4, not 3.5,3.6, will support3.7[#1050](https://github.com/docker/cli/issues/1050))
```bash
Target platform containers for this service will run on, using the os[/arch[/variant]] syntax, e.g.
platform: linux/arm64/v8
```

Since windows can run linux containers(LCOW), cross-platform has become more and more complicated.
Splitting docker images is much easier for windows.
