### ISSUE TITLE
Query event API with limit always return first $n records when database use redis

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#2604]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-data

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction

1. Startup EdgeX with device-virtual which database use redis
2. Invoke the core-data API to get the events/reading limited to 5 records
http://localhost:48080/api/v1/event/device/Random-Integer-Device/5

## 🔥 Exception or Error
<pre><code>

</code>Always return first 5 records.</pre>
Should return the last 5 records.

## 🌍  Your Environment
**Deployment Environment:** ubuntu 18.04

**EdgeX Version:** geneva 1.2.1

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
It was fixed before https://github.com/edgexfoundry/edgex-go/issues/1643
However, it appears after fixing another bug
https://github.com/edgexfoundry/edgex-go/issues/2064
