### ISSUE TITLE
Module exploration - remove or replace github.com/armon/circbuf

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2615]
# 🚀 Feature Request

### Relevant Package
github.com/armon/circbuf

### Description
Based on exploration of dynamically versioned packages, this one showed significant issues against the Gregg/Espy defined criteria.  Explore means to replace or exclude it from use.  Otherwise document why it must be kept.

**Comment by tsconn23** [comment]
This package is used by Consul which most likely means it must be retained. I've attached a screenshot of the dependency graph but verbally, it is as follows:

```
github.com/hashicorp/consul/api@v1.1.0 -->
github.com/hashicorp/serf@v0.8.2 -->
github.com/armon/circbuf@v0.0.0-20150827004946-bbbad097214e
```

<img width="617" alt="Screen Shot 2020-08-18 at 1 15 19 PM" src="https://user-images.githubusercontent.com/1342980/90550078-0b85a880-e155-11ea-88f7-03a499a7a6be.png">

**Comment by tonyespy** [comment]
From the dependency graph, it's getting pulled in by hashicorp [serf](https://github.com/hashicorp/serf) which is the component used by consul for service discovery and orchestration. I checked and there aren't any issues filed against serf for circbuf usage, so maybe that's a good place for us to start (i.e. file an issue against serf)?

We also could check to see whether our usage of consul actually causes this code to be invoked. If it doesn't maybe we document it as such similar to the way we analyze CVE/security vulnerabilities?

**Comment by cloudxxx8** [comment]
@tonyespy We don't directly use this module.  Do we really need to find out our usage of consul actually causes this code to be invoked?  
I thought documenting why it must be kept is enough.
@jpwhitemn should we just document the reason on the wiki page?  https://wiki.edgexfoundry.org/display/FA/Vetting+Process+for+3rd+Party+Dependencies

**Comment by jpwhitemn** [comment]
@cloudxxx8 - yes, I'll document.  Obviously, we should try to avoid using this elsewhere, but will note this in current use.
