### ISSUE TITLE
Module exploration - remove or replace github.com/mitchellh/consulstructure

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2617]
# 🚀 Feature Request

### Relevant Package
github.com/mitchellh/consulstructure

### Description
Based on exploration of dynamically versioned packages, this one showed significant issues against the Gregg/Espy defined criteria.  Explore means to replace or exclude it from use.  Otherwise document why it must be kept.

**Comment by tsconn23** [comment]
This package is used by Consul. EdgeX relies on it in order to update `[Writable]` service configurations in real time.

In fact @lenny-intel landed a PR in this package.
https://github.com/mitchellh/consulstructure/pull/2

Recommend not removing/replacing.

**Comment by tonyespy** [comment]
Like with circbuf, maybe filing an issue against consul would be a good start. Like some of the other packages that have been flagged:

 * no releases / tags / issues
 * a single developer until Lenny contributed PR #2
 * before Lenny's PR, the last commit was two years ago 

If this is required for the official consul go client, then why isn't this a hashicorp repository?

**Comment by cloudxxx8** [comment]
@tonyespy Consul official API doesn't use it, and we use it directly in go-mod-registry and go-mod-configuration.
https://github.com/edgexfoundry/go-mod-registry/blob/1046cccd4841a3fd011f4d5cde55378f39b67fd6/go.mod#L5
https://github.com/edgexfoundry/go-mod-configuration/blob/4c1a00cd56993df88690e739771b983436048561/go.mod#L6
It's a simple code, so I also suggest to keep and document it.

**Comment by jpwhitemn** [comment]
documenting this and closing as done for circbuf
