### ISSUE TITLE
Module exploration - remove or replace github.com/pascaldekloe/goe

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2618]
# 🚀 Feature Request

### Relevant Package
github.com/pascaldekloe/goe

### Description
Based on exploration of dynamically versioned packages, this one showed significant issues against the Gregg/Espy defined criteria.  Explore means to replace or exclude it from use.  Otherwise document why it must be kept.

**Comment by tsconn23** [comment]
This package is ultimately used by Consul which most likely means it must be retained. I've attached a screenshot of the dependency graph but verbally, this package is referenced by the following:

```
github.com/hashicorp/consul/api@v1.1.0
github.com/hashicorp/memberlist@v0.1.3
```

<img width="891" alt="Screen Shot 2020-08-18 at 1 02 39 PM" src="https://user-images.githubusercontent.com/1342980/90548890-44bd1900-e153-11ea-91e0-935a74bdfe56.png">

**Comment by jpwhitemn** [comment]
Per other consul uses, closing this out and commenting on the Wiki 3rd party modules page.
