### ISSUE TITLE
Module exploration - remove or replace github.com/ryanuber/columnize

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2619]
# 🚀 Feature Request

### Relevant Package
github.com/ryanuber/columnize

### Description
Based on exploration of dynamically versioned packages, this one showed significant issues against the Gregg/Espy defined criteria.  Explore means to replace or exclude it from use.  Otherwise document why it must be kept.

**Comment by tsconn23** [comment]
This package is ultimately used by Consul which most likely means it must be retained. I've attached a screenshot of the dependency graph but verbally, it is as follows:

```
github.com/hashicorp/consul/api@v1.1.0 -->
github.com/hashicorp/serf@v0.8.2 -->
github.com/ryanuber/columnize v0.0.0-20160712163229-9b3edd62028f
```
Click to enlarge

<img width="696" alt="Screen Shot 2020-08-18 at 12 56 48 PM" src="https://user-images.githubusercontent.com/1342980/90548431-8c8f7080-e152-11ea-8754-557aa7e4bc93.png">

**Comment by jpwhitemn** [comment]
As with others associated to Consul, closing for now and marking this on the 3rd party package list on the wiki.
