### ISSUE TITLE
Module exploration - remove or replace github.com/sean-/seed 

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2620]
# 🚀 Feature Request

### Relevant Package
github.com/sean-/seed 

### Description
Based on exploration of dynamically versioned packages, this one showed significant issues against the Gregg/Espy defined criteria.  Explore means to replace or exclude it from use.  Otherwise document why it must be kept.

**Comment by tsconn23** [comment]
This package is ultimately used by Consul. I've attached a screenshot of the dependency graph but verbally, it is as follows:

```
github.com/hashicorp/consul/api@v1.1.0 -->
github.com/hashicorp/serf@v0.8.2 -->
github.com/hashicorp/memberlist@v0.1.3 -->
github.com/sean-/seed@v0.0.0-20170313163322-e2103e2c3529
```
<img width="1472" alt="Screen Shot 2020-08-18 at 10 32 17 AM" src="https://user-images.githubusercontent.com/1342980/90533697-7aa3d280-e13e-11ea-8723-bb9a962678a9.png">

**Comment by jpwhitemn** [comment]
Given connection to Consul, closing this for now and commenting this on our 3rd party package page on Wiki.
