### ISSUE TITLE
ADD_PROXY_ROUTE will break if URL contains dot characters

### ISSUE THREAD

**Issue by judehung** [edgexfoundry/edgex-go#2621]
# 🐞 Bug Report

### Affected Services

 The issue is located in: edgex-proxy 
https://github.com/edgexfoundry/edgex-go/blob/master/internal/security/proxy/service.go#L221

### Is this a regression?

 No, it's a new enhancement for Geneva release.

### Description and Minimal Reproduction
The PR from edgexfoundry/edgex-go#2474 introduces an enhancement that users could add additional Kong routes via environment variable ADD_PROXY_ROUTE. The value of ADD_PROXY_ROUTE takes a comma-separated list of one or more (at least one) paired additional service name and URL for which to create proxy Kong routes. The paired specification is in the format of **{RoutePrefix}.{TargetRouteURL}**. There is a potential bug here: if **{TargetRouteURL}** contains dot characters, e.g. an IP address, the route parsing logic will break, as the code simply use `routePair := strings.Split(route, ".")` to parse the route. To avoid this potential issue, the code should consider to only spilt **{RoutePrefix}.{TargetRouteURL}** into 2 substrings with the very first dot: `routePair := strings.SplitN(route, ".", 2)`

Steps to reproduce the issue:
1. Modify the docker-compose-geneva-redis.yml from the developer-script by adding the entry in the environment section of edgex-proxy for ADD_PROXY_ROUTE as shown below:
```
edgex-proxy:
  ...
  environement:
    ...
    ADD_PROXY_ROUTE: "myService.http://10.0.2.15:12345"
```
2. Run docker-compose up of edgex-proxy:
```
docker-compose -f docker-compose-geneva-redis.yml up edgex-proxy
```
and you shall observe an error as shown below

## 🔥 Exception or Error
<pre><code>
edgex-proxy               | level=ERROR ts=2020-07-10T12:34:07.63913068Z app=edgex-security-proxy-setup source=service.go:148 msg="failed to parse additional proxy Kong routes from env myService.http://10.0.2.15:12345: malformed host in route URL for additional kong route 10: address 10: missing port in address"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 18.04
**EdgeX Version:**
1.2.1

**Anything else relevant?**
None

**Comment by cloudxxx8** [comment]
fixed by #2622
