### ISSUE TITLE
Services receiving errors from HA Redis cluster

### ISSUE THREAD

**Issue by tianxingguo** [edgexfoundry/edgex-go#2628]
Hello there! 😄

Tried to replace redis with redis cluster for HA, but core-metadata got following error:
level=INFO ts=2020-07-14T08:22:48.214983834Z app=edgex-core-metadata source=config.go:219 msg="Loaded configuration from /res/configuration.toml"
level=ERROR ts=2020-07-14T08:22:48.216967634Z app=edgex-core-metadata source=logger.go:74 msg="logTarget cannot be blank, using stdout only"
level=INFO ts=2020-07-14T08:22:48.216997999Z app=edgex-core-metadata source=config.go:330 msg="Using local configuration from file (0 environment overrides applied)"
level=INFO ts=2020-07-14T08:22:48.221134173Z app=edgex-core-metadata source=database.go:146 msg="Database connected"
level=INFO ts=2020-07-14T08:22:48.225043517Z app=edgex-core-metadata source=telemetry.go:86 msg="Telemetry starting"
level=INFO ts=2020-07-14T08:22:48.225136109Z app=edgex-core-metadata source=httpserver.go:94 msg="Web server starting (0.0.0.0:48081)"
level=INFO ts=2020-07-14T08:22:48.225161462Z app=edgex-core-metadata source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2020-07-14T08:22:48.225179992Z app=edgex-core-metadata source=message.go:51 msg="Starting edgex-core-metadata 1.2.1 "
level=INFO ts=2020-07-14T08:22:48.225197955Z app=edgex-core-metadata source=message.go:55 msg="This is the EdgeX Core Metadata Microservice"
level=INFO ts=2020-07-14T08:22:48.225212094Z app=edgex-core-metadata source=message.go:58 msg="Service started in: 11.136261ms"
level=ERROR ts=2020-07-14T08:22:56.519649321Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:23:17.828290908Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:23:21.993357722Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:23:41.132730804Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:24:13.563131574Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:25:02.753838091Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:26:30.687207676Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:29:26.749469774Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:34:35.891309588Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:39:40.648137538Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:44:53.786749148Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:49:58.609573023Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T08:55:11.44253707Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T09:00:19.877402577Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"
level=ERROR ts=2020-07-14T09:05:28.850583396Z app=edgex-core-metadata source=handler.go:47 msg="MOVED 13735 10.42.0.162:6379"

**Deployment Environment:**

**EdgeX Version: Geneva

**Comment by cloudxxx8** [comment]
@andresrinivasan for awareness
is it expected?

**Comment by andresrinivasan** [comment]
This is not expected but it also has not been tested. @tianxingguo can you describe your HA setup in a little more detail and attach your config file? Also are you using Sentinel (and if so what's the details on that config)?

**Comment by tianxingguo** [comment]
Got 6 redis instances cluster, 3 for master and 3 for slave:
       instance0: master  instance3 ： slave
       instance1: master  instance4 ： slave
       instance3: master  instance5 ： slave

can follow https://redis.io/topics/cluster-tutorial to setup redis cluster.
And checked code, just used "github.com/gomodule/redigo/redis" to access redis db, but up to now redigo not support redis cluster.

**Comment by tianxingguo** [comment]
Redis Sentinel  is normal , but need config master node for core-metadata, core-date , core-command and support-notification ,since master for W and slave for R.

[Databases]
    [Databases.Primary]
	 Host = 'edgex-redis-master-0.edgex-redis-headless'
	 Name = 'coredata'
	 Password = 'password'
         Username = 'core'
	  Port = 6379
         imeout = 5000
       Type = 'redisdb'

**Comment by andresrinivasan** [comment]
> And checked code, just used "github.com/gomodule/redigo/redis" to access redis db, but up to now redigo not support redis cluster.

Ah. That's a non-trivial issue that we didn't consider as replication and clustering wasn't part of the requirements at the time of implementation. I must retract my earlier statement that this is unexpected; this won't work with the current implementation. We should consider this a feature request.

> Got 6 redis instances cluster, 3 for ~master~ primary and 3 for ~slave~ replicas:
instance0: ~master~ primary instance3 ： ~slave~ replica
instance1: ~master~ primary instance4 ： ~slave~ replica
instance2: ~master~ primary instance5 ： ~slave~ replica

> Redis Sentinel is normal , but need config ~master~ primary node for core-metadata, core-date , core-command and support-notification ,since ~master~ primary for W and ~slave~ replica for R.

For purpose of capturing requirements, I believe you're not looking for straight up replication (the Redis Sentinel scenario). I believe you're looking for Clustering and Replication. In other words, you want to shard across the multiple primary Redis instances, you want to scale your reads by using the replicas, and you want failover when the a primary fails.

Can you confirm this is indeed your requirements or elaborate on what your requirements are?

Since you want to shard your data, I'm guessing the size of your data exceeds the memory of a single server. Would you be able to describe the use case or problem in more detail? If you have a solution mapped it would also be helpful to understand your thinking there as well.

**Comment by tianxingguo** [comment]
Yes, from telecom industry lots of redis connections  from telecom devices simultaneously,  including reading connections and writing connections. One individual redis instance can not bear jumped-up and huge number of connections at same time , and not suppport 24 zero downing.So take the redis cluster way to meet the actual requirement.  Even Redis Sentinel can not meet, only one invidual master for writing. Hope Edgexfoundry also support redis cluster, not only Redis Sentinel.

**Comment by jpwhitemn** [comment]
@tianxingguo - this is a non-trivial effort and one not supported by the project at this time (and not really covered in our supported edge use at this time).  Should you or others like to assist in exploring this requirement and potential EdgeX addition going forward, please reach out and we can look at adding it to the project roadmap.
