### ISSUE TITLE
Add metrics for Edgex to enhance the system monitor

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#263]
**Metrics** and **Log** are two basic parts of a stable system. For enhancing the EdgeX's stability we should consider to monitor it in the future. The monitor would need to be provided metrics. So we should introduce the metrics infrastructure for it.

There are a few scenario where we could add metrics: 

* device data import count / rate;
* support notification count / schedule count (trigger count)
* export data count / rate;
* ....

Although, metrics and log sometimes can match the same goal(provide information to calculate/aggregate/analysis). But they are different, here is a [good article](https://www.wavefront.com/metrics-vs-logs-dilemma-part-2/) described the difference between them.

I find a popular go metrics package : [go-metrics](https://github.com/rcrowley/go-metrics), which can write metrics into InfluxDB. And using this (we can also implement a logger to write log into InfluxDB), we could integrate the metrics with InfluxDB's full technology stack (monitor, dashboard, storage, computing).

What's your idea? @jpwhitemn and @drasko

**Comment by drasko** [comment]
@yanghua good point here.

In Mainfllux we use metrics (and logs of course) for every service, something like this: https://github.com/mainflux/mainflux/blob/master/http/api/metrics.go, and those are then exported to Prometheus. We are using [go-kit metrics](https://godoc.org/github.com/go-kit/kit/metrics) because we are using go-`kit` in Mainfux, but `go-metrics` looks like a nice package and a good candidate for EdgeX.

**Comment by yanghua** [comment]
@jpwhitemn if this idea been accepted, I will try to contribute a input plugin to [Telegraf (The plugin-driven server agent for collecting & reporting metrics)](https://github.com/influxdata/telegraf) for EdgeX. This work will promote EdgeX's connectivity with other ecosystem and make EdgeX easy to monitor.

**Comment by tsconn23** [comment]
Closing this issue per further discussion via Core WG and System Mgmt WG. There are several actionable items here which can be re-added to the issues list once we have decided on directions via the working groups.
