### ISSUE TITLE
Redis startup race condition - Not setting up DB credentials

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2636]
# 🐞 Bug Report

### Affected Services
Continuation from #2542 - while fix worked for Geneva, there was a suggestion on the part of Tony and Andre needed for Hanoi going forward:

Tony:  Re: [ -s ], isn't it still possible for the the file to be partially written when this check is made? Wouldn't a semaphore file be safer?
Andre: Given the length of the password and the typical I/O buffer, it is unlikely for a partial write to occur.

When Geneva is released, I'm going to rewrite security-secretstore-read to eliminate the password file altogether and set the password directly in Redis.

### Is this a regression?
temp solution in Geneva

### Description and Minimal Reproduction
see #2542

**Comment by hutchic** [comment]
decided this is a duplicate of https://github.com/edgexfoundry/edgex-go/issues/2636 going to track progress on that issue going forward

**Comment by andresrinivasan** [comment]
@hutchic Did you mean to close this issue (#2636) or a different one?
