### ISSUE TITLE
Add Update YAML Device Profile to Core Metadata V2 API

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#2639]
# 🚀 Feature Request

### Relevant Package

 This feature request is for Core Metadata V2 API

### Description

Currently V1 and V2 (WIP) only support `Add YMAL Device Profile` while they support `Add & Update JSON Device Profile`. YAML has become the defact'o format for device profiles since all the EdgeX Device services provide default device profiles written in YAML. So it makes sense that EdgeX V2 support `Update YAML Device Profile`.

### Describe the solution you'd like

Add `UpdateYamlProfile` to V2 swagger. Implementation should simply un-marshal back to JSON and use `UpdateJsonProfile`

### Describe alternatives you've considered
Do nothing and  force user to use JSON for updates.

**Comment by weichou1229** [comment]
@lenny-intel Does the device profile need to support the Patch operation?

**Comment by cloudxxx8** [comment]
for YAML, we don't support patch, only support Put the whole YAML file

**Comment by lenny-intel** [comment]
Agreed, for YAML file Update is a Replace. i.e. the whole new updated file has to be uploaded.
