### ISSUE TITLE
core-domain the data type of attributes field in DeviceObject is not generic "object"

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#264]
In the original data model design, the data type of attributes field in DeviceObject is a generic "object".
In the current source code, it is map[string]string, which restrict the extension capability of data model.
https://github.com/edgexfoundry/edgex-go/blob/master/core/domain/models/deviceobject.go

Different kinds of device resource might need different kinds of attributes.
map[string]string means the attribute value can only be string type.  For example, if any of attribute is an array, the following error will occur:
unmarshal errors:
  line 85: cannot unmarshal !!seq into string

**Comment by tsconn23** [comment]
@cloudxxx8 Is there a specific test case where you came across this issue? Golang doesn't have an object type in the same manner as Java. If you have a specific use case, we can look at it to try and devise a solution.

**Comment by cloudxxx8** [comment]
@tsconn23 
We are using different kinds of devices and protocols, and they all have different attributes.  We need the capability to extend the domain model to fit the variety of IoT requirement.  The attribute might numeric type, an array, or another object.  I believe lots of users will encounter the same issue.
In order to set it as generic object in golong, we can simply use map[string]interface{} to replace map[string]string

**Comment by cloudxxx8** [comment]
@tsconn23 
In Device and DeviceProfile domain model, we have already used interface{} for location and objects field
https://github.com/edgexfoundry/edgex-go/blob/master/core/domain/models/device.go
https://github.com/edgexfoundry/edgex-go/blob/master/core/domain/models/deviceprofile.go

**Comment by tsconn23** [comment]
@cloudxxx8 Since you have an approach and know how to duplicate the error condition, do you want to make that code change, test it and then submit a PR? Sounds like a 1 line change.

**Comment by cloudxxx8** [comment]
ok, please assign this issue to me.
I will run the unit test and black box test to make sure it works fine before creating the pull request

**Comment by cloudxxx8** [comment]
@tsconn23 
please help review the change, thanks
https://github.com/edgexfoundry/edgex-go/pull/275

**Comment by tsconn23** [comment]
Merged. Thanks.
