### ISSUE TITLE
Dockerfiles incorrectly use ENTRYPOINT when they should use CMD.

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#2643]
# 🚀 Feature Request

### Relevant Package

 This feature request is for all edgex-go services

### Description
 A clear and concise description of the problem or missing capability...
Per docker documentation:
`The main purpose of a `CMD` is to provide defaults for an executing container`
https://docs.docker.com/engine/reference/builder/#cmd
While `An ENTRYPOINT allows you to configure a container that will run as an executable`
https://docs.docker.com/engine/reference/builder/#entrypoint

Here is an example for Consul which has an entrypoint script and a command
https://github.com/hashicorp/docker-consul/blob/master/0.X/Dockerfile#L75

Also, security-proxy-setup is done correctly:
https://github.com/lenny-intel/edgex-go/blob/master/cmd/security-proxy-setup/Dockerfile#L30
In this case they want to be able to override the command-line options without specifying the executable. Another way of combining `ENTRYPOINT` and `CMD`

### Describe the solution you'd like

1. Simply change `ENTRYPOINT ` to `CMD`
    Overrides of `CMD` in compose file have to include the executable.
2. Leave the executable in `ENTRYPOINT ` and move command-line options to `CMD`
   Overrides of `CMD` in compose file are then just the command-line options.
   Similar to security-proxy-setup 

### Describe alternatives you've considered
None

**Comment by lenny-intel** [comment]
Some more examples:
https://github.com/eclipse/mosquitto/blob/f39bf49f9059bfbf2b802fbe8ea435dab42ebf0c/docker/1.5/Dockerfile
https://github.com/docker-library/redis/blob/bfd904a808cf68d4b5ecc267bb4d4a1a0ca5f921/5.0/alpine/Dockerfile
https://github.com/emqx/kuiper/blob/master/deploy/docker/Dockerfile
https://github.com/Kong/docker-kong/blob/60626098f2f32fe1528eb4ffacff13fd1c3e919f/alpine/Dockerfile#L47
https://github.com/nats-io/nats-streaming-docker/blob/f3b3e48bdaa499e7f583e4cd0034df31a08644a6/0.18.0/scratch/Dockerfile#L4

**Comment by lenny-intel** [comment]
In Core WG meeting on 7/30/20 we agreed for those services that do not have actual entrypoint scripts to set ENTRYPOINT=<executable> and CMD=<command-line options>.

**Comment by lenny-intel** [comment]
Venkat from Intel DevOps is taking this. @ernestojeda assigned as proxy.

**Comment by bnevis-i** [comment]
Request that whatever changes are made be compatible with the [bootstrapping ADR](https://github.com/edgexfoundry/edgex-docs/issues/133).  We are currently overriding command in a number of containers to control startup initialization.

**Comment by lenny-intel** [comment]
@bnevis-i, great point!! I reviewed the current compose files and found that the only edgex-go service that has override of  `CMD`  is `security-secrets-setup`.  `security-secrets-setup` has an actual entrypoint script, so the docker file for this service will not change.
