### ISSUE TITLE
Add clients to interact with core-data service

### ISSUE THREAD

**Issue by dylanhantula** [edgexfoundry/edgex-go#265]
There is currently a client for getting, posting, and updating value descriptors in the core-data service - it can be found at _edgex-go/core/clients/coredata/coredata-clients.go_. In my own projects, I have used this client when creating device service applications to make registering value descriptors easier. There are similar clients in core-metadata for interacting with addressables, commands, devices, device profiles, and device services. 

There is no counterpart client for getting, posting, and updating events and readings in core-data, however. This means that all of the REST calls pertaining to events and readings need to be crafted manually by the developer, which can be cumbersome. PR #260 addresses this by creating methods around the REST calls to core-data for events and readings.

**Comment by tsconn23** [comment]
As a follow-up, I acknowledge that we are handling external calls by deserializing raw JSON within EdgeX to our internal domain models today. For example:

_/edgex-go/core/metadata/rest_addressable.go_
```
func restAddAddressable(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	var a models.Addressable
	err := json.NewDecoder(r.Body).Decode(&a)
        ...
}
```

This isn't really good practice.

**Comment by tonyespy** [comment]
As mentioned yesterday during our devices f2f meeting, I'd actually started working on an Core Data events REST endpoint for my Go device SDK work, so it's great to find out that there's some existing code to handle this. @tsconn23 What needs to happen to land this code?
