### ISSUE TITLE
new version openapi yaml is not working in postman

### ISSUE THREAD

**Issue by augustine-lin** [edgexfoundry/edgex-go#2650]
# 📚 Docs or Wiki Bug Report

### Description

new version openapi can not import by postman

### What's the affected URL?**

https://github.com/edgexfoundry/edgex-go/tree/master/openapi

When I import the yaml of v1 or v2, postman will say "failed to import data format not recognized"

### Expected vs Actual Behavior**

openapi should be import by postman

## 📷Screenshot 

<img width="527" alt="螢幕快照 2020-07-31 下午3 08 09" src="https://user-images.githubusercontent.com/63775049/89009698-ac93f700-d33f-11ea-9cc3-c8a70310747c.png">

**Comment by weichou1229** [comment]
@augustine-lin you should try the raw link, it works on my postman.
https://raw.githubusercontent.com/edgexfoundry/edgex-go/master/openapi/v2/core-metadata.yaml

**Comment by augustine-lin** [comment]
@weichou1229 Thank your response 
I use the raw link still not working. 
I will re download postman and try it. 

<img width="531" alt="螢幕快照 2020-07-31 下午3 49 35" src="https://user-images.githubusercontent.com/63775049/89013024-c1738900-d345-11ea-93e2-7e6610078645.png">

**Comment by augustine-lin** [comment]
@weichou1229 download the newest postman and it work. thank you!
