### ISSUE TITLE
Upgrade to Go 1.15.1

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2680]
# 🚀 Feature Request

### Relevant Package
All Dockerized services from edgex-go

### Description
Upgrade all services to use Go 1.15.1.

### Describe the solution you'd like
Update the Dockerfile to use golang:1.15-alpine base image

### Describe alternatives you've considered
n/a

**Comment by lenny-intel** [comment]
The following files also need to be updated:

- Dockerfile.build
- go.mod
- README.md
- snap/snapcraft.yml
- snap/local/build-helpers/bin/go-build-helper.sh (in comment)
