### ISSUE TITLE
[notifications] support long / HTML email messages

### ISSUE THREAD

**Issue by AlexCuse** [edgexfoundry/edgex-go#2682]
# 🚀 Feature Request

### Relevant Package

 
support-notifications

### Description
 A clear and concise description of the problem or missing capability...
The email channel in the notification service cannot send HTML messages.  It also cannot send plain text messages over 1000 characters.  

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
I have broken out the message formatting component of sending_service.sendMail like so - contentType is passed in from the property on the notification.

```go
func sendMail(
	message string,
	addressees []string,
	contentType string,
	lc logger.LoggingClient,
	smtp notificationsConfig.SmtpInfo) models.TransmissionRecord {

	tr := getTransmissionRecord("SMTP server received", models.Sent)

	smtpMessage := buildSmtpMessage(smtp.Subject, contentType, message)

	err := smtpSend(addressees, smtpMessage, smtp)
	if err != nil {
		lc.Error("Problems sending message to: " + strings.Join(addressees, ",") + ", issue: " + err.Error())
		tr.Status = models.Failed
		tr.Response = err.Error()
		return tr
	}
	return tr
}

func buildSmtpMessage(subject string, contentType string, message string) []byte {
	// required CRLF at ends of lines and CRLF between header and body for SMTP RFC 822 style email
	buf := bytes.NewBufferString("Subject: " + subject + "\r\n")

	// only add MIME header if notification content type was set
	// maybe provide charset overrides as well?
	if contentType != "" {
		buf.WriteString(fmt.Sprintf("MIME-version: 1.0;\r\nContent-Type: %s; charset=\"UTF-8\";\r\n", contentType))
	}

	buf.WriteString("\r\n")

	//maximum line size is 1000, insert newlines in message if needed
	ln := 998
	idx := 0

	for len(message) > idx+ln {
		buf.WriteString(message[idx:idx+ln] + "\r\n")
		idx += ln
	}

	buf.WriteString(message[idx:] + "\r\n")
	
	return []byte(buf.String())
}
```

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Tried preformatting the message and including header but felt dirty forcing SMTP implementation details into consumers.  Could conceivably do it as an application service facade.

I am undecided about whether it would be useful to update go-mod-core-contracts to include character set on the notification.  Could be something configured at the service level as well, or maybe inferred from the environment.  

I also considered a similar approach using `bytes.Runes([]byte(message))` for chunking the message but since we are doing this to conform to the SMTP protocol I'm not sure how much this matters.  It might come into play more for other character sets, and is an easy enough change to make.

I will start adding test coverage now but can open a PR if desired once these questions are resolved.  May be good to do some refactoring of sending_service as well to make it easier to test in general but I won't do that if I'm going to be maintaining a fork for awhile :)

**Comment by AlexCuse** [comment]
As part of this change I am also updating the rest sends to use the content type if provided, otherwise default to text/plain that is used currently.

**Comment by jpwhitemn** [comment]
@AlexCuse - per the core working group meeting today, we decided that this feature/enhancement request is a good one and should be incorporated into EdgeX.  However, at this time, we don't believe we'll have the team resources to get this in for the Hanoi release.  If you think you can submit a PR to get your suggested changes in per above, we will review it and incorporate it in Hanoi.  Otherwise, we will add this to the tasks for the Ireland release.  Let me know so I know how to attach this to the correct release.

**Comment by AlexCuse** [comment]
@jpwhitemn I should be able to get it done in fairly short order if I don't dive right into refactoring that sending_service.  This is what I have right now, adds fairly decent coverage to the changes I've made so far.

https://github.com/AlexCuse/edgex-go/commit/27fd4bd4a4b458e22158ce5413900ee98c3d7025

It doesn't seem to me like adding charset overrides is terribly urgent considering what is there now but I can keep that on the radar down the road, I probably will come back and refactor the sending service when time allows.

**Comment by jpwhitemn** [comment]
perfect - thanks @AlexCuse.  I'll put this in the in-progress bucket.  If there are parts you leave for a future date, please create another issue for them so that we don't lose them (label them Ireland).

**Comment by AlexCuse** [comment]
I thought about adding a subject on the notification or subscription to override configuration as well @jpwhitemn - maybe would be good to do that along with charset changes at the same time since both would require changing go-mod-core-contracts as well.
