### ISSUE TITLE
Pre-populate the event ID with a UUID

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2684]
# 🚀 Feature Request
Make ID field of event required and provided before passing to core data for persistence.

### Relevant Package
core data and core contracts

### Description
This feature began as an ADR (see https://github.com/edgexfoundry/edgex-docs/pull/227).  Per the discussion, the idea is to 
generate a UUID and assign it to the id field before storing the event to the database. If the id field was empty at the time of persistence, then have core data generate a UUID (or just have the ID field as required making clients provide the UUID in the ID).

Per @lenny-intel - this also solves why we used checksum in the first place for CBOR encoded events. Now the ID will be set in the CBOR encoded Event and accessible in App Service once it is un-marshaled. Then we only need to have the MarkAsPushedById API.

### Describe alternatives you've considered
addition of a new UUID property to event

**Comment by lenny-intel** [comment]
Do we want to make the ID required in the Event DTO or simply set it in AddEvent API as soon as the event is received?

**Comment by jpwhitemn** [comment]
Per core WG meeting today, the following was decided:
1) the field id becomes a required field and must be populated before being sent to core data.  This will make sure the event has a UUID even when/if we get to a point where device services bypass core data and start sending events directly to application services.
2) the population of the UUID in the id field for event should be part of initialization of the event in contracts.
