### ISSUE TITLE
"ping" to core-metadata succeeds although the service is not ready to handle requests

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/edgex-go#2692]
# 🐞 Bug Report

### Affected Services

 The issue is located in:  core-metadata

### Description and Minimal Reproduction
See [device-sdk-go #577](https://github.com/edgexfoundry/device-sdk-go/issues/577)
The device service has checked the availability of core-metadata but when it tries to call its API, errors indicate that the database is not yet loaded

**Comment by cloudxxx8** [comment]
this should be able to be fixed by modifying the bootstrap code

**Comment by jpwhitemn** [comment]
Is this still an issue with new V2 code (in secure and non-secure mode)?  Is this OBE?
Critical enough issue because it determines when our services our ready.
