### ISSUE TITLE
Dry_Run alway got "true" when executing swagger publish on Jenkins build 

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#2698]
# 📚 Docs or Wiki Bug Report

### Description
 
Swagger publish always got dry-run to true and the API docs didn't publish to SwaggerHub.
The latest update in SwaggerHub is 21 July.
All API docs on edgex-go and app-functions-sdk-go didn't publish to swaggerhub when building images.

### What's the affected URL?**
 https://docs.edgexfoundry.org/...

### Expected vs Actual Behavior**

 API documents publish to SwaggerHub successfully.

## 🔥 Exception or Error
<pre><code>

00:07:55  [edgeXSwaggerPublish]: Setting up Environment and Executing Publish. - DRY_RUN: true
[Pipeline] withEnv
[Pipeline] {
[Pipeline] configFileProvider
00:07:55  provisioning config files...
00:07:55  copy managed file [swaggerhub-api-key] to file:/w/workspace/edgex-go/142@tmp/config4008615169615879990tmp
[Pipeline] {
[Pipeline] libraryResource
[Pipeline] sh
00:07:55  --> edgex-publish-swagger.sh
00:07:55  === Publish openapi/v1 API ===
00:07:55  [publishToSwagger] Publishing the API Docs [openapi/v1] to Swagger
00:07:55  [publishToSwagger] Publishing API Name [core-command]
00:07:55  [publishToSwagger] Dry Run enabled...Simulating upload
00:07:55  curl -X POST https://api.swaggerhub.com/apis/EdgeXFoundry1/core-command?oas=3.0.0&isPrivate=false&force=true
</code></pre>
[edgex-go build job](https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-go/job/master/142/consoleFull) 
[app-functions-sdk-go build job](https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/app-functions-sdk-go/job/master/119/console)

**Comment by cloudxxx8** [comment]
@ernestojeda could you please help take a look? thanks

**Comment by ernestojeda** [comment]
@soda480 Can you take a look at this?

**Comment by bill-mahoney** [comment]
@ernestojeda , @soda480 , maybe we can discuss which option for fixing this early next week 

The edgeXSwaggerPublish function implements the DRY_RUN pattern where unless DRY_RUN is set to `false` explicitly, it will only simulate an action and will not execute it.

It looks like this pattern is mostly implemented in operations found in cd-management/release yaml files (e.g. edgeXReleaseGitHubAssets, edgeXReleaseDockerImage,  etc.)

For this issue in edgex-go, the edgeXSwaggerPublish is being called from a Jenkinsfile where the DRY_RUN flag is not declared. So the edgeXSwaggerPublish function safely executes in DRY_RUN mode.

1) We could implement the DRY_RUN environment variable within the edgex-go Jenkinsfile, explicitly setting it to FALSE.
2) Remove the DRY_RUN check within edgeXSwaggerPublish
3) Create a version of edgeXSwaggerPublish to be executed from the release flow and a different method to be executed from a repository CI Jenkinsfile flow.  (Similar to how edgeXDocker and edgeXReleaseDockerImage is working)

A question we might ask is if the SwaggerPublish docs are ever released via the cd-management/release at release time or just after every PR merge to main? I don't see any release.yaml using edgeXSwaggerPublish right now.

**Comment by cloudxxx8** [comment]
@bill-mahoney we want the Swagger document to be published in each PR merged, not only release.

**Comment by soda480** [comment]
Another option would be to reverse the condition (i.e. logic) within `edgeXSwaggerPublish` to check if DRY_RUN is explicitly set to true.
This would allow us to maintain a DRY_RUN pattern in `edgeXSwaggerPublish` and not be forced to explicitly set DRY_RUN variable to True in all the Jenkinsfile that current publish to Swagger.

Are there any other repos (besides `edgex-go`) that publish to Swagger?

**Comment by cloudxxx8** [comment]
https://github.com/edgexfoundry/app-functions-sdk-go/tree/master/openapi/v2 should also be published, and https://github.com/edgexfoundry/device-sdk-go/tree/master/openapi is going to be implemented the auto publication
