### ISSUE TITLE
[metadata] Unable to update adminState and operatingState at the same time

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#2703]
# 🐞 Bug Report

### Affected Services

 The issue is located in: metadata (@iain-anderson found this issue)

### Is this a regression?

 No

### Description and Minimal Reproduction
Start EdgeX core services and device-virtual service, then do:
```
curl -v -X PUT -d '{"adminState":"UNLOCKED","operatingState":"DISABLED"}' 0:48081/api/v1/device/name/Random-Boolean-Device
*   Trying 0.0.0.0...
* TCP_NODELAY set
* Connected to 0 (127.0.0.1) port 48081 (#0)
> PUT /api/v1/device/name/Random-Boolean-Device HTTP/1.1
> Host: 0:48081
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 52
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 52 out of 52 bytes
< HTTP/1.1 200 OK
< Date: Thu, 24 Sep 2020 08:38:50 GMT
< Content-Length: 0
< 
* Connection #0 to host 0 left intact
* Closing connection 0
```

The update request returns a 200 OK, and the device service gets the callback to indicate that the device is updated. However when I do curl 0:48081/api/v1/device/name/Random-Boolean-Device again, the operatingState still shows as ENABLED. (And indeed the device service continues to have it enabled).

**EdgeX Version:**nightly-build

**Anything else relevant?**
According to https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/metadata/rest_device.go#L419-L493,  PUT _/api/v1/device/name/{name}_ and _/api/v1/device/id/{id}_ only update the first device state specified in the request body.

**Comment by jpwhitemn** [comment]
Was this bug fixed as part of the 1.3.1 metadata fix?  Is if fixed in V2?

**Comment by iain-anderson** [comment]
Works in v2, although the API is a little different:
`curl -X PATCH -d '[{"apiVersion":"v2", "Device":{ "name":"Device1", "adminState":"UNLOCKED", "operatingstate":"UP"}}]' 0:48081/api/v2/device`

**Comment by cloudxxx8** [comment]
@weichou1229 could you please make a quick test to see whether we have fixed in Hanoi? (1.3.1 core-metadata)

**Comment by weichou1229** [comment]
No, we haven't. 

The API updates OperatingState if AdminState not supplied.
https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/metadata/rest_device.go#L399

**Comment by cloudxxx8** [comment]
@iain-anderson could you workaround this issue by sending two update requests and close this issue, since it is fixed in v2?

**Comment by iain-anderson** [comment]
Hi @cloudxxx8 it's not an issue for me, just observed it when manually updating something. Feel free to close (I don't have permissions in this repository)
