### ISSUE TITLE
[metadata] If a Device's Service is modified, only the new DS is notified

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/edgex-go#2716]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-metadata

### Is this a regression?

 No

### Description and Minimal Reproduction
Use a PUT request to api/v1/device to change a device's associated device service. The device record is correctly modified and a callback is sent to the new device service, but no callback is sent to the old device service.

## 🌍  Your Environment
**Deployment Environment:** Services running native on ubuntu 20.04

**EdgeX Version:** edgex-go master

**Anything else relevant?**

**Comment by jpwhitemn** [comment]
@cloudxxx8 @iain-anderson Can this Issue be closed as the associated PR merged??

**Comment by iain-anderson** [comment]
> @cloudxxx8 @iain-anderson Can this Issue be closed as the associated PR merged??

Yes
