### ISSUE TITLE
[V2] Correlatioin id key should be X-Correlation-ID 

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2724]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-data

### Is this a regression?
No

### Description and Minimal Reproduction
In the new V2 API design, correlation id key in the header should be `X-Correlation-ID`, but the current implementation reuse the V1 key `Correlation-Id`

## 🌍  Your Environment
**EdgeX Version:**
master

**Comment by lenny-intel** [comment]
I have found we have two constants for Correlation ID. `Correlation-Id` is consistently used TRACE logging and `X-Correlation-ID` for the HTTP header. It is confusing when developing. I would be good with just using `X-Correlation-ID` everywhere.

**Comment by cloudxxx8** [comment]
This issue will be fixed in https://github.com/edgexfoundry/go-mod-core-contracts/pull/317
In edgex-go, we should update v1 swagger files if it is merged

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/go-mod-core-contracts/pull/317, and there is no Correlation-Id defined in V1 swagger
