### ISSUE TITLE
[All] Delete by Id API could delete other model in Redis

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2731]
# 🐞 Bug Report

### Affected Services

 The issue is located in: all services with Delete by Id API

### Is this a regression?
No

### Description and Minimal Reproduction

1. Execute the Delete by Event Id API in core-data with a Reading Id
2. Reading object is deleted

Since Redis is a key/value store and we store the Id as the key.

## 🔥 Exception or Error
No particular error, but it is not the correct behavior

## 🌍  Your Environment
**Deployment Environment:**
with Redis DB
**EdgeX Version:**
master

**Comment by cloudxxx8** [comment]
We could fix it in V2 API by using the pre-fix in the key for different models

**Comment by jpwhitemn** [comment]
There is a work around for this in V1 API, will be fixed with V2 API implementation
Just use the correct API to delete the object and this works.
Not going to fix V1 API.
