### ISSUE TITLE
Refactor the pkg.Encode func name more meaningful

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#2753]
# 🚀 Feature Request

### Relevant Package

This feature request is for **internal/pkg/encoding.go**

### Description
Since we use pkg.Encode in lots of function but the function name is not clear, so we need to refactor the function name more meaningful.
The discussion can refer to the comment https://github.com/edgexfoundry/edgex-go/pull/2701#discussion_r492926156.

### Describe the solution you'd like
Refactor name to EncodeAndSend

**Comment by jpwhitemn** [comment]
@weichou1229 @cloudxxx8 - in scope for Hanoi or Ireland?

**Comment by lenny-intel** [comment]
@jpwhitemn, This is TechDebt that I would push to Ireland.

**Comment by cloudxxx8** [comment]
We can't make this refactor until removing the v1 code.
It's an internal change without breaking backward compatibility.

**Comment by jpwhitemn** [comment]
Discussed in the Kamakura planning meeting (Nov 21) and deemed in scope for Kamakura release.
