### ISSUE TITLE
[V2] Discuss we should use id or name as the reference between objects

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2801]
# 🚀 Feature Request

### Relevant Package

 This feature request is for V2 API

### Description
In 15-OCT-2020 Core WG meeting, there is a discussion about we should use id or name as the reference between objects.  Currently we use name to reference objects.  However, it would make name become immutable.

**Comment by jpwhitemn** [comment]
OBE - already covered through V2 implementation.
