### ISSUE TITLE
Remove All Heartbeat Logging Messages from Services

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#282]
It was decided during the Palo Alto F2F that we would remove the heartbeat logging messages from all services. Heartbeats are triggered in each service's main.go and implemented in internal/pkg/heartbeat.

**Comment by yanghua** [comment]
@tsconn23 can I claim this issue?

**Comment by tsconn23** [comment]
@yanghua Go ahead.

**Comment by tsconn23** [comment]
Audit anything that imports internal/pkg/heartbeat
