### ISSUE TITLE
Can not delete interval action with version 1.2.0

### ISSUE THREAD

**Issue by tianxingguo** [edgexfoundry/edgex-go#2824]
Hi , there
  I tried  to delete a interval action  via postman , not long time no any response. But can query the interval action detail
 url : http://192.168.2.249:48085/api/v1/intervalaction/name/sss

![image](https://user-images.githubusercontent.com/12626589/96550631-ad577c00-12e3-11eb-896e-ed59a80073b9.png)

**Comment by tianxingguo** [comment]
Hi, there
  probably too many schedulers are running or support-scheduler service running too long , then blocking the deleting request.

**Comment by cloudxxx8** [comment]
@tianxingguo thanks for reporting this issue.  we will see how to improve it.

**Comment by weichou1229** [comment]
@tianxingguo 
We've made the V2 API, could you please help verify this issue with the new version API? 

You can pull and run the latest build image from the https://github.com/edgexfoundry/edgex-compose/blob/master/docker-compose-no-secty.yml.
The V2 API to create the interval:
```
curl http://0.0.0.0:59861/api/v2/interval -X POST -H "Content-Type: application/json" -d '[
    {

      "apiVersion":"v2",
      "interval": {
          "name": "20seconds",
          "interval": "20s"
      }
    }
  ]'
```

The V2 API to create intervalAction:
```
curl http://0.0.0.0:59861/api/v2/intervalaction -X POST -H "Content-Type: application/json" -d '[
    {
      "apiVersion":"v2",
      "action": {
          "name": "Get-Int32Array",
          "intervalName": "20seconds",
          "address":{
              "type": "REST",
              "httpMethod": "GET",
              "host": "edgex-core-command",
              "port": 59882,
              "Path": "/api/v2/device/name/Random-Integer-Device/Int32Array?ds-pushevent=yes"
          },
          "adminState":"UNLOCKED"
      }
    }
  ]'
```

If you got any issues, please provide the steps for reproducing the error, thanks.
