### ISSUE TITLE
Remove Unused Schedule Property from domain/models/event.go

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#283]
This property was added to the model by mistake during the Java --> Go conversion. It is handled and persisted to the DB but its value is always empty. It shouldn't be present on the event, so we need to remove it and any associated handling.

**Comment by yanghua** [comment]
@tsconn23 can I claim this issue?

**Comment by tsconn23** [comment]
@yanghua Yes, that's fine.
