### ISSUE TITLE
Can not update Path when tried  to update customized interval action  (version 1.2.1)

### ISSUE THREAD

**Issue by tianxingguo** [edgexfoundry/edgex-go#2843]
Hi there
  Got an issue, firststep created a customized interval action, then tried  to update it, only url's path can not be updated:

{"id":"9d4e5761-01b8-4092-aa7c-40310414af6b","name":"ccc","parameters":"{ \"888\" : \" aaa\",\"999\" : \" bbb\" }","target":"customized","interval":"midnight","protocol":"HTTP","httpMethod":"PUT","address":"99","port":9999,"path":"http://192.168.2.249:9090"}

after run it from postman, then requery the inerval action, the path still keep previous one.

**Comment by tianxingguo** [comment]
Not only for customized , also for core-command can not update path

**Comment by cloudxxx8** [comment]
@tianxingguo what do you mean? core-command doesn't allow any update as design.

**Comment by jpwhitemn** [comment]
Confirmed this is a bug.  Use of the PUT call on interval action changes properties like httpMethod or port, but not the path on the intervalaction (PUT to http://localhost:48085/api/v1/intervalaction).  The logs show no issue (in fact, suggest the PUT succeeded), but the path never gets updated (even when other properties do get updated).

**Comment by jpwhitemn** [comment]
Was this fixed for V2?  If so, will close this issue as we won't be supporting V1 bugs after V2.

**Comment by cloudxxx8** [comment]
this issue doesn't exist in V2
