### ISSUE TITLE
[V2 metadata] deviceservice property baseAddress can be updated to empty string

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2844]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
core-metadata

### Description and Minimal Reproduction
The `baseAddress` is required when post a device service, but it can be updated to an empty string value when update the device service using `PATCH /api/v2/deviceservice`.

## 🔥 Exception or Error
Update a device sesrvice:
```
$curl -X PATCH http://localhost:48081/api/v2/deviceservice -d '[{"service": {"name":"Device-Service-1603425701882-3", "baseAddress": ""}}]'

[{"apiVersion":"v2","requestId":"","message":"","statusCode":200}]
```
The value of `baseAddress` is an empty string:
```
$curl -X GET http://localhost:48081/api/v2/deviceservice/name/Device-Service-1603425701882-3

{"apiVersion":"v2","requestId":"","message":"","statusCode":200,"service":{"id":"b9afc41a-3239-41e2-89aa-a6389ee0bc61","name":"Device-Service-1603425701882-3","description":"deviceservice","operatingState":"ENABLED","labels":["device-example"],"baseAddress":"","adminState":"UNLOCKED"}}
```
</code></pre>

## 🌍  Your Environment
**EdgeX Version:**
master

**Comment by jpwhitemn** [comment]
@cloudxxx8 @weichou1229 
I thought baseAddress was a property that was assembled internally from protocol, method, address, port, etc.?  If so, why is any update to baseURL allowed?  Shouldn't this be (re-)created on any post or put?

**Comment by lenny-intel** [comment]
> Shouldn't this be (re-)created on any post or put?

@jpwhitemn,  Nope, we choose to have baseAddress be provided in the request. Single field replacing addressable which contained all the parts you are referring to.

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/go-mod-core-contracts/issues/362
