### ISSUE TITLE
[V2 metadata] Update device service with empty name should return status code 400

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2845]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-metadata

### Description and Minimal Reproduction
Updating a device service **without id and name** properties returns status code `404` correctly, but updating a device service with empty name or empty id returns `400`.
```
$curl -X PATCH http://localhost:48081/api/v2/deviceservice -d '[{"service": {"adminState": "LOCKED"}}]'

{"apiVersion":"v2","requestId":"","message":"device service json decoding failed","statusCode":400}
```
## 🔥 Exception or Error
Update a device service **with empty name and without id** returns status code `404`, but it should be `400`.
```
$curl -X PATCH http://localhost:48081/api/v2/deviceservice -d '[{"service": {"name":"", "adminState": "LOCKED"}}]'

[{"apiVersion":"v2","requestId":"","message":"fail to query object *models.DeviceService, because : v2:deviceService:name doesn't exist in the database","statusCode":404}]
```
Update a device service **with empty id and without name** returns status code `404`, but it should be `400`.
```
$curl -X PATCH http://localhost:48081/api/v2/deviceservice -d '[{"service": {"id":"", "adminState": "LOCKED"}}]'

[{"apiVersion":"v2","requestId":"","message":"fail to query object *models.DeviceService, because id: v2:deviceService: doesn't exist in the database","statusCode":404}]
```

## 🌍  Your Environment
**EdgeX Version:**
master

**Comment by jpwhitemn** [comment]
This is not a bug.  When other APIs are called to update something (Intervalue, ValueDescriptor, etc.) we return 400 when the request is "bad" because no id or name is provided.  It does look like the error code is consistent across APIs.
