### ISSUE TITLE
Can not RunOnce interval to frequeny interval  on version 1.2.1

### ISSUE THREAD

**Issue by tianxingguo** [edgexfoundry/edgex-go#2859]
# 🐞 Bug Report

### Affected Services

Tried to update a RunOnce type  interval to  frequency interval , as followed :
 firstly crreate a RunOnce interval with http Post method : 
{"name":"demo","runOnce":true,"frequency":"0h","cron":"","start":"20201029T000000","end":"20201031T000000"}

Seondly to change to frequency type via http put method:
{"name":"demo","id":"0350b8e7-e775-4508-817a-1bc6f2e5efc9","runOnce":false,"frequency":"9h","cron":"","start":"20201029T200000","end":"20201031T200000"}

Lastly to check the interval , but get following packet:
 {
	"Timestamps": {
		"created": 1603941383184,
		"modified": 1603941417378
	},
	"id": "0350b8e7-e775-4508-817a-1bc6f2e5efc9",
	"name": "demo",
	"start": "20201029T200000",
	"end": "20201031T200000",
	"frequency": "9h",
	"runOnce": true
}

still get "runOnce": true 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
1.2.1

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@weichou1229 could you please see whether this issue still exists in V2?

**Comment by weichou1229** [comment]
No, V2 fixed this issue.

**Comment by cloudxxx8** [comment]
@tianxingguo we won't fix the older version unless the bug is serious.  are you able to workaround this issue by restarting the service?

**Comment by cloudxxx8** [comment]
close this issue because we fixed it in V2
