### ISSUE TITLE
Introduce Codeclimate to improve code quality

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#286]
hi @drasko and @tsconn23 ,

based on the discussion in issue #280 , I find a tool name [Codeclimate](https://docs.codeclimate.com/)  which may be suitable for us.

It contains many engines(plugins), [one](https://docs.codeclimate.com/docs/golint) of the plugins is [golint](https://github.com/golang/lint) .

I have two basic requirement : 

* a CLI : can run and do local check before making a PR and can customize with CI tool with shell, Codeclimate has a [CLI](https://docs.codeclimate.com/docs/command-line-interface)
* integrate with GitHub : yes, see [details](https://docs.codeclimate.com/docs/github-issues)

so any idea about this tool? or is there more suitable tools can be shared?

cc @jpwhitemn

**Comment by tsconn23** [comment]
Can we please move these kind of proposal discussions to the email list and use issues for discrete work items?
EdgeX-GoLang@lists.edgexfoundry.org
