### ISSUE TITLE
[V2] Add service prefixes for the Redis key of each service

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2861]
# 🚀 Feature Request

### Relevant Package

 This feature request is for all service using Redis in V2

### Description
per the Core WG meeting on 29-OCT-2020, there was a conversation around what keys we use with Redis for our data. All data in Redis is accessed by key (a name).  Names/keys should belong to a namespace.  Andre suggested that we use separate key prefix by service: example cd|Event, cd|Reading, md|Device, md|DeviceProfile, etc.  (prefixes add to the space so you want short prefixes).  This sets us up better for Redis 6 access control lists according to Andre.

**Comment by jpwhitemn** [comment]
Ireland Planning Meeting in scope task
