### ISSUE TITLE
Implement missing "proxy tls" functionality in edgex-secrets-config

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2866]
# 🚀 Feature Request

### Relevant Package
edgex-secrets-config

### Description
The related [ticket to implement edgex-secrets-config](https://github.com/edgexfoundry/edgex-go/pull/2808) left out a major feature to support uploading of a user-supplied TLS certificate in order to make the EdgeX Hanoi code freeze deadline.

This request is to add the missing functionality as described in the edgex-secrets-config man page under "proxy tls".

This request realizes the objective of https://github.com/edgexfoundry/edgex-go/issues/1926 and https://github.com/edgexfoundry/edgex-go/issues/1922

**Comment by jim-wang-intel** [comment]
currently this one depends on PR #2808
