### ISSUE TITLE
Revisit requirement to have a service registry (i.e. remove or disable service registry)

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#2869]
# 🚀 Feature Request

### Relevant Package
Affects docker-edgex-consul and go-mod-registry

### Description
This feature asserts that the service registry component of EdgeX is no longer needed and shall be removed for the following reasons:

- Implementation of [new bootstrapping method](https://github.com/edgexfoundry/edgex-go/issues/2864) will decouple Vault's data store from Consul, and Vault will no longer register its service health in the Consul registry.  It will also use a new method for managing startup dependencies that does not depend on service health checks.
- Various EdgeX services [no longer perform client monitoring](https://github.com/edgexfoundry/edgex-go/issues/2594) by polling Consul.
- Service location information [comes from a trusted source](https://github.com/edgexfoundry/edgex-go/issues/2868) and not from the Consul service registry
- Docker implementation of EdgeX uses Docker DNS for host-IP mappings, and snap-based EdgeX implementation uses the host's networking stack and everything is localhost.

**Comment by jpwhitemn** [comment]
The [service registry ADR](https://docs.edgexfoundry.org/2.0/design/adr/0018-Service-Registry/) supersedes this issue. (per Core WG of 6/5)
