### ISSUE TITLE
Overflows int errors on 32bit ARM build after v1.2.2-dev.79

### ISSUE THREAD

**Issue by novuscy** [edgexfoundry/edgex-go#2870]
# 🐞 Bug Report
I tried to build the master branch on a 32bit ARM system, but I got errors about int overflows...

It was OK before v1.2.2-dev78 tag, it might be something wrong with the V2 implementations?
### Affected Services

 The issue is located in: 
Core services

### Is this a regression?

Yes,  build completes on v1.2.2-dev.78 and before 
 
### Description and Minimal Reproduction
make a 32bit ARM build after v1.2.2-dev.79

## 🔥 Exception or Error
<pre><code>

# github.com/edgexfoundry/edgex-go/internal/core/metadata/v2/controller/http
internal/core/metadata/v2/controller/http/device.go:170:73: constant 4294967295 overflows int
internal/core/metadata/v2/controller/http/device.go:313:78: constant 4294967295 overflows int
internal/core/metadata/v2/controller/http/deviceprofile.go:333:78: constant 4294967295 overflows int
internal/core/metadata/v2/controller/http/deviceservice.go:246:78: constant 4294967295 overflows int
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Raspberry Pi 4 Ubuntu 32bit
**EdgeX Version:** master 

**Anything else relevant?**

**Comment by weichou1229** [comment]
Since 32 bits ARCH only support 2,147,483,647 as the maximum positive signed integer, will use math.MaxInt32 instead of the math.MaxUint32.
