### ISSUE TITLE
[security-proxy-setup] can only use an HTTPS vault client

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#2873]
# 🐞 Bug Report

### Affected Services

 The issue is located in: security-proxy-setup

### Is this a regression?
No

### Description and Minimal Reproduction
The security-file-token-provider, security-secretstore-setup and security-proxy-setup all share a common configuration sub-section `[SecretService]` which includes a set of configuration items which define how to communicate with vault, including `Scheme` (http or https), `Server`, and `Port`.

After our discussion last week about no longer requiring TLS for internal REST communications, I tried to setup overrides in the snap to disable TLS for Vault. The following changes to the vault-config.hcl file do this:

```
 listener "tcp" { 
   address = "localhost:8200" 
-  tls_disable = "0" 
+  tls_disable = "1"
   cluster_address = "localhost:8201"
   tls_min_version = "tls12"
   tls_client_ca_file ="$SNAP_DATA/secrets/ca/ca.pem"
@@ -21,8 +21,8 @@ backend "consul" {
   path = "vault/"
   address = "localhost:8500"
   scheme = "http"
-  redirect_addr = "https://localhost:8200"
-  cluster_addr = "https://localhost:8201"
+  redirect_addr = "http://localhost:8200"
+  cluster_addr = "http://localhost:8201"
 }
```
Next I added a number of `SecretService.Scheme = http` overrides to the snap to inform the services themselves to not use HTTPS/TLS when talking to vault. This works for security-secretstore-setup and security-file-token-provider, however security-proxy-setup fails on startup because it's expecting vault to support HTTPS. When vault responds with HTTP to a request to validate a vault token, the proxy-setup logs error messages.

I traced this down to the fact that the first two support overriding SecretService.Scheme with an environment variable as they both log the override when defined. It turns out security-proxy-setup does not support such an override, and sure enough we (actually @bnevis-i) found that this is because the proxy code that sets up the vault client hard-codes `Protocol: "https"` instead of using `Protocol: c.SecretService.Scheme`.

## 🔥 Exception or Error
```
edgex-security-proxy-setup source=secret.go:67 msg="Reading secret store configuration and authentication token"
edgex-security-proxy-setup source=secret.go:73 msg="Attempting to create secretclient"
edgex-security-proxy-setup source=secret.go:82 msg="Retryable failure while creating SecretClient: Get \"https://localhost:8200/v1/auth/token/lookup-self\": http: server gave HTTP response to HTTPS client"
```

## 🌍  Your Environment
**Deployment Environment:**
snap, but the same will occur when deployed via docker-compose

**EdgeX Version:** v1.2.2-dev.106

**Anything else relevant?**

**Comment by jim-wang-intel** [comment]
@tonyespy / @lenny-intel  / @bnevis-i    This requires more in-depth discussion, as the current TOML of proxy-setup does not have the "scheme" available to use: https://github.com/edgexfoundry/edgex-go/blob/master/cmd/security-proxy-setup/res/configuration.toml#L45-L52  AND will it be a breaking change if we modify the TOML schema to add the protocol scheme?

**Comment by bnevis-i** [comment]
Need to check if the [SecretService] defined in proxy-setup (https://github.com/edgexfoundry/edgex-go/blob/master/internal/security/proxy/config/config.go) is compatible with the secrestore-setup config defined in  https://github.com/edgexfoundry/go-mod-secrets/blob/master/pkg/providers/vault/config.go which uses https://github.com/edgexfoundry/edgex-go/blob/master/internal/security/secretstoreclient/types.go

**Comment by jim-wang-intel** [comment]
> 
> 
> Need to check if the [SecretService] defined in proxy-setup (https://github.com/edgexfoundry/edgex-go/blob/master/internal/security/proxy/config/config.go) is compatible with the secrestore-setup config defined in https://github.com/edgexfoundry/go-mod-secrets/blob/master/pkg/providers/vault/config.go which uses https://github.com/edgexfoundry/edgex-go/blob/master/internal/security/secretstoreclient/types.go
> 
> I think it was a mistake to duplicate the type instead of just referring to secretstoreclient/types.go directly.

No, they are not compatible.  The [SecretService] in `proxy-setup` has different naming and also additional new attributes/properties like `HealthCheckPath` and `SNIS` (see https://github.com/edgexfoundry/edgex-go/blob/master/internal/security/proxy/config/config.go#L78-L86) when comparing with the one from `secretstore-setup` config's.  
So, i think the simplest way is to add `scheme` property but that seems to me is a breaking change in terms of TOML schema. 
Any thought on this issue, @lenny-intel ?

**Comment by tonyespy** [comment]
Adding a new configuration key isn't a breaking change, as long as it's implemented properly.

I just pushed a PR that resolves this and have confirmed that a configuration override works even if there's no actual "Scheme" in the configuration.toml file.

**Comment by lenny-intel** [comment]
Adding config properties is fine as long as they has a proper default handling if missing from the configuration.

**Comment by lenny-intel** [comment]
Also, why is this a bug. It was designed to be only TLS. Now we are changing the design.

**Comment by tonyespy** [comment]
See issue #2495 for a related issue related to security services' configuration.

**Comment by tonyespy** [comment]
> Also, why is this a bug. It was designed to be only TLS. Now we are changing the design.

It's a bug because the service hard codes a configuration value, thus an environment variable override doesn't work. Every other service works except for proxy-setup. That's why I consider it a bug.

**Comment by jim-wang-intel** [comment]
> 
> 
> > Also, why is this a bug. It was designed to be only TLS. Now we are changing the design.
> 
> It's a bug because the service hard codes a configuration value, thus an environment variable override doesn't work. Every other service works except for proxy-setup. That's why I consider it a bug.

I guess what Lenny meant that the original design for proxy-setup doesn't consider scheme to be in configuration for TLS being always https for secretstore.

**Comment by tonyespy** [comment]
> > > Also, why is this a bug. It was designed to be only TLS. Now we are changing the design.
> > 
> > 
> > It's a bug because the service hard codes a configuration value, thus an environment variable override doesn't work. Every other service works except for proxy-setup. That's why I consider it a bug.
> 
> I guess what Lenny meant that the original design for proxy-setup doesn't consider scheme to be in configuration for TLS being always https for secretstore.

**Comment by tonyespy** [comment]
Sorry, I clicked the wrong button and accidentally closed this issue...

**Comment by tonyespy** [comment]
> > > Also, why is this a bug. It was designed to be only TLS. Now we are changing the design.
> > 
> > 
> > It's a bug because the service hard codes a configuration value, thus an environment variable override doesn't work. Every other service works except for proxy-setup. That's why I consider it a bug.
> 
> I guess what Lenny meant that the original design for proxy-setup doesn't consider scheme to be in configuration for TLS being always https for secretstore.

Sure, that's certainly a valid viewpoint, however as this override works for both file-token-provide and secretstore-setup which both use the same configuration subsection (`[SecretService]`). So it's inconsistent behavior/design in my opinion. At minimum, this service should've logged an error when an override was specified for this, but in this case it's simply ignored.

Also we actually just discussed the issue of default configuration in code this week, and the consensus hasn't changed that it's not something we recommend.

**Comment by jim-wang-intel** [comment]
Closed as this has been fixed by [another PR](https://github.com/edgexfoundry/edgex-go/pull/2890/files)
