### ISSUE TITLE
Redis of edgexfoundry snap can't persist on disk

### ISSUE THREAD

**Issue by gao270615179** [edgexfoundry/edgex-go#2876]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
snap/snapcraft.yaml

### Is this a regression?

 Yes, the previous version in which this bug was not present was `v1.2.2-dev.102`

### Description and Minimal Reproduction
From v1.2.2-dev.103, in snap app redis server, command uses environment  `REDIS_SAVE_OPTS` as the option. But when redis server is running, I use `redis-cli config get save` to get the `save` config,  and the value is empty. So, redis server cannot persist on disk.

## 🔥 Exception or Error
<pre><code>

redis server cannot persist on disk.
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**  Ubuntu Core

**EdgeX Version:** v1.2.2-dev.106

**Anything else relevant?**

**Comment by jpwhitemn** [comment]
@tonyespy @anonymouse64 - can you confirm this is an issue?  If so, target for Ireland?
