### ISSUE TITLE
Refactor database client in core-metadata

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#290]
Should be fine to refactor database client in core-metadata using an interface like it's done in core-data and in export-client.

If it's fine, I can do it.

**Comment by jduranf** [comment]
@feclare Great!
Please, let me know if I can help in anything.

**Comment by tsconn23** [comment]
Closing this issue as per the email threads this morning, @feclare is well underway here.

**Comment by tsconn23** [comment]
Actually, will assign to @feclare so that he can associate with the relevant PR when ready.
