### ISSUE TITLE
[V2 data]  Update corresponding V2 API per the recent changes from Reading DTO/Model 

### ISSUE THREAD

**Issue by judehung** [edgexfoundry/edgex-go#2903]
### Affected Services
 The issue is located in: Core-Data

Per decision made in Ireland planning meeting, Reading DTO/Model of V2 API shall be updated with following changes:
1. change field `Name` to `ResourceName`
2. add new field `ProfileName`

A corresponding is submitted at https://github.com/edgexfoundry/go-mod-core-contracts/pull/374

The current V2 API of coredata shall be revised correspondingly to reflect these changes.

**Comment by lenny-intel** [comment]
This is not a bug. It is part of the enhancements to V2.
