### ISSUE TITLE
Add lightweight alternative to MongoDB in core-data

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#291]
The actual databases in core-data are MongoDB, which doesn't work in arm 32 bits devices and also uses 1GB hard disk only to create all needed collections, and InfluxDB, which have a very low performance compared to MongoDB, specially in a device with few resources. So should be fine to add a lightweight alternative for devices with few resources.

After analyze and test different options (MongoDB, InfluxDB, MariaDB, PostgreSQL, SQLite, Badger, tiedot...), seems BoltDB is a good lightweight alternative to MongoDB. The main points do decide BoltDB over other alternatives are:

1. Works in arm 32 bits devices
2. Use low RAM, CPU and storage
3. It's an embedded go database, so no need to use CGO or install anything

If it's fine and there are no suggestions to use another lightweight database, I will add the option to use BoltDB in core-data.

Finally I want to share some benchmarks results comparing BoltDB with MongoDB, InfluxDB and MariaDB. The values are in microseconds, and the lower, the best:

![benchmark](https://preview.ibb.co/ebvhV8/bench.png)

In general, MongoDB have the best performance adding entries, and BoltDB have the best performance getting entries.

**Comment by jpwhitemn** [comment]
@jduranf - it was decided at this past week's face-to-face TSC meeting that EdgeX will indeed find a replacement for the current reference implementation using Mongo.  Work is ongoing to help provide more loose coupling in the Go code around resources like the database.  This will be done for Delhi.  We also made plans to  complete a research on options and alternatives with a decision to be made by next TSC F2F in the fall and target the actual replacement by Edinburgh.

**Comment by jduranf** [comment]
@jpwhitemn thank you for your feedback!

My idea isn't to replace Mongo, I think Mongo is a valid option for a device with normal resources (although in the benchmarks I performed doesn't seems to have good results in some tests). I think should be fine to have two databases options, Mongo and another lightweight alternative.

Also my company can't wait for Edinburgh to have a Mongo replacement, so I will start working with Bolt, if there isn't any other lightweight suggestion. Anyway, if in the next TSC F2F it's decided to use a key-value database, almost all key-value go databases have similar interface, so most of the code will be reused, and I will be glad to help replacing Mongo (and Bolt) with this new database.

**Comment by drasko** [comment]
@jduranf a few questions:
- What made you discard PostgreSQL?
- Bolt vs Badger?
- Redis?

**Comment by jduranf** [comment]
@drasko
- I also tried PostgreSQL, but have worst results compared with MariaDB, except when adding an event or reading:
![benchmark2](https://preview.ibb.co/i8hhHo/bench2.png)
- Badger is very similar to Bolt, and some benchmarks say it's faster when adding values, but Badger doesn't have buckets (is a kind of collections), and Badger doesn't work in arm 32 bits (I tried it).
- I didn't thought about Redis, and maybe it's a good option. But my idea was to reduce the resources requirements, and after trying MongoDB, MariaDB, PostgreSQL and InfluxDB, I reach the conclusion the best option it's to use an embedded go database. Using an embedded go database you can reduce a lot the requirements, so that's why I choose Bolt, because is one of the most popular embedded go databases.

**Comment by tsconn23** [comment]
w/r/t Redis, members of their tech staff were at the F2F last week. They are interested in contributing a provider to the project. They plan to  start on that after the California release is out.

**Comment by drasko** [comment]
@tsconn23 @jduranf this is exactly why I mentioned Redis :)

@jduranf maybe I understand something on your diagram, but Postgres show pretty good performance here, better than MariaDB and better than BoltDB.

I'd say that SQLite also shows pretty good performance.

Benefits of having Postgres comparing to Bolt is that Postgres is full SQL DB that can work in variety of deployments, and can do complex SQL constructs, JOINs and other stuff that we'll need when we start grouping users and devices into organizations. i am not sure how Bolt can handle these.

Also, using Go's [sql](https://golang.org/pkg/database/sql/) package we can abstract [many](https://github.com/golang/go/wiki/SQLDrivers) SQL DBs and achieve support for all of them with the same code. This way in fog/cloud scenario Postgres can be used. On more constrained devices, SQLite can be used.

**Comment by drasko** [comment]
@tsconn23 @jduranf this is exactly why I mentioned Redis :)

@jduranf maybe I understand something on your diagram, but Postgres show pretty good performance here, better than MariaDB and better than BoltDB.

I'd say that SQLite also shows pretty good performance.

Benefits of having Postgres comparing to Bolt is that Postgres is full SQL DB that can work in variety of deployments, and can do complex SQL constructs, JOINs and other stuff that we'll need when we start grouping users and devices into organizations. i am not sure how Bolt can handle these.

Also, using Go's [sql](https://golang.org/pkg/database/sql/) package we can abstract [many](https://github.com/golang/go/wiki/SQLDrivers) SQL DBs and achieve support for all of them with the same code. This way in fog/cloud scenario Postgres can be used. On more constrained devices, SQLite can be used.

**Comment by jduranf** [comment]
@drasko I think you understand wrong my diagram (or I didn't explain correctly), in the diagram you see the time to perform the operations (1000 times each one) in microseconds, so less time is better Also take in account is a logarithmic diagram. This are the values used to create the diagram:

  | MongoDB | InfluxDB | BoltDB | MariaDB | SQLite | PostgreeSQL
-- | -- | -- | -- | -- | -- | --
AddReading | 71 | 3592 | 1167 | 2054 | 4441 | 1509
Readings | 65026 | 18861 | 3573 | 1510 | 4570 | 1642
ReadingCount | 39 | 15499 | 25 | 22 | 20 | 129
ReadingById | 44 | 521 | 4 | 29 | 81 | 155
ReadingsByDevice | 5591 | 643 | 283 | 39 | 114 | 183
AddEvent | 191 | 4786 | 1274 | 7022 | 4440 | 2432
Events | 5584210 | 2734619 | 29949 | 2483144 | 1358123 | 2481175
EventCount | 38 | 23663 | 28 | 24 | 20 | 135
EventById | 274 | 3227 | 31 |   |   |  
EventsForDevice | 58722 | 27349 | 523 | 1716 | 13250 | 24751

MariaDB have much better results than PostgreeSQL. For example, to retrieve 1000 events with 5 readings each one, MongoDB takes 5.5 seconds, MariaDB 2.4 seconds and BoltDB 29 milliseconds, so in this case BoltDB is much faster.

Regarding sql package, you can't use the same code using MariaDB and PostgreSQL, they use different semantics when using variables, so although the code is very similar, it isn' the same. I don't know what will happen with other sql databases.

Finally, the main problem with SQLite is it requires CGO, and this is an important problem if you have to cross compile.

**Comment by drasko** [comment]
@jduranf thanks a lot for these clarifications and benchmarks - extremely useful.

Regarding Postgres - not everything is in pure performance, there is a lot in database functionality, as I said. It should be also noted that [Cockroach DB](https://www.cockroachlabs.com/) uses Postgres `pq` driver, so it can be in-place replacement when some more scalable deployments are needed (in the cloud). It is also worth examining SQLite support via the same code if Go's `sql` package can support it - maybe here not so much change is needed as for MariaDB.

Bolt is definitely great choice for gateway deployments (note: [bbolt](https://github.com/coreos/bbolt) should be used, as original Bolt repo is not maintained any more), but we need to understand can it satisfy all the requirements regarding the functionality - as I described (JOINs, organizations, etc). Also - it should be noted that Redis Labs will become (or already is) EdgeX Foundry member, and I think that Redis can provide similar functionality as Bolt.

In general - I think that Bolt can cover gateway use-case, but I think  that it would be safer to go with DB that can scale-up to fog/cloud scenarios (Popstgres/Cockroach) and scale down to gateway with exactly the same code (Postgres/SQLite).

There will be a big discussion open on this topic soon I think, as it has been mentioned on recent F2F meeting in California.

**Comment by SteveOss** [comment]
@jduranf Great stuff.

Would also be good to know image size and memory usage for each of the alternatives.

**Comment by jduranf** [comment]
@drasko As you said, not everything is performance, and I'm sure lots of the benchmarks results can be improved (i.e. which is the point to read 1000 events, if there is a limit of 100 and everything is discarded?)
Also I confirm to you that MariaDB and SQLite have the same interface, and maybe SQLite is a good option for gateways, but SQLite requires CGO, and I think this should be avoided.

@SteveOss In general adding any database (MongoDB, InfluxDB, BoltDB, MariaDB or PostgreeSQL) increases the final size by about 0.5 MB. The exception is with SQLite, which increases the image size by more than 6 MBytes. Also take in account using any database except BoltDB and SQLite you must install the database, which usually is more than 30 MB.

**Comment by SteveOss** [comment]
@jduranf If the database image uses another base image (not Alpine) then this can add a fair bit of image size overhead.

**Comment by itamarhaber** [comment]
@jduranf amazing stuff :)

How can we go about adding Redis to your diagram and measurements? I'd be happy to implement the thing if you'll point me in the right direction.

**Comment by SteveOss** [comment]
@itamarhaber Might be worth holding on this as I think the Redis guys themselves are planning to contribute a Redis port.

**Comment by drasko** [comment]
@SteveOss actually @itamarhaber looks like Redis guy ;).

And I guess he demanded access to benchkmarking code from @jduranf so he can add Redis metrics.

**Comment by itamarhaber** [comment]
Exactly what @drasko said, but demanded is too strong of a word IMO - I asked for help :)

My plan is to:
1. Get edgex-go up and running locally - done.
2. Implement redis-client - in progress.
3. Add it to @jduranf benchmark somehow.

Would appreciate any pointers WRT 2 and 3.

**Comment by jduranf** [comment]
@itamarhaber should be great to add Redis in the benchmark!
In order to add Redis you should create an interface for Redis in /core/data/clients, like it's done with [Mongo](https://github.com/edgexfoundry/edgex-go/blob/master/core/data/clients/mongo-client.go), [Influx](https://github.com/edgexfoundry/edgex-go/blob/master/core/data/clients/influx-client.go) or [Memory](https://github.com/edgexfoundry/edgex-go/blob/master/core/data/clients/memory-database.go). You don't have to implement all functions, only the used for the benchmark.
Finally, add the Redis benchmark file, like it's done with [Mongo](https://github.com/edgexfoundry/edgex-go/blob/master/core/data/clients/mongo-client_test.go), and run the benchmark! (something like `go test -bench=Redis -tags redisRunning`).
If you want, I can run the benchmark in my computer, so all the results will be comparable. Also, if you need more help, maybe should be better if you write an email directly to me.

**Comment by itamarhaber** [comment]
@jduranf thanks!

I'm working along this path (i.e. I think I have createNewClient and maaaybe closeSession ;)) - I'll try to complete the musts based on the benchmark and share with you asap.

I'm itamar at redislabs dot com - can't seem to find yours.

**Comment by tsconn23** [comment]
@itamarhaber Before you start in earnest on this, I request that you review the work done in PR #298. This PR will go in after the California release. @feclare reorganized the package structure w/r/t database providers, clarified interface definitions and reworked how package-specific factories initialized DB providers. You will want your Redis client to fit into this structure. Core-data and core-metadata each have their own interface and we currently have one Mongo type that satisfies them both. Redis could probably do the same.

**Comment by itamarhaber** [comment]
@tsconn23 thanks for the tip - I'm working with the current unstable just so we can do a quick benchmark. Once things are sort-of-working, I'll refactor according to the new structure.

**Comment by itamarhaber** [comment]
Here are the methodology and benchmark results for my experimentations with Redis: https://gist.github.com/itamarhaber/086dcb35692745ad0f1ff492676b47c7

Summary of results
| Benchmark | MongoDB (micro/op) | RedisDB_Embedded (micro/op) | RedisDB_TCP (micro/op) | RedisDB_UDS (micro/op) |
|-|-|-|-|-|
| AddEvent | 352 | 193 | 201 | 189 |
| AddReading | 146 | 35 | 76 | 69 |
| EventById | 553 | 15 | 146 | 99 |
| EventCount | 94 | 3 | 45 | 31 |
| Events | 475,972 | 12,713 | 100,022 | 67,734 |
| EventsForDevice | 47,433 | 1,216 | 10,039 | 6,801 |
| ReadingById | 111 | 4 | 48 | 32 |
| ReadingCount | 103 | 3 | 45 | 31 |
| Readings | 3,658 | 1,681 | 1,466 | 1,429 |
| ReadingsByDevice | 725 | 162 | 230 | 216 |

@jduranf it would be awesome if you can test your implementations with this as well

**Comment by jduranf** [comment]
@itamarhaber I will not be able to test Redis implementation until end of August (I will be on vacations).
Anyway, I'm curious to know it there is persistence using Redis or not (I'm not a Redis expert), specially with embedded implementation.

**Comment by itamarhaber** [comment]
@jduranf enjoy your vacations (plural, I envy you :))!

I installed both Mongo and Redis using the defaults. I don't know about Mongo, but Redis' defaults are such that the data is persisted to disk so it is durable and survives failures. Redis can be configured as a pure in-memory database (and thus provide even better performance in some cases), but I don't think that's appropriate in this use case.

**Comment by jduranf** [comment]
Closing this issue as there is the [Data Persistence Group](https://wiki.edgexfoundry.org/display/FA/Data+Persistence+Project+Group) working on it.
