### ISSUE TITLE
[security-proxy-setup] edgx-proxy doesn't print INFO log when use --userdel

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2922]
# 🐞 Bug Report

### Affected Services

 The issue is located in: edgex-proxy

### Description and Minimal Reproduction
TAF security-enabled tests check the log containing "successful to delete" when remove token. 
Currently, TAF tests fail because the logLevel of edgex-proxy is changed from DEBUG to ERROR and the following INFO log cannot be found.

```
level=INFO ts=2020-12-04T09:02:24.0922238Z app=edgex-security-proxy-setup source=resource.go:67 msg="successful to delete testinguser at consumers"
```

## 🌍  Your Environment
**Deployment Environment:**
-
**EdgeX Version:**
master

**Anything else relevant?**
This commit https://github.com/edgexfoundry/edgex-go/commit/ff93af41a81d158de1dc365787019667f354ae25#diff-6cf8b18d0a77bef043684931681914b865d4bad0dacb268712239e7c07cb689d changed the logLevel from DEBUG to ERROR.

**Comment by cloudxxx8** [comment]
@bnevis-i your fix changed the log level from DEBUG to ERROR.  However, the default log level of other services are 'INFO'
may we set it to INFO?

**Comment by bnevis-i** [comment]
If it is an emergency, yes.  If not, then we are moving the token creation/delete out of edgex-proxy and into the new [secrets-config utility](https://github.com/edgexfoundry/edgex-go/pull/2808) that is in the same container as edgex-proxy (was necessary to resolve three other bugs). 

To use this new utility to create a token:

### Generate ECDSA key
```
openssl ecparam -name prime256v1 -genkey -noout -out ec256.key
cat ec256.key | openssl ec -out ec256.pub
```

### Create a user
```
./secrets-config proxy adduser --token-type jwt --algorithm ES256 --public_key ec256.pub --user myuser
(capture the standard output of the above command and use it as the id argument below; this is why the log level was changed to from DEBUG to ERROR)
```

### Create a JWT
```
./secrets-config proxy jwt --algorithm ES256 --id 0fjxWo34kmgtFEEdw1FC97hU74TmwM3a --private_key ec256.key 
(capture the JWT sent to standard output)
```

### Use the JWT
```
curl -k -H'Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDM0MTAxNDksImlhdCI6MTYwMzQwNjU0OSwiaXNzIjoiMGZqeFdvMzRrbWd0RkVFZHcxRkM5N2hVNzRUbXdNM2EiLCJuYmYiOjE2MDM0MDY1NDl9.PWT-e_6PrFZ-NOWZagUn_ERCsddkHZ-00C8eAMvwqe1FgzIKCqwGCi2Ephb4Xo3-EGxgl2X09xn8MSdP1kq0Ww' https://localhost:8443/metadata/api/v1/ping
ping
```

### Delete the user when done
```
./secrets-config proxy deluser --user myuser
```

**Comment by bnevis-i** [comment]
Workaround implemented (reverted log level, hard-coded an override into secrets-config).

Still need to implement long-term solution above as it is necessary to remove user creation from proxy-setup.

**Comment by cloudxxx8** [comment]
@bnevis-i sorry, we miss the progress of the security change.
do we have the document for the new user creation mechanism? or should just call the vault admin API to create users during the blackbox test?

**Comment by bnevis-i** [comment]
Documentation still needs updating.  Honestly I didn't expect anyone to be dependent on a log message.

**Comment by cloudxxx8** [comment]
I agree with that, and we will switch the implementation once the long-term solution is confirmed.

**Comment by lenny-intel** [comment]
@bnevis-i , remember the current way to get token depends on the log message. :-) That will not be the case once we switch over to using the utility in all the scripts and `compose builder` makefile.

**Comment by lenny-intel** [comment]
Closing now that we have this issue for TAF.
https://github.com/edgexfoundry/edgex-taf/issues/247
