### ISSUE TITLE
[v1 overwrite device] autoEvents not refreshed after delete and insert new device with same profile

### ISSUE THREAD

**Issue by raycola** [edgexfoundry/edgex-go#2925]
# 🐞 Bug Report

### Affected Services
The issue is located in: core-metadata and core-data

### Is this a regression?

Yes, the previous version (Geneva) in which this bug was not present.

### Description and Minimal Reproduction

1. Deploy edgex with [docker-compose-hanoi.yml](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/hanoi/compose-files/docker-compose-hanoi.yml)
2. Add device modbus service updating docker-compose file... 
3. Start Modbus Device (ModbusPal Simulator) with a mock configuration (some properties like P1, P2, P3 ecc)
4. Follow the instructions in Set Up After Starting Services [Tutorial](https://docs.edgexfoundry.org/1.2/examples/Ch-ExamplesAddingModbusDevice/#set-up-after-starting-services).
   Therefore:
   - Insert a new profile by POST to http://localhost:48081/api/v1/deviceprofile/uploadfile
   - Insert a new device by POST to http://localhost:48081/api/v1/device with some autoEvents (what it not important for test)
      p.e. "autoEvents":[ { "frequency": "10s", "onChange":false, "resource": "Values"}]. An id is returned p.e. 643d8e98-36d5-4be9-bdfa-ba71b8d913db
5.  New events occurs with multi property readings every 10 seconds with P1, P2, P3 ecc
6. Delete device by DELETE to http://localhost:48081/api/v1/device/id/643d8e98-36d5-4be9-bdfa-ba71b8d913db
7. Insert a new device with same name and profile by POST to http://localhost:48081/api/v1/device but with "different" autoEvents: 
p.e. "autoEvents":[ { "frequency": "30s", "onChange":true, "resource": "P1"}]
8. Old Values events occurs with multi property readings every 10 seconds with P1, P2, P3 ecc

## 🔥 Exception or Error
No exception or error.  Last configuration for autoEvents didn't overwrite.

## 🌍  Your Environment
**Deployment Environment:**
Docker

**EdgeX Version:** 
Hanoi release 1.3.0

**Comment by cloudxxx8** [comment]
@raycola are you running Modbus Device Service in the docker-network?  could you please paste the log of core-metadata?
I guess the device delete callback can't reach the Modbus Device Service due to the network.
If so, your Modbus Device Service address should be set to the docker0 ip address

**Comment by raycola** [comment]
Hi thanks for your message. I wrote that in the previous version (Geneva)  this bug was not present. No relevant info found in metadata logs... However I found a solution also in Hanoi through device-modbus service regression. I only changed the version of docker-device-modbus-go's image in docker-compose yaml:
From 
device-modbus:
    image: edgexfoundry/docker-device-modbus-go:1.3.0
To
device-modbus:
    image: edgexfoundry/docker-device-modbus-go:1.2.2

and no events occurs after device deleting... and it works again.

Modbus Device Service address is the same of docker0 as you can see:

sudo ip addr show docker0
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether ##:##:##:##:##:## brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever


{ 
   "name" :"MyVirtualDevice",
   "description":"MyVirtualDevice 1",
   "adminState":"UNLOCKED",
   "operatingState":"ENABLED",
   "protocols":{
      "modbus-tcp":{
         "Address" : "172.17.0.1",
         "Port" : "1502",
         "UnitID" : "1"
      }
   },
...
}

As you can see below in Hanoi with "docker-device-modbus-go:1.3.0" readings never stop  
edgex-device-modbus | level=INFO ts=2020-12-07T14:03:53.354963636Z app=edgex-device-modbus source=device.go:153 msg="Removed device: MyVirtualDevice"
edgex-device-modbus | level=ERROR ts=2020-12-07T14:03:59.954895429Z app=edgex-device-modbus source=command.go:51 msg="Device: MyVirtualDevice not found; get"
edgex-device-modbus | level=ERROR ts=2020-12-07T14:03:59.954928684Z app=edgex-device-modbus source=executor.go:53 msg="AutoEvent - error occurs when reading resource Values"

Logs:

Hanoi with  device-modbus: image: edgexfoundry/docker-device-modbus-go:1.3.0

edgex-device-modbus | level=INFO ts=2020-12-07T14:03:44.9447175Z app=edgex-device-modbus source=driver.go:162 msg="Read command finished. Cmd:AI6, Origin: 1607349824944711334, Uint16: 0 \n"
edgex-device-modbus | 2020/12/07 14:03:44 modbus: sending 00 07 00 00 00 06 01 03 00 06 00 01
edgex-device-modbus | 2020/12/07 14:03:44 modbus: received 00 07 00 00 00 05 01 03 02 00 00
edgex-device-modbus | level=INFO ts=2020-12-07T14:03:44.95145359Z app=edgex-device-modbus source=modbusclient.go:83 msg="Modbus client GetValue's results [0 0]"
edgex-device-modbus | level=INFO ts=2020-12-07T14:03:44.951479452Z app=edgex-device-modbus source=driver.go:162 msg="Read command finished. Cmd:AI7, Origin: 1607349824951471248, Uint16: 0 \n"
edgex-device-modbus | 2020/12/07 14:03:44 modbus: sending 00 08 00 00 00 06 01 03 00 07 00 01
edgex-device-modbus | 2020/12/07 14:03:44 modbus: received 00 08 00 00 00 05 01 03 02 00 00
edgex-device-modbus | level=INFO ts=2020-12-07T14:03:44.954461627Z app=edgex-device-modbus source=modbusclient.go:83 msg="Modbus client GetValue's results [0 0]"
edgex-device-modbus | level=INFO ts=2020-12-07T14:03:44.954487582Z app=edgex-device-modbus source=driver.go:162 msg="Read command finished. Cmd:AI8, Origin: 1607349824954479578, Uint16: 0 \n"
edgex-device-modbus | level=INFO ts=2020-12-07T14:03:53.354963636Z app=edgex-device-modbus source=device.go:153 msg="Removed device: MyVirtualDevice"
edgex-device-modbus | level=ERROR ts=2020-12-07T14:03:59.954895429Z app=edgex-device-modbus source=command.go:51 msg="Device: MyVirtualDevice not found; get"
edgex-device-modbus | level=ERROR ts=2020-12-07T14:03:59.954928684Z app=edgex-device-modbus source=executor.go:53 msg="AutoEvent - error occurs when reading resource Values"
edgex-device-modbus | level=ERROR ts=2020-12-07T14:04:14.955009874Z app=edgex-device-modbus source=command.go:51 msg="Device: MyVirtualDevice not found; get"
edgex-device-modbus | level=ERROR ts=2020-12-07T14:04:14.955958772Z app=edgex-device-modbus source=executor.go:53 msg="AutoEvent - error occurs when reading resource Values"
edgex-device-modbus | level=ERROR ts=2020-12-07T14:04:29.956656574Z app=edgex-device-modbus source=command.go:51 msg="Device: MyVirtualDevice not found; get"
edgex-device-modbus | level=ERROR ts=2020-12-07T14:04:29.956685398Z app=edgex-device-modbus source=executor.go:53 msg="AutoEvent - error occurs when reading resource Values"



edgex-core-metadata | level=INFO ts=2020-12-07T14:01:16.0910017Z app=edgex-core-metadata source=database.go:147 msg="Database connected"
edgex-core-metadata | level=INFO ts=2020-12-07T14:01:16.091475033Z app=edgex-core-metadata source=database.go:112 msg="Database for V2 API connected"
edgex-core-metadata | level=INFO ts=2020-12-07T14:01:16.096950561Z app=edgex-core-metadata source=telemetry.go:86 msg="Telemetry starting"
edgex-core-metadata | level=INFO ts=2020-12-07T14:01:16.100953068Z app=edgex-core-metadata source=httpserver.go:99 msg="Web server starting (edgex-core-metadata:48081)"
edgex-core-metadata | level=INFO ts=2020-12-07T14:01:16.101154834Z app=edgex-core-metadata source=message.go:50 msg="Service dependencies resolved..."
edgex-core-metadata | level=INFO ts=2020-12-07T14:01:16.101230466Z app=edgex-core-metadata source=message.go:51 msg="Starting edgex-core-metadata 1.3.0 "
edgex-core-metadata | level=INFO ts=2020-12-07T14:01:16.101275971Z app=edgex-core-metadata source=message.go:55 msg="This is the EdgeX Core Metadata Microservice (DEBUG)"
edgex-core-metadata | level=INFO ts=2020-12-07T14:01:16.101326947Z app=edgex-core-metadata source=message.go:58 msg="Service started in: 7.000342541s"
edgex-core-metadata | level=ERROR ts=2020-12-07T14:01:25.045005489Z app=edgex-core-metadata source=handler.go:47 msg="no item found for supplied key: edgex-device-modbus"
edgex-core-metadata | level=ERROR ts=2020-12-07T14:01:25.046116612Z app=edgex-core-metadata source=handler.go:47 msg="Item not found"


Hanoi with  device-modbus:  image: edgexfoundry/docker-device-modbus-go:1.2.2

edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.507472084Z app=edgex-device-modbus source=driver.go:151 msg="Read command finished. Cmd:AI4, Origin: 1607350147507464738, Uint16: 32700 \n"
edgex-device-modbus | 2020/12/07 14:09:07 modbus: sending 00 05 00 00 00 06 01 03 00 04 00 01
edgex-device-modbus | 2020/12/07 14:09:07 modbus: received 00 05 00 00 00 05 01 03 02 00 00
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.514310241Z app=edgex-device-modbus source=modbusclient.go:83 msg="Modbus client GetValue's results [0 0]"
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.51433675Z app=edgex-device-modbus source=driver.go:151 msg="Read command finished. Cmd:AI5, Origin: 1607350147514329312, Uint16: 0 \n"
edgex-device-modbus | 2020/12/07 14:09:07 modbus: sending 00 06 00 00 00 06 01 03 00 05 00 01
edgex-device-modbus | 2020/12/07 14:09:07 modbus: received 00 06 00 00 00 05 01 03 02 00 00
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.515773045Z app=edgex-device-modbus source=modbusclient.go:83 msg="Modbus client GetValue's results [0 0]"
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.515797573Z app=edgex-device-modbus source=driver.go:151 msg="Read command finished. Cmd:AI6, Origin: 1607350147515790350, Uint16: 0 \n"
edgex-device-modbus | 2020/12/07 14:09:07 modbus: sending 00 07 00 00 00 06 01 03 00 06 00 01
edgex-device-modbus | 2020/12/07 14:09:07 modbus: received 00 07 00 00 00 05 01 03 02 00 00
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.52034241Z app=edgex-device-modbus source=modbusclient.go:83 msg="Modbus client GetValue's results [0 0]"
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.52036722Z app=edgex-device-modbus source=driver.go:151 msg="Read command finished. Cmd:AI7, Origin: 1607350147520359926, Uint16: 0 \n"
edgex-device-modbus | 2020/12/07 14:09:07 modbus: sending 00 08 00 00 00 06 01 03 00 07 00 01
edgex-device-modbus | 2020/12/07 14:09:07 modbus: received 00 08 00 00 00 05 01 03 02 00 00
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.521645515Z app=edgex-device-modbus source=modbusclient.go:83 msg="Modbus client GetValue's results [0 0]"
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.521666905Z app=edgex-device-modbus source=driver.go:151 msg="Read command finished. Cmd:AI8, Origin: 1607350147521660367, Uint16: 0 \n"
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:07.526910745Z app=edgex-device-modbus source=utils.go:94 Content-Type=application/json correlation-id=a06f32d6-4510-4faf-bc3a-d00232f45ce2 msg="SendEvent: Pushed event to core data"
edgex-device-modbus | level=INFO ts=2020-12-07T14:09:13.01817412Z app=edgex-device-modbus source=device.go:128 msg="Removed device: MyVirtualDevice"



edgex-core-metadata | level=INFO ts=2020-12-07T14:07:36.413809271Z app=edgex-core-metadata source=database.go:147 msg="Database connected"
edgex-core-metadata | level=INFO ts=2020-12-07T14:07:36.414301495Z app=edgex-core-metadata source=database.go:112 msg="Database for V2 API connected"
edgex-core-metadata | level=INFO ts=2020-12-07T14:07:36.417867164Z app=edgex-core-metadata source=telemetry.go:86 msg="Telemetry starting"
edgex-core-metadata | level=INFO ts=2020-12-07T14:07:36.418351744Z app=edgex-core-metadata source=httpserver.go:99 msg="Web server starting (edgex-core-metadata:48081)"
edgex-core-metadata | level=INFO ts=2020-12-07T14:07:36.418706357Z app=edgex-core-metadata source=message.go:50 msg="Service dependencies resolved..."
edgex-core-metadata | level=INFO ts=2020-12-07T14:07:36.418779603Z app=edgex-core-metadata source=message.go:51 msg="Starting edgex-core-metadata 1.3.0 "
edgex-core-metadata | level=INFO ts=2020-12-07T14:07:36.418822886Z app=edgex-core-metadata source=message.go:55 msg="This is the EdgeX Core Metadata Microservice (DEBUG)"
edgex-core-metadata | level=INFO ts=2020-12-07T14:07:36.418873599Z app=edgex-core-metadata source=message.go:58 msg="Service started in: 6.220313249s"
edgex-core-metadata | level=ERROR ts=2020-12-07T14:07:46.392774247Z app=edgex-core-metadata source=handler.go:47 msg="no item found for supplied key: edgex-device-modbus"
edgex-core-metadata | level=ERROR ts=2020-12-07T14:07:46.393459402Z app=edgex-core-metadata source=handler.go:47 msg="Item not found"

I don't undestand why but my workaround works.

Any suggest?

**Comment by cloudxxx8** [comment]
Thanks for reporting this.  It might be a bug we created when we refactored the device-sdk-go.
I am moving this issue to https://github.com/edgexfoundry/device-sdk-go/issues/681
