### ISSUE TITLE
Introduce topic from edgex-go repository

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#293]
Now, Github can mark topic for repository, see here : https://blog.github.com/2017-01-31-introducing-topics/

I suggest to mark some topics for this repository, to let more users search edgex-go. 

Potential topics like 'IoT', 'Edge Computing', 'Golang', 'microservice' and so on. Choosing what you want to mark like this project : https://github.com/openfaas/faas

cc @jpwhitemn @drasko and @tsconn23

**Comment by jpwhitemn** [comment]
Hi Vino - as always thanks for your ideas and suggestions.  If you could please, submit this suggestion to the EdgeX email reflector lists and the appropriate EdgeX Rocket Chat channels.  Suggestions like this require more eyes to consider the idea and provide feedback.  GitHub issues should be used when there is a bug fix, required enhancement or approved feature that needs to be assigned and worked by the developers.

**Comment by yanghua** [comment]
Hi @jpwhitemn some suggestion I did though forum. But seems the Edgex's forum can not ping someone and the discussion is few. And about Rocket Chat channels, many people did not login in. 
I think this issue is an obvious suggestion and not about the edgex feature and code. It's just about the Github. And I thought it's a short and quick process. Drasko and  Tsconn are always online, so they can do this and close the issue quickly. 

This is my thought, but I will accept your suggestion.
