### ISSUE TITLE
Core Data remove V2 Pushed and Scrub APIs

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#2937]
Per [MessageBus ADR](https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/013-Device-Service-Events-Message-Bus.md)

The `Marked As Pushed` feature is being removed for Ireland. The following v2 APIs need to be removed:
- Pushed (/event/pushed)
- Scrub (/event/scrub)

**Comment by cloudxxx8** [comment]
may we keep /event/scrub and just clean up all the events?

**Comment by judehung** [comment]
@cloudxxx8 and @lenny-intel 
Since we're going to remove pushed-related APIs, do we also have to remove `pushed` filed from V2 event DTO/Model?

**Comment by cloudxxx8** [comment]
> @cloudxxx8 and @lenny-intel
> Since we're going to remove pushed-related APIs, do we also have to remove `pushed` filed from V2 event DTO/Model?

Yes
