### ISSUE TITLE
[export-client] Can't connect to database, service won't start

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#294]
I've been working on publishing an updated version of my edgexfoundry-core snap to the 'cali' track in the snap store.  Today I updated the edgex-go part in the snap to pull latest (I haven't pinned it to a commit yet):

https://github.com/tonyespy/edgex-core-snap/commit/aedccf3fcc0fbe71650ce5d74801702464513924

After rebuilding the snap, and installing locally on an Ubuntu 16.04 LTS amd64 machine, when I start EdgeX using the snap's start script, I see the following errors when export-client starts:

```
+ /snap/edgexfoundry-core/x22/bin/export-client -consul
{"level":"info","ts":1528821214.3248372,"caller":"export-client/main.go:32","msg":"Starting edgex-export-client 0.5.2"}
    2018/06/12 12:33:34 [INFO] agent: Synced service 'edgex-export-client'
    2018/06/12 12:33:34 [INFO] agent: Synced check 'Health Check: edgex-export-client'
{"level":"info","ts":1528821214.3634052,"caller":"export-client/main.go:66","msg":"Loading configuration from Consul...","version":"0.5.2"}
{"level":"error","ts":1528821214.36358,"caller":"export-client/main.go:70","msg":"Could not initialize export client","error":"couldn't connect to database: Unsuppored database type","stacktrace":"main.main\n\t/opt/dev/edgex-core-snap/parts/edgex-go/build/.gopath/src/github.com/edgexfoundry/edgex-go/cmd/export-client/main.go:70\nruntime.main\n\t/opt/dev/edgex-core-snap/parts/go/install/src/runtime/proc.go:195"}
    2018/06/12 12:33:39 [WARN] agent: http request failed 'http://:0/api/v1/ping': Get http://:0/api/v1/ping: dial tcp :0: getsockopt: connection refused

```
I think the hostname problem with the ping endpoint has been around for awhile (there may be an open issue on this already), however the "Unsuppored database type" looks like something recently introduced (and it's fatal).

**Comment by feclare** [comment]
Check the configuration file. There is a ```DBType = 'mongodb'```  in https://github.com/edgexfoundry/edgex-go/blob/master/cmd/export-client/res/configuration.toml that is needed.

**Comment by tonyespy** [comment]
@feclare Thanks for the response! Shouldn't this setting have been imported into consul by core-config-seed, or maybe the issue is that Consul settings support in export-client/-distro isn't fully working yet?

**Comment by feclare** [comment]
Probably it is missing. I don't know if someone is keeping track of the changes to the configuration files to update them in core-config-seed-go.
What I don't know is why core-config-seed-go lives in its own repo instead of edgex-go. It is harder to maintain this way. 
@jpwhitemn @tsconn23 Any reason to have it in a different repo?

**Comment by tonyespy** [comment]
@feclare It's been like this for awhile...  That said an effort is underway to move us to a new Go-based config-seed service which I understand will be part of the mono repo.  So let's leave this issue open for now and close it if/when we've verified that it works with the new Go config-seed.

In the meanwhile, I'll change my snap to use local configuration.

**Comment by tsconn23** [comment]
@xmlviking for visibility

**Comment by tsconn23** [comment]
@tonyespy Is this still an issue? If not, please close.

**Comment by jduranf** [comment]
Closing the issue, @tonyespy if it's still an issue, please open again
