### ISSUE TITLE
rule engine, send to message bus,set port 5563,but endpoint use 5573

### ISSUE THREAD

**Issue by yu-qingyun** [edgexfoundry/edgex-go#2987]
![image](https://user-images.githubusercontent.com/39030988/103614505-bad7e600-4f63-11eb-8716-3bbcb76ab634.png)
![image](https://user-images.githubusercontent.com/39030988/103614541-c9260200-4f63-11eb-9b26-591166f84767.png)

**Comment by cloudxxx8** [comment]
@yu-qingyun sorry for the late reply
could you please provide your steps to reproduce this issue?
what version you are using?

**Comment by JamesKButcher** [comment]
No response, not enough detail for us to reproduce. Will reopen if more details emerge
