### ISSUE TITLE
Add Consul API to API gateway

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#2991]
# 🚀 Feature Request

### Relevant Package

 This feature request is for Proxy Setup

### Description
 A clear and concise description of the problem or missing capability...
Consul not accessible from off box so it is not useful for making Writable configuration changes.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Add consul to the API gateway. 
If add as a sub-path like `consul` the Consul UI will not work as it is unaware of the sub-path when it redirects to other pages.
Consider adding it as the default path so the Consul UI will work.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by bnevis-i** [comment]
This issue was completed as a result of the securing consul ADR (many other tickets filed to track progress on this).
