### ISSUE TITLE
[V2] Remove all the DeleteByID API, except for Event

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2994]
# 🚀 Feature Request

### Relevant Package

 This feature request is for core-data and core-metadata

### Description
For the consistency, Core WG decided to remove all DeleteByID API, except for Event

### Describe the solution you'd like
Modify Swagger, remove the code in the layers of controller and application if no invocation from other controllers, only keep the code in the infrastructure level

**Comment by cloudxxx8** [comment]
@hahattan and @jinlinGuan  for awareness

**Comment by judehung** [comment]
For Command V2 API, https://github.com/edgexfoundry/edgex-go/issues/3037 had been resolved to remove ID-related APIs.

**Comment by judehung** [comment]
For notification V2 API, https://github.com/edgexfoundry/edgex-go/pull/3030 will update the Swagger file by removing ID-related APIs.

**Comment by FelixTing** [comment]
@judehung For Notification V2 API, because the Notification and Transmission objects only use ID as an identifier, ID-related APIs are required.
