### ISSUE TITLE
[V2] Send single AddEventRequest DTO rather than EventDTO to Message Queue

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2995]
# 🚀 Feature Request

### Relevant Package

 This feature request is for core-data

### Description
We are sending single EventDTO to ZeroMQ as we did in V1.
In V2 we should send the single AddEventRequest DTO for both JSON and CBOR.

**Comment by judehung** [comment]
Per discussion over https://github.com/edgexfoundry/edgex-go/pull/3002, update the issue to send single AddEventRequest DTO to message queue.
