### ISSUE TITLE
Unable to easily add Intervals and IntervalActions statically

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#2996]
# 🚀 Feature Request

### Relevant Package

 This feature request is for Support Scheduler

### Description
 A clear and concise description of the problem or missing capability...
 Intervals and IntervalActions a map in the configuration.toml. Existing Intervals and IntervalActions can be modified via environment variable overrides, but new ones can not be added.

For snaps, the configuration.toml has to be modified to add new Intervals and/or IntervalActions. If service already ran, the service's configuration has to be purged from Consul and service restarted.

For docker, a modified version of the configuration.toml with new Intervals and/or IntervalActions has to be volume mounted for the service to use. This can be done by simply placing it over the default configuration.toml. As with snaps, the service's configuration has to be purged from Consul before the service restarted with the new configuration.toml.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
At a minimum, the above options need to be documented. 

It has been suggested that the Intervals and IntervalActions be separated out into there one file. Doing this would remove the ability to override existing with env overrides. Also doesn't change that the file has to be modified similar to above.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Should investigate enhancing environment overrides with the ability to add new elements for maps.

**Comment by jpwhitemn** [comment]
? in Core WG was is this also an issue on Provision Watchers.  Per message exchange with @iain-anderson :  "This is designed to be dynamic, so PWs can be created/deleted/updated in much the same way as Devices can: core-metadata will issue a callback to the device service to instruct it to update its PW cache accordingly. Code is in place in Hanoi and as far as I'm aware is working."

**Comment by lenny-intel** [comment]
@jpwhitemn , this is for Support Scheduler, not device services.

**Comment by jpwhitemn** [comment]
@lenny-intel - I know this is for scheduler, but PW (used by device services) are also stored/managed from Metadata, and per the Core WG meeting, there was a concern that we may have a similar issue in that they could not be easily added statically.  Per Iain, this should not be an issue.

**Comment by lenny-intel** [comment]
Closing as will not fix
