### ISSUE TITLE
Incorrect ReadLimit Key in Core-Command Configuration TOML

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#300]
The configuration files for cmd/core-command have an incorrect key "ReadLimit". This should be "ReadMaxLimit". The effect is that the ReadMaxLimit property value on the ConfigurationStruct is always zero.

**Comment by yanghua** [comment]
hi @tsconn23 if you are busy, I can take this one~

**Comment by tsconn23** [comment]
@yanghua OK

**Comment by tsconn23** [comment]
@yanghua We'll be cutting the California branch soon. Will you be able to take care of this by Monday?

**Comment by yanghua** [comment]
Yes. I will fix it soon.
