### ISSUE TITLE
rule engine, send to http, request post, set data template failed

### ISSUE THREAD

**Issue by yu-qingyun** [edgexfoundry/edgex-go#3009]
![image](https://user-images.githubusercontent.com/39030988/104262941-9203a380-54c3-11eb-867f-5c9a5b7d2e57.png)
![image](https://user-images.githubusercontent.com/39030988/104262977-a3e54680-54c3-11eb-8a53-d60f3b33d50b.png)

**Comment by jinfahua** [comment]
Could you please provide following information?
- The error message.
- Click `view source` tab in the 2nd screen-shot, and post the rule.

**Comment by wshengqi** [comment]
@yu-qingyun Hi, could you send us the UI full screen shot as image? that may be help us to find the problem.
About your failed,I guess two situations can lead to mistakes: 
1. In the Rest HTTP Server  Information input errors may occur, like the Action is GET but the Method is POST, or the other input error.
2. The connection between UI and server may failed, please double check the EdgeX and the UI in the seem network, and the health check is pass.
If not the two reasons, please call me back and we will continue to focus on this issue. Thank you!

**Comment by jpwhitemn** [comment]
@yu-qingyun - I am going to close this issue as neither the Kuiper team or the UI team are able to reproduce this issue.  If you are able to reproduce it and if you are able to provide more details we will reopen it.
