### ISSUE TITLE
Pushing data from Core Data and Core Metadata to Redis database results in ERROR.

### ISSUE THREAD

**Issue by jcerato** [edgexfoundry/edgex-go#3015]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Data, Metadata

### Description and Minimal Reproduction
If the connection between the Core Data/Metadata and Redis database reaches the timeout, for example the connection is not used for pushing data for a certain amount of time, when a new event is pushed to the database it results in an ERROR.
The events after the one that returned error will work correctly, until a new connection timeout is reached.

## 🔥 Exception or Error
<pre><code>
</code>level=ERROR ts=2021-01-12T10:56:06.502127776Z app=edgex-core-data source=handler.go:47 msg="write tcp 10.42.1.46:48698->10.43.14.52:6379: write: broken pipe"</pre>

## 🌍  Your Environment
**Deployment Environment:** EdgeX services managed by Kubernetes.

**EdgeX Version:** EdgeX Geneva.

**Anything else relevant?** Usage of Redis cluster for High Availability.

**Comment by cloudxxx8** [comment]
@jcerato do you know whether this issue only happens in the Redis cluster environment?

**Comment by jcerato** [comment]
In my personal experience, this happens only in Redis Cluster environment.

**Comment by jpwhitemn** [comment]
@jcerato - EdgeX is not currently supporting Redis Cluster environments.  However, we think this issue is resolved for V2 (although not tested with Redis Clusters).  Advise you checkout the V2 APIs with the upcoming release and if this issue still remains, reopen it.
