### ISSUE TITLE
Dangerous chown in cmd/security-secretstore-setup/entrypoint.sh

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#3017]
Use `chown -Rh` . Without the -h chown will follow symlinks and can corrupt other parts of the OS (like making a symlink to /etc/shadow suddenly owned by edgex-user.

**Comment by beaufrusetta** [comment]
@bnevis-i I'm on it...

**Comment by beaufrusetta** [comment]
PR created to fix this: https://github.com/edgexfoundry/edgex-go/pull/3024
