### ISSUE TITLE
[Core Command] processing query params of url in put method

### ISSUE THREAD

**Issue by gao270615179** [edgexfoundry/edgex-go#3033]
# 🚀 Feature Request

### Relevant Package

 
This feature request is for processing query params of url in `put` method.

### Description
 
In `get` method, when calling device commands, the query params are placed in url, but this isn't processed in `put` method.

### Describe the solution you'd like

In `NewPutCommand` function, when creating restful url, adding the query params in url.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by lenny-intel** [comment]
Note that when query parameter was added to GET, it was decide then to not add it to PUT. 
@jpwhitemn, We should revisit this in next Core WG meeting?

**Comment by jpwhitemn** [comment]
@gao270615179 - can you provide more information on your use case?  In other words, can you provide some details about the type of PUT request on command that you are making that requires the query parameters?

Per the Core WG meeting of 1/21/21, we are considering scheduling this request in our backlog.  When added, we think this would be a "additive" API which would not break backward compatibility (so it could be addressed in this release or the next dot release depending on available resources without issue).

**Comment by gao270615179** [comment]
@jpwhitemn Thanks for your discussing. In my case, I want to read/write RFID card by UHF card reader, and each card has an unique ID (EPC). When I need operate the card, I must let the reader know which card to read/write by using EPC. When reading card, I can add EPC query parameter to GET. However, when writing card, I can't using the method. 

For the reader, the EPC is uncertain, so it can't be as a device resource attribute.  

Moreover, the EPC can be as a device resource. When writing card, it can be added to PUT as body params. But this way is not corresponding to GET, and I must process the relation between `reqs []dsModels.CommandRequest` and `params []*dsModels.CommandValue` in card reader driver.

**Comment by lenny-intel** [comment]
@jim, note that @gao270615179 has submit a PR #3034 for this, but this will also require updates to the Device SDKs to handle the PUT query parameters for command similar to how they are handled for GET.

**Comment by lenny-intel** [comment]
@gao270615179, Also note that your PR #3034 modifies the V1 API which will be removed by the time Ireland is released. The new V2 API for Support Command is currently work in progress. 

@jpwhitemn , @cloudxxx8 , If we agree to this enhancement, should be included in the current V2 API implementation?

**Comment by jpwhitemn** [comment]
All - let's discuss @gao270615179 use case and PR at the next core work group meeting and make a determination about how/when to address.

**Comment by jpwhitemn** [comment]
As decided in Core WG 1/28/21 - this is a good add.  We choose to implement this in Jakarata release (fall 2021) with stretch goal of implementing in Ireland release.  PR 3034 will be closed and not used because it is for V1.  We need a V2 implementation and it needs to also be done with work in the DS SDKs.

**Comment by gao270615179** [comment]
I have also committed the pull request 732 about query param in the DS SDKs and fix the bug in GET method.
