### ISSUE TITLE
export-distro fails to start and fills log with parsing failure message

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/edgex-go#308]
Running the services locally with a local MongoDB on Ubuntu 18.04 LTS, I receive this message (repeated forever) when starting `export-distro`:

`{"level":"warn","ts":1529418445.5104675,"caller":"distro/client.go:44","msg":"Could not parse json","error":"invalid character 'o' in literal null (expecting 'u')"}
{"level":"info","ts":1529418445.5105236,"caller":"distro/registrations.go:242","msg":"Waiting for client microservice"}
{"level":"warn","ts":1529418446.5118706,"caller":"distro/client.go:44","msg":"Could not parse json","error":"invalid character 'o' in literal null (expecting 'u')"}`

Walking back through the services, `export-client` produces this output, over and over:

`{"level":"error","ts":1529419891.6867495,"caller":"client/registration.go:83","msg":"Failed to query all registrations","error":"not authorized on coredata to execute command { find: \"exportConfiguration\", filter: {}, skip: 0, $db: \"coredata\" }","stacktrace":"github.com/edgexfoundry/edgex-go/export/client.getAllReg\n\t/home/brandon/go/src/github.com/edgexfoundry/edgex-go/export/client/registration.go:83\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go-1.10/src/net/http/server.go:1947\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Route).parse\n\t/home/brandon/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/route.go:153\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).parse\n\t/home/brandon/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/helper.go:23\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).DefaultServe\n\t/home/brandon/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/bone.go:54\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).DefaultServe-fm\n\t/home/brandon/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/bone.go:40\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).ServeHTTP\n\t/home/brandon/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/bone.go:73\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/go-1.10/src/net/http/server.go:2694\nnet/http.(*conn).serve\n\t/usr/lib/go-1.10/src/net/http/server.go:1830"}`

Finally, the MongoDB instance provides this output:

`2018-06-19T10:51:31.686-0400 I ACCESS   [conn8] Unauthorized: not authorized on coredata to execute command { find: "exportConfiguration", filter: {}, skip: 0, $db: "coredata" }`

Is this a problem with default configuration, or is there a step in the documentation I'm missing that's non-obvious?

**Comment by tsconn23** [comment]
@brandonforster Did you run the init_mongo.js script found here?

https://github.com/edgexfoundry/developer-scripts/blob/master/init_mongo.js

cd into developer-scripts. Assuming mongo is on your path, type "mongo init_mongo.js" then try to start the service again.

**Comment by brandonforster** [comment]
@tsconn23 Yes. I ran the init script without authentication, shutdown the DB, then restarted it with authentication as the instructions directed me to.

**Comment by feclare** [comment]
@brandonforster You can also try to use the mongo docker. In edgex-go/docker you can run the command:
```docker-compose up -d mongo```

**Comment by brandonforster** [comment]
Right, and I will to get up and going, but isn't running the MongoDB
natively a supported configuration?

**Comment by jpwhitemn** [comment]
Brandon, while you are correct that we should be able to run MongoDB natively or in Docker form, let's see what happens if MongoDB is running in Docker form and we point all services to Dockerized Mongo.  That would help eliminate something in the service as the issue if it works and narrow it to something in your local Mongo setup.  If it still doesn't work, then we know is something in the service or the service config.

**Comment by tsconn23** [comment]
@brandonforster Is this still a problem or can it be closed?

**Comment by caocaocaodou** [comment]
@tsconn23 
Excuese me,  I have run the linux_setup.sh , did I miss  anything?
Thank you!
