### ISSUE TITLE
(Hanoi) Backport ZMQ bug fix to Hanoi branch

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#3083]
# 🐞 Bug Report

### Affected Services

 The issue is located in:  Core data

go-mod-messaging v0.1.30 has fix for ZMQ bug
https://github.com/edgexfoundry/go-mod-messaging/issues/76

Hanoi branch needs this version of go-mod-messaging for upcoming 1.3.1 dot release.

**Comment by cloudxxx8** [comment]
fixed by #3084
