### ISSUE TITLE
Remove "From Scratch" from edgex-support-logging Docker file

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#310]
Right now, one can't open a shell into the edgex-support-logging container when it's running. This seems to be because of the `FROM scratch` definition in the Docker file.

https://github.com/moby/moby/issues/17896

We will remove it. If that fixes the issue, then we should eliminate this line from any other Dockerfiles.

**Comment by yanghua** [comment]
if you are busy, I can take this~ cc @tsconn23

**Comment by tsconn23** [comment]
As discussed during Core WG call on 21-Jun-2018 this isn't a bug, but a feature. Decision was made to relook at writing to a directory linked to a location on a common volume.
