### ISSUE TITLE
Fail to start scheduler with error "Failed to load schedules and events NOAUTH Authentication required"

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#3105]
# 🐞 Bug Report

### Affected Services

 The issue is located in: support-scheduler

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
Start services using the docker-compose file with docker-compose-nexus.yml on [developer-script PR #399](https://github.com/edgexfoundry/developer-scripts/pull/399)
## 🔥 Exception or Error
<pre><code>

level=ERROR ts=2021-02-01T07:42:09.421967984Z app=edgex-support-scheduler source=init.go:65 msg="Failed to load schedules and events NOAUTH Authentication required."
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@cloudxxx8, @weichou1229, There is a very strange side effect from recent addition of V2 code. The V2 DB handler was inserted before the V2 DB handler which is opposite of hoe it is  for Core Data and Core Metadata. When we swapped the order for Support Scheduler this issue goes away. Also the DB password is not be used in the V2 DB handler here: https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/v2/bootstrap/handlers/database.go#L58
When we added using the DB password it also resolved the issue.
