### ISSUE TITLE
`KongACL.WhiteList` for multiple groups does not work properly

### ISSUE THREAD

**Issue by kurokobo** [edgexfoundry/edgex-go#3107]
# 🐞 Bug Report

### Affected Services

The issue is located in: `initACL` in `security-proxy-setup`.

### Is this a regression?

* This issue exists in Fuji, Geneva and Hanoi.
* Not tested Edinburgh or older release.

### Description and Minimal Reproduction

1. Download latest docker-compose-hanoi.yml (with security services)
2. Add `KONGACL_WHITELIST: "admin, hoge"` to `services.edgex-proxy.environment`
3. Start EdgeX: `docker-compose up -d`
4. Create `admin-user` to group `admin` and `hoge-user` to group `hoge`, then keep their tokens
```
docker-compose run --rm --entrypoint /edgex/security-proxy-setup edgex-proxy --init=false --useradd=admin-user --group=admin
docker-compose run --rm --entrypoint /edgex/security-proxy-setup edgex-proxy --init=false --useradd=hoge-user --group=hoge
```
5. Access EdgeX through API Gateway using those two users;
```
curl -k -H 'Authorization: Bearer ADMN_USER_TOKEN' https://localhost:8443/coredata/api/v1/ping
curl -k -H 'Authorization: Bearer HOGE_USER_TOKEN' https://localhost:8443/coredata/api/v1/ping
```

## 🔥 Exception or Error

As [described in the documentation](https://docs.edgexfoundry.org/1.3/microservices/security/Ch-APIGateway/#configuring-api-gateway), adding multiple groups to an ACL is allowed, and at this time it is expected that both users will have access. 

In practice, however, both `admin-user` and `hoge-user` are denied.

```
$ curl -k -H 'Authorization: Bearer eyJhb...omitted...cSWYo' https://localhost:8443/coredata/api/v1/ping
{"message":"You cannot consume this service"}

$ curl -k -H 'Authorization: Bearer eyJhb...omitted...q5Pgo' https://localhost:8443/coredata/api/v1/ping
{"message":"You cannot consume this service"}
```

I can see that the comma separated string is set as the actual group name. This means that neither `admin` nor `hoge` will match, therefore both users will be rejected.

```
$ curl -s  http://localhost:8001/plugins | jq
{
  "next": null,
  "data": [
    {
      "created_at": 1612185075,
      "config": {
        "hide_groups_header": false,
        "blacklist": null,
        "whitelist": [
          "admin, hoge" 👈👈👈👈👈
        ]
      },
      "id": "b3374094-a285-4926-976d-d337b4a09ce5",
      ...
      "name": "acl",
      "consumer": null,
      "route": null,
      "tags": null
    },
```

## 🌍  Your Environment

**Deployment Environment:**

* Docker 19.03.6 @ Ubuntu

**EdgeX Version:**

latest Hanoi release with:
* `edgexfoundry/docker-security-proxy-setup-go:1.3.0`
* `kong:2.0.5`

**Anything else relevant?**

As far as I can tell, it seems to be a problem with the parameters given to the Kong API when initializing the ACL by [`initACL`](https://github.com/edgexfoundry/edgex-go/blob/hanoi/internal/security/proxy/service.go#L417).

In the current code, the comma-separated values that passed as environment variables are sent directly to the API using `config.whitelist` parameter. This seems to have worked in [older versions of the ACL plugin](https://docs.konghq.com/hub/kong-inc/acl/0.1-x.html):

```
$ curl -X POST http://<admin-hostname>:8001/plugins/ \
    --data "name=acl"  \
    --data "config.whitelist=group1, group2" \
    --data "config.hide_groups_header=true"
```

However, in the `kong:2.0.5` that included in Hanoi, the `config.whitelist` parameter seems to need to be written multiple times for as many groups as there are, instead of being a comma-separated string ([similar issue here](https://github.com/Kong/kong/issues/4523)).

```
$ curl -X POST http://<admin-hostname>:8001/plugins/ \
    --data "name=acl"  \
    --data "config.whitelist=group1" \
    --data "config.whitelist=group2" \
    --data "config.hide_groups_header=true"
```

Further for the [newer (current) version of the ACL plugin](https://docs.konghq.com/hub/kong-inc/acl/), the `config.whitelist` seems to be replaced with `config.allow`.

```
$ curl -X POST http://<admin-hostname>:8001/plugins/ \
    --data "name=acl"  \
    --data "config.allow=group1" \
    --data "config.allow=group2" \
    --data "config.hide_groups_header=true"
```

In Hanoi release, once I remove `acl` plugin and add it with appropriate parameter, it works as expected.

```
$ curl -X DELETE http://localhost:8001/plugins/b3374094-a285-4926-976d-d337b4a09ce5

$ curl -X POST http://localhost:8001/plugins --data "name=acl" --data "config.whitelist=admin" --data "config.whitelist=hoge" --data "config.hide_groups_header=false" | jq
{
  "created_at": 1612187040,
  "config": {
    "hide_groups_header": false,
    "blacklist": null,
    "whitelist": [
      "admin",👈👈👈
      "hoge"👈👈👈
    ]
  },
  ...

$ curl -k -H 'Authorization: Bearer eyJhb...omitted...cSWYo' https://localhost:8443/coredata/api/v1/ping
pong

$ curl -k -H 'Authorization: Bearer eyJhb...omitted...q5Pgo' https://localhost:8443/coredata/api/v1/ping
pong
```

**Comment by bnevis-i** [comment]
See also #3564

**Comment by bnevis-i** [comment]
This is deprecated in Ireland release.  While the config item exists, it is being silently ignored.

The two groups are
- admin-group (controls access to Kong admin api)
- gateway-group (controls access to EdgeX services)

**Comment by bnevis-i** [comment]
@kurokobo 

Updated instructions [here](https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/security/Ch-APIGateway.md)

Closing issue.  Please follow up if this resolution is insufficient.

Security workgroup meetings are Wednesday 9AM US Pacific Time resuming in two weeks after Jakarta planning.
