### ISSUE TITLE
Some services image footprint is over than Hanoi release 1.2 times

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#3114]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
Some services image is over than Hanoi release 1.2 times.
edgex-core-metadata image size 17.69 > Prior release size 13.49 * 1.2
edgex-core-command image size 15.96 > Prior release size 11.41 * 1.2 
edgex-support-notifications image size 15.95 > Prior release size 12.92 * 1.2
edgex-support-scheduler image size 16.12 > Prior release size 11.54 * 1.2

But the executable footprint is less than Hanoi release.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**
See [performance metrics report](https://jenkins.edgexfoundry.org/job/edgexfoundry/job/edgex-taf-pipelines/job/performance-test/43/Performance_20Metrics_20Summary_20Reports/) for reference.

**Comment by cloudxxx8** [comment]
I confirm the reason is that those docker images was from scratch in Hanoi, and become based on alpine now for the new security bootstrapper.
https://github.com/edgexfoundry/edgex-go/commit/5dc76a6c8e7f254c7fba720d41f2fe5f0204dd5b#diff-e2f519d4ca4193d865a405e3a11d71bc12a15f1b445c324ef744453319433f27

If this image size growth is reasonable, we can close this issue and modify the test script to pass it.

**Comment by jim-wang-intel** [comment]
> I confirm the reason is that those docker images was from scratch in Hanoi, and become based on alpine now for the new security bootstrapper.
> [5dc76a6#diff-e2f519d4ca4193d865a405e3a11d71bc12a15f1b445c324ef744453319433f27](https://github.com/edgexfoundry/edgex-go/commit/5dc76a6c8e7f254c7fba720d41f2fe5f0204dd5b#diff-e2f519d4ca4193d865a405e3a11d71bc12a15f1b445c324ef744453319433f27)
> 
> If this image size growth is reasonable, we can close this issue and modify the test script to pass it.

Right. HI @cherrycl  and @cloudxxx8 :  two main reasons to go to alpine: 1) the new paradigm for security-bootstrapper requires `shell` interpreter abilities 2) better security using `dumb-init` for reaping the zombie processes in various entrypoint scripts.   Hence, as discussed in security WG meeting, we have agreed upon using alpine as based image.  Thanks.

**Comment by cloudxxx8** [comment]
thanks for the explanation, @jim-wang-intel 

@cherrycl we made the decision to increase the threshold to 1.5 in this release in the QA WG meeting today.  Please help make the change in the performance test.  thanks.
