### ISSUE TITLE
[V2 metadata] Create device profile with uploadfile API failed

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#3117]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Metadata

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
Set Post `/api/v2/deviceprofile/uploadfile` with [yaml file](https://github.com/edgexfoundry/edgex-taf/blob/360264e7a4fa4aed3b7cbe3d8d1e27a77ced75bc/TAF/testData/core-metadata/deviceprofile/Test-Profile-1.yaml).

## 🔥 Exception or Error
<pre><code>

apiVersion: "v2" is added to the file, but still got the error.
```
{
    "apiVersion": "v2",
    "requestId": "",
    "message": "DeviceProfile.Versionable.ApiVersion field is required",
    "statusCode": 400
}
```
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**  Master

**Anything else relevant?**

**Comment by weichou1229** [comment]
Opened PR to fix this issue https://github.com/edgexfoundry/go-mod-core-contracts/pull/484

**Comment by weichou1229** [comment]
Opened PR https://github.com/edgexfoundry/edgex-go/pull/3130 to upgrade contract lib for taking the changes from core-contracts.
