### ISSUE TITLE
Use Consul Watches to support configuration change awareness

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#313]
Consul Watches API : https://www.consul.io/docs/agent/watches.html
We should support the microservice aware the configuration dynamic change.

This can be a part of Delhi version. I can claim it.

cc @tsconn23 and @drasko

**Comment by tsconn23** [comment]
This is on the roadmap but I'm closing this issue because it's dependent upon pending efforts to restructure the configuration entries. After the restructuring, this can be taken up.
