### ISSUE TITLE
export distro won't mark an event as pushed after it's sent to its destination

### ISSUE THREAD

**Issue by davidmsh** [edgexfoundry/edgex-go#315]
export distro in Go won't mark an event as pushed after it's sent to its destination as its Java counterpart does. We had some client need this pushed time for some benchmarking purposes. I think we should probably add it in go version of edgex. Also we probably want to make this feature configurable to avoid unnecessary service invocation and database updates when pushed are not really useful in someone's deployment. 
I can pick up this one if we are gonna implement it.

**Comment by cloudxxx8** [comment]
@davidmsh the PRs are merged.  Please close this issue.

**Comment by cloudxxx8** [comment]
https://github.com/edgexfoundry/edgex-go/pull/421
https://github.com/edgexfoundry/edgex-go/pull/454
