### ISSUE TITLE
[Secure Consul Ph. 3] Create a global Consul token (stored in a file) for use in remote configuration

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-go#3158]
# 🚀 Feature Request

### Relevant Package

 
This feature request is for `Consul bootstrapper`.

### Description
 
The Consul bootstrap management token has a built-in policy to access everything. So it is desirable to create a second token for be used in remote configuration through UI use case.
**TBD: still yet to be decided what are the ACL policy rules for such a token.**

### Describe the solution you'd like
 
1. In Consul bootstrapper, define a access policy and create a second management token which will be stored into file volume that  only shared between the `proxy-setup` and `consul`.

2. Later when `proxy-setup` runs, it will need to have access to this token in order to configure the header injection for the Kong. This step is useful for UI users to login through Consul UI.

3. Update the `consul` and `proxy-setup` services in docker-compose file so that both services have accessed to that token.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by bnevis-i** [comment]
Replanned for Levski in Levski planning 5/19/2022
