### ISSUE TITLE
event.tags not exporting

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#3170]
# 🐞 Bug Report

### Affected Services
Core Data - to app services or anything north side

### Is this a regression?
unknown

### Description and Minimal Reproduction
The core data service is not passing through any tags to the north.  Tags are being persisted in Redis, but otherwise not sent through the messagebus.

To reproduce, send the following event to http://corehost:48080/api/v1/event via POST

 {
    "device": "Random-Integer-Device",
    "origin": 123,
    "id": "82eb2e26-0f24-48aa-ae4c-de9dac3fb924",
    "tags" : {
        	"Key1": "V1",
			"Key2": "V2"
    },
    "readings": [
        {
            "name": "R1",
            "device": "Random-Integer-Device",
            "value": "Hi",
            "origin": 123,
            "ValueType": "String",
            "binaryValue": "MTIzNDU2",
            "mediaType": "application/text",
            "id": "82eb2e26-0f24-48aa-ae4c-de9dac3fb912"
        }
    ]
}

## 🔥 Exception or Error
no error / exception; but tags do not show up in event on the other side

## 🌍  Your Environment
**Deployment Environment:**
Linux, using Hanoi docker compose (no security)

**EdgeX Version:**
Hanoi; with core contracts 0.1.112

**Anything else relevant?**
I don't think we have to fix this for Hanoi, but we should make sure it is fixed for Ireland and V2 APIs

**Comment by cloudxxx8** [comment]
@weichou1229 please help check whether this problem exists in V2.  thanks.

**Comment by lenny-intel** [comment]
I have confirmed that V2 API is publishing the Event Tags and App Services are receiving them.
```
level=DEBUG ts=2021-02-16T16:19:56.2231306Z app=AppService-sample source=runtime.go:339 msg="Event Received with ProfileName=Random-Integer-Device, DeviceName=Random-Integer-Device and ReadingCount=1"
level=DEBUG ts=2021-02-16T16:19:56.2232071Z app=AppService-sample source=runtime.go:344 msg="Event tags are: [map[Key1:V1 Key2:V2]]"
```

**Comment by jpwhitemn** [comment]
Closed as this is working in V2 and no need to go back and fix for V1
