### ISSUE TITLE
Snap running issue due to SecureProviderBootstrapHandler from security-proxy-setup not having the needed secretstore config

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-go#3204]
# 🐞 Bug Report

### Affected Services

 

The issue is located in: `security-proxy-setup`

### Is this a regression?

 
Yes, the previous version in which this bug not present was before `go-mod-secret` refactor. The locally built proxy setup binary was able to start up successfully without an issue.  

### Description and Minimal Reproduction
Currently, with a newly refresh built, `security-proxy-setup` is not able to start up successfully due to the empty bootstrap configuration from GetBootstrap() because the Type of `SecretStoreInfo` is always an empty string.

To re-produce this locally with `dev` version, follow the steps:
1. rebuild a local binary executable of `security-proxy-setup` from make file
   `make cmd/security-proxy-setup/security-proxy-setup`
2. have edgex-docker stack be running: `make run dev` (so that we have Kong server to test `proxy-setup`)
3. change directory to `cmd/security-proxy-setup` and run the binary executable: `./security-proxy-setup --init=true`
4. observer the console output and see that the Type of secret config is an empty string '':
    `Retryable failure while creating SecretClient: invalid secrets client type of ''` 

## 🔥 Exception or Error
<pre><code>
./security-proxy-setup --init=true
level=INFO ts=2021-03-01T15:12:54.633528481Z app=edgex-security-proxy-setup source=config.go:181 msg="Loaded configuration from ./res/configuration.toml"
level=INFO ts=2021-03-01T15:12:54.636583059Z app=edgex-security-proxy-setup source=config.go:316 msg="Using local configuration from file (0 envVars overrides applied)"
level=INFO ts=2021-03-01T15:12:54.636706005Z app=edgex-security-proxy-setup source=secret.go:51 msg="Creating SecretClient"
level=INFO ts=2021-03-01T15:12:54.636750241Z app=edgex-security-proxy-setup source=secret.go:58 msg="Reading secret store configuration and authentication token"
level=INFO ts=2021-03-01T15:12:54.636790813Z app=edgex-security-proxy-setup source=secret.go:70 msg="Attempting to create secret client"
level=WARN ts=2021-03-01T15:12:54.636835743Z app=edgex-security-proxy-setup source=secret.go:80 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"
level=INFO ts=2021-03-01T15:12:55.637072372Z app=edgex-security-proxy-setup source=secret.go:58 msg="Reading secret store configuration and authentication token"
level=INFO ts=2021-03-01T15:12:55.637239718Z app=edgex-security-proxy-setup source=secret.go:70 msg="Attempting to create secret client"
level=WARN ts=2021-03-01T15:12:55.637370959Z app=edgex-security-proxy-setup source=secret.go:80 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"
level=INFO ts=2021-03-01T15:12:56.637666933Z app=edgex-security-proxy-setup source=secret.go:58 msg="Reading secret store configuration and authentication token"
level=INFO ts=2021-03-01T15:12:56.637831654Z app=edgex-security-proxy-setup source=secret.go:70 msg="Attempting to create secret client"
level=WARN ts=2021-03-01T15:12:56.637916758Z app=edgex-security-proxy-setup source=secret.go:80 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"
level=INFO ts=2021-03-01T15:12:57.63812175Z app=edgex-security-proxy-setup source=secret.go:58 msg="Reading secret store configuration and authentication token"
level=INFO ts=2021-03-01T15:12:57.638295406Z app=edgex-security-proxy-setup source=secret.go:70 msg="Attempting to create secret client"
level=WARN ts=2021-03-01T15:12:57.638359692Z app=edgex-security-proxy-setup source=secret.go:80 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"
...
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Local Ubuntu box

**EdgeX Version:**
Current from master branch

**Anything else relevant?**
This issue also causes the local snap service `edgexfoundry.security-proxy-setup` failed to start.

**Comment by lenny-intel** [comment]
This is not a bug caused by `go-mod-secret` refactor. The `security-bootstrapper` implementation disabled secure mode for Proxy Setup, thus the use of `go-mod-secret` was disabled, so until re-enabling secure mode for Proxy Setup does this become an issue.

**Comment by jim-wang-intel** [comment]
> This is not a bug caused by `go-mod-secret` refactor. The `security-bootstrapper` implementation disabled secure mode for Proxy Setup, thus the use of `go-mod-secret` was disabled, so until re-enabling secure mode for Proxy Setup does this become an issue.

ok, but it does triggered by this change of these lines: https://github.com/edgexfoundry/edgex-go/blob/master/internal/security/proxy/config/config.go#L109-L111   i am fine with that you would not call it a bug due to the refactor of that

**Comment by lenny-intel** [comment]
If we are removing setup of SecretStore, then the SecretStore configuration should also be removed from TOML and structs
