### ISSUE TITLE
bug(notifications): Distributing notifications to too many subscriptions

### ISSUE THREAD

**Issue by AlexCuse** [edgexfoundry/edgex-go#3225]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
support-notifications-go

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
doubtful

### Description and Minimal Reproduction

It does not appear that the set of subscriptions is filtered correctly when distributing notifications.  Instead of looking for subscriptions where categories AND labels match, it seems like it ends up doing an OR instead.  As a result anyone with a subscription on the category gets all notifications sent to it, regardless of label.  

https://github.com/edgexfoundry/edgex-go/blob/f60a6b9b3bbcf5933f7773f85fc76d84301e173f/internal/pkg/db/redis/notifications.go#L428-L451

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Redis database 

**EdgeX Version:**
1.3.0

**Anything else relevant?**

**Comment by AlexCuse** [comment]
I am going to be working on a fix against 1.3.0 for something we need to deliver in the near term but can come back and bring a PR against master if I have time.

**Comment by lenny-intel** [comment]
@cloudxxx8 , is this issue in the new V2 ?

**Comment by cloudxxx8** [comment]
@lenny-intel we haven't implemented the notification handling mechanism.
@FelixTing for awareness

**Comment by cloudxxx8** [comment]
we need to fix this in V2

**Comment by weichou1229** [comment]
This issue will fix by the PR https://github.com/edgexfoundry/edgex-go/pull/3422

**Comment by weichou1229** [comment]
@AlexCuse This issue fixed at V2, could you help verify that?

https://github.com/edgexfoundry/edgex-go/blob/3372c345ca573018b8293c0333122174fb4d3907/internal/pkg/v2/infrastructure/redis/subscription.go#L231-L245

**Comment by AlexCuse** [comment]
Sure I will try to set up a test early next week @weichou1229.  

This code looks right to me I remember the v1 change was to use redis `SINTER` command.

**Comment by AlexCuse** [comment]
Sorry for the delay @cloudxxx8 I got pulled into some 1.3 stuff and by the time I got back to it my 2.0 services needed considerable updating.  I just tested and I am not getting the duplicates anymore, think this can be closed if your associated tasks are complete.

**Comment by cloudxxx8** [comment]
thanks for the confirmation, @AlexCuse
