### ISSUE TITLE
Refactor security-bootstrapper Vault's Consul Secret Engine APIs using go-mod-secret (yet to be created)

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-go#3227]
# 🚀 Feature Request

### Relevant Package

 
This feature request is for `security-bootsrapper`'s subcommands to use go-mod-secret's API for Vault's SecretEngine API in future.

### Description
 A clear and concise description of the problem or missing capability...
Currently, the Vault's Consul Secret Engine APIs are locally coded in edgex-go.  It would be nice to move these APIs to go-mod-secret and refactor the code to use them (not exists yet today).

(Please provide reference to the code to be moved/refactored)

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Move Vault's Consul Secret Engine APIs to go-mod-secret.  This refactor can be done after `phase 2` of Securing Consul is done so that we can refactor all Vault's Consul Secret Engine APIs into `go-mod-secret` module in one scoop.

#### Change Details
Specifically, the Vault-Consul secret engine APIs used in consul-bootstrapper in this code: 
1. https://github.com/edgexfoundry/edgex-go/blob/main/internal/security/bootstrapper/command/setupacl/command.go#L654-L708 and 
2. https://github.com/edgexfoundry/edgex-go/blob/main/internal/security/bootstrapper/command/setupacl/aclroles.go#L85-L137   

could be refactored and modulized into go-mod-secrets as part of `SecretStoreClient` interfaces:  https://github.com/edgexfoundry/go-mod-secrets/blob/main/secrets/interfaces.go#L54-L69.  

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by bnevis-i** [comment]
Replanned for Levski in Levski planning 5/19/2022
