### ISSUE TITLE
Add more methods in device profile client

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#324]
Device service need more device profile client methods (core/clients/metadata/device_profile.go), specially query device profiles. Currently only Add method is implemented.
If there is no problem, I will work on it

**Comment by tsconn23** [comment]
@jduranf Can you please make the title of this issue more specific? Also, can you enumerate the methods you plan to add and provide a summary of what they're for?

**Comment by jduranf** [comment]
@tsconn23 I'm helping @tonyespy in gxds. When the device service starts, it needs to retrieve the device profiles used by the devices which use the device service. So the idea it's to modify the device profile in order to have those methods:
```
type DeviceProfileClient interface {
	Add(dp *models.DeviceProfile) (string, error)
	Delete(id string) error
	DeleteByName(name string) error
	DeviceProfile(id string) (models.DeviceProfile, error)
	DeviceProfileForName(name string) (models.DeviceProfile, error)
	DeviceProfiles() ([]models.DeviceProfile, error)
}
```
