### ISSUE TITLE
Metadata: Callback for device deletion is done by id - should be by name

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/edgex-go#3253]
https://github.com/edgexfoundry/edgex-go/blob/3a622268bb16cc6f060a937717ebd043e18486e3/internal/core/metadata/v2/application/notify.go#L75

**Comment by cloudxxx8** [comment]
the same problem in provision watcher deletion
https://github.com/edgexfoundry/edgex-go/blob/3a622268bb16cc6f060a937717ebd043e18486e3/internal/core/metadata/v2/application/notify.go#L161

we should check all the callback execution
