### ISSUE TITLE
[Secure Consul Ph. 3] Fine tune Vault configuration as to Consul's secret engine token's TTL

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/edgex-go#3258]
# 🚀 Feature Request

### Relevant Package

 
This feature request is for `secretstore-setup` and `security-bootstrapper`.

### Description

Vault configuration will be changed to request `two (2) hour` expiring Consul access tokens instead of non-expiring global management tokens.

### Describe the solution you'd like
 
- Change the original setting of never-expiring default TTL when we install Vault's `consul secret engine` to 2 hours TTL
  - Based on recent learnings, the current TTL is not non-expiring, rather it uses the default lease TTL
  - However, should be issuing regular service tokens with scoped access policy vs global management tokens
- Change the TTL while creating agent token in `security-bootstrapper` so that it will not create non-expiring agent token. (currently the default vaule is "0s" when we create it).
  -  This this should be dropped; no harm in non-expiring agent token since consul saves it anyway
- Revoke or delete all existing non-expiring agent tokens from Consul (residuals from Phase 1 or Phase 2) if any.
  - Don't need to do this.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by bnevis-i** [comment]
Replanned for Levski in Levski planning 5/19/2022

**Comment by bnevis-i** [comment]
Turns out that consul token never expires, instead, Vault actively revokes it.
