### ISSUE TITLE
Update SwaggerHub to include SourceName

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#3259]
Per Monthly Architect's meeting today, it was noted that the SwaggerHub documentation for the Event object was missing SourceName that is now in the model objects.

**Comment by lenny-intel** [comment]
Move this issue to edgex-go where the swagger files are located.

**Comment by weichou1229** [comment]
Added the SourceName field to swagger API doc at PR https://github.com/edgexfoundry/edgex-go/pull/3266
