### ISSUE TITLE
export-* services don't support standard log settings

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#328]
The export services in the California release use a different logging package (go.uber.org/zap)
than all the other services, therefore it's not possible to configure their logging behavior via consul or local configuration settings.

The snap build configures all of the service to write out log files to a **$SNAP_COMMON** (a write-able directory shared by all versions of the snap), but since the export-* services don't support a **LoggingFile** setting, their log files are not being written to disk when run inside the snap.  When run in docker containers, it's not possible to change the name of the log file, nor can the services be configured to use the support-logging service.

This bug is being reported against the latest code as of Jun 25 '18.

**Comment by drasko** [comment]
Export services were the first ones written, ment to serve as a blueprint for other services. Not all propositions from this blueprint were respected, so Export services diverged.

This should be fixed with the PR and Export services should be aligned to other services.
