### ISSUE TITLE
[V2] Get Binary Reading from database hasn't been implemented

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3286]
# 🚀 Feature Request

### Relevant Package

 This feature request is for core-data

### Description
The Binary Reading conversion hasn't been implemented in the infrastructure layer
https://github.com/edgexfoundry/edgex-go/blob/bf41993ae39f966b0d993bd56432d2f66e6af597/internal/pkg/v2/infrastructure/redis/reading.go#L235-L236

**Comment by cloudxxx8** [comment]
@jinlinGuan for awareness.  we should test the Binary Reading creation and query from core-data API

**Comment by lenny-intel** [comment]
@cloudxxx8, @jinlinGuan,   Note that Binary Reading values are not stored in the database, so expectation is the actual value will be empty, but reading properties are present.
