### ISSUE TITLE
[v2 notifications] Succeed to update values of required fields to empty

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#3298]
# 🐞 Bug Report

### Affected Services

 The issue is located in: support-notification

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
1. Create a subscription with the following body.
```
POST method
[
   {
      "subscription":{
         "name":"Subscription-1616666801751",
         "description":"Test data for subscription",
         "channels":[
            {
               "emailAddresses":[
                  "123@123.com"
               ],
               "type":"EMAIL"
            }
         ],
         "categories":[
            "health-check"
         ],
         "labels":[
            "simple"
         ],
         "receiver":"tafuser",
         "resendLimit":0,
         "resendInterval":"24h"
      },
      "apiVersion":"v2"
   }
]
```
2. Update values of required fields with the following body for the above subscription.
```
PATCH method
[
   {
      "subscription":{
         "name":"Subscription-1616666801751",
         "description":"Test data for subscription",
         "channels":[],
         "categories":[],
         "labels":[],
         "resendLimit":0,
         "resendInterval":"24h"
      },
      "apiVersion":"v2"
   }
]
```

## 🔥 Exception or Error
<pre><code>
Update successfully and query the subscription got the following response.
{
    "apiVersion": "v2",
    "requestId": "",
    "message": "",
    "statusCode": 200,
    "subscriptions": [
        {
            "id": "0b7cd56c-07cb-4ab4-8928-05f47c0dd8c4",
            "name": "Subscription-1616666801751",
            "channels": [],
            "receiver": "tafuser",
            "created": 1616726155362,
            "modified": 1616726277028,
            "description": "Test data for subscription",
            "resendInterval": "24h"
        }
    ]
}

</code></pre>
Excepted to get status code 400 when sending update subscription.

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:** master

**Anything else relevant?**

**Comment by weichou1229** [comment]
Fixed by the core-contracts PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/566
For upgrading the core-contracts lib, wait for the PR https://github.com/edgexfoundry/edgex-go/pull/3299 merge.

**Comment by cherrycl** [comment]
The empty channel issue was fixed by PR [edgexfoundry/go-mod-core-contracts#566](https://github.com/edgexfoundry/go-mod-core-contracts/pull/566). Raised #3316 for empty label and category.
