### ISSUE TITLE
go.mod doesn't exist

### ISSUE THREAD

**Issue by Castle1984** [edgexfoundry/edgex-go#3307]
The issue is located in: security-secretstore-setup
When I used the Dockerfile located in edgex-go/cmd/security-secretstore-setup to build image, it reports "go.mod does not exist".
Should I just copy the edgex-go/go.mod to edgex-go/cmd/security-secretstore-setup?
Thanks a lot！

**Comment by cloudxxx8** [comment]
@Castle1984 May I know how do you build the image?  Are you using the Makefile?  Please provide the recreate steps.

**Comment by Castle1984** [comment]
> @Castle1984 May I know how do you build the image? Are you using the Makefile? Please provide the recreate steps.

I wanna use the [Dockerfile](https://github.com/edgexfoundry/edgex-go/blob/master/cmd/security-secretstore-setup/Dockerfile) to build image, and I use the command "sudo docker build -t secret-setup:v1 ." in the path "edgex-go/cmd/security-secretstore-setup".
All I want to do is that I hope to use the image secret-setup generated by the [Dockerfile](https://github.com/edgexfoundry/edgex-go/blob/master/cmd/security-secretstore-setup/Dockerfile) to  test the exe security-secretstore-setup which is generated by the [Makefile](https://github.com/edgexfoundry/edgex-go/blob/master/Makefile). Is that right? I'm not sure.
Once I use [docker-compose.yml](https://github.com/edgexfoundry/edgex-go/blob/master/cmd/security-secretstore-setup/testdata/docker-compose.yml) to build the image to test the secretstore(using command "docker-compose up"), and it works well. But I think the image used in this testdata  is pulled from the website, and it dosen't use the the exe security-secretstore-setup generated by myself.
Or could you give me another way to test the the exe security-secretstore-setup which is generated by the [Makefile](https://github.com/edgexfoundry/edgex-go/blob/master/Makefile)? That will help a lot!

**Comment by weichou1229** [comment]
@Castle1984 You need to build from the root of project, see https://github.com/edgexfoundry/edgex-go#installation-and-execution
```
cd edgex-go
make build
```

**Comment by Castle1984** [comment]
> @Castle1984 You need to build from the root of project, see https://github.com/edgexfoundry/edgex-go#installation-and-execution
> 
> ```
> cd edgex-go
> make build
> ```

Sorry, I think you may misunderstand what I mean. I did use the command "cd edgex-go&make build", and there will be a executable file 'security-secretstore-setup' in the path edgex-go/cmd/security-secretstore-setup. And now my question is how to test this exe 'security-secretstore-setup' , so I tried to use the [Dockerfile](https://github.com/edgexfoundry/edgex-go/blob/master/cmd/security-secretstore-setup/Dockerfile) in the path where there also exits the exe 'security-secretstore-setup'. But when using the command "cd edgex-go/cmd/security-secretstore-setup&sudo docker build -t secret-setup:v1 .", the error message is "go.mod does not exist".

**Comment by weichou1229** [comment]
@Castle1984 
> But when using the command "cd edgex-go/cmd/security-secretstore-setup&sudo docker build -t secret-setup:v1 .", the error message is "go.mod does not exist".

The go.mod is located at the root of project, you can see the correct command at the Makefile:
```
docker_security_secretstore_setup:
		docker build \
	    --build-arg http_proxy \
	    --build-arg https_proxy \
		-f cmd/security-secretstore-setup/Dockerfile \
		--label "git_sha=$(GIT_SHA)" \
		-t edgexfoundry/docker-security-secretstore-setup-go:$(GIT_SHA) \
		-t edgexfoundry/docker-security-secretstore-setup-go:$(DOCKER_TAG) \
		.
```
https://github.com/edgexfoundry/edgex-go/blob/master/Makefile#L179

So you should not build the docker image at the path `edgex-go/cmd/security-secretstore-setup`.

**Comment by Castle1984** [comment]
Thanks a lot. I 'm causing all you some troubles, for I'm not familiar with this project.
The answer does helps a lot.

**Comment by Castle1984** [comment]
Thx a lot. I 'm causing all you some troubles, for I'm not familiar with this project.
The answer does help a lot.
