### ISSUE TITLE
[v2 notification] Delete subscription should return 200 instead of 204

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#3308]
# 🐞 Bug Report

### Affected Services

 The issue is located in: support-notification

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
1. Create a subscription with the following body
`[
   {
      "subscription":{
         "name":"subscription-test",
         "description":"Test data for subscription",
         "channels":[
            {
               "recipients":[
                  "123@123.com"
               ],
               "type":"EMAIL"
            }
         ],
         "categories":[
            "health-check"
         ],
         "labels":[
            "simple"
         ],
         "receiver":"tafuser",
         "resendLimit":0,
         "resendInterval":"24h"
      },
      "apiVersion":"v2"
   }
]`
2. Delete the subscription.

## 🔥 Exception or Error
<pre><code>

</code></pre>
Returned 204 No content.

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:** master

**Anything else relevant?**

**Comment by weichou1229** [comment]
This issue will fix by https://github.com/edgexfoundry/edgex-go/pull/3310

**Comment by cherrycl** [comment]
This issue was fixed.
