### ISSUE TITLE
[v2 notifications] Succeed to update both fields labels and categories to empty

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#3316]
# 🐞 Bug Report

### Affected Services

 The issue is located in: support-notification

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
1. Create a subscription with the following body.
```
POST method
[
   {
      "subscription":{
         "name":"subscription-test",
         "description":"Test data for subscription",
         "channels":[
            {
               "recipients":[
                  "123@123.com"
               ],
               "type":"EMAIL"
            }
         ],
         "categories":[
            "health-check"
         ],
         "labels":[
            "simple"
         ],
         "receiver":"tafuser",
         "resendLimit":0,
         "resendInterval":"24h"
      },
      "apiVersion":"v2"
   }
]
```
2. Update the labels and categories to empty with the following body for the above subscription.
```
PATCH method
[
   {
      "subscription":{
         "name":"subscription-test",
         "categories":[],
         "labels":[]
      },
      "apiVersion":"v2"
   }
]
```
## 🔥 Exception or Error
<pre><code>

</code></pre>
Update successfully.
Expected to update failure and return 400.

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**master

**Anything else relevant?**

**Comment by weichou1229** [comment]
Will fix by the PRs
https://github.com/edgexfoundry/go-mod-core-contracts/pull/570
https://github.com/edgexfoundry/edgex-go/pull/3327
