### ISSUE TITLE
[v2 notification] Returned 500 error when sending subscription API by api gateway

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#3323]
# 🐞 Bug Report

### Affected Services

 The issue is located in: support-notifications

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
1. Create a subscription with token and the following body
```
POST : https://localhost:8443/notifications/api/v2/subscription

[
   {
      "subscription":{
         "name":"Subscription-1617093569521",
         "description":"Test data for subscription",
         "channels":[
            {
               "host":"http://123.com",
               "port":1234,
               "httpMethod":"POST",
               "type":"REST"
            }
         ],
         "categories":[
            "health-check"
         ],
         "labels":[
            "simple"
         ],
         "receiver":"tafuser",
         "resendLimit":0,
         "resendInterval":"24h"
      },
      "apiVersion":"v2"
   }
]
```

## 🔥 Exception or Error
<pre><code>

[
    {
        "apiVersion": "v2",
        "message": "object Id existence check failed",
        "statusCode": 500
    }
]
</code></pre>
The other APIs returned the same status code with different message, like the following.
GET Response : url=https://localhost:8443/notifications/api/v2/subscription/name/subscription-test 
{"apiVersion":"v2","message":"fail to query subscription by name subscription-test","statusCode":500}

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**master

**Anything else relevant?**

**Comment by cherrycl** [comment]
Sending API through api gateway or not, both got 500 error, and found the below error log in support-notification logs.

`level=ERROR ts=2021-03-31T03:19:07.965518997Z app=edgex-support-notifications source=subscription.go:75 X-Correlation-ID=c1c9d71f-8f01-4e30-b8e6-364ac0c07adf msg=" ->  -> object Id existence check failed -> NOAUTH Authentication required."`

**Comment by weichou1229** [comment]
@jim-wang-intel @lenny-intel 
Do you have any idea about this error?
`
level=ERROR ts=2021-03-31T03:19:07.965518997Z app=edgex-support-notifications source=subscription.go:75 X-Correlation-ID=c1c9d71f-8f01-4e30-b8e6-364ac0c07adf msg=" -> -> object Id existence check failed -> NOAUTH Authentication required."
`

It seems fail to pass the RedisDB Authentication.
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/v2/infrastructure/redis/queries.go#L159

**Comment by jim-wang-intel** [comment]
> @jim-wang-intel @lenny-intel
> Do you have any idea about this error?
> `level=ERROR ts=2021-03-31T03:19:07.965518997Z app=edgex-support-notifications source=subscription.go:75 X-Correlation-ID=c1c9d71f-8f01-4e30-b8e6-364ac0c07adf msg=" -> -> object Id existence check failed -> NOAUTH Authentication required."`
> 
> It seems fail to pass the RedisDB Authentication.
> https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/v2/infrastructure/redis/queries.go#L159

Hi @weichou1229  the redis's client is being set by calling newDBClient and as I am seeing so far, the redis' client in V2 version doesn't contain the password field so that the configuration is missing the password or credentials to redis db.  So I think in the constructor of NewClient of client.go we need to have the secretstore client and then retrieve the credentials from Vault and then set the password field into the db configuration before passing that into redisClient.NewClient call in client.go.

**Comment by weichou1229** [comment]
> set the password field into the db configuration before passing that into redisClient.NewClient call in client.go.

@jim-wang-intel Thank you, it works by passing the password to the db configuration.
