### ISSUE TITLE
How to get data from EdgeX Foundry Performance Report?

### ISSUE THREAD

**Issue by suzixin** [edgexfoundry/edgex-go#3325]
Hi team:

In EdgeX Foundry Performance Report 
> Raw performance data underlying this report is provided here. ( https://docs.google.com/spreadsheets/d/131AVzDQk0Bq8Y3_NePScoP2PPVzwxYBe2fuztG3jetA/edit )

I wonder how to run this Performance test in my project, thanks.

**Comment by suzixin** [comment]
> The following notes describe how the performance data described in this report was captured. The services were run with their default configurations and the Virtual Device was allowed to run and produce sensor data in its default manner (generating data every 30 seconds for a variety of mimicked sensors).
The CPU and memory usage data was captured from Docker Engine via docker stats after successful start-up of EdgeX using the release Docker Compose files. Data export testing was run 15 times – that is generating 15 event/readings through Core Data to the Application Services layer via the Virtual Device Service.

Can you give me an example to measure the time to export the data to an endpoint, thanks.

**Comment by cloudxxx8** [comment]
Please see the document here
https://github.com/edgexfoundry/edgex-taf/blob/master/docs/edgex-taf.md
https://github.com/edgexfoundry/edgex-taf/blob/master/docs/run-performance-metrics-collection-on-local.md

You had better run with the released version v1.3.1 = hanoi

**Comment by suzixin** [comment]
Thanks for sharing related document! I still have this Question:

> The following notes describe how the performance data described in this report was captured. The services were run with their default configurations and the Virtual Device was allowed to run and produce sensor data in its default manner (generating data every 30 seconds for a variety of mimicked sensors).
The CPU and memory usage data was captured from Docker Engine via docker stats after successful start-up of EdgeX using the release Docker Compose files. Data export testing was run 15 times – that is generating 15 event/readings through Core Data to the Application Services layer via the Virtual Device Service.

Can you give me an example to measure the time to export the data to an endpoint, thanks.

**Comment by cloudxxx8** [comment]
what kind of the example?

**Comment by cloudxxx8** [comment]
please follow the document I provided and run the script, and you can get all the metrics.  the test script is the tool.

**Comment by suzixin** [comment]
Oh, I am sorry, I miss the Statistics from the  detail execution reports.
Thanks for your patience.

**Comment by cloudxxx8** [comment]
no problem
