### ISSUE TITLE
update interval hanged, no response

### ISSUE THREAD

**Issue by tianxingguo** [edgexfoundry/edgex-go#3332]
tried to update am interval , not get response , hanged always:

Put request , URL：http://localhost:4000/support-scheduler/api/v1/interval

 {"name":"cc","id":"8a6b542d-3e57-4c0e-9e1c-268b9506468e","frequency":"15m","start":"20210407T160000","end":"20210423T160000"}

checked code from https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/interval.go

// Validate satisfies the Validator interface
func (i Interval) Validate() (bool, error) {
	if !i.isValidated {
		if i.ID == "" && i.Name == "" {
			return false, NewErrContractInvalid("Interval ID and Name are both blank")
		}
		if i.Start != "" {
			_, err := time.Parse(timestampLayout, i.Start)
			if err != nil {
				return false, NewErrContractInvalid(fmt.Sprintf("error parsing Start %v", err))
			}
		}
		if i.End != "" {
			_, err := time.Parse(timestampLayout, i.End)
			if err != nil {
				return false, NewErrContractInvalid(fmt.Sprintf("error parsing End %v", err))
			}
		}
		if i.Frequency != "" {
			/* legacy frequencyPattern */
			matched, _ := regexp.MatchString(frequencyPattern, i.Frequency)
			if matched {
				if i.Frequency == "P" || i.Frequency == "PT" {
					matched = false
				}
			}
			if !matched {
				// parse frequency example "1h15m30s10us9ns"
				_, err := time.ParseDuration(i.Frequency)
				if err != nil {
					return false, NewErrContractInvalid(fmt.Sprintf("invalid Interval frequency %s format", i.Frequency))
				}
			}
		}
		**err := validate(i)**
		if err != nil {
			return false, err
		}
		return true, nil
	}
	return i.isValidated, nil
}

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version: 1.3.1

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@tianxingguo are you able to workaround this bug by deleting and re-adding the interval?
we don't have a plan for additional patch release in v1.3, but we will make sure this issue is resolved in v2.

@weichou1229 could you please confirm whether we resolve this in V2? thanks.

**Comment by tianxingguo** [comment]
@cloudxxx8  , not try  to workaround this bug by deleting and re-adding the interval yet, will try

**Comment by weichou1229** [comment]
@tianxingguo 
I can't recreate your issue. Could you provide the steps to recreate your issue?

Here are my steps:
1. Run `docker-compose -f docker-compose-hanoi-no-secty.yml up -d`
2. Post an interval
  ```
% curl http://localhost:48085/api/v1/interval -X POST -H "Content-Type: application/json" -d '{
    "name": "cc",
    "start": "20210407T160000",
    "end": "20210423T160000",
    "frequency": "15m"
}'
02c24146-1b6a-47f5-89b6-cced176d2dfe
  ```
3. Put the interval with id
```
% curl http://localhost:48085/api/v1/interval -X PUT -H "Content-Type: application/json" -d '{
    "id": "02c24146-1b6a-47f5-89b6-cced176d2dfe",
    "name": "cc",
    "start": "20210407T160000",
    "end": "20210423T160000",
    "frequency": "15m"
}'
true
```

**Comment by jpwhitemn** [comment]
@tianxingguo - I was able to confirm this works as well in Hanoi v1.3.1.  I was able to use PUT to update the start, end and frequency without issue.  Can you provide additional instructions on what failed and how to repeat your issue?  I will close this bug in a few days and assume it is no longer an issue unless I hear from you.

**Comment by jpwhitemn** [comment]
Closed as it appears not to be a bug.
