### ISSUE TITLE
export-client and export-distro are missing Attribution.txt

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#334]
Both export-client and export-distro are missing third party Attribution.txt files containing third party package names and licenses.  These files are included in all the core services.

This being reported against commit: e2f3f75

**Comment by yanghua** [comment]
hi @tonyespy it seems the Attribution.txt file exists in export-client and export-distro modules in master branch, what did you mean?

**Comment by jpwhitemn** [comment]
Closing as these services do have Attribution.txt.
