### ISSUE TITLE
I think we probably need to add a separate Redis installation description text

### ISSUE THREAD

**Issue by yangsongx** [edgexfoundry/edgex-go#3343]
# 📚 Docs or Wiki Bug Report

### Description

I think we probably need to add a separate Redis installation description,  in https://github.com/edgexfoundry/edgex-go#native-binaries,

like Go, pkg-config, ZeroMQ.

Otherwaise, someone else would probably miss this when setup the env with the step-by-step instruction.

**Comment by jpwhitemn** [comment]
@yangsongx - we do have mention of it in our documentation (see https://docs.edgexfoundry.org/1.3/getting-started/Ch-GettingStartedDevelopers/#redis).  We are reluctant to put all the steps, but rather make reference to the appropriate 3rd party instructions as these may change over time.
Are you looking for something else?  Please specify or close this request.

**Comment by jpwhitemn** [comment]
Closed for now.  Can reopen if additional information is requested.
