### ISSUE TITLE
core-command metadata command client uses wrong URL

### ISSUE THREAD

**Issue by carmelomigliore** [edgexfoundry/edgex-go#335]
Hi, I noticed that the core-command metadata command client utilizes the wrong URL. In particular, it uses the metadata device URL and this leads to an error, because it looks for commands in the device collection of the metadata DB. In order to fix this issue it should be sufficient to set the right URL in the "params" variable in the init.go file of core-command, before the initialization of the command client:
`params.Url = conf.MetaCommandURL`

Cheers
Carmelo

**Comment by jduranf** [comment]
You are right @carmelomigliore, I have sent the PR #337 to fix the issue

**Comment by jduranf** [comment]
Fix done #337 
Can someone close this issue?
