### ISSUE TITLE
ADD_PROXY_ROUTE does not set the service path property

### ISSUE THREAD

**Issue by jrtitus** [edgexfoundry/edgex-go#3353]
```yml
edgex-proxy:
  environment:
    ADD_PROXY_ROUTE: my-app.http://my-app:5002/configuration
```

## Actual
```bash
$ http :8001/services/my-app
{
...
"host": "my-app",
"id": "b5b61afb-d981-4d07-bc58-562bb7b29d52",
"name": "my-app",
"path": null,  # <------
"port": 5002,
"protocol": "http",
...
}
```
## Expected
```bash
$ http :8001/services/my-app
{
...
"host": "my-app",
"id": "b5b61afb-d981-4d07-bc58-562bb7b29d52",
"name": "my-app",
"path": "/configuration",  # <------
"port": 5002,
"protocol": "http",
...
}
```
## More Info

**Version**: `hanoi` (latest)
https://github.com/edgexfoundry/edgex-go/blob/12a188d7528ee379d18cf3e1ac715e90dfef7258/internal/security/proxy/service.go#L249-L253

**Version**: `master` (latest)
https://github.com/edgexfoundry/edgex-go/blob/4a93de6e2e8f65a45d7e1065c78fcf8c18a7addf/internal/security/proxy/service.go#L229-L234

**Function**: `parseAdditionalProxyRoutes`

It seems that `ClientInfo` does not have a `Path` attribute (in hanoi version)
https://github.com/edgexfoundry/go-mod-bootstrap/blob/359809f15d43a2ad8492a83d1d9944950c58c3af/config/types.go#L84-L91

Nor does `KongService` have it (in master version)
https://github.com/edgexfoundry/edgex-go/blob/4a93de6e2e8f65a45d7e1065c78fcf8c18a7addf/internal/security/proxy/models/kongParameters.go#L18-L23

which would explain why it does not work as I thought it would.

**Comment by hutchic** [comment]
Per our docs https://docs.edgexfoundry.org/1.3/microservices/security/Ch-APIGateway/ paths cannot be specified in the environment though could be specified when you make the REST api call through the Kong proxy.

**Comment by jrtitus** [comment]
> Per our docs https://docs.edgexfoundry.org/1.3/microservices/security/Ch-APIGateway/ paths cannot be specified in the environment though could be specified when you make the REST api call through the Kong proxy.

Hi @hutchic

1. Unless I have completely missed it, nowhere on the linked page does it explicitly say that. 

    Maybe you are referring to this snippet?
    > Once ADD_PROXY_ROUTE is configured and composed-up successfully, the proxy route then can be accessed the app's REST API via Kong as http://localhost:8000/myApp/api/v1/...

    It is also confusing, since the `/api/v1` route is not added automatically as this documentation implies. It would simply be `http://localhost:8000/myApp/...`

2. I just thought it would be a nice enhancement to this already useful feature since Kong technically supports the configuration.
