### ISSUE TITLE
Replace github.com/BurntSushi/toml with github.com/pelletier/go-toml

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3354]
# 🚀 Feature Request

### Relevant Package
all

### Description
We use github.com/pelletier/go-toml in other go modules, so it had better be consistent.
Also, this could reduce the dependency libraries.

**Comment by lenny-intel** [comment]
Agreed, I just verified that the one location we use `BurntSushi/toml` can be replaced with using `pelletier/go-toml` to un-marshal the contents of the TOML file. In this case it is only used in unit tests, which I have verified pass when using `pelletier/go-toml`

The Attribution file will need to be updated to remove  `BurntSushi/toml`.
