### ISSUE TITLE
Improve the http middleware trace log function

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3369]
# 🚀 Feature Request

### Relevant Package

 This feature request is for all services

### Description
Refer to the PR https://github.com/edgexfoundry/device-sdk-go/pull/878/files
OnResponseComplete and OnRequestBegin handler can be combined, and the log level could be checked before logging the trace.

```
func LoggingMiddleware(lc logger.LoggingClient) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if lc.LogLevel() == models.TraceLog {
				begin := time.Now()
				correlationId := IdFromContext(r.Context())
				lc.Trace("Begin request", clients.CorrelationHeader, correlationId, "path", r.URL.Path)
				next.ServeHTTP(w, r)
				lc.Trace("Response complete", clients.CorrelationHeader, correlationId, "duration", time.Since(begin).String())
			} else {
				next.ServeHTTP(w, r)
			}
		})
	}
}
```

**Comment by cloudxxx8** [comment]
It's an easy issue, and we should implement it by Ireland

**Comment by jpwhitemn** [comment]
Decision per Core WG -> keep this in Ireland backlog.  Should be easy enough to do and useful to current release.
