### ISSUE TITLE
Enable / disable a schedule interval action (without having to deleting the schedule interval action)

### ISSUE THREAD

**Issue by phanvanhai** [edgexfoundry/edgex-go#3375]
# 🚀 Feature Request

### Relevant Package

 This feature request is for Scheduler service

### Description
 In some IoT applications, the user creates some scheduling. However, the user can stop running the scheduler, and at any time, re-run the scheduler's interval.

So I think we need to add the ability to start/ stop the scheduler (similar the rules engine service)

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
we can consider to add AdminState to intervalAction

**Comment by jpwhitemn** [comment]
Cloud proposes admin state to be added to interval action  (like in device/device service) to enable / disable the interval action without having to delete/re-add the interval action.  Agreed per Core WG for Ireland

**Comment by cloudxxx8** [comment]
@weichou1229 please enable the check of adminState in both support-notifications and support-scheduler
