### ISSUE TITLE
the RAML API document description is conflicted on /registration/name/{name} GET method

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#338]
https://github.com/edgexfoundry/edgex-go/blob/master/export/client/raml/export-client.raml

The description of /registration/name/{name} GET method states:

`description: Fetch a client export registration by unique name. Response will be null if no export registration matches on name. Return ServiceException (HTTP 503) for unknown or unanticipated issues.`

Also, the API states:

```
 "404": 
                description: if the existing export registration cannot be found by name
```

They are conflicted, so Java Export Client service returns 200 OK with null content if no export registration matches on name, and Go Export Client services returns 404 Not Found with some error message.

**Comment by tsconn23** [comment]
@cloudxxx8 Assigned @janko-isidorovic @drasko. To me a 404 sounds more correct since the client registration is not found, and that's what 404 means. We didn't even include the Java version of export-client in the California release branch, so I don't think we should try to make this backward compatible.

**Comment by drasko** [comment]
@cloudxxx8 what do you mean "we need to modify RAML"? It is stating that `404` should be returned - what modification do you need?

**Comment by cloudxxx8** [comment]
@drasko 
We should modify the description of this API: 
`description: Fetch a client export registration by unique name. **Response will be null if no export registration matches on name.** Return ServiceException (HTTP 503) for unknown or unanticipated issues.`

If 404 is the expected behavior, client will not receive any response body.  Also, null is the language specific term.  In the old implementation (Java), it returns 200 OK with null information in the response body.  Could we eliminate the line from description?  Thanks.

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/edgex-go/pull/396
I also corrected the API definition of registration id not found situation

**Comment by tsconn23** [comment]
#396 has been merged. Closing.
