### ISSUE TITLE
[scheduler] IntervalAction should use v2 API to scrub event

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#3383]
# 🐞 Bug Report

### Affected Services

 The issue is located in: support-scheduler

 
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
1. Deploy edgex with command `docker-compose up -d` using [compose file](https://github.com/edgexfoundry/edgex-compose/blob/45d1bd870c75a8f14dd17f45ce6d29c2649691f7/docker-compose-pre-release-no-secty.yml).
2. Send GET request `http://localhost:48085/api/v2/intervalaction/all`.

## 🔥 Exception or Error
<pre><code>

Used v1 path on the intervalaction.
{
    "apiVersion": "v2",
    "statusCode": 200,
    "actions": [
        {
            "created": 1618882789048,
            "modified": 1618882789048,
            "id": "42ccb903-9a3d-4288-b7ea-ef52d6b62be1",
            "name": "scrub-pushed-events",
            "intervalName": "midnight",
            "address": {
                "type": "REST",
                "host": "edgex-core-data",
                "port": 48080,
                "path": "/api/v1/event/scrub",
                "httpMethod": "DELETE"
            }
        },
        {
            "created": 1618882789047,
            "modified": 1618882789047,
            "id": "aae70cc3-0306-4ede-9643-f549e27e23dd",
            "name": "scrub-aged-events",
            "intervalName": "midnight",
            "address": {
                "type": "REST",
                "host": "edgex-core-data",
                "port": 48080,
                "path": "/api/v1/event/removeold/age/604800000",
                "httpMethod": "DELETE"
            }
        }
    ]
}
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:** master

**Anything else relevant?**

**Comment by weichou1229** [comment]
Will modify the scheduler config to use V2 API for removing the events
https://github.com/edgexfoundry/edgex-go/blob/master/cmd/support-scheduler/res/configuration.toml#L50
https://github.com/edgexfoundry/edgex-go/blob/master/cmd/support-scheduler/res/configuration.toml#L60
