### ISSUE TITLE
AddEventRequest.Event.DeviceName field is required;

### ISSUE THREAD

**Issue by lazy-wangxl** [edgexfoundry/edgex-go#3397]
Both device-SDK-c and edgex-go using master branch，but have error like this:

**edgex-core-data print error**:
level=ERROR ts=2021-04-23T09:03:27.36112248Z app=edgex-core-data source=event.go:79 X-Correlation-ID=48b17e6b-79a9-4f92-9ee5-dbe313c6bdca msg="event json decoding failed -> AddEventRequest.Event.Versionable.ApiVersion field is required; AddEventRequest.Event.Id field is required; AddEventRequest.Event.DeviceName field is required; AddEventRequest.Event.ProfileName field is required; AddEventRequest.Event.SourceName field is required; AddEventRequest.Event.Origin field is required; AddEventRequest.Event.Readings field should greater than 0"

**device-SDK-c device service send JSON**:

{"apiVersion":"v2","id":"4a490cb1-4ab3-4a5d-b775-40838d73e8ae","deviceName":"Device0","profileName":"wxl-Device","origin":1619090818025212800,"readings":[{"apiVersion":"v2","id":"7ba8ed77-ff22-4272-a693-750acd735969","profileName":"wxl-Device","deviceName":"Device0","resourceName":"SwitchButton","value":"0.0000000000000000e+00","origin":1619090818025212800,"valueType":"Float64"}]}

**Comment by cloudxxx8** [comment]
I guess C SDK is still under development to support V2 API.
The core-data should receive "AddEventRequest" in V2, not "Event" object.
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/post_event__profileName___deviceName___sourceName_

@iain-anderson for awareness.

**Comment by xahehe** [comment]
@cloudxxx8 Thank you for your answer，but when C SDK can support V2 API，or is there same problem using V1 API?

**Comment by cloudxxx8** [comment]
V1 API is fine.  Please use Hanoi release (v1.3.x)

**Comment by xahehe** [comment]
@cloudxxx8 Thank you very much!

**Comment by xahehe** [comment]
@cloudxxx8 There is no Hanoi release (v1.3.x)

**Comment by xahehe** [comment]
@cloudxxx8 Excuse me，edgex-go has Hanoi release，but C SDK not
**edgex-go# git branch -a**
  delhi
* hanoi
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/california
  remotes/origin/delhi
  remotes/origin/dependabot/go_modules/github.com/edgexfoundry/go-mod-core-contracts/v2-2.0.0-dev.73
  remotes/origin/dependabot/go_modules/github.com/lib/pq-1.10.0
  remotes/origin/edinburgh
  remotes/origin/fuji
  remotes/origin/geneva
  **remotes/origin/hanoi**
  remotes/origin/master
  remotes/origin/save
  remotes/origin/semver

**device-sdk-c# git branch -a**
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/delhi
  remotes/origin/edinburgh
  remotes/origin/fuji
  remotes/origin/geneva
  remotes/origin/master
  remotes/origin/semver

and also, when I use Hanoi release of edgex-go, error:
**level=ERROR ts=2021-04-26T02:08:55.26698524Z app=edgex-core-metadata source=deviceservice.go:56 X-Correlation-ID=ad27a942-a62e-4f9d-9b05-8cb5f37c1a37 msg="device service json decoding failed -> OperatingState field should be one of 'ENABLED' 'DISABLED'"**

**Comment by cloudxxx8** [comment]
In edgex-go, please use v1.3.1 tag
In device-sdk-c, please use v1.3.0 tag
Please use tag instead of branch

**Comment by xahehe** [comment]
@cloudxxx8 Thanks, Best Regards!

**Comment by iain-anderson** [comment]
issue re AddEventRequest in CSDK will be fixed when https://github.com/edgexfoundry/device-sdk-c/pull/336 lands

**Comment by cloudxxx8** [comment]
https://github.com/edgexfoundry/device-sdk-c/pull/336 merged
