### ISSUE TITLE
make build failed

### ISSUE THREAD

**Issue by gy95** [edgexfoundry/edgex-go#3414]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
run `make build` failed

## 🔥 Exception or Error
<pre><code>

CGO_ENABLED=1 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=0.0.0" -o cmd/core-data/core-data ./cmd/core-data
go: bitbucket.org/bertimus9/systemstat@v0.0.0-20180207000608-0eeff89b0690: missing go.sum entry; to add it:
	go mod download bitbucket.org/bertimus9/systemstat
make: *** [Makefile:58: cmd/core-data/core-data] Error 1
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** go1.16.3

**EdgeX Version:** latest

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@gy95 , this is a known issue moving from Go 1.15 to Go 1.16. Please run `go mod tidy` and then rerun `make`

**Comment by gy95** [comment]
> @gy95 , this is a known issue moving from Go 1.15 to Go 1.16. Please run `go mod tidy` and then rerun `make`

ok, thanks, that solved the problem
