### ISSUE TITLE
[v2 sys-mgmt] Implement v2 health API

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/edgex-go#3418]
# 🚀 Feature Request

### Relevant Package

 This feature request is for sys-mgmt-agent

### Description
Implement v2 `/health` API

**Comment by hahattan** [comment]
According to https://app.swaggerhub.com/apis/EdgeXFoundry1/system-agent/2.0#/default/post_health, 
v2 `/health` API requires a POST request with the services specified in request body.

Compared to v1: https://app.swaggerhub.com/apis/EdgeXFoundry1/system-agent/1.2.1#/default/get_v1_health__services_
which is a GET  request with services as a parameter specified in URL path.

To me v1 design is more intuitive as we're not actually POST something to database.
@cloudxxx8 @lenny-intel what's your opinion?

**Comment by cloudxxx8** [comment]
agree, the design in v1 is better

**Comment by lenny-intel** [comment]
@hahattan, @cloudxxx8 , I also agree that POST is not correct for this, but the V1 approach with the service list in the REST path seems odd.
I.e. this the path to get `core data` and `core metadata` would be `/v1/health/edgex-core-data,edgex-core-metadata` .
Is this valid REST? 
Should the service list instead be in query parameter?

**Comment by hahattan** [comment]
> Also looks like the /config API needs to be reworked to be a GET.  

And also `/metrics`, they all have the same format in v1 (comma-separated)

I'm okay with using query parameter in v2 implementation.

**Comment by cloudxxx8** [comment]
Since all of those POST API are for query, please modify them to GET and continue to use the V1 path design as much as possible

**Comment by hahattan** [comment]
Revisiting this API after finishing others, considering the case:
```
$ curl http://localhost:58890/api/v2/health/core-data,invalid
{
    "apiVersion": "v2",
    "statusCode": 200,
    "health": {
        "core-data": "healthy",
        "invalid": "invalid service is not registered. Might not have started... "
    }
}
```

compared to other API:
```
curl http://localhost:58890/api/v2/configs/core-data,invalid
{
    "apiVersion": "v2",
    "message": "service invalid not found in Registry",
    "statusCode": 404
}
```

I would suggest make the behavior identical:
- 200 base response if all services are healthy
- 404 if any of services not found
- 500 if consul is not running

@cloudxxx8 @lenny-intel what do you think ?

**Comment by cloudxxx8** [comment]
I will bring up this topic to today's Core WG meeting

**Comment by jpwhitemn** [comment]
Redesign!!  Cloud and team trying out.  Will report back next week if this falls to 2.0.1
Use GET with query parameter (instead of URL comma separated list)
URL:  http://localhost:58890/api/v2/config/services
param:  {comma separated list}
Response - 207 for response with at least partial success (with sub block 404 for any service not found)
