### ISSUE TITLE
Standardize DBClient package level variable declaration

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#347]
In core-data, var dbc is declared and initialized in init.go
In core-metadata, var dbClient is declared in const.go and initialized in init.go

I personally think the name dbClient is preferable, being more explicit, and I like core-data’s methodology better since the variable isn't really a constant. I'm open to discussing another approach, but we need to standardize what the var is called, where it's declared and then update references accordingly.

From #298

**Comment by feclare** [comment]
I agree both on variable name and where it should be declared.

**Comment by jduranf** [comment]
Also should be fine to standardize the database enumeration. Data uses core/data/interfaces/db.go, and metadata uses core/domain/enums/database.go. I think the best place should be in core/db/db.go. What do you think?

If you want, I can work in this issue

**Comment by feclare** [comment]
@jduranf Yes, I had that in my todo list. Also adding db selection to metadata and standardize how it is done with data.
Feel free to work on it.

**Comment by feclare** [comment]
Thanks
