### ISSUE TITLE
Add CouchDB implementation to core-metadata

### ISSUE THREAD

**Issue by dylanhantula** [edgexfoundry/edgex-go#349]
Given that Mongo is licensed under the AGPL license, we want to use CouchDB in core-metadata (not core-data, which has an InfluxDB interface). CouchDB is document store similar to Mongo, but is licensed under the Apache license. This will involve creating CouchDB-specific implementations of the already existing database interfaces.

**Comment by jpwhitemn** [comment]
Per Core WG, and work carried out under the Data Persistence project, implementing with other DBs is not within the roadmap until after Edinburgh refactoring and making further determinations about what reference implementations will be supported long term.
