### ISSUE TITLE
[v2 sys-mgmt-agent] Implement v2 PUT /configs API

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/edgex-go#3491]
# 🚀 Feature Request

### Relevant Package

 This feature request is for sys-mgmt-agent

### Description
Implement v2 PUT `/configs` API

### Describe the solution you'd like
Let's first look at an example of this API in v1:
the API endpoint is `/api/v1/configs/core-data,core-metadata`, and the request body:
```
{
    "key": "MessageQueue.Optional.ConnectTimeout",
    "value": "10"
}
```
Response:
```
200 OK
{
    "configuration": {
        "core-data": {
            "success": true
        },
        "core-metadata": {
            "success": false,
            "description": "key does not exist"
        }
    }
}
```

2 problem here:
1. It tries to update the same field of the request services.
2. return 200 even if the update doesn't succeed on some services.

==========================================================================================

My proposal:

Change the API endpoint to `/api/v2/configs`, move the requested services into request body instead of URL parameter.

example request body:
```
[
    {
        "apiVersion": "v2",
        "requestId": "130c3986-dc6f-4174-80f6-1b492b55234c",
        "name": "core-data",
        "configs": {
            "MessageQueue.Optional.ConnectTimeout": "10"
        }
    },
    {
        "apiVersion": "v2",
        "requestId": "f0ac0a8a-f33a-46b3-bc3c-5db542dc9afa",
        "name": "core-metadata",
        "configs": {
            "Service.StartupMsssg": "Welcome"
        }
    }
]
```

example response:
```
207 Multi-Status
[
    {
        "apiVersion": "v2",
        "requestId": "130c3986-dc6f-4174-80f6-1b492b55234c",
        "statusCode": 200
    },
    {
        "apiVersion": "v2",
        "requestId": "f0ac0a8a-f33a-46b3-bc3c-5db542dc9afa",
        "message": "key does not exist",
        "statusCode": 404
    }
]
```

In this case the use case and the request/response data model is more closer to our v2 design.

@lenny-intel @cloudxxx8 let me know if you have any comments.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
This API is not in the original V2 scope, pushing to Jakarta

**Comment by cloudxxx8** [comment]
@jpwhitemn if SMA will be deprecated, should we close this issue?

**Comment by cloudxxx8** [comment]
@lenny-intel if SMA will be deprecated, should we close this issue?

**Comment by lenny-intel** [comment]
Yes, but lets do this as part of next Core WG. @JamesKButcher please add "Sys Management Deprecation" to next Core WG ageneda.
