### ISSUE TITLE
[core-data] configuration.json defines endpoint URLs

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#35]
The new core-data configuration.json file specifies URLs for the various REST endpoints it uses from other services.  IMHOP, the configuration should specify the host and port of any dependent services, whereas the actual endpoints and versions being used should be part of the code itself.

Reported as of commit: 74f6945

**Comment by feclare** [comment]
+1

**Comment by drasko** [comment]
@tonyespy @tsconn23 any updates on this?

**Comment by tsconn23** [comment]
@drasko @tonyespy Yes, the work is done and I'm ready to PR. I'm waiting for the build issues to get resolved before submitting the PR.

**Comment by tsconn23** [comment]
@drasko Ignore previous comment if you saw it.

I haven't really looked closely at this yet due to other tasks.

**Comment by jduranf** [comment]
This have been fixed in #541
