### ISSUE TITLE
Add CouchDB implementation to export-client

### ISSUE THREAD

**Issue by dylanhantula** [edgexfoundry/edgex-go#350]
Given that Mongo is licensed under the AGPL license, we want to use CouchDB in export-client. CouchDB is document store similar to Mongo, but is licensed under the Apache license. This will involve creating CouchDB-specific implementations of the already existing database interface.

**Comment by drasko** [comment]
@dylanhantula out of curiosity - do you plan to change database code or link something to it, so AGPL license is dealbreaker, or is there some other motivation?

**Comment by jpwhitemn** [comment]
Per Core WG, and work carried out under the Data Persistence project, implementing with other DBs is not within the roadmap until after Edinburgh refactoring and making further determinations about what reference implementations will be supported long term.
