### ISSUE TITLE
[data] Duplicate readings are created after repeating create an event with readings for a while

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#3505]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-data

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
The error can be reproduced by the following steps after looping the steps around 200 times on my local environment.

1. Create event with the following request
`POST Request : url=http://localhost:59880/api/v2/event/Profile-Test-001/Device-Test-001/Command-Test-001`
```
 {
   "event":{
      "apiVersion":"v2",
      "deviceName":"Device-Test-001",
      "profileName":"Profile-Test-001",
      "sourceName":"Command-Test-001",
      "id":"f411e43c-6c6e-4ff8-b4f7-3d0842a0b56c",
      "origin":1621905556276000000,
      "readings":[
         {
            "deviceName":"Device-Test-001",
            "resourceName":"Simple-Reading",
            "profileName":"Profile-Test-001",
            "origin":1621905556276000000,
            "valueType":"Int8",
            "value":"3"
         }
      ]
   },
   "apiVersion":"v2"
}
```
2. Query all readings count and verify the count =1
`GET Request : url=http://localhost:59880/api/v2/reading/count`
3. Create event with the following request
`POST Request : url=http://localhost:59880/api/v2/event/Profile-Test-001/Device-Test-002/Command-Test-002`
```
{
   "event":{
      "apiVersion":"v2",
      "deviceName":"Device-Test-002",
      "profileName":"Profile-Test-001",
      "sourceName":"Command-Test-002",
      "id":"a02cc8ba-72b5-4786-bec7-e09c48690fac",
      "origin":1621905556321999872,
      "readings":[
         {
            "deviceName":"Device-Test-002",
            "resourceName":"Simple-Reading",
            "profileName":"Profile-Test-001",
            "origin":1621905556321999872,
            "valueType":"Int8",
            "value":"3"
         },
         {
            "deviceName":"Device-Test-002",
            "resourceName":"Simple-Float-Reading",
            "profileName":"Profile-Test-001",
            "origin":1621905556321999872,
            "valueType":"Float32",
            "value":"39.5"
         }
      ]
   },
   "apiVersion":"v2"
}
```
4.  Query all readings count and verify the count =3
`GET Request : url=http://localhost:59880/api/v2/reading/count`
5. Delete all events and readings.
`DELETE Request : url=http://localhost:59880/api/v2/event/age/0`

## 🔥 Exception or Error
<pre><code>

Request body include an event with 2 readings, but an event with 4 reading are created.
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**Master

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
duplicated to https://github.com/edgexfoundry/edgex-go/issues/3497
