### ISSUE TITLE
Add CouchDB implementation to support-logging

### ISSUE THREAD

**Issue by dylanhantula** [edgexfoundry/edgex-go#351]
Given that Mongo is licensed under the AGPL license, we want to use CouchDB in support-logging. CouchDB is a document store similar to Mongo, but is licensed under the Apache license. This will involve creating a CouchDB-specific implementation of the already existing database interface.

**Comment by jpwhitemn** [comment]
Given Core WG decision (per work conducted by Data Persistence project), EdgeX is not going to implement alternate database implementations of services until the database abstractions are put in place for Edinburgh and a determination is made about the long term support wrt to reference implementation(s) is made.
