### ISSUE TITLE
Core Metadata should use shorter strings, or possibly enums for callback to other services

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#355]
When Core Metadata calls a device service to indicate that an object in Core Metadata has changed, it indicates which type of object changed by using full strings such as:

 * "Device"
 * "DeviceProfile"
 * "ProvisionWatcher"
 * "Schedule"

One of the review comments for the California Device Services requirements (>= v7) was that it would make sense for these string constants to be changed to JSON enums.

This is being reported against the California release.

**Comment by jpwhitemn** [comment]
As callbacks to DS are not going to be part of Delhi, moved to Edinburgh.

**Comment by tsconn23** [comment]
I don't think this is a pain point at the moment, and am inclined to close due to lack of priority.
