### ISSUE TITLE
[Metadata] Get devices by servicename returns 503 unexpected end of JSON input

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/edgex-go#3574]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 

`core-metadata`

### Is this a regression?

Unsure

### Description and Minimal Reproduction
When attempting to initialize the device cache, the `device-sdk-go` makes a REST call to core-metadata, which returns an incorrect `HTTP 503` error. This error is only observed when querying the specific device service device, and not all of the devices. See my [gist](https://gist.github.com/ajcasagrande/502df0bd4d6ee1d29dcc54113adf52ba) for my current devices.

Also, `503` is the wrong error to return in this case it should be a `500`.

## 🔥 Exception or Error
```
GET http://localhost:48081/api/v1/device
```
[Response Gist](https://gist.github.com/ajcasagrande/502df0bd4d6ee1d29dcc54113adf52ba)

<hr/>

```
GET http://localhost:48081/api/v1/device/servicename/edgex-device-rfid-llrp
```
<pre><code>
HTTP: 503

unexpected end of JSON input
</code></pre>

Observed via [device-rfid-llrp-go](https://github.com/edgexfoundry/device-rfid-llrp-go) service startup:

<pre><code>
level=ERROR ts=2021-06-16T17:36:12.091729084Z app=edgex-device-rfid-llrp source=init.go:45 msg="Device cache initialization failed: 503 - unexpected end of JSON input\n"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 20.04
Docker

**EdgeX Version:**
Hanoi via `edgex-compose` repo.

**Anything else relevant?**
Encountered while running `device-llrp-rfid-go` service.

**Comment by ajcasagrande** [comment]
After running `make clean` on `edgex-compose` and re-discovering my device I no longer see the issue. It is possible this was due to me manually removing keys from `Redis`.

**Comment by jpwhitemn** [comment]
Per @ajcasagrande note above, will reopen if this issue resurfaces.
