### ISSUE TITLE
EdgeX Core-data Rest API bug

### ISSUE THREAD

**Issue by younes199511** [edgexfoundry/edgex-go#3586]
Hello,

# 🐞 Bug Report

The issue is that REST API Get reading request fails when there is more than 65 999 readings in the database. I configured the **maxResultCount** in core-data to 5 million. 

### Affected Services
Core-data

### Is this a regression?
No

### Description and Minimal Reproduction
- Fill the EdgeX database with more then 100 000 reading
- Set **MaxResultCount**  to a value greater than 66000
- Use the Core-data REST API to retrieve the reading (/api/v1/reading, /api/v1/reading/start/end/limit)
- Fix the limit to value greater than 65 999

## 🔥 Exception or Error 
Kong Error
An invalide response was received from the upstream server

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu 20.04
2 Gb RAM
Intel(R) Atom(TM) CPU E3805 @ 1.33GHz with 2 Cores

**EdgeX Version:**
Secured Hanoi 1.3.0 version of EdgeX Foundry

**Anything else relevant?**

see the atteched screen shots
![1](https://user-images.githubusercontent.com/44032734/122761464-9024e400-d29c-11eb-8915-23f390a39ab4.jpg)
![2](https://user-images.githubusercontent.com/44032734/122761470-90bd7a80-d29c-11eb-82db-45c56702de54.jpg)
![3](https://user-images.githubusercontent.com/44032734/122761472-91561100-d29c-11eb-9647-c3707b58de36.jpg)
![4](https://user-images.githubusercontent.com/44032734/122761474-91eea780-d29c-11eb-88ea-c633725d0cb9.jpg)

**Comment by cloudxxx8** [comment]
@younes199511 could you please see the log in Redis and the memory status of the machine?
`free -h`
I suspect it is the memory issue.  Redis is a memory database, and the machine is with limited free memory when you enable security services.
You have to set up a mechanism to clean up the old data in core-data to prevent it consume too much .

**Comment by younes199511** [comment]
@cloudxxx8 I think you are right, it is related to the memory (See the screnn shots)
How can configure redis to manage better the memory usage ? So, i have an analytics application that needs to retrieve from EdgeX last 24h data (around 450 000 reading) every 5 minutes. Is this possible to be done with my hardware (2 Gb of RAM) ?

**Comment by cloudxxx8** [comment]
discussed this question offline (via email)
closing this issue
