### ISSUE TITLE
[Core Data] New Reading query API feature request

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3597]
# 🚀 Feature Request

### Relevant Package

 This feature request is for core-data

### Description
/reading/device/name/{deviceName}/resourceName/{resourceName}
/reading/device/name/{deviceName}/resourceName/{resourceName}/start/{startTimestamp}/end/{endTimestamp}

**Comment by anilchoudhury** [comment]
Thank you team for adding this API.
