### ISSUE TITLE
Core Metadata API POST /provisionwatcher not per API version 2

### ISSUE THREAD

**Issue by ZipperResolver** [edgexfoundry/edgex-go#3606]
# 📚 Docs or Wiki Bug Report

### Description

The V2 API documentation for POST /provisionwatcher example lists "profile" and "service". They should be "profileName" and "serviceName".

Also, the provisionwatcher.json in the device-sdk-go example needs to be updated to V2.

The following provisionwatcher.json worked for me:

[
  {
    "requestId": "fb34e122-84d6-4c4c-a0ba-ac181021dc6b",
    "apiVersion": "v2",
    "provisionwatcher": {
      "name": "simple-watcher",
      "identifiers": {
        "Address": "simple[0-9]+",
        "Port": "3[0-9]{2}"
      },
      "blockingidentifiers": {
        "Port": [
          "399",
          "398",
          "397"
        ]
      },
      "profileName": "Simple-Device",
      "serviceName": "device-simple",
      "adminState": "UNLOCKED"
    }
  }
]

### What's the affected URL?**
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.0.0#/default/post_provisionwatcher

### Expected vs Actual Behavior**
Do POST http://0.0.0.0:59881/api/v2/provisionwatcher with the provisionwatcher,json in the device SDK example. The result is:

{
    "apiVersion": "v2",
    "message": "provision watcher json decoding failed",
    "statusCode": 400
}

## 🔥 Exception or Error
status code 400

**Comment by cloudxxx8** [comment]
thanks for reporting it.  it's a document bug.  we will correct the Swagger file.
I've opened issue for the SDK sample:
https://github.com/edgexfoundry/device-sdk-go/issues/996

**Comment by cloudxxx8** [comment]
@jinlinGuan please help correct the Swagger file
