### ISSUE TITLE
Utilize MaxRequestSize configuration in each microservice

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3612]
# 🚀 Feature Request

### Relevant Package

 This feature request is for all services

### Description
MaxRequestSize configuration is not currently used. 
It defines the maximum size of http request body in bytes.
Thus, we should implement this feature for all microservices.

**Comment by jinlinGuan** [comment]
Currently the MaxRequestSize is set to 0 (unlimited) by default. Do we need a reasonable default limit?
Also, do we need an upper limit?

**Comment by cloudxxx8** [comment]
I don't think we need an upper limit because there is no upper limit in other configuration and 0 (unlimited) is the valid value for the backward compatible.
Let's change the default value to 10240 KB (10 MB) for now.

**Comment by farshidtz** [comment]
Making the max request size configurable is a backward compatible change as long as its default value remains the same.

Reducing the default max size from unlimited to a limited range will break existing applications that do pass larger bodies.

This is a helpful reference:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/#behavioral-changes

> ❌ DISALLOWED: Decreasing the range of accepted values for a property or parameter
>
> ❌ DISALLOWED: Changing the default value of a property, field, or parameter

**Comment by cloudxxx8** [comment]
ok, let's keep the same default value 0

**Comment by jpwhitemn** [comment]
work already completed per PR above

**Comment by cloudxxx8** [comment]
we need to wait for https://github.com/edgexfoundry/go-mod-bootstrap/pull/321 is applied to the go.mod
