### ISSUE TITLE
whats's the difference of the version  in version.go  and in tag  

### ISSUE THREAD

**Issue by zhaogaojian** [edgexfoundry/edgex-go#3613]
I Find some tag is 2.0.0. but the version in version.go is 1.2.0 or  1.30 or 2.0,what's the difference.

**Comment by cloudxxx8** [comment]
the variable Version in the version.go will be overridden at the build time, so its initial value doesn't matter
https://github.com/edgexfoundry/edgex-go/blob/4edb777b9d60e900e8671f5ac6453e52ef440742/Makefile#L45

we should modify it to something like we did in device-sdk-go
`var Version string = "to be replaced by makefile"`
https://github.com/edgexfoundry/device-sdk-go/blob/5b7ab9a3ff9866f95cdc84e39a450aa5b3c9b9ea/version.go#L10

**Comment by zhaogaojian** [comment]
Thanks very much
