### ISSUE TITLE
How do I set up the EdgeX to allow CORS requests ？

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/edgex-go#3614]
hello, I want to send GET/PUT requests from the browser to the Edgex , which is used to send instructions to the device. But I'm having cross-domain problems and don't know if I can set it in Edgex.
`Access to XMLHttpRequest at 'http://172.16.4.148:48082/api/v1/device/name/My-Random-Integer-Device-03/command/Int8' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I referred to [this](https://github.com/intel-iot-devkit/automated-checkout-utilities/blob/0dd0e1e344399f3042b1f64b82ccbc2d2e0333aa/utilities.go#L69),but I don't know where to set it. 
 Please give me some help. thank you!

**Comment by cloudxxx8** [comment]
this is the feature we haven't implemented

**Comment by FengZeHe** [comment]
### 

> this is the feature we haven't implemented
Okay, thank you.
