### ISSUE TITLE
Miss created and modified fields when querying Device and Device Service

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3630]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-metadata

### Is this a regression?
No

### Description and Minimal Reproduction

1. Start up the EdgeX Ireland release.
2. Query Device or Device Service by /api/v2/deviceservice/all and /api/v2/device/all API
3. The results miss `created` and `modified` fields

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
2.0.0

**Anything else relevant?**
The `created` and `modified` fields exist in the Device Profile query results.

**Comment by weichou1229** [comment]
This issue will fixed by go-mod-contracts PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/653
