### ISSUE TITLE
Enable the authentication plugins on a route-by-route basis

### ISSUE THREAD

**Issue by younes199511** [edgexfoundry/edgex-go#3638]
# 🚀 Feature Request

### Relevant Package

 This feature request is for Security services (Kong, Proxy-setup).

### Description
 I want to add a route for a custom application service and i want to use LDAP authentication instead of JWT. I know that EdgeX does not support LDAP authentication but What I want to do is to enable the LDAP plugin only for my custom service (Kong allows to enable authentication plugins for specific route). The issue is that JWT used by EdgeX is applied for all routes available in Kong (global plugin) so I can't add new route with no authentication. 

### Describe the solution you'd like

The solution i have in mind is two use Kong feature that allows to enable the authentication plugins on a route-by-route basis instead of globally.  A user can use multiple authentications in same time.
### Describe alternatives you've considered
I couldn't bypass this problem in EdgeX because there is no way in Kong to exclude a specific route when an authentication plugin is applied globally.

**Comment by bnevis-i** [comment]
@younes199511 would you be able to validate the attached pull request to see if this fix works for you?

**Comment by younes199511** [comment]
@bnevis-i  I tried this fix but i'm still having the same issue. When i create a new route in Kong it is automatically secured by the JWT authentication. What i'm looking for is to choose manually if i want or not to secure the new route with EdgeX JWT authentication.
