### ISSUE TITLE
Upload Device Profile API is not clear

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3640]
# 📚 Docs or Wiki Bug Report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.0.0#/default/post_deviceprofile_uploadfile
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.0.0#/default/put_deviceprofile_uploadfile

### Expected vs Actual Behavior**
To use this API, users should put the file to the key called `file`, but the document doesn't state it clearly.

## 📷Screenshot 
![image](https://user-images.githubusercontent.com/11695863/127628230-3fd27269-1463-40d6-a8de-4bf31b4b02d0.png)

**Comment by wangshihui** [comment]
![image](https://user-images.githubusercontent.com/9709818/128479106-0e1c0e8e-6e93-436f-ac9f-d69d047d1058.png)

use the swagegr edtior  to explor the openapi in the source code 

or you can refer to the edgex online document 

https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.0.0#/default/get_deviceservice_all
