### ISSUE TITLE
Update lastConnected should not trigger the Device Service callback

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3641]
### Affected Services

 The issue is located in: core-metadata

### Is this a regression?
No

### Description and Minimal Reproduction
When lastConnected timestamp is updated, it also triggers the Device Service callback, which is unnecessary.

**Comment by cloudxxx8** [comment]
Need more discussion with Device WG

**Comment by iain-anderson** [comment]
Agreed in Device WG 2nd August that the DS does not need to track the last connected value - callback need not be triggered.

**Comment by lenny-intel** [comment]
OK, sounds good to me.

**Comment by jpwhitemn** [comment]
discussed in the Kamakura planning meeting (Nov 21) and deemed in scope for Kamakura.
