### ISSUE TITLE
when update the device profile, and restart the device service, but get the device all commands is not updated? why?

### ISSUE THREAD

**Issue by zhui19871** [edgexfoundry/edgex-go#3648]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by weichou1229** [comment]
Could you provide the steps to recreate the issue? It should works without restart the device service.

**Comment by zhui19871** [comment]
The step as follows:
1 update the local device profile.
2 restart the device service.

My environment is in hybrid, other service in running docker environment except my device service in running my local.

and i want ask, Could the edgex automatic update the configuartion when restart the deivce service? include devices and profiles configuration.

**Comment by weichou1229** [comment]
> 1 update the local device profile.

Did you update the device profile via REST API?

> Could the edgex automatic update the configuartion when restart the deivce service? 

The configuration will update when restart deivce service.

> include devices and profiles configuration.

If you pre-define the device and profile in the configuration file like , device service will check the device or profile by name when startup,
- the device or profile not exists,  adding the new one
- the device or profile exists,  using the existing one

**Comment by zhui19871** [comment]
You mean only just via rest api can update the existing configuation?

**Comment by zhui19871** [comment]
By pre-define the device and profile can not update the existing one when startup? is that?

**Comment by weichou1229** [comment]
Yes, please try to use the REST API, see https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.0.0

**Comment by cloudxxx8** [comment]
@zhui19871 since you are using hybrid environment, I suspect your core-metadata can't callback the Device Service correctly.
May I know the value of your service.host in the Device Service configuration?  It should be the docker0 ip address, such as 172.17.0.1.

**Comment by wangshihui** [comment]
if you wangt  to update the profile . 
you can check the profile by the metatdata's rest api `GET http://{metadatahost}/deviceprofile/name/{name}` check if is is the origin one.
then you can  try :
plan A:  you  may need to delete the profile use the metadata rest api  `DELETE http://{metadatahost}/deviceprofile/name/{name}` before you restart the device service . 
plan B:  update the profile use the metadata rest api `PUT  http://{metadatahost}/deviceprofile`

**Comment by wangshihui** [comment]
> > 1 update the local device profile.
> 
> Did you update the device profile via REST API?
> 
> > Could the edgex automatic update the configuartion when restart the deivce service?
> 
> The configuration will update when restart deivce service.
> 
> > include devices and profiles configuration.
> 
> No. If you pre-define the device and profile in the configuration file like , device service will check the device or profile by name when startup,
> 
> * the device or profile not exists,  adding the new one to core-metadata
> * the device or profile exists,  using the existing one

yes his answer is right .

**Comment by zhui19871** [comment]
yes, now look like is new feature. but if can automatic load the configation when restart device service, may be more convinences?

**Comment by wangshihui** [comment]
This feature is  more convinences For develop test.  
Also I think it should be configurable.  to avoid some unexpected operation  In the PRD env

**Comment by cloudxxx8** [comment]
@zhui19871 although it looks convenient, device service restart will always override the real changes from core-metadata in the production.
For example, a user make some real change through core-metadata APIs, but the changes will be reset whenever the device service restarts.  It's not a valid use case.
Close this issue as won't fix.
