### ISSUE TITLE
What is the format of sending the event ？

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/edgex-go#3667]
hi , i want to send an event to Core Data. I query the [document](https://docs.edgexfoundry.org/2.0/walk-through/Ch-WalkthroughReading/) and find it hasn't been updated yet (I have cleared the browser cache). I also looked [this](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.0.0#/) up, but didn't know what format to send the event JSON.

![image](https://user-images.githubusercontent.com/25740210/128985732-7784d2cb-64c9-4fbb-9343-de33417c67f9.png)

![image](https://user-images.githubusercontent.com/25740210/128990749-3036ec14-1830-4447-a61a-b089cdebced0.png)

Could you please tell me what the format is or tell me how to query ? Thanks.

**Comment by FengZeHe** [comment]
> @FengZeHe the `ID` is in UUID format. You can use any UUID generation tool for that. In Go Device Services, we use the function in `github.com/google/uuid`
> I believe all the programming languages contain some libraries to generate it automatically.
> You could also generate it via some online tools, such as https://www.uuidgenerator.net/

Thank you for your reply ! But something strange happened ,i send the data as "Example value", but it always return `event json decoding failed` . I generated the UUID and the current unix timestamp(nanosecond) .Here's the JSON data  and profile . Could you please help me to see where I filled in the wrong? Thanks!!

![image](https://user-images.githubusercontent.com/25740210/129294216-9c6a5948-bfa1-4f0e-8c0a-85a3a4423090.png)
![image](https://user-images.githubusercontent.com/25740210/129294436-5612b8f9-5d63-41de-82b8-f0aa00d1e7f6.png)

**Comment by weichou1229** [comment]
Could you try the command `docker logs edgex-core-data` to see the error logs?

**Comment by FengZeHe** [comment]
> Could you try the command `docker logs edgex-core-data` to see the error logs?

I noticed that I missed the ApiVersion field, that's my fault. Thank you !!
