### ISSUE TITLE
Errors in core-metadata API examples for get_device_*

### ISSUE THREAD

**Issue by jrtitus** [edgexfoundry/edgex-go#3672]
# 📚 Docs or Wiki Bug Report

### Description

 
1. `labels` is misspelled as `lables` 
2. `protocols` is displayed as an array of objects instead of an object with protocol names as keys

### What's the affected URL?**

https://app.swaggerhub.com/apis/EdgeXFoundry1/core-metadata/2.0.0#/default/get_device_all
https://app.swaggerhub.com/apis/EdgeXFoundry1/core-metadata/2.0.0#/default/get_device_name__name_

## 📷Screenshot 

![image](https://user-images.githubusercontent.com/1756049/129776125-c01fc032-67e3-4421-985a-fb66e8d39885.png)

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

Microsoft Edge
Version 92.0.902.73

**Comment by cloudxxx8** [comment]
fixed by #3673
