### ISSUE TITLE
[kuiper] security-secretstore-setup uses hard-coded YAML with docker network-name

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#3676]
# 🐞 Bug Report

### Affected Services

 The issue is located in: security-secretstore-setup

### Is this a regression?
No

### Description and Minimal Reproduction
The security-secretstore-setup was [modified](https://github.com/edgexfoundry/edgex-go/pull/3537) to additionally configure the Kuiper edgex source configuration file (`edgex.yaml`) in order to allow Kuiper to read messages from the secure message bus. A new configuration stanza was added (`[SecureMessageBus]`) which adds the keys:

  - `Type`
  - `KuiperConfigPath`

Issue #3538 was opened to track support in the snap for this feature. While the snap was updated to 1.2.1 per the issue, the two configuration overrides were not implemented, so Kuiper in the snap is currently broken. What I discovered was that even after  updating the two new options in `snapcraft.yaml` as follows:

```
Type="redis"
KuiperConfigPath="$SNAP_DATA/kuiper/etc/sources/edgex.yaml"
```

...the resulting file always has the following definition for the message bus:

```
default:
  optional:
    Username: redis5
    Password: xyx...
  port: 6379
  protocol: redis
  server: edgex-redis
.
.

```

This means this source file will be incorrect in the snap (server should be 'localhost') or native deployments, preventing Kuiper from properly reading events from the message bus.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** snap

**EdgeX Version:** 2.0.0

**Anything else relevant?**

**Comment by lenny-intel** [comment]
Yep, that needs to change to `server: localhost` which should not impact Docker since we have it set properly with environment variable. BTW, the snap [PR ](https://github.com/edgexfoundry/edgex-go/pull/3671 )is also overriding this with the `EDGEX__DEFAULT__SERVER` environment variable

**Comment by tonyespy** [comment]
FYI, I've updated the snap PR tp set `EDGEX__DEFAULT__SERVER=localhost`, however this doesn't solve the problem. See my PR for more details...

I think this is because the last time I checked, these `EDGEX__*` variables are only used by Kuiper for docker deployment...

**Comment by ngjaying** [comment]
@tonyespy Currently the env variable cannot work outside of Docker. Are you able to update the eKuiper/etc/sources/edgex.yaml directly during installation? Or build that conf_util_test.go, set KUIPER_HOME to your kuiper home location and run it.
