### ISSUE TITLE
Refactoring to strictly delineate internal code vs. externally usable code.

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#368]
**The Problem**
Currently the EdgeX GoLang implementation has no separation between its internal domain model and the models used to pass data out of the system. They are one and the same. Likewise, there is no visibility as to which service client is used by an external application versus solely used internal to the EdgeX platform. This means we are at risk of making changes to either our data models or our service client code that break any applications which have imported those items. We have no way to insulate our consumers from changes we make to the application based on an internal need, nor do we have the ability to hide internal/private details of our data model since our data model is also part of our client contract.

**The Recommendation**
In order to facilitate the separation of internal/external domain models and logic, we realized that we would need to restructure the application packages. At a high level, the changes we decided to make are as follows:

/edgex-go/core
•	will be re-purposed to contain those models and libraries which are usable by external applications
•	will include the following:
    o	clients package – service clients usable by external applications 
    o	models package – data models usable by external applications
             	NOTE: These will be identical to the current property bags found today in /edgex-go/core/domain/models

/edgex-go/internal
•	This package will be extended to include all code that we do not want external applications explicitly relying on as recommended by the [golang-standards](https://github.com/golang-standards/project-layout) project layout
•	That means the following packages will be moved into here in some fashion
    o	/edgex-go/core/command
    o	/edgex-go/core/core-data
    o	/edgex-go/core/core-metadata
    o	/edgex-go/export
    o	/edgex-go/support
        	Consul-client, domain, logging
        	Service client packages will most likely go to core above
•	Domain models included herein may start off as identical to those found today in /edgex-go/core/domain/models but have the flexibility to change and move around over time according to the internal needs of the platform.
                         
We are looking at making this change early in the Delhi development cycle, so please provide feedback in a timely fashion if you have it. Also please note that any external applications which are directly linking to the current package structure within the master branch of EdgeX will break when we do this. That is unavoidable. We are doing this now so that the pill isn’t too bitter to swallow later.

**Comment by jduranf** [comment]
Maybe will be also fine to change all `Id bson.ObjectId` in domain/models to `ID string`. The change from Id to ID is a linter recommendation. The change from `bson.ObjectId` to `string` will make the code less dependent from MongoDB, and also will simplify the code (there are lots of conversions from `ObjectId` to `string` and viceversa).

**Comment by tsconn23** [comment]
@jduranf Yes, I agree something like that will need to happen. I probably won't address it as part of this issue as I have the requirement from the Device Service group to keep the external domain model the same. But with their cooperation once this is merged, I'm sure we can make our domain model DB provider agnostic, as it should be.

**Comment by tsconn23** [comment]
I'm about to submit the first PR for this issue in which the majority of the delineated code has been moved to its new location. I'm adding this comment to record my thoughts at this point on what the end goal is going to look like. There will be a couple more subsequent PRs I think.

- edgex-go/core to be renamed to edgex-go/external
        All code importable by 3rd party applications wishing to integrate with EdgeX will go here
- edgex-go/core/domain to be removed and models moved up to edgex-go/external/models.
       These models will serve as the data model for external client application consumption
- edgex-go/core/domain/enums will be collapsed into the above models package
- Instead of an edgex-go/internal/app directory containing all of the services, I decided to preserve the "core" / "export" / "support" packages as representative of the logical tiers of the platform. Therefore the service implementation code will go into a respective directory such as internal/core/metadata or internal/export/distro
- We have to refactor database-specific types out of our domain model (such as the BSON ObjectIDs)
        This should instead be a string on the model and the Mongo provider itself will be responsible for validating any platform specific datatype requirements.

**Comment by jduranf** [comment]
@tsconn23, as pointed by Stella and recommended by [golang-standards](https://github.com/golang-standards/project-layout) maybe instead of "external/" we can use "api/" and "pkg/". In "/pkg" we can put all clients, and in "api/" the json models and the RAML files.
Also, maybe "snap/" and "docker/" should be moved inside of "build/".

**Comment by tsconn23** [comment]
@jduranf Working on it now. I'm going to hold off on moving the deployables to "build/" until I get feedback from @SteveOss @anonymouse64 @tonyespy

**Comment by jduranf** [comment]
@tsconn23 good work in #369!
I guess export/ and support/ will be moved inside of internal/ in the second part.
Also I want to comment that maybe the configuration files should be moved in configs/, but this doesn't seems to be an easy thing to do.

**Comment by tsconn23** [comment]
@jduranf Yes, export/ and support/ will be in part 2. As to the configs, our Delhi workload is going to see a major rework of how we handle configuration, so I'm not including those in this work. They'll most likely be moved, but not sure where yet.

**Comment by feclare** [comment]
@tsconn23 what about moving the models and enums to edgex-go/external/ instead of edgex-go/external/models. 
In export we followed this approach, having the shared types in edgex-go/export instead of edgex-go/export/domain and it looked cleaner to me.

**Comment by tsconn23** [comment]
Since external is akin to a top-level package, I wanted to keep it as clean as possible -- thus "clients/" and "models/" plus other things that may come in the future.

**Comment by anonymouse64** [comment]
Re: moving `snap` and `docker` inside of build I disagree, as firstly it makes it harder to build the project as a snap when the `snapcraft.yaml` file isn't either in `$GIT_ROOT/snapcraft.yaml` or `$GIT_ROOT/snap/snapcraft.yaml`. So at least the snap and docker folders should remain in the root folder.

**Comment by jduranf** [comment]
Done via #369, #390 and #494 
@tsconn23 and @brandonforster, please open again if there are more to do
