### ISSUE TITLE
Support for custom attributes in Device object

### ISSUE THREAD

**Issue by AnilChoudhury-Eaton** [edgexfoundry/edgex-go#3685]
# 🚀 Feature Request

### Relevant Package
coredata
command
metadata

Adding custom attributes to the Device object to cater various needs like defining parent-child relationships or storing/defining additional device attributes.

### Description
Currently the EdgeX has defined a fixed set of attributes for device object. There is no way for a user to define custom attributes in a device object. Currently EdgeX supports custom 'attributes' field in 'DeviceResource' of the device profile. Device object has a 'protocols' attribute which has custom field support but additional custom device attributes are not related to protocols.

### Describe the solution you'd like
So we are looking for two types of support in the Device object
1. Device object should have a new attribute called 'parent' and metadata should support REST API to  get all devices having same parent. This can help to discover all devices under a particular parent.
2. Addition of custom 'attributes' field in 'Device' object similar to 'DeviceResource' object. This will help to store any custom data of a device like its child devices, Access control for a device or any other information. Extracting and processing of this field is left to device services and application services.

### Describe alternatives you've considered
Parent-child relationship is a very important area for us as gateways are multi tiered and we need to know the complete line diagram of any device from root.
We may need to develop an additional service who can maintain the device relationships but it would bring sync issues.
Or we may look to add the suggested changes ourselves but then it may or may not get standardized and accepted for all to use as it would be a separate patch set.

**Comment by anilchoudhury** [comment]
Thanks @cloudxxx8. Lets discuss this topic in next WG meeting. As suggested by @eaton-coreymutter labels can be used but has some customization needed by the users.

**Comment by tonyespy** [comment]
As discussed in the Core WG this week:

  - It should be possible to model the parent/child relationship using labels. It was pointed out that the device endpoint doesn't support labels as query parameters. While that may be true, it's still pretty trivial to ask for all of the devices (or all for a specific profile) and then implement your custom query in Go.  We could also enhance the device endpoint to allow querying by label too, which would be much easier to implement than the proposed child/parent linkage.
  - Regarding the custom attributes for devices, the recommendation was just to use the ProtocolProperties mechanism for this.
  
  @iain-anderson It was also suggested that we discuss this at the next device services WG.

**Comment by cloudxxx8** [comment]
The type of ProtocolProperties is `map[string]map[string]string`, so the capability is limited.
A clear new `Properties map[string]interface` provide more flixibility.

@tonyespy the labels query parameter has been implemented in the current v2 API
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.0.0#/default/get_device_all

**Comment by JamesKButcher** [comment]
Moving to Icebox for Jakarta. A solution exists with labels and any changes to better support this will be high impact. Consider again in Kamakura planning meeting.

**Comment by anilchoudhury** [comment]
Thanks

**Comment by jpwhitemn** [comment]
Discussed in the Kamakura planning meeting (Nov 21).  Did not make the cut for Kamakura scope.  Leave in the **icebox** for future release planning.

**Comment by cloudxxx8** [comment]
it's in the main branch, so will be released in v3.0 next month
