### ISSUE TITLE
Unable to install edgex-go related package

### ISSUE THREAD

**Issue by Rakshithakrishna2** [edgexfoundry/edgex-go#3687]
Wanted to use EdgeX Ireland version (2.0.0), for that:

To build the edgeX-go natively I am following the READme file. 

Started to install the dependency packages, 
1.My Go version is 1.17
2. For having :pkg-config- I executed the below command,
go get github.com/rjeczalik/pkgconfig/cmd/pkg-config
rakshitha@xxx:~/Ireland$ go get github.com/rjeczalik/pkgconfig/cmd/pkg-config
When executed that I am getting the following,

go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
AS per the information above, I did as below,

rakshitha@xxx:~/Ireland$ go install pkg@version
go install: pkg@version: malformed module path "pkg": missing dot in first path element

For information: my go env is:
rakshitha@xxx:~/Ireland$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rakshitha/.cache/go-build"
GOENV="/home/rakshitha/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rakshitha/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rakshitha/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3725321080=/tmp/go-build -gno-record-gcc-switches"

Kindly help me to natively build the edgex go services successfully.

**Comment by Rakshithakrishna2** [comment]
Okay, thank you @cloudxxx8

**Comment by cloudxxx8** [comment]
opened https://github.com/edgexfoundry/edgex-go/issues/3689 to update the Readme file.
