### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#37]
A couple of suggestions for improving our new logging service:

 * it would be nice if we the service operated similar to Go's log package, which provide functions which provides versions of all the logging functions that take printf style strings (e.g. Debugf, Errorf, ...)

 * we should add a facility to allow log levels to be specified per logging client, ideally in such a manner that the level can be adjusted dynamically via a REST API

 * remove logger.c name & line number from log messages.  Currently log messages are being output with the following format:

INFO: YYYY/MM/DD HH:MM:SS logger.go:<line #> <log message>

**Comment by drasko** [comment]
I would opt for JSON structured logs that can be easily parsed by a machine. this is why in `export` services we used Uber Zap: https://github.com/uber-go/zap

**Comment by rtmaster** [comment]
In addition to zap, this is a good package to rotate logs https://godoc.org/gopkg.in/natefinch/lumberjack.v2

**Comment by yanghua** [comment]
hi all,
It seems the project has two log formats when I run multiple microservices. I am writing the scheduler microservice. The JSON format looks good. But who can tell me which one I should choose?

**Comment by yanghua** [comment]
Hi all,
If no one can give a suggestion, I will agree with @drasko and @rtmaster to replace `logger.LoggingClient` with uber's zap in my #57 issue. I find the `logger.LoggingClient` can not print the real code line and define log output level like **log4j**.

**Comment by tsconn23** [comment]
@yanghua You need to be sure your logging solution is behind an interface. Properly speaking, logger.loggingClient IS an interface and it is used by all of the core services. You could potentially extend the loggingClient factory to instantiate your new type of logger similar to what has been done for the DBClient.

**Comment by yanghua** [comment]
@tsconn23 I know `LoggingClient` client is a interface. But I think the system/framework kernal should provide a **unified** (a project just need one format) and **extendible** (could have multiple implementations, but should not let upper modules implement itself, they just need to use the abstract API) log framework. The unified and controllable log format would bring many advantages: collect, parse, analyze and so on.

**Comment by drasko** [comment]
Status?

**Comment by drasko** [comment]
If no objections, I will close this one due too inactivity.

**Comment by drasko** [comment]
Closed due to inactivity.
