### ISSUE TITLE
Persistence of selected DeviceResource events

### ISSUE THREAD

**Issue by anilchoudhury** [edgexfoundry/edgex-go#3703]
# 🚀 Feature Request

### Relevant Package
core-data
This feature is required to avoid storing all events from all DeviceReources but store critical DeviceResources events to persistence storage

### Description
Currently core-data supports non-persistence or persistence for all event data to persistent store.
It should support a middle ground, where user can configure which DeviceResource events need to be persisted and which all can be maintained in RAM only and does to need to be persisted.

### Describe the solution you'd like
Add a new configuration some thing like 'persistence' to deviceResources in device profile.
This can define if we want to persist events related to this DeviceResource.
This is very important for small storage devices and to avoid too much wear out of flash.

### Describe alternatives you've considered
1. We can create separate instances of redis database and using one to store the persistence data and other to non-persistence data. Currently we are disabling persistence of core-data as it writes too much data to database.
2. We are looking to store these events separately directly to redis by our own way.

**Comment by cloudxxx8** [comment]
this can be achieved by filtering events from the message bus topic
https://github.com/edgexfoundry/edgex-go/blob/a77f58c90179b916eae9116a1115cd7226a95c94/cmd/core-data/res/configuration.toml#L49

The full topic of event is
edgex/events/device/<device-profile-name>/<device-name>/<source-name>

**Comment by anilchoudhury** [comment]
Hi @cloudxxx8,
This has following limitations:
- It will block keeping event record for any other device even in non-persistent way
- It can be designed to filter a particular device or device profile events only.  How to define 10 devices under different device profiles
- It can't define a way to configure persistence for 10 deviceReources out of 1000 deviceResources for a type of device

**Comment by cloudxxx8** [comment]
You can also set up application service to export data to various database with customized filters
core-data is not designed for long term storage

**Comment by eaton-coreymutter** [comment]
Discussed in today's Core WG meeting.
We can work around by having an app service filter events we want to persist onto a different event bus topic (app-service-configurable can even do this). Then we can run a second persist-everything core-data on that topic, and get the data to the main (non-persisting) core-data via that app service (would have to write it).
We could look at implementing something like a "persist" bool in events handled by one core-data, but that's a bigger/future project so we can close this issue.

**Comment by JamesKButcher** [comment]
Thanks @eaton-coreymutter
