### ISSUE TITLE
[Core Data] Delete events and readings by key-ids directly

### ISSUE THREAD

**Issue by gao270615179** [edgexfoundry/edgex-go#3708]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
core data

### Is this a regression?

 No

### Description and Minimal Reproduction
When there are very much events and readings, the redis takes up a lot of memory space, maybe fulling the whole memory.
And then delete events and readings by age, these functions (getEventReadingIdsByKeyScoreRange/ asyncDeleteReadingsByIds / asyncDeleteEventsByIds) will get objects of events or readings by key-ids, which need more memory for these objects.

## 🔥 Exception or Error
<pre><code>

This case will make memory full and cpu spiking. What is much worse, the system may be crash.

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu Core, memory 4G
**EdgeX Version:**
2.0.1-dev.43

**Anything else relevant?**
First, get events and readings key-ids, don't get object, and delete events and readings by key-ids directly.

**Comment by JamesKButcher** [comment]
@cloudxxx8 please can you verify the behaviour here w.r.t. get the Ids/objects?

**Comment by cloudxxx8** [comment]
get the Event object is really unnecessary in `getEventReadingIdsByKeyScoreRange`.  thanks, @gao270615179 
https://github.com/edgexfoundry/edgex-go/blob/e3fe4ea6dc2b0363ea17cb6a495f96496b33254f/internal/pkg/infrastructure/redis/event.go#L226-L235
@weichou1229 please fix it

however, the object of asyncDeleteReadingsByIds and asyncDeleteEventsByIds are necessary to get the device name and resource name.
https://github.com/edgexfoundry/edgex-go/blob/e3fe4ea6dc2b0363ea17cb6a495f96496b33254f/internal/pkg/infrastructure/redis/event.go#L57
https://github.com/edgexfoundry/edgex-go/blob/1ef40f4947fe237c3bfb0e23cc22e5d8128712fc/internal/pkg/infrastructure/redis/reading.go#L61-L62
