### ISSUE TITLE
Consul cannot be freely switched between secure and insecure modes

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#3712]
# 🐞 Bug Report

### Affected Services
EdgeX Registry service
EdgeX Configuration service

### Is this a regression?
Depends on your perspective.

### Description and Minimal Reproduction
In Ireland release, we hardened access to Consul, the component that provides Registry and Configuration services to EdgeX microservices.  It used to be possible to start EdgeX with security disabled or security enabled, depending on the user's choice.  

Now, when booting EdgeX in secure mode, Consul ACL support is enabled.  It has been determined through experimentation that once ACL support has been enabled, it is not possible to restart the framework in insecure mode without breaking client's access to the registry and configuration.

cc: @tonyespy please edit description to add more detail.

**Comment by bnevis-i** [comment]
@jim-wang-intel @lenny-intel 

I am having difficulty reproducing this issue.  Test case:

- Start the framework in secure mode (docker)
- Run docker exec -ti edgex-core-consul consul kv get edgex/appservices/2.0/app-rules-engine/SecretStore/Protocol (403 error)
- Edit docker-compose files, make /edgex-init writable, change acl enabled mode to false, docker stop edge-core-consul, make run (dev) to restart services
- Run docker exec -ti edgex-core-consul consul kv get edgex/appservices/2.0/app-rules-engine/SecretStore/Protocol (result: http)

Clearly, Consul is respecting the ACL enabled flag and it CAN be changed.

**Comment by jim-wang-intel** [comment]
@bnevis-i yes, i couldn't re-produce it in Docker compose environment either.  I think it is only having problem for @tonyespy while running in snap environment or settings.

**Comment by tonyespy** [comment]
As requested by the Security WG, I’ve tested editing the `consul_acl.json` file (found in `$SNAP_DATA/consul/config`) to set `acl.enabled=false` to see if this will disable ACL checking in Consul (after a restart), and unfortunately the answer seems to be no.

Here are the steps I’ve tried (`SNAP_DATA=/var/snap/edgexfoundry/current`):

- `sudo snap install edgexfoundry --channel=2.0 `
- `sudo snap set edgexfoundry security-secret-store=off` (this halts kong, postgres, and vault, and sets the env var `EDGEX_SECURITY_SECRET_STORE=false` for all of the services (except for device-virtual and app-service-configurable which aren’t configured in `snapcraft.yaml` to use the required command chain script which handles this var).
- individually stop (using `snap stop …`) core-data, core-command, core-metadata, redis, and consul
- `sudo rm $SNAP_DATA/redis/conf/*.conf, sudo touch $SNAP_DATA/redis/conf/redis.conf`
- set `acl.enable=false` in `$SNAP_DATA/consul/config/consul_acl.json`
- `rm $SNAP_DATA/consul/data/acl_tokens.json`
- `sudo snap start edgexfoundry.redis` (and same for consul and  core-metatadata)

This almost works as both consul and redis start, however when I start core-metadata, it fails trying to read its configuration from consul:

```
level=INFO app=core-metadata source=config.go:359 msg="Loaded service configuration from /var/snap/edgexfoundry/3196/config/core-metadata/res/configuration.toml"
level=INFO app=core-metadata source=variables.go:352 msg="Variables override of 'SecretStore.TokenFile' by environment variable: SECRETSTORE_TOKENFILE=/var/snap/edgexfoundry/3196/secrets/core-metadata/secrets-token.json"
level=INFO app=core-metadata source=config.go:156 msg="Using Config Provider access token of length 0"
level=INFO app=core-metadata source=config.go:334 msg="Using Configuration provider (consul) from: http://localhost:8500 with base path of edgex/core/2.0/core-metadata"
2021-09-08T16:56:28.874-0400 [ERROR] agent.http: Request error: method=GET url=/v1/kv/edgex/core/2.0/core-metadata/Notifications/Description from=127.0.0.1:48296 error="Permission denied"
```

**NOTE** - I also tried deleting the file `$SNAP_DATA/consul/config/consul_acl.json` with similar results.
I think the problem may be that in addition to configuring consul to require ACLs, it’s also configured to use vault as the backend for its key store, but this is just a theory for now.

**Comment by tonyespy** [comment]
I just re-ran the same sequence of commands and am still seeing the same failure when I start core-metadata:

Note, when I restart Consul, I do see the following warnings output continually every 30s:

`2021-09-29T11:52:36.553-0400 [WARN]  agent: Coordinate update blocked by ACLs: accessorID=00000000-0000-0000-0000-000000000002`

**Comment by anonymouse64** [comment]
Doesn't re-running docker-compose to do essentially `docker-compose ... down` and `docker-compose ... up` delete the containers entirely and then re-run them? If so that would not be testing what @tonyespy is testing at all since restarting the snap will not destroy the writable config at all the same way that I understand `docker-compose ... down` would.

**Comment by bnevis-i** [comment]
We discussed this at least week's security WG meeting.  Tony realized that start-consul.sh rewrites the consul config file and forces enabled=true every time, undoing the earlier work to disable it.  A fix to this should return things to normal, expected operation.
