### ISSUE TITLE
Integrate GoKart security scanning

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#3715]
GoKart is a static data flow analysis tool for Golang.

https://www.praetorian.com/blog/introducing-gokart/

https://github.com/praetorian-inc/gokart

**Comment by deadmangareader** [comment]
@bnevis-i , I would be interested in picking this up.

From what I see, there are [2 Github actions ](https://github.com/marketplace?type=actions&query=gokart+)that can be used. Otherwise, a pipeline can be created to generate a report and use the job as a pass/fail criteria.

**Comment by bnevis-i** [comment]
@deadmangareader   Thank you!   We haven't vetted the quality/effectiveness of GoKart yet.  So what I would like to see is (1) run it manually and analyze the output to see if it is catching anything new that CodeQL, golangci-lint, gosec, etc isn't catching.  Assuming it produces good results, then (2) integrate it into the "make test" target so that developers can run it locally.  Then contact our DevOps WG about integrating it into a github action.

**Comment by bnevis-i** [comment]
@deadmangareader Do you have any Hactoberfest results?  We can schedule you for the November 9 security WG meeting to share your results.

**Comment by bnevis-i** [comment]
Returning back to icebox.  Up for discussion in Minnesota release planning.

**Comment by geraldzm** [comment]
![image](https://user-images.githubusercontent.com/39227998/230155030-cd09ef57-5ad6-4f4e-93f6-811cd821a5ba.png)
![image](https://user-images.githubusercontent.com/39227998/230155098-9c03febe-b27c-4f77-9e0a-be459faa2112.png)
![image](https://user-images.githubusercontent.com/39227998/230155162-4ce01ca2-2045-454d-990f-64cd8227f8ab.png)

**Comment by bnevis-i** [comment]
Based on the above result and lack of findings in other repos, do not believe that GoKart is finding anything of relevance.  Above report does not capture enough data flow to be able to identify vulnerable data paths.

**Comment by bnevis-i** [comment]
Closed as wontfox
