### ISSUE TITLE
Core Command crash when sending command to Device Camera, and camera is offline

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#3716]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Core Command (although the actual bug could be in one of our go modules)

**Note** - this is not the same as issue #3611, which involves a crash where the device service is unavailable, this issue is about the device (e.g. camera) not being available, which results in a request timeout which is not being handled.

### Is this a regression?
Unknown

### Description and Minimal Reproduction
Core Command will crash if a command is sent to Device Camera and the specified device is offline.

## 🔥 Exception or Error
<pre><code>
level=ERROR ts=2021-09-22T15:47:29.891085333Z app=device-camera source=driver.go:190 msg="Post \"http://192.168.0.13:8080/onvif/media_service\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=ERROR ts=2021-09-22T15:47:29.89166021Z app=device-camera source=restrouter.go:158 X-Correlation-ID=ac544edc-f515-4ad9-b54a-b976f2676d93 msg="error reading DeviceResourece OnvifSnapshot for Camera001 -> Post \"http://192.168.0.13:8080/onvif/media_service\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=ERROR ts=2021-09-22T15:47:29.892694167Z app=core-command source=http.go:38 X-Correlation-ID=20b63b7e-0752-44c9-a62c-cfd5c5d31ebe msg="failed to send a http request -> Get \"http://localhost:59985/api/v2/device/name/Camera001/OnvifSnapshot\": EOF"
2021/09/22 11:47:29 http: panic serving 127.0.0.1:38258: invalid WriteHeader code 0
goroutine 1005 [running]:
net/http.(*conn).serve.func1(0xc00047a500)
	/snap/go/7954/src/net/http/server.go:1804 +0x153
panic(0x7db1e0, 0xc00043a6f0)
	/snap/go/7954/src/runtime/panic.go:971 +0x499
net/http.checkWriteHeaderCode(...)
	/snap/go/7954/src/net/http/server.go:1092
net/http.(*response).WriteHeader(0xc00049e540, 0x0)
	/snap/go/7954/src/net/http/server.go:1126 +0x718
github.com/edgexfoundry/edgex-go/internal/pkg/utils.WriteHttpHeader(0x8f3ef0, 0xc00049e540, 0x8f4d80, 0xc0003ef9b0, 0x0)
	/build/edgexfoundry/parts/edgex-go/src/internal/pkg/utils/http.go:31 +0x250
github.com/edgexfoundry/edgex-go/internal/pkg/utils.WriteErrorResponse(0x8f3ef0, 0xc00049e540, 0x8f4d80, 0xc0003ef9b0, 0x8f8648, 0xc000316d80, 0x8f4fb0, 0xc0003acaf0, 0x0, 0x0)
	/build/edgexfoundry/parts/edgex-go/src/internal/pkg/utils/http.go:42 +0x40f
github.com/edgexfoundry/edgex-go/internal/core/command/controller/http.(*CommandController).IssueGetCommandByName(0xc00000efa0, 0x8f3ef0, 0xc00049e540, 0xc000170300)
	/build/edgexfoundry/parts/edgex-go/src/internal/core/command/controller/http/command.go:111 +0x352
net/http.HandlerFunc.ServeHTTP(0xc00043bc30, 0x8f3ef0, 0xc00049e540, 0xc000170300)
	/snap/go/7954/src/net/http/server.go:2049 +0x44
github.com/edgexfoundry/edgex-go/internal/pkg/correlation.LoggingMiddleware.func1.1(0x8f3ef0, 0xc00049e540, 0xc000170300)
	/build/edgexfoundry/parts/edgex-go/src/internal/pkg/correlation/middleware.go:41 +0xb3
net/http.HandlerFunc.ServeHTTP(0xc0003ef8f0, 0x8f3ef0, 0xc00049e540, 0xc000170300)
	/snap/go/7954/src/net/http/server.go:2049 +0x44
github.com/edgexfoundry/edgex-go/internal/pkg/correlation.ManageHeader.func1(0x8f3ef0, 0xc00049e540, 0xc000170200)
	/build/edgexfoundry/parts/edgex-go/src/internal/pkg/correlation/middleware.go:27 +0x2ac
net/http.HandlerFunc.ServeHTTP(0xc000396078, 0x8f3ef0, 0xc00049e540, 0xc000170200)
	/snap/go/7954/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000279bc0, 0x8f3ef0, 0xc00049e540, 0xc00021be00)
	/root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc00049e000, 0x8f3ef0, 0xc00049e540, 0xc00021be00)
	/snap/go/7954/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc00047a500, 0x8f4d80, 0xc000398680)
	/snap/go/7954/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/snap/go/7954/src/net/http/server.go:2993 +0x39b
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
snaps

**EdgeX Version:**
2.0

**Test Instructions**

I tested this as follows:

Connected an SV3C camera.

Created this camera.toml:

```
# Pre-defined Devices
[[DeviceList]]
Name = "Camera001"
ProfileName = "camera"
Description = "siggi"
Location = "home"
  [DeviceList.Protocols]
    [DeviceList.Protocols.HTTP]
    Address = "192.168.1.188:8080"
    # Assign AuthMethod to "digest" | "usernamepassword" | "none"
    # AuthMethod specifies the authentication method used when
    # requesting still images from the URL returned by the ONVIF
    # "GetSnapshotURI" command.  All ONVIF requests will be
    # carried out using digest auth.
    AuthMethod = "usernamepassword"
    CredentialsPath = "credentials001"
# Emit a CBOR-encoded image from this camera, as an EdgeX event, every 30 seconds
[[DeviceList.AutoEvents]]
  Interval = "30s"
  OnChange = false
  SourceName = "OnvifSnapshot"

```

Installed EdgeX and device-camera (built from lastest source) snaps, copied the camera.toml file and started the service:

```
sudo snap remove --purge edgex-device-camera
sudo snap remove --purge edgexfoundry
sudo snap install edgexfoundry --channel=2.0/stable
sudo snap install ./edgex-device-camera_2.0.1-dev.4_amd64.snap --dangerous
sudo snap connect edgexfoundry:edgex-secretstore-token edgex-device-camera:edgex-secretstore-token
sudo cp camera.toml /var/snap/edgex-device-camera/current/config/device-camera/res/devices/
sudo snap start edgex-device-camera.device-camera
```

Ran this script to update the username/password secrets:

```
#!/bin/sh

curl -w %{http_code} -X POST \
-d '{
  "apiVersion": "2",
  "path" : "credentials001",
  "secretData" : [
    {
      "key" : "username",
      "value" : "admin"
    },
	{
      "key" : "password",
      "value" : "admin"
    }
  ]
}' http://localhost:59985/api/v2/secret
```

Make sure the camera is offline, and then send a command to it via Core Command:

`curl -w %{http_code} http://localhost:59882/api/v2/device/name/Camera001/OnvifSnapshot
`

**Comment by judehung** [comment]
@tonyespy Are you able to reproduce this issue using the latest code base of edgex-go?  After checking the [source codes](https://github.com/edgexfoundry/edgex-go/blob/main/internal/pkg/utils/http.go#L31-L39), I think this issue should have been fixed by https://github.com/edgexfoundry/edgex-go/pull/3662.  

Your error logs below were actually arouse from an old version of code base:
```
github.com/edgexfoundry/edgex-go/internal/pkg/utils.WriteHttpHeader(0x8f3ef0, 0xc00049e540, 0x8f4d80, 0xc0003ef9b0, 0x0)
	/build/edgexfoundry/parts/edgex-go/src/internal/pkg/utils/http.go:31 +0x250
github.com/edgexfoundry/edgex-go/internal/pkg/utils.WriteErrorResponse(0x8f3ef0, 0xc00049e540, 0x8f4d80, 0xc0003ef9b0, 0x8f8648, 0xc000316d80, 0x8f4fb0, 0xc0003acaf0, 0x0, 0x0)
	/build/edgexfoundry/parts/edgex-go/src/internal/pkg/utils/http.go:42 +0x40f
```

**Comment by tonyespy** [comment]
@judehung I reproduced this using the Ireland edgexfoundry snap (e.g. 2.0.0-2). I haven't had a chance to try this with the latest development release, but will check.

**Comment by tonyespy** [comment]
OK, I've re-tested with the edgexfoundry snap rebuild from HEAD and I can no longer reproduce the crash in core-command.

@JamesKButcher this scenario would be great for a TAF functional test (i.e. try to send a device command using core-command with a knowingly unreachable device).

**Comment by cloudxxx8** [comment]
@tonyespy thanks for the verification.  the TAF issue has been opened for this
https://github.com/edgexfoundry/edgex-taf/issues/528
