### ISSUE TITLE
support-logging API do not work

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#373]
Below GET and DELETE API do not work
  * /api/v1/logs/originServices/{{loggingService}}/{{start}}/{{end}}/{{limit}}
  * /api/v1/logs/logLevels/{{loggingLevel}}/{{start}}/{{end}}/{{limit}}
  * /api/v1/logs/logLevels/{{loggingLevel}}/originServices/{{loggingService}}/{{start}}/{{end}}/{{limit}}
  * /api/v1/logs/logLevels/{{loggingLevel}}/originServices/{{loggingService}}/labels/{{loggingLabel}}/{{start}}/{{end}}/{{limit}}
  * /api/v1/logs/logLevels/{{loggingLevel}}/originServices/{{loggingService}}/labels/{{loggingLabel}}/keywords/{{loggingKeyword}}/{{start}}/{{end}}/{{limit}}  

GET API always return empty result `[]` , DELETE API do not delete logEntry .

**Comment by weichou1229** [comment]
I think query criteria doesn't match logEntry domain at 
https://github.com/edgexfoundry/edgex-go/blob/master/support/logging/mongo.go#L65
```
// criteria
conditions = createConditions(conditions, "originservice", criteria.OriginServices)
conditions = createConditions(conditions, "level", criteria.LogLevels)

// domain
{
  "_id" : ObjectId("5b41d3f124aa9a0006ec9d1e"), 
  "logLevel" : "WARN", 
  "labels" : [ "label1", "label2" ], 
  "originService" : "service1", 
  "message" : "Hello, Logging Service!", 
  "created" : NumberLong("1531040753529") 
}
```

**Comment by tsconn23** [comment]
See my email

**Comment by cloudxxx8** [comment]
the URL of the logging service mongo.go is changed:
https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/logging/mongo.go#L65

**Comment by tsconn23** [comment]
Fixed with above PR merge
