### ISSUE TITLE
support-logging API do not check record limit

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#374]
According to RAML  https://github.com/edgexfoundry/edgex-go/blob/master/support/logging/raml/support-logging.raml#L71 , /api/v1/logs/{{limit}} should check record limit .

eg. the default limit is 100. When the {{limit}} path parameter is 101 and there are more than 101 records in db, the service should return http status 413
However, the current implementation returns 200 ok for this case

**Comment by tsconn23** [comment]
Cannot duplicate this issue outside of a test run. Populate the Mongo DB from the logEntryDb.Json file provided in the PR below and then call the endpoint by itself, not as part of a test, and it will work.

https://github.com/edgexfoundry/blackbox-testing/pull/35

**Comment by cloudxxx8** [comment]
Recreate steps of this issue:

1. start up support-logging service
2. add log entry more than 100 records
3. query log by the API  /api/v1/logs/{{limit}}, and assign a value more than 100 to {{limit}}, such as  /api/v1/logs/101
4. see the http status code in the response header

Actual Result:
HTTP Status Code 200 OK

Expected Result:
HTTP Status Code 413 Payload Too Large

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/edgex-go/pull/617
@weichou1229 please close this issue

**Comment by jduranf** [comment]
Done via #617
