### ISSUE TITLE
not able to delete device's autoevent when no empty part

### ISSUE THREAD

**Issue by edgego** [edgexfoundry/edgex-go#3750]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
when update request not mention auto event part  not able to update auto event.

no auto event part request:
[{  "apiVersion": "v2","device": { "name":"d1","description":"Example generic data type device","operatingState":"UP","adminState":"UNLOCKED","serviceName":"device-coap","profileName":"example-datatype","location":"22.19980258118404,113.09430565426588","id":"edf99b1c-f585-41d9-9da8-49c4acff50fc","labels":["coap","rest" ],"protocols": {"other": { "Address" : "" , "Port" : "" }}}}]

get response :
[{"apiVersion":"v2","statusCode":200}]

But tried to get device name d1, auto event still exists

empty auto event part request:

[{  "apiVersion": "v2","device": { "name":"d1","description":"Example generic data type device","operatingState":"UP","adminState":"UNLOCKED","serviceName":"device-coap","profileName":"example-datatype","location":"22.19980258118404,113.09430565426588","id":"edf99b1c-f585-41d9-9da8-49c4acff50fc","labels":["coap","rest" ],_**"autoEvents":[]**_,"protocols": {"other": { "Address" : "" , "Port" : "" }}}}]

get response :
[{"apiVersion":"v2","statusCode":200}]

tried to get device d1 again, auto event were deleted, this is normal.

### Is this a regression?
no, previous version no this issue.

 Yes, the previous version in which this bug was not present was:  1.3.1

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
Ireland 2.0.0

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@edgego this is as design
The update API between v1 and v2 is different.  v1 is using http PUT method, and it should contain all the fields to make a whole update. v2 is using http PATCH method, which means you can only put the part you want to update in the payload.  
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH

For example,  you can use the following payload to update `adminSate` only by the PATCH API
`[{ "apiVersion": "v2","device": { "name":"d1","adminState":"LOCKED"}}]`

In this case, if you miss the AutoEvents field in the PATCH call, the service will ignore it.
Put an empty array is to way to go, if you want to remove AutoEvents.
