### ISSUE TITLE
This branch is out-of-date with the base branch

### ISSUE THREAD

**Issue by farshidtz** [edgexfoundry/edgex-go#3777]
Hi all,

Currently, the PRs get blocked as soon as a branch gets out of date. This is really counter-productive especially in a repository as busy as this.

Note that this is a Github feature enabled in the repository settings and has nothing to do with Git merging and conflict resolution. This check "ensures pull requests targeting a matching branch have been tested with the latest code". See also: https://stackoverflow.com/questions/67332877/how-to-setup-this-branch-is-out-of-date-with-the-base-branch-in-github-repo

The purpose is make sure changes merged from other PRs are considered inside pending PRs. But how often to we actually go back and repeat those test, especially if they involve manual steps? Are there maybe better ways to automatically test independent changes as part of the CI process?

It is very often the case that changes across PRs have nothing to do with each other and this process only hinders the contributors. One could be a port change in the snapcraft file, while another is a feature addition in the code, or a typo fix in README.

**Comment by tonyespy** [comment]
Just curious if we enable this, wouldn't one of the end results be a plethora of "merge master into <feature branch>" commits?

**Comment by farshidtz** [comment]
@tonyespy:
> Just curious if we enable this, wouldn't one of the end results be a plethora of "merge master into " commits?

If you are referring to the checkbox highlighted by Ernesto, it is already enabled in this repo. That's why we need to rebase or merge master into our branches (e.g. [1](https://github.com/edgexfoundry/edgex-go/pull/3788), [2](https://github.com/edgexfoundry/edgex-go/pull/3772)) as soon as they go out of date (the topic of this issue).

**Comment by ernestojeda** [comment]
@farshidtz Correct. I believe it's checked for all EdgeX repos.

**Comment by JamesKButcher** [comment]
Will discuss during the architects meeting Dec 20th

**Comment by jpwhitemn** [comment]
Added to Monthly architect's meeting for December

**Comment by jpwhitemn** [comment]
Per Monthly Architect's meeting: Make the change on edgex-docs (require branch to be up to date check box).  For edgex-go, ask devops to give us indications of what the impact would be to CI pipelines (what happens if a build failure occurs with this new workflow; can they put a verify job in place?).  Allow the TSC to make a decision after getting the readout from Devops.
@ernestojeda - please reach out to @farshidtz @tonyespy @bnevis-i

**Comment by farshidtz** [comment]
> can they put a verify job in place?

To elaborate: the suggestion in the meeting was to replace the enforced branch update on the user-side (and git history) with the same operation done as part of the **current** CI tests. As a result, the CI workflow would first merge main into the PR's branch (in its local copy) and then perform the tests as usual and raise any possible failures.

This is to make sure that in the absence of enforced branch updates, relevant changes added by independent branches still get tested together before merging a PR.

**Comment by bnevis-i** [comment]
Right.  The enforced branch update adds 30 minutes to merge every approved PR, during which time another PR that is up-to-date can be committed, resulting in anther 30 minute round-trip.  Not only that, but the commit log gets cluttered with "merge from master" commits.  Give the loosly-coupled nature of edgex, it is rare that a behavior change in one component will be incompatible with another behavior change made in another component to justify the additional round trips.

**Comment by lenny-intel** [comment]
@bnevis-i , We should be using `Squash and Merge` to avoid the cluttered commits.

**Comment by iain-anderson** [comment]
Instead, in GitHub do "Fetch upstream" on the main branch of your fork, then on your branch
```
git fetch
git rebase -S origin/main
git push --force
```

**Comment by ernestojeda** [comment]
As of today `Jan 13, 2022`, the branch protection rules have been modified for the following repositories:
* edgex-go
* edgex-docs

**Comment by JamesKButcher** [comment]
We discussed this at length on the Core Working Group call (27th Jan) - recording available at https://wiki.edgexfoundry.org/display/FA/Core+Working+Group

Conclusion is that this is likely to be a rare occurrence and we need to be aware of it, but it is considered an acceptable risk right now. Our DevOps pipeline process will catch errors & test fails and we'll need to fix those if/when it happens. Let's monitor to see if and how frequently this occurs, but closing this ticket for now.
