### ISSUE TITLE
when system have many same device, how to define the device profile? Does every device have to define one profile?

### ISSUE THREAD

**Issue by zhui19871** [edgexfoundry/edgex-go#3792]
# 🚀 Feature Request

### Relevant Package

 This feature request is for...

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by zhui19871** [comment]
when create one device profile and multiple devices associated to it, how to send command to exactly one device?

**Comment by cloudxxx8** [comment]
In the Core Command API, the URL contains the Device name

**Comment by zhui19871** [comment]
but the device name associated multiple real device? how?

**Comment by zhui19871** [comment]
so whether or not support custome properties pass to request? like get command tag.

**Comment by cloudxxx8** [comment]
I don't understand your question.  Please describe your context and scenario more.

**Comment by zhui19871** [comment]
my device is system with many same devices and many systems, i donot want to create device profile for each device, because is same, but when i send control command to device need system address and device address, so i want the command request have customer properties pass to server, the customer parameters like device system address and system device address, then i just create one device profile for system same device.

**Comment by cloudxxx8** [comment]
if you develop your own device service based on device sdk, the URL query parameter can be passed to the Device Service.
the Attribute name is `urlRawQuery`
You can only use only one Device Profile for all Device instance exactly

**Comment by zhui19871** [comment]
ok, get. thanks.
