### ISSUE TITLE
Clean up repo README

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#3795]
# 📚 Docs or Wiki Bug Report

Repository README.md has broken and/or stale links:
- stale ref (1.3) for Walkthrough and 2.0 vs 2.1 docs
- Refs to code with master vs main branch
- broken link on LTS Policy

 A clear and concise description of the problem...

### What's the affected URL?**
 https://docs.edgexfoundry.org/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by JamesKButcher** [comment]
Needs done before Jakarta tagging
