### ISSUE TITLE
Add Redis as lightweight alternative to MongoDB in Core Data

### ISSUE THREAD

**Issue by andresrinivasan** [edgexfoundry/edgex-go#380]
Given the requirements for a fast small footprint database for Core Data, Redis OSS looks to be a good alternative to MongoDB. We will add Redis as an option.

**Comment by jduranf** [comment]
@andresrinivasan I guess you already know it, but @itamarhaber is already working in this implementation. Also should be fine to add Redis in this comparative #291

**Comment by andresrinivasan** [comment]
Ok. I thought we needed a separate issue. I'll close this one and we'll use #291 as you suggest.

**Comment by jduranf** [comment]
@andresrinivasan I think you misunderstood me, I think it's fine to have this issue, but I wasn't sure that you already know that @itamarhaber is working in the same issue, and I just wanted to avoid to have two different people working in the same issue.

**Comment by andresrinivasan** [comment]
Re-opening in preparation for @itamarhaber's PR.

**Comment by andresrinivasan** [comment]
Merged and resolved.
