### ISSUE TITLE
Including identity and access management in edgex system

### ISSUE THREAD

**Issue by charithmadhuranga** [edgexfoundry/edgex-go#3845]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

Vault,consul and Kong gateway
 This feature request is for separate micro service which will handle all identity and access management for edgex system.which will give api endpoints to developers to access the features it provide.

### Description [**REQUIRED**]
 

it will be nice to have a proper identity and access management inside edgex micro services or support for opensource solutions

### Describe the solution you'd like
 

Use opensource solutions like keycloak or hashicorp boundary which will enhanced the user experience and give developers options to work with user management.

### Describe experimented solution.

I have experimented with harshicorp boundary and keycloak which gives me satisfied result.I think it is necessary for an industrial software to have proper Iam solution in its core tool set.

**Comment by bnevis-i** [comment]
@charithmadhuranga Would you be available to present your request at the EdgeX Security working group?

**Comment by bnevis-i** [comment]
See also https://github.com/edgexfoundry/edgex-ui-go/issues/485

**Comment by bnevis-i** [comment]
@charithmadhuranga 

With EdgeX 3.0, we are leveraging Vault-based identity to authenticate proxy users and EdgeX microservices with each other.  This leverages additional identity management capability that we are using for the EdgeX secret store and does not require introducing a large Java-based dependency (such as Keycloak, mentioned above) into every EdgeX installation.

This is documented in

- https://docs.edgexfoundry.org/3.0/security/Ch-Authenticating/
- https://docs.edgexfoundry.org/3.0/design/adr/security/0028-authentication/

Moreover, by leveraging [Vault pluggable auth methods](https://developer.hashicorp.com/vault/docs/auth),
it should be possible to hook up external identity stores to authenticate users.
Thus, if you wish to integrate an OIDC provider such as Keycloak or Dex, where shouldn't be anything stopping you from doing so.

Does this meet  your requirement?

**Comment by charithmadhuranga** [comment]
Hi @bnevis-i  thank for the clear explaination.yes it satisfied the requirement I am looking for.
