### ISSUE TITLE
sending data using HTTPS to northbound devices

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#386]
Moved issue to correct repo on behalf of user @Ajit-T.
Original issue is here -- https://github.com/edgexfoundry/export-distro/issues/43

I am using export services to send my data to northbound end points, HTTP works correctly, but for HTTPS, the log says "x509: failed to load system roots and no roots provided", has anyone ran into this earlier?.......I believe this is something to do with the export-distro docker container, as from my machine I can send HTTPS data using other applications and have ca certificates in place.

I am using Version 0.6.0 California; have same result on Version 0.5.1 California Preview.

Below are the logs from export-distro logging service, the error is highlighted in BOLD

edgex-export-distro | {"level":"info","ts":1531114841.1933942,"caller":"distro/registrations.go:285","msg":"EVENT"}
edgex-export-distro | {"level":"info","ts":1531114841.2013,"caller":"distro/zeromq.go:44","msg":"Event received","event":"{"id":"5b42f5590e360800011729a1","pushed":0,"device":"GS1-AC-Drive01","created":1531114841199,"modified":0,"origin":1531114841157,"schedule":null,"event":null,"readings":[{"id":"5b42f5590e360800011729a2","pushed":0,"created":1531114841199,"origin":1531114841157,"modified":0,"device":"GS1-AC-Drive01","name":"HoldingRegister_8455","value":"173.22"}]}"}
edgex-export-distro | {"level":"info","ts":1531114841.2191534,"caller":"distro/zeromq.go:44","msg":"Event received","event":"{"id":"5b42f5590e360800011729a3","pushed":0,"device":"GS1-AC-Drive01","created":1531114841217,"modified":0,"origin":1531114841183,"schedule":null,"event":null,"readings":[{"id":"5b42f5590e360800011729a4","pushed":0,"created":1531114841217,"origin":1531114841183,"modified":0,"device":"GS1-AC-Drive01","name":"HoldingRegister_2331","value":"true"}]}"}
edgex-export-distro | {"level":"error","ts":1531114841.42404,"caller":"distro/http.go:42","msg":"Error: ","error":"Post https://httpdump.io:443/nzsjs: x509: failed to load system roots and no roots provided","stacktrace":"github.com/edgexfoundry/edgex-go/export/distro.httpSender.Send\n\t/go/src/github.com/edgexfoundry/edgex-go/export/distro/http.go:42\ngithub.com/edgexfoundry/edgex-go/export/distro.(*httpSender).Send\n\t:1\ngithub.com/edgexfoundry/edgex-go/export/distro.registrationInfo.processEvent\n\t/go/src/github.com/edgexfoundry/edgex-go/export/distro/registrations.go:155\ngithub.com/edgexfoundry/edgex-go/export/distro.registrationLoop\n\t/go/src/github.com/edgexfoundry/edgex-go/export/distro/registrations.go:167"}

**Comment by tsconn23** [comment]
Most likely certificates need to be added to Docker file from Alpine package manager

**Comment by Ajit-T** [comment]
@tsconn23 , thanks for your help, I added the certificates from Alpine package manager and got the data going to northbound devices using https.

**Comment by magallardo** [comment]
@Ajit-T Could you share the steps required to add the certificates to the export-distro image?  Did you rebuild the docker image? I am running into the same issue. Thanks
