### ISSUE TITLE
"redisdb" secret incorrectly states username for redis is "redis5"

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#3860]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
security-secretstore-setup (directly), everyone else (indirectly)

### Is this a regression?
No

### Description and Minimal Reproduction [**REQUIRED**]
In security-enabled EdgeX, when we create the secret store secret for Redis, we create a hash

username: redis5
password: (random-long-base64-string)

One would presume that in order to authenticate to Redis, one could pass

```
AUTH redis5 (random-login-base64-string)
```

But that in fact is not the case.  Rather, the correct syntax is either:

```
AUTH (random-login-base64-string)
```
or
```
AUTH default (random-login-base64-string)
```

This may have something to do with Redigo's splitting `DialUsername` out from `DialPassword`
<https://github.com/gomodule/redigo/blob/master/redis/conn.go>
as code, when we upgraded from Redis4 to Redis5, did not add redis username support.

The current situation is misleading to anyone accessing the EdgeX secretstore to get the redisdb credential.

## 🌍  Your Environment
**Deployment Environment:**  Linux
**EdgeX Version [**REQUIRED**]:** main
**Anything else relevant?**

**Comment by bnevis-i** [comment]
Proposed fix is to seed the secretstore with username "default" to match reality.

**Comment by JamesKButcher** [comment]
Marking a tech debt rather than bug and moving to icebox
