### ISSUE TITLE
Core Command GET/PUT /device/name/{name}/{command} returns 500

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#3884]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: core-command

### Description and Minimal Reproduction [**REQUIRED**]
1. Run services using [docker-compose-no-secty.yml](https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose-no-secty.yml) from edgex-compose main branch

2. `curl http://localhost:59882/api/v2/device/name/Random-Binary-Device/Binary`

## 🔥 Exception or Error
<pre>

<code>
{"apiVersion":"v2","message":"nil DeviceServiceCommandClient returned","statusCode":500}

</code></pre>
core-command log:
```
level=ERROR ts=2022-02-17T09:45:22.3464903Z app=core-command source=http.go:47 X-Correlation-ID=b3b2a6f1-16e9-4d76-ad25-553a69038aef msg="nil DeviceServiceCommandClient returned"
```

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
main branch

**Anything else relevant?**
This causes TAF tests fail

**Comment by JamesKButcher** [comment]
@lenny-intel please investigate

**Comment by lenny-intel** [comment]
I mistakenly removed  the creation of DeviceServiceCommandClient which is not one of the common clients
