### ISSUE TITLE
does edgex support riscv?

### ISSUE THREAD

**Issue by alongL** [edgexfoundry/edgex-go#3887]
Now riscv is very popular, does edgex support riscv?
Or will support in the future?

**Comment by bnevis-i** [comment]
I refer to you to https://www.eejournal.com/industry_news/iotech-announces-support-for-its-edge-software-on-intel-pathfinder-for-risc-v/

**Comment by farshidtz** [comment]
EdgeX does not currently provide RISC-V artifacts.

I have not tested this, but you should be able to build services written in Go after disabling C dependencies such as zeromq and setting GOARCH to `riscv64` for the Go compiler.
