### ISSUE TITLE
Call validation API before calling back to device service

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/edgex-go#3894]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

This feature request is for **Metadata**

### Description [**REQUIRED**]
device-sdk had implemented `/api/v2/validate/device` API. (https://github.com/edgexfoundry/device-sdk-go/issues/649). 
Metadata needs to trigger this API before calling back to device service for device changes.

### Describe the solution you'd like
Before calling back, call the new device service validation API to validate the device.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by hahattan** [comment]
@lenny-intel are we allowed to create device belongs to a non-exist device-service?
it seems the following test would fail because of this change:
https://github.com/edgexfoundry/edgex-taf/blob/5d08e5869bd0fc16a8a9c08b7197e0a68f4bdbf5/TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Positive.robot#L15

**Comment by cloudxxx8** [comment]
no, we don't allow it.  we have this check in core-metadata.
https://github.com/edgexfoundry/edgex-go/blob/556446716e4a14b8c762f3ec0116a54927b3d800/internal/core/metadata/application/device.go#L31-L36

**Comment by cloudxxx8** [comment]
oh, I just realize what is happening.
the device creation is blocked if the device service is not really running.  we should find a way to allow it.

**Comment by cloudxxx8** [comment]
on the other hand, if the device service is not running, there is no chance to validate the device creation from Device Service.
@lenny-intel @iain-anderson may I have your advise?

**Comment by lenny-intel** [comment]
@cloudxxx8 . @iain-anderson , For this release, if device service isn't running, then can't validate and allow device add/update since failing would be a breaking change. For 3.0 we need to consider failing the validation if the device service is not running.

**Comment by cloudxxx8** [comment]
ok, issue https://github.com/edgexfoundry/edgex-go/issues/3909 opened for this.
