### ISSUE TITLE
core-metadata  v2   /device/name/Camera001 with trailing slash got 404

### ISSUE THREAD

**Issue by wubigo** [edgexfoundry/edgex-go#3899]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 

core-metadata

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

http://localhost:59882/api/v2/device/name/Camera001/

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

docker desktop
**EdgeX Version [**REQUIRED**]:**

jakarta

**Anything else relevant?**

http://localhost:59882/api/v2/device/name/Camera001 + /   report 404 , 
http://localhost:59882/api/v2/device/name/Camera001 works

**Comment by cloudxxx8** [comment]
this behavior meets the API design

**Comment by farshidtz** [comment]
This is indeed following the API specs; see https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-command/2.2.0

As discussed in the core call; this is NOT a regression and is consistent across other native components and also via the proxy:
```bash
$ curl http://localhost:59880/api/v2/event/device/name/Random-Integer-Device
{"apiVersion":"v2","statusCode":200,"totalCount":0,"events":[]}
$ curl http://localhost:59880/api/v2/event/device/name/Random-Integer-Device/
404 page not found
#
# proxy:
$ curl --insecure -H 'Authorization: Bearer '$JWT https://localhost:8443/core-data/api/v2/event/device/name/Random-Integer-Device
{"apiVersion":"v2","statusCode":200,"totalCount":0,"events":[]}
$ curl --insecure -H 'Authorization: Bearer '$JWT https://localhost:8443/core-data/api/v2/event/device/name/Random-Integer-Device/
404 page not found
```

If needed, this can be changed by either:
1. Add additional proxy routes with forward slash
2. Change proxy paths to be regex with optional trailing forward slash
3. Enabling strict slash on the router (see https://pkg.go.dev/github.com/gorilla/mux#Router.StrictSlash). However, the redirection will not work as expected behind the proxy if the router is unaware of the context paths.

**Comment by JamesKButcher** [comment]
Closing ticket. Thanks for the analysis @farshidtz
