### ISSUE TITLE
Can't use "docker exec -it xx /bin/sh" command go into some container ,like cmd,metadata etc. 

### ISSUE THREAD

**Issue by badboy-huaqiao** [edgexfoundry/edgex-go#392]

**Comment by drasko** [comment]
These are `FROM scratch` containers and do not have shell inside.

Please do not open issues before:
- Doing yourself an investigation (for example reading yourself Dockerfiles)
- Asking on mailing lists
- Asking on IRC

Issues are used primarily for tracking bugs and tasks, not for asking questions.
