### ISSUE TITLE
Implement new Device Profile API

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/edgex-go#3925]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for Metadata

### Description [**REQUIRED**]. 

According to https://docs.edgexfoundry.org/2.2/design/adr/core/0021-Device-Profile-Changes/
The following API would be added to metadata:
- PATCH device profile basic info
- POST device resource
- PATCH device resource (description and isHidden only)
- DELETE device resource
- POST device command
- PATCH device command
- DELETE device command

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by jinlinGuan** [comment]
All APIs are implemented. Close this issue.

**Comment by jinlinGuan** [comment]
Implemented by 
https://github.com/edgexfoundry/edgex-go/pull/3926
https://github.com/edgexfoundry/edgex-go/pull/3930
https://github.com/edgexfoundry/edgex-go/pull/3936
https://github.com/edgexfoundry/edgex-go/pull/3937
https://github.com/edgexfoundry/edgex-go/pull/3950
https://github.com/edgexfoundry/edgex-go/pull/3962
