### ISSUE TITLE
Use formatted alternative log function instead of fmt.Sprintf

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3932]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for all services

### Description [**REQUIRED**]
We implemented the formatted alternative log function in
https://github.com/edgexfoundry/go-mod-core-contracts/issues/295
We should replace all the fmt.Sprintf in the logger with these functions.

**Comment by lenny-intel** [comment]
You mean the fmt.Sprintf calls, correct?

**Comment by cloudxxx8** [comment]
correct, I modified the subject and description.  thanks for the reminder
