### ISSUE TITLE
remove default github templates

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#3953]
new organizational templates in place at .github.  Can remove the ISSUE_TEMPLATE and PR_TEMPLATE overrides so that the repository stays consistent with default.

**Comment by farshidtz** [comment]
For reference:
- .github repo: https://github.com/edgexfoundry/.github/tree/main/.github
- documentation: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types
