### ISSUE TITLE
Error occurs sometimes "couldn't create database client" when repeating to restart services

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4005]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: any of core services or support services

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Jakarta

### Description and Minimal Reproduction [**REQUIRED**]
1. Clone edgex-taf repository
2. Go to ${taf-root-folder}/TAF/utils/scripts/docker 
3. Execute command with arch parameter `sh get-compose-file-perfermance.sh arm64` to get compose file
4. Execute command `docker-compose up`, then `docker-compose stop` to create containers and stop them without removing
5. Execute command `docker-compose start`, verify all services are started
6. Execute command `docker-compose stop`
7. Repeat step5 and step6 several times.

## 🔥 Exception or Error
<pre><code>

"couldn't retrieve database credentials: Error, path () doesn't exist in secret store"
or
"couldn't create database client: redis client creation failed -> could not dial Redis: dial tcp 172.23.0.2:0: connect: connection refused"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
I cannot recreate on my local environment. The error happens on Jenkins production.
arm64- ubuntu
x86-centos

**EdgeX Version [**REQUIRED**]:**main

**Anything else relevant?**
The error doesn't always occur and it happens on arm64 more often than x86.
[Performance_20Metrics_20Detail_20Reports-11.zip](https://github.com/edgexfoundry/edgex-go/files/8617653/Performance_20Metrics_20Detail_20Reports-11.zip)
[Performance_20Metrics_20Detail_20Reports-10.zip](https://github.com/edgexfoundry/edgex-go/files/8617654/Performance_20Metrics_20Detail_20Reports-10.zip)

**Comment by cherrycl** [comment]
This issue only happens when restarting services without security enabled.

**Comment by cloudxxx8** [comment]
it should not need database credentials when it runs without security enabled

**Comment by cherrycl** [comment]
Hit this issue often when deploy backward compose file. Use the attached compose file.
[backward-compose.zip](https://github.com/edgexfoundry/edgex-go/files/9460010/backward-compose.zip)

**Comment by lenny-intel** [comment]
Switching from Secure Mode to Non-secure mode without clearing volumes is not supported. Once secured, Redis will always require credentials when it restarts unless its volume is cleaned/removed.

**Comment by cherrycl** [comment]
Backward compatibility test doesn't test on secure mode.

**Comment by lenny-intel** [comment]
The error `"couldn't retrieve database credentials: Error, path () doesn't exist in secret store"`  could be from non-secure SecretProvider looking for the creds in the InsecureSecrets which should look like this:
```
   [Writable.InsecureSecrets]
      [Writable.InsecureSecrets.DB]
         path = "redisdb"
            [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""
```
But this should be in the older config...

**Comment by lenny-intel** [comment]
What does the Redis logs look like?

**Comment by cherrycl** [comment]
Attached the Redis log when the error occurred.
[redis.log](https://github.com/edgexfoundry/edgex-go/files/9504972/redis.log)
Not sure consul have `http://localhost:8500/ui/dc1/kv/edgex/core/2.0/core-metadata/Writable/InsecureSecrets/DB/Path` set to `redisdb` or not when the error occurred, we use the default configuration file and didn't change the value. The error only found on Jenkins job so far.

**Comment by lenny-intel** [comment]
Both Support Notifications and Core Data are finding Consul
- `Configuration has been pulled from Configuration provider `

Support Notifications seems to be a timing issue as it simply can not find Redis.
- I wonder if we have issue with docker IP assignments. i.e. notifications looking for Redis at `172.20.0.4:0` but it is now at a different IP?

Core Data can't find `Writable/InsecureSecrets/DB/Path` in config loaded from Consul.
- Can you add a dump of Core Data's /api/v2/config endpoint to verify what is in Core Data's InsecureSecrets?

**Comment by cherrycl** [comment]
I got the error on core-metadata this time. When the error occurred, the service was not started, can't get core-metadata config by endpoint `/api/v2/config`.

**Comment by lenny-intel** [comment]
@cherrycl , is this only occurring on ARM64 and for the backward compatibility testing?
I noticed you are using the TAF Performance compose file. Is that what is used for the backward compatibility testing?
When this occurs like above with core-metadata, we need to see the logs. 
Also, try removing the restart: always from the service in the compose file. This will allow you to see a clean on start-up log file.

**Comment by cherrycl** [comment]
@lenny-intel This is not only found on ARM64 and backward compatibility testing. We found this error on performance test at first, and it just happened occasionally. For the backward compatibility testing, we run 4 cases with 2 platform on a Jenkins job, this error occurred once at lease and not only on ARM64, also x86_64.

**Comment by cherrycl** [comment]
Remove the restart:always from compose file for all core-services and support services. This time I got error on core-data, please see the attached.
[core-data-0921.log](https://github.com/edgexfoundry/edgex-go/files/9615557/core-data-0921.log)
[redis-0921.log](https://github.com/edgexfoundry/edgex-go/files/9615558/redis-0921.log)

**Comment by lenny-intel** [comment]
From the Core Data logs it is pulling the configuration from Consul
`Configuration has been pulled from Configuration provider (5 envVars overrides applied)"`
Then gets error
`couldn't retrieve database credentials: Error, path () doesn't exist in secret store"`

The code line that generates this error is:
`err := fmt.Errorf("Error, path (%v) doesn't exist in secret store", path)`

So for some reason `path` is not set when is should be `redisdb`

So I suspect the configuration pulled from Consul doesn't have the Database configuration set properly like below from toml file
```toml
[Databases]
  [Databases.Primary]
  Host = "localhost"
  Name = "coredata"
  Port = 6379
  Timeout = 5000
  Type = "redisdb"
```

**Comment by cloudxxx8** [comment]
@cherrycl is this resolved after you mofity the test script?

**Comment by cherrycl** [comment]
I wrote a shell script to recreate this issue on local. See attachment. The issue may happened after several runs.
I ran this script on my 2 environment, one is x86_64, the other one is arm64. The x86_64 machine happened 2-3 times after 10 runs, but arm64 only occurred ones after 20 runs. 
[performance-issue.sh.zip](https://github.com/edgexfoundry/edgex-go/files/10257478/performance-issue.sh.zip)

run script by `docker compose` command: `sh performance-issue.sh`
run script by `docker-compose` command: `sh performance-issue.sh v1`

**Comment by cloudxxx8** [comment]
@cherrycl if we use `up` and `down` instead of `start` and `stop`, can this issue be workaround?

**Comment by cherrycl** [comment]
Use `up` and `down` doesn't cause the error for now, we have a test for it. For `start` and `stop`, we use it to test starting service without creating container.

**Comment by cloudxxx8** [comment]
@cherrycl do we still have this issue?

**Comment by cherrycl** [comment]
This issue didn't occur during Minnesota release. Close it.
