### ISSUE TITLE
Build optimization for locally-built go containers

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#4025]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
All packages in edgex-go

### Description [**REQUIRED**]
In the current method of operation, when building docker images,
each microservice in edgex-go is carried out in its own build container.
Unfortunately, this results in dependencies being fetched over and over again for each microservice being built,
which greatly lengthens the build time.

### Describe the solution you'd like
I have seen a technique used in other projects to speed up build times by caching the go module cache.
The process is:

- Create a `.go` folder at the root of the project that is excluded from git.
- When launching the build container, set the `GOCACHE` variable to an appropriate value
- When launching the build container, map `.go/cache` the the location specified by `GOCACHE` above.

### Describe alternatives you've considered
Building all the edgex-go binaries into a single docker image.

**Comment by bnevis-i** [comment]
@ernestojeda Do you agree we can close this now?

**Comment by ernestojeda** [comment]
Yes. Let's close this.

**Comment by bnevis-i** [comment]
Closed by #4113
