### ISSUE TITLE
Upgrade to Redis 7

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#4027]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
Core Data 

### Description [**REQUIRED**]
Need to stay up on latest version on Redis

### Describe the solution you'd like
Use Redis 7.x, but we get the following error (secure mode) when subscribing to MessageBus that doesn't occur with Redis 6.2.x
```
level=ERROR ts=2022-05-17T23:48:01.4893991Z app=core-data source=subscriber.go:61 msg="NOPERM this user has no permissions to access one of the channels used as arguments"
```

Same error in Device Virtual when publishing and App Service when subscribing.

No issues in non-secure mode.

### Describe alternatives you've considered
Stay on Redis 6.2.x

**Comment by lenny-intel** [comment]
@bnevis-i , FYI

**Comment by drkfmorton** [comment]
![image](https://user-images.githubusercontent.com/9958330/182867973-7da6ebeb-bd0b-4efe-8786-885234b0d56c.png)
![image](https://user-images.githubusercontent.com/9958330/182868163-eff9bf1d-9843-4de3-a00c-491403836b1c.png)

**Comment by drkfmorton** [comment]
The permission set created for the default user is missed access to all Pub/Sub channels
