### ISSUE TITLE
Documentation not building

### ISSUE THREAD

**Issue by SteveOss** [edgexfoundry/edgex-go#403]
Documentation build system needs updating to reflect new locations of raml files and generally requires a clean up.

**Comment by brandonforster** [comment]
Jumping on to this issue, I noticed two problems in `Ch-ExamplesAPIDemo.rst`:

First, when constructing a new device profile, it references a YAML file to upload that doesn't seem to exist.

Second, when registering a new client for the Rules Engine, the provided JSON is malformed. The `encryption` key that describes the object is missing its semicolon.

**Comment by tsconn23** [comment]
@SteveOss I'm assuming this can be closed?
