### ISSUE TITLE
device-uart: UART data not received to the device-uart microservice without polling the device and received data (with polling) is not sent to the core-data

### ISSUE THREAD

**Issue by vediyappan-villali** [edgexfoundry/edgex-go#4033]
**Affected Services:**
EdgeX device-uart microservice

**Description:**
I am sending data from PC (using Docklight application) to the EdgeX device-uart microservice which is running on Raspberry Pi installed with Ubuntu-Desktop 22.04 LTS. After analysis and testing, I came to know that, the data from PC is not received to device-uart service without polling first time. I need to two things: 1. The uart device-service should get the data from the UART device (PC) without polling, 2. The data received in UART device-service must be sent to core-data.

**Environment:**
Hardware: Raspberry Pi 4
OS: Ubuntu-Desktop 22.04 LTS for Raspberry Pi 4
EdgeX Version: Latest

**Reproduction Steps:**
    1. Run EdgeX (microservices such as core-data, core-command, meta-data),
    2. Run EdgeX device-uart microservice,
    3. Send serial data from PC (through Docklight) application --- Observe transmitted data is not received in device-uart microservice logs,
    4. Poll the device from device-uart microservice --- Observe data is received in device-uart microservice,
    5. Check logs of core-data microservice --- Observe data is not received in core-data microservice.

**Attachments:**
[edgex-logs_uart-data_20220523_1240.txt](https://github.com/edgexfoundry/edgex-go/files/8752566/edgex-logs_uart-data_20220523_1240.txt)
[edgex-logs_core-data_20220523_1240.txt](https://github.com/edgexfoundry/edgex-go/files/8752572/edgex-logs_core-data_20220523_1240.txt)
[polling-uart-device-from-edgex_20220523_1240.txt](https://github.com/edgexfoundry/edgex-go/files/8752574/polling-uart-device-from-edgex_20220523_1240.txt)

**Comment by cloudxxx8** [comment]
> > please move the issue to https://github.com/edgexfoundry-holding/device-uart
> 
> Hi @cloudxxx8 Unable to add the issue under device-uart. i.e., **Issues** tab is **not available** in options.

it's true.  I don't know why.  @iain-anderson do you have any idea why device-uart doesn't allow to open issue?

**Comment by cloudxxx8** [comment]
> > if polling is workable, you might just need to set an autoEvent in Device
> 
> Thank you @cloudxxx8. Able to push the data from device service to core data with autoEvent. Is it possible to push the data/readings without autoEvents configuration in device file and deviceCommands in device profile file?

I don't have enough knowledge about uart.  Do you mean you want to use async value to receive data, like the device-mqtt to subscribe a mqtt topic?

**Comment by vediyappan-villali** [comment]
Yes, similar kind of.

**Comment by cloudxxx8** [comment]
@GreysTone for awareness

**Comment by vediyappan-villali** [comment]
@cloudxxx8 Able to push events to core-data (without AutoEvents configured in device file) by using AsyncValues channel. Thank you for the input!

**Comment by cloudxxx8** [comment]
may we close this issue?

**Comment by vediyappan-villali** [comment]
Yes, we can close this issue.
