### ISSUE TITLE
REST API output messages is not matching with messages available in swagger 2.1.0

### ISSUE THREAD

**Issue by vhg-in** [edgexfoundry/edgex-go#4037]
# 📚 Docs or Wiki Bug Report

### Description [**REQUIRED**]

 As part of verifying the available REST APIs for provisioning Device and Device-Profile, Found there's a mismatch with the message value in API response JSON output
Referred swagger link: https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.1.0#/
 
 Can you please help to conclude if this is a possible bug or is it as expected.
 

### What's the affected URL? [**REQUIRED**]
 https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.1.0#/

### Expected vs Actual Behavior

**Scenario 1:**
Expected message for HTTP status Code 409 as per swagger link :
{
    "apiVersion": "v2",
    "requestId": "d3742440-c319-4a9f-a488-b54cf992e143",
    "statusCode": 409,
    "message": "Duplicated"
  }
Actual message as per testing for HTTP status code 409:
[{"apiVersion":"v2",
  "requestId":"e6e8a2f4-eb14-4649-9e2b-175247911369",
  "message":"device profile name Simple-Device-Profile exists",
  "statusCode":409}]

**Scenario 2:**
Expected message for HTTP status Code 400 as per swagger link :
{
  "apiVersion": "v2",
  "requestId": "73f0932c-0148-11eb-adc1-0242ac120002",
  "statusCode": 400,
  "message": "Bad Request"
}
Actual message as per testing for HTTP status code 400:
{"apiVersion":"v2",
"message":"*[]requests.DeviceProfileRequest json decoding failed",
"statusCode":400}

**Scenario 3:**
Expected message for HTTP status Code 400 as per swagger link :
{
  "apiVersion": "v2",
  "requestId": "9524082e-96c0-42bb-b5d0-50c869444cc7",
  "statusCode": 500,
  "message": "Internal Server Error"
}
Actual message as per testing for HTTP status code 400:
             {"apiVersion":"v2",
              "requestId":"e6e8a2f4-eb14-4649-9e2b-175247911369",
              "message":"object Id existence check failed",
              "statusCode":500}

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

 Oracle Linux Virtual machine using Jakarta - 2.1.0

**Comment by jinlinGuan** [comment]
@vhg-in 
The messages could be different from those in the examples.

For Scenario 1, we have fixed in https://github.com/edgexfoundry/edgex-go/pull/2802/files, so the response should be an array as you mentioned. Could you specify which API you used?

For Scenario 3, do you mean you expected a 400 response, but it returned 500? Could you specify the API?

**Comment by cloudxxx8** [comment]
@vhg-in since the issue has been fixed, and the error message in the example is just an example.  we only make sure the status code is accurate.  we can't list all the possible error message in the swagger doc.
closing this issue.
