### ISSUE TITLE
A question about API Gateway

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/edgex-go#4051]
Hi, I am learning to use API Gateway with the [documentation](https://docs.edgexfoundry.org/2.0/security/Ch-APIGateway/). I wanted to set up the edgex-device-rest agent, so I added the following line to the docker-compose file. But it does not run, the error log is as follows:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/25740210/172579073-a73b864c-c294-44a7-ae59-62f00e3c820d.png">

```
root@u20:/home/edgex-compose# make run
docker-compose -p edgex -f docker-compose.yml up -d 
ERROR: The Compose file is invalid because:
Service edgex-proxy has neither an image nor a build context specified. At least one must be provided.
make: *** [Makefile:54: run] Error 1
```
May I ask what is wrong with my practice and how to modify it? Your reply will be of great help to me, thank you!

**Comment by bnevis-i** [comment]
@FengZeHe is this still an issue?

**Comment by bnevis-i** [comment]
It is called `proxy-setup` now.

See https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose.yml#L677
