### ISSUE TITLE
Firmware upgrade to end devices through EdgeX (i.e., core-data RedisDB)

### ISSUE THREAD

**Issue by vediyappan-villali** [edgexfoundry/edgex-go#4052]
I want to download the firmware from a web application to EdgeX (i.e., core-data), then from there I need to send/flash it to end device (i.e., UART device or Modbus sensors).

I could see there is an option to upload the device profile file. 

Uploading device profile:

```
vediyappan@vediyappan-desktop:~/work/samples$ curl http://localhost:59881/api/v2/deviceprofile/uploadfile -F "file=@device.uart.generic.new.yaml" | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1076  100    81  100   995   6373  78297 --:--:-- --:--:-- --:--:-- 97818
{
   "apiVersion" : "v2",
   "id" : "5c0150a1-54a6-4463-9342-45c6352fe863",
   "statusCode" : 201	 `<----- The HTTP 201 created success status response code indicates that the request has succeeded and has led to the creation of a resource.`
}
vediyappan@vediyappan-desktop:~/work/samples$
```

Is there any way to transfer/download a firmware file to EdgeX (i.e., core-data RedisDB)? If yes, how can we do that and where the downloaded files are getting stored? So that I can look for the options how can I flash it to device once the file is available in EdgeX.

**Comment by cloudxxx8** [comment]
We don't support the binary file set command right now, and this requirement should be able to be considered in this ADR
https://github.com/edgexfoundry/edgex-docs/pull/644

You need to write a service to download the file and store it as your requirement (anywhere you like) and call the function call accomplished by the above ADR

**Comment by vediyappan-villali** [comment]
@cloudxxx8 Ok, I will look for other options (i.e., writing service to download file). Thank you for the info.

**Comment by bnevis-i** [comment]
Can this issue be closed?

**Comment by vediyappan-villali** [comment]
Yes, we can close this.
