### ISSUE TITLE
Device name, profile name, resource name, and command name supports Chinese naming

### ISSUE THREAD

**Issue by watjt** [edgexfoundry/edgex-go#4053]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for...
ui-go , core-data, core-metadata, core-command and  all device service, those components used package go-mod-core-contracts

### Description [**REQUIRED**]
 A clear and concise description of the problem or missing capability...
Edgex is used in many traditional industries in China, and many PLC or other device names and addresses are named in Chinese.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Modify name regular check in go-mod-core-contracts, and use url.queryUnescape decode those Chinese name in core-metadata, ui-go etc.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by jpwhitemn** [comment]
This issue is closely related to this one #3935 .  At the May 2022 planning meeting, we discussed this need.  We left it in the backlog but decided not to address this in this release (Levski).  Reconsider in future planning meetings given multiple needs now.

**Comment by cloudxxx8** [comment]
Maybe we can just allow `%` char to name for now.  Users can leverage URL escape mechanism to accomplish some sort of globalization

**Comment by lenny-intel** [comment]
Maybe our validator needs to be reversed to not allow specific characters (space, comma, etc.) rather than restrict to limited set of characters. This should allow Chinese characters??

**Comment by cloudxxx8** [comment]
yes, we can discuss in the next Core WG meeting

**Comment by weichou1229** [comment]
Opened PRs for this issue,
- core-contract  https://github.com/edgexfoundry/go-mod-core-contracts/pull/853
- device-sdk  https://github.com/edgexfoundry/device-sdk-go/pull/1502
- edgex-go https://github.com/edgexfoundry/edgex-go/pull/4664
