### ISSUE TITLE
support-scheduler usages in EdgeX application

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-go#4072]
Hi @cloudxxx8 , @cherrycl , @jpwhitemn 
1. can we use support-scheduler for scheduling any custom operations to be performed in EdgeX ?
If yes, what could those activities be apart from deletion of events ?
2. Do we have any such document which can be referred for the implementation of any custom operation being scheduled using support-scheduler ?

please let me know for any suggestions. Thanks in advance.

**Comment by cloudxxx8** [comment]
since you asked the same question on slack, let's reply the question on slack
closing this issue

**Comment by dipshirajput** [comment]
@cloudxxx8  Thank you for the clarification.
