### ISSUE TITLE
API to post a subscription 

### ISSUE THREAD

**Issue by Rakshithakrishna2** [edgexfoundry/edgex-go#4096]
HI all, from the swagger [document](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.1.0#/default/post_subscription), tried creating a subscription,like 
`curl –X POST -d '[{"apiVersion": "v2","subscription": {"name": "subscriptionA", "channels": [{"type": "EMAIL","recipients":"gentoo475@gamil.com"},{"type": "REST","host": "192.168.184.201","port": 59860,"httpMethod":"GET"}],"categories": ["daily-notify"],"labels": ["daily"],"receiver": "receiverA","resendLimit": 0,"resendInterval":"1h","adminState": "UNLOCKED"}}]'  http://192.168.184.201:59860/api/v2/subscription`

but while doing so facing json decode error
The error is 
`curl: (3) Failed to convert –X to ACE; string contains a disallowed character
curl: (6) Could not resolve host: POST
curl: (6) Could not resolve host: v2,subscription
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Could not resolve host: subscriptionA,
curl: (6) Could not resolve host: channels
curl: (3) [globbing] bad range specification in column 2
curl: (3) [globbing] unmatched close brace/bracket in column 37
curl: (6) Could not resolve host: REST,host
curl: (6) Could not resolve host: 192.168.184.201,port
curl: (3) [globbing] unmatched close brace/bracket in column 21
curl: (3) [globbing] bad range in column 2
curl: (6) Could not resolve host: [daily],receiver
curl: (6) Could not resolve host: receiverA,resendLimit
curl: (3) Port number ended with 'h'
curl: (3) [globbing] unmatched close brace/bracket in column 9
{"apiVersion":"v2","message":"*[]requests.AddSubscriptionRequest json decoding failed","statusCode":400}`

The logs of support-notification is,

`level=ERROR ts=2022-07-19T05:44:07.156771152Z app=support-notifications source=http.go:47 X-Correlation-ID=46a352e5-f3f9-41da-ad1f-6b6c5d5b5c8c msg="*[]requests.AddSubscriptionRequest json decoding failed -> invalid character 'â' looking for beginning of value"
level=DEBUG ts=2022-07-19T05:44:07.156923996Z app=support-notifications source=http.go:49 X-Correlation-ID=46a352e5-f3f9-41da-ad1f-6b6c5d5b5c8c msg="[/home/rakshitha/Documents/EDGEX/Jakarta/edgex-go/internal/io/reader.go]-github.com/edgexfoundry/edgex-go/internal/io.jsonDtoReader.Read(line 45): *[]requests.AddSubscriptionRequest json decoding failed -> invalid character 'â' looking for beginning of value"
level=ERROR ts=2022-07-19T05:44:20.107797635Z app=support-notifications source=http.go:47 X-Correlation-ID=c2f4ab8f-0750-480e-8e23-b02509c70b25 msg="*[]requests.AddSubscriptionRequest json decoding failed -> invalid character 'â' looking for beginning of value"`

Also my POST notification API is ,(where I am able to post the notification.) 
`curl -X POST -d '[{"apiVersion":"v2","notification":{"category":"daily-notify","content":"content","contentType":"string","description":"device notice","labels":["daily"],"sender":"core-metadata","severity":"NORMAL","status":"NEW"}}]' http://192.168.184.201:59860/api/v2/notification`
Kindly correct if the REST API is incorrect.
Thank you.

**Comment by cloudxxx8** [comment]
closing this issue because the same question is raised in slack
