### ISSUE TITLE
"ACL not found" messages logged as errors

### ISSUE THREAD

**Issue by farshidtz** [edgexfoundry/edgex-go#4108]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 

There are many "ACL not found" ERRORs in the logs followed by INFO messages about creating them. Are these really meant to be errors? I believe these should be reduced to WARN. 

### Is this a regression?
Yes, the previous version in which this bug was not present was: v2.2

### Description and Minimal Reproduction [**REQUIRED**]

```
sudo snap install edgexfoundry --channel=latest/edge
snap logs -n=1000 edgexfoundry | grep --ignore-case "error"
```

## 🔥 Exception or Error
```
edgexfoundry.consul[156574]: 2022-07-29T17:17:49.335+0200 [ERROR] agent.http: Request error: method=GET url=/v1/acl/policy/name/acl_policy_for_app-functional-tests from=127.0.0.1:52794 error="ACL not found"
edgexfoundry.security-consul-bootstrapper[157086]: level=INFO ts=2022-07-29T15:17:49.346843916Z app=security-bootstrapper source=aclpolicies.go:142 msg="successfully created a new agent policy with name acl_policy_for_app-functional-tests"
edgexfoundry.security-consul-bootstrapper[157086]: level=INFO ts=2022-07-29T15:17:49.348177934Z app=security-bootstrapper source=aclroles.go:129 msg="successfully created a role [app-functional-tests] for secretstore"

edgexfoundry.consul[156574]: 2022-07-29T17:17:49.348+0200 [ERROR] agent.http: Request error: method=GET url=/v1/acl/policy/name/acl_policy_for_device-grove from=127.0.0.1:52794 error="ACL not found"
edgexfoundry.security-consul-bootstrapper[157086]: level=INFO ts=2022-07-29T15:17:49.359151534Z app=security-bootstrapper source=aclpolicies.go:142 msg="successfully created a new agent policy with name acl_policy_for_device-grove"
 edgexfoundry.security-consul-bootstrapper[157086]: level=INFO ts=2022-07-29T15:17:49.360910761Z app=security-bootstrapper source=aclroles.go:129 msg="successfully created a role [device-grove] for secretstore"
...
```

## 🌍  Your Environment
**Deployment Environment:**
Snap

**EdgeX Version [**REQUIRED**]:**
2.3.0-dev.31

**Anything else relevant?**

**Comment by jim-wang-intel** [comment]
@farshidtz  we could change it warning level as you suggested, please bring this up in the next Security WG meeting to prioritize this

**Comment by bnevis-i** [comment]
Suggest instead of a GET <policy> to check existence, enumerate the list of policies and filter on <policy> existence.

**Comment by farshidtz** [comment]
As discussed in the security call, this is actually coming directly from Consul so we can't simply change it to warning. @jim-wang-intel how do you think this can be changed without doing what Brian suggests?

See also: https://github.com/hashicorp/consul/issues/9933
Maybe we can pursue this on Consul's side so it ends 404 Not Found and not logged as error.

**Comment by bnevis-i** [comment]
I believe the offending lines are:

https://github.com/edgexfoundry/edgex-go/blob/main/internal/security/bootstrapper/command/setupacl/aclpolicies.go#L113

```go
policy, err := c.getPolicyByName(tokenID, policyName)
```

https://github.com/edgexfoundry/edgex-go/blob/a0e04e5594f9191c51d4a9e4e045bcf4d31a8569/internal/security/bootstrapper/command/setupacl/aclpolicies.go#L186

And the policy list command:
<https://www.consul.io/commands/acl/policy/list>
