### ISSUE TITLE
Add HTTP 400 Response to Core-Data Service

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#411]
Operations that verify the content of a given request, whether a GET/DELETE parameter or a POST/PUT body payload, should return an HTTP Status 400 (Bad Request) instead of HTTP Status 503 (Service Unavailable). Example from internal/core/data/event.go:

```
// Post a new event
case http.MethodPost:
	var e models.Event
	dec := json.NewDecoder(r.Body)
	err := dec.Decode(&e)

	// Problem Decoding Event
	if err != nil {
		http.StatusBadRequest
		http.Error(w, err.Error(), http.StatusServiceUnavailable)
		loggingClient.Error("Error decoding event: " + err.Error())
		return
	}
```

Failure to deserialize the incoming JSON should result in a 400 (BadRequest) and not 503 (ServiceUnavailable)

The RAML should be updated accordingly.

**Comment by tsconn23** [comment]
Associated with #284

**Comment by brandonforster** [comment]
Closing this issue as the PR has been merged.
