### ISSUE TITLE
Use RequireMessageBus config instead of MessageQueue.Required

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#4180]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-command

### Description [**REQUIRED**]

Currently, core-command uses MessageQueue.Required to control whether to enable the messaging API for both internal and external command requests, and the default value is false.
https://github.com/edgexfoundry/edgex-go/blob/17acb4d22b6a38b20e3dd1bbaacb8af86852ef24/cmd/core-command/res/configuration.toml#L47-L48

This causes some issues:

1. The config name is too general to understand its feature. We should follow the config in core-metadata
https://github.com/edgexfoundry/edgex-go/blob/39fcbed88f67e201ee240975c941ad828856b121/cmd/core-metadata/res/configuration.toml#L1-L4
2. The default value should be `true` for internal messaging APIs.
3. The user might not need the external messaging, so the config should be separated and the external messaging default should be disabled.

**Comment by cloudxxx8** [comment]
@lenny-intel any thought?
I suggest to use `MessageQueue.External.Enabled= false` to determine whether the service needs to connect to the External Message Bus.

**Comment by lenny-intel** [comment]
Using External MQTT only makes sense if internal is enabled, so I don't see the need for both. I am fine with `RequireMessageBus` as we did in Core Data as it will be important when upcoming metrics are added to Core Command.

**Comment by lenny-intel** [comment]
Ok, I know see why we would want to enable/disable external MQTT :-)
Yes, agree with `RequireMessageBus = true` and `MessageQueue.External.Enabled= false`
