### ISSUE TITLE
Refine the default external messaging config in core-command

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#4181]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-command

### Description [**REQUIRED**]
The current default external messaging config is as follows
https://github.com/edgexfoundry/edgex-go/blob/17acb4d22b6a38b20e3dd1bbaacb8af86852ef24/cmd/core-command/res/configuration.toml#L81-L96

The authmode should not be `none`, and the default secret path should not be `mqtt` because it might be conflicted with the internal mqtt messaging secret path.

**Comment by cloudxxx8** [comment]
@lenny-intel any thought? I suggest the default authMode is userpassword and secret path is `external-mqtt`

**Comment by lenny-intel** [comment]
> the default secret path should not be `mqtt` because it might be conflicted with the internal mqtt messaging secret path.

Note that the the internal messaging secret path is `message-bus` for secure mqtt. 
The default AuthMode here should still be `none` and can be overridden in compose when it needs to be `userpassword`.  `SecretPath` could be more explicit `external-mqtt` as default path, but again `mqtt` could be overridden in compose file if needed.

**Comment by cloudxxx8** [comment]
ok, I think we can close this issue and keep it as is
thanks, @lenny-intel
