### ISSUE TITLE
Refine the default messaging topics in core-command

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#4183]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-command

### Description [**REQUIRED**]
The current default topics settings are as follows:
https://github.com/edgexfoundry/edgex-go/blob/17acb4d22b6a38b20e3dd1bbaacb8af86852ef24/cmd/core-command/res/configuration.toml#L56-L62

These are accordance with ADR.
However, they don't follow the general edgex topic naming.  Just like event messaging, there are two kinds of topics, published by device services and core service.  Thus, I suggest to use the following topics:

```
    DeviceRequestTopicPrefix = "edgex/device/command/request"    # for publishing requests to the device service; <device-service>/<device-name>/<command-name>/<method> will be added to this publish topic prefix
    DeviceResponseTopic = "edgex/device/command/response/#"      # for subscribing to device service responses
    CommandRequestTopic = "edgex/core/command/request/#"     # for subscribing to internal command requests
    CommandResponseTopicPrefix = "edgex/core/command/response"     # for publishing responses back to internal service /<device-name>/<command-name>/<method> will be added to this publish topic prefix
    QueryRequestTopic = "edgex/core/commandquery/request"   # for subscribing to internal command query requests
    QueryResponseTopic = "edgex/core/commandquery/response"   # for publishing reponsses back to internal service
```

In addtion, the external topics should be just examples, and they should not be conflicted with the internal topics in case the user use the internal message broker to run some tests.
https://github.com/edgexfoundry/edgex-go/blob/17acb4d22b6a38b20e3dd1bbaacb8af86852ef24/cmd/core-command/res/configuration.toml#L92-L96

Thus, I suggest changing them to:
```
    CommandRequestTopic = "external/edgex/command/request/#"           # for subscribing to 3rd party command requests
    CommandResponseTopicPrefix = "external/edgex/command/response"     # for publishing responses back to 3rd party systems /<device-name>/<command-name>/<method> will be added to this publish topic prefix
    QueryRequestTopic = "external/edgex/commandquery/request/#"        # for subscribing to 3rd party command query request
    QueryResponseTopic = "external/edgex/commandquery/response"        # for publishing responses back to 3rd party systems
```

**Comment by cloudxxx8** [comment]
@lenny-intel any thought?

**Comment by lenny-intel** [comment]
Yes these internal topics are not consistent. obviously I missed that :-)
```
 CommandRequestTopic = "/command/request/#"     # for subscribing to internal command requests 
 CommandResponseTopicPrefix = "/command/response"     # for publishing responses back to internal service /<device-name>/<command-name>/<method> will be added to this publish topic prefix 
 QueryRequestTopic = "/commandquery/request"   # for subscribing to internal command query requests 
 QueryResponseTopic = "/commandquery/response"   # for publishing reponsses back to internal service 
```
I am good with the suggested changes.

As for the external topics, I don't see the value of the added the `external/` prefix. The are topics only on the external MQTT broker so there would not be any conflict.

**Comment by cloudxxx8** [comment]
ok, let's keep the external topics as is
