### ISSUE TITLE
why not set expires for redis key？

### ISSUE THREAD

**Issue by hchw** [edgexfoundry/edgex-go#4237]
https://github.com/edgexfoundry/edgex-go/blob/a2765a98d8f71eb240f317e00f16757db580c473/internal/pkg/infrastructure/redis/event.go#L152

i saw the api for delete, but i  don't know why

**Comment by cloudxxx8** [comment]
please help describe your question clearly.  I don't understand what you are asking.

**Comment by hchw** [comment]
I don't know that why not use ' _ = conn.Send(SET, storedKey, m,  "EX", timeout) '.  because ，After running  a while, redis will become very large. 
now I had add a handler in pipeline to delete event, but is it better to auto delete？
thank you

**Comment by cloudxxx8** [comment]
it's a considerable idea, and we plan to resolve this issue via https://github.com/edgexfoundry/edgex-docs/pull/723
We don't use the redis specific because we open for other persistence layer implementation.
