### ISSUE TITLE
[EdgeX 3.0] Remove SMA

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#4246]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for sma

### Description [**REQUIRED**]
We deviced to remove SMA in v3

### Describe the solution you'd like
Remove all the SMA related code

**Comment by cloudxxx8** [comment]
resolved by https://github.com/edgexfoundry/edgex-go/pull/4265

**Comment by fantacymaker** [comment]
Why should this be removed?

**Comment by fantacymaker** [comment]
aha..i see the reason: https://docs.edgexfoundry.org/2.3/microservices/system-management/Ch_SystemManagement/
