### ISSUE TITLE
Error while making docker image ?

### ISSUE THREAD

**Issue by Kumarasamy** [edgexfoundry/edgex-go#426]
Error Message:
kumarasamy@Kumarasamy-PC:~/go/src/github.com/edgexfoundry/edgex-go$ sudo make docker
docker build \
	-f docker/Dockerfile.export-client \
	--label "git_sha=dc76c0d" \
	-t edgexfoundry/docker-export-client-go:dc76c0d \
	-t edgexfoundry/docker-export-client-go:0.5.2-dev \
	.
Sending build context to Docker daemon  290.1MB
Step 1/12 : FROM golang:1.9-alpine AS builder
 ---> e2d4d570adf9
Step 2/12 : WORKDIR /go/src/github.com/edgexfoundry/edgex-go
 ---> Using cache
 ---> 0d6c64787eb1
Step 3/12 : RUN echo http://nl.alpinelinux.org/alpine/v3.6/main > /etc/apk/repositories;     echo http://nl.alpinelinux.org/alpine/v3.6/community >> /etc/apk/repositories
 ---> Using cache
 ---> 7a2fc5ba2b42
Step 4/12 : RUN apk update && apk add make
 ---> Using cache
 ---> 854a98ae4328
Step 5/12 : COPY . .
 ---> Using cache
 ---> 464ecd2f51ea
Step 6/12 : RUN make cmd/export-client/export-client
 ---> Using cache
 ---> 15616c8c54cd
Step 7/12 : FROM scratch
 ---> 
Step 8/12 : LABEL license='SPDX-License-Identifier: Apache-2.0'       copyright='Copyright (c) 2017-2018: Mainflux, Cavium'
 ---> Using cache
 ---> f865a8c9663d
Step 9/12 : COPY --from=builder /go/src/github.com/edgexfoundry/edgex-go/cmd/export-client/export-client /
 ---> Using cache
 ---> 579a7c30316a
Step 10/12 : COPY --from=builder /go/src/github.com/edgexfoundry/edgex-go/cmd/export-client/res/configuration-docker.toml /res/configuration-docker.toml
 ---> Using cache
 ---> e47d2e368cc2
Step 11/12 : ENTRYPOINT ["/export-client","--consul","--profile=docker","--confdir=/res"]
 ---> Using cache
 ---> 9fcb27c319ed
Step 12/12 : LABEL git_sha=dc76c0d
 ---> Using cache
 ---> 2305b21724a5
Successfully built 2305b21724a5
Successfully tagged edgexfoundry/docker-export-client-go:dc76c0d
Successfully tagged edgexfoundry/docker-export-client-go:0.5.2-dev
docker build \
	-f docker/Dockerfile.export-distro \
	--label "git_sha=dc76c0d" \
	-t edgexfoundry/docker-export-distro-go:dc76c0d \
	-t edgexfoundry/docker-export-distro-go:0.5.2-dev \
	.
Sending build context to Docker daemon  290.1MB
Step 1/14 : FROM golang:1.9-alpine AS builder
 ---> e2d4d570adf9
Step 2/14 : WORKDIR /go/src/github.com/edgexfoundry/edgex-go
 ---> Using cache
 ---> 0d6c64787eb1
Step 3/14 : RUN echo http://nl.alpinelinux.org/alpine/v3.6/main > /etc/apk/repositories;     echo http://nl.alpinelinux.org/alpine/v3.6/community >> /etc/apk/repositories
 ---> Using cache
 ---> 7a2fc5ba2b42
Step 4/14 : RUN apk update && apk add zeromq-dev libsodium-dev pkgconfig build-base
 ---> Using cache
 ---> 01a8ff8edbfc
Step 5/14 : COPY . .
 ---> Using cache
 ---> 91921cc89ed5
Step 6/14 : RUN make cmd/export-distro/export-distro
 ---> Using cache
 ---> d6c5537dae64
Step 7/14 : FROM alpine:3.7
 ---> 791c3e2ebfcb
Step 8/14 : LABEL license='SPDX-License-Identifier: Apache-2.0'       copyright='Copyright (c) 2017-2018: Mainflux, Cavium'
 ---> Using cache
 ---> 0e049d551ed8
Step 9/14 : RUN echo http://nl.alpinelinux.org/alpine/v3.7/main > /etc/apk/repositories;     echo http://nl.alpinelinux.org/alpine/v3.7/community >> /etc/apk/repositories
 ---> Using cache
 ---> f05a6252751c
Step 10/14 : RUN apk --no-cache add zeromq
 ---> Using cache
 ---> da60f5bbe355
Step 11/14 : COPY --from=builder /go/src/github.com/edgexfoundry/edgex-go/cmd/export-distro/export-distro /
 ---> Using cache
 ---> d49764d8a5df
Step 12/14 : COPY --from=builder /go/src/github.com/edgexfoundry/edgex-go/cmd/export-distro/res/configuration-docker.toml /res/configuration-docker.toml
 ---> Using cache
 ---> fde24d9e5165
Step 13/14 : ENTRYPOINT ["/export-distro","--consul","--profile=docker","--confdir=/res"]
 ---> Using cache
 ---> dc42a778acf7
Step 14/14 : LABEL git_sha=dc76c0d
 ---> Using cache
 ---> 372580819917
Successfully built 372580819917
Successfully tagged edgexfoundry/docker-export-distro-go:dc76c0d
Successfully tagged edgexfoundry/docker-export-distro-go:0.5.2-dev
docker build \
	-f docker/Dockerfile.core-data \
	--label "git_sha=dc76c0d" \
	-t edgexfoundry/docker-core-data-go:dc76c0d \
	-t edgexfoundry/docker-core-data-go:0.5.2-dev \
	.
Sending build context to Docker daemon  290.1MB
Step 1/14 : FROM golang:1.9-alpine AS builder
 ---> e2d4d570adf9
Step 2/14 : WORKDIR /go/src/github.com/edgexfoundry/edgex-go
 ---> Using cache
 ---> 0d6c64787eb1
Step 3/14 : RUN echo http://nl.alpinelinux.org/alpine/v3.6/main > /etc/apk/repositories;     echo http://nl.alpinelinux.org/alpine/v3.6/community >> /etc/apk/repositories
 ---> Using cache
 ---> 7a2fc5ba2b42
Step 4/14 : RUN apk update && apk add zeromq-dev libsodium-dev pkgconfig build-base
 ---> Using cache
 ---> 01a8ff8edbfc
Step 5/14 : COPY . .
 ---> Using cache
 ---> 91921cc89ed5
Step 6/14 : RUN make cmd/core-data/core-data
 ---> Using cache
 ---> 29e279aec42c
Step 7/14 : FROM alpine:3.7
 ---> 791c3e2ebfcb
Step 8/14 : LABEL license='SPDX-License-Identifier: Apache-2.0'       copyright='Copyright (c) 2018: Dell, Cavium'
 ---> Using cache
 ---> 4b30039365f2
Step 9/14 : RUN echo http://nl.alpinelinux.org/alpine/v3.7/main > /etc/apk/repositories;     echo http://nl.alpinelinux.org/alpine/v3.7/community >> /etc/apk/repositories
 ---> Using cache
 ---> d5684993f973
Step 10/14 : RUN apk --no-cache add zeromq
 ---> Running in f2a08c25464d
fetch http://nl.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/5) Installing libgcc (6.4.0-r5)
(2/5) Installing libsodium (1.0.15-r0)
ERROR: libsodium-1.0.15-r0: BAD signature
(3/5) Installing libstdc++ (6.4.0-r5)
(4/5) Installing libzmq (4.2.2-r2)
(5/5) Installing zeromq (4.2.2-r2)
Executing busybox-1.27.2-r11.trigger
1 error; 6 MiB in 17 packages
The command '/bin/sh -c apk --no-cache add zeromq' returned a non-zero code: 1
Makefile:74: recipe for target 'docker_core_data' failed
make: *** [docker_core_data] Error 1

OS:Ubuntu 16.04

**Comment by jpwhitemn** [comment]
@Kumarasamy - this doesn't look like an error in building EdgeX so much as an issue building zeromq.  What's your platform and OS?

**Comment by drasko** [comment]
Closing due inactivity. Please re-open if needed.
