### ISSUE TITLE
Core Common Config Bootstrapper - Create Service Skeleton

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#4260]
Add new service into existing repo structure 
service key will be `core-common-config` (add to core contract constants)
Create initial common config YAML file with all the Common config sections
Command line flags that will be supported
- -cp, --configProvider           
- -o, --overwrite
- -p, --profile ??
- -cf/--configFile
- -cd/--configDir

Standard makefile and docker stuff

- Add service to existing makefile
- Add standard Dockerfile

Add Core Common Config to security service as a default service

Service will simple create the command line flags and exit
Docker Entry point script that doesn't exit like proxy setup does

**Comment by lenny-intel** [comment]
all-services:
  Writable:
      Telemetry:
         Metrics:
             
  MessageBus:
     

app-services:
  Writable:
      Telemetry:
         Metrics:

device-services:
  Writable:
      Telemetry:
         Metrics:

**Comment by ejlee3** [comment]
PR here: https://github.com/edgexfoundry/edgex-go/pull/4292
