### ISSUE TITLE
Enable RegEx for executing Get commands

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#4279]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-command

### Description [**REQUIRED**]
Users need to execute multiple the Get commands to retrieve the current values from one Device, if they would like to integrate the SCADA system which comply with Sparkplug B.
https://sparkplug.eclipse.org/

For thounds device resorces, defining everything in the Device Command is not pratical.

### Describe the solution you'd like
We'd like to have a regular expression driven API (similar to your resource matching idea) on the command service (and device service) to support the idea of getting device resources using a specified and standard regular expression.  The API might look something like this:
/device/name/{name}/{regEx} where regEx specifies via regular expression string the device resource names to be obtained in the get operation.  As examples:

- /device/name/thermostatA/* -> get all the device resources from ThermostatA
- /device/name/battMngmtSysY/battString[0-9]+ -> get all the battery strings - numbered 0-9 properties

This API would be supported by the device service SDKs.

The command service would only validate that the regular expression passed in was valid.  It wouldn't have to get any operation info from metadata to complete the request to the device service (other than to know the device and device service are valid too).  The device service would respond with a retrieved event/readings for the matching device resources per the regEx.  If there is no match of device resources then the service could either respond with an error or an empty result set - TBD at implementation time).

**Comment by cloudxxx8** [comment]
@iain-anderson the special character can be handled by the URL escaped
https://github.com/edgexfoundry/go-mod-core-contracts/issues/773

I am asking @weichou1229 to provide an example and verify it with MQTT borker and Redis pub/sub

**Comment by weichou1229** [comment]
For the Redis topic example, handle the special character by the URL escaped:
```
/device/name/thermostatA/* => device.name.thermostatA.%2A
/device/name/battMngmtSysY/battString[0-9]+ => device.name.battMngmtSysY.battString%5B0-9%5D%2B
```
I verified the URL escaped worked in the Redis pub sub.

**Comment by cloudxxx8** [comment]
We also verified it can work in MQTT

**Comment by lenny-intel** [comment]
@cloudxxx8 , so we first need to implement the URL escaping of topics on go-mod-messaging implementations. Please create issue there. THX!

**Comment by cloudxxx8** [comment]
https://github.com/edgexfoundry/go-mod-core-contracts/issues/773 is the issue we need

**Comment by lenny-intel** [comment]
> [edgexfoundry/go-mod-core-contracts#773](https://github.com/edgexfoundry/go-mod-core-contracts/issues/773) is the issue we need

This is for the HTTP Client, we need the same on go-mod-messaging.

**Comment by weichou1229** [comment]
> This is for the HTTP Client, we need the same on go-mod-messaging.

@lenny-intel I'm not sure what should be done in the `go-mod-messaging`, could you help identify that?

To adopt the escaped value, I made the following changes
- add commits in the edgex-go to **unescape** the commandName 
   https://github.com/edgexfoundry/edgex-go/pull/4376/files#diff-c70f7235bd11a244a790e0f5f48c58a3e742a431fcbe2ebae2785ac6765db9edR114
- add a cmmint in device-sdk-go to **unescape** the commandName 
  https://github.com/edgexfoundry/device-sdk-go/pull/1335/files#diff-06fcd6b4cd61ca170e310a25324ac41e9b7c47990ae7350cce25b02ecc16c469R75
- add a commit in the go-core-contracts to **escape** the topic path
  https://github.com/edgexfoundry/go-mod-core-contracts/pull/806/files#diff-f2f88dc0ca897c7f32c20739cc366ecb1e48d4d6625c7b0474d5b73491a85eb0R41
