### ISSUE TITLE
edgex-go v2.3.0 can not build docker: unsupported ARCH: armv7l for "spire server/agent"

### ISSUE THREAD

**Issue by jiekechoo** [edgexfoundry/edgex-go#4282]
Build and Run on Linux on ARM 32: https://docs.edgexfoundry.org/2.3/getting-started/native/Ch-BuildRunOnArm32

Step 6/13 : RUN echo "building spire from source..." &&     make bin/spire-server bin/spire-agent &&     cp bin/spire* /usr/local/bin/
 ---> Running in 3edee74e0e63
building spire from source...
### Makefile:102: *** unsupported ARCH: armv7l.  Stop.
The command '/bin/sh -c echo "building spire from source..." &&     make bin/spire-server bin/spire-agent &&     cp bin/spire* /usr/local/bin/' returned a non-zero code: 2
^Cmake: *** [Makefile:181: docker_base] Interrupt

**Comment by jiekechoo** [comment]
1. I skip build some `DOCKERS`(security components) in Makefile
```
DOCKERS= \
	docker_core_data \
	docker_core_metadata \
	docker_core_command  \
	docker_support_notifications \
	docker_sys_mgmt_agent \
	docker_support_scheduler #\ skip from here
	docker_security_proxy_setup \
	docker_security_secretstore_setup \
	docker_security_bootstrapper \
	docker_security_spire_server \
	docker_security_spire_agent \
	docker_security_spire_config \
	docker_security_spiffe_token_provider
```
2. and comment `docker_base` in Makefile
```
docker_base:
// comment here
#	echo "Building local cache image";\
	response=$(shell curl --write-out '%{http_code}' --silent --output /dev/null "$(BASE_DOCKERFILE)"); \
	if [ "$${response}" = "200" ]; then \
		echo "Found base Dockerfile"; \
		curl -s "$(BASE_DOCKERFILE)" | docker build -t $(LOCAL_CACHE_IMAGE_BASE) -f - .; \
		echo "FROM $(LOCAL_CACHE_IMAGE_BASE)\nWORKDIR /edgex-go\nCOPY go.mod .\nRUN go mod download" | docker build -t 
$(LOCAL_CACHE_IMAGE) -f - .; \
	else \
		echo "No base Dockerfile found. Using golang:$(GO_VERSION)-alpine"; \
		echo "FROM golang:$(GO_VERSION)-alpine\nRUN apk add --update make git\nWORKDIR /edgex-go\nCOPY go.mod .\nRUN go
 mod download" | docker build -t $(LOCAL_CACHE_IMAGE) -f - .; \
	fi
// copy here
echo "No base Dockerfile found. Using golang:$(GO_VERSION)-alpine"; \
echo "FROM golang:$(GO_VERSION)-alpine\nRUN apk add --update make git\nWORKDIR /edgex-go\nCOPY go.mod .\nRUN go
mod download" | docker build -t $(LOCAL_CACHE_IMAGE) -f - .; \
```
3. make docker images locally, I built edgex-go, device-*, and custom devices and services
4. push images to private registry repository
5. modify `image` items(edgexfoundry/**) in docker-compose.yml , pull images from private registry server
6. EdgeX runs success
7. here is screenshot
![image](https://user-images.githubusercontent.com/3350211/212461421-c412690b-0b40-4312-8ebf-a9cd61f4e676.png)

**Comment by lenny-intel** [comment]
Go not longer support armv7 (https://github.com/golang/go/issues/41074)
The docker builds build the image for x86 Linux.

**Comment by farshidtz** [comment]
> Go not longer support armv7 ([golang/go#41074](https://github.com/golang/go/issues/41074)) The docker builds build the image for x86 Linux.

@lenny-intel the linked issue says that armv7 is no longer supported for [Darwin](https://en.wikipedia.org/wiki/Darwin_(operating_system)). The issue is about armv7 on Linux.
