### ISSUE TITLE
Event didn't publish to messagebus when getting command with ds-pushevent=true

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4297]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Command

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with [compose file](https://raw.githubusercontent.com/edgexfoundry/edgex-compose/main/docker-compose-no-secty.yml).
2. Remove the autoevent for pre-created device Random-Boolean-Device of device-virtual.
3. Send `Get` command to `http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool?ds-pushevent=true`
4. The event didn't receive on core-data or app-service

## 🔥 Exception or Error
No publish to MessageBus log found in device-virtual
<pre><code>
level=DEBUG ts=2023-01-19T03:53:45.007389102Z app=device-virtual source=transform.go:121 msg="device: Random-Boolean-Device DeviceResource: Bool reading: {Id:f919728f-ce62-4064-82fa-81e0f3240116 Origin:1674100425007353735 DeviceName:Random-Boolean-Device ResourceName:Bool ProfileName:Random-Boolean-Device ValueType:Bool Units: BinaryReading:{BinaryValue:[] MediaType:} SimpleReading:{Value:false} ObjectReading:{ObjectValue:<nil>}}"
level=DEBUG ts=2023-01-19T03:53:45.007424382Z app=device-virtual source=command.go:69 msg="GET Device Command successfully. Device: Random-Boolean-Device, Source: Bool, X-Correlation-ID: d974f390-7e56-48e8-88bc-5b02d0459231"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
this should be resolved after https://github.com/edgexfoundry/device-sdk-go/pull/1279 is merged and upgrade the sdk to each device service

**Comment by cherrycl** [comment]
This issue was gone after PR #4269 was merged.
