### ISSUE TITLE
Same 'VERSION' file used for docker and snaps

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#4313]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
build

### Is this a regression?
No

### Description and Minimal Reproduction [**REQUIRED**]
The `VERSION` file in the git root is used for both versioning snaps as well as docker.  The result is that if you are testing both snaps and docker, docker testing is ineffectual.

For example, after building a snap, VERSION might be 3.0.0-dev.99.

But if you build docker at that point, you get edgexfoundry/container-name:3.0.0-dev.99 but the docker-compose files are configured to use edgexfoundry/container-name:0.0.0-dev.   Thus, when testing under docker, after building a snap, you are not actually testing the latest change.

## 🌍  Your Environment
**Deployment Environment:**
**EdgeX Version [**REQUIRED**]:** "main"

**Anything else relevant?**

**Comment by farshidtz** [comment]
The VERSION file is generated during the snap build (as output of `git describe`), because the Makefile needs it for the builds. We could change this so that the file isn't added to the git root, but rather kept only inside the build environment of the snap.

**Comment by bnevis-i** [comment]
Closing since EdgeX has deprecated the snap distribution of EdgeX
