### ISSUE TITLE
Set PostDeviceChanges=true on metadata configuration didn't sent notices to notifications

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4315]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: metadata, notifications

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with [compose file](https://raw.githubusercontent.com/edgexfoundry/edgex-compose/d6a7aab736ce2fec08ca120173d648c185f782cf/docker-compose-no-secty.yml).
2. Set PostDeviceChanges=true on metadata from Consul
3. Restart edgex-core-metadata service
4. Create, update or delete a device
5. Query notifications

`No any device related notifications found`
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** x86 / ubuntu

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
`PostDeviceChanges` will be removed from EdgeX 3.0, so please also remove the corresponding TAF tests
https://github.com/edgexfoundry/edgex-go/issues/4316
