### ISSUE TITLE
All properties of device resource are listed when get device profile by API, even the upload file didn't contain the property

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4321]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Metadata

### Is this a regression?

 No, this behavior also existed on Levski.

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with [compose file](https://github.com/edgexfoundry/edgex-compose/blob/6800fab20a8887fe927a3722835509193cc8b929/docker-compose-no-secty.yml).
2. Create a new profile with attached file.
[Test-Profile-3.yaml.zip](https://github.com/edgexfoundry/edgex-go/files/10660495/Test-Profile-3.yaml.zip)

3. Query the profile by API `http://localhost:59882/api/v2/deviceprofile/name/Test-Profile-3`

## 🔥 Exception or Error
deviceResources displayed like as below.
<pre><code>
{
                "description": "Generate device FLOAT32 value",
                "name": "DeviceValue_FLOAT32_R",
                "isHidden": true,
                "tag": "humidity",
                "properties": {
                    "valueType": "Float32",
                    "readWrite": "R",
                    "units": "",
                    "minimum": "",
                    "maximum": "",
                    "defaultValue": "",
                    "mask": "",
                    "shift": "",
                    "scale": "",
                    "offset": "",
                    "base": "",
                    "assertion": "",
                    "mediaType": ""
                },

</code></pre>
Expected behavior:
```
{
                "description": "Generate device FLOAT32 value",
                "name": "DeviceValue_FLOAT32_R",
                "isHidden": true,
                "tag": "humidity",
                "properties": {
                    "valueType": "Float32",
                    "readWrite": "R",
}
```

## 🌍  Your Environment
**Deployment Environment:** x86 / Ubuntu

**EdgeX Version [**REQUIRED**]:** main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
we should re-visit this issue after https://github.com/edgexfoundry/go-mod-core-contracts/issues/770 is resolved

**Comment by cloudxxx8** [comment]
@cherrycl please help verify this issue again

**Comment by cherrycl** [comment]
This issue was fixed.
