### ISSUE TITLE
Java "support-notifications" will not pass new Blackbox (Integration) tests.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#435]
- This is a heads up that "support-notifications" (Java) will **not** pass new Blackbox (Integration) tests.
- The relevant PR is: [PR #428](https://github.com/edgexfoundry/edgex-go/pull/428)
- According to the Java RAML, for both "/transmission" and for "/notification", the path each for querying records (collections) by creation timestamp between start date and end date, with limited returned records, is:
`/{start}/{end}/{limit}`
- Per the (following) update (for both "/transmission" and for "/notification") in the RAML, "support-notifications" (Java) will **not** pass new Blackbox (Integration) tests: 
`/start/{start}/end/{end}/{limit}`
- A change will eventually be required for the Java implementation to match the Golang version.

**Comment by tsconn23** [comment]
@akramtexas Can you please move this to the Java support-notifications repo issues list?

https://github.com/edgexfoundry/support-notifications

**Comment by akramtexas** [comment]
@tsconn23 Yep, done. I've created [Issue #21](https://github.com/edgexfoundry/support-notifications/issues/21) to the Java support-notifications repo issues list. I reckon the next step is for me to delete the issue as [originally created here...](https://github.com/edgexfoundry/edgex-go/issues)
