### ISSUE TITLE
Set/Get command by external mqtt got error "timed out waiting for response"

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4356]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Command

### Description and Minimal Reproduction [**REQUIRED**]
Get Command:
```
mosquitto_pub -h localhost -p 1884 -t edgex/command/request/Test-Device/Virtual_GenerateDeviceValue_INT16_RW/get -m '{
    "Correlation-ID": "14a42ea6-c394-41c3-8bcd-a29b9f5e6835",
    "apiVersion": "v2",
    "requestId": "e6e8a2f4-eb14-4649-9e2b-175247911369",
    "ContentType": "application/json",
    "queryParams": {
        "ds-pushevent":"true",
        "ds-returnevent":"true"
     }
}'
```

Set Command 
```
mosquitto_pub -h localhost -p 1884 -t edgex/command/request/Test-Device/Virtual_GenerateDeviceValue_INT16_RW/set -m '{
    "Correlation-ID": "14a42ea6-c394-41c3-8bcd-a29b9f5e6835",
    "apiVersion": "v2",
    "requestId": "e6e8a2f4-eb14-4649-9e2b-175247911369",
    "ContentType": "application/json",
    "Payload": "eyJWaXJ0dWFsX0RldmljZVZhbHVlX0lOVDE2X1JXIjogIjMyMDAifQ=="
}'
```

## 🔥 Exception or Error
No response received and found the error on core-command logs
<pre><code>
level=ERROR ts=2023-02-14T08:52:55.459643933Z app=core-command source=external.go:159 msg="Failed to send DeviceCommand request with internal MessageBus: timed out waiting for response on edgex/device/command/request/device-virtual/Test-Device/Virtual_GenerateDeviceValue_INT16_RW/get/e6e8a2f4-eb14-4649-9e2b-175247911369 topic"

level=ERROR ts=2023-02-14T08:54:54.13365617Z app=core-command source=external.go:159 msg="Failed to send DeviceCommand request with internal MessageBus: timed out waiting for response on edgex/device/command/request/device-virtual/Test-Device/Virtual_GenerateDeviceValue_INT16_RW/set/e6e8a2f4-eb14-4649-9e2b-175247911369 topic"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@cherrycl , this issue is fixed by https://github.com/edgexfoundry/edgex-go/pull/4348
