### ISSUE TITLE
Need Additional REST APIs in metadata service to get device or device profile count

### ISSUE THREAD

**Issue by AnilChoudhury-Eaton** [edgexfoundry/edgex-go#4390]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
EdgeX Metadata
This request is to add a new REST API which can just return the number of devices or device profiles present in the meta-data service.

### Description [**REQUIRED**]
Currently, EdgeX Metadata service REST API does not provide an API even in the 2.3.0 release, to fetch device and device profile count.
When we keep a huge number (maybe 100s) of devices/device profiles in metadata, it may be difficult to understand and display in UI efficiently.
We would prefer to display the total but only fetch and display a limited and fetch more if a user is interested.
This will reduce the REST load on buses on slow connections. Also, limited reads will improve all page content load faster.

### Describe the solution you'd like
/device/count
/deviceprofile/count

Maybe these queries may be improved more with the same filter parameters used for /device/all or /deviceprofile/all
.

### Describe alternatives you've considered
we have to call /device/all and /device profile/all, all the time to fetch all and then use UI filters to only display a few and cache them UI unnecessarily. This also makes UI heavier and slower.

**Comment by cloudxxx8** [comment]
it should be easy to implement like we did in /event/count

by the way, the current workaround is to call the `/device/all` API with `?limit=1` query parameter, and you can get the `totalCount` in the response payload.
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.3.0#/default/get_device_all

**Comment by cloudxxx8** [comment]
> The v2.3 version of Core-Metadata's Swagger APIs shows a response field for both of these GET device/all and deviceprofile/all APIs: "totalCount": 3, The schemas unhelpfully describe this as totalCount | integerThe total count of all multi instances.
> 
> I think this does what you want: request "all" with limit = 1, and see what this field tells you. I tested on our v2.0 core-metadata but don't get this field in the response.

this field was added in v2.1.  are you using v2.0 or v2.3?

**Comment by AnilChoudhury-Eaton** [comment]
> the current workaround is to call the `/device/all` API with `?limit=1` query parameter, and you can get the `totalCount` in the response payload.

We are using 2.0.0 right now.
But thanks for the suggestion to use a device limit of 1.
