### ISSUE TITLE
Makefile improvements

### ISSUE THREAD

**Issue by feclare** [edgexfoundry/edgex-go#44]
I have found a way to compile all the go code in the repository and to generate all the microservices. The only problem is that the executables are stored in $GOPATH/bin

```
go install ./...
```
So we will need to move them afterwards to other location. 
We could use something like:
```
build:
    go install ./...
    mv $GOPATH/bin/core-data $DESTDIR
...
    mv $GOPATH/bin/export-distro $DESTDIR
```
Removing the build_microservices target. Opinions?

**Comment by drasko** [comment]
@feclare please refer to https://github.com/edgexfoundry/edgex-go/issues/26 and also https://github.com/edgexfoundry/edgex-go/issues/25 because I expect problems here with `go install`

**Comment by jpwhitemn** [comment]
Makefile issues and changes to be discussed in 3/22 Core WG meeting.

**Comment by feclare** [comment]
The only remaining issue is where should the executables be generated. I know @drasko likes to have them in a different directory like `edgex-go/build`. With the configuration files sharing the same filenames each microservice needs to be in a different directory, if we want to have this I should use something like:
```
edgex-go/build/core-data/ 
edgex-go/build/core-data/core-data
edgex-go/build/core-data/res/configuration.toml
edgex-go/build/core-metadata/ 
edgex-go/build/core-metadata/core-metadata
edgex-go/build/core-metadata/res/configuration.toml
```
Any other alternative?

**Comment by drasko** [comment]
@feclare I propose that we leave it for now as is. We'll see later.

If you are OK with this, please close this issue.
