### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by SavantEVO** [edgexfoundry/edgex-go#4423]
I try to use this repo https://github.com/edgexfoundry/edgex-go
but when I used docker-compose up I got an Error shown below. Please give advise me on how to fix that! Thanks you so much
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/109493900/223804687-530131b0-4d0a-4872-b065-60efa7a73996.png">

**Comment by cloudxxx8** [comment]
please provide more information about your question.
which branch? which docker-compose file?
it's probably the wrong volume settings in your docker-compose file according to the error message.

**Comment by cloudxxx8** [comment]
close this issue due to no response
