### ISSUE TITLE
Addon services unable to access common config

### ISSUE THREAD

**Issue by vli11** [edgexfoundry/edgex-go#4437]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
Any addon service that doesn't have the permissions built-in by default, example: device-mqtt

### Is this a regression?
No since common config is new

### Description and Minimal Reproduction [**REQUIRED**]
run compose-builder in secure mode with device mqtt: 
$ make run mqtt-broker ds-mqtt

## 🔥 Exception or Error
```
level=ERROR ts=2023-03-13T16:19:46.251975009Z app=device-mqtt source=bootstrap.go:48 msg="failed to create provider for /all-services: failed to get Configuration Provider (consul) access token: HTTP response with status code 400, message: failed to generate Consul token using [device-mqtt]: {\"errors\":[\"role \\\"device-mqtt\\\" not found\"]}\n"
```

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by lenny-intel** [comment]
I am unable to recreate this when pulled latest secure mod images.
