### ISSUE TITLE
Consume loading config from YAML and convert config TOML files to YAML

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#4452]
# 🚀 Refactor

### Relevant Package [**REQUIRED**]

 This feature request is for Configuration files

### Description [**REQUIRED**]
Configuration files are now expected to be in YAML format

### Describe the solution you'd like
Consume go-mod-bootstrap that loads config from YAML and convert all config TOML files to YAML

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/edgex-go/pull/4456
