### ISSUE TITLE
Request timeout when posting device with non-existent device-service

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4470]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Metadata

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX by [compose file](https://github.com/edgexfoundry/edgex-compose/blob/d3abd814d7ee08bb719e32901cdf7f306f4b71a8/docker-compose-no-secty.yml)
2. Post device and the serviceName is not created, example as below
```
[
    {
      "device":{
         "origin":1471806386919,
         "name":"Test-Device",
         "description":"Test-Device",
         "adminState":"UNLOCKED",
         "operatingState":"UP",
         "protocols":{
            "other":{
               "Address":"simple01",
               "Port":"300"
            }
         },
         "labels":[
            "device-sample"
         ],
         "location":"{lat:45.45,long:47.80}",
         "serviceName":"device-test",
         "profileName":"Random-UnsignedInteger-Device"
      },
      "apiVersion":"v2"
   }
]
```

## 🔥 Exception or Error
<pre><code>
level=ERROR ts=2023-03-22T03:40:55.473828137Z app=core-metadata source=device.go:67 X-Correlation-ID=295c0f4b-38d6-40e2-9e34-4778014f6afd msg="Error sending request to topic 'edgex/device-test/validate/device' -> timed out waiting for response on edgex/response/device-test/6e3c9eec-d3cc-4837-8dd1-e93fc552c3a3 topic"
level=ERROR ts=2023-03-22T03:40:55.474047843Z app=core-metadata source=encoding.go:32 msg="Error encoding the data: http: Handler timeout"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by weichou1229** [comment]
I thought it was the same issue that opened at the go-mod-messaging repo. https://github.com/edgexfoundry/go-mod-messaging/issues/227

**Comment by lenny-intel** [comment]
@weichou1229 , no this is different and is expected behavior now.
If the validation request is sent to a device service that isn't running it will expectedly timeout.

**Comment by cherrycl** [comment]
Just found current behavior is if the request contains multiple requests inside which only one request uses not running device-service, then the response status code returns 503, not 207 with individual response status.

I was wondering if it is more reasonable to return 207 outside level with 503 inside for the not running device-service request.

**Comment by cloudxxx8** [comment]
@weichou1229 please help create a fix in core-metadata to return 207 instead of 503

**Comment by cloudxxx8** [comment]
@cherrycl please open a different bug for this

**Comment by cherrycl** [comment]
> Just found current behavior is if the request contains multiple requests inside which only one request uses not running device-service, then the response status code returns 503, not 207 with individual response status.
> 
> I was wondering if it is more reasonable to return 207 outside level with 503 inside for the not running device-service request.

Opened #4478 for this issue.
