### ISSUE TITLE
Got "Unauthorized" error when executing interval action with security enabled

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4479]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Scheduler

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy security EdgeX with [compose file](https://github.com/edgexfoundry/edgex-compose/blob/d3abd814d7ee08bb719e32901cdf7f306f4b71a8/docker-compose.yml)
2. Create an Interval with following request body
```
POST https://localhost:8443/support-scheduler/api/v2/interval with JWT token
[
   {
      "interval":{
         "name":"interval_1679737508110",
         "start":"20230325T094508",
         "interval":"30s"
      },
      "apiVersion":"v2"
   }
]
```
3. Create an Interval Action with the following request body
```
POST https://localhost:8443/support-scheduler/api/v2/intervalaction with JWT token
[
   {
      "action":{
         "name":"intervalAction_1679737508231",
         "intervalName":"interval_1679737508110",
         "address":{
            "type":"REST",
            "host":"edgex-core-data",
            "port":59880,
            "httpMethod":"DELETE",
            "path":"/api/v2/event/age/0"
         },
         "AdminState":"UNLOCKED"
      },
      "apiVersion":"v2"
   }
]
```
4. Sleep 30 seconds

## 🔥 Exception or Error
Event didn't clean up and found the following error on support-scheduler logs.
<pre><code>
level=ERROR ts=2023-03-25T09:51:38.341410182Z app=support-scheduler source=manager.go:154 msg="fail to send request with RESTAddress, err: request failed, status code: 401, err: Unauthorized\n"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@bnevis-i support-scheduler currently doesn't support the REST call with JWT authentication.  Are you going to fix it or I can assign my team member to work on it?

**Comment by lenny-intel** [comment]
@cloudxxx8 , it was added here: https://github.com/edgexfoundry/edgex-go/pull/4419

**Comment by bnevis-i** [comment]
https://github.com/edgexfoundry/edgex-docs/pull/1001
