### ISSUE TITLE
California -- Incorrect Init Service Keys. Change CleanupDefaultAge Data Type

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#449]
Fix init.go (for notifications service) to use internal.SupportNotificationsServiceKey instead of conf.ServiceName. Modify CleanupDefaultAge (in ConfigurationStruct for notifications and elsewhere) from type int64 to int. Separately, and unrelated to preceding items, remove an unwarranted check (in subscriptionHandler()) for whether max limit or results-returned has been exceeded, which would otherwise throw a redundant HTTP 413 error aka http.StatusRequestEntityTooLarge error.

**Comment by akramtexas** [comment]
Fixed submitted and PR created: [PR #448](https://github.com/edgexfoundry/edgex-go/pull/448)
