### ISSUE TITLE
bug: simpler form of ADD_KNOWN_SECRETS environment variable doesn't work

### ISSUE THREAD

**Issue by ejlee3** [edgexfoundry/edgex-go#4493]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
The bug is likely in the parsing of the know secrets in EdgeX Secret Store Setup.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]

Run EdgeX in secure mode - but change the secretstore-setup in the docker compose file to a combined rule like the example below

```
 ADD_KNOWN_SECRETS: redisdb[app-rules-engine, device-rest, device-virtual]
```

## 🔥 Exception or Error
<pre><code>
level=ERROR ts=2023-04-04T20:44:51.956545097Z app=security-secretstore-setup source=init.go:345 msg="invalid specification for ADD_KNOWN_SECRETS environment vaiable: Service list for 'redisdb' missing closing ']'"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Linux - Ubuntu 20.04
Docker 23.0.1
Docker Compose 2.16.0

**EdgeX Version [**REQUIRED**]:**
2.3 - Levski

**Anything else relevant?**

**Comment by lenny-intel** [comment]
Moving issue to edgex-docs
