### ISSUE TITLE
Failed to start support services with delayed-start mode

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4507]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support services

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
Deploy EdgeX with attached compose file which enabled delayed-start mode for support service, device-virtual and device-modbus.
[docker-compose.yml.zip](https://github.com/edgexfoundry/edgex-go/files/11197731/docker-compose.yml.zip)

## 🔥 Exception or Error
device-virtual and device-modbus started successfully with delayed-start mode, but support services not
Support services logs just stayed on the below and no next.
<pre><code>
level=INFO ts=2023-04-11T07:25:52.733587527Z app=support-notifications source=secret.go:65 msg="Creating SecretClient"
level=INFO ts=2023-04-11T07:25:52.736665941Z app=support-notifications source=variables.go:457 msg="Variables override of 'SecretStore/RuntimeTokenProvider/Enabled' by environment variable: SECRETSTORE_RUNTIMETOKENPROVIDER_ENABLED=true"
level=INFO ts=2023-04-11T07:25:52.737948554Z app=support-notifications source=variables.go:457 msg="Variables override of 'SecretStore/Host' by environment variable: SECRETSTORE_HOST=edgex-vault"
level=INFO ts=2023-04-11T07:25:52.737998133Z app=support-notifications source=variables.go:457 msg="Variables override of 'SecretStore/RuntimeTokenProvider/Host' by environment variable: SECRETSTORE_RUNTIMETOKENPROVIDER_HOST=edgex-security-spiffe-token-provider"
level=INFO ts=2023-04-11T07:25:52.738077843Z app=support-notifications source=secret.go:159 msg="SecretStore information created with 3 overrides applied"
level=INFO ts=2023-04-11T07:25:52.739677589Z app=support-notifications source=secret.go:75 msg="Reading secret store configuration and authentication token"
level=INFO ts=2023-04-11T07:25:52.739717746Z app=support-notifications source=secret.go:196 msg="runtime token provider enabled"
level=INFO ts=2023-04-11T07:25:52.739737279Z app=support-notifications source=methods.go:138 msg="using Unix Domain Socket at unix:///tmp/edgex/secrets/spiffe/public/api.sock"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu22 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**
Related to this issue in edgex-compose https://github.com/edgexfoundry/edgex-compose/issues/364 issue fix

**Comment by lenny-intel** [comment]
@bnevis-i , @jim-wang-intel , FYI

**Comment by jim-wang-intel** [comment]
Debugged with @bnevis-i  and found out there will be two changes needed: one in edgex-go configure script and compose make file in edgex-compose to fix this issue. I'll create another issue in edgex-compose.

**Comment by bnevis-i** [comment]
Note that a a result of this change, the support services will ALWAYS start in delayed-start mode when delayed-start is passed on the docker-compose makefile.
