### ISSUE TITLE
Got incorrect maximum and minimum when creating profile

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4512]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Metadata

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with [compose file](https://raw.githubusercontent.com/edgexfoundry/edgex-compose/main/docker-compose-no-secty.yml)
2. Upload profile by attached files
[profiles.zip](https://github.com/edgexfoundry/edgex-go/files/11217909/profiles.zip)

3. Query the uploaded profiles and verify the minimum and maximum value

## 🔥 Exception or Error
Upload file for Int64:
"minimum": `-9223372036854775808`
"maximum": `9223372036854775807 `
Actual return:
"minimum":`-9223372036854776000`
"maximum":`9223372036854776000`

Upload file for Uint64:
"maximum": `18446744073709551615`
Actual return:
"maximum":`18446744073709552000`

## 🌍  Your Environment
**Deployment Environment:** Ubuntu22 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by jinlinGuan** [comment]
The precision loss is expected when converting `int64`/`uint64` between `float64` in Go. We wouldn't fix this.
