### ISSUE TITLE
Security Spire Services do not start up properly

### ISSUE THREAD

**Issue by ejlee3** [edgexfoundry/edgex-go#4526]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
- security-spire-server (most likely)

### Is this a regression?

 Yes, the previous version in which this bug was not present was:

### Description and Minimal Reproduction [**REQUIRED**]
1. use the latest edgex-compose - run `make pull`
2. run `make run delayed-start ds-virtual ds-modbus`
3. wait for services to come up and check the listed service logs

## 🔥 Exception or Error

The error in `edgex-security-spire-server` is:
```
time="2023-04-25T18:35:17Z" level=error msg="Unknown configuration detected" keys="default_jwt_svid_ttl,default_x509_svid_ttl" section=server
unknown configuration detected
```
The error in `edgex-security-spire-agent` is:
```
Error: connection error: desc = "transport: error while dialing: dial unix /tmp/edgex/secrets/spiffe/private/api.sock: connect: no such file or directory"
```
The error in `edgex-security-spire-config` is: a loop `waiting for /tmp/edgex/secrets/spiffe/private/api.sock`

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
latest - main 

**Anything else relevant?**

**Comment by bnevis-i** [comment]
This is related to https://github.com/edgexfoundry/ci-build-images/pull/206 which was merged yesterday.

Please do

make clean_docker_base docker_base to get the new spire engine and everything should start working again.

**Comment by bnevis-i** [comment]
This is fixed.  Root cause is that  https://github.com/edgexfoundry/ci-build-images/pull/206 needed to be committed 15-30 minutes before https://github.com/edgexfoundry/edgex-go/pull/4521.  As a result, stale images were pushed to nexus.
