### ISSUE TITLE
Add Support-Notifications to "make run"

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#456]
When executing the `make run` command line, the support-notifications service is not currently started along with the other services. We need to make this so.

Please also ensure that the `make run_docker` command starts the relevant container.

**Comment by akramtexas** [comment]
- @tsconn23 My (initial) impression of `support-notifications service` was as a standalone service... But making this service start _along_ with the other services makes sense. 
- I will make this happen, along with noted point on the `make run_docker` command.

**Comment by tsconn23** [comment]
@akramtexas Well, it is a stand-alone service in the sense that it's a deployable unit. Wouldn't the service need to participate in the overall eco-system in any case? If so, something needs to start it.

**Comment by akramtexas** [comment]
@tsconn23 Agreed: It is a service which needs to _participate_ in the overall ecosystem. You're right: Having it start _along_ with the other services is the way to manage it's lifecycle 💯

**Comment by akramtexas** [comment]
@tsconn23 The following PR has been submitted to address this: [PR #460](https://github.com/edgexfoundry/edgex-go/pull/460) - Good catch, thanks!
