### ISSUE TITLE
Fail to get spiffe-token-provider token for deplayed-start services

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4577]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: deplayed-start services

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Generate deplayed-start compose file with command `make gen deplayed-start ds-virtual` on edgex-compose repo. 
2. Execute `docker compose up -d`
3. Found error on services, device-virtual, support-notifications and support-scheduler 

## 🔥 Exception or Error
<pre><code>
level=INFO ts=2023-05-24T07:07:07.321975901Z app=device-virtual source=secret.go:79 msg="Reading secret store configuration and authentication token"
level=INFO ts=2023-05-24T07:07:07.322029647Z app=device-virtual source=secret.go:210 msg="runtime token provider enabled"
level=INFO ts=2023-05-24T07:07:07.322039323Z app=device-virtual source=methods.go:138 msg="using Unix Domain Socket at unix:///tmp/edgex/secrets/spiffe/public/api.sock"
level=INFO ts=2023-05-24T07:07:07.391092447Z app=device-virtual source=methods.go:150 msg="workload got X509 source"
level=WARN ts=2023-05-24T07:07:07.41341202Z app=device-virtual source=secret.go:132 msg="Retryable failure while creating SecretClient: failed to get spiffe-token-provider gettoken api call, status code = 404 "

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 2204 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@bnevis-i this issue failed the TAF tests, but it worked fine before yesterday.
could you please help check whether this PR failed anything?
https://github.com/edgexfoundry/edgex-go/pull/4573/files

**Comment by bnevis-i** [comment]
I just finished regressing the change.  Indeed this is the fix.

**Comment by cherrycl** [comment]
Issue was fixed.
