### ISSUE TITLE
make get-token parse error

### ISSUE THREAD

**Issue by ewenchoon** [edgexfoundry/edgex-go#4579]
running EdgeX in Docker on MacOS and trying to get token using make get-token but getting parse error.
been searching for solution but no luck. please advise.

parse error: Invalid numeric literal at line 1, column 12
                                                         ERROR
make: *** [get-token] Error 1

**Comment by cloudxxx8** [comment]
Please describe your question with more information?
Did you run it in edgex-compose?  Which branch (version) you are using?
What is the machine architecture, x86 or arm64?  Did you run any other command?

**Comment by ewenchoon** [comment]
> Please describe your question with more information? Did you run it in edgex-compose? Which branch (version) you are using? What is the machine architecture, x86 or arm64? Did you run any other command?

thanks for replying. downloaded the zip file under main branch. Using Docker on MacOs Ventura.
Run the command in Terminal, the last command I run before make get-token was docker-compose ps.
I found that edgex-security-proxy-setup always exited in Docker too.

Please advice. thanks.
<img width="466" alt="image" src="https://github.com/edgexfoundry/edgex-go/assets/17289618/e9d560cb-1b4b-48da-a4de-09743e0dfac1">

**Comment by cloudxxx8** [comment]
Which repository you are using, edgex-compose?  What is the machine architecture, x86 or arm64?
Please provide all the context.  If you ran docker-compose ps, you should also run docker-compose up or others before.
By the way, don't use the main branch, because it's under development.  Please use the released version, such as levksi (2.3.0).

**Comment by ewenchoon** [comment]
> Which repository you are using, edgex-compose? What is the machine architecture, x86 or arm64? Please provide all the context. If you ran docker-compose ps, you should also run docker-compose up or others before. By the way, don't use the main branch, because it's under development. Please use the released version, such as levksi (2.3.0).

I tried levski and make run arm64, but edgex-security-bootstrapper and edgex-ui-go  just keep showing starting.
<img width="560" alt="image" src="https://github.com/edgexfoundry/edgex-go/assets/17289618/30d4a48a-f3e0-4c78-ae04-dd0b77b50042">

**Comment by cloudxxx8** [comment]
you could check the log to see what goes wrong

**Comment by bnevis-i** [comment]
`make get-token`  just calls a shell script.  Please run the steps in the shell script individually and show the output of each step (sanitize the tokens produced).  Also please specify which EdgeX version you are using.

**Comment by bnevis-i** [comment]
Awaiting response from @ewenchoon.  Will close issue if response not received.

**Comment by farshidtz** [comment]
Isn't this because the current configuration of Nginx writes error responses in raw text instead of JSON?

**Comment by farshidtz** [comment]
> > Isn't this because the current configuration of Nginx writes error responses in raw text instead of JSON?
> 
> Yes, it is likely choking on the input to `jq`. But unless the reporter can send the raw output, it's hard to tell what's going on.

Correct, but the parsing failure is making it hard to identify the underlying issue. The reported could most probably figure it out if the payload was parsed correctly. It was easy to hit such errors by misconfiguring the snaps.

We could either make Nginx serialize in JSON (as in EdgeX v2), or make `get-token` parse the HTTP response depending on the `Content-Type` header.

**Comment by ewenchoon** [comment]
thanks for the reply. I will try the solution as suggested and feedback. thanks.

**Comment by lenny-intel** [comment]
closing as answered
