### ISSUE TITLE
Add POST /secret API for core-command

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#4585]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-command

### Description [**REQUIRED**]
From Levski release, core-command service adds support for an external MQTT connection: https://docs.edgexfoundry.org/3.0/microservices/core/command/Ch-Command/#commands-via-messaging
In some cases, credentials and/or certificates are required to establish a connection.

### Describe the solution you'd like
Implement a new API:
POST /secret

**Comment by cloudxxx8** [comment]
@lenny-intel may we implement this to resolve https://github.com/edgexfoundry/edgex-docs/issues/1034?

**Comment by lenny-intel** [comment]
> @lenny-intel may we implement this to resolve [edgexfoundry/edgex-docs#1034](https://github.com/edgexfoundry/edgex-docs/issues/1034)?

@cloudxxx8 , will have to go into 3.1 
Note that all services have the ability to seed secrets vis Secrets File. Please use this option in https://github.com/edgexfoundry/edgex-docs/issues/1034.
https://docs.edgexfoundry.org/3.0/security/SeedingServiceSecrets/#secrets-file

**Comment by cloudxxx8** [comment]
this issue will be resolved once https://github.com/edgexfoundry/go-mod-bootstrap/issues/478 is implemented

**Comment by lenny-intel** [comment]
@cloudxxx8 , can this be closed since https://github.com/edgexfoundry/go-mod-bootstrap/issues/478 is completed?

**Comment by cloudxxx8** [comment]
yes, we have applied it to edgex-go, and Cherry created the new tests for it
https://github.com/edgexfoundry/edgex-taf/pull/862
