### ISSUE TITLE
CPU increases abnormal when creating interval with us/ns unit

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4586]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-scheduler

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX
2. Create interval with us/ns
```
POST http://localhost:59861/api/v3/interval
[
   {
      "interval":{
         "name":"interval_1679737508110",
         "start":"20230605T094508",
         "interval":"1us"
      },
      "apiVersion":"v3"
   }
]
```

## 🔥 Exception or Error
<pre><code>
Status code: 503
Response body: HTTP request timeout
CPU: more than 200% (view CPU by "docker stats")

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 22.04 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cherrycl** [comment]
No sure if it is similar with [device-sdk-go issue #1447](https://github.com/edgexfoundry/device-sdk-go/issues/1447).
When creating device and set autoevent interval to us caused the device-service memory increases abnormally.

**Comment by farshidtz** [comment]
I agree that it is not a breaking change if it is already broken.
I think even milliseconds should not be allowed when setting an interval which involves making HTTP calls to another service. The networking and computation could easily exceed the interval and lead to significant resource usage.

**Comment by cloudxxx8** [comment]
@farshidtz that's a good idea.  we should just define a reasonable smallest allowed duration.  auto event doesn't involve HTTP call, and scheduler potentially allow other intervalAction type in the future.  Maybe 10ms is a candidate?

**Comment by lenny-intel** [comment]
@cloudxxx8 , @farshidtz , I like this approach. Would 1ms be appropriate for AutoEvents and 10ms for IntervalActions?

**Comment by cloudxxx8** [comment]
@farshidtz in the discussion of Core WG June-21-2023, we feel if we round the value to the smallest allowed duration, users won't be able to notice that and the services will work unepected to them.  As a result, we prefer to return an error if the value is less than the minimize value.  Is it ok with you?

**Comment by farshidtz** [comment]
@cloudxxx8 If someone has used those small intervals on a fast machine and the application works for them, that's great and according to their expectation. Suddenly receiving errors definitely won't be what they expect.

If a new deployment is taking place, the user would read the documentation about the rounding behaviour when setting a value. There should not be any surprises. To make it clearer the value rounding can be logged as a warning.

Nevertheless, I am fine with throwing an error if you believe no one has used a small interval due to the unexpectedly high CPU usage. As mentioned, it is not a breaking change if it is already broken.

**Comment by lenny-intel** [comment]
@cloudxxx8, @farshidtz has a good point on systems that can handle the smaller intervals. IMO, we should make this configurable. Something like `EnforceMinIntervals` which defaults  to false (for non-backwards breaking). Those that have slower machines can enable it. Thoughts?

**Comment by lenny-intel** [comment]
@cloudxxx8 , doesn't this ability to handle lower intervals depend on the systems networking capability, MessageBus performance and the quality of the network (if going off system)?

**Comment by jumpingliu** [comment]
According to the discussion in the Core WG meeting on June 27 2023, we will put the warning msg in the log if the interval is smaller than suggested minimal allowable value (10ms for intervalAction and 1ms for autoEvent).

Hi @farshidtz , so it won't be the breaking change anymore, is that okay for you?

**Comment by farshidtz** [comment]
@jumpingliu Sound good. Thanks for letting me know.
