### ISSUE TITLE
Interval not being triggered because of different time zone

### ISSUE THREAD

**Issue by jackchenjc** [edgexfoundry/edgex-go#4594]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-scheduler

### Is this a regression?

  No

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX.
2. Create interval with start time set to current time.
<pre><code>POST http://localhost:59861/api/v3/interval
[
   {
      "interval":{
         "name":"interval_1679737508110",
         "start":"20230619T080000",
         "interval":"5s"
      },
      "apiVersion":"v3"
   }
]
</code></pre>

Found that the new created interval was not being triggered if the start time (20230619T080000 UTC+8 based on my location) is later then the actual UTC time (which is 20230619T000000 in this case).

The `support-scheduler` service should compare the interval start time with current time in local time zone.

## 🔥 Exception or Error
n/a

## 🌍  Your Environment
**Deployment Environment:**
macOS

**EdgeX Version [**REQUIRED**]:**
main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@lenny-intel from my point of view, it's a real bug.  Users create interval with Unix Timestamp (int64) calculated by their local time, and they expect it can work with the local time.  Our document doesn't mention it's UTC.  
We should pay attention on any timestamp related cases in the future. If their machine is using UTC+0,  everything would still work fine.
I just added to the Minnesota known bugs.

**Comment by cloudxxx8** [comment]
Oh, my bad, it's not Unix Timestamp.
Either way, since our document doesnt' state it's UTC, no one should expect it's UTC unless their timezone is UTC.
