### ISSUE TITLE
Scan and replace use of pkg/errors module with errors

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#4602]
https://github.com/pkg/errors was archived in 2021
https://blog.dharnitski.com/2019/09/09/go-errors-are-not-pkg-errors/

**Comment by cloudxxx8** [comment]
We should review all the edgex repositories for this replacement

**Comment by jackchenjc** [comment]
The `pkg/errors` module has already been removed from edgex-go in https://github.com/edgexfoundry/edgex-go/pull/3492.
