### ISSUE TITLE
device's property "notify" not work

### ISSUE THREAD

**Issue by edgego** [edgexfoundry/edgex-go#4609]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
Data, Metadata, Command

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
NO

### Description and Minimal Reproduction [**REQUIRED**]
When create a new deivce with  property "notify", set notify to true, then can create the device. But when query this device, not get the  property "notify":

packet to create device:

[{  "apiVersion": "v2","device": { "name":"mod7","description":"","operatingState":"UP","adminState":"UNLOCKED","serviceName":"device-modbus","profileName":"Test-Device-Modbus-Profile","location":""**_,"notify":true_**,"labels":[ ] ,"protocols": {"modbus-tcp": { "Address" : "192.168.1.244" , "Port" : "1502" , "UnitID" : "0" , "Timeout" : "0" , "IdleTimeout" : "0" }},"autoEvents": []}}]

response packet:
[{"apiVersion":"v2","statusCode":201,"id":"caa6996f-9d22-496e-b2c2-1f9b0e30c6be"}]

 Then query the device with name mod7:

{"apiVersion":"v2","statusCode":200,"totalCount":7,"devices":[**_{"created":1689494055765,"modified":1689494055765,"id":"caa6996f-9d22-496e-b2c2-1f9b0e30c6be","name":"mod7","adminState":"UNLOCKED","operatingState":"UP","location":"","serviceName":"device-modbus","profileName":"Test-Device-Modbus-Profile","protocols":{"modbus-tcp":{"Address":"192.168.1.244","IdleTimeout":"0","Port":"1502","Timeout":"0","UnitID":"0"}}},_**{"created":1689038824930,"modified":1689493830760,"id":"4096d660-6d08-436d-a928-228fd4261711","name":"mod1","description":"modbus tcp","adminState":"UNLOCKED","operatingState":"UP","lastConnected":1689425014240,"labels":["Templated"],"location":"(22.71285645414127,113.95019531250001)","serviceName":"device-modbus","profileName":"Test-Device-Modbus-Profile","autoEvents":[{"interval":"5s","onChange":false,"sourceName":"RoomTemperature"}],"protocols":{"modbus-tcp":{"Address":"192.168.1.244","IdleTimeout":"0","Port":"1502","Timeout":"0","UnitID":"1"}}},{"created":1689424802633,"modified":1689474161406,"id":"0694a286-054b-4b60-af84-90b2d5f2c6ca","name":"mod5","description":"demo","adminState":"UNLOCKED","operatingState":"UP","lastConnected":1689424982655,"labels":["Templated"],"location":"(22.667244265664948,114.12597656250001)","serviceName":"device-modbus","profileName":"Test-Device-Modbus-Profile","autoEvents":[{"interval":"1m","onChange":false,"sourceName":"SwitchA"}],"protocols":{"modbus-tcp":{"Address":"192.168.1.244","IdleTimeout":"0","Port":"1502","Timeout":"0","UnitID":"1"}}},{"created":1689393580862,"modified":1689425004204,"id":"804d8d8f-1d3d-4a36-8432-989abd6503a7","name":"mod3","description":"demo","adminState":"UNLOCKED","operatingState":"UP","lastConnected":1689425004200,"labels":["Templated"],"location":"(22.667244265664948,114.12597656250001)","serviceName":"device-modbus","profileName":"Test-Device-Modbus-Profile","autoEvents":[{"interval":"1m","onChange":false,"sourceName":"SwitchA"}],"protocols":{"modbus-tcp":{"Address":"192.168.1.244","IdleTimeout":"0","Port":"1502","Timeout":"0","UnitID":"1"}}},{"created":1689424807369,"modified":1689424987399,"id":"069a6d53-49be-4dbc-b188-13bb7c094e59","name":"mod6","description":"demo","adminState":"UNLOCKED","operatingState":"UP","lastConnected":1689424987395,"labels":["Templated"],"location":"(22.667244265664948,114.12597656250001)","serviceName":"device-modbus","profileName":"Test-Device-Modbus-Profile","autoEvents":[{"interval":"1m","onChange":false,"sourceName":"SwitchA"}],"protocols":{"modbus-tcp":{"Address":"192.168.1.244","IdleTimeout":"0","Port":"1502","Timeout":"0","UnitID":"1"}}},{"created":1689424795638,"modified":1689424975672,"id":"744ed3f3-d6ad-4b25-8991-5e3fc0bd4f02","name":"mod4","description":"demo","adminState":"UNLOCKED","operatingState":"UP","lastConnected":1689424975668,"labels":["Templated"],"location":"(22.667244265664948,114.12597656250001)","serviceName":"device-modbus","profileName":"Test-Device-Modbus-Profile","autoEvents":[{"interval":"1m","onChange":false,"sourceName":"SwitchA"}],"protocols":{"modbus-tcp":{"Address":"192.168.1.244","IdleTimeout":"0","Port":"1502","Timeout":"0","UnitID":"1"}}},{"created":1689045814260,"modified":1689424966079,"id":"0e398016-83d3-4c60-bda0-5b1a3c673229","name":"mod2","description":"demo","adminState":"UNLOCKED","operatingState":"UP","lastConnected":1689424966077,"labels":["Templated"],"location":"(22.667244265664948,114.12597656250001)","serviceName":"device-modbus","profileName":"Test-Device-Modbus-Profile","autoEvents":[{"interval":"1m","onChange":false,"sourceName":"SwitchA"}],"protocols":{"modbus-tcp":{"Address":"192.168.1.244","IdleTimeout":"0","Port":"1502","Timeout":"0","UnitID":"1"}}}]}

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
ubuntu
**EdgeX Version [**REQUIRED**]:**

v2.3.0
**Anything else relevant?**

**Comment by cloudxxx8** [comment]
this field is not really used
it was removed long time ago, and we just missed the document update
we totally removed it in v3

**Comment by edgego** [comment]
@cloudxxx8 Thanks for info, Also get same issue for device service. added labels or description for updating device service, when got the updates device service lost labels or description. Could you please check it?

**Comment by cloudxxx8** [comment]
@edgego please open another issue with your update payload
