### ISSUE TITLE
Broken Link in Device Service Documentation

### ISSUE THREAD

**Issue by mkhuluf** [edgexfoundry/edgex-go#462]
Hello,

I was reading through the Device Service Documentation for EdgeX from this Google Drive Link
 (https://docs.google.com/document/d/1aMIQ0kb46VE5eeCpDlaTg8PP29-DBSBTlgeWrv6LuYk/edit#)
and in the ValueDescriptors section, there's a broken link that directs the user to the core-data raml file in edgex-go repo

Broken Link: https://github.com/edgexfoundry/edgex-go/blob/master/core/data/raml/core-data.raml
Actual Link: https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-data.raml

**Comment by mkhuluf** [comment]
I forgot to add that it's also in the Data Transformation section as well

**Comment by mhall119** [comment]
There are also broken links to these files in:
docs/api/Ch-APICoreMetadata.rst
docs/api/Ch-ExamplesAPIDemo.rst
