### ISSUE TITLE
Fail to generate token when username contains '_', like device-modbus_1

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4621]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: security-secretstore-setup

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Generate compose file from [edgex-compose/compose-builder](https://github.com/edgexfoundry/edgex-compose/tree/main/compose-builder) by command `make gen device-modbus`
2. Add new service device-modbus_1 with environment variable `EDGEX_INSTANCE_NAME: 1` to the compose file for testing multiple instances. Also update variables `EDGEX_ADD_KNOWN_SECRETS`, `EDGEX_ADD_SECRETSTORE_TOKENS` and `EDGEX_ADD_REGISTRY_ACL_ROLES`. Attached the compose file for reference. 
[docker-compose.yml.zip](https://github.com/edgexfoundry/edgex-go/files/12236419/docker-compose.yml.zip)
3. Deploy edgex by command `docker compose up -d`

## 🔥 Exception or Error
Failed to start security-secretstore-setup and found the below error
<pre><code>
level=ERROR ts=2023-08-02T05:26:29.91707072Z app=security-file-token-provider source=init.go:85 msg="error occurred generating tokens: invalid username: device-modbus_1"
level=ERROR ts=2023-08-02T05:26:29.918110416Z app=security-secretstore-setup source=init.go:357 msg="token provider failed: /security-file-token-provider terminated with non-zero exit code 1"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 2204 / x86_64

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@bnevis-i for awareness, this issue always happens if the users want to run multiple device service instance with security and consul.
https://docs.edgexfoundry.org/3.0/microservices/device/Ch-DeviceServices/#running-multiple-instances

Do you have any good idea how we can fix it?

**Comment by bnevis-i** [comment]
> @bnevis-i for awareness, this issue always happens if the users want to run multiple device service instance with security and consul. https://docs.edgexfoundry.org/3.0/microservices/device/Ch-DeviceServices/#running-multiple-instances
> 
> Do you have any good idea how we can fix it?

Will have to investigate.  Theoretically, at the Vault level, underscore is valid for a username:
https://developer.hashicorp.com/vault/api-docs/auth/userpass
_The username for the user. Accepted characters: alphanumeric plus "_", "-", "." (underscore, hyphen and period); username cannot begin with a hyphen, nor can it begin or end with a period._

**Comment by bnevis-i** [comment]
@cherrycl I turned out that I explicitly disallowed underscores as part of input validation.  See linked PR for fix.
