### ISSUE TITLE
core-data's api “/event/scrub” block long time when delete events's item more 200000+

### ISSUE THREAD

**Issue by unanao** [edgexfoundry/edgex-go#465]
software:
california

Enviromnet:
The mongo have more 200000+ events ane 200000+ readmings

Get all events costs about 3 minutes
Execute more than 30 minutes only delete 100000+ events and related readings.
CPU is more than 40%
![cpu](https://user-images.githubusercontent.com/2163628/43835482-b20068e8-9b44-11e8-81c5-6f32e669beea.png)

**Comment by jpwhitemn** [comment]
The intention of scrub was to be done periodically by a call in scheduling service - thereby avoiding large blocking scrub.  Having said that, with Go concurrency model, we should have it non block.  Assigning to @tsconn23 and @xmlviking but probably not going to be addressed until Edinburgh release.

**Comment by jpwhitemn** [comment]
@tsconn23 @jduranf - can we either close this issue out or move it to Geneva?  Is it still being worked as it has an Edinburgh label?

**Comment by jduranf** [comment]
If I'm not wrong, as #1286 is closed, this issue also can be closed
