### ISSUE TITLE
Docker build spire service with Golang 1.21

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#4666]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for spire services

### Description [**REQUIRED**]
If we want to build the docker image with Golang 1.21, the spire services require the sipre repo to release a new version with Goland 1.21 changes https://github.com/spiffe/spire/commit/4d96a37b82bb9797ae7ddb13f84b7a4d4fbe4125

**Comment by lenny-intel** [comment]
@weichou1229 , please add details about issue you ran into with building spire services docker images.

**Comment by bnevis-i** [comment]
FYI: The last spire release was on August 16 and the golang 1.21 support was merged on August 21.

**Comment by bnevis-i** [comment]
It looks like the project is now publishing multi-arch (amd64, arm64) docker images on their github.  I may be able to change the build process to download an arch-specific static linked binary instead of recompiling on the fly, or even use the upstream containers.

**Comment by bnevis-i** [comment]
I have a draft PR out here that I am going to regress.

https://github.com/edgexfoundry/edgex-go/pull/4667

If this works, we can remove spire server and agent from the build cache as well as from local build.

**Comment by bnevis-i** [comment]
Reassigning to Ernesto, who will be making a corresponding change in ci-build-images which should button this one up.

**Comment by ernestojeda** [comment]
Latest v1.21 golang base image now uses pre-built spire-server and spire-agent

See:
https://github.com/edgexfoundry/ci-build-images/blob/golang-1.21/Dockerfile#L26-L27
