### ISSUE TITLE
Name field escape configurable

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#4673]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core services and device service

### Description [**REQUIRED**]
The Url escape function should be configurable.

1. Add config for all services, default is false,
  ```
  all-services:
      Service:
          EnableNameFieldEscape: false
  ```
2. Skip the escape function if EnableNameFieldEscape is false

Refer to https://github.com/edgexfoundry/edgex-go/issues/4053

**Comment by cloudxxx8** [comment]
rename to `EnableNameFieldEscape` and add the following comments
`// The name field escape could allow the system to use special or Chinese characters in the different name fields, including device, profile, and so on.  If the EnableNameFieldEscape is false, some special characters might cause system error.
