### ISSUE TITLE
Separate Common API from each service's swagger in to common swagger

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#4697]
# 📚 Docs 

### Description [**REQUIRED**]

Unable to show just common swagger on this page https://docs.edgexfoundry.org/3.1/api/Ch-APIIntroduction/ since they are embedded in each services swagger file. Suggest moving the common API swagger to openapi/v3/common/yaml which then can be referenced appropriately from the edgeX Docs.

### What's the affected URL? [**REQUIRED**]
 Swagger files

**Comment by jumpingliu** [comment]
per the WG on Oct 24, we've decided not to do this.
