### ISSUE TITLE
message connected twice

### ISSUE THREAD

**Issue by sixhj** [edgexfoundry/edgex-go#4708]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
Trigger creation fails when using nats

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

vel=INFO ts=2023-10-25T09:12:56.2696683Z app=app-new-service source=clients.go:164 msg="Using REST for 'core-data' clients @ http://localhost:59880"                                         
level=INFO ts=2023-10-25T09:12:56.2696683Z app=app-new-service source=clients.go:164 msg="Using REST for 'core-metadata' clients @ http://localhost:59881"                                     
level=INFO ts=2023-10-25T09:12:56.2696683Z app=app-new-service source=clients.go:164 msg="Using REST for 'core-command' clients @ http://localhost:59882"                                      
level=INFO ts=2023-10-25T09:12:56.2696683Z app=app-new-service source=version.go:66 msg="Skipping core service version compatibility check"                                                    
level=INFO ts=2023-10-25T09:12:56.2696683Z app=app-new-service source=metrics.go:64 msg="0 specified for metrics reporting interval. Setting to max duration to effectively disable reporting."
level=INFO ts=2023-10-25T09:12:56.2701866Z app=app-new-service source=manager.go:128 msg="Metrics Manager started with a report interval of 2562047h47m16.854775807s"                          
level=INFO ts=2023-10-25T09:12:56.2701866Z app=app-new-service source=bootstrap.go:251 msg="SecuritySecretsStored metric registered and will be reported (if enabled)"                         
level=INFO ts=2023-10-25T09:12:56.2701866Z app=app-new-service source=bootstrap.go:251 msg="SecuritySecretsRequested metric registered and will be reported (if enabled)"                      
level=INFO ts=2023-10-25T09:12:56.2701866Z app=app-new-service source=server.go:88 msg="Registering standard routes..."                                                                        
level=INFO ts=2023-10-25T09:12:56.2701866Z app=app-new-service source=configupdates.go:48 msg="Waiting for App Service configuration updates..."                                               
level=INFO ts=2023-10-25T09:12:56.270698Z app=app-new-service source=service.go:554 msg="Service started in: 951.6757ms"                                                                       
level=INFO ts=2023-10-25T09:12:56.270698Z app=app-new-service source=config.go:487 msg="Checking if custom configuration ('AppCustom') exists in Configuration Provider"
level=INFO ts=2023-10-25T09:12:56.2732891Z app=app-new-service source=config.go:640 msg="Loading configuration file from res\\configuration.yaml"
level=INFO ts=2023-10-25T09:12:56.2749848Z app=app-new-service source=config.go:526 msg="Loaded custom configuration from File (0 envVars overrides applied)"
level=INFO ts=2023-10-25T09:12:56.5005102Z app=app-new-service source=config.go:543 msg="Custom Config loaded from file and pushed to Configuration Provider (overwritten)"
level=INFO ts=2023-10-25T09:12:56.5005102Z app=app-new-service source=config.go:601 msg="Watching for custom configuration changes has started for `AppCustom`"
level=INFO ts=2023-10-25T09:12:56.5005102Z app=app-new-service source=runtime.go:197 msg="PipelineMessagesProcessed-default-pipeline metric has been registered and will be reported (if enabled)"
level=INFO ts=2023-10-25T09:12:56.5005102Z app=app-new-service source=runtime.go:197 msg="PipelineMessageProcessingTime-default-pipeline metric has been registered and will be reported (if enabled)"
level=INFO ts=2023-10-25T09:12:56.5010391Z app=app-new-service source=runtime.go:197 msg="PipelineProcessingErrors-default-pipeline metric has been registered and will be reported (if enabled)"
level=INFO ts=2023-10-25T09:12:56.5010391Z app=app-new-service source=runtime.go:122 msg="Transforms set for `default-pipeline` pipeline"
level=DEBUG ts=2023-10-25T09:12:56.5010391Z app=app-new-service source=service.go:386 msg="Default pipeline added with 4 transform(s)"
level=INFO ts=2023-10-25T09:12:56.5010391Z app=app-new-service source=main.go:137 msg=001
level=INFO ts=2023-10-25T09:12:56.5010391Z app=app-new-service source=triggermessageprocessor.go:90 msg="MessagesReceived metric has been registered and will be reported"
level=INFO ts=2023-10-25T09:12:56.5010391Z app=app-new-service source=server.go:181 msg="Starting HTTP Web Server on address localhost:59740"
level=INFO ts=2023-10-25T09:12:56.5015625Z app=app-new-service source=triggermessageprocessor.go:96 msg="InvalidMessagesReceived metric has been registered and will be reported (if enabled)"
level=INFO ts=2023-10-25T09:12:56.5015625Z app=app-new-service source=triggerfactory.go:51 msg="EdgeX MessageBus trigger selected"
level=INFO ts=2023-10-25T09:12:56.5015625Z app=app-new-service source=messaging.go:66 msg="Initializing EdgeX Message Bus Trigger for 'nats-core'"
level=INFO ts=2023-10-25T09:12:56.5015625Z app=app-new-service source=messaging.go:83 msg="Subscribing to topic: edgex/events/#"
level=ERROR ts=2023-10-25T09:12:56.5020793Z app=app-new-service source=service.go:198 msg="already connected to NATS"
level=ERROR ts=2023-10-25T09:12:56.5020793Z app=app-new-service source=main.go:140 msg="Run returned error: failed to initialize Trigger"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
use master  app-functions-sdk
**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@sixhj please fill out the issue template, especially the environement, version, and reproduce steps

**Comment by lenny-intel** [comment]
This issue has been fix in the latest App SDK to be release on Nov 15th.
