### ISSUE TITLE
The secretstore service will deadlock, when vault uses clustered mode and the health check configured in secretstore is for Standby nodes

### ISSUE THREAD

**Issue by ethan256** [edgexfoundry/edgex-go#4726]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]  

- security-secretstore-setup
- security-bootstrap
 The issue is located in:  
https://github.com/edgexfoundry/edgex-go/blob/main/internal/security/secretstore/init.go#L245

When deploying Vault using cluster mode, if the health check configured in the security-secretstore-setup service is the vault of the standby node, the health check endpoint for Vault [/sys/health](https://developer.hashicorp.com/vault /api-docs/system/health#read-health-information) will return 429, which will cause a deadlock in the secretstore.

### Is this a regression?

 No. 

### Description and Minimal Reproduction [**REQUIRED**]
1. Installing Vault in Cluster Mode
2. Start EdgeX with the Vault health check configured in security-secretstore-setup as Standby node

## 🔥 Exception or Error
<pre><code>

deallock
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Docker
**EdgeX Version **[REQUIRED]**
v3.0.0

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@bnevis-i , FYI

**Comment by bnevis-i** [comment]
Hi Ethan, it is a holiday in the US this week.   Feel free to submit a PR.  Will review next week.

**Comment by bnevis-i** [comment]
Awaiting dependabot update for go-mod-secrets to `v3.1.0-dev.16` or later.

**Comment by bnevis-i** [comment]
@ethan256 Still working on this.  I think we need to bump go-mod-secrest to v3.2.x or v4 for dependabot to pick it up.  Working with CI folks.

**Comment by bnevis-i** [comment]
> > @ethan256 Still working on this. I think we need to bump go-mod-secrest to v3.2.x or v4 for dependabot to pick it up. Working with CI folks.
> 
> I agree to upgrade go-mod-secrets to v3.2.x.

go-mod-bootstrap has picked this up so hopefully it won't be long now.

**Comment by lenny-intel** [comment]
@ethan256 , @bnevis-i , latest go-mod-bootstrap v3.2.0-dev.3 is update will latest 3.2.0 dev versions on the other go-mods which includes any merged PRs to those other go-mods.

**Comment by bnevis-i** [comment]
@ethan256 please confirm the fix and close the issue if it is resolved to your satisfaction.
