### ISSUE TITLE
Environment Variables don't work

### ISSUE THREAD

**Issue by jiekechoo** [edgexfoundry/edgex-go#4730]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
All core services.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v2.3.0

## 🔥 Exception or Error
<pre><code>

  core-data:
...
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-data
      SERVICE_REQUESTTIMEOUT: "50s"
...

</code></pre>

![image](https://github.com/edgexfoundry/edgex-go/assets/3350211/b6bfab62-d4f7-443e-b873-146fe9527091)

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]: v3.1.0

**Anything else relevant?**

**Comment by jiekechoo** [comment]
@cloudxxx8 @lenny-intel

**Comment by lenny-intel** [comment]
@jiekechoo , you can only override Private settings on a service if they exist in the local private configuration.yaml.
https://docs.edgexfoundry.org/3.1/microservices/configuration/CommonEnvironmentVariables/#service-configuration-overrides

The `RequestTimeout` is in the Common Config and must be overridden on the `core-common-config-bootstrapper` service (applies to all services) i.e. `ALL_SERVICES_SERVICE_REQUESTTIMEOUT`

Or add `Service.RequestTimeout` to the individual service's configuration.yaml so it can be overridden on the individual service as you are trying.

**Comment by jiekechoo** [comment]
Thanks for you help, @lenny-intel 

I got the solution in https://github.com/orgs/edgexfoundry/discussions/216

Closed.
