### ISSUE TITLE
Support notifications should be able to communicate with authenticated EdgeX endpoints

### ISSUE THREAD

**Issue by jrtitus** [edgexfoundry/edgex-go#4747]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

`support-notifications`

### Description [**REQUIRED**]

Based on the comment found here, the idea would be to make this work.
https://github.com/edgexfoundry/edgex-go/blob/587930f9e62dbb8d1de22549799db07406fff5b2/internal/support/notifications/application/channel/sender.go#L42-L44

### Describe the solution you'd like

Modification of [`models.RESTAddress`](https://github.com/edgexfoundry/go-mod-core-contracts/blob/d550de8b963874dbc1f06193e92b8c8c21de2ad3/models/address.go#L71-L75) and [`dtos.RESTAddress`](https://github.com/edgexfoundry/go-mod-core-contracts/blob/d550de8b963874dbc1f06193e92b8c8c21de2ad3/dtos/address.go#L52-L55) types in order to specify that the endpoint is part of an authenticated EdgeX service, defined by `AddCustomRoute`, for example. Maybe just a boolean `injectAuth` or something similar. Then, when the subscription is created, this attribute can be specified as part of the `channels` array, and the injection can be done when the notification is sent.

### Describe alternatives you've considered
 N/A

**Comment by jrtitus** [comment]
Working code, if you want to pull and test: 

* [edgex-go](https://github.com/edgexfoundry/edgex-go/commit/2e560318b4d5d887a8afd713f95d1adaa26dfffb)
* [go-mod-core-contracts](https://github.com/jrtitus/go-mod-core-contracts/commit/4cb512a874a9211d08383c8b9f1bce5c6e0b7296)

> The test below was completed with edgex-compose; modified `docker-compose-with-app-sample-arm64.yml` to replace the `support-notifications` image with one that I built locally.

### `injectAuth` specified on a transmission with a protected endpoint

#### Subscription Request
```json
[
  {
    "apiVersion": "v3",
    "subscription": {
      "name": "subscriptionC",
      "channels": [
        {
          "type": "REST",
          "host": "app-sample",
          "port": 59700,
          "path": "/api/v3/version",
          "httpMethod": "GET",
          "injectAuth": true
        }
      ],
      "categories": [
        "test-notify"
      ],
      "labels": [
        "test"
      ],
      "receiver": "receiverA",
      "resendLimit": 0,
      "resendInterval": "1h",
      "adminState": "UNLOCKED"
    }
  }
]
```

#### Notification Request
```json
[
  {
    "apiVersion": "v3",
    "notification": {
      "category": "test-notify",
      "content": "content",
      "contentType": "string",
      "description": "test notice",
      "labels": [
        "test"
      ],
      "sender": "postman",
      "severity": "CRITICAL",
      "status": "NEW"
    }
  }
]
```

#### Result `GET http://localhost:59860/api/v3/transmission/all`
![image](https://github.com/edgexfoundry/edgex-go/assets/1756049/f0637c0e-9e20-4bfb-9cb0-a574edb6031b)

### No `injectAuth` specified on a transmission with an open endpoint
#### Subscription Request
```json
[
  {
    "apiVersion": "v3",
    "subscription": {
      "name": "subscriptionD",
      "channels": [
        {
          "type": "REST",
          "host": "app-sample",
          "port": 59700,
          "path": "/api/v3/ping",
          "httpMethod": "GET",
          "injectAuth": false
        }
      ],
      "categories": [
        "test-notify"
      ],
      "labels": [
        "test"
      ],
      "receiver": "receiverA",
      "resendLimit": 0,
      "resendInterval": "1h",
      "adminState": "UNLOCKED"
    }
  }
]
```

#### Notification Request
(same as the one in the above example)

#### Result `GET http://localhost:59860/api/v3/transmission/all`
![image](https://github.com/edgexfoundry/edgex-go/assets/1756049/b64efae1-bb10-49d2-aac4-63a1f3cd9e3f)

**Comment by cloudxxx8** [comment]
What is the use case to send the REST call from the Notifications service back to EdgeX services?
The design of the Notifications service is to notify the external system.

On the other hand, the naming of `injectAuth` is too general for the REST channel, because it only supports EdgeX internal auth injection.  You may rename it to `injectEdgeXAuth`.

**Comment by jrtitus** [comment]
> What is the use case to send the REST call from the Notifications service back to EdgeX services? The design of the Notifications service is to notify the external system.

The main use case I was considering would be to allow for application services and device services defining an endpoint with `AddCustomRoute` to be able to subscribe and react to notifications using those custom route handlers. Unless there is a better way to accomplish this, that I'm not thinking of?

> On the other hand, the naming of `injectAuth` is too general for the REST channel, because it only supports EdgeX internal auth injection. You may rename it to `injectEdgeXAuth`.

Sounds good to me.

**Comment by cloudxxx8** [comment]
@jrtitus 
Sorry, I was occuipied and just got some time reply the community issue.
Your implementation and use case sound good to me.  Please open PRs and I will review and merge them.

**Comment by jrtitus** [comment]
> @jrtitus 
> Sorry, I was occuipied and just got some time reply the community issue.
> Your implementation and use case sound good to me.  Please open PRs and I will review and merge them.

No worries, I've been busy with other things as well. I should have some time to open the PRs today after work. Thanks!
