### ISSUE TITLE
Add Core Keeper Service

### ISSUE THREAD

**Issue by jackchenjc** [edgexfoundry/edgex-go#4783]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for the new core-keeper service

### Description [**REQUIRED**]
 Core Keeper is a lightweight configuration and registry service that is aimed to replace Consul in the EdgeX architecture

**Comment by SynchronicIT** [comment]
What would be needed to get the new core keeper merged into the main branch?

**Comment by cloudxxx8** [comment]
Just need some more tests and code review
