### ISSUE TITLE
Bump golang libraries to fix CVEs in Napa branch

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#4792]
The current version golang.org/x/crypto and golang.org/x/net in Napa branch is discovered CVEs

**Comment by jumpingliu** [comment]
fixed by https://github.com/edgexfoundry/edgex-go/issues/4792

**Comment by cloudxxx8** [comment]
We discovered more CVEs
![image](https://github.com/edgexfoundry/edgex-go/assets/11695863/00e70c27-acb2-4ce0-a600-f75442bd196d)
![image](https://github.com/edgexfoundry/edgex-go/assets/11695863/463edafa-4289-4dc3-bbcb-19c538520f52)
![image](https://github.com/edgexfoundry/edgex-go/assets/11695863/2af71327-e82e-4f31-96ba-07fe48dbd6fc)

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/edgex-go/pull/4799
