### ISSUE TITLE
Add support for systemd-notify to snap services

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#480]
Using systemd-notify for snap services would allow us to properly support EdgeX micro-services as actual services in the snap. The current problem with doing this is that after a given service is started there's some amount of "initialization time" before the service is "ready" for it's dependent services to run. 
If we were able to use systemd-notify inside the micro-services, then we could specify in the snapcraft.yaml for the services to be considered "ready" by systemd only after receiving the notify signal from the services. This would also give us easy watchdog support when starting the snaps. 
See more discussion at issue #441.

**Comment by anonymouse64** [comment]
Related, possibly prerequisite: #485

**Comment by tonyespy** [comment]
This has landed in Dehli (#722), but is not yet in master, so adjusting labels accordingly.
