### ISSUE TITLE
Consul does not work as intended based on documentation [Build and Run on Linux on x86/x64]

### ISSUE THREAD

**Issue by M0hanrajp** [edgexfoundry/edgex-go#4816]
# 🐞 Bug Report

### Affected Services 

 The issue is located in: starting up the consul agent as specified in the doc https://docs.edgexfoundry.org/3.1/getting-started/native/Ch-BuildRunOnLinuxDistro/#start-consul

### Is this a regression?

Not a regression.

### Description and Minimal Reproduction

Follow the steps mentioned in https://docs.edgexfoundry.org/3.1/getting-started/native/Ch-BuildRunOnLinuxDistro/

## 🔥 Exception or Error
<pre><code>
mpunix@LIN-MP22QN1X:~/edgex$ ls
app-service-configurable  device-virtual-go  docker_security_false  docker_security_true  edgex-go  edgex-ui-go  ekuiper
mpunix@LIN-MP22QN1X:~/edgex$ nohup consul agent -ui -bootstrap -server -client 0.0.0.0 -data-dir=tmp/consul &
[1] 176641
mpunix@LIN-MP22QN1X:~/edgex$ nohup: ignoring input and appending output to 'nohup.out'

// After executing this command I entered http://127.0.0.1:8500 but there is no response
// Below is the error captured from another terminal instance:
mpunix@LIN-MP22QN1X:~$ cd edgex/
mpunix@LIN-MP22QN1X:~/edgex$ curl http://127.0.0.1:8500/v3/api/ping
curl: (7) Failed to connect to 127.0.0.1 port 8500 after 11 ms: Connection refused
</code></pre>

## 🌍  Your Environment
**Deployment Environment: Ubuntu 22.04**

**EdgeX Version: 3.0/3.1**

---
Thanks.

**Comment by jiekechoo** [comment]
@M0hanrajp 
Just run with the command:
```
consul agent -ui -bootstrap -server -client 0.0.0.0 -data-dir=tmp/consul
```
if no error, and, in another terminal try to check the TCP port 8500 is avaliable:
```
netstat -nlpt |grep 8500
```

**Comment by M0hanrajp** [comment]
Thanks @jiekechoo, 

I used the following command but consul was not up
```bash
~/edgex$ consul agent -ui -bootstrap -server -client 127.0.0.1 -data-dir=tmp/consul
==> Multiple private IPv4 addresses found. Please configure one with 'bind' and/or 'advertise'.
```
So I tried with the below command and consul agent is up at specified client IP, Thanks 👍 
```bash
~/edgex$ consul agent -ui -bootstrap -server -client 0.0.0.0 -data-dir=tmp/consul -bind=127.0.0.2 -advertise=127.0.0.2
==> Starting Consul agent...
...
2024-07-04T23:35:21.793+0530 [INFO]  agent.http: Registered resource endpoint: endpoint=/api/catalog/v2beta1/nodehealthstatus
2024-07-04T23:35:21.793+0530 [INFO]  agent: Starting server: address=[::]:8500 network=tcp protocol=http
2024-07-04T23:35:21.794+0530 [INFO]  agent: Started gRPC listeners: port_name=grpc_tls address=[::]:8503 network=tcp
2024-07-04T23:35:21.795+0530 [INFO]  agent: started state syncer
2024-07-04T23:35:21.795+0530 [INFO]  agent: Consul agent running!
```
---
Closing the bug.

**Comment by M0hanrajp** [comment]
Adding few more information,

My understanding was not proper, after I ran with nohup and I saw the output of nohup.out: 
```
~/edgex$ cat nohup.out
==> Multiple private IPv4 addresses found. Please configure one with 'bind' and/or 'advertise'.
==> Multiple private IPv4 addresses found. Please configure one with 'bind' and/or 'advertise'.
```
So I ran with the below command & consul agent works with nohup

* nohup: Prevents the process from receiving the SIGHUP (hang up) signal, which is sent when the terminal is closed.
* &: Runs the command in the background, allowing you to continue using the terminal for other tasks.
```bash
~/edgex$ nohup consul agent -ui -bootstrap -server -client 127.0.0.1 -data-dir=tmp/consul -bind=127.0.0.2 -advertise=127.0.0.2
nohup: ignoring input and appending output to 'nohup.out'
^Cmpunix@LIN-MP22QN1X:~/edgex$ cat nohup.out
...
==> Log data will now stream in as it occurs:

2024-07-05T00:05:02.184+0530 [INFO]  agent: Starting server: address=127.0.0.1:8500 network=tcp protocol=http
2024-07-05T00:05:02.185+0530 [INFO]  agent: Started gRPC listeners: port_name=grpc_tls address=127.0.0.1:8503 network=tcp
2024-07-05T00:05:02.186+0530 [INFO]  agent: started state syncer
2024-07-05T00:05:02.186+0530 [INFO]  agent: Consul agent running!
```
---
Thanks
