### ISSUE TITLE
Modify core-data configuration under Writable doesn't take effect before restarting service when using core-keeper as registry service

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4832]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: core-keeper

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Generate compose file by `make gen no-secty keeper mqtt-bus ds-virtual arm64` under [edgex-compose/compose-builder](https://github.com/edgexfoundry/edgex-compose/tree/57138ce759e62b29e6a039647c8f0c1bd2238e8f/compose-builder)
2. Deploy service by the generated compose file.
3. Set core-data log to Debug.
```
curl -X PUT http://localhost:59890/api/v3/kvs/key/edgex/v3/core-data/Writable/LogLevel \
-H 'Content-Type: application/json' -d '{"value": "DEBUG"}'
```
4. View core-data logs `docker logs edgex-core-data`

## 🔥 Exception or Error
<pre><code>
The change does not take effect immediately.
The change only takes effect after restarting core-data
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 2204 / arm64

**EdgeX Version [**REQUIRED**]:** main

**Anything else relevant?**

**Comment by jackchenjc** [comment]
Fixed with [edgex-compose#470 ](https://github.com/edgexfoundry/edgex-compose/pull/470)
