### ISSUE TITLE
Create new support-cron-scheduler service

### ISSUE THREAD

**Issue by jackchenjc** [edgexfoundry/edgex-go#4834]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for creating the new support-cron-scheduler service.

### Description [**REQUIRED**]

This issue has been opened to create a new support-cron-scheduler service for EdgeX. Multiple pull requests will be submitted to facilitate easier review.

**Comment by cloudxxx8** [comment]
close as implementation complete
