### ISSUE TITLE
Inconsistent definition of AdminState between suppport-cron-scheduler API docs and dtos

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4879]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-cron-scheduler

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. AdminState in API docs is required https://github.com/edgexfoundry/edgex-go/blob/872e8ffdf3f0ef6c4a8f4e5a20969148dd3ced41/openapi/v3/support-cron-scheduler.yaml#L293-L297, but in dtos defines `omitempty`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@cherrycl It's a doc bug.  Please help modify the API doc:
Remove adminState from required fields, and add a description to state the default value is UNLOCKED if it is empty

In the DTO `validate:"omitempty,oneof='LOCKED' 'UNLOCKED'"` means the value should be 'LOCKED' or 'UNLOCKED', but if the value is empty, don't validate it.  We auto assign the value UNLOCKED if it is empty.
