### ISSUE TITLE
schedule job didn't auto-trigger if it has been triggered by manual before startTimestamp

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4886]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-cron-scheduler

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Create a schedule job
```
[
  {
    "apiVersion": "v3",
    "scheduleJob": {
      "name": "test_job_1",
      "definition": {
        "type": "INTERVAL",
        "startTimestamp": 1725522240000,
        "endTimestamp": 1725522300000,
        "interval": "20s"
      },
      "actions": [
        {
          "type": "REST",
          "contentType": "application/json",
          "address": "http://172.17.0.1:59880/api/v3/ping",
          "method": "GET"
        }
      ],
      "labels": ["core-data"]
    }
  }
]
```
2. Trigger it manual by API job/trigger/name/${name} before the startTimestamp, got return status code 500 with error message `failed to trigger scheduler action for job: test_job_1`
3. Wait until startTimestamp

## 🔥 Exception or Error
The job wasn't auto-trigger.

## 🌍  Your Environment
**Deployment Environment:** Ubuntu2204/arm64

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**
Re-trigger the job by API job/trigger/name/${name} will return `503 Service Unavailable`

**Comment by jackchenjc** [comment]
Plan to replace the current implementation with [WithStartAt](https://pkg.go.dev/github.com/go-co-op/gocron/v2#WithStartAt) and [WithStopAt](https://pkg.go.dev/github.com/go-co-op/gocron/v2#WithStopAt).

Pending and waiting for #4884 to be resolved.
