### ISSUE TITLE
Expired schedule job is re-triggerred after restarting support-cron-scheduler

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4890]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-cron-scheduler

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Create a scheduler job
2. Wait the job started and stopped
3. Restart support-cron-scheduler

## 🔥 Exception or Error
The expired schedule job is re-triggered
<pre><code>
....
level=DEBUG ts=2024-09-06T07:05:40.016031163Z app=support-cron-scheduler source=manager.go:261 msg="A new schedule action record with type: REST and status: SUCCEEDED was added for job: test_job_1, record ID: ab088a56-7573-4dcb-a9a8-6b747afb3656, Correlation-ID: 7c78aa45-43b1-4d78-b499-d9ca9c569261"
level=DEBUG ts=2024-09-06T07:05:50.010199607Z app=support-cron-scheduler source=rest.go:40 msg="Successfully send the rest request with address http://172.17.0.1:59880/api/v3/ping"
level=DEBUG ts=2024-09-06T07:05:50.010430808Z app=support-cron-scheduler source=gocron.go:105 msg="REST action was executed successfully, response: {\"apiVersion\":\"v3\",\"timestamp\":\"Fri Sep  6 15:05:50 CST 2024\",\"serviceName\":\"core-data\"}"
level=DEBUG ts=2024-09-06T07:05:50.016112465Z app=support-cron-scheduler source=manager.go:261 msg="A new schedule action record with type: REST and status: SUCCEEDED was added for job: test_job_1, record ID: 9d6c9de5-f616-49cf-b7cf-6523901941f2, Correlation-ID: 7c78aa45-43b1-4d78-b499-d9ca9c569261"
level=DEBUG ts=2024-09-06T07:06:00.002032216Z app=support-cron-scheduler source=manager.go:128 msg="The scheduled job test_job_1 was stopped in the scheduler manager. Correlation-ID: d9a2c4ff-ae22-420f-a83b-887952905381"
level=DEBUG ts=2024-09-06T07:06:06.357628579Z app=support-cron-scheduler source=reporter.go:195 msg="Publish 0 metrics to the 'edgex/telemetry/support-cron-scheduler' base topic"
level=DEBUG ts=2024-09-06T07:06:06.35786978Z app=support-cron-scheduler source=manager.go:123 msg="Reported metrics..."
level=DEBUG ts=2024-09-06T07:06:36.357201871Z app=support-cron-scheduler source=reporter.go:195 msg="Publish 0 metrics to the 'edgex/telemetry/support-cron-scheduler' base topic"
level=DEBUG ts=2024-09-06T07:06:36.357357616Z app=support-cron-scheduler source=manager.go:123 msg="Reported metrics..."
level=INFO ts=2024-09-06T07:06:51.430338396Z app=support-cron-scheduler source=config.go:853 msg="Watching for 'Writable' configuration changes has stopped"
level=INFO ts=2024-09-06T07:06:51.430592639Z app=support-cron-scheduler source=httpserver.go:262 msg="Web server stopped"
...
## restarting logs
...
level=INFO ts=2024-09-06T07:06:51.720858287Z app=support-cron-scheduler source=manager.go:60 msg="New scheduled job test_job_1 was added into the scheduler manager. ScheduleJob ID: feccf895-2718-4613-ac2a-a0ecb0f71065, Correlation-ID: 6110eb2f-829f-416c-8529-c2db3b3eed16"
level=DEBUG ts=2024-09-06T07:06:51.720881369Z app=support-cron-scheduler source=schedulejob.go:227 msg="The startTimestamp is expired for the scheduled job: test_job_1, which will be started immediately. Correlation-ID: 6110eb2f-829f-416c-8529-c2db3b3eed16"
level=DEBUG ts=2024-09-06T07:06:51.720890577Z app=support-cron-scheduler source=schedulejob.go:243 msg="The endTimestamp is expired for the scheduled job: test_job_1, which will be stopped immediately. Correlation-ID: 6110eb2f-829f-416c-8529-c2db3b3eed16"
level=DEBUG ts=2024-09-06T07:06:51.721025657Z app=support-cron-scheduler source=manager.go:128 msg="The scheduled job test_job_1 was stopped in the scheduler manager. Correlation-ID: 6110eb2f-829f-416c-8529-c2db3b3eed16"
level=DEBUG ts=2024-09-06T07:06:51.721037782Z app=support-cron-scheduler source=manager.go:113 msg="The scheduled job test_job_1 was started. Correlation-ID: 6110eb2f-829f-416c-8529-c2db3b3eed16"
level=DEBUG ts=2024-09-06T07:06:51.725540698Z app=support-cron-scheduler source=scheduleactionrecord.go:162 msg="Missed schedule action records with action id: b15ac040-30bb-4028-875d-57f255697755 of job: test_job_1 have been created successfully. Correlation-ID: 6110eb2f-829f-416c-8529-c2db3b3eed16"
level=DEBUG ts=2024-09-06T07:06:51.725570697Z app=support-cron-scheduler source=schedulejob.go:205 msg="Successfully loaded the existing scheduled job: test_job_1. Correlation-ID: 6110eb2f-829f-416c-8529-c2db3b3eed16"
level=INFO ts=2024-09-06T07:06:51.72558378Z app=support-cron-scheduler source=httpserver.go:167 msg="Web server starting (edgex-support-cron-scheduler:59863)"
level=INFO ts=2024-09-06T07:06:51.725589322Z app=support-cron-scheduler source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2024-09-06T07:06:51.725592072Z app=support-cron-scheduler source=message.go:51 msg="Starting support-cron-scheduler 3.2.0-dev.61 "
level=INFO ts=2024-09-06T07:06:51.725593863Z app=support-cron-scheduler source=message.go:55 msg="This is the Support Cron Scheduler Microservice"
level=INFO ts=2024-09-06T07:06:51.725596572Z app=support-cron-scheduler source=message.go:58 msg="Service started in: 51.797728ms"
level=INFO ts=2024-09-06T07:06:51.725604238Z app=support-cron-scheduler source=bootstrap.go:254 msg="SecuritySecretsRequested metric registered and will be reported (if enabled)"
level=INFO ts=2024-09-06T07:06:51.725607446Z app=support-cron-scheduler source=bootstrap.go:254 msg="SecuritySecretsStored metric registered and will be reported (if enabled)"
level=INFO ts=2024-09-06T07:06:51.725617196Z app=support-cron-scheduler source=httpserver.go:239 msg="listening on underlay network. ListenMode '' at edgex-support-cron-scheduler:59863"
level=DEBUG ts=2024-09-06T07:07:01.727049355Z app=support-cron-scheduler source=rest.go:40 msg="Successfully send the rest request with address http://172.17.0.1:59880/api/v3/ping"
level=DEBUG ts=2024-09-06T07:07:01.727157477Z app=support-cron-scheduler source=gocron.go:105 msg="REST action was executed successfully, response: {\"apiVersion\":\"v3\",\"timestamp\":\"Fri Sep  6 15:07:01 CST 2024\",\"serviceName\":\"core-data\"}"
level=DEBUG ts=2024-09-06T07:07:01.732117759Z app=support-cron-scheduler source=manager.go:261 msg="A new schedule action record with type: REST and status: SUCCEEDED was added for job: test_job_1, record ID: c967fc18-8dce-445b-9c66-6b55c0ec4575, Correlation-ID: 83891720-aaff-4eda-be42-f773f4f3b0eb"
level=DEBUG ts=2024-09-06T07:07:11.728406614Z app=support-cron-scheduler source=rest.go:40 msg="Successfully send the rest request with address http://172.17.0.1:59880/api/v3/ping"
level=DEBUG ts=2024-09-06T07:07:11.72892335Z app=support-cron-scheduler source=gocron.go:105 msg="REST action was executed successfully, response: {\"apiVersion\":\"v3\",\"timestamp\":\"Fri Sep  6 15:07:11 CST 2024\",\"serviceName\":\"core-data\"}"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 2204/arm64

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by jackchenjc** [comment]
Verified this issue has been fixed but I caught another bug that the missed records still been generated.
Will fix it in the PR for this issue.
