### ISSUE TITLE
Enable ASLR by default on all cmd/ binaries

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#4916]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
All cmd/ binaries

### Description [**REQUIRED**]
Current EdgeX binaries are dynamic binaries without ASLR enabled.  They are using dynamic linking and linking to a C runtime, binaries should be be built with "-buildmode=pie" option.  This can be checked with the checksec --file=path/cmd/binary     

See https://www.ituonline.com/tech-definitions/what-is-address-space-layout-randomization-aslr for a brief into on ASLR

Note: The latest golang compiler also now supports a `-bindnow` linker flag to enable full RELRO

**Comment by cloudxxx8** [comment]
thanks @bnevis-i 
we are adding the flags to all the Makefile
