### ISSUE TITLE
Rules Engine not showing in list of registered export clients

### ISSUE THREAD

**Issue by mhall119** [edgexfoundry/edgex-go#492]
Following the API walkthrough when I got to the step of checking on registered export clients, it returned an empty array when it should have at least had the Rules Engine listed.

https://github.com/mhall119/edgex-go/blob/new-walkthrough/docs/walk-through/Ch-WalkthroughExporting.rst#export-clients

When following the next step, to manually add another export client, it returns a 400 error with the message: Could not validate json fields

**Comment by jpwhitemn** [comment]
This is fixed with California 0.6.1 release.

**Comment by mhall119** [comment]
Is the docker-compose-california-0.6.0.yml going to be updated to point to new images with this fix, or will there be a -0.6.1.yaml added?

**Comment by mhall119** [comment]
Confirming that this works with the 0.6.1 docker-compose file
