### ISSUE TITLE
Unable to register export client when following the API Walkthrough

### ISSUE THREAD

**Issue by mhall119** [edgexfoundry/edgex-go#493]
https://github.com/mhall119/edgex-go/blob/new-walkthrough/docs/walk-through/Ch-WalkthroughExporting.rst#export-clients

When following the step to manually add another export client, it returns a 400 error with the message: Could not validate json fields

The JSON I'm POSTing is:
`{"name":"MyMQTTTopic","addressable":{"name":"MyMQTTBroker","protocol":"TCP","address":"tcp://m10.cloudmqtt.com","port":15421,"publisher":"EdgeXExportPublisher","user":"hukfgtoh","password":"mypass","topic":"EdgeXDataTopic"},"format":"JSON","encryption":{"encryptionAlgorithm":"AES","encryptionKey":"123","initializingVector":"123"},"enable":true}`

**Comment by feclare** [comment]
when trying to use your json I got the following trace in export-client:
{"level":"error","ts":1534878320.3670533,"caller":"client/registration.go:122","msg":"Failed to validate registrations fields","data":"{\"name\":\"MyMQTTTopic\",\"addressable\":{\"name\":\"MyMQTTBroker\",\"protocol\":\"TCP\",\"address\":\"tcp://m10.cloudmqtt.com\",\"port\":15421,\"publisher\":\"EdgeXExportPublisher\",\"user\":\"hukfgtoh\",\"password\":\"mypass\",\"topic\":\"EdgeXDataTopic\"},\"format\":\"JSON\",\"encryption\":{\"encryptionAlgorithm\":\"AES\",\"encryptionKey\":\"123\",\"initializingVector\":\"123\"},\"enable\":true}",**"error":"Destination invalid: "**,"stacktrace":"github.com/edgexfoundry/edgex-go/export/client.addReg\n\t/home/feclare/go/src/github.com/edgexfoundry/edgex-go/export/client/registration.go:122\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/lib/go/src/net/http/server.go:1947\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Route).parse\n\t/home/feclare/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/route.go:153\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).parse\n\t/home/feclare/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/helper.go:22\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).DefaultServe\n\t/home/feclare/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/bone.go:54\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).DefaultServe-fm\n\t/home/feclare/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/bone.go:40\ngithub.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).ServeHTTP\n\t/home/feclare/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/bone.go:73\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/go/src/net/http/server.go:2694\nnet/http.(*conn).serve\n\t/usr/lib/go/src/net/http/server.go:1830"}

You need to add the destination, ``"destination":"MQTT_TOPIC"``, to the json

**Comment by mhall119** [comment]
That did the trick! Thanks @feclare
