### ISSUE TITLE
Removed schedule job still got "Failed to stop job" error in logs

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4933]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-cron-scheduler

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Create a Job with the following request body
```
[
   {
      "scheduleJob":{
         "name":"job_1",
         "definition":{
            "type":"INTERVAL",
            "interval":"5s",
            "startTimestamp":{{startTime}},
            "endTimestamp":{{endTime}}
         },
         "actions":[
            {
               "type":"REST",
               "address": "http://edgex-core-metadata:59881/api/v3/ping",
               "method": "GET"
            }
         ],
         "adminState":"UNLOCKED"
      },
      "apiVersion":"v3"
   }
]
```
2. Delete the job after the job was started and not stopped
3. Wait until the endTimestamp was arrived.

## 🔥 Exception or Error
<pre><code>
level=ERROR ts=2024-10-04T02:57:08.066888351Z app=support-cron-scheduler source=schedulejob.go:279 msg="Failed to stop the scheduled job: job_1 based on endTimestamp. Error: the scheduled job: job_1 does not exist, Correlation-ID: 498c290f-d378-40f2-b724-0e14c61b8a6c"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu2204/arm64

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by jackchenjc** [comment]
This should be fixed when https://github.com/edgexfoundry/edgex-go/issues/4886 is resolved.

**Comment by cloudxxx8** [comment]
let's wait for the dependabot upgrade

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/edgex-go/pull/4962
