### ISSUE TITLE
Got runtime error exception while updating scheduleJob with invalid action type

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4944]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-cron-scheduler

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Run command `make run no-secty keeper mqtt-bus postgres arm64` under [compose-build](https://github.com/edgexfoundry/edgex-compose/tree/main/compose-builder) to deploy service
2. Create scheduleJob with following request body
```
[
   {
      "scheduleJob":{
         "name":"job_1728265600039",
         "definition":{
            "type":"CRON",
            "crontab":"*/30 * * * * *",
            "startTimestamp":{{startTime}},
            "endTimestamp":{{endTime}}
         },
         "actions":[
            {
               "type":"REST",
               "contentType":"application/json",
               "address":"http://edgex-core-data:59880/api/v3/ping",
               "method":"GET",
               "injectEdgeXAuth":false,
               "payload":""
            }
         ],
         "adminState":"UNLOCKED",
         "autoTriggerMissedRecords":true,
         "labels":[
            "CRON",
            "REST"
         ]
      },
      "apiVersion":"v3"
   }
]
```
3. Update scheduleJob with following request body
```
[
   {
      "scheduleJob":{
         "name":"job_1728265600039",
         "actions":[
            {
               "type":"invalid",
               "contentType":"application/json",
               "deviceName":"deviceControl",
               "sourceName":"Virtual_DeviceValue_INT16_RW",
               "payload":"{\"value\": 1234}"
            }
         ]
      },
      "apiVersion":"v3"
   }
]
```
## 🔥 Exception or Error
<pre><code>
2024/10/07 12:01:56 http: panic serving 192.168.64.1:62309: runtime error: invalid memory address or nil pointer dereference
goroutine 372 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1947 +0xb0
panic({0x109dc40?, 0x2150440?})
        runtime/panic.go:785 +0x124
net/http.(*timeoutHandler).ServeHTTP(0x400022c380, {0x1570770, 0x4000098140}, 0x400037e780)
        net/http/server.go:3675 +0x654
github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/handlers.(*HttpServer).BootstrapHandler.TimeoutWithConfig.TimeoutConfig.ToMiddleware.func9.1({0x1590280, 0x40002560a0})
        github.com/labstack/echo/v4@v4.11.4/middleware/timeout.go:125 +0x1ac
github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/handlers.(*HttpServer).BootstrapHandler.UrlDecodeMiddleware.func5.1({0x1590280, 0x40002560a0})
        github.com/edgexfoundry/go-mod-bootstrap/v3@v3.2.0-dev.58/bootstrap/handlers/common_middleware.go:84 +0x260
github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/handlers.(*HttpServer).BootstrapHandler.LoggingMiddleware.func4.1({0x1590280, 0x40002560a0})
        github.com/edgexfoundry/go-mod-bootstrap/v3@v3.2.0-dev.58/bootstrap/handlers/common_middleware.go:60 +0x394
github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/handlers.ManageHeader.func1({0x1590280, 0x40002560a0})
        github.com/edgexfoundry/go-mod-bootstrap/v3@v3.2.0-dev.58/bootstrap/handlers/common_middleware.go:40 +0x204
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x40001c5d48, {0x15708c0, 0x4000212000}, 0x400037e140)
        github.com/labstack/echo/v4@v4.11.4/echo.go:669 +0x318
net/http.serverHandler.ServeHTTP({0x156bd40?}, {0x15708c0?, 0x4000212000?}, 0x6?)
        net/http/server.go:3210 +0xbc
net/http.(*conn).serve(0x400046a090, {0x15735c0, 0x40003ab590})
        net/http/server.go:2092 +0x4fc
created by net/http.(*Server).Serve in goroutine 99
        net/http/server.go:3360 +0x3dc
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu2204/arm64

**EdgeX Version [**REQUIRED**]:**Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
resolved by https://github.com/edgexfoundry/edgex-go/pull/4958
