### ISSUE TITLE
[snap/cali] Sometime security-start.sh fails with permission denied errors (Ubuntu 16.04)

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#496]
The california edgexfoundry snap sometimes fails at startup in the **security-start.sh** shell script with the following error:
```

echo Starting up security services
Starting up security services
+ /snap/edgexfoundry/16/bin/security-start.sh
2018/08/22 10:18:38 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
2018/08/22 10:18:38 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
2018/08/22 10:18:38 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
Error: /snap/edgexfoundry/16/share/lua/5.1/kong/cmd/start.lua:25: unable to open env path /var/snap/edgexfoundry/15/kong/.kong_env (Permission denied)
```

This is an intermittent problem, and appears to be the result of a race condition, as I can stop/start EdgeX multiple times without issue (I just did 7 in a row with no problem).

I'm running snap version **0.6.0-20180822+67e0af0 (16)** installed from the **california/edge** channel.  I made sure to ensure all of the interfaces were connected, and re-started the snap after connecting them:

```
espy@shrike-x:/tmp$ snap interfaces | grep edge
:hardware-observe          edgexfoundry
:mount-observe             edgexfoundry
:network                   edgexfoundry,firefox,rocketchat-desktop,surl
:network-bind              edgexfoundry,surl
:process-control           edgexfoundry
:system-observe            edgexfoundry

```
I'm running the snap on an up-to-date **Ubuntu Desktop 16.04 LTS** running as a guest OS inside Parallels on macbook pro.  I haven't yet been able to reproduce it on **Ubuntu Desktop 18.04 LTS** or **Ubuntu Core 16**.

**Note** - my 16.04 image has encrypted home enabled, which is a key difference between it, and the other versions of Ubuntu I've tried it on.

Steps to reproduce:

1) Install the snap via: 

`$ sudo snap install --channel california/edge edgexfoundry
`
2) connect the interfaces:
```

$ sudo snap connect edgexfoundry:hardware-observe
$ sudo snap connect edgexfoundry:mount-observe
$ sudo snap connect edgexfoundry:process-control
$ sudo snap connect edgexfoundry:system-observe

```
3) restart the snap:

`$ sudo snap restart edgexfoundry
`
4) start the snap:

`$ sudo edgexfoundry.start-edgex
`
Repeat as necessary to reproduce:

5) stop the snap:

`$ sudo edgexfoundry.stop-edgex
`
6) start the snap

`$ sudo edgexfoundry.start-edgex
`

**Comment by anonymouse64** [comment]
One way to fix this is to delete the kong_env file when we run the `stop-edgex` script, this ensures it doesn't exist when start-edgex is run.

**Comment by anonymouse64** [comment]
PR open: #508

**Comment by tonyespy** [comment]
I just ran a dozen start/stop cycles in a row on a Dell GW 3000 running Ubuntu Core 16 and using version 0.6.1~pre1-20180907+fb544b5 of the snap from the california/candidate channel. All the starts worked just fine, so I really think this issue is related to my home dir encryption on my classic Ubuntu Desktop system.
