### ISSUE TITLE
Event should not be created when contains binary reading with empty mediaType

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4964]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: core-data

### Is this a regression?

 Yes, the previous version in which this bug was not present was: napa

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy service by `[docker-compose-no-secty-arm64.yml](https://github.com/edgexfoundry/edgex-compose/blob/57a2deeff85f2fee03a42ad075f16051b8dce520/docker-compose-no-secty-arm64.yml`
2. Create event with binary reading and set mediaType to empty
```
POST http://localhost:59880/api/v3/event/Service-Test-002/Profile-Test-002/Device-Test-002/Command-Test-002

{
   "event":{
      "apiVersion":"v3",
      "deviceName":"Device-Test-002",
      "profileName":"Profile-Test-002",
      "sourceName":"Command-Test-002",
      "id":"db3b2bce-91bd-4c07-a32e-83b65144ac0a",
      "origin":1728446686531000064,
      "readings":[
         {
            "deviceName":"Device-Test-002",
            "resourceName":"Binary-Reading",
            "profileName":"Profile-Test-002",
            "origin":1728446686531000064,
            "mediaType":"",
            "valueType":"Binary",
            "binaryValue":"83010203"
         }
      ]
   },
   "apiVersion":"v3"
}
```

Expected result: Return status code 400 with `message: BinaryReading.MediaType field is required`
## 🔥 Exception or Error
Event was created.

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu2204/arm64

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**
Redis and Postgres both have the same issue.

**Comment by cherrycl** [comment]
This issue is still existed on latest image.

**Comment by weichou1229** [comment]
Since the service unmarshal the reading as null reading, the service skips the reading checking.
Open core-contracts to fix it https://github.com/edgexfoundry/go-mod-core-contracts/pull/939

**Comment by weichou1229** [comment]
@cherrycl This should be fixed once the edgex-go upgrade the core-contracts.

**Comment by jumpingliu** [comment]
close this issue as the core-contracts is the latest version
