### ISSUE TITLE
Bring the new System Management Agent functionality into master.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#497]
- As part of bringing the new System Management Agent functionality into master, the refactoring done to split business logic from INFRA concerns is included therein. 
- Details regarding the former can be [found here](https://wiki.edgexfoundry.org/display/FA/Phase+1%2C+System+Management+Delhi+Release)
- And details regarding the latter can be [found here](https://github.com/edgexfoundry/edgex-go/issues/457).

**Comment by jduranf** [comment]
Closing via #498 
Also related with #112
