### ISSUE TITLE
Check gofmt in all pull requests

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#501]
In the last commits, several code have been pushed which fails in gofmt check. One month ago, gofmt check was 100% and now is 94%, as can be seen in [edgex-go report card](https://goreportcard.com/report/github.com/edgexfoundry/edgex-go).

Maybe should be a good idea to modify [edgex-go-master-verify](https://jenkins.edgexfoundry.org/job/edgex-go-master-verify-go/) in order to check if the PR pass the gofmt check or not. [Here](https://github.com/opentable/sous/blob/master/bin/check-gofmt) is a simple example in how to do it.

**Comment by feclare** [comment]
I agree
Adding it to make test will make it easy for people to test locally.

**Comment by tsconn23** [comment]
@JPWKU Thoughts?

**Comment by jduranf** [comment]
@JPWKU any news about this suggestion?

**Comment by jpwhitemn** [comment]
@JPWKU - Jeremy, I thought this was already in our CI/CD pipe? Can you comment?  If it is not, we should add to our DevOps roadmap for Edinburgh.  Doable??

**Comment by andresrinivasan** [comment]
Re consideration of gometalinter. I've been using [golangci-lint](https://github.com/golangci/golangci-lint) which aggregates additional linters.

**Comment by brandonforster** [comment]
closed via #1298
