### ISSUE TITLE
Add snap config setting to control consul usage

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#518]
The snap currently always enables Consul and starts each service with the bootstrap parameter `--registry`. Also as of Edinburgh, the Consul is bound to the port 8500 via an environment variable which is set in snapcraft.yaml, so its technically not possible to change Consul's port without rebuilding the snap.

For Fuji, the snap should add a configure hook which supports a new key called **registry.enable**, which if set to false, will prevent Consul from being started and the config-seed service from running, and will strip the `--registry `parameter from the other service command lines.

**Comment by anonymouse64** [comment]
Removing this from Delhi, as I won't have time to implement this and #485 for Delhi.

**Comment by anonymouse64** [comment]
Unfortunately, doing this probably requires some kind of wrapper script which I worked very hard to eliminate as much as possible from the snap :-/

**Comment by anonymouse64** [comment]
I have a clever fix for this that should be pretty straight forward to do with `command-chain` and `environment`, and best of all only needs one additional wrapper script

**Comment by anonymouse64** [comment]
Moving this to Geneva...

**Comment by tonyespy** [comment]
This didn't make the Geneva train, so removing the milestone.

**Comment by tonyespy** [comment]
I'd like to keep this open, and will plan to address this as part of the Hanoi release.

**Comment by tonyespy** [comment]
As there hasn't been any demand for this feature, I'm going to closing this issue as "won't fix" for now. This may change in the future, and is so we'll address it then.
