### ISSUE TITLE
make build error, package not find and internal package package not allowed

### ISSUE THREAD

**Issue by maxiwu** [edgexfoundry/edgex-go#526]
After successfully run "make prepare". then I run "make build".
it still complains about missing package like BurntSushi/toml and such. from both $GOROOT and $GOPATH
including go-zoo/bone, hashicorp/consul/api, go.uber.org/zap, gopkg.in/mgo.v2, gopkg.in/mgo.v2/bson

I try to fix it by running "go get ...", then come up a new exceptions
github.com/edgexfoundry/edgex-go/internal not allowed
github.com/edgexfoundry/edgex-go/internal/pkg/config not allowed
github.com/edgexfoundry/edgex-go/internal/pkg/usage not allowed

what does this means? no permission? or missing files?

**Comment by maxiwu** [comment]
I think I run "go get github.com/edgexfoundry/edgex-go", but it does not show any message. No success or fail. Then I run git clone https://github.com/edgexfoundry/edgex-go

I install Glide using apt-get install glide. But then I updated it by "go get -u github.com/Masterminds/glide" to fix the package "." bug.

**Comment by maxiwu** [comment]
clean up and retry.

apt get install for glide and git.
go get edgex-go
curl | sh for zeroMQ
This time, no error.

**Comment by drasko** [comment]
https://medium.com/mainflux-iot-platform/edgex-in-anger-part-1-installation-5468c52be4d1
