### ISSUE TITLE
Core config should use default empty Mongo user/pass

### ISSUE THREAD

**Issue by drasko** [edgexfoundry/edgex-go#529]
Currently some of the core services use different `username` and `password` for MongoDB. This prevents script to easily launch services on the local machine (not in docker) during the dev phase, without modification of `.toml` files.

**Comment by maxiwu** [comment]
Indeed very confusing. I am trying to install and deploy natively.
follow steps from official doc and mongo db configuration is not mentioned.
a lot of error just pop up when I start edgex services.

**Comment by drasko** [comment]
@maxiwu sure - this is why [this](https://github.com/edgexfoundry/edgex-go/pull/530) PR is for.

Also, you can follow my blog on building and running EdgeX natively: https://medium.com/mainflux-iot-platform/edgex-in-anger-part-1-installation-5468c52be4d1
