### ISSUE TITLE
Implement mongo backend in support_logging

### ISSUE THREAD

**Issue by feclare** [edgexfoundry/edgex-go#53]
Support logging only have the 'file' backend, mongo still needs to be implemented.

**Comment by chenchix** [comment]
@feclare could you assign this issue to me?

**Comment by chenchix** [comment]
@feclare you can close this issue

**Comment by chenchix** [comment]
[support-logging] Add mongodb support  #78 adds the feature.

**Comment by drasko** [comment]
Thanks @chenchix
