### ISSUE TITLE
rulesengine, logging and consul registry does not start

### ISSUE THREAD

**Issue by maxiwu** [edgexfoundry/edgex-go#533]
I am still trying to run edgex natively. here is my steps:
1. successfully run make build with no errors
2. make run
3. only core command response to ping pong
4. install mongodb and fix configuration.toml (s)
5. create mongodb collections manually. coredata, exportclient, logEntry, logging
6. rulesengine, logging still does not response to ping
7. consul registry still 404 error

The error message from terminal console is:
{"level":"info"","ts:........,"caller":"distro/registrations.go:274","msg":"Starting registration loop"}
ERROR: 2018/09/04 15:54:11 couldn't connect to database: server returned error on SASL authentication 
step: Authentication failed.
...keep repeating...

I can't figure out where does this error come from, which service or which .go file. there is no filename and no line number.

**Comment by tsconn23** [comment]
Did you run the init_mongo script?
https://github.com/edgexfoundry/developer-scripts/blob/master/init_mongo.js

That script creates all of the required collections and credentials in your local Mongo instance. The service credentials match those in this script.

**Comment by maxiwu** [comment]
ok, there is a script. I think you guys are trying to work this out. I have two questions

1. why javascript? we are doing things in GoLang, right? try to run a .js feel out of place. I need to install Node.JS just because I need to run this script? I would rather choose a manual create collections and user/password document over .js
2. this .js script is not mention in the .md. should update that to tell people if you want to run native, run this script.

**Comment by tsconn23** [comment]
@maxiwu Mongo has a native client for javascript. If you have Mongo running, you just type `mongo init_mongo.js`

**Comment by maxiwu** [comment]
After running the script with init_mongo.js
"make run" do not have any exception.
I can see listening on port: 48082, 48090, 48061, 48081, 48060, 48080.

However, 48070, 48071, 48075 are all missing.
http://127.0.0.1:8500/ui also fail.
I try to ping every services, :48075 does not response.

**Comment by mhall119** [comment]
port 8500 is the Consul service, which isn't part of the edgex-go repo, so it wouldn't be something managed by `make run`

Ports 48070 and 48071 belong to the export-distro and export-client services respectively, and those look like they've started. Try calling the `/api/v1/ping` API on both and see if they return a `pong` response.

Port 48075 is used by the support-rulesengine microservice, which hasn't been ported to Go yet and is therefore not part of the edgex-go repo either. You can find it here: https://github.com/edgexfoundry/support-rulesengine

**Comment by maxiwu** [comment]
thank you @mhall119 , I miss understand the relationship between docker build and -go.
