### ISSUE TITLE
pkg/clients, pkg/models - Cleanup naming inconsistencies with complex names

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#535]
As a project, it'd be nice to come to some agreement on how we handle naming Go source files which contain single types with compound names (eg. DeviceProfile). Many of the files in edgex-go originally were ported from Java, hence the convention of putting struct types in separate files with matching filenames. As the code in pkg/clients and pkg/models is meant for external client consumption, we should at minimum strive for some consistency in our approach as we currently have a mix of "_" usage (eg. [pkg/clients/device_profile.go](https://github.com/edgexfoundry/edgex-go/blob/master/pkg/clients/metadata/device_profile.go), [pkg/clients/metadata/schedulevent.go](https://github.com/edgexfoundry/edgex-go/blob/master/pkg/clients/metadata/scheduleevent.go)).

In general, the use of the "_" character is generally avoided in Go source files, as by convention this is used to denote unit test or platform-specific code. The core golang packages generally follow this rule, however there are plenty of exceptions (e.g. [crypto/tls/cipher_suites.go](https://golang.org/src/crypto/tls/cipher_suites.go)).

**Comment by drasko** [comment]
I thought that we did this already on one of the previous meetings, and conclusion was `snake_case`.

**Comment by jpwhitemn** [comment]
@drasko - I thought agreement was achieved on this as well.  @tsconn23 - if we are incorrect or have work to do, please put in the hopper.  If not, close please.
