### ISSUE TITLE
MongoDB test doesn't work

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#536]
After PR #494, MongoDB test doesn't work. This is the output console:

```
$ go test -tags mongoRunning
# github.com/edgexfoundry/edgex-go/internal/pkg/db/mongo
./export_test.go:19:21: TestMongoDB redeclared in this block
	previous declaration at ./client_test.go:22:21
./export_test.go:23:12: undefined: DBConfiguration
./export_test.go:31:16: undefined: NewExportMongoClient
./export_test.go:36:2: undefined: testDB
FAIL	github.com/edgexfoundry/edgex-go/internal/pkg/db/mongo [build failed]
```

If it's fine, I will fix it.

Could be possible to perform `go test -tags mongoRunning` in `edgex-go-master-verify` to avoid this kind of issue happen again?

**Comment by feclare** [comment]
It is not that easy. We need a mongo server running in localhost to be able to run that tests. I thought of creating a docker with mongo and run the tests inside. But I didn't had the time to build it.

This same idea could be used to test any other database supported.

**Comment by tsconn23** [comment]
@jduranf Looks like you're running tests via some other means than `make test`. It looks like you're running tests within the pkg/db/mongo directory itself. Help me understand the approach. I'm not familiar with the `-tags` flag.

**Comment by feclare** [comment]
The tests requiring some infrastructure running to be able to execute the test are protected by a build tag. This way we can have some tests that can be manually executed to test the mongo db backend.

@jduranf suggest that if it could be run in CI it will help to catch errors like this before getting them to master.

Example of how to use build flags:
https://github.com/edgexfoundry/edgex-go/blob/2fc7d402a59c1b2730880341de10e989e65ed7a9/internal/pkg/db/mongo/client_test.go#L7

**Comment by tsconn23** [comment]
Thanks @feclare 

I changed the `make test` target locally to the following and I see the mongo error. Maybe we should just put this in the makefile to always run the tests this way.

```
test:
	go test -cover -tags mongoRunning ./...
	go vet ./...
```

**Comment by feclare** [comment]
I don't like the idea of require having a running mongo(and probably influx) in the development machine to be able to run the tests. It makes setting up an developer environment harder than it is, and we need to simplify it, not make it even more complicated.

My idea to do it without requiring have them running locally and being easy to execute the test was to create a docker that was able to run all tests.
