### ISSUE TITLE
internal/export/distro/format.go:123:18: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by itamarhaber** [edgexfoundry/edgex-go#539]
Getting this after meging from master and running tests. Tending to blame @brandonforster wrt 02202ba32ee093c8ee38ead485d5d4925fd8d6f8 :)

```
...
internal/export/distro/format.go:123:18: multiple-value uuid.NewV4() in single-value context
internal/export/distro/format.go:126:29: multiple-value uuid.NewV4() in single-value context
```

**Comment by andresrinivasan** [comment]
Try updating your glide.lock with

```
- name: github.com/satori/go.uuid
  version: 36e9d2ebbde5e3f13ab2e25625fd453271d6522e
```

**Comment by itamarhaber** [comment]
Or just removing the lock file entirely #panicstoosoon #facepalm

**Comment by caocaocaodou** [comment]
> Try updating your glide.lock with
> 
> ```
> - name: github.com/satori/go.uuid
>   version: 36e9d2ebbde5e3f13ab2e25625fd453271d6522e
> ```

@andresrinivasan my new edgex-go version has no glide.lock, I replace this in my glide.yaml, but it does not work, please tell me the solution. Thank you!

**Comment by jduranf** [comment]
@caocaocaodou you just have to remove your `glide.lock` and `vendor` directory, then run `make prepare` and finally `make`. There is no need to modify any glide file

**Comment by caocaocaodou** [comment]
> @caocaocaodou you just have to remove your `glide.lock` and `vendor` directory, then run `make prepare` and finally `make`. There is no need to modify any glide file

thank you! but my edgex-go directory has no glide.lock , just glide.yaml .  I remove vendor directory, make prepare, then make . It does not work...

**Comment by caocaocaodou** [comment]
> Maybe you have a problem with glide cache. Try removing `~/.glide`, `glide.lock` and `vendor`. And again `make prepare` and `make`.

thank you ! but i am in china, i can not connect to golang.org, glide mirror seems also not work,  so my make prepare always error and it still does not work...
