### ISSUE TITLE
support-logging logfile doesn't follow convention with other services

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#545]
The current support-logging logfile that is specified in the configuration.toml here: https://github.com/edgexfoundry/edgex-go/blob/335486c1d6d1d9e1ca23778dab0a15cd460a6520/cmd/support-logging/res/configuration.toml#L4
doesn't match the rest of the services which prefix the name of the service with `edgex-`.

This isn't a big deal, but changes things slightly for the snap, i.e. see the difference between the sed expression here: https://github.com/edgexfoundry/edgex-go/blob/335486c1d6d1d9e1ca23778dab0a15cd460a6520/snap/snapcraft.yaml#L294  and here: https://github.com/edgexfoundry/edgex-go/blob/335486c1d6d1d9e1ca23778dab0a15cd460a6520/snap/snapcraft.yaml#L299

**Comment by jpwhitemn** [comment]
@xmlviking - Eric, adding to the backlog of work we have for support logging.  Your call if this gets done for Delhi or needs to push to Edinburgh.

**Comment by anonymouse64** [comment]
Fixed in #659
