### ISSUE TITLE
refactor support notifications client

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#55]

**Comment by yanghua** [comment]
finished most work, waiting for issue #50 's PR being merged to fuse together @tsconn23 .

**Comment by drasko** [comment]
@yanghua can this one be closed?

**Comment by yanghua** [comment]
hi @drasko , this issue links to PR #61 , I will handle the conflict soon.

**Comment by yanghua** [comment]
@drasko closing this issue, thank you and all other contributors.
