### ISSUE TITLE
[snap] Missing support-rulesengine

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#552]
While running the blackbox tests against the latest California candidate snap (**0.6.1~pre1-20180907+fb544b5 / 31**), I discovered that we'd never added **support-rulesengine** to the snap.

I've started this work [here](https://github.com/tonyespy/edgex-go/tree/cali-add-rulesengine), however there's an issue with the service not finding its template directory which is causing it to crash:

> 
> [2018-09-12 17:58:52.021] boot - 3406  INFO [main] --- RuleEngine: Starting Drools with drl files from:  edgex/rules
> [2018-09-12 17:58:52.022] boot - 3406  INFO [main] --- RuleEngine: Uploading Drool rules...
> [2018-09-12 17:58:52.022] boot - 3406  INFO [main] --- RuleEngine: ...no rules found to upload
> [2018-09-12 17:58:52.102] boot - 3406  WARN [main] --- MavenSettings: Environment variable M2_HOME is not set
> [2018-09-12 17:58:53.784] boot - 3406  WARN [main] --- AbstractKieModule: No files found for KieBase defaultKieBase
> [2018-09-12 17:58:53.864] boot - 3406  INFO [main] --- KieRepositoryImpl: KieModule was added: MemoryKieModule[releaseId=org.default:artifact:1.0.0-SNAPSHOT]
> [2018-09-12 17:58:54.147] boot - 3406 ERROR [main] --- RuleCreator: Problem getting rule template location.edgex/templates does not exist.
> [2018-09-12 17:58:54.163] boot - 3406 ERROR [main] --- SpringApplication: Application startup failed
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ruleCreator': Invocation of init method failed; nested exception is java.io.FileNotFoundException: edgex/templates does not exist.
> 
>

**Comment by jpwhitemn** [comment]
Ian and Tony, guessing you are targeting this for Delhi release.  Please update if I am mistaken.

**Comment by anonymouse64** [comment]
Yes this is for Delhi, we also will target this for California.

**Comment by anonymouse64** [comment]
This was fixed for California in this PR: https://github.com/edgexfoundry/edgex-go/pull/634

**Comment by anonymouse64** [comment]
Fixed for Delhi in #731

**Comment by tonyespy** [comment]
I'm going to leave this open, but note that since replacing the current rules engine is on the list for Edinburgh, we shouldn't forward port the packaging changes for the old Java-based rules-engine from Dehli, but instead wait until a replacement has been chosen.

**Comment by anonymouse64** [comment]
Actually no we need to add support-rulesengine for Edinburgh because the new go replacement won't be added for Edinburgh.
