### ISSUE TITLE
Use docker to build the snap for CI builds

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#557]
Currently, we need to spin up a 16.04 VM to do the snapcraft builds, as the snap cannot currently be built with any other OS without using some sort of a container (i.e. snapcraft cleanbuild). Instead, we can do run snapcraft inside of a docker container using the official docker image for snapcraft: https://hub.docker.com/r/snapcore/snapcraft/

**Comment by jpwhitemn** [comment]
Ian is this something you are targeting for Delhi or beyond?

**Comment by anonymouse64** [comment]
This is for Delhi and also for California as this is mainly a CI thing and will enable ARM64 builds of the snap.
