### ISSUE TITLE
"flag redefined: confdir" error happens when an external code imports pkg/clients and uses confidir flag

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#562]
When pkg/clients is imported, pkg/clients/types/endpoint.go will import internal/pkg/consul package.
Then, internal/pkg/consul/client.go causes internal/pkg/config is also imported.
In internal/pkg/config/loader.go, confdir flag is defined as a global variable, so this flag would always be occupied.

https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/config/loader.go#L35

`var confDir = flag.String("confdir", "", "Specify local configuration directory")`

Any other external code wants to use pkg/clients package and confidir flag together will cause "flag redefined: confdir" error.

**Comment by tsconn23** [comment]
@cloudxxx8 I agree the import from endpoint.go to the internal package needs to be reworked. Nothing in the exportable edgex-go/pkg should import anything from internal. Maybe I'll have some time to look at this tomorrow.

**Comment by tsconn23** [comment]
Fix is pending. Will review on this morning's Device Service call.

**Comment by cloudxxx8** [comment]
We have made a workaround in Device Service SDK, so it's fine to be pending
