### ISSUE TITLE
Metadata's addressable client doesn't have update, remove function

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#566]
https://github.com/edgexfoundry/edgex-go/blob/master/pkg/clients/metadata/addressable.go
I want to update or remove addressable by client lib in device-sdk-go. But it doesn't have relative function. 
Can I create a branch to add these features? @tsconn23

**Comment by mhall119** [comment]
You can make an HTTP DELETE call to the Addressable in core-metadata to delete it, see https://docs.edgexfoundry.org/core-metadata.html#addressable_id__id_

I believe that you can update it using HTTP PUT (or maybe POST) if you pass it the addressable ID

**Comment by weichou1229** [comment]
Yes, but I want to update or remove device by client lib because it already integrate with Cunsul.

**Comment by jpwhitemn** [comment]
Assigning this to @tsconn23 and tentatively put towards Delhi but his call on whether this stays Delhi or gets pushed back.  Would be a good feature for someone new to the project to work on.

**Comment by tsconn23** [comment]
@weichou1229 went ahead and did the work. We merged in the PR this morning. Closing issue.
