### ISSUE TITLE
Implement upload function for metadata’s device profile client

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#572]
I want to implement this feature for upload the pre-defined device profile, which is used in device-sdk-go.
* /api/v1/deviceprofile/uploadfile `UploadFile(yamlFilePath string) (string, error) `
* /api/v1/deviceprofile/upload `Upload(yamlString string) (string, error) `

**Comment by jduranf** [comment]
Why not using Add()?

**Comment by weichou1229** [comment]
Because metadata already have upload function , we can use it directly without parse file and convert to deviceProfile struct.

**Comment by cloudxxx8** [comment]
@jduranf we have already had YAML parser in core-metadata, so it might be better to reuse it.  Also, C Device Service SDK uploads YAML to core-metadata directly, and we would like to make the behavior consistent.
