### ISSUE TITLE
exprot-distro don't push events to rules-engine using 0.7.0 images in User Model

### ISSUE THREAD

**Issue by AhaEdgar** [edgexfoundry/edgex-go#575]
When I use the 0.7.0 images in User Model, all steps followed by "EdgeX Demonstration API Walk Through", I find a problem about 'rules engine' or 'export distro '.
-----
If there is a device :  
-----
```
device id : "5ba31f1c9f8fc20001a6b6ad"   
device name : "countcamera1" 

```
-----
now I add a rule for the device like this:
-----
```
{
	"name": "humancount_rules_test#1",
	"condition": {
		"device": "5ba31f1c9f8fc20001a6b6ad",
		"checks": [{
			"parameter": "humancount",
			"operand1": "Integer.parseInt(value)",
			"operation": ">",
			"operand2": "1"
		}]
	},
	"action": {
		"device": "5ba31f1c9f8fc20001a6b6ad",
		"command": "5ba31ee59f8fc20001a6b6a8",
		"body": "{\\\"depth\\\":\\\"3\\\"}"
	},
	"log": "humancount_rules_test"
}
```
-----
then, I add a new event to "core data" like this :
-----

```
{
	"device": "5ba31f1c9f8fc20001a6b6ad",
	"readings": [{
		"name": "humancount",
		"value": "4"
	}, {
		"name": "caninecount",
		"value": "3"
	}]
}
```
or

```
{
	"device": "countcamera1",
	"readings": [{
		"name": "humancount",
		"value": "4"
	}, {
		"name": "caninecount",
		"value": "3"
	}]
}

```
-----
the expected results:
-----
```
1. "docker logs -f  <rules engine> " will show some info about the "humancount", because "export distro" will sent the envet to "rules engine".

2. "docker logs -f <command>" will show some info about the action of the rules named "humancount_relus_test#1", because "rules engine" will send the action to "command".
```
-----
the actual results
-----

exprot-distro logs
```
2018-09-20T04:55:05.672000000Z INFO: 2018/09/20 04:55:05 Event received: {"id":"5ba328290e360800018e2500","pushed":0,"device":"5ba31f1c9f8fc20001a6b6ad","created":1537419305655,"modified":0,"origin":0,"schedule":null,"event":null,"readings":[{"id":"5ba328290e360800018e2501","pushed":0,"created":1537419305655,"origin":0,"modified":0,"device":"5ba31f1c9f8fc20001a6b6ad","name":"humancount","value":"4"},{"id":"5ba328290e360800018e2502","pushed":0,"created":1537419305655,"origin":0,"modified":0,"device":"5ba31f1c9f8fc20001a6b6ad","name":"caninecount","value":"3"}]}
2018-09-20T04:55:05.673658000Z INFO: 2018/09/20 04:55:05 EVENT
```

However,
the actual results do not get these expected results. There's nothing like exported results in "relus-engine" and "command". I make sure the "`export.client=true`" config in consul. These phenomena indicate that the event is not pushed to the rules engine. However, the "rules engine service" has registered in “export registration”. All the steps followed by "https://docs.edgexfoundry.org/Ch-Walkthrough.html" .

is there some bugs in “rules engine” or “export distro”？or I have make some mistakes. 

`GET http://192.168.254.130:48071/api/v1/registration` 

```
[
    {
        "id": "5ba2f075fd4ca800013010c3",
        "created": 1537405045361,
        "modified": 0,
        "origin": 0,
        "name": "EdgeXRulesEngine",
        "addressable": {
            "created": 0,
            "modified": 0,
            "origin": 0,
            "id": null,
            "name": "EdgeXRulesEngineAddressable",
            "protocol": "ZMQ",
            "method": "POST",
            "address": null,
            "port": 0,
            "path": null,
            "publisher": null,
            "user": null,
            "password": null,
            "topic": null,
            "baseURL": null,
            "url": null
        },
        "format": "SERIALIZED",
        "filter": {},
        "encryption": {},
        "enable": true,
        "destination": "ZMQ_TOPIC"
    }
]

```

**Comment by AhaEdgar** [comment]
Register for JSON formatted data to be sent to MQTT topic (www.cloudmqtt.com). In this way, I can get the events/readings in www.cloudmqtt.com. Maybe just can't push events/readings to the rules engine？

**Comment by jpwhitemn** [comment]
This is a bug - the event does get processed by export distro and the rules engine is registered appropriately, but the distro service does not send it back out on ZeroMQ connector to rules engine service.  In fact, registration.go even says ZeroMQ not supported.

**Comment by jpwhitemn** [comment]
I have a fix for this.  Waiting for @tsconn23 to complete his config v2 work in export distro.
