### ISSUE TITLE
Docs verify job failing on California

### ISSUE THREAD

**Issue by JPWKU** [edgexfoundry/edgex-go#576]
https://jenkins.edgexfoundry.org/job/edgex-go-docs-california-verify-docs/ has been failing since Sept 13th with a sphinx error.  There have been no environment changes but a new release of sphinx was posted on Sept 12th which may be a good place to look.
It's possible we will need to refactor the docs on california or pin back to an older version of sphinx.
https://pypi.org/project/Sphinx/#history

**Comment by SteveOss** [comment]
Looks like the build image needs updating to pull a specific version of Sphinx. Will check how you specify a version to "pip install" ...
