### ISSUE TITLE
Add additional EdgeX Micro Service Management (MSM) capabilities. 

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#581]
- Add new endpoint to the notifications micro-service as part of the MSM (Micro-Service Management) API, the System Of Record (SOR) for configuration, and which will work with the SMA service when it (SMA) needs to fetch latest configuration from a given micro-service (in this case, notifications).
- Update MSM service module to reflect the most up-to-date data resulting from processing the incoming request
- Add capability to determine, process, and load contents of the SMA's manifest file.
- Add functionality for performing operations on a micro-service by a delegated call such as to start and stop a micro-service.
- Add capability to get metrics for EdgeX micro-services, starting with notifications.

**Comment by akramtexas** [comment]
- The relevant work is being done on a branch of this fork of the mono repo: [Construction Site](https://github.com/akramtexas/edgex-go/commits/msm_api)

**Comment by akramtexas** [comment]
- Some relevant REST client (Postman) test data for handy reference:
[operation URL](http://localhost:48090/api/v1/operation)

> {
   "action":"stop",
   "services":[
   	  "edgex-core-metadata",
      "edgex-support-notifications",
      "edgex-core-data"
   ],
   "params":[
   	"graceful"
   	]
}

**Comment by anonymouse64** [comment]
Is this for Delhi?

**Comment by jpwhitemn** [comment]
Yes Ian - this is for Delhi.

**Comment by anonymouse64** [comment]
Okay, I've filed an item to add this to the snap for Delhi as #624.
