### ISSUE TITLE
support-logging logs aren't stored in database

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#584]
Currently support-logging logs aren't stored in "MongoDB" database and, which is worst, if using "File" database then the log file content is mixed with raw logs messages and json log messages.

This lines in internal/support/logging:
```
// Setup local service logging to file.
LoggingClient = logger.NewClient(internal.SupportLoggingServiceKey, false, Configuration.LoggingFile)
```
Should be changed with something like:

```
// Setup Logging
logTarget := setLoggingTarget()
LoggingClient = logger.NewClient(internal.SupportLoggingServiceKey, true, Configuration.LoggingRemoteURL)
```

What do you think?
Maybe this can be done as part of config V2 effort?

**Comment by tsconn23** [comment]
Related https://github.com/edgexfoundry/edgex-go/issues/545
