### ISSUE TITLE
Inconsistent keys in configuration files

### ISSUE THREAD

**Issue by SteveOss** [edgexfoundry/edgex-go#59]
In the various service configuration (json) files have inconsistent key capitalisation. 
For example just looking at the Consul related keys there are:

Consulcheckaddress and ConsulCheckAddress
Consulhost and ConsulHost
Consulprofilesactive and ConsulProfilesActive
Consulport and ConsulPort

Looks like the core-data config files are those missing capitalisation.

**Comment by tsconn23** [comment]
Code change has been merged.
