### ISSUE TITLE
Copyright header leakage into godoc

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#594]
Many of the package in edgex-go are leaking copyright headers to generated by godoc, as seen in the following edgex-go packages:

 * [pkg/models](https://godoc.org/github.com/edgexfoundry/edgex-go/pkg/models)
 * [pkg/clients/types](https://godoc.org/github.com/edgexfoundry/edgex-go/pkg/clients/types)
 * [pkg/clients](https://godoc.org/github.com/edgexfoundry/edgex-go/pkg/clients)
 * [pkg/clients/metadata](https://godoc.org/github.com/edgexfoundry/edgex-go/pkg/clients/metadata)
 * pkg/clients/*
 
This leakage can be fixed by making sure there's a blank line between file copyright header comments and godoc.

**Comment by jpwhitemn** [comment]
@brandonforster can you clean these up this week when you are adding some of the unit tests?

**Comment by brandonforster** [comment]
@jpwhitemn I'll take care of it!

**Comment by tsconn23** [comment]
Moved to new go-mod-core-contracts repo https://github.com/edgexfoundry/go-mod-core-contracts/issues/4
