### ISSUE TITLE
BUG: core-metadata not loading V2 config file in docker container

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#605]
When the edgex-core-metadata container starts, the following error is logged.

```
ERROR: 2018/09/28 22:37:54 could not load configuration file (/res/configuration-docker.toml): open /res/configuration-docker.toml: no such file or directory
ERROR: 2018/09/28 22:37:55 edgex-core-metadata: Service bootstrap failed!
```

This is because the following line should be calling LoadFromFileV2
https://github.com/edgexfoundry/edgex-go/blob/8f04e830a51f9697a4f65c08ab82fb1637663831/internal/core/metadata/init.go#L106

**Comment by jpwhitemn** [comment]
Just ran into this :) - looks to be isolated to just Metadata.  All other Config V2 updated services seem to work fine.
