### ISSUE TITLE
Update build/install instructions in top level README

### ISSUE THREAD

**Issue by andresrinivasan** [edgexfoundry/edgex-go#607]

**Comment by jpwhitemn** [comment]
@mhall119 - do you think this is something you can help clean up??

**Comment by mhall119** [comment]
Absolutely! What specifically needs to be updated?

**Comment by jpwhitemn** [comment]
Michael - perhaps if we organize it similar to what you did for documentation with pointers to the documentation (check out https://github.com/nats-io/gnatsd for a detailed readme):
-what you need to use EdgeX (install docker and docker compose)
-what you need to develop or contribute EdgeX (go, 0MQ lib, probably an editor - we use GoLand)
-how to build the project (make prepare, make build, etc.)
-how to run the project (make run)
-how to run via docker...
etc...

**Comment by andresrinivasan** [comment]
This specific issue is closed.
