### ISSUE TITLE
Simplify clients code

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#609]
Currently the EdgeX clients code in pkg/clients are composed by lots of functions copy and pasted with minor modifications.

This can be simplified, which will make the code more easy to maintain and also will reduce the probability of any bug.

**Comment by tsconn23** [comment]
@jduranf After merging the PRs shown above, is there still work to be done here or can we close this?

**Comment by jduranf** [comment]
The only missing things to do are:

1. Remove the [scheduler client](https://github.com/edgexfoundry/edgex-go/tree/master/pkg/clients/scheduler), as it's not used and the API doesn't match with the API implemented in support-scheduler
2. Add pkg/clients/export/client. Currently there is a [TODO](https://github.com/edgexfoundry/edgex-go/blob/master/internal/export/distro/client.go#L19)

The first point is easy to do, but the second point I don't know if it's worth it, because I'm not sure if export will be refactored or not.

What do you think?

**Comment by tsconn23** [comment]
@xmlviking Do you have any input on Joan's first point above? Are there any external applications (like Device Services, etc) that would be using this and break if we remove it?

@jduranf I'd leave the 2nd point alone for now. Fede and I were going back and forth about that but with the developing plan to replace export services, wouldn't worry about it.

**Comment by jduranf** [comment]
Done!
