### ISSUE TITLE
Export Distro's ZeroMQ port for receiving data from CoreData should not be hard coded

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#612]
The port number 5563 for receiving data from Core Data should not be hardcoded in https://github.com/edgexfoundry/edgex-go/blob/master/internal/export/distro/zeromq.go

**Comment by tsconn23** [comment]
I actually came across this while working on ConfigV2 #621 . Will be included in upcoming PR.
