### ISSUE TITLE
move notification struct from support notification client to core domain models dir 

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#62]
as a stipulative rule, seems like all models are defined into `core/domain/models` dir. The `Notification` should also be there just like `Schedule`.  @drasko do you approve this ?

**Comment by drasko** [comment]
I can not tell for the core, @jpwhitemn @tsconn23 and @feclare are maintaining this part. But I do not like this dir structure - shared models should be pulled out of the `domain` dir and kept in the root dir

**Comment by feclare** [comment]
@yanghua 
In this case I think its place is where it is. Is a struct that only is used for functions in support/notifications-client 
And in case of being moved, it should be support/domain
@drasko 
I also prefer if we move the the core/domain files to core/ and support/domain to support/. If @jpwhitemn and @tsconn23 also agree I can do it.

**Comment by yanghua** [comment]
@feclare OK, I create this issue is that `Schedule` and `ScheduleEvent` models are that dir. And these models from clients should follow same stipulative rule. Hope for getting consensus of opinion.
