### ISSUE TITLE
Add log level filter in logging system

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#628]
Currently all logs are stored/transmitted/printed regardless of their log level. Should be fine to add the option to set the log level in the log client.

If it's fine, I will work on it.

**Comment by jpwhitemn** [comment]
Joan - you may want to connect with @xmlviking.  He is going to be working on #484 and some of this work might be related.

**Comment by jduranf** [comment]
@jpwhitemn I already created PR #629 which will add the option to set the log level, then configuration should be modified in order to set the log level. For me it's fine if @xmlviking implements this second part.
I implemented this feature because the logs in device-sdk-go are too much verbose.
