### ISSUE TITLE
Integrate Redis implementation with logging

### ISSUE THREAD

**Issue by andresrinivasan** [edgexfoundry/edgex-go#630]
Logging is pretty sparse right now...

**Comment by jduranf** [comment]
@andresrinivasan, before implementing Redis into logging, logging should be refactored in order to use `internal/pkg/db`

**Comment by andresrinivasan** [comment]
@tsconn23 Please assign to me

**Comment by jduranf** [comment]
Closing as #863 duplicate. Please reopen if I'm wrong.
