### ISSUE TITLE
Expose Redis status to Consul

### ISSUE THREAD

**Issue by andresrinivasan** [edgexfoundry/edgex-go#631]
The handler code necessary for Consul to know the status of Redis must be implemented.

**Comment by andresrinivasan** [comment]
@tsconn23 Please assign to me

**Comment by tsconn23** [comment]
@andresrinivasan Is this still relevant? If not, please close. If so, please provide some details.

**Comment by andresrinivasan** [comment]
Yes. If Consul is how we manage an EdgeX deployment you'll want visibility to the DB.

**Comment by andresrinivasan** [comment]
#fuji

**Comment by tsconn23** [comment]
@andresrinivasan Does the following PR addresses this issue? If not, please update the description if there's additional work to be done.
https://github.com/edgexfoundry/edgex-go/pull/1359

**Comment by andresrinivasan** [comment]
No, this issue is entirely about Redis being a good citizen and telling Consul its status.

**Comment by tsconn23** [comment]
@andresrinivasan Is this still on your Fuji roadmap? If so, proposed timeframe? What does it entail?

**Comment by andresrinivasan** [comment]
Yes. End of September. I was going to look at what was implemented for Mongo and try to emulate that.

**Comment by tsconn23** [comment]
@andresrinivasan Should I bump this to Geneva?

**Comment by andresrinivasan** [comment]
Sigh. Yes.

**Comment by bnevis-i** [comment]
Redis health check was introduced inhttps://github.com/edgexfoundry/docker-edgex-consul/pull/26
