### ISSUE TITLE
How to add a new devices during its deviceservice running?

### ISSUE THREAD

**Issue by AhaEdgar** [edgexfoundry/edgex-go#637]
Assuming there is an already running `device-service-A`, a new device is now added to EdgeX. 
there are two ways to add a new device：

1. add the `device instance` to `metadata` directly. Then, `metadata `will periodic call the `device-service-A` REST API ("/discovery") to update its local device list. Lastly, `device-service-A` could know that a new device has been added.
`User--add a new device instance-->metadata----notification----->device-service-A`

2. add the device instance to `device-service-A`. `device-service-A` should  provide a REST API to add a new device. Then, `device-service-A` will call `metadata `to build a new device instance and update local device list. Lastly, `device-service-A` could konw that a new device has been added.
`User--add a new device-->device-service-A---add a new device instance----->metadata`

The above two methods are my guess. If there is something wrong, please specify. Thanks! : )

**Comment by jduranf** [comment]
When you add a device in metadata, the device-service is notified using a callback.
Also a device-service can add new devices in metadata if they are defined in configuration or discovered
