### ISSUE TITLE
Download jar files from nexus for snap java services

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#644]
As we still have a few java services left in the snap, mainly `support-scheduler`, `support-rulesengine`, and `device-virtual` we build this from scratch using the maven snapcraft plugin. However this takes a long time to build these, and the jars are already built and published to the staging nexus [here](https://nexus.edgexfoundry.org/content/repositories/staging/org/edgexfoundry/support-scheduler/) (for support-scheduler for example).  

We should instead just download these jar files into the snap rather than build them from scratch.

CC @tonyespy

**Comment by anonymouse64** [comment]
One question about this is whether we should use `SNAPSHOT` or `STAGING`.

**Comment by anonymouse64** [comment]
@JPWKU can you comment on whether we should download jars of the Java services from `SNAPSHOT` or from `STAGING` on the nexus?

I think for master we should use the more "recent" one, while after the branch cut we should use the more stable version for the release. However, I'm not familiar enough with the terminology to know which one is which...

**Comment by JPWKU** [comment]
My personal opinion is that since SNAP is packaging that we should pull
from staging (they go through blackbox tests whereas SNAPSHOTS do not).
There is an issue with pulling from staging on nexus2 which has a bug where
they are ordered backwards.  I have a workaround for this in the docker
packaging.  Lets discuss on rocketchat.

**Comment by anonymouse64** [comment]
We will take this up again after Delhi

**Comment by anonymouse64** [comment]
There's only one java service left in the Edinburgh snap, and it's future status in the snap is questionable so I think it's reasonable to just close this and continue building the jars from source as is.
