### ISSUE TITLE
Spread the EdgeX Micro Service Management (MSM) API to the CoreCommand service.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#654]
- The gist of having EdgeX Micro Service Management (MSM) API spread to the CoreCommand service is to add the capability of delegating to the CoreCommand service the request (to the SMA) for that service's configuration info and for its metrics info.
- Initially, this existed only for the support-notifications service.
- Work per this Issue is taking place on the following branch: [Construction site](https://github.com/akramtexas/edgex-go/commits/spread_msm_api).

**Comment by tsconn23** [comment]
Adding some details based on our conversation. This is the agreed upon service to start with and after this one, propagation to the rest of the services should be an exercise in repetition.

1.) Implement /api/v1/metrics route in the service
2.) Add the above route to the RAML
3.) Create the MgmtClient interface with associated type (recommend /pkg/clients/command/mgmt.go)
     Should contain functions for 
        FetchConfiguration() (string, error)
	FetchMetrics() (string, error)
    ** Consistent with notifications client from PR #620 **
4.) Follow the pattern in the command client for initialization of the type and respective Monitor
5.) Integrate command client into SMA and test end to end.

**Comment by akramtexas** [comment]
- Starting work (in this series of Issues) with the [Issue for CommandClient](https://github.com/edgexfoundry/edgex-go/issues/654)
