### ISSUE TITLE
Install and Deploy using Docker fails due to Glide dependency

### ISSUE THREAD

**Issue by antoniomtz** [edgexfoundry/edgex-go#657]
Golang dependencies are required for compiling the services.
Glide must be installed to pull dependencies.
I'd just update the README and add Glide as pre-requisite. 

Thanks,
Antonio

**Comment by jpwhitemn** [comment]
@mhall119 attention.  Michael - is this something you can address when you rework the READMe page?  Thanks

**Comment by mhall119** [comment]
Instead of having this duplicated in the README and in the docs, can we shorten the README to be just a "Quick Start" running the existing docker images, and then point to the docs for instructions on building and running your own?
