### ISSUE TITLE
Change Reading Value type from string to object (interface)

### ISSUE THREAD

**Issue by antoniomtz** [edgexfoundry/edgex-go#666]
For the readings model, specifically "value":{"type":"string","required":false,"title":"value"} , it is assumed that the device will always emit a single value. 
Example: {name:"count", value:"5"} or {name:"temp", value:"50"}

If the device emits a more complex type such a json object ( Example: {name:"people", value: { age: "30", gender: "Male", emotion: "happy" } } ), right now , the only way is to covert the json object to string.

Having Value type as object will allow more flexibility in the data passing across.

**Comment by jpwhitemn** [comment]
@antoniomtz - why is this necessary versus the EdgeX way of having an Event with 3 Readings (one each for age, gender and emotion)?  Would encoding this in a binary 64bit encoded string work for you (we are looking to support CBOR in Edinburgh release)?  Having an object requires the export and other north side services to also know how to deal with the object structure type as well.

**Comment by antoniomtz** [comment]
@jpwhitemn The only reason that this is necessary, it's because a some devices generate more that one attribute associated to a particular entity. 
For example:
Computer vision : { person: 1, age: 30, gender: "Male", emotion: "happy", ... }
RFID: { tag: "xyz", location: "x", facility: "w", ... }

As you mentioned, one way to solve it, it's to have one Event and a Reading per attribute. This however, will require extra modifications on existing device services, and apps on the north side to satisfy this schema.

The other easy solution is to encode the json object into base64, and decode it on the north side as you said. This could be a light lift from existing services.

Both ways are valid, I agree changing the type of Value property to object will impact other services and this may be a major change.

**Comment by jpwhitemn** [comment]
Closing for now.  Will re-investigate with additional requirements or as needs evolve post Edinburgh
