### ISSUE TITLE
support-notifications audit

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#671]
While working on Config V2 integration with the support-notifications PR #660 I noticed that what appears to be the function whereby the process to serve distributions is never called. I placed a TODO [here](https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/notifications/normal_distribution.go#L24) in the code. Similarly the [function](https://github.com/edgexfoundry/edgex-go/blob/master/internal/support/notifications/normal_resend.go#L24) to start the monitoring process for resends is never called.

Since this service was recently converted from Java into Go, I suggest based on the above that a functional audit needs to be conducted that should include:
- Some process for sending notifications is active
- Notifications are being sent to the DB and/or email
- Notifications are being retried in case of failure
- Notifications are limited by a max # of retries
- Retries are attempted on an internal schedule.

**Comment by anonymouse64** [comment]
Do the black box tests cover this functionality in support-notifications?

**Comment by tsconn23** [comment]
I do see some files in the [repo](https://github.com/edgexfoundry/blackbox-testing/tree/master/bin/postman-test) under DataDumps and collections, but nothing under the data file. This means that there's at least been some work to define the test data, but it doesn't look like sample requests have been prepared. Will loop in @cloudxxx8 @andyf1967

**Comment by tsconn23** [comment]
@weichou1229 @cloudxxx8 It should be organized in a standardized way though. Can we split the requests into their own file as we've done for everything else so that the methodology is consistent?

**Comment by weichou1229** [comment]
@tsconn23 I create a PR to add data file. https://github.com/edgexfoundry/blackbox-testing/pull/89
