### ISSUE TITLE
Scheduler should return 404 if schedule not found

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#675]
Call to /info/:name results in an empty schedule instead of nil and an HTTP 404 error.  What is returned is {"created":0,"modified":0,"origin":0,"id":"","name":null,"start":null,"end":null,"frequency":null,"cron":null,"runOnce":false}.
The log file does appropriately indicate:  edgex-support-scheduler | WARN: 2018/10/14 01:22:03 can not find a schedule context with schedule name : scrub-aged-events

**Comment by tsconn23** [comment]
Fixed. Now returns a 404.
