### ISSUE TITLE
System management Agent config - returns only service config found

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#678]
On a call such as http://localhost:48090/api/v1/config/edgex-support-notifications,edgex-core-data, the SMA would return {Service: name, Config: {}} for those services it finds.  If Notifications was up and Core Data was not, it would return:  {"Service":"edgex-support-notifications","Config":{"Clients":{"Logging":{"Host":"localhost","Port":48061,"Protocol":"http"}},"Databases":{"Primary":{"Host":"localhost","Name":"notifications","Password":"","Port":27017,"Timeout":5000,"Type":"mongodb","Username":""}},"Logging":{"EnableRemote":false,"File":"./logs/edgex-support-notifications.log"},"Registry":{"Host":"localhost","Port":8500,"Type":"consul"},"ResendLimit":2,"Service":{"BootTimeout":30000,"CheckInterval":"10s","ClientMonitor":15000,"Host":"localhost","Port":48060,"Protocol":"http","ReadMaxLimit":1000,"StartupMsg":"This is the Support Notifications Microservice","Timeout":5000},"Smtp":{"Host":"smtp.gmail.com","Password":"mypassword","Port":587,"Sender":"jdoe@gmail.com","Subject":"EdgeX Notification"}}}
It would not indicate that there is no config for edgex-core-data (or even that it was a valid service).  It should return null for those services not available or where the service does not have any config.  It shouldn't leave the service name out of the return collection.

**Comment by jpwhitemn** [comment]
Errors should also be return in the case there is an issue on response from one service

**Comment by akramtexas** [comment]
Will address this shortly.

**Comment by akramtexas** [comment]
- This bug has, in the past 24 hours, actually been addressed and fixed as part of the following PR which was in flight already: [PR #672](https://github.com/edgexfoundry/edgex-go/pull/672).

**Comment by akramtexas** [comment]
@jpwhitemn Let's please sync up sometime to ensure that the needful has been addressed 👍

**Comment by akramtexas** [comment]
- On further testing, I do notice that if a service is down, for example the edgex-config-seed service, then a response as follows is returned for that service:
> "edgex-config-seed": ""
- The call was: 
> http://localhost:48090/api/v1/metrics/edgex-config-seed,edgex-support-logging,edgex-core-metadata,edgex-support-notifications,edgex-core-data,edgex-core-command,edgex-export-client,edgex-export-distro

**Comment by akramtexas** [comment]
This issue has been addressed. Should a service be inaccessible, the SMA will report the response, for example the following:

`{
    "Configuration": {
        "edgex-core-command": "edgex-core-command get config error: Get http://localhost:48082/api/v1/config: dial tcp [::1]:48082: connect: connection refused",
        "edgex-core-data": "edgex-core-data get config error: Get http://localhost:48080/api/v1/config: dial tcp [::1]:48080: connect: connection refused",
        "edgex-core-metadata": "edgex-core-metadata get config error: Get http://localhost:48081/api/v1/config: dial tcp [::1]:48081: connect: connection refused",
        "edgex-export-client": "edgex-export-client get config error: Get http://localhost:48071/api/v1/config: dial tcp [::1]:48071: connect: connection refused",
        "edgex-export-distro": "edgex-export-distro get config error: Get http://localhost:48070/api/v1/config: dial tcp [::1]:48070: connect: connection refused",
        "edgex-support-logging": "edgex-support-logging get config error: Get http://localhost:48061/api/v1/config: dial tcp [::1]:48061: connect: connection refused",
        "edgex-support-notifications": "edgex-support-notifications get config error: Get http://localhost:48060/api/v1/config: dial tcp [::1]:48060: connect: connection refused"
    }
}`
