### ISSUE TITLE
include manifest.yaml in the snap

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#684]
If one sets the `SNAPCRAFT_BUILD_INFO` environment variable to 1 when building the snap, snapcraft will include a `manifest.yaml` file inside the snap which lists all of the packages, etc. that were used to build the snap. This is turned on automatically when building the snap using build.snapcraft.io or launchpad.net, but since we don't use those it's not turned on.

All we need to do to turn this on is add that environment variable to https://github.com/edgexfoundry/edgex-go/blob/14173639dff77434f23ecc64a352c11e18aa5d37/snap/entrypoint.sh#L1-L20

**Comment by tsconn23** [comment]
@anonymouse64 Hold off on this. That file is going away. See issue #673

**Comment by tsconn23** [comment]
@anonymouse64 Oh, maybe I'm mistaken. I saw "manifest.toml" for "manifest.yaml". These are two different things I guess.
