### ISSUE TITLE
core-data and core-command cpu useage close to 100%

### ISSUE THREAD

**Issue by sjt-xfwh** [edgexfoundry/edgex-go#702]
core-data and core-command cpu useage close to 100%
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 3076 root      20   0   28368  11296   7668 S  98.7  0.3   8655:12 core-data
 3388 root      20   0   13480   7960   5128 R  98.0  0.2   8654:36 core-command

edgex-go version 0.6.0 
system: ubuntu 18.04
hardware: dell edge gateway 3000
run as docker
edgexfoundry/docker-core-command-go         0.6.0               8a9c61101c31        3 months ago        8.35MB
edgexfoundry/docker-core-data-go            0.6.0               ea2f1fe6e8bc        3 months ago        16.1MB

**Comment by jpwhitemn** [comment]
@sjt-xfwh - please see issue #384.  I believe this was fixed with 0.6.1.  Please resubmit with additional details if this is not the case.

**Comment by sjt-xfwh** [comment]
@jpwhitemn thanks
