### ISSUE TITLE
snap's license info is "unset"

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#711]
The license field for the snap is currently "unset":
```bash
$ snap info edgexfoundry | grep license
license:   unset
$
```
Because the project ships a few dependencies which aren't under the apache license, we can't just say that the snap is apache, as it's really multiple licenses. As such, we should use the SPDX license "other", as currently SPDX doesn't have a way of specifying multiple licenses.

**Comment by popey** [comment]
You totally can set multiple licenses in the store. Go to https://snapcraft.io/edgexfoundry/listing and scroll down. You'll find this dialog..

![screenshot from 2018-10-19 13-12-26](https://user-images.githubusercontent.com/1841272/47217578-bcc42780-d3a0-11e8-84ad-ba2cbba2d882.png)

You should be able to set the license appropriately there. If not, then it's likely a bug in the store. If it doesn't fully support what you need in the short term, then I'd recommend setting the store text description to a piece of plain text describing the licenses used.

**Comment by anonymouse64** [comment]
@popey can this be set from the `snapcraft.yaml` or does it have to be done in the store?

**Comment by popey** [comment]
Currently you'll need to edit it in the store. The feed from the snapcraft.yaml to the store hasn't landed yet for licenses. It will, but right now, you'll need to edit it in the store.

**Comment by kyrofa** [comment]
> can this be set from the snapcraft.yaml or does it have to be done in the store?

The ability to specify this in the snapcraft.yaml is in snapcraft's `edge` channel, but is not yet within a stable release ([relevant PR](https://github.com/snapcore/snapcraft/pull/2318)). Note also that metadata changes in the snapcraft.yaml (summary, description, etc.) only effect the store on first push. Subsequent pushes, even if the snap contains updated metadata, will not update the metadata on the store. If you change metadata in the snap and want it to take effect in the store, you'll need to use `snapcraft push-metadata` to do it (see `snapcraft push-metadata --help` for more details). I assume `license` follows the same rules as the rest of the metadata, although I've not tested to be sure.

**Comment by anonymouse64** [comment]
@JPWKU has set the license to "Other Open Source" through the store, and we now do all builds with `snapcraft push-metadata --force` so that the source of truth going forward will be snapcraft.yaml.
Note that we won't be able to upgrade the version of snapcraft we use just yet as we use snapcraft from docker, which hasn't been updated yet. See also issue #888
