### ISSUE TITLE
Scheduler/Metadata Interaction Error During "Make Run"

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#725]
When I execute "make run" from the command line, I usually see errors indicating that the scheduler is trying to call metadata for default schedule information, but metadata isn't ready to serve requests yet. Example:

```
ERROR: 2018/10/29 16:41:14 error connecting to metadata and retrieving schedules Get http://localhost:48081/api/v1/schedule: dial tcp [::1]:48081: connect: connection refused
ERROR: 2018/10/29 16:41:14 error connecting to metadata and retrieving schedule events: Get http://localhost:48081/api/v1/scheduleevent: dial tcp [::1]:48081: connect: connection refused
INFO: 2018/10/29 16:41:14 scheduler could not find schedule id with schedule with name : midnight
ERROR: 2018/10/29 16:41:14 error trying to add schedule to core-metadata service: Post http://localhost:48081/api/v1/schedule: dial tcp [::1]:48081: connect: connection refused
ERROR: 2018/10/29 16:41:14 scheduler could not find schedule id with schedule event name : scrub-pushed-events
```

Do we need retries here?

**Comment by vishwasrao** [comment]
Hi,
You to run init script 
[](https://github.com/edgexfoundry/developer-scripts/blob/master/init_mongo.js)
It will populate all required data.
then execute "make run"
It should start successfully.

**Comment by xmlviking** [comment]
@vishwasrao - a PR is in the works that should address this in the Delhi build.  It's not in the current master version yet.  After this PR get's merged you should not have any issues.   Issue was around core-metadata not being fully up before support-scheduler attempted to contact it.    I put in a retry wait group which should fix this issue. :)   What is amazing is the entire stack is up in 2 secs.  :)
