### ISSUE TITLE
SMA doesn't work with the snap

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#751]
The new `sys-mgmt-agent` microservice in EdgeX doesn't work with snaps, as the only 2 options for setting the configuration.toml are `os` and `docker`, neither of which are compatible with the snap. This issue tracks a few related issues that should all be fixed at the same time I think.

The `docker` implementation uses the docker compose file which isn't available inside the snap (because the services aren't deployed as containers in the snap).
The `os` implementation uses `ps` to get the PID of the microservices and then manually kills those processes. This also isn't compatible with the snap because doing so inside snap confinement requires the interface `process-control`, and also isn't necessary because the EdgeX microservices are actually systemd services inside the snap and as such can be started/stopped outside of the snap using `systemctl` (which is from systemd), and from inside the snap using `snapctl` (which is from snapd).

Also, the implementation should at least be changed to use the `ExecutorClient` interface for starting, stopping and restarting. Currently the interface is only used for stopping services, and also unconditionally attempts to use the docker functions to start/restart services so sending a start/restart request to `sys-mgmt-agent` will fail inside the snap. 

Finally, the implementation should also provide for two new types of operations managing the other services, the ability to disable a service and enable a service. This currently wouldn't be used for docker as to my knowledge docker-compose doesn't automatically start things up at boot, but for the snap all the services come up automatically, and there's a common distinction between stopping a currently running service now but letting it come up automatically on reboot, and stopping it permanently from ever coming up again without explicit user interaction (that interaction being the act of enabling the service again).

Thus the following things should be fixed:
- [ ] A new "snap" format should be allowed to be specified from configuration.toml that is implemented in go that uses `snapctl`
- [ ] The implementation of starting and restarting services should be abstracted out to the `ExecutorClient` interface
- [ ] Implement Disable/Enable of services

**Comment by anonymouse64** [comment]
I implemented most of this in a branch : https://github.com/anonymouse64/edgex-go/tree/bugfix/751

The only part missing from that branch is integration for enable/disable/restart within the router.

For Delhi we now have two options, to take the full approach I implemented above, or to take the pared down version here: https://github.com/edgexfoundry/edgex-go/pull/750 which only implements basic support for stopping services in the snap.

**Comment by anonymouse64** [comment]
Okay, [my branch](https://github.com/anonymouse64/edgex-go/tree/bugfix/751) (same as above, but tweaked and rebased) implementing all of the above is done and tested with the snap. I think this should be taken up for Delhi, at least for a dot release if not the main release. 
@tsconn23 and @akramtexas thoughts?

**Comment by akramtexas** [comment]
@anonymouse64 After doing some due diligence to make sure I'm not overlooking anything, my recommendation is to please treat the Delhi Dot Release as a vehicle for handlin bug-fixes only. Making SMA work with the snap should of course be addressed, but not in the Delhi Release.

**Comment by anonymouse64** [comment]
@akramtexas so I see the current implementation as having the following bugs:
1. Using the SMA within the snap does not work at all with starting/stopping/restarting services
2. Errors are not checked within `InvokeOperation` and as such the response code returned to all clients is always 200
3. The code path for starting a service always hard codes calls to docker which in the best case may do nothing and in the worst case may end up inadvertently killing the service due to snap confinement not allowing calls out to docker installed on the host
4. The code path for restarting the docker case is implemented incorrectly, where `InvokeOperation` is called for stop, then called for start rather than calling InvokeOperation once for RESTART. While this is incorrect from coding implementation, it is also a bug for the OS type, where it will attempt to call out to docker if a restart is issued when using `OperationType=os` which could introduce other problems.

While for the snap specifically we only care about 1, 2-4 are still in fact bugs with the current implementation and should be fixed. All of these issues are fixed in my branch, in addition to implementing the things that this issue is about.

**Comment by anonymouse64** [comment]
Also we have already decided that 1 is a blocker for Delhi, the only question I have now is how much of the other issues should be handled for Delhi as well. I think we should handle all of them because I've already written the code and it just needs to be reviewed.

**Comment by anonymouse64** [comment]
Note that I filed independent issues for all the things here and so now this issue is just about SMA supporting snap in general.

**Comment by akramtexas** [comment]
@anonymouse64 Did you want to keep this issue open for any `snap`-related work or should we close this issue?

**Comment by anonymouse64** [comment]
Let's just open a new issue, there's a lot of irrelevant context here now

**Comment by akramtexas** [comment]
The new issue opened by @anonymouse64 (to replace this issue) is the following: [Issue-1132](https://github.com/edgexfoundry/edgex-go/issues/1132)
