### ISSUE TITLE
Update version of go in the snap to 1.11.2

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#765]
In sync with #764, we should update the version of go used to build the services to 1.11.2.

**Comment by anonymouse64** [comment]
The snap build for this fails because we can't build vault with go version 1.11.2. The most recent version of vault is v1.0.2 (we are currently building vault version 0.10.2). A prerequisite for this is @https://github.com/edgexfoundry/security-secret-store/issues/53 

@alain2sf is it okay to upgrade the version of vault to 1.0.2?

**Comment by alain2sf** [comment]
@Ian Johnson The Docker Vault service uses the official HashiCorp image so we are not impacted by the Golang version, I understand for Snaps you build Vault from source then?

I’m currently testing the Vault version 1 and so far everything is fine, I should complete this task rapidly. It’s taking a bit more than expected as I wanted to try new features and also associate the upgrade with a bug fix in the vault-worker code. Obviously if needed I can dispatch these 2 tasks in 2 PR’s.

So then, should I first submit a PR for the ``security-secret-store`` repo with the compose file specifying Vault image 1.0.2 before you make the update for Snaps ? Or we can process in parallel ?

**Comment by anonymouse64** [comment]
@alain2sf Yes we build vault from source in the snap.

Since the snap packaging is in this (edgex-go) repo and the docker compose script is in the security-secret-store repo, we will need to have 2 PR's which I think we can do in parallel. Whenever you're done testing the 1.0 release of Vault just comment on this issue or the corresponding issue in security-secret-store and I'll open the PR for the snap. 

If there are new features in vault 1.0 that we will take advantage of in vault-worker, please let me know so I can test them in the snap to make sure they work properly.

**Comment by alain2sf** [comment]
Sure will do.

**Comment by alain2sf** [comment]
@anonymouse64 PR submitted. Vault 1.0.2 upgrade included.
https://github.com/edgexfoundry/security-secret-store/pull/58
