### ISSUE TITLE
SMA has duplicate, different code for restarting services

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#767]
For example, here in the handler function:

https://github.com/edgexfoundry/edgex-go/blob/2489ade220a8026f80aa49fac57b631cbb30c4f8/internal/system/agent/router.go#L70-L90

`InvokeOperation` is never called with the `action=RESTART`, and instead just manually calls `InvokeOperation` is called with `action=STOP` and then again with `action=START`. This is wrong because the restart operation should be able to be implemented in a manner other than just issuing a stop and a start as there may be a more efficient implementation available (i.e. in the snap, one can just use one call of `snapctl`). This is also handled in `InvokeOperation` already: 

https://github.com/edgexfoundry/edgex-go/blob/2489ade220a8026f80aa49fac57b631cbb30c4f8/internal/system/agent/services.go#L117-L170

Additionally, there is a difference in the implementation between the two points, where `InvokeOperation` itself uses a sleep in between stopping and starting services using docker, where as the `operationHandler` has no such sleep.

**Comment by akramtexas** [comment]
> This is wrong because the restart operation should be able to be implemented in a manner other than just issuing a stop and a start as there may be a more efficient implementation available (i.e. in the snap, one can just use one call of `snapctl`).

`While I maintain the position—and I trust that you will appreciate that I'm not trying to be intransigent about it—that implementing a "restart" operation as a "stop" operation followed by a "start" operation is _not_ wrong, I am positively sympathetic  and receptive to an improved and superior implementation.`

**Comment by anonymouse64** [comment]
@akramtexas there are two problems here with having this duplicate code. 

1. The code path inside `InvokeOperation` is not ever used anywhere except inside `operationHandler`, which means that the code path inside `InvokeOperation` is _stale_ and not used or tested at all. This is bad coding practice to leave stale bits of code lying around. There also can never be an external consumer of the `InvokeOperation` function because it lives in an `internal/...` package and go disallows importing it anywhere except here.
2. There are in fact implementations of system management agents (in general) such as systemd, sys-v and others that are able to more efficiently implement a "restart" operation than by issuing a "Stop" and then a "Start". In fact with systemd (which is what snapd uses for the snap), you can in fact have configure different behavior between stopping a service and restarting a service. The whole thing can get extremely complicated with systemd service units having many different options. See for example the manual page for a service unit: http://manpages.ubuntu.com/manpages/bionic/man5/systemd.unit.5.html As such, the function `operationHandler` should abstract the details of how a "Restart" operation is handled to the `InvokeOperation` function, which itself should abstract the very specific details of a Restart operation to the individual implementation chosen/configured by the user, be it docker, snap, native, etc. If a particular implementation decides to just verbatim issue a "stop" then a "start", that's fine as that's the decision of the implementation. However the SMA should not force upon implementations a specific decision about _how_ to implement restarting a service.

Does that all make sense?

**Comment by akramtexas** [comment]
This is excellent and eminently insightful feedback, @anonymouse64. Much appreciated, thanks for making the time to share the insights 🆒

**Comment by akramtexas** [comment]
- The relevant source code has since then been heavily refactored to align. As such, this issue can be closed.
