### ISSUE TITLE
Using OperationType=os with the SMA results in docker commands being run for start/restart ops

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#768]
Setting `OperationsType = 'os'` in the configuration.toml for sys-mgmt-agent still results in docker commands being run. For example if one sends a POST to sys-mgmt-agent's `/api/v1/operation` to restart a service, then that service is killed using it's PID, but then immediately after that docker-compose is run to start up the equivalent service inside a container.

For example use:
```
curl --header "Content-Type: application/json" --request POST --data '{"action":"restart","services":["edgex-core-command"]}' localhost:48090/api/v1/operation
```

After running this, now edgex-core-command will be started from the docker compose file.

**Comment by akramtexas** [comment]
The option `OperationsType = 'os'` has since then been removed. This issue can be closed.
