### ISSUE TITLE
SMA should support disable/enable parameters for stop/start

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#770]
In addition to stopping, starting, and restarting services, sys-mgmt-agent should gain 2 new abilities for managing services:

* `enable` -> this turns a service persistently on, where the service will be brought up again after a reboot or update
* `disable` -> this turns a service persistently off, where the service will *not* be brought up again after a reboot or update

I don't know how this fits in with docker or native OS deployment, but this is easily supported in the snap, as snap services are implemented with systemd unit files and as such startup after updates or reboots.

**Comment by akramtexas** [comment]
This is a good-to-have enhancement. Given the (several other, separate) pressing issues and tasks to address, recommending that this issue be tagged for `Fuji` release.

**Comment by jpwhitemn** [comment]
We agreed in system management working group that enable/disable would be accomplished through parameters to the executors as it is not relevant to all type of implementations.  Closing for now and we can relook/reopen in Fuji if parameters don't work

**Comment by anonymouse64** [comment]
We should just re-use the same issue

**Comment by anonymouse64** [comment]
any status update on this @akramtexas or @jpwhitemn ?

**Comment by jpwhitemn** [comment]
Ian (@anonymouse64)  - I see that you reopened this and sorry I did not see that done in Feb.  AS we discussed this during a meeting with Tony present and I think this was resolved in that we decided that this would be internal to the executor working as it was not a universal need (system not every OS would have an ability to understand the persistently on idea).  

At the time Tony was ok with this decision.  I'll reopen the discussion at an upcoming system management meeting, but still considered this closed barring additional information from you and Tony (@tonyespy).
Jim

    On Monday, July 15, 2019, 8:02:56 PM CDT, Ian Johnson <notifications@github.com> wrote:  
 
 
any status update on this @akramtexas or @jpwhitemn ?

**Comment by anonymouse64** [comment]
I remember the discussion, the plan that I understood was that support for disabling or enabling services from the SMA would be implemented with parameters (and not have separate commands for disable/enable). My question was specifically about parameters - have they been implemented yet?

**Comment by jpwhitemn** [comment]
Ah - ok, yes we will add that to the to-do list and make sure this is in place for Fuji.  I'll coordinate with Akram and make sure we have a continual readout on this feature at the upcoming sys mgmt WG meetings.

    On Tuesday, July 16, 2019, 10:43:22 AM CDT, Ian Johnson <notifications@github.com> wrote:  
 
 
I remember the discussion, the plan that I understood was that support for disabling or enabling services from the SMA would be implemented with parameters (and not have separate commands for disable/enable). My question was specifically about parameters - have they been implemented yet?

**Comment by michaelestrin** [comment]
Looking at the history of this issue, I'm not clear on what is being requested here.

System agent exposes a single endpoint (/api/v1/operations) that passes whatever Operation.Action is provided in the request's POST body.

Does this implementation satisfy this issue's request?  If not, can you clarify what this issue is requesting?

@anonymouse64

**Comment by michaelestrin** [comment]
From a side conversation with @jpwhitemn:

> He wants parameter pass option in start/start/restart commands.  Parameters would be sent through to the executor (optional use - he would use them in snap implementation to provide enable/disable option described). On our side, the linux/docker executor would ignore them for now (could be handy in the future).

If that's the case, they're not currently supported. We unmarshal the POST body into an Operation struct that only includes Action (i.e. start, stop, restart) and a list of targeted services.

**Comment by anonymouse64** [comment]
@michaelestrin my original request was that we have separate actions/operations for enable and disable, but this was disregarded in favor of parameters. I'm not sure how the parameters work was supposed to work from a REST API point of view

**Comment by michaelestrin** [comment]
Would extending the Operation struct (which is what we're marshalling the request's POST body contents to) as follows...

```
type Operation struct {
	Action   string   `bson:"action" json:"action,omitempty"`
	Services []string `bson:"services,omitempty" json:"services,omitempty"`
        Parameters []string `json:"parameters,omitempty"`
}
```
...and passing those parameters across to the executor as-is satisfy this issue @anonymouse64?

**Comment by anonymouse64** [comment]
if the executor was executed with:

```
./executor ${service} ${action} ${parameters}
```

that would be enough for this. 

IIRC, the current mechanism is to execute the following for every service (individually):

```
./executor ${service} ${action}
```

Not sure how to do this if there is more than one service in a single call to the executor.

**Comment by anonymouse64** [comment]
I guess one thing that's missing from the implementation that @michaelestrin worked on is verification of the parameters, as is, it seems the code allows any parameters to be provided on the REST API and they are all passed verbatim to the executor. This could be an avenue for privilege escalation, especially considering the docker executor has full control over the docker socket. I'd like to request that a new issue be filed for validation of the provided parameters. Probably just enable/disable are okay for now for parameters.

**Comment by michaelestrin** [comment]
By definition, parameters are passed through the agent to an executor as-is without verification.  They are specific to a given executor instance and not universal.  For our example Docker executor implementation, you are correct in the additional parameters are passed to the docker command.  Instead of dealing with this through validation in the agent (which does nothing to limit the exposure  in the executor), I'd propose we leave it to the executor to validate and ignore incoming parameters based on the requirements of its specific implementation.  

I do agree that this should be handled in a new issue.

What do you think @anonymouse64?

**Comment by anonymouse64** [comment]
> I do agree that this should be handled in a new issue.

yes let's move it to a new issue, I filed https://github.com/edgexfoundry/edgex-go/issues/1851
