### ISSUE TITLE
The implementation of SMA should use an interface to support start/stop/restart

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#771]
The current implementation of the sys-mgmt-agent is that it has a single interface `ExecutorClient` which is only used to stop services and not used for the other operations, which means for example, starting and restarting a service needs manual refactoring inside `InvokeOperation`, which is less than ideal. In the ideal case one should only need to update the code that supports choosing an implementation from `configuration.toml` and then also add the relevant go code to implement that option and not touch `InvokeOperation`.

**Comment by akramtexas** [comment]
- The relevant source code has since then been heavily refactored in this area to align. As such, recommending that this issue be closed.
