### ISSUE TITLE
Standardize Logging in the SMA

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#780]
The System Mgmt Agent should use the standard Logging Client that all EdgeX services use and not utilize log.Println or log.Printf. An example of how to accomplish this is provided here:

https://github.com/tsconn23/edgex-go/tree/issue_763_tsc

**Comment by akramtexas** [comment]
- The _one-and-only_ reason why Go's built-in (overly-rudimentary) logging (viz. log.Fatal()) was used in the first place has to do with how the package structuring that was not allowing the import of the clients/logging package.
- Looking forward to addressing this issue 👍
