### ISSUE TITLE
Deployment mechanism for SMA for Delhi

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#781]
This issue is to discuss deploying the sys-mgmt-agent for Delhi. From PR #763, there's an open question about how the sys-mgmt-agent should be deployed using docker.
To summarize the issue, when using docker as a deployment mechanism, sys-mgmt-agent needs to use docker-compose to manage the containers. However, currently nothing is done to actually run setup a Docker-in-Docker setup so running these docker-compose commands from inside the container, so all these docker commands fail when attempting to manage the other services. 
I see the following solutions to the problem:
* create proper Docker-in-Docker setup for the sys-mgmt-agent container.
This is so that a `docker` executable inside the sys-mgmt-agent container talks to the host system's docker socket and effectively can manage the host's containers from inside a container. This would be the preferable solution because then folks wanting to use docker for deploying EdgeX can still use the docker-compose file to run everything inside docker containers.
* run sys-mgmt-agent outside of a docker container. 
This makes it easier for sys-mgmt-agent to use the docker commands to manage containers, but presents significant difficulty in deployment for users, as now they have to handle where to get the binaries from other that DockerHub if sys-mgmt-agent isn't inside a container, and they also have to manage running it properly as a daemon on their own rather than letting docker-compose manage it.

**Comment by anonymouse64** [comment]
As per @tsconn23's input on #763 for Delhi, folks will need to run sys-mgmt-agent outside of a docker container for Delhi. As such, I still think it's relevant to ask how folks will be expected to run sys-mgmt-agent in this case? Minimally the documentation will need to be updated to reflect whatever deployment mechanism is chosen to run sys-mgmt-agent natively.
I imagine the simplest might be to provide a script which downloads the binary from the nexus and installs it on the user's $PATH in say `/usr/local/bin/edgex-sys-mgmt-agent` or the equivalent on Windows. Or possibly it is installed in `$GOPATH/bin` if the user has go installed on their system.

**Comment by akramtexas** [comment]
This has been addressed through the `Docker-in-Docker` layered image approach.
