### ISSUE TITLE
Abstraction Layer for Consul

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#797]
All of the services in the EdgeX eco-system rely heavily on Consul. We are currently importing and calling into the Consul libraries directly through [this client](https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/consul/client.go).

We need to create an abstraction layer for deployment scenarios where it is desirable to use another provider for Service Registry and Configuration (Spring, for example). 

Consul will most likely remain the EdgeX default solution, but a customer of EdgeX should be able to create their own type conforming to an interface which would allow the services to discover one another and obtain configuration from another source.

Responsibilities of the provider are pretty constrained so it might make sense in this case to have a single unified interface utilized throughout the project rather than the duck-typed methodology we've used for the data providers. Currently, these responsibilities are:
- Populate the remote Configuration server (config-seed)
- Obtain configuration information at startup (all services except config-seed)
- Refresh configuration information when something upstream changes (all services except config-seed)
- Refresh host/port information within service clients on a configured interval (all services except config-seed)
- Service Registration on bootstrap
- Health checks

**Comment by lenny-intel** [comment]
I see that the C SDK uses Consul, so this abstraction also needs to be in C?

**Comment by tsconn23** [comment]
No, that would be a separate effort. First priority is the edgex-go services.

**Comment by tsconn23** [comment]
Duplicate #1039.
