### ISSUE TITLE
/docs/support/logging/Ch-Logging.rst is in need of major update

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#803]
Architectural description (old Java) and how to use logging client are in need of updating.

**Comment by tsconn23** [comment]
I'm going to propose that this page be WAY simplified. In my opinion, it only needs to convey the architecture of the support-logging service at a very high level -- how it is used by other services, options related to persistence, how to use the client and configuration information. Stuff like the DataObjects and sequence diagrams should be dropped. That stuff changes all the time. We're making work for ourselves if we include that stuff IMHO.
