### ISSUE TITLE
/docs/support/scheduler/Ch-Scheduling.rst is in need of major update

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#804]
More content on how to use and what it does, what configuration to set is needed

**Comment by mhall119** [comment]
Can this issue be merged with #1000 ?

**Comment by xmlviking** [comment]
This should have been merged into the existing #1000 which has been completed :)

**Comment by xmlviking** [comment]
We will be closing this issue for now.  If any other documentation concerns come up we will address those with a new issue.  This issue was covered with #1000
