### ISSUE TITLE
Device Service documentation needs more content and major update

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#806]
Device Service documentation that starts here: https://docs.edgexfoundry.org/Ch-DeviceServices.html needs more content and major update for new SDKs (and removing old and complex java stuff).

**Comment by cloudxxx8** [comment]
The documents are provided:

- https://docs.edgexfoundry.org/Ch-GettingStartedSDK.html
- https://docs.edgexfoundry.org/Ch-ExamplesAddingModbusDevice.html
- https://docs.edgexfoundry.org/Ch-ExamplesAddingMQTTDevice.html
- https://docs.edgexfoundry.org/Ch-ExamplesRandomDeviceService.html

Thanks, @mhall119 

@jpwhitemn please see whether we can close this issue
