### ISSUE TITLE
The snap should be easier to use with HTTPS

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#808]
Currently in the snap, we create a Root Certificate Authority, then generate keys and self-sign them with this Root CA. In production this is bad practice, and we want to easily enable the following scenarios I think:

1. User provides their own certs that they were provided from some actually trusted CA. 
This case is straight forward, we would just need to drop the cert files in an appropriate place in `$SNAP_DATA` and then adjust all the `host = localhost` everywhere in the config files to instead use the hostname associated with the certs provided. I think we can get away with just having Kong use the certs and not need to upstream support for all the individual services using HTTPS directly.
2. User provides their own Root CA. 
This is similar to the above, but where a company may have their own company wide CA that is not in the global trust that they sign internal intranet certs with. Not totally clear we need to support this, as probably makes more sense in this case to just have the admin's generate the signed certs with their Root CA outside of the snap and then this turns into case 1.
3. Use LetsEncrypt and the ACME protocol to facilitate automatic certificate generation.
This would probably to the user look something like how the NextCloud snap works : https://github.com/nextcloud/nextcloud-snap/wiki/Enabling-HTTPS-(SSL,-TLS)

**Comment by tsconn23** [comment]
@anonymouse64 Is this still Edinburgh? If not, can you tag it for Fuji please?

**Comment by anonymouse64** [comment]
Another related point for this is to make the addresses that i.e. kong listens on configurable, as currently in the snap we just listen on `0.0.0.0` when some users may prefer to use only localhost for the admin interface for example.

**Comment by tonyespy** [comment]
@anonymouse64 The issue you've described is specific to the snap, but I suspect there are probably some related problems with the Docker approach as well. If so, just wondering if they should be captured here and/or in separate issue(s)?

**Comment by anonymouse64** [comment]
@tonyespy Yes this issue could be made more general to also apply to Docker, but arguably both Docker and the snap would benefit from the security services in general being easier to use with HTTPS

**Comment by anonymouse64** [comment]
This will happen as a part of i.e. #1926 and other related Geneva things and is being tracked there instead
