### ISSUE TITLE
Support CBOR - (Edinburgh Roadmap Item)

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#820]
EdgeX will support the ingestion, use and export of binary data in CBOR format. Device Services will be allowed to send binary data as part of the Event/Reading packages. Core and Export Services will be adapted to handle, persist, and route/send binary data as it does integer, float, and string data today. Incorporation of binary data will allow custom built local analytics to use the binary data to trigger actuation of devices.

**Comment by tsconn23** [comment]
Closing this as we aren't tracking anything against it. Issue has been elevated to a project board.
https://github.com/orgs/edgexfoundry/projects/21
