### ISSUE TITLE
Decouple EdgeX from MongoDB (Edinburgh Roadmap Item)

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#821]
EdgeX database-using services (Core Data, Metadata, Export Client, Logging, Notifications, and Scheduling) will be refactored to be more loosely coupled to the persistence mechanism (currently MongoDB). This will ease the use of alternative persistent stores and technology (such as streaming) in future implementations and even allow the project to select alternate or additional reference implementation databases in future releases.
Partially covered by #811

**Comment by tsconn23** [comment]
FYI this issue may get closed as the work is broken into smaller, more manageable chunks (such as issue #811)

**Comment by tsconn23** [comment]
Completed.
