### ISSUE TITLE
Device blacklist in metadata

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#826]
Metadata will include a new device blacklist (with associated management API).  This blacklist will allow devices to be excluded from automatic provisioning.  See related item in the Device Service SDK and DS Group Tasks.

**Comment by tsconn23** [comment]
@SteveOss I'm thinking this can be managed as a simple list of device names. When a device is deleted, it gets added to the blacklist. If someone tries to re-provision, the service can return a 400 Bad Request. Would that be suitable?

**Comment by SteveOss** [comment]
@tsconn23 Sounds good to me.

**Comment by jpwhitemn** [comment]
@SteveOss - considering the future, I am guessing we'll need to eventually support the idea of whitelist (as well as blacklist) for various reasons (not just for purposes of tracking deletes).  In particular, I am thinking about device provisioning concerns.  Given this, do we want to consider some of these issues when considering the lists?  simple list of device names may work today, but going forward, and as we think about more distributed EdgeX will this suffice?  OK with crawl being simple list, but think we forward think this a little bit and have in mind when/where additions are needed.

**Comment by SteveOss** [comment]
@jpwhitemn My general thoughts on all these sort of "identity" issues, are that everything should be
identified by a GUID, named labels (that may not be unique) can be added to make things more
understandable for a user, but all core identity should be GUID based. So I guess I would base black/white listing on this. Obviously each device service would be responsible for the GUID management of attached devices.

**Comment by tsconn23** [comment]
Retagging as Geneva since this is reliant on the Provision Watcher requirements currently being fleshed out by Device Service WG. API changes will be required that we are thinking will not be backward compatible.

**Comment by michaelestrin** [comment]
Updated labels.  This is part of dynamic device discovery that was committed to at the Geneva F2F.

**Comment by tonyespy** [comment]
@jpwhitemn Can this be considered done, as the ProvisionWatcher work has already been finished, and the blacklist (see ProvisionWatcher.BlockingIdentifiers) is already part of the model?

That said, wondering if we'll have time to address go-mode-core-contracts issue [#226](https://github.com/edgexfoundry/go-mod-core-contracts/issues/226) (embedded device profile and service).

**Comment by jpwhitemn** [comment]
I am ok with closing.  As for #226, I defer to the WG's working it as to whether we address this in Geneva or push.  Let's pick up the conversation on that issue.
