### ISSUE TITLE
SMA to collect CPU metrics (Edinburgh Roadmap Item)

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#832]
the System Management Agent and associated system management API will add the ability to track service CPU usage and metrics.

**Comment by anonymouse64** [comment]
Note that if https://bitbucket.org/bertimus9/systemstat is to be used for tracking memory usage, we will need to request additional permissions for the snap in order for the snap to be able to read `/proc/meminfo`. This will probably be added to `system-observe`, which we already use, but that's not totally clear right now.
