### ISSUE TITLE
make build issue

### ISSUE THREAD

**Issue by shangarnithi** [edgexfoundry/edgex-go#837]
~/go/src/github.com/edgexfoundry/edgex-go$ make build
CGO_ENABLED=0 go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=1.0.0" -o cmd/config-seed/config-seed ./cmd/config-seed
vendor/github.com/hashicorp/consul/api/api.go:5:2: cannot find package "context" in any of:
	/home/utx/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/hashicorp/consul/vendor/context (vendor tree)
	/home/utx/go/src/github.com/edgexfoundry/edgex-go/vendor/context
	/usr/lib/go/src/context (from $GOROOT)
	/home/utx/go/src/context (from $GOPATH)
Makefile:31: recipe for target 'cmd/config-seed/config-seed' failed
make: *** [cmd/config-seed/config-seed] Error 1

facing above issue , please assist on this

**Comment by tsconn23** [comment]
Looks like have something wrong with your Go installation. The context package is part of the runtime and is usually found at $GOROOT/src/context. You could also try a `make prepare` before running `make install` but if your Go install is hosed, you'll have other problems.

I'm closing this issue as it's not applicable to EdgeX. If you like you can try to get additional assistance on [Slack](https://edgexfoundry.slack.com/)

**Comment by anonymouse64** [comment]
I am guessing the issue here is not that the go installation is incorrect, but rather that the go version is too old. IIRC, master now expects to be built with go 1.10
