### ISSUE TITLE
When sending put command with an inexistent id to /reading of Core Data API, 404 should be returned

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#838]
OS version: ubuntu 16.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:
1. start up EdgeX
2. send a put command with an inexistent id to /reading of Core Data API
for example, with the following request URL and body:
```
Method: PUT
URL: http://localhost:48080/api/v1/reading
Body: 
{
    "id": "57e866d4e4b0ca8e6d73a412",
    "created": 1475227070170,
    "modified": 1475227070170,
    "origin": 1471806366619,
    "pushed": 0,
    "name": "co2",
    "value": "12"
 }
```

Actual results: Got returned http status code 409 Conflict
Expected results: Got returned http status code 404 NotFound
RAML: https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-data.raml#L331

**Comment by tsconn23** [comment]
Tested. Works as expected. Closing.
<img width="703" alt="screen shot 2019-02-14 at 5 57 50 pm" src="https://user-images.githubusercontent.com/1342980/52825390-253ac100-3082-11e9-80d3-09bebfe5f572.png">
