### ISSUE TITLE
When sending delete command with an inexistent id to /reading/id/{id} of Core Data API, 404 should be returned

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#839]
OS version: ubuntu 16.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. start up EdgeX
2. send delete command with an inexistent id to /reading/id/{id} of Core Data API
for example, with the following request URL:
`Method: DELETE`
`URL: http://localhost:48080/api/v1/reading/id/57e866d4e4b0ca8e6d73a412`

Actual results: Got returned http status code 503 Conflict
Expected results: Got returned http status code 404 NotFound
RAML: https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-data.raml#L401

**Comment by tsconn23** [comment]
Tested. Works as expected. Closing.
<img width="765" alt="screen shot 2019-02-14 at 5 56 30 pm" src="https://user-images.githubusercontent.com/1342980/52825343-f6bce600-3081-11e9-88b2-fad5d6ee3d24.png">
