### ISSUE TITLE
When sending delete command with an inexistent id to /valuedescriptor/id/{id} of Core Data API, 404 should be returned

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#840]
OS version: ubuntu 16.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. start up EdgeX
2. send delete command with an inexistent id to /reading/id/{id} of Core Data API
for example, with the following request url:
`Method: DELETE`
`URL: http://localhost:48080/api/v1/valuedescriptor/id/57e5036fe4b0f1b53f5340fe2`

Actual results: Got returned http status code 500 InternalServerError
Expected results:  Got returned http status code 404 NotFound
RAML: https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-data.raml#L707

**Comment by tsconn23** [comment]
Tested. Works as expected. Closing.
<img width="680" alt="screen shot 2019-02-14 at 5 55 18 pm" src="https://user-images.githubusercontent.com/1342980/52825300-cecd8280-3081-11e9-801a-121e74ae3d35.png">
