### ISSUE TITLE
When using Core Command API to update the device opState/adminState with an inexistent id(or name) , 404 should be returned

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#844]
OS version: ubuntu 16.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. start up EdgeX
2. send put command with an inexistent id(or name) to /device/{id}/adminstate/{adminState} of Core Command API
for example, with the following request URL:
`Method: PUT`
`URL: http://localhost:48082/api/v1/device/57f7937ae4AAAAe2d67c20b5/adminstate/LOCKED`

Actual results: Got returned http status code 500 InternalServerError
Expected results: Got returned http status code 404 NotFound

RAML: 

- https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-command.raml#L100
- https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-command.raml#L123
- https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-command.raml#L168
- https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-command.raml#L191

**Comment by brandonforster** [comment]
Fixed by PR#919
