### ISSUE TITLE
When sending get/put command with an inexistent id to /device/{id}/command/{commandId} of Core Command API, 404 should be returned

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#845]
OS version: ubuntu 16.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. start up EdgeX
2. send get/put command with an inexistent device id to /device/{id}/command/{commandId} of Core Command API
for example:
```
Method: GET
URL: http://localhost:48082/api/v1/device/57f7937ae4AAAAe2d67c20b5/command/57f5e11fe4b060e2071a5c00

Method: PUT 
URL: http://localhost:48082/api/v1/device/57f7937ae4AAAAe2d67c20b5/command/57f5e11fe4b060e2071a5c00
Body: {"temp":74}
```

Actual results: Got returned http status code 500 InternalServerError
Expected results: Got returned http status code 404 NotFound

RAML: 

- https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-command.raml#L75
- https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-command.raml#L59

**Comment by brandonforster** [comment]
Fixed by PR#919
