### ISSUE TITLE
When issuing GET command to a locked device, 423 should be returned

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#846]
OS version: ubuntu 16.04
EdgeX version: 1.0.0
Environment details: Docker container
Steps to reproduce:

1. start up EdgeX
2. send get command to /device/{id}/command/{commandId} of Core Command API
for example: `http://localhost:48082/api/v1/device/{deviceLockedId}/command/57f5e077e4b060e2071a5c36`

Actual results: Got returned http status code 502 BadGateway
Expected results: Got returned http status code 423 Locked

RAML: https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-command.raml#L61

**Comment by jdharms** [comment]
Resolved with #906
