### ISSUE TITLE
edgex-docker-launch.sh shebang points to (SHELL) but script has BASH syntax

### ISSUE THREAD

**Issue by daviur** [edgexfoundry/edgex-go#857]
Trying to build my own docker containers while following the README.md I got an error in the "sudo make run_docker". It appears to be because the shebang of edgex-docker-launch.sh points to SHELL (#!/bin/sh) but the script has BASH syntax on the if statements with "[[". Simply changing the shebang to "#!/usr/bin/env bash" fixed the issue.

**Comment by anonymouse64** [comment]
On Ubuntu, `/bin/sh` is a symlink to `dash` which is traditional posix `sh`
implementation and not bash.

**Comment by andresrinivasan** [comment]
Ah. So do we prefer a Posix script or can I create a dependency on bash?

**Comment by anonymouse64** [comment]
A dependency on bash is fine, a number of the snap specific scripts all use bash instead of posix sh.

**Comment by SteveOss** [comment]
As a general comment, unless there is a good reason not to, would always write sh scripts, as this maximises portability across Unix variants.

**Comment by anonymouse64** [comment]
Sure, I think this bug is about the fact that we have a `bash` script that declares itself as using `sh`.

**Comment by SteveOss** [comment]
Or, it could be a bug about a sh script that incorrectly uses bash syntax. Depends on how you look at it :)

**Comment by andresrinivasan** [comment]
I'm will update the script to be POSIX compliant for portability per @SteveOss.

**Comment by andresrinivasan** [comment]
Though @daviur I'm still concerned that you're invoking `make run_docker` as root. Is there a requirement on your side for root?

**Comment by daviur** [comment]
I'm running Ubuntu 18.04, and I tried both with root and non-root user with docker group. Same problem. 
Effectively, changing the script, SH did not handle "if [[ ]];" syntax. but it did handle "if [ ];". Also, reading about SH syntax it appears to be expected.

**Comment by daviur** [comment]
To clarify, my first intention was to run "make run_docker" as a non-root user with the docker group appended.
