### ISSUE TITLE
Missing leading slash in default schedule path

### ISSUE THREAD

**Issue by nfode** [edgexfoundry/edgex-go#873]
This is a about [this](http://edgex-core-data:48080api/v1/event/scrub) line in the scheduler docker config file.
The support-scheduler generates schedules from its config.
Currently:
```
 Path = 'api/v1/event/scrub'
```
This results in the following addressable path:
```
http://edgex-core-data:48080api/v1/event/scrub
```
Where clearly the slash after the port is missing.

Edit: Consul is disabled

**Comment by jduranf** [comment]
@nfode thanks! Created PR #875 in order to fix this.
