### ISSUE TITLE
Missing endpoint to delete old logs by age

### ISSUE THREAD

**Issue by nfode** [edgexfoundry/edgex-go#889]
The logging service is currently missing an endpoint to delete old logs by age.

Deleting logs by age is, for example, useful for schedules since there the end date can not be set dynamically.

I implemented a solution [here](https://github.com/nfode/edgex-go/commit/16adfc94d85117b8fcd74bf473765b739e1e441d).

Is it of your interest to add this upstream? Then I am going to open a PR.

**Comment by tsconn23** [comment]
This can already be accomplished like so:

DELETE http://localhost:48061/api/v1/logs/0/10000000000000

The solution linked above does the same
```
criteria.Start = 0
criteria.End = db.MakeTimestamp() - parsedAge
```
[Docs to existing endpoints](https://docs.edgexfoundry.org/support-logging.html#logs)

**Comment by nfode** [comment]
Thank you for your fast answer.

I do not really understand your solution.
The docs say 
```
end: required (number)
end date in long form
```

And if I got it right end is the time in milliseconds in since the unix epoch, so it is an fixed date?

But what if I want to delete logs that are older then 24h at any given time? I do not get either from the code and the docs how to accomplish that.

Sorry for bothering, if I just misunderstand the whole thing.

**Comment by tsconn23** [comment]
> And if I got it right end is the time in milliseconds in since the unix epoch, so it is an fixed date?
Yes, that's correct.

> But what if I want to delete logs that are older then 24h at any given time? I do not get either from the code and the docs how to accomplish that.

Then the caller of the API endpoint shown above would need to calculate the millisecond timestamp for 24 hours ago and pass it in the second param. The first param would be 0 signifying unix epoch.

**Comment by nfode** [comment]
> Then the caller of the API endpoint shown above would need to calculate the millisecond timestamp for 24 hours ago and pass it in the second param. The first param would be 0 signifying unix epoch.

Correct. 

But my problem was what if someone wants to use the edgex scheduler to delete old logs. 
Then calculating the millisecond timestamp for 24 hours ago does not work since I once create a addressable for an schedule event.
Therefore my implementation adds an endpoint that allows to pass the age as an argument.
If I send:

```
/logs/removeOld/age/86400000
```

This deletes everything older then 24H since 86400000 Milliseconds are 24H.

**Comment by tsconn23** [comment]
I see. I understand the use case now.

@xmlviking Do you have any thoughts on this?

**Comment by jduranf** [comment]
I agree with @nfode idea. Maybe a PR should be created with @nfode code, but also upgrading the raml API

**Comment by nfode** [comment]
@jduranf You mean the raml API docs? I can open a PR tomorrow to discuss what still has to be done.
What besides API doc is still missing are tests. I have to figure out how to mock the `db.MakeTimestamp()`.

**Comment by tsconn23** [comment]
Well, the other thing that needs to be done if we make this change is to update the blackbox tests. We are now requiring developers to align the blackbox tests with any API signature or behavior changes. 

Test definitions can be found here:
https://github.com/edgexfoundry/blackbox-testing

A video showing how to execute the tests locally can be found here:
https://www.youtube.com/watch?v=LQU0Xf6EN0U

**Comment by tsconn23** [comment]
Closing. This functionality was added.
https://github.com/edgexfoundry/edgex-go/commit/dca0e43e9ccbb8f25247522bae81327008cd5f0a
