### ISSUE TITLE
Source field in new go-kit log doesn't work properly

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#891]
This is how looks the source field:
```
level=INFO ts=2018-12-05T22:14:10.521941928Z source=<autogenerated>:1 msg="Service dependencies resolved..."
level=INFO ts=2018-12-05T22:14:10.557821039Z source=<autogenerated>:1 msg="Starting edgex-core-command 1.0.0 "
level=WARN ts=2018-12-05T22:14:21.85609384Z source=<autogenerated>:1 msg="terminating: interrupt"
```
If I change `log.Caller()` value to 6, instead of 5, the source field looks right:
```
level=INFO ts=2018-12-05T22:14:31.51180613Z source=main.go:56 msg="Service dependencies resolved..."
level=INFO ts=2018-12-05T22:14:31.538643221Z source=main.go:57 msg="Starting edgex-core-command 1.0.0 "
level=WARN ts=2018-12-05T22:14:41.791174783Z source=main.go:71 msg="terminating: interrupt"
```
Any idea why this is happening?

I'm using go 1.9.5 in an Ubuntu 16.04 machine (linux/amd64)

**Comment by jduranf** [comment]
OK, using go 1.10.5 and 1.11.2 works fine. So seems this issue was fixed in go 1.10.x.

[EdgeX documentation](https://github.com/edgexfoundry/edgex-go/blob/master/docs/getting-started/Ch-GettingStartedGoDevelopers.rst) recommends to use go 1.9. So, or this feature is disabled or the documentation is updated in order to recommend go 1.10 or newer.

Any thoughts?

**Comment by brandonforster** [comment]
We are going to update that as part of Edinburgh, right? I think the best thing to do here is update the doc and close the issue.

**Comment by tsconn23** [comment]
We are moving to 1.11.x for Edinburgh, so definitely upgrade for any work being done in master. I'm on 1.11.2 right now. The documentation will need to be changed for the Edinburgh release. Delhi is still 1.9.5.

**Comment by tsconn23** [comment]
Can we go ahead and close this issue then?

**Comment by jduranf** [comment]
Sure
