### ISSUE TITLE
CoreData fail to handle relationship between event and reading in Redis DB

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#896]
**OS version:** macos 10.14  
**EdgeX version:** delhi
**Environment details:** Docker container  
**Steps to reproduce:**

1.Start up EdgeX
2.Add new event

```
Method: POST
URL: http://localhost:48080/api/v1/event
Body:
{  
   "device":"luxmeter",
   "readings":[  
      {  
         "name":"luminousIntensity",
         "value":"12"
      },
      {  
         "name":"luminousIntensity",
         "value":"15"
      },
   ]
}
```

3.Delete a reading which belongs to the event

```
Method: DELETE
URL: http://localhost:48080/api/v1/reading/id/{{readingId}}
```

4.Query event

```
Method: GET
URL: http://localhost:48080/api/v1/event
```

**Actual results:** 
1.Http status code - 500 Internal Server Error
2.Error message - Document is corrupted

The issue is in the relationship handling between event and reading.  The deletion behavior of reading triggers this bug.

**Comment by jduranf** [comment]
This is related with #776.
Closing the issue as duplicated (please reopen if I'm wrong)
