### ISSUE TITLE
Implement support-notifications microservice in Go

### ISSUE THREAD

**Issue by drasko** [edgexfoundry/edgex-go#90]
https://github.com/edgexfoundry/support-notifications has to be rewritten in Go.

**Comment by jpwhitemn** [comment]
I am working on this task.  Please contact me if you want to assist, but  don't start your own without consulting me.  You can find progress here:  https://github.com/jpwhitemn/edgex-go/tree/notifications

**Comment by jpwhitemn** [comment]
Duplicate of #113.  Closing and attributing to California Dot Release.  Work near completion
