### ISSUE TITLE
Remove Support for Labels from Logging

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#904]
As discussed on the Core Working Group call (6-Dec-18) we will be removing functionality supporting "labels" from log entries. This is because there is nowhere in the current Go-based services that this field is used. Therefore the logic and APIs to support its use are just cruft.

It appears from preliminary review that changes will be contained to the support-logging service.

- Remove APIs which take labels as parameters
- Remove any persistence logic for labels
- Remove any parsing for queries or marshaling/unmarshaling dealing with labels.

Related blackbox test issue https://github.com/edgexfoundry/blackbox-testing/issues/112

**Comment by jduranf** [comment]
If it's fine, I will work on this issue
