### ISSUE TITLE
Missing Attributions.txt for Edinburgh

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#907]
Various services are missing their Attributions.txt files including `config-seed`, `export-client`, `export-distro`, `support-logging`, and `support-notifications`.

Additionally, the services with Attributions.txt have out-of-date attributions and don't include newer dependencies added to the project. They also don't contain _all_ of the dependencies, including dependencies of dependencies.

This is a blocker for Delhi.

**Comment by anonymouse64** [comment]
Also all of the Attribution.txt files inside `internal/...` are unnecessary as that code cannot be imported from anywhere outside of this repo. 

Additionally, I have checked and none of the code that we do export from `github.com/edgexfoundry/edgex-go/pkg/{clients,models}` imports the internal directory, so all of the dependencies pulled in from the `internal/...` directory just need to be referenced in the `cmd/.../Attribution.txt` files for all the services.

**Comment by anonymouse64** [comment]
Note that it doesn't appear as if the docker images contain the Attribution.txt. See:
```
$ mkdir core-config-seed-rootfs
$ docker pull edgexfoundry/docker-core-config-seed-go:0.7.1
0.7.1: Pulling from edgexfoundry/docker-core-config-seed-go
Digest: sha256:02a61ae965e8995b2dcc5c78026abd2be8afcb5a39714de3ea2452e67ed76353
Status: Image is up to date for edgexfoundry/docker-core-config-seed-go:0.7.1
$ id=$(docker create edgexfoundry/docker-core-config-seed-go:0.7.1)
$ docker export $id > img.tar
$ tar -xf img.tar -C core-config-seed-rootfs/
$ find core-config-seed-rootfs/ -iname "*license*"
core-config-seed-rootfs/usr/local/go/LICENSE
core-config-seed-rootfs/usr/local/go/src/cmd/vendor/github.com/google/pprof/LICENSE
core-config-seed-rootfs/usr/local/go/src/cmd/vendor/github.com/ianlancetaylor/demangle/LICENSE
$ find core-config-seed-rootfs/ -iname "*attribution*"
$ 
```
The only license files currently shipped with the docker image are from the actual go source code source trees. 

As I mentioned in my PR it's not clear to me how to include the Attribution.txt file into the docker image due to how the `COPY` works with the flags used as well as the `FROM scratch`. Perhaps @tsconn23 or @JPWKU can comment on how best to do this.

**Comment by tsconn23** [comment]
We'd probably just add a line like so to each docker file

`COPY --from=builder /go/src/github.com/edgexfoundry/edgex-go/cmd/core-data/Attribution.txt /Attribution.txt`

**Comment by anonymouse64** [comment]
Can you submit that PR or do you need me to? I think that the delhi docker images should be updated with this, not sure if that will happen automatically or if it needs a delhi build job triggered.

**Comment by tsconn23** [comment]
Currently, any update of the delhi images would require a 0.7.2 release. @jpwhitemn @JPWKU for visibility.

**Comment by tsconn23** [comment]
Is this an action that needs to be taken for Edinburgh?

**Comment by anonymouse64** [comment]
This still needs to be done, I have not done anything for this and all docker images are still not including their Attribution.txt files
