### ISSUE TITLE
SupportLogging fail to execute log's DELETE API which persistence is file

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#909]
Actually, all log's DELETE APIs will cause this error.

**OS version:** macos 10.14  
**EdgeX version:** delhi
**Environment details:** Docker container  
**Steps to reproduce:**

1.Start up EdgeX
2.Execute DELETE API

```
Method: DELETE
URL: http://localhost:48080/api/v1/logs/logLevels/{{loggingLevel}}/{{start}}/{{end}}
```

3.Check SupportLogging's console log and then it **will print error when logEntitys is empty**.

```
2018/12/08 06:05:38 http: panic serving 172.30.0.1:35294: runtime error: invalid memory address or nil pointer dereference

goroutine 574 \[running\]:

net/http.(*conn).serve.func1(0xc4201220a0)

/usr/local/go/src/net/http/server.go:1697 +0xd0

panic(0x75c720, 0x9a3650)

/usr/local/go/src/runtime/panic.go:491 +0x283

github.com/edgexfoundry/edgex-go/internal/support/logging.(*fileLog).remove(0xc420118c60, 0xc420042ad0, 0x1, 0x1, 0xc420042bb0, 0x1, 0x1, 0xc4200425d0, 0x1, 0x1, ...)

/go/src/github.com/edgexfoundry/edgex-go/internal/support/logging/file.go:104 +0x410

github.com/edgexfoundry/edgex-go/internal/support/logging.delLogs(0x979b00, 0xc42008e000, 0xc42012e200)

/go/src/github.com/edgexfoundry/edgex-go/internal/support/logging/server.go:193 +0xa4

net/http.HandlerFunc.ServeHTTP(0x7e0228, 0x979b00, 0xc42008e000, 0xc42012e200)

/usr/local/go/src/net/http/server.go:1918 +0x44

github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Route).serveMatchedRequest(0xc420123360, 0x979b00, 0xc42008e000, 0xc42012e100, 0xc420242360)

/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/helper_17.go:38 +0xcc

github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Route).parse(0xc420123360, 0x979b00, 0xc42008e000, 0xc42012e100, 0xc42012c400)

/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/route.go:148 +0x159

github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).parse(0xc42011e380, 0x979b00, 0xc42008e000, 0xc42012e100, 0xc42003dcf8)

/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/helper.go:22 +0xb9

github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).DefaultServe(0xc42011e380, 0x979b00, 0xc42008e000, 0xc42012e100)

/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/bone.go:54 +0x4d

github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).DefaultServe-fm(0x979b00, 0xc42008e000, 0xc42012e100)

/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/bone.go:40 +0x48

github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone.(*Mux).ServeHTTP(0xc42011e380, 0x979b00, 0xc42008e000, 0xc42012e100)

/go/src/github.com/edgexfoundry/edgex-go/vendor/github.com/go-zoo/bone/bone.go:73 +0x54

net/http.serverHandler.ServeHTTP(0xc420117930, 0x979b00, 0xc42008e000, 0xc42012e100)

/usr/local/go/src/net/http/server.go:2619 +0xb4

net/http.(*conn).serve(0xc4201220a0, 0x97a1c0, 0xc42011e200)

/usr/local/go/src/net/http/server.go:1801 +0x71d

created by net/http.(*Server).Serve

/usr/local/go/src/net/http/server.go:2720 +0x288

```

**Comment by weichou1229** [comment]
Yes, you're right. This is happening for DELETE APIs but only failed when log number is zero.
In the first picture, it is work but failed in the second picture.

<img width="778" alt="2018-12-10 8 53 25" src="https://user-images.githubusercontent.com/11187505/49705481-5f8a7b00-fc59-11e8-8306-ce04026cc749.png">
<img width="770" alt="2018-12-10 8 54 22" src="https://user-images.githubusercontent.com/11187505/49705483-60bba800-fc59-11e8-9a20-dede437c1d3d.png">

**Comment by tsconn23** [comment]
Per discussion in the Core WG calls, the solution here is going to be that the support-logging service will return an [HTTP 406](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406) when the service is configured to use "File" persistence and a queryable endpoint is called.

On the support-logging service, every endpoint except the following should be considered "queryable"
```
GET /logs
GET /logs/{limit}
```

Every DELETE endpoint currently requires some kind of query to obtain a set of messages for deletion. It's possible we may want to add a DELETE that purges everything and would be usable with file persistence. Otherwise, there will be no way to clean logs that are persisted to a file.

**Comment by jduranf** [comment]
@tsconn23 as a user of the "File" persistence, your proposed endpoints list is too much restrictive.
If it's fine, I can fix the issue detected by @weichou1229 and leave those endpoints:
```
GET /logs
GET /logs/{limit}
GET /{start}/{end}/{limit}

DELETE /{start}/{end}
DELETE /removeold/age/{age}
```
If trying to use another endpoint, the service will return HTTP 406.

**Comment by tsconn23** [comment]
@jduranf If I understand you correctly, you want to keep the following endpoints when the Persistence is set to `file`. 
```
GET /{start}/{end}/{limit}

DELETE /{start}/{end}
DELETE /removeold/age/{age}
```
But the underlying functionality of those endpoints is query driven, so what's your idea for doing this in a performant way using only one or more text log files? Do I misunderstand?

**Comment by jpwhitemn** [comment]
@weichou1229 @tsconn23 - can we either close this issue out or move it to Geneva?  Is it still being worked as it has an Edinburgh label?

**Comment by weichou1229** [comment]
If we need to keep this enhancement, I'm ok to move it to the Geneva release.

**Comment by michaelestrin** [comment]
Closed due to lack of activity.
