### ISSUE TITLE
Define public API for duplicated microservice endpoints behind reverse proxy

### ISSUE THREAD

**Issue by drasko** [edgexfoundry/edgex-go#91]
Some of the microservices have API endpoints with same REST path. Example: `/ping`.

When behind reverse proxy, a mapping is needed so that we can know which exactly service we address (i.e. are we hitting `export-client/ping` or `core-data/ping`).

Suggested mapping can be `/<service_name>/<api_ednpoint>` - for example `/export-client/ping`, but `Kong` (a reverse proxy and API gateway currently selected by Security WG) has also a method of passing this configuration to microservices via HTTP headers (might be impractical if we later want MQTT topics to map to HTTP URLs).

**Comment by tingyuz** [comment]
yes this can be closed as we are using the name of micro service as part of the url if the end user is requesting to access the resources, the approach is similar to what Drasko proposed in the previous comments.  E.g,  we need to use https://reverse_proxy:port/coredata/v1/api/ping to access the ping endpoint for core data.

**Comment by jpwhitemn** [comment]
Per Tingyu comment - closing
