### ISSUE TITLE
support-logging TestFileRemove tests fail under Windows

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#910]
Call to MoveFileEx() in C:/Go/src/internal/syscall/windows/syscall_windows.go:255 returns ERROR_ACCESS_DENIED.  

TestFileRemove() calls testPersistenceRemove() (src/github.com/edgexfoundry/edgex-go/internal/support/logging/persistence_test.go:180) .  testPersistenceRemove() calls 
fileLog.remove() (src/github.com/edgexfoundry/edgex-go/internal/support/logging/file.go:62).  fileLog.remove() calls os.Rename() (src/github.com/edgexfoundry/edgex-go/internal/support/logging/file.go:97).  os.Rename()'s implementation calls windows.Rename() which calls MoveFileEx().

While this is a Windows-specific issue, it's also related to the support-logging implementation.  Test code that creates, opens, and calls os.Rename() functions normally on Windows.

Test failure under Windows (run in GoLand):

![image](https://user-images.githubusercontent.com/464327/49735581-2f3cdf80-fc4d-11e8-8434-9e95fc7754d7.png)

**Comment by brandonforster** [comment]
@michaelestrin have you noticed this recently? Should this be scoped for Geneva or Hanoi?

**Comment by michaelestrin** [comment]
Still an issue (though fewer failures now than before).

![image](https://user-images.githubusercontent.com/464327/68697275-1b2bed00-0544-11ea-85dc-9a9f3aa70b63.png)

**Comment by akramtexas** [comment]
My DEV environment for EdgeX has been on a Mac, but I can set up a similar environment on my Windows machine and proceed from there.

**Comment by akramtexas** [comment]
I have installed the various needed software components (`GoLand`, `golang`, `edgex-go`, `Cygwin`, etc.) on my Windows machine and got past some log-in issues as well. Once I am able to recreate this issue, I will work on a fix.

**Comment by akramtexas** [comment]
Set up is nearly complete (the set up of `ZeroMQ` remains). Having returned after being out sick, I have resumed this work and am currently resolving the following build error, related to `ZeroMQ`, which I expect to get resolved once `ZeroMQ` has been successfully installed:
```
$ make build
CGO_ENABLED=0 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=master" -o cmd/config-seed/config-seed ./cmd/config-seed
CGO_ENABLED=0 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=master" -o cmd/core-metadata/core-metadata ./cmd/core-metadata
CGO_ENABLED=1 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/edgex-go.Version=master" -o cmd/core-data/core-data ./cmd/core-data
# github.com/pebbe/zmq4
exec: "gcc": executable file not found in %PATH%
make: *** [cmd/core-data/core-data] Error 2
```

**Comment by akramtexas** [comment]
- Having followed the instructions for [Setting up ZMQ to build on Windows](https://github.com/edgexfoundry/edgex-go/blob/master/ZMQWindows.md), the setup of `ZMQ` is failing consistently during Step-6 (with the error `fatal error: zmq.h: No such file or directory, compilation terminated`), when running the command `go get -v -x github.com/pebbe/zmq4` from a bash shell. The full output accompanying the error is:
```
Akram_Ahmad@W106Q42SN2 MINGW64 ~/go/src/github.com/edgexfoundry/edgex-go (master)
$ go get -v -x github.com/pebbe/zmq4
# get https://proxy.golang.org/github.com/pebbe/zmq4/@v/list
# get https://proxy.golang.org/github.com/pebbe/zmq4/@v/list: 200 OK (0.900s)
WORK=C:\Users\AKRAM_~1\AppData\Local\Temp\go-build334983982
github.com/pebbe/zmq4
mkdir -p $WORK\b001\
cd C:\Users\akram_ahmad\go\pkg\mod\github.com\pebbe\zmq4@v1.0.0
CGO_LDFLAGS='"-g" "-O2" "-LC:\\Users\\akram_ahmad\\go\\pkg\\mod\\github.com\\pebbe\\zmq4@v1.0.0\\usr\\local\\lib" "-lzmq"' "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe"
 -objdir "C:\\Users\\AKRAM_~1\\AppData\\Local\\Temp\\go-build334983982\\b001\\" -importpath github.com/pebbe/zmq4 -- -I "C:\\Users\\AKRAM_~1\\AppData\\Local\\Temp\\go
-build334983982\\b001\\" -g -O2 "-IC:\\Users\\akram_ahmad\\go\\pkg\\mod\\github.com\\pebbe\\zmq4@v1.0.0\\usr\\local\\include" "C:\\Users\\akram_ahmad\\go\\pkg\\mod\\g
ithub.com\\pebbe\\zmq4@v1.0.0\\auth.go" "C:\\Users\\akram_ahmad\\go\\pkg\\mod\\github.com\\pebbe\\zmq4@v1.0.0\\errors.go" "C:\\Users\\akram_ahmad\\go\\pkg\\mod\\githu
b.com\\pebbe\\zmq4@v1.0.0\\polling.go" "C:\\Users\\akram_ahmad\\go\\pkg\\mod\\github.com\\pebbe\\zmq4@v1.0.0\\socketget.go" "C:\\Users\\akram_ahmad\\go\\pkg\\mod\\git
hub.com\\pebbe\\zmq4@v1.0.0\\socketget_windows.go" "C:\\Users\\akram_ahmad\\go\\pkg\\mod\\github.com\\pebbe\\zmq4@v1.0.0\\socketset.go" "C:\\Users\\akram_ahmad\\go\\p
kg\\mod\\github.com\\pebbe\\zmq4@v1.0.0\\zmq4.go"
# github.com/pebbe/zmq4
..\..\..\..\pkg\mod\github.com\pebbe\zmq4@v1.0.0\auth.go:19:17: fatal error: zmq.h: No such file or directory
compilation terminated
```
- The issue evidently lies in the following area of ZMQ setup:
Note: As of Nov 2019, ZMQ 4.3.3 does not work and results in an error: https://github.com/pebbe/zmq4/issues/152/. 4.3.2 is recommended and tested on Win 10: https://ci.appveyor.com/project/zeromq/libzmq/builds/25882500/job/s2yhbnjrdouq5qnm/artifacts and https://github.com/zeromq/libzmq/tree/a84ffa12b2eb3569ced199660bac5ad128bff1f0.
- Noting that the version of ZMQ that used to work (according to the ZMQ setup doc) has been archived. It's artifacts are no longer available (Only most recent artifacts, going back 6 months, are available).

**Comment by akramtexas** [comment]
- Found the `ZMQ` 4.3.2 artifacts (not available at https://ci.appveyor.com/project/zeromq/libzmq), over at https://zeromq.org/download/#windows. 
- So for the related step (`Step-4`) to clone the source of ZMQ, and to ensure that it matches the version/commit I have downloaded, I will look in the source tree for a 4.3.2 tag.

**Comment by akramtexas** [comment]
- @rsdmike by the end of yesterday afternoon, having compared our notes (regarding the issue getting `ZMQ` to work on `Windows`), looks like we're both running into the same issue that is explained by the needed artifacts (referring to those mentioned in Setting up [ZMQ to build on Windows](https://github.com/edgexfoundry/edgex-go/blob/master/ZMQWindows.md)) no longer being available:
```
Note: As of Nov 2019, ZMQ 4.3.3 does not work and results in an error: https://github.com/pebbe/zmq4/issues/152/. 4.3.2 is recommended and tested on Win 10: https://ci.appveyor.com/project/zeromq/libzmq/builds/25882500/job/s2yhbnjrdouq5qnm/artifacts and https://github.com/zeromq/libzmq/tree/a84ffa12b2eb3569ced199660bac5ad128bff1f0.
```
- I am setting up `ZMQ` for the first time on a `Windows` machine (and running into this issue), while you haven't got the set up of `ZMQ` to work on your new machine, following those artifacts no longer being available.
- I will revisit this issue today and share any findings or breakthrough. Likewise, please keep me posted, thanks.

**Comment by akramtexas** [comment]
- Got `ZMQ` running (inferring that from the following output from running `core-data.exe`:

> PS C:\Users\akram_ahmad\go\src\github.com\edgexfoundry\edgex-go\cmd\core-data> .\core-data.exe
level=INFO ts=2020-02-20T17:14:41.9400168Z app=edgex-core-data source=file.go:53 msg="Loaded configuration from ./res/configuration.toml"
level=ERROR ts=2020-02-20T17:14:41.9410148Z app=edgex-core-data source=secret.go:58 msg="unable to parse secret store configuration: open /vault/config/assets/resp-init.json: The system cannot find the path specified."
PS C:\Users\akram_ahmad\go\src\github.com\edgexfoundry\edgex-go\cmd\core-data>

- The next step is to recreate the `blackbox-testing` test failure under Windows (run in GoLand).

**Comment by rsdmike** [comment]
You need to disable security with the ENV var to get rid of that error -- can look at the compose file in nightly non secty to see what it is

**Comment by akramtexas** [comment]
> You need to disable security with the ENV var to get rid of that error -- can look at the compose file in nightly non secty to see what it is

Thanks very much for your help, @rsdmike 👍

**Comment by akramtexas** [comment]
- On my Windows machine, `TestFileRemove` passes, as do all the other tests in `internal/support/logging/logger/file/file_test.go`.
![logging_file_test](https://user-images.githubusercontent.com/40174952/75194242-5f22b680-571d-11ea-9fb9-446131c026b2.JPG)

**Comment by michaelestrin** [comment]
Runs green for me.  Closing issue.

**Comment by akramtexas** [comment]
> Runs green for me. Closing issue.

Awesome ✅ Thanks for confirming 👍
