### ISSUE TITLE
CoreData fail to update event and reading

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#930]
**OS version:** macos 10.14  
**EdgeX version:** 1.0.0
**Environment details:** Docker container  
**Steps to reproduce:**

1.Start up EdgeX

2-1.Update event

```
Method: PUT
URL: http://localhost:48080/api/v1/event
Body:
{"id":"0874cf01-bbd4-4121-9020-d3e667665fd0","pushed":1471806399999}

Response:
ObjectIDs must be exactly 12 bytes long (got 0)
```

2-1.Update reading

```
Method: PUT
URL: http://localhost:48080/api/v1/reading
Body:
{
    "id": "8cf9858a-33d5-488d-b2ef-6ae8508f2ba6",
    "name": "ohm",
    "value": "6"
 }

Response:
ObjectIDs must be exactly 12 bytes long (got 0)
```

It seems core-data use Uuid instead of Id and then it shoud allow Id to be empty like valueDesvriptor's model.
[value_descriptor](https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/mongo/models/value_descriptor.go#L11)

**Comment by tsconn23** [comment]
This has been resolved due to the recent work in core-data (PR #1001 for example)
