### ISSUE TITLE
fix the license file in the base repos

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#945]
The Apache 2 License file has a Mainflux copyright where the template copyright should be.  Please replace line 179

Copyright 2015 Mainflux

With

Copyright [yyyy] [name of copyright owner]

**Comment by tsconn23** [comment]
@jpwhitemn The title says "base repos". Was this just for edgex-go or others as well? If edgex-go only, then we can close.

**Comment by jpwhitemn** [comment]
Yep - I put separate issues in for the rest.
