### ISSUE TITLE
"make docker" failing

### ISSUE THREAD

**Issue by daviur** [edgexfoundry/edgex-go#952]
To build the containers I am following the instructions on the README.md: run "make docker". It fails when building "docker/Dockerfile.export-client". 

Error:
`internal/pkg/config/loader.go:25:2: cannot find package "github.com/BurntSushi/toml" in any of:
        /usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
        /go/src/github.com/BurntSushi/toml (from $GOPATH)
internal/pkg/db/mongo/models/event.go:8:2: cannot find package "github.com/globalsign/mgo" in any of:
        /usr/local/go/src/github.com/globalsign/mgo (from $GOROOT)
        /go/src/github.com/globalsign/mgo (from $GOPATH)
pkg/models/addressable.go:23:2: cannot find package "github.com/globalsign/mgo/bson" in any of:
        /usr/local/go/src/github.com/globalsign/mgo/bson (from $GOROOT)
        /go/src/github.com/globalsign/mgo/bson (from $GOPATH)
pkg/clients/logging/logger.go:27:2: cannot find package "github.com/go-kit/kit/log" in any of:
        /usr/local/go/src/github.com/go-kit/kit/log (from $GOROOT)
        /go/src/github.com/go-kit/kit/log (from $GOPATH)
internal/export/client/registration.go:17:2: cannot find package "github.com/go-zoo/bone" in any of:
        /usr/local/go/src/github.com/go-zoo/bone (from $GOROOT)
        /go/src/github.com/go-zoo/bone (from $GOPATH)
internal/pkg/db/memory/data.go:19:2: cannot find package "github.com/google/uuid" in any of:
        /usr/local/go/src/github.com/google/uuid (from $GOROOT)
        /go/src/github.com/google/uuid (from $GOPATH)
internal/pkg/consul/client.go:19:2: cannot find package "github.com/hashicorp/consul/api" in any of:
        /usr/local/go/src/github.com/hashicorp/consul/api (from $GOROOT)
        /go/src/github.com/hashicorp/consul/api (from $GOPATH)
internal/pkg/consul/client.go:20:2: cannot find package "github.com/mitchellh/consulstructure" in any of:
        /usr/local/go/src/github.com/mitchellh/consulstructure (from $GOROOT)
        /go/src/github.com/mitchellh/consulstructure (from $GOPATH)
internal/pkg/db/mongo/models/action.go:19:2: cannot find package "github.com/pkg/errors" in any of:
        /usr/local/go/src/github.com/pkg/errors (from $GOROOT)
        /go/src/github.com/pkg/errors (from $GOPATH)
make: *** [Makefile:43: cmd/export-client/export-client] Error 1`

The only way I could make it work was by calling "make prepare" before "make docker". 
If this is expected, maybe it should be explicit on the README.md. 

Any insights?

**Comment by tsconn23** [comment]
Yes, you would need to run `make prepare` before `make docker`. If that's not explicit in the Readme, then an update to the content would be appropriate.

**Comment by jdharms** [comment]
Closed with #1068
