### ISSUE TITLE
Makefile does not pick HTTP_PROXY from env

### ISSUE THREAD

**Issue by daviur** [edgexfoundry/edgex-go#953]
I have been trying to build the containers using "make docker" but given the fact that I am in a Intranet behind a proxy it simply fails. The only solution I could find was to modify the Makefile by adding "--build-arg HTTP_PROXY=$(HTTP_PROXY)" to every "docker build".

Digging a little more on the error, I can see that "docker build" does get the proxy from the terminal but it doesn't pass it to any the internal commands in the Dockerfile.* scripts. For example, "RUN apk" fails because it doesn't get the proxy.

Docker documentation mentions that the "--build-arg" must be used to pass the proxy to the container been built. But this certainly requires to modify the Makefile.

Is there a better way to do this?

**Comment by rsdmike** [comment]
Hey there @daviur, I had the same issue. With Docker 17.07, you can configure the Docker client to pass proxy information to containers automatically. You just need to create/edit a file called `config.json` in `~/.docker/` and add  `proxies` property: 
```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://127.0.0.1:3001",
     "httpsProxy": "http://127.0.0.1:3002",
     "noProxy": "*.test.example.com,.example2.com"
   }
 }
}
```

This is separate from setting proxy for the Docker Daemon (i.e. pulling images) which is typically done with systemd.
