### ISSUE TITLE
Add "help" argument support to core services

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#96]
Provide verbiage w/r/t supported command line flags and their usage via ./service --help 

See 
https://stackoverflow.com/questions/23725924/can-gos-flag-package-print-usage or this: https://github.com/MainfluxLabs/fluxmq/blob/master/main.go

**Comment by drasko** [comment]
@tsconn23 yes, probably the best golang CLI library. We are using it in Mainflux CLI: https://github.com/mainflux/bashflux - you can take a look here: https://github.com/mainflux/bashflux/blob/master/bashflux.go

But for this solution it would be an overkill :).
