### ISSUE TITLE
Migrate Legacy Export/Support Services to Gorilla MUX

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#963]
Per issue #962 we want to standardize all services on Gorilla MUX [v1.6.2](https://github.com/gorilla/mux/releases/tag/v1.6.2) to enable capabilities planned for the new year. The current export-client/distro and support-logging/scheduler services use `github.com/go-zoo/bone` as their router and should be changed so that common patterns can be used across all services in the edgex-go repo.

**Comment by jduranf** [comment]
Currently support-logging and support-scheduler use `github.com/go-zoo/bone`. If I'm not wrong, they also should be migrated to Gorilla MUX.

**Comment by tsconn23** [comment]
Oh, right you are. I will modify the issues accordingly. Thanks.

**Comment by jduranf** [comment]
I will work on it

**Comment by tsconn23** [comment]
@jduranf Any progress on this? There are enhancements that are dependent on this effort and we'd like to get them scheduled.

**Comment by jduranf** [comment]
I finished this issue several days ago, but I'm waiting for #965 before creating the PR, as this PR it's also touching the same code. If you want, I can send the PR without waiting, but this will create some conflicts.
