### ISSUE TITLE
Query API with limit $n should return the latest $n records instead of the first $n records

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#966]
EdgeX version: master

Steps to reproduce:

1. Start up EdgeX with device-random
2. Invoke the core-data API to get the events limited to 10 records
http://localhost:48080/api/v1/event/device/Random-Integer-Generator01/10

Actual results:
The first 10 events are returned, so the result is always the same even if there are more new events received

Expected results:
The last 10 events are returned
The order is not defined in RAML, but users expect to get the latest ones.
https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-data.raml#L139

This issue could apply to all other query with limit argument.

**Comment by Quyrean** [comment]
I was able to duplicate this easily.  

I think the following reading call should match the event call.

```
/reading/device/{deviceId}/{limit}
```

There are several other reading calls that I am not sure about 

```
  /reading/name/{name}/device/{device}/{limit}: 
  /reading/name/{name}/{limit}: 
  /reading/uomlabel/{uomLabel}/{limit}: 
  /reading/label/{label}/{limit}: 
  /reading/type/{type}/{limit}: 
```
And these I would leave alone as they already specify start and end time

```
/event/{start}/{end}/{limit}: 
/reading/{start}/{end}/{limit}: 
```

**Comment by tsconn23** [comment]
Would suggest just addressing the endpoint mentioned in the issue for initial PR to keep things small. If  the solution is acceptable, then we can decide when to extrapolate to other endpoints. If we make changes to other endpoints, we'll probably do that all at once under the auspices of a more inclusive issue report.

**Comment by tsconn23** [comment]
No, as long as the changeset is small, it's fine.

**Comment by Quyrean** [comment]
Cool, actually I there are more documentation changes than actual code.

**Comment by tsconn23** [comment]
@cloudxxx8 FYI, there isn't an explicit specification of which field to use in addressing this issue -- created vs modified. Per the discussion on PR #1050 it makes sense to us that this would be sorted by `modified` as opposed to `created`. If you're not on board with that, let us know. Obviously, tests will need to align.

**Comment by jduranf** [comment]
It's possible, and usually happens, to have events (or other objects) without `modified` or `origin` time, but all events have `created` time, so I suggest to use the `created` time.

**Comment by tsconn23** [comment]
@jduranf The recent work on the Mongo persistence layer has standardized the handling of created and modified. Even if modified doesn't come in via the contract because it's empty, it will be set to equal the created value before being saved to the database.

**Comment by jduranf** [comment]
Thanks for the clarification @tsconn23. Then should be better to use `modified`
