### ISSUE TITLE
Config-seed: Remove support for population from *.properties files

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#968]
With the Edinburgh release, the config-seed will no longer support population of the Java device service configuration data via *.properties files.

Delete all folders from the config-seed/res/properties directory with the exception of 
- device-virtual 
- edgex-support-rulesengine

The above services require a replacement solution before we can remove the *.properties support entirely.

**Comment by anonymouse64** [comment]
This shouldn't be done until there are replacements for the current Java services, i.e. rules-engine and device-virtual I think. Or absent that, those services should be completely obsoleted.

**Comment by tsconn23** [comment]
Edited accordingly
