### ISSUE TITLE
Suggestion: Rename files in /docker to be [servicename].Dockerfile instead of Dockerfile.[servicename]

### ISSUE THREAD

**Issue by rsdmike** [edgexfoundry/edgex-go#981]
In working in an IDE like VSCode, the files in the docker directory aren't recognized as actual Dockerfiles by the editor given their file extension isn't .Dockerfile. Furthermore, they are not recognized as dockerfiles by the Docker extension thus preventing them from showing up in menu options to build with the IDE. It's a small thing for developer experience, but I'd be more then willing to help out in updating the names and makefiles. However, I'm not sure the impact it would have on CI/CD if any. 

![image](https://user-images.githubusercontent.com/22204562/50666560-9743c480-0f72-11e9-9c26-f353f3472076.png)

As a second thought, It might be a better idea yet to move the Dockerfiles into their respective cmd/ folders and simply call them "Dockerfile" which could potentially simplify any tooling such that the the filename would not need to be specified. 

Thoughts?

**Comment by tsconn23** [comment]
@rsdmike The top of line proposal is easy enough and will be self-contained to the edgex-go repo. The CI/CD pipeline simply calls `make docker` which is driven from the makefile. So if the filenames change and the make targets are updated, all should continue to work. We'll know quickly from the verify jobs if that's not the case.

I'm not sure of the benefit of the second thought. FWIW I use GoLand. Waiting to see if any other VSCode users out there chime in on this.

**Comment by andresrinivasan** [comment]
I solved the first problem by adding another file association to my VSC `settings.json` as this is an issue with other projects I am working with:

```json
"files.associations": {
        "Dockerfile.*": "dockerfile"
    }
```

I'm not a huge fan of creating a directory for a single file.

**Comment by jpwhitemn** [comment]
Agree with Andre on this.  That is what file association preferences in any IDE are about.  As soon as we change it to meet the default for one IDE, it will run counter to the default of another IDE.  Not in favor of making changes unless there appears to be a bigger benefit.  

Mike, thanks for your suggestion and if you still feel this is needed, I'd encourage you to make your case on a broader context and let us get input from DevOps working group chair on impact.


    On Thursday, January 3, 2019, 5:54:59 PM CST, André Srinivasan <notifications@github.com> wrote:  
 
 
I solved the first problem by adding another file association to my VSC settings.json as this is an issue with other projects I am working with:
"files.associations": {
        "Dockerfile.*": "dockerfile"
    }
I'm not a huge fan of creating a directory for a single file.

**Comment by SteveOss** [comment]
As a counter example the docker plugin for Intellij recognises Dockerfile.xxx as a docker file.

**Comment by tsconn23** [comment]
> As a counter example the docker plugin for Intellij recognises Dockerfile.xxx as a docker file.

This is probably why I haven't noticed an issue in GoLand then since it's effectively IntelliJ.

**Comment by andresrinivasan** [comment]
@rsdmike, thanks for the clarification and I apologize for being dense.

I don't have an issue with configuring the IDE to recognize `Dockerfile.foo` and would prefer that naming pattern over `foo.Dockerfile`.

What does resonate with me is the point Docker has recommended calling the file `Dockerfile` and placing them in the folder where `main.go` lives.
