### ISSUE TITLE
Re-implement rules engine (or pick new) in Go or other language

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#99]
Re-implement the rules engine (currently written in Java using Drools) in Go.  Alternatively, pick a package and language implementation that offers the same or similar capability but in a smaller footprint (memory, CPU), smaller executable size, and starts up faster than current Java implementation.

**Comment by drasko** [comment]
Current candidate: https://github.com/Comcast/rulio

If considering implementation, Mainflux rules engine can be a good start: https://github.com/MainfluxLabs/rules-engine

**Comment by jpwhitemn** [comment]
In addition to those above, also looking at https://github.com/hopkinsth/go-ruler, https://github.com/huttotw/grules, https://github.com/myntra/roulette, https://github.com/zhouzhuojie/conditions, https://github.com/utk1369/infer-go.  May expand to other languages with small footprint, and option to use something like NodeRed

**Comment by jpwhitemn** [comment]
Also explore C-based, RUST or other small and compiled rules engines
http://www.clipsrules.net/
https://sourceforge.net/projects/clipsrules/

**Comment by slightcycle** [comment]
How about using the softplc to implement the rules engine? I have tried this way to implement rules engine on stm32-chip, and I use the lua script to store the rules. CPU just uses the rules engine to execute the script. Here is a website for demo(in c++ language):https://github.com/wditch/plcLib

**Comment by SteveOss** [comment]
@slightcycle Agree that simply supporting a suitable scripting language (lua is a good candidate here), is a nice solution.

**Comment by jpwhitemn** [comment]
Also exploring JSON Logic as suggested by @andresrinivasan

**Comment by AnthonyMBonafide** [comment]
While doing some research into the various tools that are available, I had a crazy thought I wanted to get out there. Would we be able to introduce Functions as a service(FaaS) here to accomplish what we need? My initial thought is that going this route could possibly give us more flexibility as far as the language(s) and possibly runtime which the logic/rules are operating under. This is a crazy idea since we are planning to go the opposite direction with footprint size as this would most likely add to the size of the system and needed resources. Any thoughts to my madness?

**Comment by jpwhitemn** [comment]
James - FaaS was part of the consideration for application services.  Current Application Functions SDK is based on the idea (but the existing form) of FaaS.  From my perspective and based on the decision made for application services - not there yet and not edge ready (size, server, etc.).  Having said that, I am always open to a Missouri approach - "show me"

    On Friday, June 14, 2019, 9:01:35 AM CDT, Anthony M. Bonafide <notifications@github.com> wrote:  
 
 
While doing some research into the various tools that are available, I had a crazy thought I wanted to get out there. Would we be able to introduce Functions as a service(FaaS) here to accomplish what we need? My initial thought is that going this route could possibly give us more flexibility as far as the language(s) and possibly runtime which the logic/rules are operating under. This is a crazy idea since we are planning to go the opposite direction with footprint size as this would most likely add to the size of the system and needed resources. Any thoughts to my madness?

**Comment by michaelestrin** [comment]
Closing this issue.  Applications WG is taking on rules engine replacement.  See https://github.com/edgexfoundry/app-functions-sdk-go/issues/252
